### ISSUE TITLE
how to use Token refresh in L5

### ISSUE THREAD

**Issue by ykenny** [tymondesigns/jwt-auth#101]
when i got tips it says "token expire" , how can i refresh and got new token?
 i have been use JWTAuth::refresh($oldToken) but it doesn't work .

**Comment by jfadich** [comment]
This is an issue with the package. In the refresh method when decode is called the token is validated automatically, but the refreshFlow defaults to false so a token expiration exception is thrown. 

I submitted a pull request that fixes the issue. You can look at it and use the changes, or wait to see if the pull request is accepted.

**Comment by tymondesigns** [comment]
should be fixed as of `0.5.3`
