### ISSUE TITLE
Wiki documentation out of date.  Project dead?

### ISSUE THREAD

**Issue by RotateAt60MPH** [tymondesigns/jwt-auth#1011]
Can anyone tell me what the vintage of the documentation is?  I can't seem to do anything useful with JWT since I cannot even get the sample code snippets to work (yet).

**Comment by didadan** [comment]
Also the vendor publish command in the installation instructions dont seem to do anything. There are over 200 open issues, is this abandoned?

**Comment by RotateAt60MPH** [comment]
Sure as heck seems like that to me...

**Comment by didadan** [comment]
Well, there are recent commits and I guess Laravel 5.4 compatibility is still in progress. What version do you use?

**Comment by didadan** [comment]
And what exactly doesnt work for you?

**Comment by RotateAt60MPH** [comment]
For me, it's that JWTAuth::encode does not appear to exist anymore, per the samples for creating a token.

**Comment by didadan** [comment]
Which Laravel version are you running?

**Comment by didadan** [comment]
This worked for me:
`$token = JWTAuth::fromUser($user);
return response()->json(compact('token'));
`
