### ISSUE TITLE
Can I know the current valid tokens

### ISSUE THREAD

**Issue by abosami2000** [tymondesigns/jwt-auth#1012]
Hey ,

Are there a way to know all the valid tokens or how many users uses my app right now.

**Comment by kohenkatz** [comment]
No, the whole point of JWT is that it does not store this information on the server-side.  If you want to keep a list of logged-in users, you need to implement that yourself (or perhaps JWT is not the solution for your needs).

**Comment by ghost** [comment]
thanks @kohenkatz
