### ISSUE TITLE
Refresh Js permission Without Logout

### ISSUE THREAD

**Issue by meritlouka** [tymondesigns/jwt-auth#1016]
how  to refresh my menu par according to changed permissions  to current user immediately without logout while using entrust with "laravel"

**Comment by zRosenthal** [comment]
If I am understanding your question correctly, you want to automatically update your UI when a users permissions are changed?
If thats the case you can do this a few different ways.

1)
   * When a permissions for any user is changed you can add their user id to your cache
     * if using redis you can have a set of user ids for users whose permissions have been changed
   * Then you can set up middleware to check this set against the user making the request
     * If they are in the set then you can invalidate their token and issue them a new one
     * You can also attach an additional response parameter to tell the UI to update

2)
   * You can make use of Web sockets for real time communication between your server and client application

**Comment by meritlouka** [comment]
This is the case Thank you so much .
for the first solution i want to make sure i understand you well 
i will compare changed permission person id with logged in user id and if the same i will update his permission list in my ui (angular)
