### ISSUE TITLE
Get All active tokens [ Need help ]

### ISSUE THREAD

**Issue by DevYunus** [tymondesigns/jwt-auth#1023]
I have gone through documentation but i haven't found  method which return all active tokens . I need to implement invoking user token functionality. I can do it by managing tokens in database but i don't need that overhead . I am just a beginner in Laravel please give any valuable feedback .

**Comment by zRosenthal** [comment]
I don't believe you can. Tokens are only persisted (in cache) when they are blacklisted. Tokens are validated by checking there signature so it is not necessary to persist each token created.

If you want to revoke user token functionality (blacklist) you need to know the token. Im not sure what your use case is but it sounds like there is a better way to do what you are trying to do.

Idea: if you simply want to revoke a token for specific user, consider adding the user ids to cache or a database and create middleware to check each parsed token to see if that user needs to have their token blacklisted in which case you now have the token to black list. See #1016
