### ISSUE TITLE
Add a JwtCheck middleware

### ISSUE THREAD

**Issue by mmichaelbiz** [tymondesigns/jwt-auth#103]
Could be worth adding a JwtCheck middleware. This can be included on routes where you do not want to exclude guests so do not want to throw the exceptions if they are not authenticated, but want to handle some additional logic in the cases where an authenticated user is making the request.

Seeing as your authenticate function is already setting the Laravel authenticated user object, once this middleware has been added you will be able to use the non-session Laravel auth functions such as Auth::check(), Auth::User() and Auth::id().

Here is an example of one that I am currently using:

```php
<?php

namespace App\Http\Middleware;

class JwtCheck extends \Tymon\JWTAuth\Middleware\GetUserFromToken
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, \Closure $next)
    {
        if ($token = $this->auth->setRequest($request)->getToken()) {
            try {
                $this->auth->authenticate($token);
            } catch (\Exception $e) {
                unset($e);
            }
        }

        return $next($request);
    }
}

```

**Comment by tymondesigns** [comment]
Yea this is a good idea.. will look to add this soon

**Comment by mcblum** [comment]
This is great! Thanks @mmichaelbiz.

**Comment by mani95lisa** [comment]
@mmichaelbiz Hi, I'm new to Laravel and JwtAuth, could you please give me any informations about that? any demo or article is ok, thanks!

**Comment by mmichaelbiz** [comment]
sure @mani95lisa.

Check out Laravel's official docs on middleware here: http://laravel.com/docs/5.0/middleware

You can use this middleware code to to attempt to authenticate a user. If no valid JWT then it will ignore and continue as if the request was made by a 'guest' user.

If a valid JWT was passed with the request, for a given user the authenticated user object that Laravel uses will be set up, meaning that you can start to work with that user, using something like Auth::check(), Auth::User() and Auth::id().

It is basically a convenient way to handle authenticated user accessing areas of your webpage or app that are also available to guests.

Check this part of the Laravel official docs out for a little more info:
http://laravel.com/docs/5.0/authentication#retrieving-the-authenticated-user

I hope that helps. Good luck!

**Comment by mani95lisa** [comment]
@mmichaelbiz thanks!

**Comment by mani95lisa** [comment]
@mmichaelbiz I have learned everything about that now, but I have a little question : can I use `JWTAuth::attempt` without password? It seems that function is provided by a Provider, but I don't know how to change that. If you know that, please let me know, thanks!

**Comment by tymondesigns** [comment]
done :) 0b9060d86cb11ec9fab9eb7987fcd1d39fbd0f53

**Comment by mmichaelbiz** [comment]
Sweet! Thanks Sean!
