### ISSUE TITLE
Not expiring token on Lumen 5.4

### ISSUE THREAD

**Issue by newkillerbeast2017** [tymondesigns/jwt-auth#1035]
In my Lumen 5.4 application, I am using JWT for Auth. However, I cannot expire tokens for some reason but rest all works fine.

Here is my code:

	class UserController extends Controller
	{
		protected $jwt;
		public function __construct(JWTAuth $jwt)
		{
        	$this->jwt = $jwt;
    	}
		
		public function LogoutUser(Request $request){
        	$token = $this->jwt->getToken();
		
        	if($this->jwt->invalidate($token)){
            	return response()->json([
               		'message' => 'User logged off successfully!'
            	], 200);
        	} else {
            	return response()->json([
               		'message' => 'Failed to logout user. Try again.'
                ], 500);
        	}
    	}
    }

I followed this tutorial to integrate JWT Auth in my application : [https://iwader.co.uk/post/tymon-jwt-auth-with-lumen-5-2][1] and in my `vendor/tymon/jwt-auth/config/config.php`, it show as enabled:

    'blacklist_enabled' => env('JWT_BLACKLIST_ENABLED', true),

  [1]: https://iwader.co.uk/post/tymon-jwt-auth-with-lumen-5-2

**Comment by catalinux** [comment]
Do you get any error? Blacklisting works with a memcached storage

**Comment by jubairsaidi** [comment]
Not sure if it's the same with Lumen but I use Auth::guard which exposes `$jwt->attempt($creds)` and `$jwt->logout(true)` where true forces invalidation of the token.

**Comment by newkillerbeast2017** [comment]
@jubairsaidi could you give an example on where and how to use auth guard?

**Comment by jubairsaidi** [comment]
I'm familiar with the Laravel way of doing it, but not Lumen.  a quick search for Lumen auth guard resulted in this https://github.com/arubacao/http-basic-auth-guard.

You should keep in mind though, using JWTAuth is what gets passed to Auth guard so you should be able to use the method directly.

**Comment by newkillerbeast2017** [comment]
@jubairsaidi thanks for your tips. However, I havnt used the same package but implemented something very similar. The config files and the service providers are typically equivalent. It doesn't give any errors on invalidating but the fact is the token is never invalidated. This thing has been driving me nuts.
