### ISSUE TITLE
JWT Refresh - old token not expiring

### ISSUE THREAD

**Issue by phpnets** [tymondesigns/jwt-auth#1036]
Hi, 
In my laravel 5.3 project, I have written my own middleware to check Authentication and a controller function to get refresh token (when ever we call). But recently I found the old token is not expiring even after the new token is generated. Please see my codes below:

Middleware:

```
<?php
namespace App\Http\Middleware;

use Closure;
use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;
use Tymon\JWTAuth\Exceptions\TokenExpiredException;

class JWTCustomAuth
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {

    try {

        if (! $user = JWTAuth::parseToken()->authenticate()) {
            return response()->json([
                    'status' => 'FAILURE',
                    'msg'    => 'User not found',
                    'data'   => [],
                ],404);
        }

        } catch (TokenExpiredException $e) {

            return response()->json([
                    'status' => 'FAILURE',
                    'msg'    => 'Token expired',
                    'data'   => [],
                ], $e->getStatusCode());

        } catch (TokenInvalidException $e) {

            return response()->json([
                    'status' => 'FAILURE',
                    'msg'    => 'Token invalid',
                    'data'   => [],
                ], $e->getStatusCode());
 
        } catch (JWTException $e) {

            return response()->json([
                    'status' => 'FAILURE',
                    'msg'    => 'Token absent',
                    'data'   => [],
                ], $e->getStatusCode());

        }

        return $next($request);
    }
}
```

I have written a function in my controller to manually refresh the token when ever required. Please see the code:

```
use Tymon\JWTAuth\Exceptions\JWTException;
use Tymon\JWTAuth\Exceptions\TokenExpiredException;

 public function refreshToken()
    {
     
        $token = JWTAuth::getToken();

        if(!$token){
            return response()->json([
                'status' => 'FAILURE',
                'msg'    => 'Token not provided',
                   
            ], 400);

        }

        try{

            $newToken = JWTAuth::refresh($token);

        }
        catch(TokenExpiredException $e){
             return response()->json([
                'status' => 'FAILURE',
                'msg'    => 'Token is expired',
            ], 400);
        }catch(JWTException  $e){
             return response()->json([
                'status' => 'FAILURE',
                'msg'    => 'Token is invalid',
            ], 400);

        }
        return response()->json([
                'status' => 'SUCCESS',
                'msg'    => 'New token created successfully',
                'data'   => [
                    'token' => $newToken,
                ]
                    
            ]);
    }
```

Everything works fine but the old token still valid even after the new token is generated. I haven't changed any thing in the JWT/config.php. But I have changed .env file's CACHE_DRIVER = array for another requirement (Entrust Acl). But I have reverted and checked this. But the problem remains there.
Please share your ideas regarding this.
Thank you,
Harinarayanan T

**Comment by newkillerbeast2017** [comment]
@tymondesigns I have been experiencing the same problems as well. Old tokens are still valid after invalidating them.

**Comment by bernierayxu** [comment]
@phpnets @newkillerbeast2017 
I just had the same problem but finally work it out.

Change cache driver to file and you need to restart "php artisan serve" to make it listen again.
Then you'll be able to invalidate the token.

However, "Entrust" package requires "tagging" and make cache driver array. 

So the solution is to choose a different version of entrust

change your composer as follows:

"zizaco/entrust": "dev-master#6a0fd8c3b73037b4855c6c4eaf1060788c0df1e9"

you'll be able to have a version that works well with file cache driver.

**Comment by newkillerbeast2017** [comment]
So we need to change entrust version and use cache array to get it working?

**Comment by bernierayxu** [comment]
@newkillerbeast2017 I'm afraid so [face palm]

**Comment by isaackearl** [comment]
doesn't work for me, I'm still able to refresh blacklisted tokens...

**Comment by tymondesigns** [comment]
this should now be resolved as per recent fixes, Thanks guys

**Comment by newkillerbeast2017** [comment]
@tymondesigns I used beta 3 but still have to use `file` as the cache driver. Doesn't work with the default `array` cache driver.

**Comment by ittikorns** [comment]
I'm on the latest branch and experiencing the same problem. Manually refresh the token with default configuration doesn't invalidate the old token when cache driver is ARRAY. The only solution so far is to change the CACHE_DRIVE=file.

**Comment by n0490b** [comment]
I'm using Lumen 5.4 and the latest jwt-auth beta and I am experiencing the same problem. I have to change it to `file` to get it to work otherwise the token doesnt get blacklisted

**Comment by hari-web** [comment]
@tymondesigns  do we have any possible solution for this?

**Comment by darrynten** [comment]
This is a serious issue and it got closed?

It doesn't seem that the maintainers are very security conscious.

**Comment by tymondesigns** [comment]
You cannot use the array driver to blacklist tokens and expect the token to remain blacklisted across requests. It has no persistence, by definition.

@darrynten It was an issue, until it was fixed and closed. The only issue that is left here is that people are not using a persistent cache driver

**Comment by ye7iaserag** [comment]
I'm sorry but the bug still exists in rc1
I tested today, with cache driver file
The token gets added to the cache with expires in timestamp
Then it is removed from the cache the first time the refresh request is made
So the first time it will say token is invalid then the cache gets removed an viola, it's working again in the next refresh

How to repeat:
1- get a token issued
2- make sure the token expired and the grace period has ended
3- hit the refresh route, it will return invalid token
then the cache file gets deleted and the next refresh request will return a token
even though the token is expired and invalidated

**Comment by tarekbazine** [comment]
I'm on the 1.0.0-rc.2 version (caching in file "CACHE_DRIVER=file") and the bug still exists!

**Comment by tarekbazine** [comment]
issue not solved yet @tymondesigns (plz don't close !)

**Comment by Mahfoud047** [comment]
**I'm using the 1.0.0-rc.2 version with Laravel 5.4 and CACHE_DRIVER is on file, The issue still exists, @tymondesigns would you please check it out?**

**Comment by alhajymoayed** [comment]
The issue still exists

**Comment by Paulalopesdeveloper** [comment]
Working for me:
JWTAuth::manager()->invalidate(new \Tymon\JWTAuth\Token($user->token), $forceForever = false);
