### ISSUE TITLE
for laravel 5.4 has bug

### ISSUE THREAD

**Issue by myprogo** [tymondesigns/jwt-auth#1042]
"message": "Class 'Tymon\\JWTAuth\\Providers\\JwtGuard' not found",
  "status_code": 500,

**Comment by mydisha** [comment]
same here, latests commit give jwt error
Class 'Tymon\JWTAuth\Providers\JwtGuard' not found",

**Comment by jhivan** [comment]
In `vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php`, add:
`use Tymon\JWTAuth\JWTGuard;`.

**Comment by tymondesigns** [comment]
This was introduced as part of #1039 and has now been fixed. Thanks for reporting
