### ISSUE TITLE
How I can change default App\User ?

### ISSUE THREAD

**Issue by tronghiep92** [tymondesigns/jwt-auth#1046]
Hi all,

I changed `config/jwt.php` but still was using the model set at` auth.php`.

I haved tried adding `Config::set('auth.providers.users.model', \MyCustom\User::class);` before
`JWTAuth::attempt` but when I using `JWTAuth::parseToken()->authenticate();` it working incorrect, query using the model set at `auth.php`?

Please help me? Thanks!!!

**Comment by jeffersonsouza** [comment]
Hi, @tronghiep92!

I had to change the user model in config/auth.php and config/jwt.php to get the stuff done.

The second file is generated when you run: 

`php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"`

Did you try that?

**Comment by maximenko** [comment]
Hi, please find or add this rows in your config/jwt.php:
    /*
    |--------------------------------------------------------------------------
    | User Model namespace
    |--------------------------------------------------------------------------
    |
    | Specify the full namespace to your User model.
    | e.g. 'Acme\Entities\User'
    |
    */

    'user' => 'App\Staff',
