### ISSUE TITLE
Error composer update

### ISSUE THREAD

**Issue by fredroo** [tymondesigns/jwt-auth#1051]
my composer.json

"tymondesigns/jwt-auth": "0.5.*"

show this error in composer update:

![image](https://cloud.githubusercontent.com/assets/6863089/24216844/81005754-0f1c-11e7-8bb6-c80a52de4795.png)

**Comment by fredroo** [comment]
@tymondesigns please help me

**Comment by ellisio** [comment]
Looks like you ran:

```
composer require tymondesigns/jwt-auth
```

When you should have ran:

```
composer require tymon/jwt-auth
```

**Comment by fredroo** [comment]
composer require tymon/jwt-auth
show this error
![image](https://cloud.githubusercontent.com/assets/6863089/24217767/bae886dc-0f1f-11e7-9e98-6a3cfb261418.png)

**Comment by fredroo** [comment]
solved: use this in my composer.json:
        "tymon/jwt-auth": "1.0.0-beta.2"
