### ISSUE TITLE
How to support clock skew among servers?

### ISSUE THREAD

**Issue by dmoreno** [tymondesigns/jwt-auth#1053]
I'm experiencing an issue due to an inevitable clock skew between servers. If I have 2 servers:

- First server receives login request and generates JWT token
- Second server receives next requests and responds with 'Invalid value provided for claim [iat]'. For this server, token has been generated one second in the future.

These servers are in a PaaS provider (Microsoft Azure) and I can not solve the clock skew issue. I think this case could be very frequent, not perfect synced clocks among servers. How can we use tymon/jwt-auth in this scenario?

[JWT RFC7519](https://tools.ietf.org/html/rfc7519) says:

> Implementers MAY provide for some small leeway, usually no more than a few minutes, to
   account for clock skew.

Could jwt-auth support any leeway while it checks 'isFuture' condition?

**Comment by tymondesigns** [comment]
This is a very good point.. I'll look into it

**Comment by dmoreno** [comment]
@tymondesigns, could you look into this issue? Any chance to have a leeway support in tymon/jwt-auth?

I think this would be a very relevant feature to get a greater scalability. We could stop using affinity cookies.

**Comment by askkaz** [comment]
+1

**Comment by tymondesigns** [comment]
@dmoreno I have added this functionality in - there is a new config option (so you will need to re-publish or copy it over). `JWT_LEEWAY`

https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php#L210

No release published yet though, just on `develop` atm

**Comment by dmoreno** [comment]
it sounds great! Thanks for your work @tymondesigns!

**Comment by cedricve** [comment]
Doesnt work for me, using latest version 1.0.2.
