### ISSUE TITLE
Interface 'Tymon\\JWTAuth\\Contracts\\JWTSubject' not found

### ISSUE THREAD

**Issue by anilskalyane** [tymondesigns/jwt-auth#1054]
Hi,

After installing the 0.5.10 version of jwt-auth in my Lumen 5.4 project.
I'm getting the below error
Interface 'Tymon\\JWTAuth\\Contracts\\JWTSubject' not found

my Auth controller:

use Illuminate\Auth\Authenticatable;
use Laravel\Lumen\Auth\Authorizable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Database\Eloquent\SoftDeletes;

//use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Users extends Model implements JWTSubject, AuthenticatableContract {

    use SoftDeletes,
        Authenticatable;

**Comment by kohenkatz** [comment]
You need to use the new v1.0.0 beta version in order to work with 5.4.

**Comment by anilskalyane** [comment]
It's resolved now.
@kohenkatz Thanks a lot for your reply :)

**Comment by tahiryasin** [comment]
@kohenkatz could you please explain how to install v1.0.0

**Comment by kohenkatz** [comment]
Update your `composer.json` with this dependency:

```
"tymon/jwt-auth": "^1.0.0-beta.3@dev"
```

**Comment by gopalkumar315** [comment]
@kohenkatz Thanks a lot
