### ISSUE TITLE
refresh ttl null in 

### ISSUE THREAD

**Issue by jake142** [tymondesigns/jwt-auth#1067]
Hi,

I have these settings in my cfg:

    'ttl' => env('JWT_TTL', 60),
    'refresh_ttl' => env('JWT_REFRESH_TTL', 20160),

And these in my .env (Laravel Lumen)

    JWT_TTL=60
    JWT_REFRESH_TTL=null

Even though I get "Token has expired" when I try to refresh a token with TTL>60

I use 1.0.0-beta.3

**Comment by newkillerbeast2017** [comment]
@tymondesigns facing the same issue after the new update. Was working in beta 2 previously.

**Comment by newkillerbeast2017** [comment]
@jake142 #340 solves the issue. I forgot about this. Might be worth mentioning in the wiki @tymondesigns

**Comment by Ore00** [comment]
Based on the previous comments, I'm thinking this can be closed.
@jake142 is this still a problem?

**Comment by Ore00** [comment]
@tymondesigns this should be closed?
