### ISSUE TITLE
Undefined index: model with multi-auth guards using version 1.0.0-beta.1

### ISSUE THREAD

**Issue by kofikwarteng** [tymondesigns/jwt-auth#1081]
Hello guys,

I have created 2 guards all using the JWT driver. One for called users and another called tutors. I am using Laravel 5.3. Authentication works perfectly with the users middleware when I declare it in my route like this and I am able to access protected routes using the token returned through authentication:
<pre>
 Route::group([
            'middleware' => 'auth:api',
        ], function () {
 //user protected routes go here
});
</pre>

This is how I have declared the tutor middleware route:
<pre>
 Route::group([
            'middleware' => 'auth:tutor',
        ], function () {
 //tutor protected routes go here
});
</pre>
When I use the tutor guard, authentication works perfectly and a token is returned to me, but anytime I try to use the token to make a request to a protected route, I get this error message:
<pre>
ErrorException in CreatesUserProviders.php line 65:
Undefined index: model
in CreatesUserProviders.php line 65
at HandleExceptions->handleError('8', 'Undefined index: model', '/home/vagrant/code/studiens/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php', '65', array('config' => array('driver' => 'eloquent', 'table' => 'App\Tutor'))) in CreatesUserProviders.php line 65
at AuthManager->createEloquentProvider(array('driver' => 'eloquent', 'table' => 'App\Tutor')) in CreatesUserProviders.php line 38
at AuthManager->createUserProvider('tutors') in AbstractServiceProvider.php line 79
at AbstractServiceProvider->Tymon\JWTAuth\Providers\{closure}(object(Application), 'tutor', array('driver' => 'jwt', 'provider' => 'tutors')) in AuthManager.php line 111
</pre>

What am i doing wrong?

Thanks in advance.

**Comment by kofikwarteng** [comment]
Is this project abandoned? Looks like no one is here to help. This looks like a bug that needs fixing.

**Comment by Aslam97** [comment]
U should check your guard in **config/auth.php** check the provider which is use for the table. here example
for **Model** `'administrators' => [
             'driver' => 'eloquent',
             'model' => App\Administrator::class,
         ],`
for table not use a model
`'administrators' => [
             'driver' => 'database',
             'table' => 'administrator',
         ],` 

I hope its help

**Comment by usafhassan** [comment]
Thank you so much @hafizu97 You saved my life 😀

**Comment by valdev-fs** [comment]
cool, u saved my time @hafizu97

**Comment by patelsumit5192** [comment]
Thank you so much @Aslam97. but i have one question why change to "eloquent" => 'database'
