### ISSUE TITLE
update install wiki

### ISSUE THREAD

**Issue by xcaptain** [tymondesigns/jwt-auth#1082]
[https://github.com/tymondesigns/jwt-auth/wiki/Installation](https://github.com/tymondesigns/jwt-auth/wiki/Installation) this wiki is outdated, I want to contribute but have no permission, so if anyone can update this?  Below are the changes.

use `php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"` instead `php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"`

use `php artisan jwt:secret` instead `php artisan jwt:generate`

**Comment by tymondesigns** [comment]
closing as the wiki is intended for v0.5.* only
