### ISSUE TITLE
Potential security breach in JWT validation using multiple User models

### ISSUE THREAD

**Issue by artalisa** [tymondesigns/jwt-auth#1083]
In current validation scheme for JWT only "sub" is used to validate JWT against particular User model (e.g. model primary key). So if model exists by primary key, then ticket is valid. However in situations, when project uses multiple Laravel Guards (e.g "web" and fore example "api"), developer is free to choose a different User model for each of Guards. However generated JWT for one Guard will be valid for another one =) (despite of different model usage) if model with same primary key exists. So assuming that "web" guard uses "user" model, and "api" guard uses some "apiUser" model. JWT generated for "web" guard user.id == 1, will also be valid for "api" guard apiUser.id == 1 which gives a potential security breach.
Proposal is to add "guard" param into JWT payload and validate it during "authenticate" stage against the current default guard.

**Comment by kevinvdburgt** [comment]
I can confirm this issue, the "sub" claim only contains an ID. (for example guards; `admin` and `user` using jwt).

Authenticated as an user (jwt claim)
```
{"iss":"http://localhost/api/auth/login","iat":1493003197,"exp":1493006797,"nbf":1493003197,"jti":"BZtPIwWUI9t4wMpj","sub":7}
```

```php
Auth::guard('admin')->user(); // Fetches the admin record with ID 7
Auth::guard('user')->user(); // Fetches the user record with ID 7
Auth::guard()->user(); // (results in a error, not sure why? Type error: Argument 1 passed to Tymon\JWTAuth\JWTGuard::setUser() must implement interface Illuminate\Contracts\Auth\Authenticatable, instance of Illuminate\Database\Eloquent\Collection given)
```

This might be as better option as @artalisa proposed.
```
{"iss":"http://localhost/api/auth/login","iat":1493003197,"exp":1493006797,"nbf":1493003197,"jti":"BZtPIwWUI9t4wMpj","sub":{"id":7,"guard":"user"}}
```

So the results are like: 
```php
Auth::guard('admin')->user(); // null
Auth::guard('user')->user(); // Fetches the user record with ID 7
Auth::guard()->user(); // Fetches the user record with ID 7
```

@tymondesigns your thoughts on this?

**Comment by Mando-Chris** [comment]
Just a note as to how we worked around this.  Added some middleware to our admin routes that changes the JWT secret. So tokens created for admin users and normal users are no longer interchangeable.

A quick fix for us.

**Comment by tradzero** [comment]
Sounds a big issue...

**Comment by tymondesigns** [comment]
Whoops forgot to close this... It was fixed a while ago, no issues anymore
