### ISSUE TITLE
[Help needed] Invalidate multiple Users tokens.

### ISSUE THREAD

**Issue by b12k** [tymondesigns/jwt-auth#1084]
Greetings!
First of all thanx for an awesome module!
I have a question:
How can I invalidate tokens of multiple users?
I have a collection of User entities and need to sign them off, and I found this part a bit tricky.
Plese advice me how can I do that.
Thanx in advance!

**Comment by b12k** [comment]
I need to use that to force other User to logout.
Is there any possibility to get all tokens issued for a specific user?
The User may be signed in at multiple devices - so multiple valid tokens are issued.
How can I invalidate that tokens?

**Comment by shingsoso** [comment]
Hi , Have you found any solution to achieve that ?

**Comment by b12k** [comment]
@shingsoso Hello, I solved this issue by migrating to Laravel Passport.
