### ISSUE TITLE
Where to put 'auth' => [ 'jwt' => 'Dingo\Api\Auth\Provider\JWT', ] Laravel 5.3

### ISSUE THREAD

**Issue by Drakota** [tymondesigns/jwt-auth#1089]
Hi,  right now I have this problem where I can generate a token just fine, but I get this message 
`Failed to authenticate because of bad credentials or an invalid authorization header.`
I searched a little and found out people got this problem fixed by adding 
`
'auth' => [
      'jwt' => 'Dingo\Api\Auth\Provider\JWT',
    ],
`
in config/api.php, but I don't have this file. 
I'm using Laravel 5.3
Thanks for helping.

**Comment by vishalVDevmurari** [comment]
Execute:
php artisan vendor:publish --provider="Dingo\Api\Provider\LaravelServiceProvider"

In config/api.php

'auth'=>[], Add ['jwt' => 'Dingo\Api\Auth\Provider\JWT'],

**Comment by tymondesigns** [comment]
This question belongs on dingo/api
