### ISSUE TITLE
Type error: Argument 1 passed to Tymon\JWTAuth\JWT::fromUser() must be an instance of Tymon\JWTAuth\Contracts\JWTSubject, instance of App\User given

### ISSUE THREAD

**Issue by pavinthan** [tymondesigns/jwt-auth#1094]
Type error: Argument 1 passed to Tymon\JWTAuth\JWT::fromUser() must be an instance of Tymon\JWTAuth\Contracts\JWTSubject, instance of App\User given

**Comment by amandiobm** [comment]
Hi there, i was having the same problem...

Reading along all the issues.... I found this [#860](https://github.com/tymondesigns/jwt-auth/issues/860).

Pretty nice tutorial... will save your day!

**Comment by sivakumarraju89** [comment]
you need to update the User Model.

Check the link
http://jwt-auth.readthedocs.io/en/docs/quick-start/#update-your-user-model

**Comment by zhekaus** [comment]
@sivakumarraju89 ,
I have updated User Model, however the same problem persists.

**Comment by marcellopato** [comment]
This works like a breeze! 

> http://jwt-auth.readthedocs.io/en/docs/quick-start/#update-your-user-model

DAMN! Suddenly it does not work anymore! ERROR!

 "message": "Call to undefined method Illuminate\\Auth\\TokenGuard::once()",

**Comment by leandroruel** [comment]
came here because of this error... what now?

edit: my bad, i forgot the: "implements JWTSubject" at User Model

`class User extends Authenticatable implements JWTSubject`

**Comment by Illusionist3886** [comment]
@leandroruel 
after doing that

`Interface 'App\JWTSubject' not found`

**Comment by kabelo2ka** [comment]
@Illusionist3886 
You should also import `JWTSubject` like so:

`use Tymon\JWTAuth\Contracts\JWTSubject;`

**Comment by vinpearl1508** [comment]
cc

**Comment by StevieDC** [comment]
I had to do this as well.
https://africalocals.com/?/question/375

**Comment by StevieDC** [comment]
In case it has gone ...

add the folowing 2 methods in your User model
 
/**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

**Comment by ardianzack** [comment]
> 
> 
> came here because of this error... what now?
> 
> edit: my bad, i forgot the: "implements JWTSubject" at User Model
> 
> `class User extends Authenticatable implements JWTSubject`

Work for me
Laravel version 5.7.28
"tymon/jwt-auth": "~1.0.0-rc.2"

**Comment by Yass-Gfx** [comment]
For Laravel above 5.4 
in my case i user laravel 7

# Install JWT package via composer
composer require tymon/jwt-auth

# Publish the config
php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"


# Generate secret key
php artisan jwt:secret

# Configure Auth guard inside the config/auth.php
'defaults' => [
        'guard' => 'api',    #use api as guard
        'passwords' => 'users',
    ],
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt',  #use jwt in the driver
            'provider' => 'users',
            'hash' => false,
        ],
    ],

# Update your User model

      use Tymon\JWTAuth\Contracts\JWTSubject;
#and add implements as this

       class User extends Authenticatable implements JWTSubject

then add those in the user model

public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }


that's all hope this helps

**Comment by afifalfiano** [comment]
> For Laravel above 5.4
> in my case i user laravel 7
> 
> # Install JWT package via composer
> composer require tymon/jwt-auth
> 
> # Publish the config
> php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"
> 
> # Generate secret key
> php artisan jwt:secret
> 
> # Configure Auth guard inside the config/auth.php
> 'defaults' => [
> 'guard' => 'api', #use api as guard
> 'passwords' => 'users',
> ],
> 'guards' => [
> 'web' => [
> 'driver' => 'session',
> 'provider' => 'users',
> ],
> 
> ```
>     'api' => [
>         'driver' => 'jwt',  #use jwt in the driver
>         'provider' => 'users',
>         'hash' => false,
>     ],
> ],
> ```
> 
> # Update your User model
> ```
>   use Tymon\JWTAuth\Contracts\JWTSubject;
> ```
> 
> #and add implements as this
> 
> ```
>    class User extends Authenticatable implements JWTSubject
> ```
> 
> then add those in the user model
> 
> public function getJWTIdentifier()
> {
> return $this->getKey();
> }
> 
> ```
> /**
>  * Return a key value array, containing any custom claims to be added to the JWT.
>  *
>  * @return array
>  */
> public function getJWTCustomClaims()
> {
>     return [];
> }
> ```
> 
> that's all hope this helps

this is helpful to me. Thanks

**Comment by menisha28** [comment]
This requires that the `User Model` implements this contract  in your model:

    use Tymon\JWTAuth\Contracts\JWTSubject;
    
    class User extends Model implements JWTSubject {


**Or**

 you have to update your `User model` to implement the `Tymon\JWTAuth\Contracts\JWTSubject` interface:

    use Tymon\JWTAuth\Contracts\JWTSubject;
    
    class User extends Model implements JWTSubject{
        /**
         * Get the identifier that will be stored in the subject claim of the JWT.
         *
         * @return mixed
         */
        public function getJWTIdentifier()
        {
            return $this->getKey();
        }
    
        /**
         * Return a key value array, containing any custom claims to be added to the JWT.
         *
         * @return array
         */
        public function getJWTCustomClaims()
        {
            return [];
        }
    }

**Comment by aminulemrul** [comment]
only add this line in user model
class User extends Authenticatable implements JWTSubject
