### ISSUE TITLE
Caching authentication in Redis

### ISSUE THREAD

**Issue by ftaurino** [tymondesigns/jwt-auth#1095]
Hi all,

We use this package without problems with Lumen, but -every- single request to the urls protected
with JWT authentication, generate a query to the user model, with a query like

"select * from "users" where "users"."id" = $1 limit 1"

It would be possible to instruct jwt to cache, say in Redis and with an appropriate key for every user,
this query result?

Many thanks,

Francesco

**Comment by mikemillers** [comment]
Had similar issue, you need to implement a custom user provider and add the cache to the retrieve functions of the \Illuminate\Contracts\Auth\UserProvider interface

**Comment by ftaurino** [comment]
thanks mike. and can you give me some hints on where to put the code?

**Comment by mikemillers** [comment]
Sure.. follow this to make your CustomUserProvider. 
https://laravel.com/docs/5.4/authentication#adding-custom-user-providers

Make your CustomUserProvider extend the out-of-the-box \Illuminate\Auth\EloquentUserProvider and override the retrieve functions to use whatever cache mechanism you like. 

eg something a bit like...

    class CustomUserProvider extends EloquentUserProvider{

         //stuff goes here          

        public function retrieveById($identifier)
        {
            return \Cache::remember('user:'.$identifier,5,function() use($identifier){
                    parent::retrieveById($identifier);
                 });
        }

        //more stuff here

    }

**Comment by amandiobm** [comment]
Theres a way to make this code to be part of this repository?? I guess this will be a good modification in performance.

**Comment by mehranhadidi** [comment]
hello guys, @ftaurino could you do that successfully ? i want to do the same. do you have any hints?

**Comment by ctf0** [comment]
another solution would be cacheing the user along with its token, this way u gain 2 things
1- no more duplicate tokens for the same user https://github.com/tymondesigns/jwt-auth/issues/1620
2- no need for custom logic

to make sure the cache expire same as the token, use the `JWT_TTL` env variable

**Comment by letmetodo** [comment]
@mikemillers can you give me a demo…… it too difficult... Thanks..
