### ISSUE TITLE
New version for Laravel 5.4

### ISSUE THREAD

**Issue by fredroo** [tymondesigns/jwt-auth#1099]
when new version compatible with laravel 5.4

0.5.* not work

**Comment by harkenn** [comment]
Looking at other tickets it looks like 5.* is supported but the installation instructions are wearily out of date.

**Comment by telmen** [comment]
I'm running on Laravel 5.4 and it works.

**Comment by fredroo** [comment]
@telmen how?

**Comment by telmen** [comment]
Just followed the instruction. Can you show me the code or error?

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/24837206/f007a2a6-1d04-11e7-84c2-e8a993f1d830.png)
@telmen look this print

**Comment by telmen** [comment]
Hmm, that's odd. Could you insert a package manually into composer.json and run composer install? 
![image](https://cloud.githubusercontent.com/assets/6022423/24837250/a48dc70e-1d6a-11e7-90dc-0a8ff27e00ae.png) this is my composer.json for now.

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/24837286/1cf9b6da-1d07-11e7-94c8-2aba8386e834.png)
my composer, but not work same erro phpseclib error

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/24837296/7181341c-1d07-11e7-9cbb-c1344ef334f6.png)
same error phpseclib

**Comment by fredroo** [comment]
@harkenn look

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/24837548/00d7fe70-1d0d-11e7-95f0-8756f10033cd.png)

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/24837555/10d64228-1d0d-11e7-99bb-a1fdff1753cd.png)

**Comment by fredroo** [comment]
"require": {
        "php": ">=5.6.4",
        "FortAwesome/Font-Awesome": "*",
        "barryvdh/laravel-cors": "^0.9.2",
        "laravel/framework": "5.4.*",
        "laravel/passport": "^2.0",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0",
        "phpseclib/phpseclib": "^2.0",
        "tymon/jwt-auth": "0.5.*"
    },
![image](https://cloud.githubusercontent.com/assets/6863089/24837618/875e5a88-1d0e-11e7-9536-3fc652e718ae.png)

@telmen

**Comment by fredroo** [comment]
last version from laravel/framework
last version from phpseclib/phpseclib

![image](https://cloud.githubusercontent.com/assets/6863089/24838189/633c7d8c-1d19-11e7-9cfa-add0b31786c3.png)

**Comment by fredroo** [comment]
@telmen look

use version: 
![image](https://cloud.githubusercontent.com/assets/6863089/24838331/8936a870-1d1c-11e7-8d0a-055ab920891b.png)

this error:

![image](https://cloud.githubusercontent.com/assets/6863089/24838313/5f895018-1d1c-11e7-8f58-c39159ef2477.png)

providers:
 Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,

aliases:
        'JWTAuth' => Tymon\JWTAuth\Facades\JWTAuth::class,
        'JWTFactory' => Tymon\JWTAuth\Facades\JWTFactory::class,

**Comment by fredroo** [comment]
version 0.5.* not install well

**Comment by tymondesigns** [comment]
fixed via `0.5.12`
