### ISSUE TITLE
How to post token ?

### ISSUE THREAD

**Issue by ykenny** [tymondesigns/jwt-auth#110]
when i use get method add token in url  , it work! 

but  when i use post method and  try to post token to route, it told me "Not allowed."

So, can you tell me what's wrong? Thanks!

**Comment by uberzhilkin** [comment]
Wonder if it is the same issue as mine: https://github.com/tymondesigns/jwt-auth/issues/109

What version of JWT-auth are you using?

**Comment by ykenny** [comment]
@uberzhilkin laravel5 and jwt-auth0.5.3

**Comment by uberzhilkin** [comment]
@ykenny I would suggest using a simple method of passing the token through the hidden field

```
{{ Form::open(['route'=>'named.route']) }}
{{ Form::hidden('token', 'IWOOFIWHIHGHG{KSDPF_token_value_AJFHOQFHOIQHFOIHSDF'); }}
{{ Form::close() }}
```

The token handling should take place at the dedicated 'named.route' controller function then.

**Comment by pfazzino** [comment]
Why would you pass the token in the form and not in the Authorization header?

**Comment by ykenny** [comment]
@pfazzino cause i haven't set virtual host, so ,should i set virtual host and retry it?

**Comment by pfazzino** [comment]
I'm not sure I understand the question regarding setting in virtual host. Are you referring to the mod_rewrite rule to pass the Authorization header to the php process?

**Comment by ykenny** [comment]
@pfazzino 
![d514e609-84a0-4f4e-9fe2-57a90b0992cf](https://cloud.githubusercontent.com/assets/3362710/7606793/a3f84fb4-f98e-11e4-92af-041b27633fbd.png)

I post them in header but it does't work?Do you know what's wrong?

**Comment by tymondesigns** [comment]
What server are you using here?

**Comment by ykenny** [comment]
@tymondesigns I use apache , so i have been try to add Rewrite rule in apache  httpd.conf , but after that i try to restart apache and it can not start , what is happened?
![3e4f1548-78b8-4c4e-90a1-f19d0ab7558e](https://cloud.githubusercontent.com/assets/3362710/7607632/85cb8f2c-f995-11e4-8cc0-b83eb1a55ab4.png)

**Comment by pfazzino** [comment]
Why do you have AllowOverride None?

**Comment by ykenny** [comment]
i try to delete AllowOverride None this line or modify AllowOverride  All , both doesn't work!

**Comment by ykenny** [comment]
@pfazzino i try to delete AllowOverride None this line or modify AllowOverride All , both doesn't work!

**Comment by tymondesigns** [comment]
Since this is an issue with your Apache configuration.. I would suggest also posting on stackoverflow or server fault.

**Comment by uberzhilkin** [comment]
@tymondesigns, hi Sean! Could you please take a look at my problem: https://github.com/tymondesigns/jwt-auth/issues/109 ?

Thank you!

**Comment by tymondesigns** [comment]
@uberzhilkin Yep, I will take a look at your issue as soon as I can! probably later today

**Comment by uberzhilkin** [comment]
@tymondesigns, very much appreciated, thank you!

**Comment by snRNA** [comment]
@ykenny  did you handled your problem? how to post the JWT token .I think I may face the problem same with you
