### ISSUE TITLE
Non expiring token till user logs out

### ISSUE THREAD

**Issue by telmen** [tymondesigns/jwt-auth#1107]
jwt-auth  "tymon/jwt-auth": "0.5.*"
laravel 5.4
In version 0.5.* how can I have non expiring token till users log out?

**Comment by telmen** [comment]
You mean JWT_TTL in .env file? There is no JWT_TTL in config/jwt.php. If you meant that, when I set TTL to null. Token became invalid right after authentication. Hmm. Which version do you use? 0.5*? Or

**Comment by kmrifat** [comment]
@telmen you may find `ttl="60"` in `config/jwt.php`  @akkhan20  just try to tell you to null JWT Token time limit(TTL) for non expiring token till user logs out.

> If you set TTL=null then token will never expire

**Comment by akkhan20** [comment]
@telmen you need to remove the variable 'exp' from required_claims too which saves the time when the token will expire if you don't remove that then your token will expire as soon as you create one.

**Comment by telmen** [comment]
It seems not working. When I set TTL to null, with or without 'exp' removed from required_claims, my token just expires as soon as I login.
``
'ttl' => null,
'required_claims' => ['iss', 'iat', 'nbf', 'sub', 'jti'],
``
this is my current config/jwt.php

**Comment by telmen** [comment]
Is there any additional configuration or did I mess up something else?

**Comment by akkhan20** [comment]
for me its like this in jwt.config 
`'ttl' => env('JWT_TTL', 60),`
`'required_claims' => ['iss', 'iat', 'nbf', 'sub', 'jti'],`
in .env
`JWT_TTL=60`

and it works fine

**Comment by telmen** [comment]
and you're on Laravel 5.4?

**Comment by akkhan20** [comment]
yes Laravel 5.4 and implemented in Lumen 5.4 too

**Comment by telmen** [comment]
and you followed the installation instruction? hmm

**Comment by akkhan20** [comment]
yes of course if it works with ttl=60 then there is no other issue then this.

**Comment by telmen** [comment]
Thanks but these didn't work. So I had to hard code the vendor, remove all 'exp' claims and token expired exceptions etc. Now it works.

**Comment by josuecamelo** [comment]
I solved the problem with a simple implementation.

https://github.com/josuecamelo/jwt-token-quase-eterno/blob/master/Implementacao.php

**Comment by webblufter** [comment]
That worked for me to set infinite time in Laravel 5..8 , change in **config > jwt.php**
// 'ttl' => env('JWT_TTL', 60),
'ttl' => env('JWT_TTL', **null**),
and
// 'required_claims' => [ 'iss', 'iat', 'nbf', 'sub', 'jti', **'exp'**, ],
'required_claims' => [ 'iss', 'iat', 'nbf', 'sub', 'jti', ],

**Comment by imranfareeth-acldigital** [comment]
vbfdggfgfdgd

**Comment by imranfareeth-acldigital** [comment]
Hi, am using lcobucci/jwt liabrarby using it is working for jwt token expiration but token refresh not working, any idea?
Versions:
"php": "^7.3|^8.1.5",
"lcobucci/jwt": "^3.4|4.1.5"
kindly support, thanks

**Comment by imranfareeth-acldigital** [comment]
Hi, am using lcobucci/jwt library using it is working for JWT token expiration but token refresh not working, any idea?
Versions:
"php": "^7.3|^8.1.5",
"lcobucci/jwt": "^3.4|4.1.5"
kindly support, thanks
