### ISSUE TITLE
Token will not expire when user is online

### ISSUE THREAD

**Issue by kmrifat** [tymondesigns/jwt-auth#1109]
Is that possible to to not expire token when user is online ? 
sometime token expire when user is online and sudden he feel he has been logged out.

Is there any way to extend token expire time by particular user last activity ?

**Comment by pankitgami** [comment]
You can increase your TTL or you can refresh the token at the specific interval.

**Comment by juanvillegas** [comment]
Just trigger an ajax ping to the server, that will refresh the token. The value you should look at is your _refresh_ttl_
