### ISSUE TITLE
Authorization Bearer  is not working

### ISSUE THREAD

**Issue by sandipsapkota1** [tymondesigns/jwt-auth#1111]
Hello, i setup with everything fine. Also works fine but , while requesting , Header Authorization and bearer with token key is not working.
I checked with Get method and , ?token=   URL works fine.
Why Header request not supported?

**Comment by pankitgami** [comment]
Please post your token and Request Header.

**Comment by sandipsapkota1** [comment]
Authorization    Bearer Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdFwvbDVcL2FwaVwvYXV0aGVudGljYXRlIiwiaWF0IjoxNDkyNDE5ODMyLCJleHAiOjE0OTI0MjcwMzIsIm5iZiI6MTQ5MjQxOTgzMiwianRpIjoiSnA5cGowR2pZTUdFZHE1YyJ9.rpoicp3nJimVErflmDIQwRfrsbAosJHX4jFB7Yj26lw

these are my token and request header.

**Comment by pankitgami** [comment]
>  Bearer Bearer 

You have bearer twice in the request header.

**Comment by sandipsapkota1** [comment]
Sorry, this was twice while posting in comment only, I am using it once and not working. 
Authorization Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdFwvbDVcL2FwaVwvYXV0aGVudGljYXRlIiwiaWF0IjoxNDkyNDE5ODMyLCJleHAiOjE0OTI0MjcwMzIsIm5iZiI6MTQ5MjQxOTgzMiwianRpIjoiSnA5cGowR2pZTUdFZHE1YyJ9.rpoicp3nJimVErflmDIQwRfrsbAosJHX4jFB7Yj26lw

**Comment by sandipsapkota1** [comment]
Key is ok, while but it throws, 401 unauthorized.

**Comment by pankitgami** [comment]
Are you using `FormRequest` ? If so check `authorize` function. If it is returning `false`. Change it to return `true`.

**Comment by sandipsapkota1** [comment]
Yes i am using authenticate function in laravel 5.4
```
public function authenticate()
    {
        $credentials = request()->only('email','password');
  try {
            $token = JWTAuth::attempt($credentials);
        if (!$token) {
                return response()->json(['error' => 'Invalid_Credientals_from'], 401);
            }
        }
        catch (JWTException $e) {
            return response()->json(['error' => 'something_is_went_wrong'], 500);
        }
        return response()->json(['token' => $token], 200);
    }
```

**Comment by sandipsapkota1** [comment]
this issue was due to , JWT key missing.

**Comment by milobluebell** [comment]
what? i saw you just said that your Key "is ok" in your comment on 17 Apr, so what's your meaning of "JWT key missing"? ( sry for my poor english:)

**Comment by milobluebell** [comment]
i have the same problems as this issue,but i have no idea how to fix this..

**Comment by milobluebell** [comment]
i fixed this problem with some native php codes,but i don't know if it is right or will causes some bugs in some other places . --- i modify the codes in authJWT.php on line.22 from `$user = JWTAuth::toUser($request->input('token'))` to `$user = JWTAuth::toUser(explode(" ",$request->header("authorization"))[1])`       AND my token info in my Request Headers is `Authorization:Bearer {token string}`
