### ISSUE TITLE
Refresh claims on PayloadFactory

### ISSUE THREAD

**Issue by shibby** [tymondesigns/jwt-auth#1118]
Hello,

I'm getting trouble with custom claims. If i generate more than one jwt token, each token gets previous one's claims too, if not overridden. Here is an example:

```php
$claims = ['foo' => 'bar'];
$payload = \JWTFactory::make($claims);
$token1 = \JWTAuth::encode($payload);
dump(\JWTAuth::getPayload($token1)); //this contains 'foo' key.

$claims = ['anotherkey' => 'anothervalue'];
$payload = \JWTFactory::make($claims);
$token2 = \JWTAuth::encode($payload);
dump(\JWTAuth::getPayload($token2)); //this contains both 'foo' and 'anotherkey' key.
```
What do i suggest? I've added refreshClaims() function. (Not tested)

```php
$payload = \JWTFactory::refreshClaims()->make($claims);
```
This removes all claims used before. I'm not sure should it be used in `make` function always. Or is it a good idea generating many token in one request.

**Comment by tymondesigns** [comment]
This has already been fixed on the upcoming release via a parameter - https://github.com/tymondesigns/jwt-auth/blob/develop/src/JWT.php#L94

I'm not accepting any non security patches to the current master branch.

Thanks though
