### ISSUE TITLE
Was tymon.jwt.valid event removed from v1.0.0?

### ISSUE THREAD

**Issue by diego-betalabs** [tymondesigns/jwt-auth#1121]
It was fired at Tymon\JWTAuth\Middleware\GetUserFromToken on v0.5.* but I can't find it in v1.0.0. It was permanent removed or was updated?

**Comment by akkhan20** [comment]
u can use Middleware\Authenticate instead

**Comment by tymondesigns** [comment]
Events are no longer fired in the new version as they are not necessary any more
