### ISSUE TITLE
Wiki Needs to be updated.

### ISSUE THREAD

**Issue by progammer-rkt** [tymondesigns/jwt-auth#1123]
Current service provider which we need to add in `config\app.php` as per wiki is : 

> 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider'

But the actual one working now is :

> Tymon\JWTAuth\Providers\LaravelServiceProvider::class

Similary, as per wiki, the token can be created by using the command

>  php artisan jwt:generate

But the actual command that works now is : 

> php artisan jwt:secret

Please note I am currently using the version : `1.0.0-beta.3`. 

So I request to kindly update wiki as per these working data.

**Comment by akkhan20** [comment]
the document refers to stable version and not beta version

**Comment by progammer-rkt** [comment]
@akkhan20 So do you mean it will use the same service provider and token generation command which are specified in wiki once it comes to a stable release ?

**Comment by akkhan20** [comment]
no i believe all those things will change according to the source code and may be 2 wikis for both the versions

**Comment by tymondesigns** [comment]
the wiki refers to the `0.5.*` releases. New documentation is coming that will be for the `1.0.*` release
