### ISSUE TITLE
JWTAuth::attempt($credentials, $customClaims) not works

### ISSUE THREAD

**Issue by gandra** [tymondesigns/jwt-auth#1125]
Accordiong to [docs](https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens) there is a second parameter where you can pass an array of custom claims. e.g.
```
$customClaims = ['foo' => 'bar', 'baz' => 'bob'];

JWTAuth::attempt($credentials, $customClaims);
// or
JWTAuth::fromUser($user, $customClaims);
```

I have tried and this not work as expectd. After decoding token back I can not find my custom claims. So I have checked [source code](https://github.com/tymondesigns/jwt-auth/blob/develop/src/JWTAuth.php) and there is no such method signature with method `attempt` accepting 2 params: `credentials` and `customClaims`. Instead there is `attempt` method with only 1 parameter - `credentials`:

```
public function attempt(array $credentials)
```

So,
is this documentation not accurate or what? How I can add custom claioms during authentication and later how I can retreive loggedin user and custom claims as well?

**Comment by akkhan20** [comment]
the document is for version 0.5 and i believe u got 1.0.0-beta-3

**Comment by gandra** [comment]
Thanks @akkhan20 !
You are right. In the version 0.5.11 there is a such method: [0.5.11/src/JWTAuth.php](https://github.com/tymondesigns/jwt-auth/blob/0.5.11/src/JWTAuth.php)
So in order to use this I have to downgarde it?
Why in newer version this functionality is revoked?

**Comment by gandra** [comment]
When trying top downgrade to ver 0.5.11 composer gives me error:
`Class 'Tymon\JWTAuth\Providers\LaravelServiceProvider' not found`

So now in v icious circles of version hell. Latest version do not have functionalites it claims to have on formal page. You count on that and then you are in problem.

**Comment by gandra** [comment]
I have found a way how to introduce custom claims. Via `JWTSubject` and `getJWTCustomClaims()`

**Comment by akkhan20** [comment]
i think this error
''Tymon\JWTAuth\Providers\LaravelServiceProvider' not found'
is because u have the service this service provider registered in app.php

**Comment by gandra** [comment]
Yes @akkhan20 ,
aftert switching to old version I forgot to publish conf:
```
php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
```

anyway I have found a way how to add custiom claims via `getJWTCustomClaims()` so I will close this issue.

**Comment by ThomasRalee** [comment]
@gandra 

would you mind sharing how did you add custom claims?

**Comment by fureszk** [comment]
@ThomasRalee 
Here is how you do it:

        $payload = JWTFactory::customClaims([
            'sub' => Auth::user()->email,
        ])->make();

        $token = JWTAuth::manager()->encode($payload)->get();
