### ISSUE TITLE
Refresh tokens not working in laravel4.

### ISSUE THREAD

**Issue by tw3eX** [tymondesigns/jwt-auth#113]
I try this:
>JWTAuth::parseToken()->refresh();

And get this:
>TokenExpiredException Token has expired.

The version for laravel 5, as far as I know, was repaired. And what about laravel 4?)

**Comment by tymondesigns** [comment]
I will patch laravel 4 to match soon

**Comment by tymondesigns** [comment]
Sorry but it turns out I don't have the time to maintain both major versions of laravel.

I guess try and upgrade to L5 when feasible

**Comment by olivernagy** [comment]
In case someone still has to deal with Laravel 4 like I do, the following workaround seemed to have fixed this issue:
```
$currentToken = JWTAuth::getToken();
JWTAuth::manager()->getPayloadFactory()->setRefreshFlow();
$token = JWTAuth::refresh($currentToken);

return Response::json(compact('token'));
```

It sets the `refreshFlow` on the `PayloadFactory` before even starting to refresh the token, fixing the validation in `decode`.
