### ISSUE TITLE
Reduce Token Size

### ISSUE THREAD

**Issue by sandipsapkota1** [tymondesigns/jwt-auth#1131]
please anybody help me how to reduce token size.

It is 268 character long now. I need only about  6 to 12  characters long

**Comment by akkhan20** [comment]
You will eliminate the whole purpose of it if you somehow get it to 6-12 characters

**Comment by sandipsapkota1** [comment]
can u tell me , how to do it

**Comment by jonagoldman** [comment]
JWT is an industry stardard. https://tools.ietf.org/html/rfc7519 you can't just somehow reduce the size of it.
