### ISSUE TITLE
ttl => null results in ["token_invalid"]

### ISSUE THREAD

**Issue by iamface** [tymondesigns/jwt-auth#1135]
Hello,

I've been using this package and it has worked great with the default setting
`'ttl' => env('JWT_TTL', 60),`. When I try to remove the time to live and set it to null, the response is always `["token_invalid"]`. Is there something else in the config that needs to be changed as well?

Thanks

**Comment by akkhan20** [comment]
yes you need to edit the token parameter in config that saves the expiry time

**Comment by iamface** [comment]
Are you referring to the `ttl` parameter or something else?

**Comment by akkhan20** [comment]
sorry i didn't remembered the exact parameter earlier it is 'required_claims' in the config and you need to remove 'exp' from that array

**Comment by iamface** [comment]
Yep that did it. Thanks @akkhan20!
