### ISSUE TITLE
[Help] Steam Login + JWT

### ISSUE THREAD

**Issue by kwinkel** [tymondesigns/jwt-auth#1136]
Hello,

I'm struggling with my following task:
I want to build an API which is restricted for different roles.
To authenticate a User, I want to use JWT in the request header to validate an user request. 

Steps:
* User logs in with Steam Auth at API.MyApp/auth/steam (using "invisnik/laravel-steam-auth": "2.*")
* Redirect to Frontpage.MyApp/login/token/{Token} to safe this with user storage (angular)
* (Frontpage made with Angular2)
* Angular sends request for restricted call with JWT Token for authentication
* API checks users permissions and send data in json format 

Problem now is: I tried a lot of tutorials on the web, leading me nearly to surrender with jtw-auth and laravel. It's my first Larvel/jwt-auth Project.

My installation:  https://gist.github.com/kwinkel/cc3e5204b533aca094de3c4c53a26b82
* "php": ">=5.6.4",
* "laravel/framework": "5.4.*",
* "laravel/tinker": "~1.0",
* "invisnik/laravel-steam-auth": "2.*",
* "tymon/jwt-auth": "1.0.x-dev"

Last Tutorial I tried was this one: https://github.com/tymondesigns/jwt-auth/issues/860
Last Error as I'm close to give up: 
User.php#8 >> Trait 'App\Authenticatable' not found

any help would be appreciated :(

**Comment by tymondesigns** [comment]
Looking at your user model, you are not importing a few things such as `Authenticatable`, `Authorizable`, `CanResetPassword`, `Notifiable` etc.

See here for a clue https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Auth/User.php

**Comment by kwinkel** [comment]
Thanks!

I've updated my gist to the actual setup.

Working now:
* Steam Login outputs token

Not working:
* when I try to authenticate a User with a Token (AuthController#index), the User Object stays empty..

**Comment by kwinkel** [comment]
```                
$token = \JWTAuth::fromUser($user, array('test' => 'hellooo'));
return response()->json([
 'user' => $user,
 'token' => $token
]);
```

results in a valid user and token response, but when I try to authenticate THIS token, I just receive an empty object (print_r prints "1")

using `JWTAuth::parseToken()->authenticate()`
token is set, checked with `JWTAuth::getToken()`
