### ISSUE TITLE
Support for JWE Encryption

### ISSUE THREAD

**Issue by pfazzino** [tymondesigns/jwt-auth#114]
It doesn't look like the namshi/jose package used supports encryption so I'm considering changing provider to use https://github.com/nov/jose-php. Before I do this I wanted to check if there was immediate plans to add support for JWE coming up in jwt-auth?

**Comment by tymondesigns** [comment]
@pfazzino can't see it being in the next release tbh, probably one for the one after, as it is something I want to implement at some point

Thanks
