### ISSUE TITLE
Guys , Help Me how can i save last_login 

### ISSUE THREAD

**Issue by sandipsapkota1** [tymondesigns/jwt-auth#1141]
I need to store last_login timestamp 
after the user logins through the jwt.auth  .

How can i save it to users table ,  last_login  column?

**Comment by johannesschobel** [comment]
Hey @sandipsapkota1 ,

you can do something like this in your `AuthController`. Look for your `authenticate()` method (wherever this method is located - i do not know your application).
However, this method should authenticate a `User` based on the provided credentials (e.g., via an `AuthRequest`).

When creating the JWToken (e.g., via `$user = JWTAuth::toUser($token)` you can do something like this..

```php
$user = JWTAuth::toUser($token)
$user->last_login = Carbon::now();
$user->save();

return $token;
```

Cheers

**Comment by johannesschobel** [comment]
hey @sandipsapkota1 , can you give a feedback on this issue? does my solution work?
if so, can you please close the issue?
Cheers

**Comment by sandipsapkota1** [comment]
Hello, thanks it worked.
