### ISSUE TITLE
Laravel 5.4 Incompatiblity: Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by allanxp4** [tymondesigns/jwt-auth#1144]
To reproduce:

- Start a new Laravel 5.4 Project.
- Follow the jwt-auth instructions.
- On the step "php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
you get a exception "Call to undefined method Illuminate\Foundation\Application::share()"

Searching from this problem on other repositories (like https://github.com/willvincent/feeds/issues/24), it seems like this API has changed on Laravel 5.4

Thanks.

**Comment by tymondesigns** [comment]
this is now fixed
