### ISSUE TITLE
Authenticate with Third-Party Package to Create Token?

### ISSUE THREAD

**Issue by iolson** [tymondesigns/jwt-auth#115]
I'm currently running into an issue when using the method of:
```
$token = JWTAuth::attempt($credentials)
```

The error is the following:
```
Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\User given
```

I'm currently using Cartalyst's Sentinel Package for Authentication and Registration. I was wondering if there was another way I can handle this to create the token and be able to Parse the token correctly in the future.

Package Docs: https://cartalyst.com/manual/sentinel/2.0

**Comment by tymondesigns** [comment]
This is possible right now.. You just have to implement the AuthInterface in the providers directory.

#79 should help
