### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Cache\CacheManager

### ISSUE THREAD

**Issue by wisarmy** [tymondesigns/jwt-auth#1161]
![image](https://cloud.githubusercontent.com/assets/5906470/26183998/bb45812c-3bb4-11e7-8d1e-01500b19482b.png)
lumen 5.2

**Comment by l3lackrooz** [comment]
in lumen :
added this line in **bootstrap/app.php**
`$app->alias('cache', \Illuminate\Cache\CacheManager::class);`

**Comment by Adil-Abid** [comment]
after add $app->alias('cache', \Illuminate\Cache\CacheManager::class);
this error show
  Cache store [] is not defined.
