### ISSUE TITLE
How do i fetch data from related tables of user ?

### ISSUE THREAD

**Issue by yash2code** [tymondesigns/jwt-auth#1168]
I am successfully getting the information from user table but what if I want to fetch data from friends table respect to user ? How do i do that?

**Comment by Petronetto** [comment]
If I understand what you want, you can simply do `$user = JWTAuth::parseToken()->authenticate();` and so `$user->friends`, as you can see here: https://github.com/tymondesigns/jwt-auth/wiki/Authentication

**Comment by tymondesigns** [comment]
this is a generic laravel question. see https://laravel.com/docs/5.4/eloquent-relationships
