### ISSUE TITLE
jwt.auth middleware - returning status code 400 on TokenExpiredException

### ISSUE THREAD

**Issue by Neoglyph** [tymondesigns/jwt-auth#117]
Hey everyone, 

I have stumbled across a problem, where the jwt-auth middleware (the ```Tymon\JWTAuth\Middleware\GetUserFromToken``` class) on an ```ExpiredTokenException``` would keep returning me a status code of 400, instead of the correct 401, all while returning the correct response - ```["token_expired"]```.

I have got it working, by adding namespaces before the Exceptions, which seemed to return the correct $e->getStatusCode() and fixed the issue.

I just wanted to post this here, since it will maybe be of use to someone, who might stumble on the same problem, that I have.

``` php
namespace Tymon\JWTAuth\Middleware;

class GetUserFromToken extends BaseMiddleware
{
    ...
    public function handle($request, \Closure $next)
    {
        ...
        /* before - returns incorrect $e->getStatusCode() */
        try {
            $user = $this->auth->authenticate($token);
        } catch (TokenExpiredException $e) {
            return $this->respond('tymon.jwt.expired', 'token_expired', $e->getStatusCode(), [$e]);
        } catch (JWTException $e) {
            return $this->respond('tymon.jwt.invalid', 'token_invalid', $e->getStatusCode(), [$e]);
        }
        /* after - returns correct $e->getStatusCode() */
        try {
            $user = $this->auth->authenticate($token);
        } catch (Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {
            return $this->respond('tymon.jwt.expired', 'token_expired', $e->getStatusCode(), [$e]);
        } catch (Tymon\JWTAuth\Exceptions\JWTException $e) {
            return $this->respond('tymon.jwt.invalid', 'token_invalid', $e->getStatusCode(), [$e]);
        }
       ...
    }
}
```

**Comment by rathesDot** [comment]
Had the same problem and fixed it the same way as @Neoglyph described. Works well and should be updated.

**Comment by jdsingh** [comment]
@Neoglyph Had the same problem. Status code should be 401 for this package.

It returns 404 for user_not_found where it should return 401 when using `GetUserFromToken` middleware.

**Comment by jasanmiguel** [comment]
I have the same problem. Status should be 401

**Comment by npx** [comment]
Can we keep this open as this is not fixed in 0.5.3?

**Comment by Mr-Anonymous** [comment]
I thought the OP's report was fixed looking at the linked issue but I still got the same error where `400 {"error":"token_not_provided"}` is returned for token expired reason.

**Comment by Mr-Anonymous** [comment]
Just now I noticed that even `{"error":"token_invalid"}` is returned as 400. Isint that supposed to be 401 too?

**Comment by martinlindhe** [comment]
+1

**Comment by tymondesigns** [comment]
You guys will need to implement your own middleware for this. Just catch the exceptions and return responses as you see fit

**Comment by josoroma** [comment]
For token expiration fits: 440 Login Timeout - The client's session has expired and must log in again.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
