### ISSUE TITLE
Access only page - avoid including token via a query string

### ISSUE THREAD

**Issue by yeenotgithub** [tymondesigns/jwt-auth#1179]
I want to access a page (basically a view page like admin dashboard after logging in) without including token via a query string like 

http://api.mysite.com/me?token={yourtokenhere}

because every time I would access another page under admin would always require including token via a query string. Is there any alternative to avoid it? Are there any methods that would allow it? For me it would be unprofessional to see a token at the url. Please help me, thank you!

**Comment by tymondesigns** [comment]
There are may ways to pass a token in the request besides query string. e.g. Auth headers, route params, cookies and post parameters.

Take a look here https://github.com/tymondesigns/jwt-auth/tree/develop/src/Http/Parser

**Comment by Yeenot** [comment]
Thanks tymon! I'll check this link.
