### ISSUE TITLE
Escaped slashes causing errors

### ISSUE THREAD

**Issue by smaxwellstewart** [tymondesigns/jwt-auth#118]
Hi,

First off thank you for writing such a useful library and open sourcing it. Really appreciated.

I started using your library to issue tokens, to be consumed by services written in other languages. I could not get tokens to verify the signature. I then tried verifying them on http://jwt.io, also had the same problem.

On closer inspection I noticed the problem was escaped backslashes in the token caused by, src/Claims/Claim.php line 110:

```php
return json_encode($this->toArray());
```
It should be:

```php
return json_encode($this->toArray(), JSON_UNESCAPED_SLASHES);
```

I can submit a PR to sort this.

**Comment by tymondesigns** [comment]
Merged
