### ISSUE TITLE
Custom Claims second param don't recieve

### ISSUE THREAD

**Issue by alfredobarron** [tymondesigns/jwt-auth#1212]
First I want to thank for the excelent library.

I have a little question.

# In your documentation tells that we can pass two parameters in the JWTAuht::attemp function 

![image](https://user-images.githubusercontent.com/2327016/27236331-3a450128-528a-11e7-9635-43821fdbe38d.png)

# But in the JWTAuht.php file just recive one parameter. How can I solve that?

![image](https://user-images.githubusercontent.com/2327016/27236315-26e074f0-528a-11e7-961b-67f0ff65713a.png)

**Comment by miscbits** [comment]
on the newest version, try this 
```
JWTAuth::customClaims($yourclaimsarray)->fromUser($user);```

**Comment by alfredobarron** [comment]
Thanks @miscbits for your help, but...

I am use this version

![screen shot 2017-06-22 at 12 32 07 pm](https://user-images.githubusercontent.com/2327016/27447545-ed033e9a-5746-11e7-8aa1-a9d84b3d1842.png)


and get this error message

![screen shot 2017-06-22 at 12 31 49 pm](https://user-images.githubusercontent.com/2327016/27447549-f42aa30c-5746-11e7-9a6a-e83ff5c936bd.png)


this is my code

```
$customClaims = ['exp' => Carbon::now()->addMinutes(1)];
$token = JWTAuth::customClaims($customClaims)->attempt($credentials);
```

**Comment by miscbits** [comment]
ah I see. Well if you want to update your version to use this snippet, I am using 
```
        "tymon/jwt-auth": "1.0.0-beta.3",
```

**Comment by miscbits** [comment]
I looked into this on version 0.5.12

![image](https://user-images.githubusercontent.com/8864479/27448837-44f526f6-5754-11e7-9e3a-9251fa8edbed.png)

This is what I see in the source code. 

https://github.com/tymondesigns/jwt-auth/releases/tag/0.5.12
got the code from this page 

Maybe something is wrong with your installed version (happens often with composer.) you could try deleting your vendors folder and re-running 
```
$ composer update
$ composer install
```

**Comment by alfredobarron** [comment]
You have reason, I think that the fix is format date not is good for exp parameter.

This is my code.
```
$customClaims = ['exp' => Carbon::now()->addMinutes(1)];
$token = JWTAuth::attempt($credentials, $customClaims);

```

**Comment by miscbits** [comment]
if you think thats the problem you can add Carbon::now()->addMinutes(1)->toDateTimeString();

**Comment by miscbits** [comment]
oh as a side note, carbon has the method addMinute() which is the same as addMinutes(1) so you could also just do 

Carbon::now()->addMinute()->toDateTimeString();

**Comment by alfredobarron** [comment]
The error is "Could not create token"

```
        $credentials = $request->only('email', 'password');

        $customClaims = ['exp' => Carbon::now()->addMinutes(1)->toDateTimeString()];

        try {
            // attempt to verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials, $customClaims)) {
                return response()->json(['error' => 'Invalid Credentials'], 401);
            }
        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return response()->json(['error' => 'Could not create token'], 500);
        }
```

**Comment by alfredobarron** [comment]
Solved!!!

```
$customClaims = ['exp' => Carbon::now()->addMinutes(1)->timestamp];
```
