### ISSUE TITLE
Unable to use dev branch with grace period

### ISSUE THREAD

**Issue by subalee** [tymondesigns/jwt-auth#1220]
Hi,

I've been using this package  (0.5.* ) with success. However in the app that consumes my API, I do parallel requests.

If i use the middleware that comes with the package, then by the time i get the response with new token the second request has already started with now blacklisted token.

I've tried using the dev-master branch, however the blacklist_grace_period is not there, I also tried using the 1.0.0.beta.3 however that one is missing JWTAuthServiceProvider.

How can i require this package with the blacklist_grace_period option that does have the Provider as well?

Thanks!

**Comment by craigcartmell** [comment]
Require the latest release candidate branch.

The provider was renamed to `Tymon\JWTAuth\Providers\LaravelServiceProvider::class` so just replace this in your `config/app.php` file. 

Or `LumenServiceProvider` if you're using Lumen.

**Comment by subalee** [comment]
@craigcartmell thanks, closed
