### ISSUE TITLE
Middleware auth:api guard error

### ISSUE THREAD

**Issue by zanjs** [tymondesigns/jwt-auth#1226]
laravel : 5.4
jwt-auth: 1.0.0-beta.3

auth.php

```php
'guards' => [

       'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
],
```

route/api.php

```
 Route::group(['middleware' => 'auth:api'], function () {
     Route::get('/me', 'UserController@me');
 });
```

If token is wrong,  The error is as follows

```

(1/1) InvalidArgumentException
Route [login] not defined.
```

**Comment by chrishessler** [comment]
This is happens when you try to reach a guarded route without being authenticated. It trows an exception, handled in app/exceptions/Handler.php

```
protected function unauthenticated($request, AuthenticationException $exception)
{
    if ($request->expectsJson()) {
        return response()->json(['error' => 'Unauthenticated.'], 401);
    }

    return redirect()->guest(route('login'));
}
```

E.g. In my current project I only want the application to return JSON responses. I changed this to:
```
protected function unauthenticated($request, AuthenticationException $exception)
{
    return response()->json(['error' => 'Unauthenticated.'], 401);
}
```

**Comment by zanjs** [comment]
@chrishessler Thank you 😱

**Comment by gausam** [comment]
@chrishessler @zanjs Isn't it better if this is configured somehow by the package out of the box, considering the package is used in API contexts more often than not. I could be wrong though!

**Comment by gausam** [comment]
My bad. I see in the Laravel source it's actually

```
return $request->expectsJson()
                    ? response()->json(['message' => $exception->getMessage()], 401)
                    : redirect()->guest(route('login'));
```

Which means you're safe if your consumer has appropriate headers.

Carry on with your wonderful new year :tada:

**Comment by spawnia** [comment]
In Passport 5.0.3, a bug was fixed which prevented the correct error response on JSON calls with incorrect authentication. This now works as intended.

**Comment by hasnatbabur** [comment]
Laravel always check possible response type to deliver.

If I set HTTP Header to Accept : application/json during ajax or any type of request it gives me response in json format.

Hope this will help. Thanks

**Comment by richellyitalo** [comment]
Not work with me. I'm using version 5.7
Any solution?

**Comment by surtibhavin6006** [comment]
@richellyitalo 

At App\Http\Middleware\Authenticate

`
protected function redirectTo($request)
{
        if(strpos($request->getUri(), '/api') !== false){
                return false;
        }
        return route('login');
}
`

**Comment by richellyitalo** [comment]
Works when i ran `php artisan make:auth`

**Comment by surtibhavin6006** [comment]
I think don't need `php artisan make:auth` if we are using only API with JWT

**Comment by richellyitalo** [comment]
I'll try without `make:auth`.

**Comment by fer-ri** [comment]
Since this package extended from auth guards using `JWTGuard`, so it always throws `Illuminate\Auth\AuthenticationException` when `check` or `user` is `null` as you can see at https://github.com/illuminate/auth/blob/master/Middleware/Authenticate.php#L67

My solution is to replace `App\Http\Middleware\Authenticate` with this

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;

class Authenticate extends Middleware
{
    /**
     * Determine if the user is logged in to any of the given guards.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  array                    $guards
     * @return void
     *
     * @throws \Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException
     */
    protected function authenticate($request, array $guards)
    {
        if (empty($guards)) {
            $guards = [null];
        }

        foreach ($guards as $guard) {
            if ($this->auth->guard($guard)->check()) {
                return $this->auth->shouldUse($guard);
            }
        }

        throw new UnauthorizedHttpException('JWTAuth', 'Unauthenticated.');
    }
}
```

As you can see I removed `redirectTo` method and replace `authenticate` to throw `UnauthorizedHttpException` 

You are free to change what to be thrown anyway.

---

**UPDATE**

Or maybe better

```php
<?php

namespace App\Http\Middleware;

use Illuminate\Auth\AuthenticationException;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException;

class Authenticate extends Middleware
{
    /**
     * Determine if the user is logged in to any of the given guards.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  array                    $guards
     * @return void
     *
     * @throws \Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException
     */
    protected function authenticate($request, array $guards)
    {
        try {
            parent::authenticate($request, $guards);
        } catch (AuthenticationException $e) {
            throw new UnauthorizedHttpException('JWTAuth', $e->getMessage());
        }
    }
}
```

**Comment by daniel0101** [comment]
Got this to work by setting the Accept Header to application/json ..Laravel automatically sends you Json Error Responses
