### ISSUE TITLE
how to customise JWTAuth::attempt ?

### ISSUE THREAD

**Issue by mani95lisa** [tymondesigns/jwt-auth#123]
Thanks!

I have readed this article : http://www.toptal.com/web/cookie-free-authentication-with-json-web-tokens-an-example-in-laravel-and-angularjs .

I'm a little confused about this method `JWTAuth::attempt`, please help me out, thanks again.

**Comment by tymondesigns** [comment]
What are you trying to customise?

You would simply pass in the login credentials and a token will be returned, which you can use to make subsequent authenticated requests

**Comment by mani95lisa** [comment]
@tymondesigns Thanks, I'm new to use Laravel and JwtAuth. I mean how can I customize the behaviour of `JWTAuth::attempt($credentials)`. Because I have to verify password and mobile by Model. For example, I have to `User::find()->first()` and compare the password.

Maybe it's the question of Laravel, thanks!

**Comment by tymondesigns** [comment]
You shouldn't ever have to manually compare the password, as laravel's authentication system handles that - http://laravel.com/docs/5.0/authentication

There's lots of material online, so just dig in! Laracasts.com is a good start if your looking to learn more

**Comment by mani95lisa** [comment]
@tymondesigns ok, thanks!
