### ISSUE TITLE
[Symfony\Component\Debug\Exception\FatalThrowableError]              Call to undefined function Tymon\JWTAuth\Providers\config_path()

### ISSUE THREAD

**Issue by svolence** [tymondesigns/jwt-auth#1232]
[Symfony\Component\Debug\Exception\FatalThrowableError]           
  Call to undefined function Tymon\JWTAuth\Providers\config_path()

**Comment by max-bertinetti** [comment]
you miss a colon in 

Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class

like

Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,

**Comment by tymondesigns** [comment]
need some more info here
