### ISSUE TITLE
Server restart logs everyone out

### ISSUE THREAD

**Issue by HiradRoshandel** [tymondesigns/jwt-auth#1238]
Everytime I push to my server using bitbucket pipelines my server briefly restarts and that logs every user out (apparently the token is not valid anymore). Has anyone experienced this before or has managed to fix this issue? Thanks

**Comment by mr-feek** [comment]
Are you changing your `JWT_SECRET` in each new build?

**Comment by HiradRoshandel** [comment]
@feeekkk  no my jwt.php has this line:
`'secret' => env('JWT_SECRET', 'SOMEHASH'),`

**Comment by zRosenthal** [comment]
are you running `php artisan jwt:generate` anywhere in your build/deploy pipeline? This would reset the secret and is just about the only way I can imagine everyones tokens being invalidated on server restart.
A good place to check is in composer.json hooks.

**Comment by tymondesigns** [comment]
as @zRosenthal has said, the only way your users could logged out is if your secret changed or your server's time is waayy out of sync
