### ISSUE TITLE
token_not_provided problem 

### ISSUE THREAD

**Issue by badrshs** [tymondesigns/jwt-auth#1240]
Hi , I'm working on api project  
between ionic framework  and laravel jwt-auth library 

the problem is when i send the information from my app the result is always token_not_provided  

I had print the parameter and everything is fine 

I did the same on postman and it's work fine  without the error 

I had print too the parameter with dd() on none token api and the same parameter as my ionic app there is no different 

any idea please ? anyone has an information about this ? ? 

this is my dd() result 
 
```
array:1 [
  "token" => "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwMDMwLCJpc3MiOiJodHRwOi8vNHByb2dyYW1tZXIuY29tL2FwaS92MS91c2VyL3TpZ251cCIsImlhdCI6MTQ5OTE5NTA0NSwiZXhwIjozMzY1NDM1MDQ1LCJuYmYiOjE0OTkxOTUwNDUsImp0aSI6IndEUHFuaGJNVWFoU284bm4ifQ.uODP2ArKUMmlrVzL-rlamsvOB81wusHn0aO22SivH-T"
]


And on postman it's the same 

array:1 [
  "token" => "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwMDMwLCJpc3MiOiJodHRwOi8vNHByb2dyYW1tZXIuY29tL2FwaS92MS91c2VyL3TpZ251cCIsImlhdCI6MTQ5OTE5NTA0NSwiZXhwIjozMzY1NDM1MDQ1LCJuYmYiOjE0OTkxOTUwNDUsImp0aSI6IndEUHFuaGJNVWFoU284bm4ifQ.uODP2ArKUMmlrVzL-rlamsvOB81wusHn0aO22SivH-T"
]

```

can you see any difference  ?  it's really strange

**Comment by ghost** [comment]
Try to send it as an header

**Comment by mhrahul** [comment]
I am sending it as header at Laravel 5.4.30 but still the same message arrived!
