### ISSUE TITLE
Edge giving incorrect authentication requirement compared to Chrome and Firefox

### ISSUE THREAD

**Issue by johnboc** [tymondesigns/jwt-auth#1244]
Framework: Laravel 5.4
tymon/jwt-auth Version: 0.5.12
Windows 10

All routes are protected apart from the the login page and the route posting the user's login credentials. Everything works as expected using Chrome and Firefox on Windows, but Microsoft Edge and any browser on iOS returns a 404 error "The requested resource requires user authentication" when the user clicks the login button that posts to the login route.

Any ideas on what differences between the browsers may be causing this?

**Comment by tymondesigns** [comment]
no idea i'm afraid, but closing as not to do with this package
