### ISSUE TITLE
Get token not giving token

### ISSUE THREAD

**Issue by tijanmdr** [tymondesigns/jwt-auth#1256]
hello, I'm trying to get JWT token from headers using `JWTAuth::getToken()` and this is what i get `"authorization": {},` and while `dd(JWTAuth::getToken())`, it gives response as 
```
Token {#360
  -value: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hcGkvdjEvbG9naW4iLCJpYXQiOjE1MDAzNjMzNzgsImV4cCI6MTUwMDY2MzM3OCwibmJmIjoxNTAwMzYzMzc4LCJqdGkiOiI0bmkyVmg5RWt1TWtWNnhkIn0.OORKHBnIareDr2Z48pkXN-V3ykUEQRfpfNx5RnQkVI4"
}
```
Is there any way to access the above token or get token value

**Comment by zRosenthal** [comment]
Yes, my guess is there is a different bug in your code. Can you add more code where this is happening?

**Comment by tijanmdr** [comment]
I'm sorry didn't reply then. I already fixed it by doing `(string)JWTAuth::getToken()` which successfully gives me my required `Authorization Code`

**Comment by tijanmdr** [comment]
I'm sorry didn't reply then. I already fixed it by doing `(string)JWTAuth::getToken()` which successfully gives me my required `Authorization Code`

**Comment by eranshmil** [comment]
Instead, you can use JWTAuth::getToken()->get()

**Comment by rojonunoo** [comment]
@tijanmdr Man you are a savior .. you have no idea

**Comment by wprincearora** [comment]
@eranshmil  thanks man it worked

**Comment by wwwprincearora** [comment]
`sdsdsdsdsdsd`

**Comment by aadhar41** [comment]
Thanks man it works

**Comment by zkenstein** [comment]
> (string)JWTAuth::getToken()

Used it but return:**Wrong number of segments**

**Comment by zkenstein** [comment]
> JWTAuth::getToken()->get()

with this return: Call to a member function get() on null
