### ISSUE TITLE
Global Exception Handling 1.0.0-beta.3

### ISSUE THREAD

**Issue by jampack** [tymondesigns/jwt-auth#1267]
This piece of code is not working as supposed:

> public function render($request, Exception $e)
{
    if ($e instanceof Tymon\JWTAuth\Exceptions\TokenExpiredException) {
        return response()->json(['token_expired'], $e->getStatusCode());
    } else if ($e instanceof Tymon\JWTAuth\Exceptions\TokenInvalidException) {
        return response()->json(['token_invalid'], $e->getStatusCode());
    }
    return parent::render($request, $e);
}

using version 1.0.0-beta.3 in laravel 5.4, running `get_class($e)` returns:

> "Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException"

for all the exceptions related to this package

**Comment by jampack** [comment]
no clue?

**Comment by dmason30** [comment]
@tymondesigns How are we supposed to identify the reason for authentication failure if the events have gone and we are not getting the relevant exceptions?

**Comment by tymondesigns** [comment]
@dmason30 you are getting the relevant exceptions. The package is still throwing the same exceptions as before. 

The difference being now, that the middleware that are provided with the package, throw Symfony http exceptions, which are simply sensible defaults, that can be caught and converted into an appropriate http response.

So you are free to either:
- Use the middleware that come out of the box, and catch the Symfony http exceptions and respond as such.
- Or write your own middleware to catch the package specific exceptions e.g. `TokenExpiredException` and form a http response that way

**Comment by jampack** [comment]
The issue is that how to identify the basic cause of the exception i.e invalid, blacklist, expired, cant be parsed...
The default exception throws a text response with a statusCode of '0' which is not a norm in APIs, how will a client identify what was the cause if we dont send a statusCode and statusText a general message can not became the source for identifying an issue like for token blacklist the message is "The token has been blacklisted" where as client would expect a standard statusText => "token_blacklisted" statusCode=>"1234"

**Comment by tymondesigns** [comment]
@akkhan20 It's pretty straightforward:

```php
try {
  $user = Auth::user();
} catch (\Tymon\JWTAuth\Exceptions\TokenBlacklistedException $e) {
  return response()->json(['error' => 'token_blacklisted'], 401);
} catch (\Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {
  return response()->json(['error' => 'token_expired'], 401);
}
```

**Comment by jampack** [comment]
thats simple but i was referring to the exceptions in exception handler when exceptions are raised by the auth&refresh middleware

**Comment by tymondesigns** [comment]
the exceptions that are raised in the package do not contain any http related things (and they shouldn't), so calling `$e->getStatusCode()` will fail

**Comment by johncloud200** [comment]
How to use exception on Handler.php?

**Comment by ghost** [comment]
@tymondesigns I saw in the code that you use the same type of exception to throw token expiration based on `ttl` and expiration where it can no longer be refreshed `refresh_ttl`. Shouldn't they be more specific and throw different types of exceptions?

Relevant code:

#### IssuedAt.php

```php
throw new TokenExpiredException('Token has expired and can no longer be refreshed');
```

#### Expiration.php

```php
throw new TokenExpiredException('Token has expired');
```

**Comment by victorrss** [comment]
I am using

```
"php": ">=7.0.0",
"fideloper/proxy": "~3.3",
"laravel/framework": "5.5.*",
"laravel/tinker": "~1.0",
"tymon/jwt-auth": "1.0.0-rc.1"
```

it worked here
Add the following code to the render method within app/Exceptions/Handler.php

```
public function render($request, Exception $e)
    {
        if($e instanceof \Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException){
            return response()->json([$e->getMessage()], $e->getStatusCode());
        }
        return parent::render($request, $e);
    }
```

**Comment by lawrence615** [comment]
Hello @victorrss,

Your solution actually works, thanks for sharing.

But I was wondering, if you get "Token has expired and can no longer be refreshed", how do you then proceed to getting a valid token to access the API? Considering that logout route has jwt.auth middleware.

**Comment by ghost** [comment]
@lawrence615 Just sharing how I did it with this package... you should have code in your frontend that will *catch* that error.

I created an interceptor using axios. If the interceptor catches an expired token error from Laravel, it will send another request to the `/api/refresh` route.

If the token was refreshed successfully, the original request is repeated. In this situation the flow of the application is uninterrupted, it probably just gets delayed for a few milliseconds waiting for the token refresh.

If the token can't be refreshed, then (1) I use my frontend router to redirect to the login page (2) remove the JWT from local storage and also clear out any variables related to authentication (3) show a message that tells the user their session has expired.

**Comment by kalemdzievski** [comment]
> @tymondesigns I saw in the code that you use the same type of exception to throw token expiration based on `ttl` and expiration where it can no longer be refreshed `refresh_ttl`. Shouldn't they be more specific and throw different types of exceptions?
> 
> Relevant code:
> 
> #### IssuedAt.php
> ```
> throw new TokenExpiredException('Token has expired and can no longer be refreshed');
> ```
> 
> #### Expiration.php
> ```
> throw new TokenExpiredException('Token has expired');
> ```

I am experiencing the same issue. @tymondesigns

**Comment by kalemdzievski** [comment]
@raniesantos having the same problem, and nobody responds ...
https://github.com/tymondesigns/jwt-auth/issues/1848

Did you had any luck solving this issue. I had to hard code an if statement checking the message of the exception ... Very very bad.
