### ISSUE TITLE
L5.5 Compatibility

### ISSUE THREAD

**Issue by ragingdave** [tymondesigns/jwt-auth#1271]
With the release of L5.5 around the corner, it would be nice to at least be able to install jwt-auth alongside L5.5, in order to help find new bugs (if any).
A suggestion might be to change the composer require version to ~5.1 which correct me if I'm wrong, should show support for L5.1 to L5.x. Another option would be to add another `||` check for 5.5.x-dev.

**Comment by ragingdave** [comment]
If it helps I could submit a PR to add the additional check @tymondesigns .

**Comment by ghost** [comment]
It would be great cause soon laravel 5.5 will be released.

**Comment by kohenkatz** [comment]
PRs #1278, #1288, and #1275 (which is bad) all do this.

See also #1289

**Comment by tymondesigns** [comment]
done via #1278
