### ISSUE TITLE
[REQUEST][1.0.0-beta.3] Add parser chain to config

### ISSUE THREAD

**Issue by dmason30** [tymondesigns/jwt-auth#1276]
@tymondesigns It would be nice if we could manage the parser chain in the `jwt.php` config as I would only like it to use cookie, plus I have a number of forms that post a `token` field which is causing issues. 

I have had to create a new `ServiceProvider` extending yours in the mean time to override it.

**Comment by tymondesigns** [comment]
I don't really want to bloat the config out too much, it's simple enough to customize things through your AppServiceProvider or any other e.g.

```php
app('tymon.jwt.parser')->setChain([new AuthHeaders]); // etc
```
