### ISSUE TITLE
Token has expired during login operation

### ISSUE THREAD

**Issue by therealmjk** [tymondesigns/jwt-auth#1277]
Hi i had no issues with my login but after pushing my service to google app engine any time i try to login i get this exception.

{
    "message": "operation failed",
    "detail_message": "Token has expired",
    "file": "/app/vendor/tymon/jwt-auth/src/Validators/PayloadValidator.php",
    "line": 83,
    "error": true
}

**Comment by therealmjk** [comment]
So i did some debugging and found out the user gets logged it but the error is from when i try to create the token using the fromUser() function please help me out

**Comment by therealmjk** [comment]
solved.. Sorry!

**Comment by nijil-v** [comment]
@therealmjk How did you solve this? I am also getting the same error
