### ISSUE TITLE
Get a refresh token. (not refreshing an access token)

### ISSUE THREAD

**Issue by mesqueeb** [tymondesigns/jwt-auth#1282]
Hello community.
I'm really confused with the difference between 'refresh tokens' and "refreshing a token".

I think that refreshing a token just gives a new 'access token' which is short lived right?
But I wanna set my 'refresh tokens' to live for a year, and save them onto the local storage.

It's confusing in this library when it gives you an 'access token' and when it gives a 'refresh token'.
**How do I generate a "refresh token" manually?**

If I have a 100% front-end Single Page Application. And I want my users to stay logged in forever on the same computer and browser, **it's this refresh token that I should save in a cookie or local storage right?** (leave the cookie vs local storage aside for now)

**Comment by tremby** [comment]
I asked the same in #1105.
