### ISSUE TITLE
What to do to install with L5.5?

### ISSUE THREAD

**Issue by vibrantBits** [tymondesigns/jwt-auth#1289]
No really an issue but a question: Is it a way to make it work with L5.5?
I guess it is just matter of modifying a couple of things in composer.json, is it not?

**Comment by BafS** [comment]
Yes it's just about the composer.json for the conflicts. I did a fork (https://github.com/tymondesigns/jwt-auth/pull/1288/files), you can try to use `bafs/jwt-auth` temporary.

**Comment by vibrantBits** [comment]
Great, I'll try it. Thanks!

**Comment by kohenkatz** [comment]
See also: #1271, #1275, #1278

**Comment by cspshadx** [comment]
L5.5 is out, any updates on this?

**Comment by tymondesigns** [comment]
done via #1278
