### ISSUE TITLE
Error while executing command php artisan jwt:generate - Laravel 5.5

### ISSUE THREAD

**Issue by geekcom** [tymondesigns/jwt-auth#1296]
**Details:**

* Error while executing command **php artisan jwt:generate** 
* Version: "tymon/jwt-auth": "0.5.*"
* Laravel 5.5

**Error:** 

[ReflectionException]Method Tymon\JWTAuth\Commands\JWTGenerateCommand::handle() does not exist

**Comment by tymondesigns** [comment]
Laravel 5.5 compatiblity is only available via https://github.com/tymondesigns/jwt-auth/releases/tag/1.0.0-rc.1

**Comment by geekcom** [comment]
Thanks @tymondesigns
