### ISSUE TITLE
Laravel5 publish config

### ISSUE THREAD

**Issue by ghost** [tymondesigns/jwt-auth#13]
Hi,

Thanks for the great package! The only thing I found different so far is the command to publish config file in Laravel 5.0. You have to do:

`php artisan publish:config tymon/jwt-auth`

**Comment by JDqv** [comment]
I see @tymondesigns is updating laravel-5 branch - nice. Whats your take on missing config publishing command. It should be clear by now how its intended, imho, but I cant find anything on it. How do you publish it?

This command is not there anymore

     php artisan publish:config tymon/jwt-auth

**Comment by tymondesigns** [comment]
yea this command has now been removed.. The way to do it now is:
```
php artisan vendor:publish
```
as seen here - http://laravel.com/docs/master/packages

This will create a file called `jwt.php` in the config directory (there is no more packages folder)

I still have some work to do on the documentation, but hoping to have that done asap

Thanks

**Comment by JDqv** [comment]
tnx
that means, that line 71 must change in JWTGenerateCommand. It points to old config path.
this should look something like

    $contents = $this->files->get($path = base_path()."/config/jwt.php");

instead of
 
    $contents = $this->files->get($path = $this->laravel['path']."/config/packages/tymon/jwt-auth/{$env}config.php");

**Comment by tymondesigns** [comment]
yep.. still have to update that. Not sure whether to update the .env file instead, the same as laravels key:generate command
