### ISSUE TITLE
Refresh an expired token still within its refresh_ttl

### ISSUE THREAD

**Issue by osteel** [tymondesigns/jwt-auth#130]
Hi,

This is not an issue *per se* (a priori), but more a question about the *refresh token flow*.

I understand that a token having passed its `ttl` (expired) but still within its `refresh_ttl` should still be *refreshable*, but I am confused about whether or not this should be done by the middleware (it doesn't seem to be the case).

Whenever a token is expired, it doesn't get through the `GetUserFromToken` middleware as an exception is thrown, so it doesn't get the chance to be refreshed by the `RefreshToken` middleware even if it is still *refreshable* (as < `refresh_ttl`).

Does this mean we're expected to catch the `TokenExpiredException` so we can then check if the token is still *refreshable* and manually call `JWTAuth::refresh` and pass the new token to the response ourselves? Or implement a `refreshToken` endpoint accepting an expired token and refreshing it, to be called by the webapp when it gets a `401` response (so the webapp can retry the request with the returned refreshed token) (as some people seem to advocate).

Am I missing something here?

Thanks!

**Comment by tymondesigns** [comment]
I guess we'll continue the discussion here #127
