### ISSUE TITLE
 Class 'JWTAuth' not found

### ISSUE THREAD

**Issue by hashk99** [tymondesigns/jwt-auth#1301]
`Class 'JWTAuth' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'JWTAuth' not found`

Error occured in a laravel 5.5 project.
I've republished my configurations.

**Comment by hashk99** [comment]
Seems like adding JWTAuth facade to app configurations missing in the document. please update it.
I've managed to fix this issue by adding `
        'JWTAuth' => Tymon\JWTAuth\Facades\JWTAuth::class,` into  `aliases` array in the app.php file.

**Comment by tymondesigns** [comment]
it's explained here https://github.com/tymondesigns/jwt-auth/wiki/Installation
