### ISSUE TITLE
How to prevent the man-in-the-middle

### ISSUE THREAD

**Issue by rogeryu23** [tymondesigns/jwt-auth#131]
Hi seems, the token is just put in the http header which is not secure
Does it have support to do generating the signature and send only the signature over the wire and valided at the server side?

Thanks
Roger

**Comment by tymondesigns** [comment]
Hi Roger,

Firstly, you should never add any sensitive information to the token claims.

Having the token sent as a header doesn't raise any security concerns to me.

To answer your question though. No that's not how JWT's work.

The package currently uses JSON Web Signature (JWS).
Although I will be looking to add JWE support after the next release is out of the way.

See http://self-issued.info/docs/draft-ietf-jose-json-web-encryption-40.html and https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41

SSL is always a good idea too
