### ISSUE TITLE
JWT_BLACKLIST_GRACE_PERIOD  does not have any effect

### ISSUE THREAD

**Issue by jackengine** [tymondesigns/jwt-auth#1314]
with jwt-auth 0.5.12, Laravel 5.4.28 this do not have any effect. refreshed token gets blacklisted immediately..

**Comment by spirant** [comment]
I believe that the Blacklist Grace Period was not implemented in 0.5.12. Using the the Dev branch (v1.x) may solve this issue.

**Comment by FHoulbreque** [comment]
Probably this is stating the obvious, but don't forget `php artisan config:cache` if you changed the .env file.

**Comment by jackengine** [comment]
Hi @FrancoisH I did those all most obvious things already, but it couldn't solve.
Thanks.

Hi @spirant you might be right, that Dev Branch may solve this. But we have changed login policy, so we are not going to upgrade this for now.

Thanks
