### ISSUE TITLE
addClaim is not adding claim values

### ISSUE THREAD

**Issue by chillcaw** [tymondesigns/jwt-auth#1319]
After a recent update the `addClaim()` function is no longer adding a `$name`, `$value` pair.

This code (This was working about a couple of weeks ago):
`$this->jwt->factory()->addClaim('aid', $request->get('application_id'));`

Is adding {`"addClaim" : "aid"`} to the payload of the token, rather than {`"aid" : aidValue`}

**Comment by przemyslaw-leczycki-valueadd** [comment]
You should use `customClaims` method now.
I had similar issue after updating from 1.0.0-beta.3 to 1.0.0-rc.1. Method `addClaim` is protected now. 
[commit](https://github.com/tymondesigns/jwt-auth/commit/ef4e5c9711c4d42ed581ddde6ffe341917f29607)
There is no error because it's muted by `__call` method.
```
public function __call($method, $parameters)
    {
        $this->addClaim($method, $parameters[0]);

        return $this;
    }
}
```

**Comment by tymondesigns** [comment]
The way to do it is 
```php
$payload = factory()->claims(['aid' => $request->get('application_id')])->make();
// or
$payload = factory()->aid($request->get('application_id'))->make();
```

**Comment by przemyslaw-leczycki-valueadd** [comment]
@tymondesigns can I use safely `customClaims` or should I change to `claims` alias? Do you plan to deprecate it in the future?

**Comment by tymondesigns** [comment]
@przemyslaw-leczycki-valueadd no deprecations planned for that 👍

**Comment by chillcaw** [comment]
If I use either of those factory methods i get an error: 
'JWT payload does not contain the required claims'

NOTE: This was fixed by removing the ->make() method at the end. E.g:
$payload = factory()->aid($request->get('application_id'));
