### ISSUE TITLE
res is null. $scope.signup angular error

### ISSUE THREAD

**Issue by tarunhere** [tymondesigns/jwt-auth#132]
![jwt error](https://cloud.githubusercontent.com/assets/4122496/7915046/918cdbf6-0898-11e5-839b-92015e2be228.png)
I have setup this project in local, but on submitting I am getting this error from the angularjs.
Please help me understand this.

Also, I have implemented roles and permission from Entrust package, How can I implement JWT to work with Entrust roles package? 
Any help/guide will be highly appreciated.

**Comment by tymondesigns** [comment]
Looks like CORS is the cause of your issue.

This package is great for this https://github.com/barryvdh/laravel-cors
