### ISSUE TITLE
Problem with post request

### ISSUE THREAD

**Issue by sajjaadalipour** [tymondesigns/jwt-auth#1323]
This is my code for pars token `JWTAuth::parseToken()->authenticate();` .
This worked fine when my request is `GET` but not worked fine when my request is **POST**.
My exception is  **The token could not be parsed from the request**

**Comment by mbezhanov** [comment]
@smartdeath Are you sending an "Authorization" header with your HTTP request, containing the token?

**Comment by sajjaadalipour** [comment]
@mbezhanov I don't send any "Authorization" header but I didn't the problem when my method was **GET**

**Comment by mbezhanov** [comment]
@smartdeath This exception message indicates that the library cannot retrieve and parse the token from the request you are sending. How are you sending your token? Possible options are:

1. As an HTTP Request header (including `Authorization: Bearer YOUR_TOKEN_GOES_HERE` header when forming the request)
2. As a query parameter (e.g. submitting a request to `https://example.com/?token=YOUR_TOKEN_GOES_HERE`)
3. As an Input Source parameter
4. As a Route parameter
5. As a Cookie

Which one do you use? 1 and 2 work properly for me in version `1.0.0-rc1`. I haven't tried out the rest.

**Comment by sajjaadalipour** [comment]
@mbezhanov Thank you for your help.
