### ISSUE TITLE
Authorization header not working wilth my API

### ISSUE THREAD

**Issue by ramibadran** [tymondesigns/jwt-auth#1329]
Hi Guys

When i add an Authorization header <Bearer xcxcxcxc> to my api call which used JWT token i got the following error: NotFoundHttpException:

note:

im using nginx
my htaccess file:
i can generate JWT token

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

</IfModule>

**Comment by ramumaheswaran** [comment]
Rambhidaran - any luck with this issue?

**Comment by ramibadran** [comment]
yes i had issue with my environment/htaccess and now its working fine 
thanks for asking

**Comment by ramumaheswaran** [comment]
Can you please share what was the .htaccess change?

Thanks & Regards,
Mahesh

**Comment by ramumaheswaran** [comment]
Can you please share what was the environment &  .htaccess change? We have been breaking our heads for quite sometime.  We tried Angular JS,PHP, jquery and javascript.
