### ISSUE TITLE
Update JOSE Library

### ISSUE THREAD

**Issue by spawn-guy** [tymondesigns/jwt-auth#134]
so, this library uses JOSE of version 2.
apparently, tokens, generated by that version do NOT pass validation on http://jwt.io 
as well as tokens generated by NodeJS OAuth server are not accepted by JOSE.
there is a version 4.0.0 of JOSE and 5.0.0 in development.

in my case i quick-implemented FirebaseAdaptor for https://github.com/firebase/php-jwt and now everything is working like a charm.

**Comment by tymondesigns** [comment]
This was done in #126 and b0d64636edf1b0718dfa97face9e9227909012c6

**Comment by tymondesigns** [comment]
Will release patch soon
