### ISSUE TITLE
prv claim?

### ISSUE THREAD

**Issue by jampack** [tymondesigns/jwt-auth#1344]
What is the new "prv" parameter in the token?

**Comment by slashsbin** [comment]
It seems it's the Hash of the User Provider Class, See https://github.com/tymondesigns/jwt-auth/pull/1167.

**Comment by jampack** [comment]
@slashsBin  Thanks alot :)

**Comment by outrowender** [comment]
Actually, it's the hash of the `namespace` of User Provider Class

**Comment by sentrychris** [comment]
This might be a stupid question but just to confirm, what does "prv" stand for in this instance? I assume it's short for "provider"?

**Comment by slashsbin** [comment]
Yes, you assumed correctly.
