### ISSUE TITLE
how can I get the user with hasmany information?

### ISSUE THREAD

**Issue by edwinhuish** [tymondesigns/jwt-auth#1356]
Hi, I want to know, if there have some way to get user info with hasmany information?

Just like below:

**User model**
```
class User extends Authenticatable
{
   // ..........

    public function roles()
    {
        return $this->hasMany(UserRoles::class,'user_id', 'id');
    }
}
```

**Controller**
```
    public function info(Request $request)
    {
        $user = JWTAuth::parseToken()->authenticate();

        $state = User::with('role')->find($user->id);

        return response()->json(['state' =>$state]);
    }
```

## Is there have a easy way to get the user info with hasmany ??

**Comment by jampack** [comment]
my friend you have posted the issue on wrong repository or i would say the package doesn't provide any such methods to do that. Query wise the code in your controller is the shortest easiest snippet
