### ISSUE TITLE
In the release "1.0.0-rc.1", how do i create a token by user?

### ISSUE THREAD

**Issue by josericardomcastro** [tymondesigns/jwt-auth#1364]
In the release "1.0.0-rc.1", how do i creating a token based on a user object?

I read the documentation [http://jwt-auth.readthedocs.io/en/docs/quick-start/](http://jwt-auth.readthedocs.io/en/docs/quick-start/) and only explains the token generation using the attempt method.

``$this->guard()->attempt($credentials)).``

I need to validate my user like this:

```
public function login(Request $request)
{
$user = User::where('passwd', $request->pass)->get();
if ( $user  ){
// authenticates and returns the token
}
return response()->json(['error' => 'Unauthorized'], 401);
```

**Comment by imslepov** [comment]
```
protected function credentials(Request $request)
{
	return $request->only('passwd');
}

public function login(Request $request)
{
	$token = $this->guard()->attempt($this->credentials($request));
	if ($token) {
		// todo
	}
	return response()->json(['error' => 'Unauthorized'], 401);
}
```

**Comment by josericardomcastro** [comment]
When i use the attempt() method i receive this error:

`ErrorException: Undefined index: password in file /sysadm/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php on line 131`

I don´t have a "password" column in my user´s table.

**Comment by andrewmclagan** [comment]
see https://github.com/tymondesigns/jwt-auth/issues/1426

**Comment by tymondesigns** [comment]
You can do something like:

```php
$token = auth()->login($user);
$token = auth()->byId($userId);
```
