### ISSUE TITLE
Token gets created without email

### ISSUE THREAD

**Issue by arctican** [tymondesigns/jwt-auth#1374]
I'm having an issue, where a token is created if I don't send an email parameter. If I send only a password, then a token is successfully created from the first user in the DB with that password. 

If I send an incorrect password, or supply both the email and password, with either incorrect, it fails as it should.

I have tried this with both the 0.5.* and 1.0.0-rc1 releases.

I am using Laravel 5.5.20, with Dingo 2.0.0-alpha1.

Following the 1.0.0 Wiki guide:

    $credentials = $request->only('email', 'password');
    if ($token = $this->guard()->attempt($credentials)) {
        return $this->respondWithToken($token);
    }
    return response()->json(['error' => 'Unauthorized'], 401);

**Comment by Kyslik** [comment]
Do you even validate?

```php
$credentials = $request->validate([
    'email'    => 'required|email',
    'password' => 'required|min:6',
]);
```

**Comment by arctican** [comment]
Apologies, for some reason the email wasn't marked as required.

Thanks
