### ISSUE TITLE
Secret key stored in config/jwt.php

### ISSUE THREAD

**Issue by thomasschiet** [tymondesigns/jwt-auth#138]
When I generate a new secret key using ```php artisan jwt:generate```, it is stored in ```config/jwt.php```. Why is this? Wouldn't it be better if it were stored in ```.env```, just like ```APP_KEY```? Now git wants me to commit my key, this doesn't seem like a good practice.

**Comment by aligajani** [comment]
Correct, thought the same.

**Comment by tymondesigns** [comment]
In the same way that Laravel [has a default value](https://github.com/laravel/laravel/blob/master/config/app.php#L81) of `SomeRandomString`, this is only meant as a fallback if a key has not been set in the env vars. Which it should have been in production and other non local environments.

If you add the `--show` flag to the command then, it will simply output it to the console.

**Comment by thomasschiet** [comment]
The point is that it doesn't set the env var, and if it is set, it will try to update the fallback value set in ```config/jwt.php```. 

For example, when my ```.env``` file contains
```
JWT_SECRET=oldkey
```
and ```config/jwt.php```
```php
'secret' => env('JWT_SECRET', 'changeme')
```
The command does not work. It will search for "oldkey" in ```jwt.php``` and change it to the newly generated key. Obviously, the old key isn't present and thus nothing will be changed. However, it will still say that the new secret was set successfully. 

As you can see [here](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/KeyGenerateCommand.php#L37), Laravel checks the env file, whereas [jwt-auth](https://github.com/tymondesigns/jwt-auth/blob/laravel-5/src/Commands/JWTGenerateCommand.php#L38) checks the config file.

**Comment by aligajani** [comment]
It works for me if I put in just this :

'secret' => env('JWT_SECRET')


And then JWT_SECRET in my .env


On Sunday, June 7, 2015, Thomas Schiet <notifications@github.com> wrote:

> The point is that it doesn't set the env var, and if it is set, it will
> try to update the fallback value set in config/jwt.php.
>
> For example, when my .env file contains
>
> JWT_SECRET=oldkey
>
> and config/jwt.php
>
> 'secret' => env('JWT_SECRET', 'changeme')
>
> The command does not work. It will search for "oldkey" in jwt.php and
> change it to the newly generated key. Obviously, the old key isn't present
> and thus nothing will be changed. However, it will still say that the new
> secret was set successfully.
>
> As you can see here
> <https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/KeyGenerateCommand.php#L37>,
> Laravel checks the env file, whereas jwt-auth
> <https://github.com/tymondesigns/jwt-auth/blob/laravel-5/src/Commands/JWTGenerateCommand.php#L38>
> checks the config file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tymondesigns/jwt-auth/issues/138#issuecomment-109756238>
> .
>


-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by thomasschiet** [comment]
If I do that, and run the command to generate a new secret, nothing happens because ```$path``` defined [here](https://github.com/tymondesigns/jwt-auth/blob/laravel-5/src/Commands/JWTGenerateCommand.php#L38) points to ```config/jwt.php```.

**Comment by Donatello-za** [comment]
This issue should really not be closed. If keeping it as is then it means that I have to explain to every developer in the team to use php artisan jwt:generate --show and then paste the entry manually into a .env file instead of it being generated in the .env file as it should. I am worried that if it is committed to the repository due to it being in jwt.php that a developer's key end up on a production server.

**Comment by jadjoubran** [comment]
Hi @Donatello-za 
This is issue has been resolved here #311 
So the fix will be available in the upcoming release (0.6)

**Comment by tymondesigns** [comment]
@jadjoubran is correct. Also note that the name of the command has changed to `jwt:secret`

**Comment by Donatello-za** [comment]
Thanks! It is much appreciated!
