### ISSUE TITLE
custom claim not working as expected

### ISSUE THREAD

**Issue by jmdavid** [tymondesigns/jwt-auth#1388]
Hello,

based on documentation, the following code is supposed to work:
`
$credentials = $request->only('email', 'password');
$customClaims = ['sCustomercode' => '1234', 'sActivesessionID' => 'abcd'];
if (!$token = app('auth')->guard($this->guard)->attempt($credentials, $customClaims)) {
    return response()->json(['error' => 'invalid_credentials'], 401);
}
`

but when token is decoded, I have no custom properties.

The only way for now is:
`
$token = JWTAuth::fromUser($user, $customClaims);
$payload = JWTFactory::sCustomercode('1234')->sActivesessionID('1234')->sVerification('abcd')->make();
$token = JWTAuth::encode($payload)->get();
`
It is more intuitive to provide an array in attempt(), is it a bug or the feature changed without refreshing the documentation?

Thanks.

**Comment by ulisescarreonalvarez** [comment]
I added the claims through User model.

**Comment by axul** [comment]
I'm having the same issue, I need different types of tokens, with custom exp dates. Adding hte claims through User model is not a solution

**Comment by jmdavid** [comment]
@tymondesigns 
Hey, any update on that?

**Comment by tymondesigns** [comment]
See here for v1.0.0 http://jwt-auth.readthedocs.io/en/develop/auth-guard/#adding-custom-claims

**Comment by jmdavid** [comment]
Still not working with LUMEN.  

$token = app('auth')->attempt($credentials) 
or 
$token = app('auth')->guard('api')->attempt($credentials)

Always return false.

**Comment by jmdavid** [comment]
Just to clarify:

$credentials = $request->only('email', 'password');
$user = User::where('email', $request->get('email'))->first();
$valid = Hash::check($request->get('password'), $user->getAttribute('password'));

$valid is true.

$test = JWTAuth::attempt($credentials);

$test is false.

So there is something with attempt.
