### ISSUE TITLE
How does this package work internally?

### ISSUE THREAD

**Issue by aligajani** [tymondesigns/jwt-auth#139]
I need to know a bit more about how this package works, considering security is an important issue.

**Comment by tymondesigns** [comment]
Can you narrow it down a little? Which flow do you want to know about..

**Comment by aligajani** [comment]
Well, a user wants to login via Larqvel socialite, how would that be done.
Such as handling the callback redirect.

On Sunday, June 7, 2015, Sean Tymon <notifications@github.com> wrote:

> Can you narrow it down a little? Which flow do you want to know about..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tymondesigns/jwt-auth/issues/139#issuecomment-109748483>
> .
>


-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by tymondesigns** [comment]
The way in which a user is created/registered is outside of the scope of this package.

To use your example, you handle the callback as you normally would and register them if they aren't already. Then simply create a token for that user, using the relevant method 
(in the current version that would be `$token = JWTAuth::fromUser($user);`)

**Comment by aligajani** [comment]
Cool. I was just wondering. How secure is your implementation of the JWT.

On Sunday, June 7, 2015, Sean Tymon <notifications@github.com> wrote:

> The way in which a user is created/registered is outside of the scope of
> this package.
>
> To use your example, you handle the callback as you normally would and
> register them if they aren't already. Then simply create a token for that
> user, using the relevant method
> (in the current version that would be $token = JWTAuth::fromUser($user);)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tymondesigns/jwt-auth/issues/139#issuecomment-109802668>
> .
>


-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by tymondesigns** [comment]
it uses HMAC SHA-256 out of the box, but many other algorithms are available. 

The heavy lifting is done by another package - https://github.com/namshi/jose

some other jwt libs use it too

**Comment by aligajani** [comment]
Okay, I saw on JWT's site (jwt.io) that that package, /namshi/jose has
vulnerabilities.

Have you looked at it?

On Sun, Jun 7, 2015 at 11:04 PM, Sean Tymon <notifications@github.com>
wrote:

> it uses HMAC SHA-256 out of the box, but many other algorithms are
> available.
>
> The heavy lifting is done by another package -
> https://github.com/namshi/jose
>
> some other jwt libs use it too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tymondesigns/jwt-auth/issues/139#issuecomment-109803407>
> .
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by tymondesigns** [comment]
yes many libraries had the vulnerability at the time, but was addressed soon after it was discovered
