### ISSUE TITLE
Changing the JWT token in runtime for test purposes

### ISSUE THREAD

**Issue by jgrossi** [tymondesigns/jwt-auth#1393]
Hi, first, thanks for this amazing package, really. 😉

I'm using it with Lumen 5.5 and everything is working fine, btw. I'm returning custom JSON for the expired token, checking for `UnauthorizedHttpException` and `TokenExpiredException` exceptions, which is working fine.

I'd like to test this behavior with PHPUnit to make sure the returned JSON is according to what I'm expecting. This would be important for the app I'm developing.

I'd like to change the `exp` claim, actually. I can create a custom claim collection, and then trying to create a payload using the factory, but I cannot create a payload with an expired `exp` date, what makes sense, of course.

Do you know how can I test that? I'd like to make sure to pass through the request an expired JWT and to make sure those exceptions are called and my JSON response is correct. Then, any idea to how can I generate an expired JSON in runtime? 🤔🤔🤔

Thanks!

**Comment by jamesaspence** [comment]
I'm having this exact issue, almost a year later. Trying to write a test that ensures that my refresh works with an expired token (but before refresh ttl is expired). I did a bit of digging but it seems difficult to create the claims for a subject, since the default factory appears to handle that logic inside of protected methods.

**Comment by jgrossi** [comment]
@jamesaspence thanks for bringing this back. sorry, but I forgot to update (and close) this issue... what I'm doing is changing the `Carbon` date for testing. `Carbon` has a  `setTestNow()` method that allows you to change the current date, so you can "start" a test 5 days ago, and then your expiration stuff is gonna work.

in my case a token is created when the user is created, so that's why I change the date right after that, but in your case I think is before calling some route, for example.

so you can force setting the token header in the test, with a date "before" now, and then right before calling the route you change the date to now, then the route is gonna find a expired token, make sense?

```php
/** @test */
public function it_can_refresh_a_token_and_the_expire_date()
{
    Carbon::setTestNow(Carbon::now()->subDays(5));
    $user = factory(User::class)->create();
    Carbon::setTestNow();

    $original = $user->token->toArray();

    $user->token->refresh();

    $this->assertNotEquals($user->token->value, $original['value']);
    $this->assertNotEquals((string) $user->token->created_at, $original['created_at']);
    $this->assertGreaterThan($original['created_at'], $user->token->created_at);
}
```
I hope it helps. gonna close this issue for now, because this is a resonable solution IMHO.

**Comment by jamesaspence** [comment]
Nice! Thanks. I actually found a way (potentially) to get this working as well - I had to do a ton of tinkering and it was kinda a pain, so this seems the better way forward.

I'll attempt to clean up my attempt and test it, and post it when I get the chance (in case it helps somebody else)
