### ISSUE TITLE
Fatal error due to references to old interfaces (includes fixes)

### ISSUE THREAD

**Issue by jayhealey** [tymondesigns/jwt-auth#140]
Installing `0.6.*`, it looks like there's some references to old interfaces that have moved into a contracts namespace. Two interfaces (Storage & JWT) are being referenced and they've recently moved.

Replace `Tymon\JWTAuth\Providers\Storage\StorageInterface` with `Tymon\JWTAuth\Contracts\Providers\Storage` in `Tymon\JWTAuth\Blacklist`.

Replace `Tymon\JWTAuth\Providers\JWT\JWTInterface` with `Tymon\JWTAuth\Contracts\Providers\JWT` in `Tymon\JWTAuth\JWTManager`.

Make those changes (about 6 lines of code in all, including comments) appears to resolve the issue.

**Comment by tymondesigns** [comment]
Looks like packagist didn't update to the latest commit hash, as I fixed this in 811392db0799eed56cd120825e51b11c3be24074

Should be updated now though

Thanks
