### ISSUE TITLE
Hey, i am a beginner in laravel  so i need someone to help me

### ISSUE THREAD

**Issue by TinsaeFekadu** [tymondesigns/jwt-auth#1401]
After installing the 0.5.12 version of jwt-auth in my Laravel 5.3 project.
I'm getting the following error Interface 'Tymon\JWTAuth\Contracts\JWTSubject' not found

**Comment by jerguslejko** [comment]
Hey @TinsaeFekadu. The version that you are using (`v0.5.12`) does not have the `Tymon\JWTAuth\Contracts\JWTSubject` interface. This interface was introduced in `v1.0.0`.

I hope that helps.

**Comment by TinsaeFekadu** [comment]
Wow thanks bro it works now!
be blessed!!!

**Comment by jerguslejko** [comment]
Glad to help! Feel free to close the issue

**Comment by tymondesigns** [comment]
Thanks @jerguslejko
