### ISSUE TITLE
Wiki is wrong for custom claims

### ISSUE THREAD

**Issue by ftrotter** [tymondesigns/jwt-auth#1409]
The "attempt" function does not accept a second argument, as the wiki indicates. 

Instead we needed to call the "customClaims" function, before the attempt. 

The code works fine but the documentation is wrong. 

Thanks for the excellent project. 

Regards,
-FT

**Comment by tymondesigns** [comment]
The wiki is for version `0.5.*` only.
Now it is done with a setter e.g. `auth()->claims(['foo' => 'bar'])->attempt();`
