### ISSUE TITLE
token not provided

### ISSUE THREAD

**Issue by adrianopiro** [tymondesigns/jwt-auth#141]
somebody can help me? 
I'am new in Laravel and i'm trying to authenticate by jwt-auth, but I'm having problems.
when i trying to access some controller that have the construct middleware, like request below...
```
public function __construct()
	{
	    $this->middleware('jwt.auth');
	}
public function index() {
	        // dd(\Request::all());
		return view('cartas');
	}
```

i get the error >>>  {"error":"token_not_provided"}

i read the wiki, but not find a solution for this issue.

**Comment by tymondesigns** [comment]
The `jwt.auth` middleware requires that a token is present in the request. Since it will attempt to retrieve the authenticated user from it.

The response you are seeing comes from the middleware

**Comment by adrianopiro** [comment]
@tymondesigns ... thanks for reply. Can you give me an example hoe do it? I'am new with laravel and i'm getting some difficulties. How will be the route and controller with jwt-auth? Please, help me... kkkkk

**Comment by adrianopiro** [comment]
@tymondesigns i think that i'am understand somethings. I thought the authentication was made by jwt-auth, but actually it is made by auth controller, alright? I read in wiki "Creating a Token based on the users credentials" and thought was necessary a specific controller based in jwt-auth to authenticate. But don't need yap? We can use the default auth controller from laravel. This is it?

**Comment by tymondesigns** [comment]
You cannot use the laravel's AuthController, in its default form anyway.

This package is intended to be used when building an api, as a way of authenticating an incoming request.

I think you would benefit from some laravel training to be honest. I can highly recommend laracasts.com
