### ISSUE TITLE
Decode JWT Token

### ISSUE THREAD

**Issue by simplenotezy** [tymondesigns/jwt-auth#1414]
How to decode a JWT token in it's raw format?

Say I'd like to run:

   JWTAuth::invalidate('some_token');

Outputs an error: `A token is required`

**Comment by chrisbbreuer** [comment]
You need to set the token first since ^1.0.0. If you check the source you would realize that `invalidate()` does not accept a token value. Stick to a stable release I would recommend.

In your case `JWTAuth::setToken('some_token')->invalidate();` would work though!
