### ISSUE TITLE
How to use public key

### ISSUE THREAD

**Issue by Arkanius** [tymondesigns/jwt-auth#1416]
Is there a way to set and validate JWT public key ? 

I'm using 0.5.* version and the only config that I have is the `secret`in `config/jwt.php`

I'd like to give the public key to other users of app. 

I know that it's possible with `JWT` in other packages like:  `xaamin/jwt`

```
    'algorithm' => 'RS512',
    
    // ... Other stuff here
    
    'keys' => [
        'public' => '../keys/public_key.pem',
        'private' => '../keys/private_key.pem',
        
        'passphrase' => null,
    ],
```

Is there a way to do this here (any version)?

**Comment by tymondesigns** [comment]
you need to use `file://path/to/file.pem`

quite shocking to see https://github.com/xaamin/jwt has plagiarised this package by copying and pasting about 90% of the code, and claiming authorship of it

**Comment by Arkanius** [comment]
Thaks!

I figured out by using JOSE (included in your package). I didn't see that https://github.com/xaamin/jwt was just an copy/paste (an not a good one)...

That is really an absurd.
