### ISSUE TITLE
basic laravel auth not working on laravel 5.5

### ISSUE THREAD

**Issue by normanaranez** [tymondesigns/jwt-auth#1424]
the basic laravel auth not working anymore after some changes in config.app but the jwt login works fine.

**Comment by tymondesigns** [comment]
much more info is needed, versions of laravel, this package, what exact errors etc

**Comment by normanaranez** [comment]
it was fixed now. i just change the default guard to web not api. and declare the guard api to the controller of the jwt

**Comment by gregorskii** [comment]
I am running into this issue as well, except I am finding that other methods in the JWT controller will use the default guard when logged out, or at least try to redirect to the laravel /login screen.

I found the documentation states:

```
public function __construct()
{
      $this->middleware('auth.api', ['except' => ['login']]);
}
```

Is the correct way to setup the JwtAuthController http://jwt-auth.readthedocs.io/en/docs/quick-start/

Swapping it with:

```
public function __construct()
{
      $this->middleware('jwt.auth', ['except' => ['login']]);
}
```

fixes it.

Seems like auth.api does not exist as a middleware?

```
  #middleware: array:12 [▼
    "auth" => "Illuminate\Auth\Middleware\Authenticate"
    "auth.basic" => "Illuminate\Auth\Middleware\AuthenticateWithBasicAuth"
    "bindings" => "Illuminate\Routing\Middleware\SubstituteBindings"
    "can" => "Illuminate\Auth\Middleware\Authorize"
    "guest" => "App\Http\Middleware\RedirectIfAuthenticated"
    "throttle" => "Illuminate\Routing\Middleware\ThrottleRequests"
    "cors" => "Barryvdh\Cors\HandleCors"
    "entrust-gui.admin" => "Acoustep\EntrustGui\Http\Middleware\AdminAuth"
    "jwt.auth" => "Tymon\JWTAuth\Http\Middleware\Authenticate"
    "jwt.check" => "Tymon\JWTAuth\Http\Middleware\Check"
    "jwt.refresh" => "Tymon\JWTAuth\Http\Middleware\RefreshToken"
    "jwt.renew" => "Tymon\JWTAuth\Http\Middleware\AuthenticateAndRenew"
```

Is it possible to finish the laravel 5 branch and update the docs?

**Comment by tymondesigns** [comment]
The middleware is `auth:api` in the docs. github's formatting is much easier to read https://github.com/tymondesigns/jwt-auth/blob/develop/docs/quick-start.md

**Comment by gregorskii** [comment]
I see, but that's what I am saying. `auth:api` does not appear in my middleware list. Also when I update to this the auth methods start to hit the web redirects on auth failure.

**Comment by tymondesigns** [comment]
It is the one at the top of array you posted 
`'auth' => \Illuminate\Auth\Middleware\Authenticate::class`

the `:api` bit is a middleware parameter to specify the auth guard.

And the reason you are receiving html unauthorized responses is because you need to send the `Accept` header to indicate that it's ajax (json) request.

`Accept: application/json`

**Comment by gregorskii** [comment]
Ah... apologies not as familiar with laravel middleware.

I was getting thrown off because of the full arrays:

```
#middleware: array:12 [▼
    "auth" => "Illuminate\Auth\Middleware\Authenticate"
    "auth.basic" => "Illuminate\Auth\Middleware\AuthenticateWithBasicAuth"
    "bindings" => "Illuminate\Routing\Middleware\SubstituteBindings"
    "can" => "Illuminate\Auth\Middleware\Authorize"
    "guest" => "App\Http\Middleware\RedirectIfAuthenticated"
    "throttle" => "Illuminate\Routing\Middleware\ThrottleRequests"
    "cors" => "Barryvdh\Cors\HandleCors"
    "entrust-gui.admin" => "Acoustep\EntrustGui\Http\Middleware\AdminAuth"
    "jwt.auth" => "Tymon\JWTAuth\Http\Middleware\Authenticate"
    "jwt.check" => "Tymon\JWTAuth\Http\Middleware\Check"
    "jwt.refresh" => "Tymon\JWTAuth\Http\Middleware\RefreshToken"
    "jwt.renew" => "Tymon\JWTAuth\Http\Middleware\AuthenticateAndRenew"
  ]
  #middlewareGroups: array:2 [▼
    "web" => array:6 [▼
      0 => "App\Http\Middleware\EncryptCookies"
      1 => "Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse"
      2 => "Illuminate\Session\Middleware\StartSession"
      3 => "Illuminate\View\Middleware\ShareErrorsFromSession"
      4 => "App\Http\Middleware\VerifyCsrfToken"
      5 => "Illuminate\Routing\Middleware\SubstituteBindings"
    ]
    "api" => array:3 [▼
      0 => "throttle:60,1"
      1 => "bindings"
      2 => "Barryvdh\Cors\HandleCors"
    ]
  ]
```

It looked like api:auth did not exist, I thought that was the standard web auth mechanism.

I will swap it back and add the accept header.

**Comment by gregorskii** [comment]
Yep, this appears to work better, however, I had to leave the default guard to `web` to keep regular Laravel auth working.

**Comment by mhelaiwa** [comment]
@gregorskii I changed my code like you said and my default guard to `web` but I am getting this error:
`Method Illuminate\Auth\SessionGuard::factory does not exist.`

Auth controller
```
class AuthController extends Controller
{
    /**
     * Create a new AuthController instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:api', ['except' => ['login']]);
    }
}
```
My config
```
'defaults' => [
      'guard' => 'web',
      'passwords' => 'users',
],
```
My routes
```
Route::group(['middleware' => 'api','prefix' => 'auth'], function ($router) {
    Route::post('login', 'AuthController@login');
    Route::post('logout', 'AuthController@logout');
    Route::post('refresh', 'AuthController@refresh');
    Route::post('me', 'AuthController@me');
});
```

I have:
`Laravel Framework 5.6.23`
`JWT 1.0.0`

**Comment by mhelaiwa** [comment]
#1428 Same issue was solved here
