### ISSUE TITLE
Token Refresh / Expiry / Invalidation

### ISSUE THREAD

**Issue by kiwina** [tymondesigns/jwt-auth#143]
Found and strange behavior!

I refresh a token with blacklist enabled witch is expired!

$token = JWTAuth::parseToken()->refresh();

Now this token should be invalidated for any further requests but since it's expired it's not added to the invalidation list, so i could use it to get a new token witch is i think a little odd

**Comment by tymondesigns** [comment]
Yea looks like something I will need to fix.

I will need to add some extra logic around blacklisting tokens, since this is because an expired token is never added to the blacklist, disregarding the fact that it can be refreshed.

Thanks!

**Comment by doberlion** [comment]
it will work with Laravel 5.1?

**Comment by amilgaul** [comment]
@tymondesigns  any update for refresh token. 

Thanks.

**Comment by tymondesigns** [comment]
Will work on this soon

**Comment by tdhsmith** [comment]
:+1:
