### ISSUE TITLE
怎么检查token是否过期？

### ISSUE THREAD

**Issue by boorcode** [tymondesigns/jwt-auth#1430]
怎么检查token是否过期？

**Comment by tymondesigns** [comment]
I have no idea what this means

**Comment by 2637977081** [comment]
@tymondesigns 
he say:"How to check if the token expires? "----------from goole translate [Chinese to English] 
We have used “jwt” to give an expiration time，but how do we get it

**Comment by 2637977081** [comment]
`Jwts.parser().setSigningKey(secretKey).parseClaimsJws(jwt).getBody().getExpiration();`

可以使用getBody获取过期时间，过期时间与当前时间进行判断，但前提是你需要将过期时间存入jwt中
