### ISSUE TITLE
hi,How do I check that token is expired?please.

### ISSUE THREAD

**Issue by boorcode** [tymondesigns/jwt-auth#1431]
Hi,please,How do I check that token is expired?

**Comment by ozdemir08** [comment]
There is no direct method to do that. You should first try to make an authentication and if token is expired, then you can catch it by `TokenExpiredException`. 
Note that if `refresh_ttl` ends, it will also caught by `TokenExpiredException`

```
try{
    $user = JWTAuth::parseToken()->authenticate();
} catch (TokenExpiredException $e){
    return response()->json(['Page must be refreshed']);
} 
```

**Comment by tymondesigns** [comment]
You can call `JWTAuth::parseToken()->check()` (for v0.5.*) which will return a boolean or `auth()->check()` for v1.0.*

**Comment by stevenkitter** [comment]
@tymondesigns hello guys. it is just for validator not for expired.how can i know it was expired exactly.

**Comment by jehadja** [comment]
Hi , Simply JWT is base64 coded HEADER.PAYLOAD.VERIFY_SIGNATURE
we need exactly PAYLOAD
it will look something like 
```
{
  "sub": "1234567890",
  "name": "John Doe",
  "exp":"1516235022",
  "iat": 1516239022
}
```
covert it to json and then compare 👍 
```
$dataRaw = explode(".",$token);
         $dataRaw =  base64_decode ($dataRaw[1]);
         $now = time();
         $dataRaw = json_decode($dataRaw);
         if($dataRaw->exp < $now-60){
           return "No_Need";
         }
```

**Comment by hopeseekr** [comment]
This is somethign that should be in the library. I mean, come on.

**Comment by hopeseekr** [comment]
I figured it out! @boorcode:

```php
\JWTAuth::parseToken()->getClaim('exp');
```

It will throw `TokenExpiredException` if the token is expired.
