### ISSUE TITLE
Laravel 5.1

### ISSUE THREAD

**Issue by Exelord** [tymondesigns/jwt-auth#144]
Its not installing with Laravel 5.1 :/  - Composer error

**Comment by tymondesigns** [comment]
which version are you attempting to install ?

**Comment by WilsonFpz** [comment]
+1 tymon/jwt-auth dev-master requires illuminate/http ~4.0

**Comment by Exelord** [comment]
yup, I just run "composer require 'tymon/jwt-auth:dev-master'" and there is a problem. But version 0.5.3 works very well

**Comment by tymondesigns** [comment]
dev-master is intended to target laravel 4, please use `0.5.*` or `0.6.*@dev` for laravel 5 and 5.1

**Comment by tymondesigns** [comment]
You should avoid using `dev-master` in any case since it's prone to change at any time
