### ISSUE TITLE
wrong installation instruction on http://jwt-auth.readthedocs.io/en/docs/laravel-installation/

### ISSUE THREAD

**Issue by babakzarrinbal** [tymondesigns/jwt-auth#1444]
on http://jwt-auth.readthedocs.io/en/docs/laravel-installation/
what the fu*** ???
i nearly gone mad over this ...
wrong typo in "add service provider" section
    Tymon\JWTAuth\Providers\**LaravelServiceProvider**::class,

 LaravelServiceProvider should be JWTAuthServiceProvider
please fix it.

**Comment by tymondesigns** [comment]
> LaravelServiceProvider should be JWTAuthServiceProvider

No it shouldn't. You are reading the docs for the wrong version. Look at the readme https://github.com/tymondesigns/jwt-auth

**Comment by andrey-bahrachev** [comment]
@tymondesigns Well, the thing is if you install the package by `composer require tymon/jwt-auth` command it installs 0.5.* version which is the latest stable, not just the latest one as the doc says, so that's misleading.

**Comment by samoilenkoevgeniy** [comment]
@babakzarrinbal @andrey-bahrachev they are right.
