### ISSUE TITLE
Interface 'Tymon\JWTAuth\Contracts\JWTSubject' not found

### ISSUE THREAD

**Issue by lbottoni** [tymondesigns/jwt-auth#1448]
Hi,
i have tried use the guide
[quick-start.md](https://github.com/tymondesigns/jwt-auth/blob/develop/docs/quick-start.md)

**version in composer**: "tymon/jwt-auth": "0.5.*"

### User Model
`<?php

namespace App\Models;

use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\Project;

class User  extends Authenticatable implements JWTSubject
{
	use Notifiable;

	/**
	 * Get the identifier that will be stored in the subject claim of the JWT.
	 *
	 * @return mixed
	 */
	public function getJWTIdentifier()
		{
			return $this->getKey();
		}

	/**
	 * Return a key value array, containing any custom claims to be added to the JWT.
	 *
	 * @return array
	 */
	public function getJWTCustomClaims()
		{
			return [];
		}
	/**
	 * Questi attributi possono essere modificati
	 *
	 * @var array
	 */
	protected $fillable = [
		'name', 'email', 'password',
	];

	/**
	 * Questi attributi non potranno essere visti nella chiamata rest
	 *
	 * @var array
	 */
	protected $hidden = [
		'password', 'remember_token'
	];

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function projects(){
		$propertyInProject="user_id";
		$propertyForeignWithProject="id";
		return $this->hasMany(Project::class,$propertyInProject,$propertyForeignWithProject);
	}

}
`

before use the guide the model worked fine (i retrived always the token).

### ERROR

> (1/1) FatalErrorExceptionInterface 'Tymon\JWTAuth\Contracts\JWTSubject' not found
> --
> in User.php (line 12)

**Comment by tymondesigns** [comment]
looks like you are looking at the docs for version `1.0.0` instead of `0.5.*`.. You will either need to update to `1.0.0` or see the wiki for `0.5` docs

**Comment by prasathkarnan** [comment]
/**
 * Get the identifier that will be stored in the subject claim of the JWT.
 *
 * @return mixed
 */
public function getJWTIdentifier()
	{
		return $this->getKey();
	}

/**
 * Return a key value array, containing any custom claims to be added to the JWT.
 *
 * @return array
 */
public function getJWTCustomClaims()
	{
		return [];
	}
/**
 * Questi attributi possono essere modificati
 *
 * @var array
 */
protected $fillable = [
	'name', 'email', 'password',
];

/**
 * Questi attributi non potranno essere visti nella chiamata rest
 *
 * @var array
 */
protected $hidden = [
	'password', 'remember_token'
];

/**
 * @return \Illuminate\Database\Eloquent\Relations\HasMany
 */
public function projects(){
	$propertyInProject="user_id";
	$propertyForeignWithProject="id";
	return $this->hasMany(Project::class,$propertyInProject,$propertyForeignWithProject);
}

**Comment by thiagopetherson** [comment]
You wrote "Suject". The correct is "Subject".

**Comment by gauravthinktanker** [comment]
i have a same issue. 
Interface "Tymon\JWTAuth\Contracts\JWTSubject" not found {"exception":"[object] (Error(code: 0): Interface \"Tymon\\JWTAuth\\Contracts\\JWTSubject\" not found at user.php.
version is "tymon/jwt-auth": "^2.0",
