### ISSUE TITLE
Logout??!?!?!?!?!?!?!

### ISSUE THREAD

**Issue by lbottoni** [tymondesigns/jwt-auth#1449]
After 2 DAYS i can not understand how to do a logout method!!!

```
	public function logout(Request $request)
		{
			$user = JWTAuth::parseToken()->toUser();
			JWTAuth::invalidate(JWTAuth::parseToken());
			$authuser=Auth::user();
			$user2 = JWTAuth::parseToken()->toUser();
			return response()->json([$user,$authuser,$user2],200);
```

or get always a user autenticated or get a exception in all test!?but, the documentation don't say nothig about logout method!!!!

**Comment by lbottoni** [comment]
$token=JWTAuth::getToken();JWTAuth::invalidate($token);

**Comment by julianpoma** [comment]
This is working for me

`public function logout(Request $request) {
        $token = JWTAuth::getToken();
        JWTAuth::invalidate($token);
        return response()->json(['message' => 'The token has been blacklisted'], 200);
    }`

**Comment by bradroberts** [comment]
You may want the extra security of invalidating the token on the server, but for many (simple) applications, removing the token from the client will effectively logout the user. In my apps, that usually looks something like this in Javascript: `localStorage.removeItem('auth_token');` replacing "auth_token" with whatever variable you're using.

**Comment by seekcx** [comment]
Perhaps you should look at this document. http://jwt-auth.readthedocs.io/en/develop/auth-guard/
