### ISSUE TITLE
Error in time to live time unit

### ISSUE THREAD

**Issue by matteoerrera** [tymondesigns/jwt-auth#1454]
In this file:
`jwt-auth/config/config.php
`
at row 93 there is a comment that say
`
    | Specify the length of time (in minutes) that the token will be valid for.
`

But the real time unit used by jwt-auth are the seconds.

So if I write 10 minutes, after 10 seconds the token expire

**Comment by tymondesigns** [comment]
I can't really see how this would happen tbh.. since lots of other people would have raised this issue. Also It clearly adds minutes when creating the exp claim - https://github.com/tymondesigns/jwt-auth/blob/develop/src/Claims/Factory.php#L140
