### ISSUE TITLE
Questions generate token

### ISSUE THREAD

**Issue by roydekleijn** [tymondesigns/jwt-auth#1459]
I use version 1.0.0

Normally I create a token like this: Auth::attempt($credentials)
With username and password.

I also have the case that users can login with their social account (google/twitter), in this case I only have the social_id. How can I generate a token based on this social_id? which is also stored in my DB.

Thanks,
Roy

**Comment by tymondesigns** [comment]
You could get the user object from the social id and use `$token = Auth::login($user);`

**Comment by roydekleijn** [comment]
thanks, which is better?

Auth::fromUser or Auth::login

**Comment by tymondesigns** [comment]
you should use `Auth::login()`
