### ISSUE TITLE
How to get caching support when use authenticate based on token and generate token by user

### ISSUE THREAD

**Issue by rogeryu23** [tymondesigns/jwt-auth#146]
Right now seems it reads the database by using model class, 
but in real production, seems reading db each time for validate a token or generate a new token is expensive

I hope can read user info from memcache. Is there any easy way of doing this

**Comment by tymondesigns** [comment]
validating a token will not touch the database (unless you have cache driver set to db and have blacklist enabled)

Could you post your code, So I can better understand what you are trying to achieve?

**Comment by rogeryu23** [comment]
i pretty much copy the middleware code and change a bit1 ) are you saying    $user = JWTAuth::setToken($token)->authenticate($token); does not call db, it is just decoding? If so then no problem at all.
2) The other question i have is each time user logins in,          return JWTAuth::fromUser($user);is called,  what does this fromUser do?  how many fields of user does it grab to construct the token?

3） no cache driver set to db, it is set to file right now, but i am not sure what blacklist you talk about, do you mean the used token, if so i think right now is turned on. maybe by default turned on?


this is from middleware        $token = $request->header(Constants::get('http_header.x_auth_token'));        if (!$token) {            return $this->respondBadRequestError(                Constants::get('error_code.token_not_provided'),                trans('errors.token_not_provided'));        }
        try {            $user = AuthManager::authenticate($token);        } catch (BaseException $e) {            return $this->getJsonResponseByException($e);        }
        if (!$user) {            return $this->respondNotFoundError(                Constants::get('error_code.token_invalid'), trans('errors.token_invalid'));        }
        $this->events->fire('tymon.jwt.valid', $user);
        return $next($request);    }

This is AuthManager which is a helper
class AuthManager{    use JsonResponseTrait;
    public static function authenticate($token)    {        if (!$token) {            throw new AuthException(                Constants::get('error_code.token_not_provided'),                trans('errors.token_not_provided'));        }
        try {            $user = JWTAuth::setToken($token)->authenticate($token);
        } catch (TokenExpiredException $e) {            throw new AuthException(                Constants::get('error_code.token_expired'),                trans('errors.token_expired'), $e);        } catch (JWTException $e) {            throw new AuthException(                Constants::get('error_code.token_invalid'),                trans('errors.token_invalid'), $e);        }
        if (!$user) {            throw new ResourceNotFoundException(                Constants::get('error_code.user_not_found'),                trans('errors.user_not_found'));        }
        return $user;    }
    public static function getRefreshToken($token)    {        if (!$token) {            throw new AuthException(                Constants::get('error_code.token_not_provided'),                trans('errors.token_not_provided'));        }
        try {            $newToken = JWTAuth::setToken($token)->refresh();        } catch (TokenExpiredException $e) {            throw new AuthException(                Constants::get('error_code.refresh_token_expired'),                trans('errors.refresh_token_expired'), $e);        } catch (JWTException $e) {            throw new AuthException(                Constants::get('error_code.token_invalid'),                trans('errors.token_invalid'), $e);        }
        return $newToken;    }
    public static function getTokenByEmail(User $user)    {        return JWTAuth::fromUser($user);    }}Date: Tue, 16 Jun 2015 12:40:57 -0700
