### ISSUE TITLE
login except doesn't seems to work.

### ISSUE THREAD

**Issue by roydekleijn** [tymondesigns/jwt-auth#1465]
I want to use the auth middleware except for one endpoint, but middleware excepts doesn't seem to work.

Versions I use:
laravel/lumen-framework   v5.5.2  
ymon/jwt-auth            1.0.0-rc.1 

[bootstrap/app.php]
```
$app->withFacades();
$app->withEloquent();

$app->routeMiddleware([
    'auth' => App\Http\Middleware\Authenticate::class,
]);

$app->register(App\Providers\AuthServiceProvider::class);
$app->register(Tymon\JWTAuth\Providers\LumenServiceProvider::class);
```

[config/auth.php]
```
<?php
return [
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
    'guards' => [
        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
    ],
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model'  => \App\User::class,
        ]
    ],
];
```

[routes/api.php]
```
$router->group([
    'middleware' => 'auth:api',
    'prefix' => 'auth'
], function ($router) use ($router) {
    $router->post('login', 'AuthController@login');
    $router->post('logout', 'AuthController@logout');
    $router->post('refresh', 'AuthController@refresh');
    $router->post('me', 'AuthController@me');
});
```

[AuthController.php]
My understanding is that for all endpoints the auth middleware is used, except for login.

```
class AuthController extends Controller
{
    /**
     * Create a new AuthController instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['login']]);
    }

    /**
     * Get a JWT via given credentials.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function login(Request $request)
    {
        $credentials = $request->only(['email', 'password']);
        var_dump($request); exit;
    }

}
```

It doesn't reach the var_dump, but I see:
```
{
"error": "Unauthorized"
}
```

It works if I remove the auth middleware. I wonder what I do wrong.

**Comment by roydekleijn** [comment]
well, it only works when moving the 'login' route outside the group...

**Comment by tymondesigns** [comment]
looks like it's because you have `'middleware' => 'auth:api'` on your route group

**Comment by roydekleijn** [comment]
ok but that is the same as the documentation says, right ?

http://jwt-auth.readthedocs.io/en/develop/quick-start/

**Comment by roydekleijn** [comment]
Is the documentation wrong with this ?

**Comment by hjJunior** [comment]
I am getting the same error

**Comment by loperd** [comment]
> looks like it's because you have `'middleware' => 'auth:api'` on your route group

Hi. I have a question. 
Please answear me.
How to unlogin user token? I tried use `auth('api')->logout()` but this don't work for me,
the token still could be used..

Thanks!

**Comment by infotech-computing** [comment]
I have the same isue. Did anyone get the solution?
