### ISSUE TITLE
Support laravel 5.6

### ISSUE THREAD

**Issue by Belphemur** [tymondesigns/jwt-auth#1479]
### Subject of the issue
Laravel released the 5.6, it would be nice to have this packet support it

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 5.6.0
| Package version   | 1.0.0
| PHP version       | 7.2.2

**Comment by bkremenovic** [comment]
I have already created pull request, and he approved it and merged. We just need to update packagist.

**Comment by bitfumes** [comment]
Not working with laravel 5.6. Its giving this error 
![screen shot 2018-02-08 at 18 20 39](https://user-images.githubusercontent.com/26225409/35973813-d0deb624-0cfc-11e8-8780-3720dd45efc5.jpg)

Please update it soon

**Comment by JBtje** [comment]
Use: "tymon/jwt-auth": "dev-master" and it works. "1.0.0-rc.1" does indeed not (yet) work.

edit: ignore that... the dev-master on composer != the dev-master on git... and doesn't work

**Comment by bitfumes** [comment]
Okay thanks for this, it included properly but 
`php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"`
this command not publishing anything

**Comment by bogumilkorek** [comment]
Try to use "tymon/jwt-auth": "dev-develop" in composer.json, it worked in my case.

**Comment by bitfumes** [comment]
Ohh got it, I have to publish via this command
`php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"
`

not with this 

`php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
`

Thanks everyone.

**Comment by micheleangioni** [comment]
`"tymon/jwt-auth": "dev-develop"` should fix the problem for everyone, but really looking forward for a new tagged release :)

**Comment by tymondesigns** [comment]
`1.0.0-rc.2` tagged 👍

**Comment by bitfumes** [comment]
thanks @tymondesigns

**Comment by micheleangioni** [comment]
@tymondesigns good job, thanks! :)

**Comment by preciousgeorge** [comment]
I keep getting this error must Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to App\Http\Controllers\API\Auth\NewLoginController::__construct() must implement interface Tymon\JWTAuth\Contracts\Providers\Auth, null given in file /Users/soullounge/Development/php_devs/EazyTender/app/Http/Controllers/API/Auth/NewLoginController.php on line 31

Somebody please help
Laravel 5.6
"tymon/jwt-auth": "dev-develop"

N.B no matter what version of jwt-auth i use, it  is the same error. Please, help as this is really urgent...

**Comment by Belphemur** [comment]
You should open a new issue for that.
And I don't see why you want your controller to implement the interface
Tymon\JWTAuth\Contracts\Providers\Auth

**Comment by preciousgeorge** [comment]
@Belphemur I sorted it out by running 
php artisan config:clear
php artisan cache:clear 
The problem was that i had an older version installed before and when i decided to use this version i did not clear the config and cache. Thanks for the reply. Meanwhile, i don't know if you can help me with. I am trying to implement multi authentication using 2 tables. I currently am running "tymon/jwt-auth": "1.0.0.rc-2". i have done everything i found online but it still defaults to the User model.             
          `Config::set( 'jwt.user', 'App\Model\Vendor');`
         `Config::set('auth.providers.users.model', App\Model\Vendor::class);`
         `$credentials = $request->only( ['email', 'password' ]);`
         `$t = JWTAuth::attempt($credentials);`

**Comment by douglasjunior** [comment]
Checkout this tutorials
- https://arjunphp.com/laravel-5-6-rest-api-jwt-authentication/
- https://appdividend.com/2018/02/24/laravel-jwt-authentication-tutorial/

**Comment by tommie24** [comment]
Run 
composer require tymon/jwt-auth:dev-develop --prefer-source
