### ISSUE TITLE
Any plans to support Lumen?

### ISSUE THREAD

**Issue by nschirmer** [tymondesigns/jwt-auth#148]
Hi,

I'm building a backend API using Lumen and will be using JWT for authentication. Came across your package, which looks perfect, but it seems we can't just drop any Laravel package into Lumen like I thought...

Basically the config_path function is not available in Lumen as it doesn't support publishing via artisan yet, which breaks things. :)

Thanks for any help you can provide!

**edit: oops, I just discovered duplicate issue #91 -- my bad.**

**Comment by tymondesigns** [comment]
No worries.. Hope to get something together over the weekend

**Comment by nickrouty** [comment]
+1 - I came here via dingo/api, but can't seem to get this package configured. Would be great!

**Comment by nschirmer** [comment]
@nickrouty I came across a tutorial recently for easily integrating JWT-Auth with Lumen. I had already gotten it integrated before finding it, but it may very well help you out a lot! http://laravelista.com/json-web-token-authentication-for-lumen/

In the end, especially after reading the end of that tutorial (and speaking with the author), I decided to just switch over to Laravel 5.1 instead of using Lumen. The API I'm building will be bigger than just a few routes, with cronjobs and queue workers, and the author told me the developer of Lumen basically confirmed it's intended more for small APIs with just a few routes.

Good luck!

**Comment by nickrouty** [comment]
@nschirmer Thanks for the reply, much appreciated. I may end up going that route. For the time being, I'm trying to keep it simple and was hoping Lumen vs. Laravel would help with that simplicity.. that may not be the case ;)

**Comment by nschirmer** [comment]
Yeah, Lumen really does _sound_ nice but I'm afraid it's not fully there yet. For one, I was really struggling trying to get route groups to work properly (when embedding them within other groups). Couldn't figure out what I was doing wrong until the suggestion to just use Laravel came up. Once I switched, my routes started working as-is without any modifications (besides switching from $app-> to Route::) so it was just a bizarre issue with Lumen.

For simplicity though, Lumen still seems like a good choice, and it can only get better as they improve it.

Sorry for the tangent on this issue, Tymon. :)
