### ISSUE TITLE
Auth::attempt() without generating token?

### ISSUE THREAD

**Issue by SzymonLisowiec** [tymondesigns/jwt-auth#1483]
### Auth::attempt() without generating token?
Can I use `Auth:attempt($data)` without getting token? I need few steps:
1. `if(Auth::attempt($data)){` //here without generating token. Currently `attempt` returning token :|
2. Check user status
3. only to generate token by `JWTAuth::fromUser(Auth::user())`

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no 
| Framework         | Laravel
| Framework version | 5.6.0
| Package version   | dev-develop
| PHP version       | 7.2.1

**Comment by tymondesigns** [comment]
you can use `Auth::validate($credentials)`

**Comment by SzymonLisowiec** [comment]
but `Auth::validate` don't setting `Auth::user`

**Comment by tymondesigns** [comment]
If you want the user to be set aswell then use `Auth::once($credentials)`

**Comment by SzymonLisowiec** [comment]
Ok, Thanks :D
