### ISSUE TITLE
Can't Run API Laravel in Heroku but not in localhost

### ISSUE THREAD

**Issue by baguskah** [tymondesigns/jwt-auth#1485]
### Success run API Laravel in Localhost but in Heroku doesn't
I use JWT for auth api, when hit with postman in localhost, it work but when deploy in heroku token jwt always invaild and always turn "message": "Unauthenticated." 

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6
| Package version   | 1.x.y
| PHP version       | 7.x.y

**Comment by baguskah** [comment]
just got the problem, JWT_SECRET in .env wasn't deployed to heroku server, i have to add JWT_SECRET manually in Setting Application Dashboard in Heroku. Solved

**Comment by mohamoha6200** [comment]
Could you please tell me if you are using any specific buildpack in Heroku are you using PHP buildPack ?

**Comment by salomechemiat** [comment]
> ### Success run API Laravel in Localhost but in Heroku doesn't
> I use JWT for auth api, when hit with postman in localhost, it work but when deploy in heroku token jwt always invaild and always turn "message": "Unauthenticated."
> 
> ### Your environment
> Q	A
> Bug?	no
> New Feature?	no
> Framework	Laravel
> Framework version	5.6
> Package version	1.x.y
> PHP version	7.x.y

I'm currently facing the same problem. But this time, it works on my postman but does not work on my frontend
please help
