### ISSUE TITLE
how to send the token by the header and not by the url

### ISSUE THREAD

**Issue by lCHECHOl** [tymondesigns/jwt-auth#1488]
### My environment

| homestead | vagrant
| Bug?              | no 
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 5.5
| PHP version       |  7.1

thanks in advance

**Comment by josh9060** [comment]
Use Laravel's response helper to return the token in the header.

```
return response(200)->header( Put token in here );
```

Is this what you are trying to achieve?

**Comment by lCHECHOl** [comment]
This is my code, how would it be? 

what I want is that all the tokens that I use are sent by the header for security, none should be for the url

public function signin(Request $request)
    {
      $this->validate($request,[
        'user_email' => 'required|email',
        'password' => 'required|min:6',
      ]);

      $user_email = $request->input('user_email');
      $password = $request->input('password');

      if ($user = User::where('user_email', $user_email)->first()) {
        $credentials = [
          'user_email' => $user_email,
          'password' => $password,
        ];

        $token = null;

        try {
            if (!$token = JWTAuth::attempt($credentials)) {
              return response()->json([
                'error' => 'El correo ó la contraseña son incorrectos'
              ],404);
            }
        } catch (JWTAuthException $e) {
            return response()->json([
              'error' => 'failed_to_create_token',
            ],404);
        }

        $response = [
          'success' => 'Usuario Logueado',
          'Usuario' => $user,
          'token' => $token
        ];
        return response()->json($response, 201);
      }
       $response =[
         'error' => 'Ha ocurrido un error durante el logueo al sistema',
       ];
       return response()->json($response,404);
    }

**Comment by josh9060** [comment]
I believe you could so something like this:

```
return response()
    ->header( Token in here! )
    ->json($response, 201);
```

Double check with the docs - but I think that should work!

But, in most situations I would just return the token in the response body.

**Comment by lCHECHOl** [comment]
try placing the code as you say but this one says this
![image](https://user-images.githubusercontent.com/13172977/36444604-c124eefa-1649-11e8-9249-69ceb01e99df.png)
![image](https://user-images.githubusercontent.com/13172977/36444642-debe3b42-1649-11e8-9608-1af7e2d79dad.png)
I'm using postman to prove everything, what am I doing wrong?
The only thing I saw about passing the token via http with the header is this, but I do not understand
![image](https://user-images.githubusercontent.com/13172977/36444888-86ec999e-164a-11e8-9cce-c71ce8aa249f.png)

**Comment by lCHECHOl** [comment]
I already knew how to send the token by the header in the following way:
![image](https://user-images.githubusercontent.com/13172977/36449617-4ea1b272-1659-11e8-8360-2812f20345ab.png)

![image](https://user-images.githubusercontent.com/13172977/36449646-655127b4-1659-11e8-9694-159e3da28679.png)

but I get another question, how do I recover the token in another view so that I do not mark the token is required if something like this happens:

![image](https://user-images.githubusercontent.com/13172977/36449695-867b4870-1659-11e8-9553-14de8ed0e4be.png)

if I pass the token by url it works, but it's not what I need

![image](https://user-images.githubusercontent.com/13172977/36449746-b6f6ecc0-1659-11e8-80bf-78f9c2b7ce21.png)
