### ISSUE TITLE
Issues with laravel 5.1 and middleware

### ISSUE THREAD

**Issue by vincent-herlemont** [tymondesigns/jwt-auth#149]
Hello,

In laravel 5.1 there aren't 'before' in the Route API, we need to use 'middleware' but laravel doesn't arrive to find a 'jwt-auth' (it's normally)
```
ReflectionException in Container.php line 736:
Class jwt-auth does not exist
````

```php
Route::get('/restricted', [
   'middleware' => 'jwt-auth',
   function () {
       $token = JWTAuth::getToken();
       $user = JWTAuth::toUser($token);

       return Response::json([
           'data' => [
               'email' => $user->email,
               'registered_at' => $user->created_at->toDateTimeString()
           ]
       ]);
   }
]);
```
It's possible to create a new middleware for communicate but what it the best practice for make it ?

**Comment by tymondesigns** [comment]
Please see the wiki https://github.com/tymondesigns/jwt-auth/wiki/Authentication#middleware-and-filters
