### ISSUE TITLE
Auth attempt with password as md5 ?

### ISSUE THREAD

**Issue by ouraios** [tymondesigns/jwt-auth#1490]
I'm using a legacy and database and for now we cant change the users password to something else than md5, how can i use JWTAuth attempt method with an md5 password since apparently it always hash incoming password with bcrypt ?

**Comment by leewanvu** [comment]
Hi @ouraios 
You should create a custom hasher(md5).
Like that: https://github.com/typetokrish/Laravel-Custom-Hashing
Hope that link will help you.

**Comment by ahmedsafadii** [comment]
have the same issue :( the top solution is not working anymore
