### ISSUE TITLE
Non-static method Tymon\JWTAuth\JWTAuth::fromUser() should not be called statically

### ISSUE THREAD

**Issue by hadikmsh** [tymondesigns/jwt-auth#1495]
### Non-static method Tymon\JWTAuth\JWTAuth::fromUser() should not be called statically
Hi
thanks for your great package. I recently update my packages and after that i got this exception when use  JWTAuth::fromUser() ;
how can i fix this?
thanks.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 5.5
| Package version   | 1.x.y
| PHP version       |  7.2

### Steps to reproduce
use JWTAuth::fromUser() 

### Expected behaviour
make a token from a user model.
### Actual behaviour
throw an exception Non-static method Tymon\JWTAuth\JWTAuth::fromUser() should not be called statically

**Comment by hadikmsh** [comment]
its because of use wrong namespace Tymon\JWTAuth\JWTAuth instead of  JWTAuth ;

**Comment by P4Thi0ut** [comment]
You actually have to define the facade in **app/config.php** in order to use just JWTAuth;
so yeah, use **JWTAuth;** or alternatively : **use Tymon\JWTAuth\Facades\JWTAuth;**
