### ISSUE TITLE
Error updating and publishing package

### ISSUE THREAD

**Issue by readfordna** [tymondesigns/jwt-auth#1509]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel 
| Framework version | 5.6.7
| Package version   | 1.x.y
| PHP version       | 7.1.3

### Steps to reproduce
updated composer.json to include the following require package: "tymon/jwt-auth": "1.0.*"

composer update

and also

php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"

                 
### Expected behaviour
package installed with out error.

### Actual behaviour
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 1 update, 0 removals
  - Installing symfony/polyfill-util (v1.7.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.7.0): Loading from cache
  - Installing namshi/jose (7.2.3): Loading from cache
  - Updating tymon/jwt-auth (1.1.x-dev => 1.0.0-rc.2): Loading from cache
namshi/jose suggests installing phpseclib/phpseclib (Allows to use Phpseclib as crypto engine, use version ^2.0.)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:
                                                                    
  Class 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider' not found  
                                                                    

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

############

php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"

In ProviderRepository.php line 208:
                                                                    
  Class 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider' not found

**Comment by djbobbydrake** [comment]
Got the same issue. Followed the docs (http://jwt-auth.readthedocs.io/en/develop/laravel-installation/). Worked fine thereafter. I replaced `Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,` with `Tymon\JWTAuth\Providers\LaravelServiceProvider::class` in my app.php.

**Comment by readfordna** [comment]
Thanks for the help, djbobbydrake. that solved the problem.
