### ISSUE TITLE
Unable authenticate with invalid token

### ISSUE THREAD

**Issue by james-daddies** [tymondesigns/jwt-auth#151]
I am getting `Unable authenticate with invalid token.` 401 responses when I am accessing protected API routes (using DIngo with JWT auth). I login successfully and get a token returned. I can't find that error string so I don't know if this is on JWT side or Dingo side.

    $auth = Sentinel::stateless(Input::only(['email', 'password']));
    
    if (!$auth) throw new UnauthorizedHttpException('JWTAuth', 'Username or password is not correct');
    
    return ['token' => JWTAuth::fromUser($auth), 'user' => $auth];

**Comment by tymondesigns** [comment]
Not sure what could be the issue here. I have a feeling it's on the dingo side. A composer update might solve this

**Comment by tymondesigns** [comment]
Assuming resolved

**Comment by james-daddies** [comment]
Wasn't resolved, but ended up removing auth requirement anyways. Agree that dingo might be the problem.

**Comment by tymondesigns** [comment]
Ah ok.. You might be interested to know i've added Sentinel support out of the box in the next release - https://github.com/tymondesigns/jwt-auth/blob/develop/src/Providers/Auth/Sentinel.php

**Comment by james-daddies** [comment]
Ohh, might be useful for another project. Thanks!
