### ISSUE TITLE
Issues when updating from 0.5.* to 1.0.0*

### ISSUE THREAD

**Issue by Mr-Anonymous** [tymondesigns/jwt-auth#1519]
I am currently using jwt-auth version 0.5.* on Laravel 5.3. For frontend I use Angular 1.3 with Satellizer. 

My question is: when I upgrade my jwt-auth to version 1.0.0 and Laravel to 5.6, will the existing users be unable to login anymore until they update their app? From what I read I understand that with 1.0.0, the token is encrypted. So, what happens after I update this plugin and when users who are using my old version of the app sends the unencrypted token for the request? Satellizer plugins stores the jwt auth in localstorage and adds this token to the header when sending requests. So if the users does not update their app, they will be sending the old token that was stored in their device even after I update jwt-auth to 1.0.0 in my server. What happens in these cases? I need to know what to anticipate so I know if it is safe to update jwt-auth to 1.0.0 on a live production server.

Can someone kindly share their experience please?

**Comment by johankladder** [comment]
Had some experience today. Also upgraded to the 1.0.0-rc version.

In my experience the old tokens are not valid anymore (in my situation). I think this happened because the token is signed with other variables (like the JWT-secret etc) then the previous ones. 

In my case, the users needed to log in again because of this, but this wasn't a big deal for me.

**Comment by Mr-Anonymous** [comment]
Hi @johankladder Thank you for confirming that. I guess I might need to make sure proper http interceptors are set in my app so soon after the update, as soon as the old token becomes invalid, they are redirected to login again. As long as I can upgrade this on the server without needing to change anything in the frontend, it should be fine I guess. Thanks again for confirming that.

When you did the update, may I ask how did you change it from 0.5.* version to 1.0.0.* version?

Do I need to:

1. Remove the `JWTAuthServiceProvider` from `providers` array, `JWTAuth`  from `aliases` and `JWTFactory` from `Facade`  in `config/app.php`

2. Delete the old `jwt.php` config file

3. And follow the installation instruction [here](url=http://jwt-auth.readthedocs.io/en/develop/laravel-installation/) as if its a new installation?

4. Run `composer update`

Is that how I do it? Or is there another way to do it? If the above is right, apart from the above 4 steps, is there any other steps I need to check to ensure?

Lastly, I don't need to add the service provider to the providers array in the `config/app.php` config file if its Laravel 5.6, do I?

Can you tell me how you did the upgrade please?

**Comment by johankladder** [comment]
Just install the new version by requiring the rc version. The installation should be documented in the version 1.0.0 docs, but to answer your questions:

1. Indeed, but I think this is only in 5.6. Also make sure you update http/kernel.php route middleware if you have any:

```
'jwt.auth' => Tymon\JWTAuth\Http\Middleware\Authenticate::class,
'jwt.refresh' => Tymon\JWTAuth\Http\Middleware\RefreshToken::class;
```

2. I think you need to, a new formatted one is generated (it has some new keys en variables, make sure you read them before implementing)
3. 
4. After add the rc package to the requirements, you need to do that, as you are updating a package (for lock file).

Note: The exception handling is not very well documented now, not sure how to implement that in the right way. I have my own implementation now,  I'm not sure if I should post that here, as it is prob not very safe.

Are you using unlimited tokens for the user?

**Comment by Mr-Anonymous** [comment]
Thanks heaps for that info. It helped heaps. I was searching for this specific info for a few days now. 

I will give your suggested steps a try and hope it goes well. Since after testing in dev server I will need to update a live production server, so I am just a bit nervous as the update changes the login method a bit.

Regarding the unlimited tokens for user, do you mean a limit on how many token can a user generate at a time? If yes, there is no limit set in my app in order to allow users to login from multiple devices simultaneously. However, when they logout, that specific token will be blacklisted.

Thank you again for writing back to me. I will proceed with the upgrade and fingers crossed.

Cheers,
Neel.
