### ISSUE TITLE
JWTAuth from user - Laravel 5.1

### ISSUE THREAD

**Issue by Murwa** [tymondesigns/jwt-auth#153]
In case anyone gets into an issue with `JWTAuth::fromUser()` for 0.6.*, the user model needs to implement `Tymon\JWTAuth\Contracts\JWTSubject`

If I'm not wrong @tymondesigns

**Comment by tymondesigns** [comment]
yes you are correct :+1:

**Comment by Murwa** [comment]
Thank you!

**Comment by hoshomoh** [comment]
You should update the wiki with these information.  Almost thought the mistake was from me after wasting 6hours of my life.

**Comment by tymondesigns** [comment]
@hoshomoh the wiki is being updated to coincide with the 0.6 release. Nothing is 100% final at this point, since it is still in the development phase
