### ISSUE TITLE
URGENT!!!!. Having issues creating multi auth, please help, it is urgent

### ISSUE THREAD

**Issue by preciousgeorge** [tymondesigns/jwt-auth#1530]
i don't know if anyone can help me with. I am trying to implement multi authentication using 2 tables. I currently am running "tymon/jwt-auth": "1.0.0.rc-2". i have done everything i found online but it still defaults to the User model.
`Config::set( 'jwt.user', 'App\Model\Vendor');`
`Config::set('auth.providers.users.model', App\Model\Vendor::class);`
`$credentials = $request->only( ['email', 'password' ]);`
`$t = JWTAuth::attempt($credentials);`

**Comment by crossRT** [comment]
Have you resolved this issue?
Following is my solution, kindly put this into your controller's contructor.
```php
$this->middleware(['jwt.auth']);

// make this controller use 'api:member' guard.
auth()->shouldUse('api:member');

```

**Comment by preciousgeorge** [comment]
Thanks a lot @crossRT i finally was able to make it work using Irazasyed/jwt-auth-guard, i used it to set the guard i wanted it to authenticate with, each guard is already set up to a model. If you are interested i could give you a run down on how i went about it....Thanks a lot for the suggestion man, bless up.

**Comment by SamHz** [comment]
@crossRT 
```
// make this controller use 'api:member' guard.
auth()->shouldUse('api:member');
```
can be use in middleware?

**Comment by adhikarysunil1** [comment]
@preciousgeorge  How you get the authenticated member information using api:member guard?
