### ISSUE TITLE
ver. 2.0 is incompatible with php 7.2

### ISSUE THREAD

**Issue by altaraven** [tymondesigns/jwt-auth#1533]
### Composer json wrong requirement in version 2.0
"php": "^7.0"

when running
composer require tymon/jwt-auth:2.0

[InvalidArgumentException]                                                        
  Package tymon/jwt-auth at version 2.0 has a PHP requirement incompatible with yo  
  ur PHP version (7.2.3.0)

**Comment by tymondesigns** [comment]
Version 2.0 is very bleeding edge, and I wouldn't use it just yet. but thanks for pointing out

**Comment by altaraven** [comment]
Yep, I see, but new documentation is pointing to "JWTSubject" contract which is present only in 2.0
http://jwt-auth.readthedocs.io/en/develop/quick-start/

**Comment by tymondesigns** [comment]
It's present in all `1.*` releases and on the develop branch
