### ISSUE TITLE
Is version 2 stable and installable on production app?

### ISSUE THREAD

**Issue by mehrdad-shokri** [tymondesigns/jwt-auth#1534]
### Subject of the issue
I see branch 2 is available and 2.0.x-dev tag available on packagist.  
Can it be installed on prodction app?  
How is it different from v1?  
Also how to install it? 

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 5.6.y
| Package version   | 2.x.y
| PHP version       | 7.x.y

**Comment by josh9060** [comment]
Version 2.0.0 is still in development. You can use it in production, but be advised that their may be bugs that have not been ironed out yet.

**Comment by mehrdad-shokri** [comment]
I ended up using 1.0.0-rc.2 since v2.0.0 was giving me a silly error i Don't remember right now.
