### ISSUE TITLE
Retrieve Token saved in cookie

### ISSUE THREAD

**Issue by rleger** [tymondesigns/jwt-auth#154]
Hi,

I'm using cookies to store my token (L5.1). I'm building an app using vuejs. The user authenticates via a login form and the cookie gets saved. From there on, all my calls to the API routes use the GetUserFromToken middleware to authenticate the user. If the token is invalid or expired or so, the user gets redirected to the login page.

I should mention I'm building my app as a standard http laravel app with some api calls for a more dynamic and responsive feel. It's not a all-api-angular-type app. 

I'd like to be able to retrieve the token from the cookie in the middleware (since my frontend does not know there even is a token its not sent in the header). 

I've modified the GetUserFromToken middelware to this, so the token in the header would have priority over the one in the cookie : 
```
public function handle($request, \Closure $next)
{
    if (! $token = $this->auth->setRequest($request)->getToken()) {
        if (! $token = $request->cookie('token')) {
            return $this->respond('tymon.jwt.absent', 'token_not_provided', 400);
        }
    }

...

```

Of course it should be extracted to a little helper method for cleanliness. The cookie name could also be set in the config file.

I'd be happy to submit a pull request but I'd like to know what you thought of the idea. I'm happy to hear any other way you would suggest to handle that.

Thanks !

**Comment by ryanwinchester** [comment]
@rleger how are you setting the cookie? if i set one in laravel it's encrypted.

**Comment by ryanwinchester** [comment]
+1

**Comment by tdhsmith** [comment]
Not sure what OP's implementation is, but [you *can* set particular cookies to be unencrypted](http://laravel.com/docs/5.1/responses#attaching-cookies-to-responses) by adding their names to the `$except` array in `App\Http\Middleware\EncryptCookies`.

That said, it's possible they are simply setting the cookies with Laravel as well, so it wouldn't matter. (Though that approach wouldn't work in environments where the JWT is being used by multiple parties.)

**Comment by ryanwinchester** [comment]
@tdhsmith thanks, that helped a lot

**Comment by harveyslash** [comment]
Could you send the full file for this ? I want to check for auth token in cookies as you. Can you tell what things exactly I need to modify? It would be great if you could upload the files somewhere
