### ISSUE TITLE
"auth()->attempt()" returns a boolean.

### ISSUE THREAD

**Issue by josh9060** [tymondesigns/jwt-auth#1540]
### `auth()->attempt()` returns a boolean.
In the 1.* docs, the example uses `auth()->attempt()`, however, when I attempt to use this it returns a boolean. I don't think it's a problem on my end, as I have recreated the 'bug' in a second app.

When I use the `JWTAuth` facade, it works - `JWTAuth::attempt()` -> returns a token.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6.*
| Package version   | 1.0.0-rc.2
| PHP version       | 7.1.12

### Steps to reproduce
In a Controller, implement the `auth()->attempt()` functionality and return the value from it.

A quick way to reproduce:

`return (string) auth()->attempt(request(['email', 'password']));`

### Expected behaviour
A valid JWT will be returned.

### Actual behaviour
The response will be: "1". Indicating that the operation was successful, but does not return the token.

**Comment by josh9060** [comment]
For some reason, the guard was not being set to the default I set: "api". I done a composer dump-autoload and update - it now works as expected.

**Comment by hjJunior** [comment]
I've tried but keep returning bolean

**Comment by Wowgreat** [comment]
I meet same trouble    Can you hel me

**Comment by josh9060** [comment]
Set your default driver to your specific API provider where the driver is 'jwt'. It's in the docs.
