### ISSUE TITLE
Returns ["user_not_found"] on authentication with user

### ISSUE THREAD

**Issue by TrustOkoroego** [tymondesigns/jwt-auth#155]
After generating a token on user registration and using it to authenticate user,returns this: `["user_not_found"]`

i am using laravel 5.1

**Comment by Murwa** [comment]
@TrustOkoroego  try passing the token as a parameter in your url. Looks like  it's not picked at the moment when passed via the authorization header

**Comment by tymondesigns** [comment]
What code are you using to generate the token?

**Comment by Murwa** [comment]
```php
JWTAuth::fromUser()
```

**Comment by TrustOkoroego** [comment]
This actually worked for me. `$authuser = JWTAuth::toUser(JWTAuth::getToken());`. I still passed the token through Authorization header. But this `$user = JWTAuth::parseToken()->authenticate();` as found in the documentation did not work.

**Comment by solvire** [comment]
IDK if this will help anyone else out but I was having a similar issue and stumbled on this thread. 
I had to set the identifier because we use unorthodox naming conventions. 

```php
JWTAuth::setIdentifier('user_id');
```
It was looking for an _id_ field so it would not set the _sub_ header

**Comment by tymondesigns** [comment]
don't forget you can set this in the config ;)

**Comment by solvire** [comment]
@tymondesigns Yes I did forget that. Or neglected to notice it when I was originally scanning it. 
Thanks for pointing that out.

**Comment by cvinothkumar** [comment]
Thanks. I got the same error. but, fixed it by overriding the $primaryKey variable with my custom db field in my user class like,
File: app\Models\User.php
class User extends Model implements AuthenticatableContract, CanResetPasswordContract {
...
/**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'userID';

**Comment by jasonz1987** [comment]
@cvinothkumar 

protected $primaryKey = 'userID';

works for me,tks.

**Comment by Hammad51** [comment]
Hi,
i ran into the same problem, i generate my token using
     public function login(Request $request)
    { 
       $user = Auth::user();
// return $user = Users::first();

return $token = JWTAuth::fromUser($user);

when i pass this generated token in url to get protected route it allway's return
{"error":"user_not_found"}

**Comment by PsychicCat** [comment]
i had this problem as well with laravel 5.1.

@TrustOkoroego's solution fixed it for me. I am not using a custom primary key.

**Comment by soja123** [comment]
i am having the same issue
i am not using user model 
public function authenticate(Request $request)
    {
        Config::set('auth.providers.users.model', \App\Modules\Panelist\Models\Panelist::class);
        $credentials = $request->only('email', 'password');
        try {
                // get panel id
                $panel = $request->only('panel_id');
                 $id = Encryption::decrypt($panel['panel_id']);
                 $panel_id = DB::table('panels')
                ->select('panels.id')
                ->where('id',$id)
                ->first();
               
               // $countryCode = $panel_id->short_code;
                if(empty($panel_id)){
                    abort(\Illuminate\Http\Response::HTTP_UNAUTHORIZED, 'Invalid Panel login, Check URL');
                }

                 $panelistuser = DB::table('panelists')
                ->where('email',$request->only('email'))
                ->where('panelists.panel_id',$panel_id->id);
                $user = $panelistuser->first();

                $status = $panelistuser->where('panelists.status',1)
                ->first();
                if (empty($user)){
                    abort(\Illuminate\Http\Response::HTTP_UNAUTHORIZED, 'Invalid Credentials');
                }
                if (empty($status)){
                    abort(\Illuminate\Http\Response::HTTP_UNAUTHORIZED, 'Panelist Email is not Varified');
                }
                $customClaims = ['panel_id' => $panel_id->id];
                if ( !($user && Hash::check($credentials['password'], $user->password) )){
                    abort(\Illuminate\Http\Response::HTTP_UNAUTHORIZED, 'Invalid Credentials');
                }
            $token = JWTAuth::fromUser($user, $customClaims); 
           // $keypanlist = Encryption::encrypt($panelistuser->id);
        } catch (JWTException $e) {
             return response()->json(['error' => 'could not create token'], 500);
        }
        return Response::json($this->makeResponse("Successfully retrive token", compact("token")));
    }
when i pass this generated token in url it allway's return
{"error":"user_not_found"}

**Comment by phpnets** [comment]
Here is the answer
http://stackoverflow.com/questions/34246464/tymon-jwt-user-not-found-laravel-5-1/34246991#34246991

**Comment by fideliscode** [comment]
same issue here @PsychicCat did you solve it

**Comment by truongquan1987** [comment]
I have the same issue because i use 2 users model separate for web and api, it tooks me 2 days to figure out why.  This because jwt always use default guard was set in config/auth.php. In my situation default guards is web so when authenticate with jwt , although i was set user model in jwt config, jwt still use the model provider for web was set in config/auth.php.Here is what i'm doing:
- config/jwt.php:
'user' => 'App\Models\AppUser',
'identifier' => 'id',
**-  create a new middleware:  app\Http\Middleware\GetUserFromToken.php and copy content from Tymon\JWTAuth\Middleware\GetUserFromToken then add this line to the first line of handle function:**
**config(['auth.defaults.guard' => 'api']);**
- config/auth.php:
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        **'api' => [
            'driver' => 'session',
            'provider' => 'app_users',
        ],**
    ],

 'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\MerchantUser::class,
        ],
        **'app_users' => [
            'driver' => 'eloquent',
            'model' => App\Models\AppUser::class,
        ],**
    ],
I'm using laravel 5.3
Hope it helpful!

**Comment by shijisaroop** [comment]
> @phpnets that's the answer if you're using a primary key other than 'id'. I had this problem still with 'id'.

Yea right. If the primary key is different then set primary key name in the user model.
 protected $primaryKey = "UserId";

So that the below function will return the value of the primarykey,

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }
So the jwt token claim "sub" will contain the user id value. Which is used to fetch the user information from the token.

Also you can set more custom claims in the model using ,
public function getJWTCustomClaims()
    {
        return ['email' => $this->getAttributeValue('Email') ];
    }

This issues caused me lot of time waste. Hope this will help some one else.

I am using Lumen 5.8 and Tymon jwt 1.0.*
