### ISSUE TITLE
Using custom password column

### ISSUE THREAD

**Issue by hjJunior** [tymondesigns/jwt-auth#1551]
### Subject of the issue
I can't log in when I'm using a custom key in database instead of `password`, so I found this #356, and I keep with the same problem even after used `getAuthPassword()` function to return `$this->custom`

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6
| Package version   | dev-develop
| PHP version       | 7.1.9

### Steps to reproduce
I followed the documentation, just changed the following lines to

````
$credentials = $request->only('email', 'password');
$login = array('email' => $credentials['email'], 'custom' => 'salt_here'.$credentials['password']);
if ( ! $token = JWTAuth::attempt($login)) {
        ...
}
````

### Expected behaviour
Return success with token 

### Actual behaviour
**This just work when I change column in database to 'password'**

**Comment by hjJunior** [comment]
### Worked now!

So to do this to work, I'm supposed to add in Model these line
``
    protected $hidden = [
        'custom'
    ];
``

**Comment by marcosrocha85** [comment]
For further reference, you can achieve custom passwords using JWTSubject contract on your user model like so:

**Your user model**
```php
...
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements JWTSubject
{
...

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }


    public function getJWTCustomClaims()
    {
        return [];
    }

    public function getAuthPassword()
    {
        return $this->your_custom_password_field; //change the field you want 
    }
```

**config/auth.php**
```php
'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```

**YourAuthProvider.php**
```php
class YourAuthProvider extends EloquentUserProvider
{
    public function retrieveByCredentials(array $credentials)
    {
        $query = $this->createModel()->newQuery();

        foreach ($credentials as $key => $value) {
            if (!Str::contains($key, 'perf_senha')) {
                $query->where($key, $value);
            }
        }

        return $query->first();
    }

    /**
     * Validate a user against the given credentials.
     *
     * @param Authenticatable $authenticatable
     * @param array $credentials
     * @return bool
     */
    public function validateCredentials(Authenticatable $authenticatable, array $credentials)
    {
        $authPassword = $authenticatable->getAuthPassword();

        return $credentials['perf_senha'] == $authPassword;
    }
}
```

**on AuthServiceProvider.php**
```php
/**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();

        \Auth::provider('custom_jwt, function ($app, $config) {
            return new YourAuthProvider($this->app['hash'], $config['model']);
        });
    }
```

Finally on **config/auth.php**
```php
'providers' => [
        'users' => [
            'driver' => 'custom_jwt',
            'model' => App\User::class,
        ],

    ],
```

Just make sure you extend your AuthProvider from DatabaseUserProvider or EloquentUserProvider, otherwise AuthManager will say you are trying to pass a YourAuthProvider instead of UserProvider in second parameter.

https://thecodeman.co/post/5ceb7f89beccb34bcab58002

It solves issue #1790 either.

**Comment by glitterlip** [comment]
> For further reference, you can achieve custom passwords using JWTSubject contract on your user model like so:
> 
> **Your user model**
> 
> ```
> ...
> use Tymon\JWTAuth\Contracts\JWTSubject;
> use Illuminate\Notifications\Notifiable;
> use Illuminate\Foundation\Auth\User as Authenticatable;
> 
> class User extends Authenticatable implements JWTSubject
> {
> ...
> 
>     public function getJWTIdentifier()
>     {
>         return $this->getKey();
>     }
> 
> 
>     public function getJWTCustomClaims()
>     {
>         return [];
>     }
> 
>     public function getAuthPassword()
>     {
>         return $this->your_custom_password_field; //change the field you want 
>     }
> ```
> 
> **config/auth.php**
> 
> ```
> 'defaults' => [
>         'guard' => 'api',
>         'passwords' => 'users',
>     ],
>     'guards' => [
>         'web' => [
>             'driver' => 'session',
>             'provider' => 'users',
>         ],
>         'api' => [
>             'driver' => 'jwt',
>             'provider' => 'users',
>             'hash' => false,
>         ],
>     ],
> ```
> 
> **YourAuthProvider.php**
> 
> ```
> class YourAuthProvider extends EloquentUserProvider
> {
>     public function retrieveByCredentials(array $credentials)
>     {
>         $query = $this->createModel()->newQuery();
> 
>         foreach ($credentials as $key => $value) {
>             if (!Str::contains($key, 'perf_senha')) {
>                 $query->where($key, $value);
>             }
>         }
> 
>         return $query->first();
>     }
> 
>     /**
>      * Validate a user against the given credentials.
>      *
>      * @param Authenticatable $authenticatable
>      * @param array $credentials
>      * @return bool
>      */
>     public function validateCredentials(Authenticatable $authenticatable, array $credentials)
>     {
>         $authPassword = $authenticatable->getAuthPassword();
> 
>         return $credentials['perf_senha'] == $authPassword;
>     }
> }
> ```
> 
> **on AuthServiceProvider.php**
> 
> ```
> /**
>      * Register any authentication / authorization services.
>      *
>      * @return void
>      */
>     public function boot()
>     {
>         $this->registerPolicies();
> 
>         \Auth::provider('custom_jwt, function ($app, $config) {
>             return new YourAuthProvider($this->app['hash'], $config['model']);
>         });
>     }
> ```
> 
> Finally on **config/auth.php**
> 
> ```
> 'providers' => [
>         'users' => [
>             'driver' => 'custom_jwt',
>             'model' => App\User::class,
>         ],
> 
>     ],
> ```
> 
> Just make sure you extend your AuthProvider from DatabaseUserProvider or EloquentUserProvider, otherwise AuthManager will say you are trying to pass a YourAuthProvider instead of UserProvider in second parameter.
> 
> https://thecodeman.co/post/5ceb7f89beccb34bcab58002
> 
> It solves issue #1790 either.

Your solution works like a charm, but is there any method to only change 
```
'api' => [
            'driver' => 'custom_jwt_driver',
            'provider' => 'users',
            'hash' => false,
        ],
```

instead of change `user` driver?

**Comment by marcosrocha85** [comment]
In theory, if you override getAuthPassword in your User model. It may work.
```
public function getAuthPassword()
{
    return $this->perf_senha;
}
```

The problem of mine was that Illuminate\Auth\DatabaseUserProvider refers to 'password' key in order to get passwords from model, instead of using getAuthPassword. In my case, the field was written in ("Argh") portuguese instead of english, so I had to create my custom driver to make it work. That is the problem when you don't have conventions while creating your database or do not have a database admin.

The limitation it creates is that no matter if you're trying to call JWT's `attempt` method with your custom fields, Laravel will try to use 'password' anyways. At least that's all I could identify while I was debugging the code for default JWT Authentication.

**Comment by nmindz** [comment]
Just one thing that was key to me, which I found referred nowhere else, is that you what you might actually want to return is a **hash check** instead of a simple boolean comparison between your plaintext string from the request form and the bcrypt hash from the database.

```
    public function validateCredentials(Authenticatable $authenticatable, array $credentials)
    {
        $authPassword = $authenticatable->getAuthPassword();

        return Hash::check($credentials['perf_senha'], $authPassword);
    }
```

So that it instead compares and validates the password string from the request to the bcrypt hash.

**Comment by hendra-jti** [comment]
> ### Worked now!
> So to do this to work, I'm supposed to add in Model these line `protected $hidden = [ 'custom' ];`

i still cannot do this event i add the custom column. any idea ?
