### ISSUE TITLE
need refresh token example

### ISSUE THREAD

**Issue by ajoslin103** [tymondesigns/jwt-auth#156]
Would someone be kind enough to post an example of refreshing a token passed in a param 'refresh token' 

I've gotten this far:

    /**
     * Attempt to do token refresh
     *
     * @return  JWT Token
     */
    public function doRefresh()
    {
        // grab credentials from the request
        $expiredToken = Input::only('refresh_token');

        try {

            // attempt to refresh token for the user
            if (! $token = JWTAuth::parseToken($expiredToken)->refresh()) {
                return Response::json(['error' => 'invalid_token'], 401);
            }

        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return Response::json(['error' => 'could_not_refresh_token'], 500);
        }

        // all good so return the token
        return Response::json(compact('token'));
    }

My client side is the sample from angular-jwt

    jwtInterceptorProvider.tokenGetter = function(jwtHelper, ENV, $http, locker) {
      var idToken = locker.get('jwt','no-token');
      if (jwtHelper.isTokenExpired(idToken)) {
        // This is a promise of a JWT id_token
        return $http({
          url: ENV.backend+'/auth/refresh',
          // This makes it so that this request doesn't send the JWT
          skipAuthorization: true,
          method: 'POST',
          data: { 
              grant_type: 'refresh_token',
              refresh_token: idToken 
          }
        }).then(function(response) {
          var id_token = response.data.id_token;
          locker.put('jwt',idToken);
          return id_token;
        });
      } else {
        return idToken;
      }
    };

**Comment by devmark** [comment]
1. refresh token each time you call api .  return new toekn or reset header
that let you make sure it is single user.

2. call refresh token even expired token.
it is just let "this user" dont need to fill the username&password again. after refreshed token, the old one token could not use anymore.


if mobile app, it should be use first option. 
for now, i may go to second option to do that.

btw, i dont know is it good for security. 
please figure out me. :)

**Comment by ajoslin103** [comment]
to be more clear -- my attempt to refresh the token is failing with this line

(I am using Laravel 4 so I don't have access to the middleware)

        // attempt to refresh token for the user
        if (! $token = JWTAuth::parseToken($expiredToken)->refresh()) {
            return Response::json(['error' => 'invalid_token'], 401);
        }

[2015-06-21 23:04:57] local.ERROR: exception 'BadMethodCallException' with message 'Method [refresh] does not exist.' in /Users/ajoslin/Documents/Als/Development/ResearchCircle/Round2/Interventionaire2/rest-2/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:268

**Comment by ajoslin103** [comment]
$newToken = '';

	    try {

	        $token = Input::get('token');
	        Log::info("old_token: $token");

	        $newToken = JWTAuth::refresh($token);
	        Log::info("new_token: $newToken");

	    } catch (TokenExpiredException $e) {
	        Log::info("TokenExpiredException: ".$e->getMessage() );
	        $newToken = $e->getMessage();
	    } catch (JWTException $e) {
	        Log::info("JWTException: ".$e->getMessage() );
	        $newToken = $e->getMessage();
	    }

	    return $newToken;
