### ISSUE TITLE
Token has expired after JWTAuth::fromUser($user)

### ISSUE THREAD

**Issue by MatheusGit** [tymondesigns/jwt-auth#1560]
### Subject of the issue
I am developing an api, and the error "Token has expired" happens in any request following the login that use token.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.5
| Package version   | dev-develop
| PHP version       | 7.1

### Steps to reproduce
Steps:

1-

When calling domain / api / login, the user is authenticated in LDAP, and the returned data is saved in User, then I give the following command to generate the token:

$ token = JWTAuth :: fromUser ($ user);
return response () -> json (compact ('user', 'token'));

2-

I take the token and make a request for the api, which is passed in a middleware with the following validation code:

try {

        JWTAuth :: parseToken ();
         $ user = JWTAuth :: authenticate (JWTAuth :: getToken ());
} catch (...) {
        ....
}

And then the "Token has expired" error occurs.

PS: 'ttl' is 1200.

Help me, pls.

**Comment by svolence** [comment]
I also encountered this problem. How did you solve it?
