### ISSUE TITLE
JWT Token with multiple authentication sources

### ISSUE THREAD

**Issue by loic-lopez** [tymondesigns/jwt-auth#1563]
### Subject of the issue
I would like to know if is it possible to create a JWT token for multiple domains like : 
First domain : api.test.local
Second domain : chat.test.local

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | ?
| Framework         | Laravel
| Framework version | 5.6
| Package version   | latest
| PHP version       |  7.x.y

Thanks for reply.

**Comment by MatheusGit** [comment]
Maybe if the JWT_SECRET are the same, it works
