### ISSUE TITLE
When I use the jwt.refresh it returns the same token (and invalidating it)

### ISSUE THREAD

**Issue by dani3l** [tymondesigns/jwt-auth#158]
Weird thing
I tried the jwt.refresh middleware but it returns the same token (after invalidation) so the next request throws unauthorized.

Any idea?

I'm using L5.1

**Comment by osteel** [comment]
No idea if it's related but I had the problem in testing context: basically if you make several requests using the refresh middleware in the same test method, the PayloadFactory will still use the `Request` object of the first request (as it is not re-instanciated), hence will reissue the same token as using the same payload data (after invalidating it).

Might be something to investigate according to how you're trying out the middleware at the moment.

This is something @tymondesigns might actually want to document somewhere, really got me a headache finding this one!

**Comment by dani3l** [comment]
It doesn't work well when jwt.auth is also applied to the routes so I create a refresh route and only call it when token expired.

This is ok for now , buy is there any way to return a new token every request?

**Comment by boukeversteegh** [comment]
@osteel Thanks, that helped me get my tests working!
I am running $this->refreshApplication(); in between the two requests, that works
