### ISSUE TITLE
Multi server behind loadbalancer setup

### ISSUE THREAD

**Issue by marijnhurkens** [tymondesigns/jwt-auth#1583]
### Subject of the issue
I am trying to run our app behind an AWS loadbalancer and there are some issues with the tokens. Mainly we have some users which randomly have to sign in again when using the app.

I think this issue has to do with the tokens from server A being invalid when used on server B and vice versa. 

My question: what would be the best way to handle this situation? Can the servers use a shared secret key?

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 5.6
| Package version   | dev-develop
| PHP version       | 7.1

**Comment by devqx** [comment]
The jwt-auth also works with a User Provider, since you are using a load
balancer, set up jwt on the load balancer which distributes and forward
traffic's, since your applications server make a request to a another
database server which hosts the user database.

**Comment by J5Dev** [comment]
Im not sure if you have already solved this, but the best way is to just ensure that the JWT secret is not autogenerated as part of your deploy script, instead generate one, and pass it in to each service as part of the env vars.

This should sort out your issues.

**Comment by marijnhurkens** [comment]
Thanks, this was the solution to the problem, the tokens work fine now :)
