### ISSUE TITLE
Missing Authorization header

### ISSUE THREAD

**Issue by EduardoOliveira** [tymondesigns/jwt-auth#160]
Hello, I'm using jwt-auth with the laters laravel5.1 build but I'm getting some troubles authentication via header, I always get a JWTException.
Here's my middleware implementation:

    public function handle($request, Closure $next)
    {

        try {

            if (! $user = JWTAuth::parseToken()->authenticate()) {
                return response()->json(['user_not_found'], 404);
            }

        } catch (TokenExpiredException $e) {

            return response()->json(['token_expired'], $e->getStatusCode());

        } catch (TokenInvalidException $e) {

            return response()->json(['token_invalid'], $e->getStatusCode());

        } catch (JWTException $e) {

            return response()->json(['token_absent'], $e->getStatusCode());

        }

        return $next($request);
    }

by placing getallheaders () on the index I can see that the PHP receives the correct headers.

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9(....)

Passing the token via query (?token=qwiehiqwehiqw) it all works fine.
Am I missing something?

**Comment by csrui** [comment]
I'm having the exact same issue. 

I've also added to my apache config (as documented) 
```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

**Comment by csrui** [comment]
Correcting my last post. It works after all.

Just add the following to public/.htaccess

```
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

**Comment by EduardoOliveira** [comment]
Sorry forgot to close the issue, arrived the the same conclusion 2 days ago.
https://github.com/lexik/LexikJWTAuthenticationBundle/issues/23#issuecomment-51714234

But thank you for the reply!
