### ISSUE TITLE
update from 0.5.* to 1.0.0-rc.2 --Class auth.jwt does not exist

### ISSUE THREAD

**Issue by gileneusz** [tymondesigns/jwt-auth#1610]
Guys I simply cannot update from 0.5.* to 1.0.0-rc.2
I've got error: `"Class auth.jwt does not exist",`
This is a little bit frustrating, because 0.5 worked fine for me. 
on my 0.5 I had 
```
    protected $routeMiddleware = [
        'auth.jwt' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
        'jwt.refresh' => \Tymon\JWTAuth\Middleware\RefreshToken::class,   
    ];
```
and It worked fine. Now I have an error: 
`message": "Class Tymon\\JWTAuth\\Middleware\\GetUserFromToken does not exist`

so I changed it to:
```
    protected $routeMiddleware = [
        'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
        'jwt.refresh' => \Tymon\JWTAuth\Middleware\RefreshToken::class,   
    ];
```
and now: `"Class auth.jwt does not exist",`

Guys this is real frustrating, can anyone help me?

**Comment by vdomah** [comment]
In 1.0 middlewares are completely different 
![middle](https://user-images.githubusercontent.com/9612735/43065416-70d0db96-8e6a-11e8-939c-db17a0121b27.png)
