### ISSUE TITLE
On blacklisting

### ISSUE THREAD

**Issue by osteel** [tymondesigns/jwt-auth#162]
Hi,

I'm using the single-use token flow with the `RefreshToken` middleware along with the `GetUserFromToken` one.

Playing around with an Angular front-end to test my API,  I started experiencing weird regular `401` responses, the `GetUserFromToken` middleware refusing tokens that had just been refreshed by the `RefreshToken` middleware.

Digging a bit, I realised that sometimes, even though the tokens are different, the blacklisted values are the same, making the `GetUserFromToken` rejecting valid tokens.

The values stored in the blacklist are the tokens' `jti`, supposed to be a unique id for the token. It is based on the `sub` and the `nbf`, respectively the user id (by default) and the "Not Before" claim.

It is expected that the `sub` doesn't change between 2 requests, so the real unique value here is the `nbf`, which is the number of seconds since `1970-01-01`.

The problem is, in my application, requests can be chained in such a way they're happening fast enough for the `nbf` to be the same for 2 different requests, and I think it's reasonable to think other people will get the issue at some point as well.

Solutions I can think of off the top of my head are to add another existing claim to the `jti` hash (like the issuer, but it's likely that the same api endpoint could be hit twice in the same second as well), to store the token value itself (would take more memory I guess), or simply to add another random string to the hash.

Cheers!

**Comment by tymondesigns** [comment]
You are right in your conclusion that the unix timestamp is really the only thing that keeps the jti's unique.

I will, as you say, add another value to compensate for this

**Comment by osteel** [comment]
Cool cheers!

**Comment by tymondesigns** [comment]
https://github.com/tymondesigns/jwt-auth/commit/82a0b5a12dd339183955f83dc2ed599ab740e58d#diff-deaffdc80700298d7be656b353c40eb8R192 should fix it

**Comment by osteel** [comment]
Looks good!
