### ISSUE TITLE
Class Tymon\JWTAuth\Providers\JWT\Namshi does not exist

### ISSUE THREAD

**Issue by JeremyGreaux** [tymondesigns/jwt-auth#163]
Hi,

After the installation, I wanted in my controller generate a token.
I end up with this error:

Class Tymon\JWTAuth\Providers\JWT\Namshi does not exist

Is this normal ?

regards

**Comment by JeremyGreaux** [comment]
Sorry, I made an error in the configuration file ...
You can deleted this issue...

Sorry again

**Comment by jtrupina** [comment]
what was the issue?

**Comment by JeremyGreaux** [comment]
I created a new config file in config/jwt.php with this : " <?php return []; "
