### ISSUE TITLE
Docs need to explain where tokens are stored

### ISSUE THREAD

**Issue by genyded** [tymondesigns/jwt-auth#1633]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      |yes
| Framework         | Laravel 
| Framework version | 5.6
| Package version   | 1.0.0-rc.2
| PHP version       | 7.1.3

### Steps to reproduce
The current 1.0.0 docs do not specify where the tokens are stored. if they are cleaned up or updated on expiration, or anything about any maitainence or cleanup that needs to be done. Also same for blacklist (how can you remove one from the blacklist). 

### Expected behaviour
Docs should detail where everything is and how it works.

### Actual behaviour
Docs do not say anything about this.

**Comment by mattmcdev** [comment]
JSON web tokens are stateless, they aren't stored anywhere.

Everything needed to validate the token is contained within the token itself.

**Comment by genyded** [comment]
OK - that makes sense, but was confusing because prior version had all the "auth" tables and those are gone now.

**Comment by alalfakawma** [comment]
> JSON web tokens are stateless, they aren't stored anywhere.
> 
> Everything needed to validate the token is contained within the token itself.

Sorry to bump this old thread but, can you explain what data is stored in the token?

**Comment by mfn** [comment]
@alalfakawma this is explained very well in the specs => https://tools.ietf.org/html/rfc7519
