### ISSUE TITLE
Please Change Documentation for *Note to Apache users*

### ISSUE THREAD

**Issue by jasonspick** [tymondesigns/jwt-auth#164]
In my error, I was making changes to my apache configuration file 000-default.conf. After struggling with this for about a week I found it is the .htaccess file that needs to be updated. Could you please update the documentation to help avoid confusion in the future?

Note to Apache users

Apache seems to discard the Authorization header if it is not a base64 encoded user/pass combo. So to fix this you can add the following to your .htaccess file.

Thanks!

**Comment by tymondesigns** [comment]
Yea I don't mind clarifying that in the wiki. Although I have somewhat solved this issue in the coming release
