### ISSUE TITLE
Laravel 5.7 Compatibility

### ISSUE THREAD

**Issue by blindsz** [tymondesigns/jwt-auth#1645]
is the latest version supported and compatible in laravel 5.7?

**Comment by megama5** [comment]
nope

**Comment by binaryk** [comment]
Not yet:
<img width="1023" alt="screenshot 2018-08-28 at 20 04 39" src="https://user-images.githubusercontent.com/6833714/44738456-a6ff5800-aafd-11e8-917a-b139f2744443.png">

**Comment by ghost** [comment]
Is this repo even still maintained?

Does anyone know of an alternative package?

**Comment by omaryoussef** [comment]
Well there was an update about 2 months ago... Don't know of any alternative packages.

**Comment by megama5** [comment]
Just for you, omaryoussef (with support of laravel 5.7 lol)
https://github.com/megama5/jwt-auth
