### ISSUE TITLE
exp, nbf and iat change value from string to int

### ISSUE THREAD

**Issue by lkoenigsberger** [tymondesigns/jwt-auth#165]
Hi,
I have a problem with the given claims: exp,nbf,iat. All these values are returned as a string.
Is there a way to change the values from a string to an integer value??

Update: read the specs here https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.4

and all these claims should be an integer!!

Thanks

**Comment by stevenmyhre** [comment]
Any chance you'll have a stable/tagged release soon that will include this? It's blocking some interoperability with some of my node server libraries that require these claims be integers.

**Comment by aejnsn** [comment]
I second this @stevenmyhre.
