### ISSUE TITLE
Install in Laravel 5.7

### ISSUE THREAD

**Issue by jafar-albadarneh** [tymondesigns/jwt-auth#1659]
### Subject of the issue
Package “tymon/jwt-auth”: “1.0.0-rc.2” was not able to be installed

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no 
| Framework         | Laravel
| Framework version | 5.7.1
| Package version   | 1.0.0-rc.2
| PHP version       | 7.2

### Steps to reproduce
- `composer require “tymon/jwt-auth”: “1.0.0-rc.2”`
- `composer update`

### Expected behaviour
It should be installed without any issues

### Actual behaviour
```
Problem 1
    - Conclusion: remove laravel/framework v5.7.1
    - Installation request for tymon/jwt-auth 1.0.0-rc.2 -> satisfiable by tymon/jwt-auth[1.0.0-rc.2].
    - Conclusion: don't install laravel/framework v5.7.1
    - Conclusion: don't install laravel/framework v5.7.0
    - tymon/jwt-auth 1.0.0-rc.2 requires illuminate/http 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.* -> satisfiable by illuminate/http[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
```

**Comment by TobiasJ** [comment]
This was fixed in tymon/jwt-auth (dev-develop e190b6a) + (https://github.com/tymondesigns/jwt-auth/commit/d6fab6e52f388f99156b1f313ffd393958196b04).

Using the develop branch should fix your issue.

**Comment by MaartenStaa** [comment]
@TobiasJ can you tag a new release, so we don't have to use a `dev-` prefix?

**Comment by TobiasJ** [comment]
@MaartenStaa I'm not a maintainer as I just started using this package myself. But maybe @tymondesigns got the time to tag a new release for us.

**Comment by SergeyMiracle** [comment]
@tymondesigns any updates?

**Comment by hopeseekr** [comment]
I officially forked this repo and I will be adding 5.7 support tomorrow. I'm tired of waiting.

**Comment by tymondesigns** [comment]
Sorry to keep you guys waiting! I've just tagged a new release

https://github.com/tymondesigns/jwt-auth/releases/tag/1.0.0-rc.3

**Comment by SergeyMiracle** [comment]
@tymondesigns thank you very much 👍

**Comment by mirfansulaiman** [comment]
@tymondesigns Thank you 👍

**Comment by khanhvu14** [comment]
@tymondesigns Thank you 💯

**Comment by rohanisuhadi** [comment]
@tymondesigns Thank You very much

**Comment by umutyerebakmaz** [comment]
Thanks @tymondesigns

**Comment by Harsukh21** [comment]
`$credentials = $request->only('email', 'password');`
`Config::set('jwt.user', \App\Admin::class); `
`Config::set('auth.providers.users.model', \App\Admin::class);`

`dd(JWTAuth::attempt($credentials));`

it's give me false. so it's not working with another model how to fixed it please help me.
