### ISSUE TITLE
Control of logged in users

### ISSUE THREAD

**Issue by garbinmarcelo** [tymondesigns/jwt-auth#1663]
### Control of logged in users
Is it possible to control logged in users?
Example: Limit the number of logins / users who are accessing the application.

Another question, is it possible to check if a user has already logged in? In this case, for example the command "Auth::check()", then if he had already logged in he did not generate another token, keep the token (if it is not expired).

Could someone give me an idea?

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no 
| Framework         | Laravel
| Framework version | 5.4.43
| Package version   | 1.0.x-dev
| PHP version       | 7.2.2

**Comment by shirshak55** [comment]
I think you should do it manually. Whenever user login increment their count and like that. I don't think this package should be responsible for that.

**Comment by garbinmarcelo** [comment]
@shirshak55 I return to that question. Would you have any idea how to do this? Is it something with a database record?

**Comment by shirshak55** [comment]
yea it has to be stored in db or redis i prefer later one for speed
