### ISSUE TITLE
Route [login] not defined (How return right the status and message?)

### ISSUE THREAD

**Issue by richellyitalo** [tymondesigns/jwt-auth#1664]
### Subject of the issue
Problem when try access route that need token with my spa, show me "Route [login] not defined.", but needs show unautorized status.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7
| Package version   | 1.0.0-rc.2
| PHP version       | 7.2

**Comment by mateuszkardas** [comment]
Try name Your route `Route::post('login', 'AuthController@login')->name('login');`

**Comment by richellyitalo** [comment]
But it's on api, the right way it's return **`{message: unathenticated}`** throught rest.

**Comment by john-xu** [comment]
@richellyitalo 
you should check line 216 in file "vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
you could put Accept: application/json in your request header

**Comment by richellyitalo** [comment]
Thanks, @john-xu .
After check that and run **`php artisan make:auth`** it's works.
Thanks guys and have a nice day!
