### ISSUE TITLE
implementing token signing with certificates

### ISSUE THREAD

**Issue by lkoenigsberger** [tymondesigns/jwt-auth#167]
As shown here it would be nice if we can switch to private key signing.

https://github.com/namshi/jose#usage

**Comment by tymondesigns** [comment]
Shouldn't be much work to get this in. 

I'll see what I can do

**Comment by th3m477** [comment]
Hi @tymondesigns 

I see that this should support RS256 (Public<>Private key pair), however no tests are currently available. To try to decrypt a valid JWT I'm setting the config secret to my public key as "----BEGIN PUBLIC KEY---------........----END PUBLIC KEY------", and the algo correctly. I'm getting a "token_invalid" response. I also tried using openssl_pkey_get_public() to provide a resource.

Using Namshi as underlying verification - but the $jws->verify($this->secret, $this->algo) is throwing an error. 

Wondering if you managed to get this to work?

Thanks,
Matt

**Comment by tymondesigns** [comment]
closing as tracking in #307
