### ISSUE TITLE
What is the order of getting tokens?

### ISSUE THREAD

**Issue by smithyj** [tymondesigns/jwt-auth#1675]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.7.6
| Package version   | dev-develop
| PHP version       | 7.2.3

### Steps to reproduce
nothing

### Expected behaviour
nothing

### Actual behaviour
nothing

I observed in the code that when the token authentication is obtained, it will judge according to the parser. After the first acquisition, it will give up other acquisition methods, which will cause problems.

## For Example:

```
headers = {
    authorization： xxxxxxxxxxxxxx, // this is vaild or invalid ？
}

http query = {
    token: xxxxxxxx, // this is vaild or invalid ？
}

http params = {
   token: xxxxxxxx, // this is vaild or invalid ？ 
}
```
three origin is include auth token, How to judge? I want to valid auth token user

**Comment by haidang666** [comment]
Using provided middleware to validate token, you should put it in the header

**Comment by smithyj** [comment]
@HaiDang666 Thanks
