### ISSUE TITLE
Laravel creating new session file on each requests

### ISSUE THREAD

**Issue by HybridFox** [tymondesigns/jwt-auth#1676]
### Subject of the issue
After implementing jwt-auth in my laravel project a new session file is being created on each request. Only after deploying to production and noticing inode usage is through the rough i noticed the issue. So the exact cause is not known.

If anyone has ever encoutered this and / or knows a fix for this. Please let me know. otherwise i will be redo adding jwt-auth and check step by step if i'm encountering the issue again

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6.x
| Package version   | 0.5.12
| PHP version       | v7.1.11

**Comment by shirshak55** [comment]
did you use api and auth api as route middleware? Using `web` middleware is responsible for such thing. If you are using this package then web middleware is usually redundant

**Comment by HybridFox** [comment]
I am not using the web middleware, only the one the package provided

**Comment by HybridFox** [comment]
I "fixed" the issue by switching to memcached and setting a relatively short expiry. This stopped my inodes from running out.

I know this is not a real fix though
