### ISSUE TITLE
Custom length

### ISSUE THREAD

**Issue by ChristianGiupponi** [tymondesigns/jwt-auth#168]
Hi,
I'd like to use this package to generate token to use as api key, there is any way to set the length?
I tried:

~~~
$key = JWTAuth::fromUser($user);
~~~

but the length is 255 char that is too much for a simple apy key

**Comment by tymondesigns** [comment]
I think you may have misunderstood how JWT's are constructed. The length is not directly configurable. But there is a direct relationship between the length of the token and the number of claims. - see [here](https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens#creating-a-token-based-on-a-user-object)

You can find out what claims exist in your token by pasting it on http://jwt.io/
