### ISSUE TITLE
Proper installation instructions for Laravel 5.7

### ISSUE THREAD

**Issue by vsecades** [tymondesigns/jwt-auth#1695]
### Proper installation instructions for Laravel 5.7
Really, need a proper walk-through of installation

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no / yes
| New Feature?      | no / yes
| Framework         | Laravel 
| Framework version | 5.7
| Package version   | 1.0.0-rc.3
| PHP version       | 7.1

### Steps to reproduce
Had to follow 3 different bug reports to get things working.

### Expected behaviour
I should be able to follow one single version of the truth for the combination I am installing it for.

### Actual behaviour
Had to fiddle around with things for 2 hours to get them to work... 👎

**Comment by marcioelias** [comment]
Hey @vsecades,

can you share these steps that you have to do in order to get all working?

I'm upgrading a project to Laravel 5.7, and are having a lot of problems.

**Comment by bangtiray** [comment]
hy @vsecades 
please share your step,,

**Comment by shirshak55** [comment]
it is working as expected. The docs is also working properly which step did you failed?

**Comment by iammackinnon** [comment]
[This comment](https://github.com/tymondesigns/jwt-auth/issues/1038#issuecomment-393520213) should help solve the issue for most I think.

The docs also needs updating.  I had to delve into the issues to find out how to at least install (following the docs resulted in jwt:secret throwing an error)

**Comment by benmcm1994** [comment]
I believe the only step missing is `composer update`. I was getting 

> There are no commands defined in the "jwt" namespace.

Until I updated my composer.

**Comment by 82rules** [comment]
I've installed 1.0.0-rc.3 and was able to install correctly BUT the login() function in the AuthController example in the docs derives the token from Auth()->attempt() which return a boolean. 

Should the User model be extending a different class, all I see is an interface with two abstracts to implement.

**Comment by shirshak55** [comment]
@82rules it returns boolean which is correct. You check using that boolean and generate token

**Comment by 82rules** [comment]
@shirshak55 I dont see in the docs how to generate the token. I'm following the instructions provided https://jwt-auth.readthedocs.io/en/develop/quick-start/ 

The way I got it working was to resolve JWTAuth in the auth controller and substitute it for auth() 

`use Illuminate\Http\Request;
use Tymon\JWTAuth\JWTAuth;
use App\Http\Controllers\Controller;

class AuthController extends Controller
{
  private $auth;
  public function __construct(JWTAuth $auth)
  {
    $this->middleware('auth:api', ['except' => ['login']]);
    $this->auth = $auth;
  }
  
  /**
   * Get a JWT via given credentials.
   *
   * @return \Illuminate\Http\JsonResponse
   */
  public function login()
  {
    $credentials = request(['email', 'password']);
    
    if (! $token = $this->auth->attempt($credentials)) {
      return response()->json(['error' => 'Unauthorized'], 401);
    }
    
    return $this->respondWithToken($token);
  }`

Let me know if there is a proper method for generating the token.

**Comment by shirshak55** [comment]
Can you format the code .

Here is my config which works properly

```
namespace YOURNAMESPACEHERE
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    /**
     * Create a new AuthController instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:api', ['except' => ['login']]);
    }

    /**
     * Get a JWT token via given credentials.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function login(Request $request)
    {
        $credentials = $request->only('email', 'password');

        if ($token = $this->guard()->attempt($credentials)) {
            return $this->respondWithToken($token);
        }

        return response()->json(['error' => 'Invalid Login Details'], 401);
    }

    /**
     * Get the authenticated User.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function me()
    {
        return response()->json($this->guard()->user(), 200);
    }

    /**
     * Log the user out (Invalidate the token).
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function logout()
    {
        $this->guard()->logout();

        return response()->json(['message' => 'Successfully logged out']);
    }

    /**
     * Refresh a token.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function refresh()
    {
        return $this->respondWithToken($this->guard()->refresh());
    }

    /**
     * Get the token array structure.
     *
     * @param  string $token
     *
     * @return \Illuminate\Http\JsonResponse
     */
    protected function respondWithToken($token)
    {
        return response()->json([
            'access_token' => $token,
            'token_type'   => 'bearer',
            'expires_in'   => $this->guard()->factory()->getTTL() * 60,
        ]);
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\Guard
     */
    public function guard()
    {
        return Auth::guard('api');
    }
}
```

**Comment by jamby77** [comment]
@82rules - today I struggled with making this run as well. 
I think key part of the docs is:
```
'defaults' => [
    'guard' => 'api',
    'passwords' => 'users',
],
```
Which makes default auth guard to be 'api'. If you do not do that, you need to change the call in login() from
```
    /**
     * Get a JWT via given credentials.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function login()
    {
        $credentials = request(['email', 'password']);

        if (! $token = auth()->attempt($credentials)) {
            return response()->json(['error' => 'Unauthorized'], 401);
        }

        return $this->respondWithToken($token);
    }
```
to
```
    public function login(): JsonResponse
    {
        $credentials = request(['email', 'password']);
        if (!$token = auth('api')->attempt($credentials)) {
            return response()->json(['error' => 'Unauthorized'], 401);
        }
        return $this->respondWithToken($token);
    }
```
Note the auth() helper is called with argument 'api'

**Comment by muhtarudinsiregar** [comment]
i try to follow instruction in wiki, then i get error 
`"Call to undefined method Illuminate\\Auth\\TokenGuard::attempt()",`.

then i refactor my controller with @jamby77, still get error.

but when i use laravel 5.6, its no problem :thinking:
anyone who success using jwt auth in laravel 5.7 can share the setup :pray:

**Comment by shirshak55** [comment]
@muhtarudinsiregar see above  my reply it is working perfectly on laravel 5.7. 


Did you configured config/auth.php file too? Many people arenot configuring that.

**Comment by muhtarudinsiregar** [comment]
@shirshak55 yeah, already configured config/auth.php. you can check my auth.php here https://gist.github.com/muhtarudinsiregar/2444f502c173f292073348be732687c5

**Comment by shirshak55** [comment]
@muhtarudinsiregar use this it is working fine for me

```
namespace YOURNAMESPACEHERE
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;

class AuthController extends Controller
{
    /**
     * Create a new AuthController instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:api', ['except' => ['login']]);
    }

    /**
     * Get a JWT token via given credentials.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function login(Request $request)
    {
        $credentials = $request->only('email', 'password');

        if ($token = $this->guard()->attempt($credentials)) {
            return $this->respondWithToken($token);
        }

        return response()->json(['error' => 'Invalid Login Details'], 401);
    }

    /**
     * Get the authenticated User.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function me()
    {
        return response()->json($this->guard()->user(), 200);
    }

    /**
     * Log the user out (Invalidate the token).
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function logout()
    {
        $this->guard()->logout();

        return response()->json(['message' => 'Successfully logged out']);
    }

    /**
     * Refresh a token.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function refresh()
    {
        return $this->respondWithToken($this->guard()->refresh());
    }

    /**
     * Get the token array structure.
     *
     * @param  string $token
     *
     * @return \Illuminate\Http\JsonResponse
     */
    protected function respondWithToken($token)
    {
        return response()->json([
            'access_token' => $token,
            'token_type'   => 'bearer',
            'expires_in'   => $this->guard()->factory()->getTTL() * 60,
        ]);
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\Guard
     */
    public function guard()
    {
        return Auth::guard('api');
    }
}

```

**Comment by muhtarudinsiregar** [comment]
@shirshak55 i solved my problem about 
`"Call to undefined method Illuminate\\Auth\\TokenGuard::attempt()"`, 
and your code work too, thank you :+1: 

Its because i forget set my middleware with jwt-auth in routes but in documentation no one mention it. I dont know if its dingo/api middleware or jwt-auth.  You can follow this [tutorial](https://codebriefly.com/laravel-5-6-jwt-auth-api/) its work with laravel  5.7.

**Comment by shirshak55** [comment]
hmm it is in docs 
https://jwt-auth.readthedocs.io/en/develop/quick-start/

where did you check?

**Comment by muhtarudinsiregar** [comment]
@shirshak55 i check in jwt-auth wiki [here](https://github.com/tymondesigns/jwt-auth/wiki) but no one mention that jwt-auth in middleware. if you check readthedoc part `Add some basic authentication routes`, in routes used `'middleware' => 'api'` not `jwt.auth`.

**Comment by shirshak55** [comment]
api will work because in config/auth.php api array you will set jwt :)

i mean this

```
        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
```

**Comment by shirshak55** [comment]
I am currently using laravel 5.7 development branch which is latest and jwt is working really fine with api auth.

**Comment by haidang666** [comment]
I wrote this hope it helps https://medium.com/@hdcompany123/laravel-5-7-and-json-web-tokens-tymon-jwt-auth-d5af05c0659a

**Comment by muhtarudinsiregar** [comment]
thank you @shirshak55, my bad, i forget to change api driver to jwt :+1:

**Comment by hopeseekr** [comment]
@shirshak55 I followed your guide...

`JWTAuth::attempt($payload);` works fine.

`\Auth::guard('api')->attempt($payload);` always returns false. :-/

**Comment by vsecades** [comment]
https://medium.com/@hdcompany123/laravel-5-7-and-json-web-tokens-tymon-jwt-auth-d5af05c0659a

This works well, once you realize everything is being done on the .env file.  Anyhow, closing as it is resolved, the package mantainer SHOULD update instructions.  Not going to kill them.

**Comment by iamsajidjaved** [comment]
First Run php artisan package:discover
Then php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
Then php artisan jwt:secret

**Comment by abdullahessam** [comment]
you should use auth('api')->attempt()


> I've installed 1.0.0-rc.3 and was able to install correctly BUT the login() function in the AuthController example in the docs derives the token from Auth()->attempt() which return a boolean.
> 
> Should the User model be extending a different class, all I see is an interface with two abstracts to implement.

**Comment by MOHAMMED-ABD-RAZAQ** [comment]
> [This comment](https://github.com/tymondesigns/jwt-auth/issues/1038#issuecomment-393520213) should help solve the issue for most I think.
> 
> The docs also needs updating. I had to delve into the issues to find out how to at least install (following the docs resulted in jwt:secret throwing an error)

me too

**Comment by ChrGriffin** [comment]
I'm here from Laravel 7. Following the instructions on https://jwt-auth.readthedocs.io/en/develop/quick-start/, to the letter, on a fresh install, results in the old error:

```
Error: Call to undefined method Illuminate\Auth\TokenGuard::attempt() in file C:\laragon\www\my-project\vendor\laravel\framework\src\Illuminate\Auth\AuthManager.php on line 307
```
