### ISSUE TITLE
Getting user when not using auth:api middleware?

### ISSUE THREAD

**Issue by shirshak55** [tymondesigns/jwt-auth#1697]
In Laravel

`auth()->user()`

returns true if user is logged in  and null if user get logged out.

If route is protected by `auth:api`
`auth()->user()` works as expected

But if route has only been added to `api` not to `auth:api`
auth()->user() it always returns null even if I passed authentication token in header.

There may be some part of application where I don't want user to login compulsorily and check if user is logged in or not ? How can i do it because clearly auth()->user() is giving null even after passing authentication header. (not using auth:api as there is no compulsion to login.)

Thanks

**Comment by elightbo** [comment]
I just noticed this today, too. Did you come up with a solution?

**Comment by shirshak55** [comment]
@elightbo i forgot to use auth:api middleware that was only problem

**Comment by shirshak55** [comment]
also make sure you configured config/auth.php. It was a silly mistake

**Comment by elightbo** [comment]
@shirshak55 Maybe I misunderstood the problem, but I thought the issue only came up when you were trying to access the user without using the `auth:api` middleware. I'd like my endpoint to be open, but only return certain data if there is an authenticated user.

**Comment by shirshak55** [comment]
you can use auth('api') like that.

**Comment by shirshak55** [comment]
use api middleware and you may able to use auth('api')

**Comment by elightbo** [comment]
Yep! Doing `auth('api')->user()` did the trick. https://github.com/laravel/passport/issues/175#issuecomment-351670973. Thanks for the help.
