### ISSUE TITLE
Invalid value provided for claim [nbf]

### ISSUE THREAD

**Issue by matheusb-comp** [tymondesigns/jwt-auth#1698]
### Subject of the issue
When overriding the `nbf` claim with the "adding custom claims" method described [here](https://jwt-auth.readthedocs.io/en/develop/auth-guard/#more-advanced-usage), using a timestamp in the future, an `InvalidClaimException` is raised with message `Invalid value provided for claim [nbf]`.

Inside [`validateCreate()`](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Claims/NotBefore.php#L35) it seems that the value is considered invalid for being in the future, however, the `nbf` claim is [defined](https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens) as "The earliest point in time that the token can be used".

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | not sure
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.6.37
| Package version   | 1.0.0-rc.2
| PHP version       | 7.2.10

### Steps to reproduce
```
$timestamp = now()->addMinutes(15)->timestamp;
$token = Auth::claims(['nbf' => $timestamp])->attempt($credentials);
```
The same happens if the claim is added inside the User model
```
public function getJWTCustomClaims()
{
    return [
        'nbf' => now()->addMinutes(15)->timestamp
    ];
}
```

### Expected behaviour
The token should be created with a `nbf` claim of "now + 15 minutes", meaning that it won't be valid until that point in time.

### Actual behaviour
`InvalidClaimException` raised, preventing the token from being created.

**Comment by tymondesigns** [comment]
Good catch! I guess not many people have been creating tokens for future use. I will patch this now

Thanks!
