### ISSUE TITLE
Running into a 500 error

### ISSUE THREAD

**Issue by nickrouty** [tymondesigns/jwt-auth#170]
Setting up a fresh install of Laravel with dingo/api package. I am getting the error:

PHP Fatal error:  Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in .../vendor/symfony/http-kernel/Exception/HttpException.php on line 29

 PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])' in .../vendor/symfony/http-kernel/Exception/HttpException.php:29
Stack trace:
#0 {main}
  thrown in ../vendor/symfony/http-kernel/Exception/HttpException.php on line 29

I am trying to make a call to generate a new auth token and am hitting this error... any one run into something like this before?

It's happening specifically when I am calling: 

$token = JWTAuth::attempt($credentials)

```php
<?php namespace App\Http\Controllers\V1;

use App\Models\V1\User;
use App\Http\Requests;
use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;

/**
 *
 */
class UserController extends BaseController {

	/**
     * Return users, paginated in sets of 25 by default.
     *
	 */
	public function index()
	{

        //$results = User::all();

	}

    public function authenticate()
    {

        $credentials = \Input::only('email', 'password');

        try {

            // Attempt to verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {

                // Something went wrong whilst attempting to encode the token
               return $this->response->errorUnauthorized(['error' => 'invalid_credentials']);

            }
        } catch (JWTException $e) {

            // Something went wrong whilst attempting to encode the token
            return $this->response->errorInternal(['error' => 'could_not_create_token'], 500);

        }


        // Everything went well, let's return the token and auth this user!
        return $this->response->array(array('token' => compact('token')));

    }

**Comment by tymondesigns** [comment]
looks like something specific to the way dingo/api handles exceptions.. I would open an issue there instead
