### ISSUE TITLE
Argument 2 passed to Lcobucci\JWT\Signer\Hmac::createHash() must be an instance of Lcobucci\JWT\Signer\Key, null given, called in /app/vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 34

### ISSUE THREAD

**Issue by shantudas** [tymondesigns/jwt-auth#1705]
### jwt: auth not working
Locally jwt worked fine but on heroku server its not working

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no
| Framework         | Laravel 
| Framework version | 5.7.9
| Package version   | 1.0.0-rc.3
| PHP version       | 7.2.1

### Steps to reproduce
try jwt on heroku server

### Expected behaviour
Token should be generated.

### Actual behaviour
{ "message": "Type error: Argument 2 passed to Lcobucci\\JWT\\Signer\\Hmac::createHash() must be an instance of Lcobucci\\JWT\\Signer\\Key, null given, called in .../app/vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 34", "status_code": 500 }

**Comment by muhtarudinsiregar** [comment]
are you already run command `php artisan jwt:secret` to generate jwt  secret key in your heroku?

**Comment by shantudas** [comment]
@muhtarudinsiregar yes , already did

**Comment by StevieDC** [comment]
I'm getting this error. All working fine on local dev but not live. Any suggestions please?

**Comment by shantudas** [comment]
> I'm getting this error. All working fine on local dev but not live. Any suggestions please?

Sorry @StevieDC I did not find any solution either. if you found any solution please let me know

**Comment by KonstantinLapkovsky** [comment]
@shantudas @StevieDC I met with a similar problem too. I changed the 'JWT Provider' to `'jwt' => Tymon\JWTAuth\Providers\JWT\Lcobucci::class` in the jwt.php file and cleared the config cache.

Controller constructor:
```
public function __construct(JWTAuth $jwtAuth)
{
    $this->jwtAuth = $jwtAuth;
}
```

**Comment by dagenius007** [comment]
Did this work? I am stuck.

**Comment by shantudas** [comment]
nope @dagenius007

**Comment by dagenius007** [comment]
@shantudas  Do you have a jwt.php in your config?

**Comment by StevieDC** [comment]
As mine was working locally I decided to bypass Git and Ftp everything up to the server (except .env). It then worked on the live server!

**Comment by amr** [comment]
You might need to clear your cache after running `php artisan jwt:secret`. I clear laravel cache using `php artisan clear-compiled && php artisan optimize`

**Comment by egiesemka** [comment]
stop php artisan serve, and start again

**Comment by CodyFortenberry** [comment]
I was having a problem on Fortrabbit. The fix for me was to upload my .env file. It was in the gitignore so it was not committed. At the bottom of the .env file is the jwt secret.

**Comment by tymondesigns** [comment]
This error happens when JWT_SECRET is not defined

**Comment by lucianobragaweb** [comment]
For me works only run: 

`php artisan jwt:secret`

and after:

`php artisan clear-compiled && php artisan optimize`

Works Fine!!
Thanks!!

**Comment by deniwerikmartins** [comment]
> For me works only run:
> 
> `php artisan jwt:secret`
> 
> and after:
> 
> `php artisan clear-compiled && php artisan optimize`
> 
> Works Fine!!
> Thanks!!

THIS WORKS!!!

**Comment by rafaelxavierborges** [comment]
composer update
php artisan vendor:publish
php artisan jwt:secret

Verify if JWT_SECRET is defined in your ENV file or even in config/jwt.php

php artisan config:clear
php artisan cache:clear
php artisan clear-compiled && php artisan optimize
composer dumpautoload

This worked fine for me.
=)

**Comment by soamazyng** [comment]
php artisan jwt:secret. I clear laravel cache using php artisan clear-compiled && php artisan optimize
This work! Thank you!!!

**Comment by mohanlar96** [comment]
> are you already run command `php artisan jwt:secret` to generate jwt secret key in your heroku?

Thank you :) working good

**Comment by ajaymarathe** [comment]
> are you already run command `php artisan jwt:secret` to generate jwt secret key in your heroku?

This helps.. thanks :)

**Comment by Nataanthoni** [comment]
Simply add the below JWT_SECRET from your local .env file at the bottom of your remote .env file

Something like;
JWT_SECRET=roCZauuldMpw5i4039393939393372y98bEWumqd9ls7Uk8DEpr0gIZ6WIWB

Hope this helps :)

**Comment by marcos1262** [comment]
For me, using Heroku, 
`heroku run php artisan jwt:secret  `
was not working, but
`heroku config:set JWT_SECRET=<your generated key>`
worked.
And then clear cache.

**Comment by ahmed126742** [comment]
> @shantudas @StevieDC I met with a similar problem too. I changed the 'JWT Provider' to `'jwt' => Tymon\JWTAuth\Providers\JWT\Lcobucci::class` in the jwt.php file and cleared the config cache.
> 
> Controller constructor:
> 
> ```
> public function __construct(JWTAuth $jwtAuth)
> {
>     $this->jwtAuth = $jwtAuth;
> }
> ```

Wooow greate jobe man this one works with me

**Comment by captain-burah** [comment]
This normally happens with ".env" configurations.

SERVER: Heroku
FRAMEWORK: Laravel 8.x

I added the JWT_SECRET key; which is available at the bottom of the ".env" file in Laravel 8, to the HEROKU config variables. Then it worked all right.

**Comment by RaihanulHoque** [comment]
> For me works only run:
> 
> `php artisan jwt:secret`
> 
> and after:
> 
> `php artisan clear-compiled && php artisan optimize`
> 
> Works Fine!! Thanks!!

Works for me too.
