### ISSUE TITLE
Creating a Token based on anything you like

### ISSUE THREAD

**Issue by Tarasovych** [tymondesigns/jwt-auth#1708]
### Subject of the issue
I'm trying to create custom claims accroding to [wiki](https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens#creating-a-token-based-on-anything-you-like).

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7
| Package version   | 1.0.0-rc.3
| PHP version       | 7.1

### Steps to reproduce
    $customClaims = JWTFactory::customClaims(['foo' => 'bar', 'baz' => 'bob']);
    $payload = JWTFactory::make($customClaims);
    $token = JWTAuth::encode($payload);
    dd($token);

### Expected behaviour
I expect string at `dd($token)`.

### Actual behaviour
> Tymon\\JWTAuth\\Exceptions\\TokenInvalidException(code: 0): JWT payload does not contain the required claims

**Comment by haidang666** [comment]
Hi @Tarasovych, you have to log user in first before using `customClaims` for example:  

        $credentials = request(['email', 'password']);

        $tokenWithCustom = auth('api')->attempt($credentials);

        $customClaims = ['foo' => 'bar', 'baz' => 'bob'];

        $payload = JWTFactory::make($customClaims);
        
        $token = JWTAuth::encode($payload);

        dd($token->get());  

FYI, you can check `Validators/PayloadValidator.php` to see what claims it required. `dd($payload)` you can see those required claims.

**Comment by Tarasovych** [comment]
@HaiDang666 hi, thanks for your response. So without authorized user I can't generate any JWT, am I right?

**Comment by haidang666** [comment]
@Tarasovych You can create token by creating a payload by manual for example:  

        $requiredClaims = [
             new Issuer('faker'),
             new IssuedAt(Carbon::now('UTC')) ,
             new Expiration(Carbon::now('UTC')->addDays(1)),
             new NotBefore(Carbon::now('UTC')),
             new JwtId('faker'),
             new Subject('faker')
        ]; 

        $claims = new Collection($requiredClaims);
        $payload = new Payload($claims, new PayloadValidator());

        $tokenInstance = JWTAuth::encode($payload);
        $token = $tokenInstance->get();

        $decode = JWTAuth::decode($tokenInstance);
        dd($decode);

and add this in beginning of the file:  

        use Tymon\JWTAuth\Payload;
        use Tymon\JWTAuth\Claims\Collection;
        use Tymon\JWTAuth\Validators\PayloadValidator;
        use JWTFactory;
        use JWTAuth;
        use Carbon\Carbon;
        use Tymon\JWTAuth\Claims\Issuer;
        use Tymon\JWTAuth\Claims\IssuedAt;
        use Tymon\JWTAuth\Claims\Expiration;
        use Tymon\JWTAuth\Claims\NotBefore;
        use Tymon\JWTAuth\Claims\JwtId;
        use Tymon\JWTAuth\Claims\Subject;

This may be not a good way, you should try to write new `PayloadValidator` instead

**Comment by Tarasovych** [comment]
Still wonder why don't [this](https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens#creating-a-token-based-on-anything-you-like) work as it is. Maybe I need to adjust `required_claims` array in `config/jwt.php` somehow...

**Comment by haidang666** [comment]
@Tarasovych yes, you can modify `required_claims` in config. It work as expected.
    
    'required_claims' => [
        'iss',
        // 'iat',
        // 'exp',
        // 'nbf',
        // 'sub',
        'jti',
    ],

**Comment by Tarasovych** [comment]
Now with config
```
    'required_claims' => [
        'iss',
//        'iat',
//        'exp',
//        'sub',
        'jti',
    ],
```
and
```
        $customClaims = JWTFactory::customClaims(['foo' => 'bar', 'baz' => 'bob']);
        $payload = JWTFactory::make($customClaims);
        $token = JWTAuth::encode($payload);
        dd($token);
```
I get

> Argument 2 passed to Tymon\\JWTAuth\\JWTAuth::__construct() must be an instance of Tymon\\JWTAuth\\Contracts\\Providers\\Auth, null given

**Comment by haidang666** [comment]
Can you upload your repo, here is my code  
https://github.com/HaiDang666/LrvAdmin/blob/custom-token/app/Http/APIControllers/Auth/APILoginController.php  
 make post request in at `http://localhost:8000/api/auth/login`

**Comment by Tarasovych** [comment]
@HaiDang666 your token is made inside `login()` which belongs to auth logic. I want to create token without any auth logic (if that's possible). Even without User entity.

**Comment by haidang666** [comment]
@Tarasovych `login()` just a normal function in `Controller`. I just moved it into other controller and it's still work

**Comment by ereztdev** [comment]
@Tarasovych Why did you close this? I haven't managed to make this token without auth either.
I am looking exactly at this issue now; Need to create a token with custom claims without any auth attempts/credentials.

**Comment by Tarasovych** [comment]
@ereztdev you can go like it's described in the [docs](https://jwt-auth.readthedocs.io/en/develop/quick-start/).

For any model you want you can ` implements JWTSubject` and go on.
