### ISSUE TITLE
Why does the guide suggest responding with redundant data?

### ISSUE THREAD

**Issue by Oleg-Arkhipov** [tymondesigns/jwt-auth#1719]
### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no

### Subject of the issue
Why does the guide suggests responding with token like this:
```json
{
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ",
    "token_type": "bearer",
    "expires_in": 3600
}
```
and not just:
```json
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"
```
or, if you want to support older JSON spec (which doesn't allow string as root):
```json
{
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"
}
```

I am not sure why would you need static `token_type: bearer` and especially `expires_in`, because expiration time is already baked in JWT itself.

**Comment by haidang666** [comment]
You can read [here](https://stackoverflow.com/questions/5925954/what-are-bearer-tokens-and-token-type-in-oauth-2) and [here](https://tools.ietf.org/html/draft-ietf-oauth-v2-15#section-4.3.3) for the protocol. I think it's just a good practice for implementation of jwt-auth. In some particular cases, clients may need those information.

**Comment by Oleg-Arkhipov** [comment]
@HaiDang666 what does OAuth 2.0 protocol has to do with this package? It is pure single token authentication (using JWT aas token format) and does not implement a single bit of OAuth. Putting 2 similar fields in response does not automatically give you anything. And expiration time is not redundant in case of OAuth with random string cause it is not embedded in it already (like in JWT token).

**Comment by tymondesigns** [comment]
@Oleg-Arkhipov you can return the token in any way you like. The clients might not care to decode the token to discover the expiration so it's just an example, it has nothing to do with oauth, only resembling the typical oauth response format
