### ISSUE TITLE
L5.1 "JWT payload does not contain the required claims"

### ISSUE THREAD

**Issue by theatrain** [tymondesigns/jwt-auth#172]
I keep getting this error message when using 

    \JWTAuth::attempt($request->only(['email','password']));

I have tried to trace the problem through the JWTAuth lib and the only thing I can come up with is that when it gets to JWTAuth.php line 187, the user identifier is passed through but not received in PayloadFactory.php Line 71.

If I put 

    dd(func_get_args()); 

in PayloadFactory.php Line 72, I can see that it was passed in but there are no arguments specified for the make() method.

The reason the error is being thrown is because the sub property is missing from the claims.

**Comment by wind930** [comment]
use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;

**Comment by theatrain** [comment]
I ended up removing and re-installing and it works. Think I must have messed something up when upgrading.
