### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by dennisoderwald** [tymondesigns/jwt-auth#1721]
Unfortunately jwt-auth is currently not compatible with Laravel 5.8. Is there an update planned?

**Comment by Oleg-Arkhipov** [comment]
But there is no 5.8 release yet.

**Comment by ereztdev** [comment]
I think he was referring to:
https://packagist.org/packages/laravel/framework#dev-master

**Comment by lofye** [comment]
I'm about to upgrade to 5.8.x-dev for an upcoming release, but we are heavily dependant on jwt-auth. Looking forward to this compatibility update :)

**Comment by xiaohuilam** [comment]
It's time to make compatible.

**Comment by ajcastro** [comment]
Waiting for a release compatible with laravel 5.8. When will it be available?

**Comment by mits87** [comment]
Actually Laravel 5.8 was released and jwt-auth package is still not compatible:

`Installation request for laravel/framework (locked at v5.8.0, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.0].`

**Comment by akr4m** [comment]
Waiting for Laravel 5.8 Compatibility.

**Comment by mathieutu** [comment]
See https://github.com/tymondesigns/jwt-auth/commit/34d8e48b2a3dd779f37e53fcb76f37e69e8cdd25

**Comment by dhcmega** [comment]
Hi, how do I install the compatible version? Thanks!

**Comment by leeovery** [comment]
Until it's tagged you can install from the git commit hash using composer:

`"tymon/jwt-auth": "dev-develop#34d8e48 as 1.0.0-rc.3.2"`

**Comment by dhcmega** [comment]
It worked, thanks a lot!

**Comment by leeovery** [comment]
I made a mistake though. Use dev-develop. Edited comment.

**Comment by dhcmega** [comment]
Ok, changed it and I think it's better, because nesbot was downgraded to v1.36.2, and now it's back to v2.14.2.
Thanks again!

**Comment by tymondesigns** [comment]
Forgot to close this one. Release has been made for this

**Comment by cmanna** [comment]
> dev

how i could not get you

**Comment by AnimalInstinct** [comment]
"laravel/framework": "5.8.0"

"tymon/jwt-auth": "dev-develop#34d8e48 as 1.0.0-rc.3.2"

php artisan vendor:publish
In ProviderRepository.php line 208:                                                            
Class 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider' not found

**Comment by cmanna** [comment]
Use latest tymon and replace the fire function by dispatch. fire function has been deprecated in new version laravel 5.8..

**Comment by Jovanie25** [comment]
how to make an authentication system on laravel using auth firebase
