### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by billriess** [tymondesigns/jwt-auth#1726]
What is the best way to handle errors when using jwt-auth? Currently, I am using both web and api guards. If an api user sends a bad token, they get a response of the login page not a json response indicated an invalid token as expected. Is there some higher level thing I'm missing here? Do I have to catch exceptions in the Exceptions\Handler@render? What are the exceptions I can catch if so?

To clarify, this is for 1.0.0-rc3, the wiki says exceptions are coming soon for a little while now.

**Comment by jampack** [comment]
`app\Exceptions\Handler.php` in render method:
```
if($request->wantsJson()) {
    if($exception instanceof AuthenticationException){
        return response()->json(['unauthenticated'],401)
    }
}
```
