### ISSUE TITLE
Invalid blacklist processing

### ISSUE THREAD

**Issue by ghost** [tymondesigns/jwt-auth#1728]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.6
| Package version   | 1.0.0.rc3
| PHP version       | 7.2.13

### Steps to reproduce
When invalidating tokens generated using setTTL (null)
Run add flow, not addForever.

### Expected behaviour
If invalidate an unexpired token,
it must be permanently blacklisted via Func (Forever)

### Actual behaviour
If Blacklist is saved as Func (Put) instead of Func (Forever)
It will be removed from the list after a certain period of time.
The invalidated token becomes a reusable token.

**Comment by tymondesigns** [comment]
I believe is fixed by #1775
