### ISSUE TITLE
Error 401 ?

### ISSUE THREAD

**Issue by donnygunawan93** [tymondesigns/jwt-auth#173]
I have code on my angular.

$scope.getNewToken();

Thats function send old token to server then receive a new token from jwt.refresh middleware.

When i do loop with interval 2 sec.

$scope.getNewToken();//delay 2 sec,
$scope.getNewToken();//delay 2 sec,
$scope.getNewToken();//delay 2 sec,
$scope.getNewToken();//delay 2 sec,
$scope.getNewToken();//delay 2 sec, infinite, like so

thats works fine,

but when i do loop with interval 1 sec,

for the 1st request thats ok i can get new token from server, but...
for the 2nd request i get error 401,

and the question is why the server not accept my token? any suggest?

**Comment by albrethandoyo** [comment]
oh sorry thats issue on my angular not on server LoL

**Comment by albrethandoyo** [comment]
oh yes, i was checking my angular, thats was ok, i think this is server issues, any one help?

**Comment by tymondesigns** [comment]
This is probably related to to #162 

And should be resolved in the next version

Not sure why you'd do this in a real app though?

**Comment by donnygunawan93** [comment]
actually i just want to chain some promises, 
so code above just for trace where is the problems hahaha.

ok i will wait for the next version thx buddy ^_^

**Comment by tymondesigns** [comment]
No worries
