### ISSUE TITLE
php artisan jwt:secret --env=testing set JWT to .env instead .env.testing

### ISSUE THREAD

**Issue by Tarasovych** [tymondesigns/jwt-auth#1734]
### Subject of the issue
`JWT_SECRET` doesn't set while working with `.env.testing`.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.7
| Package version   | 1.0.0-rc.3
| PHP version       | 7.1

### Steps to reproduce
1. Create `.env.testing` in the framework root folder.
2. Run `php artisan jwt:secret --env=testing` in the terminal.

### Expected behaviour
Expected `JWT_SECRET` in the `.env.testing`.

### Actual behaviour
There is no `JWT_SECRET` in the `.env.testing`.

**Comment by tymondesigns** [comment]
Can you give an example of other packages doing this? Doesn't seem worth it

**Comment by Tarasovych** [comment]
@tymondesigns it's default Laravel behavior (when you run `php artisan migrate --env=testing` for example), so I thought it might work as expected.

**Comment by sn0rk64** [comment]
You can solve the problem using this:
`sed -i '/^JWT_SECRET=/d' .env.testing; echo "JWT_SECRET=$(php artisan jwt:secret --show)" >> .env.testing`

**Comment by surajknanda10** [comment]
This error generally display when you install jwt package in laravel 5.5 version. then after you set service providers and run following command.

php artisan jwt:generate
then you seen this error message in terminal.

how to resolve it? simple follow this step

Step - 1 Re-install package

composer require tymon/jwt-auth:dev-develop --prefer-source
or the following is a new release package use laravel 6.X

composer require tymon/jwt-auth:1.0.*
in this developement version this errors fixed.

Step - 2 Set Service Provider

'providers' => [
    ....
    Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class to 
    Tymon\JWTAuth\Providers\LaravelServiceProvider::class
],
Step - 3 Generate key

php artisan jwt:secret
