### ISSUE TITLE
How to revoke all old tokens after change password ?

### ISSUE THREAD

**Issue by evansnguyen0104** [tymondesigns/jwt-auth#1738]
### How to revoke all old tokens after change password ?

I need revoke all old tokens after user change password.I had try refresh token but it not working ! 

### Environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | no 
| Framework         | Laravel
| Framework version | 5.7
| Package version   | 1.0.0-rc.3
| PHP version       | 7.2

**Comment by sebastianhelbig** [comment]
- Store the timestamp of last password change server side. 
- Compare `iat` of the token with the saved timestamp.
- If `iat` is older than saved timestamp, the token should not be accepted by your server.

**Comment by tymondesigns** [comment]
What @sebastianhelbig said 😄
