### ISSUE TITLE
RefreshToken middleware sends refreshed token even if expired

### ISSUE THREAD

**Issue by drawmyattention** [tymondesigns/jwt-auth#174]
Given I have an expired token, and I make a request to an endpoint that has the ```jwt.refresh``` middleware, I would expect the an exception to be thrown but to not automatically receive a refreshed token.

Currently, the middleware sends back a refreshed token. It's easy enough to change this behaviour but I wanted to see what the logic behind this was before making any changes or submitting a PR.

**Comment by tymondesigns** [comment]
This is expected behaviour. A token can be refreshed up until the `refresh_ttl` has expired, regardless of the expired state of the token
