### ISSUE TITLE
使用JWT报错 框架是lumen Non-static method Tymon\JWTAuth\JWT::factory() should not be called statically

### ISSUE THREAD

**Issue by 469231308** [tymondesigns/jwt-auth#1741]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no / yes
| New Feature?      | no / yes
| Framework         | Laravel / Lumen
| Framework version | 5.x.y
| Package version   | 1.x.y
| PHP version       | 5.x.y / 7.x.y

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by tymondesigns** [comment]
`Tymon\JWTAuth\JWT` is not a facade if that's what you mean
