### ISSUE TITLE
must be an instance of Tymon\JWTAuth\Contracts\Providers\Storage, null given

### ISSUE THREAD

**Issue by NikolaGavric94** [tymondesigns/jwt-auth#1744]
### Subject of the issue
I have `redis` setup as my caching driver and I have an instance running and it is working because I have tests to check if the cache is being retrieved in timely manner and with correct values. Any help would be appreciated, btw I have the latest config file and I have setup the interface on the User class properly and changed the driver to jwt

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Lumen
| Framework version | 5.7.22
| Package version   | dev-master
| PHP version       | >= 7.2.6

### Steps to reproduce
I've followed the basic steps to install the package and set everything up with Lumen 5.7, after that whatever command that I run I get this error:

```
Argument 1 passed to Tymon\JWTAuth\Blacklist::__construct() must be an instance of Tymon\JWTAuth\Contracts\Providers\Storage, null given, called in x/y/vendor/tymon/jwt-auth/s  
  rc/Providers/AbstractServiceProvider.php on line 288
```

### Expected behaviour
Shouldn't show the error message

### Actual behaviour
The error message is shown

**Comment by NikolaGavric94** [comment]
Nvm, this was an issue on my end, closing it

**Comment by Digital4design** [comment]
I am also facing this issue. Can you please let me know how you fix this issue on your end? 
Thanks.

**Comment by ajarti** [comment]
Hi @NikolaGavric94 ,
                                      I am going mad trying to solve this, do you mind sharing what had gone wrong for you?

Thanks.

**Comment by ajarti** [comment]
Ok I solved it for me ... had to have redis:latest in my docker compose and not redis:3.2 as the image.

Hope that helps someone.
