### ISSUE TITLE
Extend token expiry into future each time it is used to hit the server

### ISSUE THREAD

**Issue by codekeyz** [tymondesigns/jwt-auth#1748]
### Subject of the issue
I am building a backend to serve both web & mobile frontends using Lumen. JWT Authentication and logout works fine but user gets kicked out after the default token expiry. Is there any way i can extend the expiry into the future anytime a request hits the server with the token ?

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no / yes
| Framework         | Lumen
| Framework version | 5.7.*
| Package version   | 1.0@dev
| PHP version       | 7.1.3

**Comment by hoangmy92** [comment]
JWT token will consistency through its lifetime. 
So you need to re-generate new token and save the new generated token again in your local. 
If so, just use the refresh feature https://jwt-auth.readthedocs.io/en/develop/auth-guard/#refresh
