### ISSUE TITLE
life time ( JWT_TTL)

### ISSUE THREAD

**Issue by mmteyrek** [tymondesigns/jwt-auth#1749]
### Subject of the issue
I'm trying to change the time life of my token so I set JWT_TLL in .env to 43800 but the life time remains to 1 hour.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no 
| Framework         | Laravel
| Framework version | 5.4.36
| Package version   | dev-develop
| PHP version       | php7.2.14

### Steps to reproduce
set JWT_TTL in .env to 43800

### Expected behaviour
life time 1 month

### Actual behaviour
life time remains to 1 hour

**Comment by hoangmy92** [comment]
Try to access **tinker** and type **config('jwt.ttl')**, what is the returned value?

**Comment by mmteyrek** [comment]
60

![image](https://user-images.githubusercontent.com/17122420/52788031-fa3f7580-305f-11e9-87fa-52ef302ea4c5.png)

![image](https://user-images.githubusercontent.com/17122420/52788435-37583780-3061-11e9-8f88-81f905ca8367.png)



![image](https://user-images.githubusercontent.com/17122420/52788082-1f33e880-3060-11e9-92a7-590c53965315.png)

**Comment by mmteyrek** [comment]
I found the issue.
I intialise my cach using this command et it's working now 👍

php artisan config:cache
