### ISSUE TITLE
what cache key format ?

### ISSUE THREAD

**Issue by oleksandr-mykhailenko** [tymondesigns/jwt-auth#1757]
Hello, I'm use a Redid store to save black list, but I have 2 API clinet, and my second API should check the redis store.
And how I have this format https://imgur.com/6hqiDuG
laravel_cache:8418d3c17340bff59466c6dafd59211d5dc9fd34:14xBRF0jEsvCUkPl
 where created a hash (8418d3c17340bff59466c6dafd59211d5dc9fd34) before jti param ? 
Thank you

**Comment by tymondesigns** [comment]
This is how the laravel framework stores cache keys in redis. You can access the blacklisted items by doing the following
```php
// $jti is the value of the `jti` claim
Cache::tags('tymon.jwt')->get($jti);
```
