### ISSUE TITLE
Class jwt does not exist

### ISSUE THREAD

**Issue by varichs** [tymondesigns/jwt-auth#1758]
### Your environment
| Q                 | A
| ----------------- | ---

| Framework         | Laravel 
| Framework version | 5.5.*
| Package version   | 1.0.0-rc.1
| PHP version       |  7.1

![jwt](https://user-images.githubusercontent.com/22510514/52953578-e2028a00-33c2-11e9-9ad8-3741c73058ba.JPG)

**Comment by ricardoperovano** [comment]
hey, did you solved this issue @varichs ?

**Comment by varichs** [comment]
> hey, did you solved this issue @varichs ?

yes,  I just used the wrong middleware name

**Comment by chaucachavez** [comment]
@varichs  I have the same error, can you specify how you solved it? please

**Comment by alexarros** [comment]
@chaucachavez 

I fixed, making this change

AuthController.php

old

public function __construct()
    {
        $this->middleware('jwt', ['except' => ['login']]);
    }


new

public function __construct()
    {
        $this->middleware('auth:api', ['except' => ['login']]);
    }

**Comment by dalejodc** [comment]
Thanks a lot @alexarros ! :clap: It worked for me.

**Comment by alvarodicopgroup** [comment]
it works thanks!

**Comment by michabbb** [comment]
in case someone finds this because of the error "Target class [auth.jwt] does not exist.": don´t forget to add:

```php
protected $routeMiddleware = [
   'auth.jwt'         => Authenticate::class,
];
```
