### ISSUE TITLE
JWT payload does not contain the required claims

### ISSUE THREAD

**Issue by Murwa** [tymondesigns/jwt-auth#176]
Hey @tymondesigns, just updated and got 
> TokenInvalidException in PayloadValidator.php line 57:
> JWT payload does not contain the required claims

**Comment by tymondesigns** [comment]
Which version?

**Comment by Murwa** [comment]
The dev-develop branch - 0.6.@dev

**Comment by tymondesigns** [comment]
Hmm.. this hasn't changed. Are you sure that your config matches whats in your token?

**Comment by Murwa** [comment]
I have default config; I get the error coz 'sub' is not provided: I get a token if I remove 'sub' from config, but now it's useless coz there won't be user infor 😐

**Comment by tymondesigns** [comment]
that's weird.. I will take a look when I'm back at my machine.

could you post your code your using to create the token

**Comment by Murwa** [comment]
Here is my config 
~~~php 
'required_claims' => ['iss', 'iat', 'exp', 'nbf', 'sub', 'jti'],
~~~

Then my auth code 
~~~php
        $this->validate($request, [
            'email' => 'required', 'password' => 'required',
        ]);
        try {
            if (!$token = JWTAuth::attempt($this->getCredentials($request))) {
                throw new Exception('Invalid credentials');
            }
            return response()->json(['token' => $token]);
        } catch (Exception $e) {
            return response()->json(['error' => $e->getMessage()]);
        }
~~~

**Comment by jayhealey** [comment]
This is still an issue. It looks like the custom claims aren't being passed to `make` function in the `PayloadFactory` class.

See line 183 in `JWTAuth`:
```
return $this->factory()->make($this->getClaimsArray($user));
```

The `make` function from `PayloadFactory` doesn't receive parameters:
```
    public function make()
    {
        $claims =  $this->buildClaims()->resolveClaims();

        return new Payload($claims, $this->validator, $this->refreshFlow);
    }
```

My suggestion would be to replace it with:
```
    public function make($claims = array())
    {
        $claims =  $this->addClaims($claims)->buildClaims()->resolveClaims();

        return new Payload($claims, $this->validator, $this->refreshFlow);
    }
```

**Comment by tymondesigns** [comment]
Apologies.. Didn't post back here... This has changed as described in https://github.com/tymondesigns/jwt-auth/pull/177#issuecomment-120417203

**Comment by jayhealey** [comment]
I can see - but that's not solving the problem when using `JWTAuth::fromUser`.

As of the latest commit, using `"tymon/jwt-auth": "0.6.*`, I still receive this error using `JWTAuth::fromUser`:

```
JWT payload does not contain the required claims
```

This used to work before the claims were reworked.

__*Whilst the `makePayload` function in `JWTAuth` is passing forward the claims, the `make` function being called does not receive the claims*__.

See line 183 in `JWTAuth` (https://github.com/tymondesigns/jwt-auth/blob/develop/src/JWTAuth.php#L183):

```
    public function makePayload(JWTSubject $user)
    {
        return $this->factory()->make($this->getClaimsArray($user));
    }
```

Whilst the `$this->getClaimsArray($user)` is returns the claims array and passed it to `make`, the `make` function isn't receiving it, because it's currently defined like this:

```
    public function make()
    {
        $claims = $this->buildClaims()->resolveClaims();

        return new Payload($claims, $this->validator, $this->refreshFlow);
    }
```

See the latest code:
https://github.com/tymondesigns/jwt-auth/blob/develop/src/PayloadFactory.php#L66

__*There are no parameters set in the `make` function, and the custom claims are not being added to the `$claims` array.*__

The change would be to tweak it to be:

```
   public function make($claims = array())
    {
        $claims =  $this->addClaims($claims)->buildClaims()->resolveClaims();

        return new Payload($claims, $this->validator, $this->refreshFlow);
    }
```

I'm happy to make a pull request if need be, as it looks like #177 was committed and then reverted.

**Comment by tymondesigns** [comment]
Ah yea, I see what you mean.. Will fix this shortly, and also I'll need to look at my tests for this, as they were not failing :/

My fix would be slightly different than your suggestion (although that would indeed work) but I'm only on my phone ATM, so can't illustrate that easily right now

Thanks

**Comment by trousers** [comment]
I had this error after setting the TTL to null

**Comment by eness** [comment]
to overcome this issue for those who use JWT_TTL=null, remove 'exp' key from your config/jwt.php's 'required_claims' array then you'll be fine! :)

**Comment by qazihamayun** [comment]
@trousers and @eness Really Thankful to you guys. It solved issue

**Comment by SimeonDominiq** [comment]
@trousers  & @eness You saved my time. It solved the issue after much hours of debugging. Thank God

**Comment by ereztdev** [comment]
> required_claims

not really, removed the exp key and still receiving error.

**Comment by kjostling** [comment]
> > required_claims
> 
> not really, removed the exp key and still receiving error.

@ereztdev you got any insights to share? I believe I just got the same issue as you...

**Comment by kamil-kielczewski** [comment]
In file `config/jwt.php` from key

`'required_claims' => ['iss', 'iat', 'exp', 'nbf', 'jti', 'sub']`

I remove unused claims (in my case `'sub'`)

**Comment by mhdiiilham** [comment]
Ah, thanks for this comment, finally I know where I did wrong

> I had this error after setting the TTL to null
> 
> Edit: Aha!
> 
> #340

**Comment by devleinad** [comment]
@eness  Thank you very much
