### ISSUE TITLE
JWT usage in web routes

### ISSUE THREAD

**Issue by grgsllnd** [tymondesigns/jwt-auth#1760]
### Subject of the issue
Describe your issue here.
Trying to secure images in storage with auth:web middleware
Route::get('media/{filename}','MediaController@fetchMedia')->name('get.file');
class MediaController extends Controller{
	public function __construct(){
        $this->middleware('auth');
        //$this->middleware('auth:web');
        //$this->middleware('auth:api');
    }
...
### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.7.27
| Package version   | ^1.0.0
| PHP version       | 7.2

### Steps to reproduce
Tell us how to reproduce this issue.
Install jwt
try to use in web routes jwt auth for media queries

### Expected behaviour
Tell us what should happen
Is it possible to verify if user is authenticated via ajax?
Store jwt token in web api when user login 
then images can be filtered by user-id authorisations

### Actual behaviour
Tell us what happens instead

Redirected to route /login because only authenticated via jwt

**Comment by jadsalhani** [comment]
If you're using Ajax then the `content-type` and `accept` headers should both be set to `application/json` for laravel to detect that it's an API request

**Comment by philbenoit-ibsa** [comment]
@GregoireSailland Are you checking the JWT is sent through on the media request? Also, double check your auth on the route to ensure its setup correctly to use JWT. 

The default Laravel web route does not supply back the JWT so you would need to ensure the user has this before hitting any route secured by the token.

**Comment by Ore00** [comment]
@gsailland It appears that this isn't an issue anymore? Is this one good to close?
