### ISSUE TITLE
JWT Auth doesn't have Laravel 5.8 Compatibility and Carbon 2

### ISSUE THREAD

**Issue by akr4m** [tymondesigns/jwt-auth#1764]
https://github.com/tymondesigns/jwt-auth/releases/tag/1.0.0-rc.3

Please release Larvel 5.8 compatibility package with nesbot/carbon: v2.* require

**Comment by eleftrik** [comment]
Any temporary workaround?
Thank you

**Comment by mathieutu** [comment]
https://github.com/tymondesigns/jwt-auth/pull/1762

**Comment by mathieutu** [comment]
See https://github.com/tymondesigns/jwt-auth/commit/34d8e48b2a3dd779f37e53fcb76f37e69e8cdd25
And #1765

**Comment by mathieutu** [comment]
Just wait for a new tag.

**Comment by mathieutu** [comment]
Hi @tymondesigns could you make a minor tag with the last commits, so we can use them in our projects?

Thanks!

**Comment by gdespirito** [comment]
+1

**Comment by ldiebold** [comment]
+1

**Comment by tymondesigns** [comment]
I'll have a tagged release for you guys in the coming days, Thank you for your patience!

**Comment by valehasadli** [comment]
guys, my composer.json for jwt-auth ->  "tymon/jwt-auth": "^1.0.0-rc.1" and I want to update Laravel version 5,7 to 5.8, now is everything okay or have some issues?

**Comment by atapatel** [comment]
Duplicate of https://github.com/tymondesigns/jwt-auth/issues/1721

**Comment by akr4m** [comment]
`"tymon/jwt-auth": "dev-develop#f72b8eb as 1.0.0-rc.3.2"`

Try this and update.
This is solution for: 

- chore(deps): Allow Laravel 5.8
- ci: remove xdebug
- Add Carbon 2 compatibility. (#1765)
- fix(storage): Convert minutes to seconds for Laravel 5.8
- fix(carbon): Fix for carbon issue
- test: Fix for other carbon issue
- increase secret key length to 64

**Comment by Vagmacker** [comment]
Hi guys


I tried to follow the instructions given above but I did not succeed, I'm using the dev-develop#63698d304554e5d0bc3eb481cc260a9fc900e151 (last version until today)

can you help me ?

**Comment by ibraah88** [comment]
this one works for me 
` "tymon/jwt-auth": "dev-develop#f72b8eb as 1.0.0-rc.3.2",
`

**Comment by Vagmacker** [comment]
This does not work for me. Am I doing something wrong?

**Comment by ibraah88** [comment]
can you paste the block **require**  of your composer.json

**Comment by Vagmacker** [comment]
"require": {
    "php": "^7.1.3",
    "barryvdh/laravel-cors": "^0.11.0",
    "canducci/zipcode": "1.1",
    "fideloper/proxy": "^4.0",
    "guzzlehttp/guzzle": "5.3.2",
    "illuminate/contracts": "5.8.*",
    "illuminate/filesystem": "^5.8",
    "illuminate/support": "5.8.*",
    "laravel/framework": "5.8.*",
    "laravel/tinker": "^1.0",
    "mdanter/ecc": "^0.5.2",
    "phpseclib/phpseclib": "^2.0",
    "spatie/laravel-permission": "^2.12",
    "symfony/finder": "^4.2",
    "tymon/jwt-auth": "dev-develop#f72b8eb as 1.0.0-rc.3.2"
  },

**Comment by akr4m** [comment]
```
"require": {
"php": "^7.1.3",
"barryvdh/laravel-cors": "^0.11.0",
"canducci/zipcode": "1.1",
"fideloper/proxy": "^4.0",
"guzzlehttp/guzzle": "5.3.2",
"illuminate/contracts": "5.8.",
"illuminate/filesystem": "^5.8",
"illuminate/support": "5.8.",
"laravel/framework": "5.8.*",
"laravel/tinker": "^1.0",
"mdanter/ecc": "^0.5.2",
"phpseclib/phpseclib": "^2.0",
"spatie/laravel-permission": "^2.12",
"symfony/finder": "^4.2",
"tymon/jwt-auth": "^1.0"
},
```

```ssh
composer update
```

Brother, do it. I think, This will work for you

**Comment by Vagmacker** [comment]
Which middleware should I use?
Even with the changes still continues with this bug

**Comment by Vagmacker** [comment]
My route:

Route::group(['middleware' => ['auth:api', 'jwt.refresh']], function () {

        Route::post('/logout', 'AuthController@logout')->name('logout');
        Route::get('/auth/user-logged', 'AuthController@userLogged')->name('user.logged');

        Route::apiResources([
            'roles' => 'RoleController',
            'cells' => 'CellController',
            'churches' => 'ChurchController',
            'permissions' => 'PermissionController'
        ]);
    });

**Comment by Jovanie25** [comment]
moi j'ai toujour un petiit souci
avec  composer require tymon/jwt-auth 1.0.0-rc3.2
sa m'affiche
[InvalidArgumentException]
  Could not find package tymon/jwt-auth in a version matching 1.0.0-rc3.2

**Comment by ibraah88** [comment]
use : **"tymon/jwt-auth": "^1.0"** in your **composer.json** and run **composer update**

**Comment by Jovanie25** [comment]
merci pour la reponse

**Comment by Jovanie25** [comment]
comment faire un systeme d'authentification sur laravel en utilisant firebase auth

**Comment by eleftrik** [comment]
@Jovanie25 Please use English language.

**Comment by Jovanie25** [comment]
how to make an authentication system on laravel using auth firebase

**Comment by eleftrik** [comment]
> how to make an authentication system on laravel using auth firebase

Please search on Google. This thread is an issue and is not about Firebase auth. Thank you

**Comment by Jovanie25** [comment]
ok

**Comment by connecteev** [comment]
can we please fix this for laravel 5.8? Not sure why this was closed :(

**Comment by mfn** [comment]
@connecteev the latest https://github.com/tymondesigns/jwt-auth/releases/tag/1.0.0-rc.4.1 works with 5.8, I'm running it.

If you've any specific problems, please create a new issue, thanks!

**Comment by chan-dev** [comment]
why does JWT specific exceptions doesn't have their own status code such as `TokenInvalidException`?
