### ISSUE TITLE
auth()->attempt() cant make login

### ISSUE THREAD

**Issue by Mabs2001** [tymondesigns/jwt-auth#1766]
### Subject of the issue
I'm using a Laravel Api with Jwt authentication but the credentials arrive correctly by the api routes but always gives fail in login with the correct credentials.

`public function login()
    {
        $credentials = request(['email', 'password']);
        $token = NULL;
        if (!$token = auth()->attempt($credentials)) {
            return response()->json(['error' => 'Email or password doesn\'t exist'], 401);
        }
        return $this->respondWithToken($token);
    }`

**Comment by tymondesigns** [comment]
Please provide more detail
