### ISSUE TITLE
Can't login user except the id =1

### ISSUE THREAD

**Issue by owen4comes** [tymondesigns/jwt-auth#1767]
### Subject of the issue
Can't login user except the id =1

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | I dont know
| New Feature?      | no
| Framework         | Laravel 
| Framework version | 5.5
| Package version   | 1.0.0.rc-1
| PHP version       |  7.1.5

### Steps to reproduce
At first , I login the user (id=1) ,it works. But when I logout and want to login another user(id != 1), the login method shows me it's login success ,but when I request another api with middleware jwt.auth ,it fail in authenticate() method :
```
if ($result = $this->auth->parseToken()->authenticate()) {
                return $next($request);
            }
```
and I guess jwt cache the id=1 user ,how can I fix this?

and this is my logout method:
```
Auth::guard('api')->logout();
```

### Expected behaviour
I can login every user

### Actual behaviour
I can only login the user where id=1

**Comment by LeonAlvarez** [comment]
I suggest to try new rc.

**Comment by tymondesigns** [comment]
I would also suggest upgrading to the latest version and report back if still an issue, but I'm doubtful this is an issue with the package
