### ISSUE TITLE
Make 0.5 for laravel 5.8

### ISSUE THREAD

**Issue by AucT** [tymondesigns/jwt-auth#1771]
Is there any chance for appearing 0.5 or 0.6 version that support laravel 5.8 ?

I've tried 1.0 but it is like version for fully replacing auth to jwt. And the hack ($token = auth('api')->attempt($credentials);)  didn't work. Also it doesn't say anything why user can't login.

**Comment by LeonAlvarez** [comment]
Did you try "tymon/jwt-auth": "dev-develop#f72b8eb as 1.0.0-rc.3.2" 
Im using it with laravel 5.8
`$token = auth()->attempt($credentials)`

I got the api as default guard but it should work also if u specify a guard.

**Comment by tymondesigns** [comment]
No plans to touch the `0.5.*` releases with the exception of any possible security patches

**Comment by Maharramoff** [comment]
@LeonAlvarez Thanks. It worked!
