### ISSUE TITLE
Seprerating the Payload and the Auth

### ISSUE THREAD

**Issue by privatmamtora** [tymondesigns/jwt-auth#178]
I am wondering if the Payload part of this package could be separated from the Authentication.
So dependency wise it could be
jwt-auth
     |_ jwt-payload
                  |_ namshi/jose

It seems the jwt-payload would be a very valuable package. Out of the 7 libraries that depend on namshi none implement just the payload part of the jwt.

**Comment by tymondesigns** [comment]
When you say Payload, which parts exactly do you mean?

Tbh I've been thinking of splitting out this package so its truly framework agnostic.

Are you suggesting that other jwt packages may want to require the payload aspect alone?

**Comment by privatmamtora** [comment]
Yes

So the following in a separate package
Payload.php
PayloadFactory.php
Token.php
Validators/*
Facades/JWTFactory.php

Almost everything directly connected to namshi/jose

**Comment by privatmamtora** [comment]
Is it ok if I send a pull request (Need it now, I am already half way done)?

**Comment by tymondesigns** [comment]
Not sure how you could achieve this with a PR?

It's something I'll consider though for sure

**Comment by privatmamtora** [comment]
I have done it. But I havn't been able to completely test it because of https://github.com/tymondesigns/jwt-auth/issues/179, and other things (dev branch changes)

The auth lib: https://github.com/privatmamtora/jwt-auth/tree/jwt-payload
The payload lib: https://github.com/privatmamtora/jwt-payload
It is just a starter. (I added you as collaborator)

**Comment by privatmamtora** [comment]
Actually the only code that needed to change involves the "Custom Claims".
Remove it from JWTAuth and only allow the "Factory" to manipulate claims.
The JWTAuth class will be responsible for "custom claims" (user claims).
Once that is done the payload (claims) and the JWTAuth will be decoupled.
(Users that only use the payload would have to update the required claims, because the current validator requires the `iss` claim)

**Comment by christianbartels** [comment]
I'm interested in this as well to be able to generate different tokens with different claims. Currently custom claims get included in all subsequent generated payloads and there doesn't seem to be a way to remove a claim, once it has been added to JWTAuth. Something like `$jwtAuth->manager()->clearPayload()` would really help...
