### ISSUE TITLE
  There are no commands defined in the "jwt" namespace problem

### ISSUE THREAD

**Issue by OAmor** [tymondesigns/jwt-auth#1784]
### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 5.7.28
| Package version   | 1.x.y
| PHP version       |  7.1.27

### Steps to reproduce
i followed the same docs steps but when i run 
`php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"
`
i don't get the config/jwt.php file also when i run 
`php artisan jwt:secret`
i get this error

>   There are no commands defined in the "jwt" namespace.  

i tried many solutions like clearing cash but always the same problem

**Comment by OAmor** [comment]
finally find the solution
we should update the version manually in `composer.json` to for laravel >=5.5 to `"tymon/jwt-auth": "^1.0"` and then run `composer update`

**Comment by ajaymarathe** [comment]
> finally find the solution
> we should update the version manually in `composer.json` to for laravel >=5.5 to `"tymon/jwt-auth": "^1.0"` and then run `composer update`

updating `composer.json` helps me :) thanks !!
