### ISSUE TITLE
[Recommendation] Integrate jwt-auth with  Golang

### ISSUE THREAD

**Issue by rizkyarlin** [tymondesigns/jwt-auth#1789]
[Recommendation] Integrate jwt-auth with  Golang

Hi guys. My team has been using jwt-auth for almost every project that we did.
Now we are trying to build a big application which forces us to use Laravel and Golang for the REST Service. What is your recommendation for me to approach this?

Just build the Laravel with JWT Auth and build a middleware on Golang that call the API on Laravel which will give a response of user role and detail if authenticated? I wonder if it will give us performance issues in the future.

Thanks!

| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | no 
| Framework         | Laravel
| Framework version | 5.8
| Package version   | 1.*
| PHP version       | 7.3

**Comment by code-quantum** [comment]
I see another solution of this problem. JWT does not need intermediate requests.  You can store the information you need in payload part of jwt token. I suppose it would be nice to give an example of using the jwt library for go in conjunction with laravel.

see for understanding https://en.wikipedia.org/wiki/JSON_Web_Token
