### ISSUE TITLE
nestbot/carbon

### ISSUE THREAD

**Issue by mennovanhout** [tymondesigns/jwt-auth#1795]
I was seeing some issues here that are closed because this issue should be solved.
However i'm still having this issue with a brand new Laravel 5.8 installation.

Problem 1
    - Installation request for tymon/jwt-auth ^0.5.12 -> satisfiable by tymon/jwt-auth[0.5.12].
    - Conclusion: remove nesbot/carbon 2.16.2
    - Conclusion: don't install nesbot/carbon 2.16.2
    - tymon/jwt-auth 0.5.12 requires nesbot/carbon ~1.0 -> satisfiable by nesbot/carbon[1.0.0, 1.0.1, 1.1.0, 1.10.0, 1.11.0,
1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.2.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.3.0, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0].
    - Can only install one of: nesbot/carbon[1.26.3, 2.16.2].
    - Can only install one of: nesbot/carbon[1.26.4, 2.16.2].
    - Can only install one of: nesbot/carbon[1.27.0, 2.16.2].
    - Can only install one of: nesbot/carbon[1.28.0, 2.16.2].
    - Can only install one of: nesbot/carbon[1.29.0, 2.16.2].
    - Can only install one of: nesbot/carbon[1.29.1, 2.16.2].
    - Can only install one of: nesbot/carbon[1.29.2, 2.16.2].
    - Can only install one of: nesbot/carbon[1.30.0, 2.16.2].
    - Can only install one of: nesbot/carbon[1.31.0, 2.16.2].
    - Can only install one of: nesbot/carbon[1.31.1, 2.16.2].
    - Can only install one of: nesbot/carbon[1.32.0, 2.16.2].

**Comment by StudiosKelemy** [comment]
Carbon 2 is officially supported by Laravel since the version 5.8, if you want to use it on a lower version, you can follow those steps:

Set explicitly the Carbon version and add the adapter in your composer.json:

{
    "require": {
        "nesbot/carbon": "2.16.3 as 1.34.0"
        "kylekatarnls/laravel-carbon-2": "^1.0.0"
    }
}

**Comment by StudiosKelemy** [comment]
Use 1.25.0 alias for Laravel 5.6, 1.34.0 for other versions as each version of Laravel has its own range of Carbon compatibility, you have to take 2.3.0 as the real used version, then pick an alias among versions Laravel supports. You may have other dependencies with other Carbon restrictions. If so, we cannot ensure Carbon 2 will works with them as Carbon 1 did, but you can still try an other version alias. To be sure an alias will be compatible with all of your current dependencies, you can choose the version of Carbon you have before upgrading to Carbon 2 using composer show nesbot/carbon.

Then update your dependencies by running.

**Comment by L-Y** [comment]
My use lumen5.8 and My question is:
```php
  Problem 1
    - Installation request for tymon/jwt-auth ^0.5.12 -> satisfiable by tymon/jwt-auth[0.5.12].
    - Conclusion: remove nesbot/carbon 2.17.0
    - Conclusion: don't install nesbot/carbon 2.17.0
    - tymon/jwt-auth 0.5.12 requires nesbot/carbon ~1.0 -> satisfiable by nesbot/carbon[1.0.0, 1.0.1, 1.1.0, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.2.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.3.0, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0].
    - Can only install one of: nesbot/carbon[1.26.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.26.1, 2.17.0].
    - Can only install one of: nesbot/carbon[1.26.2, 2.17.0].
    - Can only install one of: nesbot/carbon[1.26.3, 2.17.0].
    - Can only install one of: nesbot/carbon[1.26.4, 2.17.0].
    - Can only install one of: nesbot/carbon[1.27.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.28.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.29.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.29.1, 2.17.0].
    - Can only install one of: nesbot/carbon[1.29.2, 2.17.0].
    - Can only install one of: nesbot/carbon[1.30.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.31.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.31.1, 2.17.0].
    - Can only install one of: nesbot/carbon[1.32.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.33.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.34.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.34.1, 2.17.0].
    - Can only install one of: nesbot/carbon[1.34.2, 2.17.0].
    - Can only install one of: nesbot/carbon[1.34.3, 2.17.0].
    - Can only install one of: nesbot/carbon[1.34.4, 2.17.0].
    - Can only install one of: nesbot/carbon[1.35.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.35.1, 2.17.0].
    - Can only install one of: nesbot/carbon[1.36.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.36.1, 2.17.0].
    - Can only install one of: nesbot/carbon[1.36.2, 2.17.0].
    - Can only install one of: nesbot/carbon[1.0.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.0.1, 2.17.0].
    - Can only install one of: nesbot/carbon[1.1.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.10.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.11.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.12.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.13.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.14.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.15.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.16.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.17.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.18.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.19.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.2.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.20.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.21.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.22.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.22.1, 2.17.0].
    - Can only install one of: nesbot/carbon[1.23.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.24.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.24.1, 2.17.0].
    - Can only install one of: nesbot/carbon[1.24.2, 2.17.0].
    - Can only install one of: nesbot/carbon[1.25.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.3.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.4.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.5.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.6.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.7.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.8.0, 2.17.0].
    - Can only install one of: nesbot/carbon[1.9.0, 2.17.0].
    - Installation request for nesbot/carbon (locked at 2.17.0) -> satisfiable by nesbot/carbon[2.17.0].

```
My set the Carbon version in my composer.json and Solved.
```php

{
    "require": {
         "nesbot/carbon": "2.17.0 as 1.34.0"
     }
}
```

**Comment by chojnicki** [comment]
Why this weird carbon workaround? It's not carbon fault...

Error is caused simply by old version of jwt-auth. "tymon/jwt-auth ^0.5.12"

Install latest with   composer require tymon/jwt-auth "^1.0"

It's shame that 1.0 after 3 years is still not released as stable. Because of this almost everyone that is starting with this package (including me) is installing wrong version, and big surprise why it is not working. To make it even worse, documentation for 1.0 still has command that is installing 0.5 version.

**Comment by tirthbodawala** [comment]
Totally agree with @chojnicki 
use the following instead:
```bash
composer require tymon/jwt-auth:^1.0
```

**Comment by spetrey** [comment]
I second your method @chojnicki. FWIW, some may need to adjust their `composer.json` file to permit dev non-stable releases:
```
...
"type": "project",
"minimum-stability": "dev",
"require": {
...
```

**Comment by hopeseekr** [comment]
I really regret adopting tymondesigns/jwt-auth for my startup project in early 2016, on the then-assurances that a stable 1.0 would be "right around the corner." Three years later, all I have to do is say, shame.

SHAME!!! You have 396 open issues. No version 1 in 3 years. People installing the wrong version by default. NO README with installation instructions to be found ANYWHERE on the master branch. The default GitHub page is the *unstable* 2.0 *develop* branch, which you seem to place most of your time and commits in...

Your frickin documentation on the Wiki is *STILL FOR v0.5!!* And you say after THREE YEARS:

> For version 0.5.* See the WIKI for documentation.
> Documentation for 1.0.0 is coming soon, but there is an unfinished guide here

This project is being maintained very very very poorly! Start a Patreon account. Open up to cyrpocurrency investments. Pledge to fix 1.0 until it's stable enough to release 1.0 and THEN AND ONLY THEN focus on 2.0.

This project is a case study of what NOT to do with an important one-man operation.

Oh and how about you add 3-5 people as full-fledged members able to merge pull requests, etc. so that this backlog can start going down?

**Comment by michael-basweti** [comment]
> Why this weird carbon workaround? It's not carbon fault...
> 
> Error is caused simply by old version of jwt-auth. "tymon/jwt-auth ^0.5.12"
> 
> Install latest with composer require tymon/jwt-auth "^1.0"
> 
> It's shame that 1.0 after 3 years is still not released as stable. Because of this almost everyone that is starting with this package (including me) is installing wrong version, and big surprise why it is not working. To make it even worse, documentation for 1.0 still has command that is installing 0.5 version.

Thanks man, this helped a lot.

**Comment by innerspirit** [comment]
> Totally agree with @chojnicki
> use the following instead:
> 
> ```shell
> composer require tymon/jwt-auth:^1.0
> ```

That didn't work for me, but this did: `composer require tymon/jwt-auth:1.0.0-rc.4.1`

**Comment by Thirdwrist** [comment]
> I really regret adopting tymondesigns/jwt-auth for my startup project in early 2016, on the then-assurances that a stable 1.0 would be "right around the corner." Three years later, all I have to do is say, shame.
> 
> SHAME!!! You have 396 open issues. No version 1 in 3 years. People installing the wrong version by default. NO README with installation instructions to be found ANYWHERE on the master branch. The default GitHub page is the _unstable_ 2.0 _develop_ branch, which you seem to place most of your time and commits in...
> 
> Your frickin documentation on the Wiki is _STILL FOR v0.5!!_ And you say after THREE YEARS:
> 
> > For version 0.5.* See the WIKI for documentation.
> > Documentation for 1.0.0 is coming soon, but there is an unfinished guide here
> 
> This project is being maintained very very very poorly! Start a Patreon account. Open up to cyrpocurrency investments. Pledge to fix 1.0 until it's stable enough to release 1.0 and THEN AND ONLY THEN focus on 2.0.
> 
> This project is a case study of what NOT to do with an important one-man operation.
> 
> Oh and how about you add 3-5 people as full-fledged members able to merge pull requests, etc. so that this backlog can start going down?

Why not fork and maintain the project, it's opensource you know.

**Comment by Dhayllin** [comment]
> > Totally agree with @chojnicki
> > use the following instead:
> > ```shell
> > composer require tymon/jwt-auth:^1.0
> > ```
> 
> That didn't work for me, but this did: `composer require tymon/jwt-auth:1.0.0-rc.4.1`

worked for version 5.8.x of laravel

**Comment by thebachtiarz** [comment]
> 
> 
> > Totally agree with @chojnicki
> > use the following instead:
> > ```shell
> > composer require tymon/jwt-auth:^1.0
> > ```
> 
> That didn't work for me, but this did: `composer require tymon/jwt-auth:1.0.0-rc.4.1`

nice this is work for me, im using v.5.8 'composer require tymon/jwt-auth:1.0.0-rc.4.1'

**Comment by connecteev** [comment]
> > I really regret adopting tymondesigns/jwt-auth for my startup project in early 2016, on the then-assurances that a stable 1.0 would be "right around the corner." Three years later, all I have to do is say, shame.
> > SHAME!!! You have 396 open issues. No version 1 in 3 years. People installing the wrong version by default. NO README with installation instructions to be found ANYWHERE on the master branch. The default GitHub page is the _unstable_ 2.0 _develop_ branch, which you seem to place most of your time and commits in...
> > Your frickin documentation on the Wiki is _STILL FOR v0.5!!_ And you say after THREE YEARS:
> > > For version 0.5.* See the WIKI for documentation.
> > > Documentation for 1.0.0 is coming soon, but there is an unfinished guide here
> > 
> > 
> > This project is being maintained very very very poorly! Start a Patreon account. Open up to cyrpocurrency investments. Pledge to fix 1.0 until it's stable enough to release 1.0 and THEN AND ONLY THEN focus on 2.0.
> > This project is a case study of what NOT to do with an important one-man operation.
> > Oh and how about you add 3-5 people as full-fledged members able to merge pull requests, etc. so that this backlog can start going down?
> 
> Why not fork and maintain the project, it's opensource you know.

defeats the purpose of the OSS community pulling together in one direction versus having 1000s of forks. there's enough complexity as-is and while @hopeseekr 's language is rather strong for software that is gratis, I tend to agree with him. There are better ways to manage this project than to let things just sit there and rot.

**Comment by damnguy** [comment]
> Totally agree with @chojnicki
> use the following instead:
> 
> ```shell
> composer require tymon/jwt-auth:^1.0
> ```

This worked for me too.

**Comment by aoeng** [comment]
so laravel 6.0 use
```
"6.0.1 as 5.8.2"
```
hah

**Comment by Messhias** [comment]
After 2 months looking in the core and etc I decide to move myself doing my own laravel JWT auth token, unfortunately I cannot and I'll not downgrade any version of I have in my project since everything is connect each other.

3 years for a stable version is too much, but I could understand you since it's an open-source project and you're doing that alone. 

I hope in future your project became bigger again, good luck for those whose try to use JWT.
