### ISSUE TITLE
Payload timestamps are strings - should be integers

### ISSUE THREAD

**Issue by dani3l** [tymondesigns/jwt-auth#180]
Hi guys
I'm using socket.io in my app and there's an npm package called socketio-jwt by auth0 to validate tokens for socket connections.

The package uses another package called jsonwebtoken and one of the checks is:
`if (typeof payload.exp !== 'number') { return done(new JsonWebTokenError('invalid exp value')); }`
(https://github.com/auth0/node-jsonwebtoken/blob/master/index.js#L169)

So I checked the payload output and it showed that exp, iat and other timestamps are translated as strings, so I had to remove that condition manually in order of it to work.

Hopefully you guys can solve the problem so I can use the original package again.

thanks!

**Comment by privatmamtora** [comment]
This was solved with 622f6c39cdcbba86bd4540aa611327ffe6357e3d, but currently on develop branch

**Comment by dani3l** [comment]
any chance you can merge this one to master for the time being?
