### ISSUE TITLE
Can we access to low-level JWT functions?

### ISSUE THREAD

**Issue by realtebo** [tymondesigns/jwt-auth#1806]
I use succesfully your package, so thanks a lot.

We'd like to be able to read payload from jwt sent in the body, or aside to the auth header.

Is there some way to do a simple thing like this?

    $payload = JwtAuth::payload($jwt_token_string);

and

    $signature_ok = JwtAuth::check_signature($jwt_token_string);

?

**Comment by imqishi** [comment]
I'm looking for the solution too, I want to use jwt-token string which generated from laravel-jwt to verify user not in laravel, I trace to src/Validators and find PayloadValidator.php, but I still don't get the way to use it...

**Comment by imqishi** [comment]
Finally I find the way!
```php
$ok = JWTAuth::setToken('your_string_token')->check(); // true or false
```

**Comment by realtebo** [comment]
Another way is to use the packages that are been used by this.

```
use Lcobucci\JWT\Parser;
use Lcobucci\JWT\Signer\Hmac\Sha256;

....

$token = (new Parser())->parse((string) $token_string
```
