### ISSUE TITLE
Refresh token should keep ttl

### ISSUE THREAD

**Issue by robin-dongbin** [tymondesigns/jwt-auth#1808]
### Subject of the issue
When use refresh, the new token should keep the ttl which I set first time.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.8
| Package version   | 1.0.0-rc4.1
| PHP version       | 7.2

### Steps to reproduce
```
// When user login,I need to setTTL for different client
1. $token = auth()->setTTL(7200)->attempt($credentials);
2. use `jwt.refresh` middleware

```

### Expected behaviour
When use refresh, the new token should keep the ttl which I set first time.

### Actual behaviour
ttl change to default value which in `jwt.php` config file.

**Comment by cosmini** [comment]
If you wish to override TTL defined in config, why don't you set TTL in your refresh method, same as when you do attempt?

For example in your case:
`
    $refreshedToken = auth()->setTTL(7200)->refresh());
`

**Comment by robin-dongbin** [comment]
I suggest do this in default refresh middleware
