### ISSUE TITLE
Exceptions can't be handled when using middleware

### ISSUE THREAD

**Issue by drawmyattention** [tymondesigns/jwt-auth#181]
I'm globally handling exceptions within my ```Handler.php``` file. However, as the ```GetUserFromToken.php``` file wraps the authentication attempt in a try / catch block, the Exceptions can't be handled by my own handler.

An alternative method is required to allow for our own exception handling.

**Comment by loginwashere** [comment]
You always have an option to extend GetUserFromToken and change handle logic as it suits your needs.

Also GetUserFromToken::handle directly and indirectly (via response method)  fires events and you can subscribe to them in for example EventServiceProvider and try to throw exception again to catch it in your Handler.php or call handler method in EventServiceProvider.

**Comment by tymondesigns** [comment]
I'm planning on adding some more generic middlewares in the next release. But the truth is, middleware is usually application specific and devs are bound to have differing requirements. If you need to catch any specific exceptions or handle something specific, then I would always advise that you write your own middleware for that. Not much to it really :smile:
