### ISSUE TITLE
Non-static method Tymon\JWTAuth\JWTAuth::attempt()

### ISSUE THREAD

**Issue by mouradsm** [tymondesigns/jwt-auth#182]
Non-static method exception on Laravel 5.1

Non-static method Tymon\JWTAuth\JWTAuth::attempt() should not be called statically, assuming $this from incompatible context

**Comment by mouradsm** [comment]
solved in https://github.com/tymondesigns/jwt-auth/issues/104 

Thanks!

**Comment by GlenHughes** [comment]
What was the solution to this? I'm getting the same error!

**Comment by acidjazz** [comment]
@GlenHughes are you using 
```php
use Tymon\JWTAuth\JWTAuth;
```
in your class? I believe this overrides the facade `JWTAuth` and does not allow static calls

**Comment by hyperflux** [comment]
Use this instead:

`use Tymon\JWTAuth\Facades\JWTAuth;`

**Comment by dunkel015** [comment]
Not found class with Illuminate\Support\Facades\Auth

**Comment by Jason-Nake** [comment]
please instead config\jwt..php : ` 'jwt' => 'Tymon\JWTAuth\Providers\JWT\NamshiAdapter',` as ` 'jwt' => Tymon\JWTAuth\Providers\JWT\Namshi::class`  , `'auth' => 'Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter'` as ` 'auth' => Tymon\JWTAuth\Providers\Auth\Illuminate::class` , `'storage' => 'Tymon\JWTAuth\Providers\Storage\IlluminateCacheAdapter'` as ` 'storage' => Tymon\JWTAuth\Providers\Storage\Illuminate::class`

**Comment by automatonatm** [comment]
*use Tymon\JWTAuth\Facades\JWTAuth;*

**Comment by kashtech79** [comment]
If I use "use Tymon\JWTAuth\Facades\JWTAuth; I get  "message": "Class 'Tymon\\JWTAuth\\facades\\JWTAuth' not found",
& in case of use Tymon\JWTAuth\JWTAuth; i get  Non-static method Tymon\\JWTAuth\\JWT::parseToken() should not be called statically"

**Comment by breezyx28** [comment]
`use Tymon\JWTAuth\Facades\JWTAuth as JWTAuth;`

try

`JWTAuth::attempt($credentials)` or any function comes with JWTAuth

this will remove the error
