### ISSUE TITLE
Middleware Api not working well

### ISSUE THREAD

**Issue by thewasta** [tymondesigns/jwt-auth#1820]
### My environment
| Q                 | A
| ----------------- | ---
| Framework         | Laravel 
| Framework version | 5.5.*
| Package version   | dev-develop
| PHP version       | 7.3.3

### Subject of the issue
I'm trying to protect access to routes with JWT, which means that users should add header with the auth provided by login with API (JWT Token).
#### First question:
My website has a login access for normal users (typing your email, and pass) who have access to website and then they can access to API with this information (Using POSTMAN, for example, to use post method) and they will get the Token generated. If I go to 'auth/login' (route) it works fine, but if I go to 'auth/logout' (route) it sends me message 'logout success' and then I try 'auth/me' with same token and it sends all information. Should not work, right? It shouldn't send me information because session is closed.

#### Second question:
In auth.php file how can I use two defaults guards?

```
 'defaults' => [
         'guard' => 'api',
         'passwords' => 'users',
     ]
```

If I change web to api, I can't login in website as normal, but I can access to API and viceversa.
#### Third question
How can I add middleware to routes with api?
```
Route::group(
    [
        'middleware' => 'api',
        'prefix' => 'auth'
    ],
    function($router)
    {
        Route::post('login', 'AuthController@login');
        Route::post('logout', 'AuthController@logout');
        Route::post('refresh', 'AuthController@refresh');
        Route::post('me', 'AuthController@me');
        Route::group(
            [
                'prefix' =>  'product',
            ],
            function()
            {
                Route::post('price/{id}', 'Resources\Entrypoint\Http\Laravel\Product\ProductGetController@getPrice');
                Route::post('price', 'Resources\Entrypoint\Http\Laravel\Product\ProductPostController@changePrice');
            }
        );
    }
);
```
This is my api.php controller, I previously deleted api file because when I started this I didn't expect to make an api ¿Should I work with the second controller file? (In routes, Im using two controllers the first one is the controller provided by JWT and the second is the controller created by me). In the Route Provider file and added this:
```
        Route::prefix('api')
            ->middleware('api')
            ->namespace($this->namespace)
            ->group(base_path('routes/resources.php'));
```
With his own function name and then added to map function.
API login has a controller, and the information which I want to make it accessible by API has other controller file (just saying). For now if I try to access to **auth/product/price/*Number***
It returns the data, and it shouldn't return, because the header is without the Token.

In the Kernel.php file I added
```
protected $middleware = [
   ...
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
    ];
```
Whitouth this lines, If I try to go to **/auth/product/price/1** it retruns 

> _Session store not set on request._

### Steps to reproduce
Install JWT and Laravel with my versions.
Table of users information name is: app_users and columns

> _id,active,password,first_name,last_name,email,last_login,remember_token,created_at,updated_at_

Remove api.php file and create a new one and add it to Route Providers file.

### Expected behaviour
Users with a account created in main website, can use his login information to get access to API. Users cannot register new account using with API.
API information returned, has differents routes.

### Actual behaviour
I can't login in the website but I can login with API.
Logout doesn't logout.
Middleware API doesn't works because it give me information without header.

#### Thanks in advance for your help

**Comment by zingimmick** [comment]
About second question: you can use `Auth::shouldUse($guard)` set the default guard, it will set the default guard to `api` by your way. 
About first and third questions: needs more info about class `AuthController`

**Comment by thewasta** [comment]
> About second question: you can use `Auth::shouldUse($guard)` set the default guard, it will set the default guard to `api` by your way.
> About first and third questions: needs more info about class `AuthController`

The AuthController was the same from the official website [jwt-auth](https://jwt-auth.readthedocs.io/en/develop/quick-start/)

**Comment by thewasta** [comment]
I already fixed the problem. It's pretty long text.
When I'm not busy I'll write the quote. Give me a minute.

**Comment by philbenoit-ibsa** [comment]
@thewasta In relation to your first question, about log out. 

Be sure to update your logout controller to invalidate the token. See here - https://jwt-auth.readthedocs.io/en/develop/auth-guard/#invalidate

As the JWT token is stored on the front end and no session is created the token will stay live for the duration set within the config/jwt.php file, the ttl value. 

If your happy that you have all the answers you should mark this closed.
