### ISSUE TITLE
How to handle exceptions in Dingo/Api?

### ISSUE THREAD

**Issue by keke122765** [tymondesigns/jwt-auth#1824]
The documentation about "Exception Handling" is unfinished.

app\Exception\Handler.php is invalid in Dingo/api.

**Comment by philbenoit-ibsa** [comment]
@keke122765 It looks like you might need to create a custom exception response. Have a look at this doc from the Dingo/Api docs - https://github.com/dingo/api/wiki/Errors-And-Error-Responses#custom-exception-responses

Then handle the exception thrown, you can find the list of exceptions from this package here. https://github.com/tymondesigns/jwt-auth/tree/develop/src/Exceptions

**Comment by keke122765** [comment]
@philbenoit-ibsa Thanks!
