### ISSUE TITLE
how to destroy jwt token,use JWTAuth::invalidate($token) not work

### ISSUE THREAD

**Issue by hhxiaohei** [tymondesigns/jwt-auth#1830]
### Subject of the issue
how to destroy jwt token,use JWTAuth::invalidate($token) not work

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 5.7
| Package version   | 1.0.0-rc.3
| PHP version       | 7.2.12

### Steps to reproduce
JWTAuth::invalidate function need the parameter is $forceForever not the token

```php
/**
     * Invalidate a token (add it to the blacklist).
     *
     * @param  bool  $forceForever
     *
     * @return $this
     */
    public function invalidate($forceForever = false)
    {
        $this->requireToken();

        $this->manager->invalidate($this->token, $forceForever);

        return $this;
    }
```

now,I have a old token need to destroy it when user login,so which function can I use? thx!

**Comment by philbenoit-ibsa** [comment]
@hhxiaohei Have a look at these docs. 

https://jwt-auth.readthedocs.io/en/develop/auth-guard/#invalidate

You don't pass the token, just the param for forceForever.

**Comment by ajcastro** [comment]
if ever you need to invalidate a different token, for example you are tracking a list of tokens in a database and you want to invalidate them.. 

```php
\JWTAuth::manager()->invalidate(new \Tymon\JWTAuth\Token($tokenString), $forceForever = false);
```

**Comment by jjba23** [comment]
Why didn’t you just mention that it is easier to invalidate with the auth helper, in the following way:
`auth()->invalidate(true)`
In my case my guard is called store_user so
`auth(“store_users”)->invalidate(true)`
The true will forever invalidate the token

**Comment by kovalenkos** [comment]
`
\JWTAuth::manager()->invalidate(new \Tymon\JWTAuth\Token($tokenString), $forceForever = false);
`
when using this design an error occurs

PHP error Non-static method Tymon\\JWTAuth\\JWT::manager() should not be called statically

**Comment by kunal4sd** [comment]
> 
> 
> Why didn’t you just mention that it is easier to invalidate with the auth helper, in the following way:
> `auth()->invalidate(true)`
> In my case my guard is called store_user so
> `auth(“store_users”)->invalidate(true)`
> The true will forever invalidate the token

@ajcastro is right with his solution, because auth()->invalidate($token) for few doesn't work.

**Comment by kunal4sd** [comment]
> 
> 
> if ever you need to invalidate a different token, for example you are tracking a list of tokens in a database and you want to invalidate them..
> 
> ```
> \JWTAuth::manager()->invalidate(new \Tymon\JWTAuth\Token($tokenString), $forceForever = false);
> ```

Thanks, it worked for me as compare to auth()->invalidate($token)

**Comment by hungvtitdng** [comment]
I can't destroy (revoke, expire) a token. I have tried with
all cases with `invalidate` but still not working. That destroys the current user.
Our case like that: revoke all tokens when a user has banned

Thanks

**Comment by vishnaidu** [comment]
> if ever you need to invalidate a different token, for example you are tracking a list of tokens in a database and you want to invalidate them..
> 
> ```
> \JWTAuth::manager()->invalidate(new \Tymon\JWTAuth\Token($tokenString), $forceForever = false);
> ```

This revokes the current logged in users' token. Does not revoke the token specified in the function. @tymondesigns I am implementing a functionality where a user can only be logged in one device and need to revoke other active tokens. Any ideas?

Thanks
