### ISSUE TITLE
Token has expired on `login` and `attempt`

### ISSUE THREAD

**Issue by khooz** [tymondesigns/jwt-auth#1835]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no / yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 5.8.26
| Package version   | 1.0.0-rc.4.1
| PHP version       | 7.2

### Steps to reproduce
DigitalOcean's vanilla LEMP, config to run Laravel, set Laravel to use Redis, use jwt package, wait for a day or two; then try any of bellow:

```
$token = auth()->attempt($credentials);
...
$token = auth()->login($user);
```

### Expected behaviour
`$token` should be set and ready to be sent.

### Actual behaviour
An exception is thrown:
```
Tymon/JWTAuth/Exceptions/TokenExpiredException with message 'Token has expired'
56
Tymon\JWTAuth\Claims\Expiration validatePayload
.../vendor/tymon/jwt-auth/src/Claims/Collection.php:62
55
 call_user_func_array
…/vendor/tymon/jwt-auth/src/Claims/Collection.php:62
54
ymon\JWTAuth\Claims\Collection Tymon\JWTAuth\Claims\{closure}
…/vendor/laravel/framework/src/Illuminate/Support/Collection.php:475
53
Illuminate\Support\Collection each
…/vendor/tymon/jwt-auth/src/Claims/Collection.php:64
52
Tymon\JWTAuth\Claims\Collection validate
…/vendor/tymon/jwt-auth/src/Validators/PayloadValidator.php:83
51
Tymon\JWTAuth\Validators\PayloadValidator validatePayload
…/vendor/tymon/jwt-auth/src/Validators/PayloadValidator.php:51
50
Tymon\JWTAuth\Validators\PayloadValidator check
…/vendor/tymon/jwt-auth/src/Payload.php:46
49
Tymon\JWTAuth\Payload __construct
…/vendor/tymon/jwt-auth/src/Factory.php:185
48
Tymon\JWTAuth\Factory withClaims
…/vendor/tymon/jwt-auth/src/Factory.php:87
47
Tymon\JWTAuth\Factory make
…/vendor/tymon/jwt-auth/src/JWT.php:234
46
Tymon\JWTAuth\JWT makePayload
…/vendor/tymon/jwt-auth/src/JWT.php:76
45
Tymon\JWTAuth\JWT fromSubject
…/vendor/tymon/jwt-auth/src/JWT.php:90
44
Tymon\JWTAuth\JWT fromUser
…/vendor/tymon/jwt-auth/src/JWTGuard.php:142
43
Tymon\JWTAuth\JWTGuard login
…/vendor/tymon/jwt-auth/src/JWTGuard.php:127
42
Tymon\JWTAuth\JWTGuard attempt
…/app/Http/Controllers/API/v0_0/Auth/LoginController.php:228
41
App\Http\Controllers\API\v0_0\Auth\LoginController login
…/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
```
`41` is where I call the `auth()->login($credentials)` where `$credentials = $request->only(['username', 'password']);`

---
I have checked all the times on all services: MySQL, PHP-FPM and system all share the same time tick and timezone. Also, notably, the code works fine in Windows WAMP stack. I tried to trace back the problem, but as far as I go, I can't reach. I'm out of ideas.

PS: Obviously the routes for login don't incorporate `auth:api` and use `guest` middleware.

**Comment by khooz** [comment]
My bad! I feel stupid.

I have changed the TTLs, setting `JWT_TTL` and `JWT_REFRESH_TTL` in the `.env` file; when changing back to the default config, instead of removing the key-value pairs from `.env` file, I just removed the values only. That being said, the value for both TTLs were set to `''` (an empty string which is `0` when interpreted as `int` in PHP). Though, I suggest an exception other than the token expiry, something like Invalid Value of some sort; or falling back to defaults, or far better, do not parse the request upon token creation and make invalid token generation possible (I haven't found the use-case yet, but it's good to know it's not barred)

Thanks for the awesome work btw!

**Comment by khongluadao** [comment]
> My bad! I feel stupid.
> 
> I have changed the TTLs, setting `JWT_TTL` and `JWT_REFRESH_TTL` in the `.env` file; when changing back to the default config, instead of removing the key-value pairs from `.env` file, I just removed the values only. That being said, the value for both TTLs were set to `''` (an empty string which is `0` when interpreted as `int` in PHP). Though, I suggest an exception other than the token expiry, something like Invalid Value of some sort; or falling back to defaults, or far better, do not parse the request upon token creation and make invalid token generation possible (I haven't found the use-case yet, but it's good to know it's not barred)
> 
> Thanks for the awesome work btw!

Thanks you, me too, my system have problem occurred after running for a while, even though no adjustments were made.
