### ISSUE TITLE
Add "no" as an option to secret generate command if it already exists

### ISSUE THREAD

**Issue by orkhanahmadov** [tymondesigns/jwt-auth#1840]
In our application we recently switched to JWT token authentication and we are deploying application to multiple environments. To prevent running command in multiple environments manually we want to add `php artisan jwt:secret` to our deployment pipeline so that secret generated automatically if it's not available in that environment.

But right now if the secret is already exists in .env it asks to input what to do. Maybe we can pass an option like `--n` to ignore generating secret if it already exists.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 5.8
| Package version   | 1.0.0-rc.4.1
| PHP version       | 7.3

**Comment by mfn** [comment]
> `--n`

I suggest something more descriptive like `--always-no`.

Btw, can you work it around by echoing `n` into the command?

**Comment by orkhanahmadov** [comment]
> > `--n`
> 
> I suggest something more descriptive like `--always-no`.
> 
> Btw, can you work it around by echoing `n` into the command?

@mfn

I created PR with "always-no" option
