### ISSUE TITLE
Getting user info along with Token right away 

### ISSUE THREAD

**Issue by mrgodhani** [tymondesigns/jwt-auth#185]
HI,

How do we get user info along with token when user signs into the application without doing any additional request to api ?

Currently we are using React and Flux with Laravel along with this jwt package.

In below code I will get user id and token. But in order not to do another request can we add user info in same token on login?

```
public function authenticate(Request $request)
    {
        $credentials = $request->only('email','password');
        if(!$token = JWTAuth::attempt($credentials))
        {
            return $this->response->errorUnauthorized("Email or password is invalid");
        }
        return (new Response(compact('token','data'), 200))
            ->header('Content-Type', 'application/json');
    }
```

**Comment by tymondesigns** [comment]
You can add custom claims to your token of course.. but I wouldn't advise that if you require lots of detail about the user.

Caching the user info on the client (e.g localStorage) is another option
