### ISSUE TITLE
Missing function logoutOtherDevices

### ISSUE THREAD

**Issue by reishou** [tymondesigns/jwt-auth#1850]
### Subject of the issue
Missing function logoutOtherDevices

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | yes
| Framework         | Laravel / Lumen
| Framework version | 5.x.y
| Package version   | 1.x.y
| PHP version       | 7.2

```
public function logout()
{
    Auth::logout();
    Auth::logoutOtherDevices('1234');

    return $this->success(true);
}
```

### Expected behaviour
I want logout (invalidate) all old token.

### Actual behaviour
Method [logoutOtherDevices] does not exist. in vendor/tymon/jwt-auth/src/JWTGuard.php:445

**Comment by ash-jc-allen** [comment]
Hi, I might be wrong. But if I remember rightly JSON web tokens are stateless and by default aren't stored in the database. The default Laravel behaviour for this in the 'web' sessions is done by changing a cookie.

You could add this functionality yourself temporarily by storing the tokens in the database. You could then write a middleware to check if the token exists in the database on each request. If a user was to logoutOtherDevices you could delete all their tokens from the database. So the middleware would deny access on the users next requests. Hopefully this makes sense and helps a bit?

**Comment by allaghi** [comment]
I am facing same problems @reishou

**Comment by RaedElNABOULSI** [comment]
Hello, I am facing the same error when adding logout other devices method:
`Auth::logoutOtherDevices();`

Error: Method [logoutOtherDevices] does not exist. in vendor/tymon/jwt-auth/src/JWTGuard.php:445

Any suggestions?

**Comment by reishou** [comment]
You should use another packages: laravel-sanctum or laravel-passport
