### ISSUE TITLE
 Invalid value provided for claim [iat]

### ISSUE THREAD

**Issue by xAqweRx** [tymondesigns/jwt-auth#1851]
### Subject of the issue
I'm facing problem with IAT parameter on different servers. there is no possible way to understand Why this happens. Adding this info. May be someone will help me.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no 
| Framework         |  Lumen
| Framework version | 5.7.8
| Package version   | 1.0.0-rc.4.1
| PHP version       | 7.2.14

### Steps to reproduce
periodical bug. Can't tell steps to reproduce ( for now ).

### Expected behaviour
new token is generated 

### Actual behaviour
```Tymon\JWTAuth\Exceptions\InvalidClaimException: Invalid value provided for claim [iat] in /var/www/collectors-api/vendor/tymon/jwt-auth/src/Claims/IssuedAt.php:37
Stack trace:
#0 /var/www/collectors-api/vendor/tymon/jwt-auth/src/Claims/Claim.php(56): Tymon\JWTAuth\Claims\IssuedAt->validateCreate(1564121609)
#1 /var/www/collectors-api/vendor/tymon/jwt-auth/src/Claims/DatetimeTrait.php(47): Tymon\JWTAuth\Claims\Claim->setValue(1564121609)
#2 /var/www/collectors-api/vendor/tymon/jwt-auth/src/Claims/Claim.php(42): Tymon\JWTAuth\Claims\IssuedAt->setValue(1564121609)
#3 /var/www/collectors-api/vendor/tymon/jwt-auth/src/Claims/Factory.php(79): Tymon\JWTAuth\Claims\Claim->__construct(1564121609)
#4 /var/www/collectors-api/vendor/tymon/jwt-auth/src/Claims/Factory.php(110): Tymon\JWTAuth\Claims\Factory->get('iat', 1564121609)
#5 /var/www/collectors-api/vendor/tymon/jwt-auth/src/Factory.php(147): Tymon\JWTAuth\Claims\Factory->make('iat')
#6 /var/www/collectors-api/vendor/tymon/jwt-auth/src/Factory.php(173): Tymon\JWTAuth\Factory->buildClaims()
#7 /var/www/collectors-api/vendor/tymon/jwt-auth/src/Factory.php(87): Tymon\JWTAuth\Factory->buildClaimsCollection()
#8 /var/www/collectors-api/vendor/tymon/jwt-auth/src/Manager.php(106): Tymon\JWTAuth\Factory->make()
#9 /var/www/collectors-api/vendor/tymon/jwt-auth/src/JWT.php(200): Tymon\JWTAuth\Manager->decode(Object(Tymon\JWTAuth\Token))
#10 /var/www/collectors-api/vendor/tymon/jwt-auth/src/JWT.php(210): Tymon\JWTAuth\JWT->getPayload()
#11 /var/www/collectors-api/vendor/tymon/jwt-auth/src/JWT.php(288): Tymon\JWTAuth\JWT->payload()
#12 /var/www/collectors-api/vendor/tymon/jwt-auth/src/JWTGuard.php(406): Tymon\JWTAuth\JWT->checkSubjectModel('App\\Models\\User...')
#13 /var/www/collectors-api/vendor/tymon/jwt-auth/src/JWTGuard.php(80): Tymon\JWTAuth\JWTGuard->validateSubject()
#14 /var/www/collectors-api/vendor/illuminate/auth/GuardHelpers.php(60): Tymon\JWTAuth\JWTGuard->user()
#15 /var/www/collectors-api/vendor/illuminate/auth/GuardHelpers.php(70): Tymon\JWTAuth\JWTGuard->check()
#16 /var/www/collectors-api/app/Http/Middleware/Authenticate.php(52): Tymon\JWTAuth\JWTGuard->guest()
#17 /var/www/collectors-api/vendor/illuminate/pipeline/Pipeline.php(163): App\Http\Middleware\Authenticate->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#19 /var/www/collectors-api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\Lumen\Http\Request))
#20 /var/www/collectors-api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#21 /var/www/collectors-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(415): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/collectors-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(261): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#23 /var/www/collectors-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(165): Laravel\Lumen\Application->handleFoundRoute(Array)
#24 /var/www/collectors-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(418): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Laravel\Lumen\Http\Request))
#25 /var/www/collectors-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(171): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#26 /var/www/collectors-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(108): Laravel\Lumen\Application->dispatch(NULL)
#27 /var/www/collectors-api/public/index.php(28): Laravel\Lumen\Application->run()
#28 {main}```

**Comment by xAqweRx** [comment]
As additional info. Server and client are in different time zones ( 5 hours differences )

**Comment by harrysbaraini** [comment]
What is the error exactly? Post the exception too.

**Comment by xAqweRx** [comment]
Tymon\JWTAuth\Exceptions\InvalidClaimException: Invalid value provided for claim [iat] in /var/www/html/rest/vendor/tymon/jwt-auth/src/Claims/IssuedAt.php:37

**Comment by harrysbaraini** [comment]
Did you add any custom claim?

I'd recommend you to create a new Laravel project, install JWT and try it without any further modification on your code.

**Comment by xAqweRx** [comment]
No. No custom claim

**Comment by f3cp** [comment]
I been getting the same exception occasionally also.

`Tymon\JWTAuth\Exceptions\InvalidClaimException: Invalid value provided for claim [iat] in /var/www/html/rest/vendor/tymon/jwt-auth/src/Claims/IssuedAt.php:37`

I have observed a few things which may be relevant to this issue.

It's the 'isFuture' check in the 'validateCreate' method of the 'IssuedAt' claim which is causing the exception.

I notice that this "isFuture" check does not use the config 'leeway' value, and will only use the default of 0. For other methods in the claim (e.g. validatePayload) the leeway is loaded from the config value.

In my circumstance somehow IAT values are occasionally generated with values that are slightly in the future, despite the token being generated and used on the same  server (I am running acceptance test that generate and then use the tokens immediately) - This is causing the exception to be triggered. I'm not sure why this is happening - but it would be useful if the leeway could be applied here as it would mitigate this.

I added some logging to the 'validateCreate' method before the exception to see the timestamps for 'now' vs my IAT value and this is an example of the values when the error occurred.
NOW value: 1566808104759
IAT Value: 1566808106000 (Stored as 1566808106 within the token)

My best guess for how an IAT could be generated that is presumed to be in the future when checked immediately after on the same server is that there could be some issue with the rounding when setting or comparing the IAT at the MS level - although I have not traced this to be the cause yet.
The only real lead I have here is that maybe it could be related to this PHP 7.1 bug (as I am running 7.1.27), but it could easily be unrelated:
https://bugs.php.net/bug.php?id=74753

It sounds like this user's issue could also be the same as what I am seeing here:
https://github.com/tymondesigns/jwt-auth/issues/887#issuecomment-524572756

**Comment by xAqweRx** [comment]
@f3cp Thank you for your comment. I've made couple of tests. And yes. This situation is connected with PHP version that I have on server side.
Here I'm posting `time()` and `Carbon` behaviour 
```
int(1) int(1566892231) int(1566892230)
int(1) int(1566892232) int(1566892231)
int(1) int(1566892233) int(1566892232)
int(1) int(1566892234) int(1566892233)
int(1) int(1566892235) int(1566892234)
int(-1) int(1566892234) int(1566892235)
int(1) int(1566892235) int(1566892234)
int(1) int(1566892236) int(1566892235)
int(1) int(1566892237) int(1566892236)
int(1) int(1566892238) int(1566892237)
int(1) int(1566892239) int(1566892238)
int(1) int(1566892240) int(1566892239)
int(-1) int(1566892239) int(1566892240)
int(1) int(1566892240) int(1566892239)
```
this is `PHP 7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0 (cli) (built: Feb  9 2019 06:51:24) ( NTS )`

**Comment by xAqweRx** [comment]
Same problem after PHP update to version ` 7.2.21-1` So this is server problem

**Comment by xAqweRx** [comment]
Problem was connected with debian time synchronisation process.

**Comment by f3cp** [comment]
Thanks @xAqweRx  - I believe my problem is also due to time synchronisation on the host machine. I think this only became a problem since upgrading to carbon 2 which introduced microsecond precession.
It would be ideal if 'leeway' was actually applied as part of the IAT validateCreate isFuture check, but I understand that few people would be using tokens so rapidly after creation that they would be coming up against this issue, as is happening in my use case.

**Comment by xAqweRx** [comment]
Currently I have Carbon 1 and this is not connected with Carbon at all.
Because I've tested native time() php method and this problem present there

**Comment by Lapinskas** [comment]
> Problem was connected with debian time synchronisation process.

Hi @xAqweRx ,

Could you please post details how have you resolved the issue? 
I've faced the same issue with Laravel Nova and single sign-on, where auth token issued and instantly checked after the redirect.

**Comment by xAqweRx** [comment]
My issue was connected with server settings of time synchronization. So, token was generated in one moment and after time sync - this was "in future". So, first of all - check how you're `time()` working and what data is shown. After this - you can do your conclusion

**Comment by richardudovich** [comment]
we should be able to use leeway to address time inconsistencies, however i am seeing that at the time IssuedAt is checked leeway does not appear to be in the config

**Comment by xAqweRx** [comment]
This is not quite good way, cause it's the same server and on the same server while sync time "moves" in "wrong" way

**Comment by richardudovich** [comment]
Ok, I understand your case, in my case there are multiple servers behind the load balancer, and it seems some are 1 or 2 seconds ahead or behind. The problem is in `IssuedAt` 
It validates the value on creation, as a result of custom `validateCreate` call, this happens before the leeway is set.
So in theory it's a bug in the sense 
```
    /*
    |--------------------------------------------------------------------------
    | Leeway
    |--------------------------------------------------------------------------
    |
    | This property gives the jwt timestamp claims some "leeway".
    | Meaning that if you have any unavoidable slight clock skew on
    | any of your servers then this will afford you some level of cushioning.
    |
    | This applies to the claims `iat`, `nbf` and `exp`.
    |
    | Specify in seconds - only if you know you need it.
    |
    */
```
is actually not true in the case off `iat`

**Comment by xAqweRx** [comment]
I think this is not quite wright. So probably you should to provide more
info about you situation and where exactly you thin you have a bug.
Probably create new ticket

**Comment by jd-patel** [comment]
syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST)

/vendor/tymon/jwt-auth/src/Claims/Claim.php26

php -v : PHP 7.4.10

Please give me solution for this.
