### ISSUE TITLE
Trying to install v1.0

### ISSUE THREAD

**Issue by dhcmega** [tymondesigns/jwt-auth#1852]
I have one project that is working ok with this in it's composer.json:
```
        "tymon/jwt-auth": "^1.0",
```

On another project I cannot install it:
```
$ composer require tymon/jwt-auth:"^1.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tymon/jwt-auth ^1.0 is satisfiable by tymon/jwt-auth[1.0.0-alpha.2, 1.0.0-alpha.3, 1.0.0-alpha1, 1.0.0-beta.1, 1.0.0-beta.2, 1.0.0-beta.3, 1.0.0-rc.1, 1.0.0-rc.2, 1.0.0-rc.3, 1.0.0-rc.4, 1.0.0-rc.4.1, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
```
If I don't include version, it tries to install v0.5

How can I install v1.0?
Thanks!

**Comment by mfn** [comment]
Try an explicit version: `require tymon/jwt-auth:1.0.0-rc.4.1`

**Comment by dhcmega** [comment]
It worked, thanks.
But will it update to the stable release? or I have to specify always version?

**Comment by mfn** [comment]
With that explicit version you will not receive any update.

Not sure how to do it correctly, sorry; not an composer expert.

OTOH you can subscribe to github notifications only for releases:
![image](https://user-images.githubusercontent.com/87493/61994489-2cc3b480-b07b-11e9-93b8-e50b5f465b97.png)

**Comment by dhcmega** [comment]
Ok, will do. Thank you for your help.
