### ISSUE TITLE
JWT Auth doesn't have Laravel 6 Compatibility 

### ISSUE THREAD

**Issue by kennethtomagan** [tymondesigns/jwt-auth#1869]
I install a fresh Laravel 6 project. but when I install tymondesigns/jwt-auth package
`composer require tymon/jwt-auth`
or 
`composer require tymon/jwt-auth:dev-develop`

but it shows an error
```
Problem 1
    - Installation request for tymon/jwt-auth dev-develop -> satisfiable by tymon/jwt-auth[dev-develop].
    - Conclusion: remove laravel/framework v6.0.0
    - Conclusion: don't install laravel/framework v6.0.0
    - tymon/jwt-auth dev-develop requires illuminate/http ^5.1 -> satisfiable by illuminate/http[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18,5.7.19, 5.7.x-dev, 5.8.x-dev, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11,v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2,v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - don't install illuminate/http 5.1.x-dev|don't install laravel/framework v6.0.0
    - don't install illuminate/http 5.2.x-dev|don't install laravel/framework v6.0.0
    - don't install illuminate/http 5.3.x-dev|don't install laravel/framework v6.0.0
    - don't install illuminate/http 5.4.x-dev|don't install laravel/framework v6.0.0
    - don't install illuminate/http 5.5.x-dev|don't install laravel/framework v6.0.0
    - don't install illuminate/http 5.6.x-dev|don't install laravel/framework v6.0.0
    - don't install illuminate/http 5.7.17|don't install laravel/framework v6.0.0
    - don't install illuminate/http 5.7.18|don't install laravel/framework v6.0.0
    - don't install illuminate/http 5.7.19|don't install laravel/framework v6.0.0
    ........................
```

how to resolve this?

**Comment by realprabs** [comment]
There is no working solution. Discussion is happening at https://github.com/tymondesigns/jwt-auth/issues/1860

**Comment by TNChalise** [comment]
@tymondesigns Every one is eager to use with laravel 6, multiple issues has been created. Can you reference accordingly and close ?

**Comment by tymondesigns** [comment]
See https://github.com/tymondesigns/jwt-auth/issues/1860#issuecomment-529290860

**Comment by munnaweber** [comment]
Hey guys, use this. Its working
composer require tymon/jwt-auth ^1.0.0

**Comment by DesKevinMendez** [comment]
> Hey guys, use this. Its working
> composer require tymon/jwt-auth ^1.0.0

Since when? I actuality using that version, but, not working :c I cannot update jwt whit that version

**Comment by munnaweber** [comment]
> > Hey guys, use this. Its working
> > composer require tymon/jwt-auth ^1.0.0
> 
> Since when? I actuality using that version, but, not working :c I cannot update jwt whit that version

 composer require tymon/jwt-auth "^1.0.0"
#DesKevinMendez  just use "^1.0.0" instead of ^1.0.0
I'm sure it will be working because i'checked it now and its working. Thank you

**Comment by chitanok** [comment]
#MunnaAhmed is right. it's working for me also

**Comment by Kwenziwa** [comment]
> composer require tymon/jwt-auth ^1.0.0

This one worked for me :)

**Comment by SaberMuthanna** [comment]
Hey guys,  If you are using Laravel version 5.5 or above, run the following command to require a dev-develop version of jwt package.
composer require tymon/jwt-auth:dev-develop --prefer-source

**Comment by alsmani-developer** [comment]
you must update your composer first 
run this command : composer update
and then run :composer require tymon/jwt-auth
I think that will work

**Comment by maverick504** [comment]
> Hey guys, use this. Its working
> composer require tymon/jwt-auth ^1.0.0

Yeah, it works for me too! Thank you! ( ^^)b

**Comment by lxandrexl** [comment]
> Hey guys, use this. Its working
> composer require tymon/jwt-auth ^1.0.0

Thanks it works

**Comment by andrefigueira93** [comment]
> > > Hey guys, use this. Its working
> > > composer require tymon/jwt-auth ^1.0.0
> > 
> > 
> > Since when? I actuality using that version, but, not working :c I cannot update jwt whit that version
> 
> `composer require tymon/jwt-auth "^1.0.0"` **<--- This one here solved the problem!!**
> #DesKevinMendez just use "^1.0.0" instead of ^1.0.0
> I'm sure it will be working because i'checked it now and its working. Thank you

Thank you!

**Comment by bsam2019** [comment]
> > > > Hey guys, use this. Its working
> > > > composer require tymon/jwt-auth ^1.0.0
> > > 
> > > 
> > > Since when? I actuality using that version, but, not working :c I cannot update jwt whit that version
> > 
> > 
> > `composer require tymon/jwt-auth "^1.0.0"` **<--- This one here solved the problem!!**
> > #DesKevinMendez just use "^1.0.0" instead of ^1.0.0
> > I'm sure it will be working because i'checked it now and its working. Thank you
> 
> Thank you!
composer require tymon/jwt-auth "^1.0.0" has worked for me,

**Comment by BelTeamProjects** [comment]
The new version JWT package was tagged for laravel 6!
Guys, use this. Its working:

composer require tymon/jwt-auth:1.0.0-rc.5

**Comment by modavidc** [comment]
> Hey guys, use this. Its working
> composer require tymon/jwt-auth ^1.0.0

It's working for me. Thanks!

**Comment by pergsify** [comment]
> The new version JWT package was tagged for laravel 6!
> Guys, use this. Its working:
> 
> composer require tymon/jwt-auth:1.0.0-rc.5

With Laravel 6.5.1, this is working. Thanks.

**Comment by mhabib555** [comment]
composer require tymon/jwt-auth "^1.0.0"
is working with laravel 6.5.2

**Comment by prosatya** [comment]
> > > Hey guys, use this. Its working
> > > composer require tymon/jwt-auth ^1.0.0
> > 
> > 
> > Since when? I actuality using that version, but, not working :c I cannot update jwt whit that version
> 
> composer require tymon/jwt-auth "^1.0.0"
> #DesKevinMendez just use "^1.0.0" instead of ^1.0.0
> I'm sure it will be working because i'checked it now and its working. Thank you

Yes , It's working for me Also. thank you so much!!!

**Comment by yusrilfadillah** [comment]
> The new version JWT package was tagged for laravel 6!
> Guys, use this. Its working:
> 
> composer require tymon/jwt-auth:1.0.0-rc.5

Thank you, it's working for me

**Comment by ervan23** [comment]
> > > Hey guys, use this. Its working
> > > composer require tymon/jwt-auth ^1.0.0
> > 
> > 
> > Since when? I actuality using that version, but, not working :c I cannot update jwt whit that version
> 
> composer require tymon/jwt-auth "^1.0.0"
> #DesKevinMendez just use "^1.0.0" instead of ^1.0.0
> I'm sure it will be working because i'checked it now and its working. Thank you

Working like a charm. thx

**Comment by boussara** [comment]
Thank you, it's working for me

**Comment by dipenparmar12** [comment]
composer require tymon/jwt-auth ^1.0.0

Above command perfectly working fine in laravel 6.5 
but it not work in verion laravel 5.2 or more

**Comment by Ahmed-Aboud** [comment]
for newer versions
 https://github.com/tymondesigns/jwt-auth/releases

**Comment by oviniciusfeitosa** [comment]
The command below works for me using Laravel version 8:

```sh
composer require tymon/jwt-auth:^1.0.2
```

Reference [here](https://vinnyfs89.gitbook.io/knowledge/technology/programming-or-scripts-languages/php/laravel/known-issues-1#tymon-jwt-auth-0-5-12-requires-illuminate-support-5-0-greater-than-found-illuminate-support-v-5-0-0-5-8-x-dev-but-it-conflicts-with-your-root-composer-json-require-8-18)

Hope it helps! 👍

**Comment by mod7ex** [comment]
same problem in laravel 8 but `composer require tymon/jwt-auth ^1.0.0` worked fine

**Comment by MoatazAbdAlmageed** [comment]
laravel v6 

./composer.json has been updated
Running composer update tymon/jwt-auth --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework 6.0.*, found laravel/framework[v6.0.0, ..., v6.0.4] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
