### ISSUE TITLE
Unable to parse token in post calls

### ISSUE THREAD

**Issue by selvin007** [tymondesigns/jwt-auth#187]
whenever token is part of post parameters and not specified in url or header it is unable to parse token from request

/tymon/jwt-auth/src/JWTAuth.php

it works if we change 

 public function parseToken($method = 'bearer', $header = 'authorization', $query = 'token')
    {
        if (! $token = $this->parseAuthHeader($header, $method)) {
            if (! $token = $this->request->query($query, false)) {
                throw new JWTException('The token could not be parsed from the request', 400);
            }
        }

        return $this->setToken($token);
    }

to

public function parseToken($method = 'bearer', $header = 'authorization', $query = 'token')
    {
        if (! $token = $this->parseAuthHeader($header, $method)) {
            if (! $token = $this->request->input($query, false)) {
                throw new JWTException('The token could not be parsed from the request', 400);
            }
        }

        return $this->setToken($token);
    }

any specify reason to use $this->request->query instead of $this->request->input

**Comment by tymondesigns** [comment]
No reason :smile: , in-fact I will probably change it to `request->input`

Thanks!

**Comment by danieldeppe** [comment]
Hey, is there yet a version available with working post parameter token?
