### ISSUE TITLE
Support Laravel 6.0

### ISSUE THREAD

**Issue by felipesmendes** [tymondesigns/jwt-auth#1873]
### Subject of the issue
I cant use jwt-auth in laravel 6.0 because it not has support.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no 
| New Feature?      | no
| Framework         | Laravel
| Framework version | 6.0
| Package version   | 1.0.0-rc.4.1
| PHP version       | 7.2^

### Steps to reproduce
Update laravel/framework to 6.0
composer update.

### Expected behaviour
Upgrading to 6.0

### Actual behaviour
I can't upgrade to Laravel 6.0

**Comment by tymondesigns** [comment]
I have just tagged a new version

**Comment by dillingham** [comment]
@tymondesigns when are you tagging a 1.0 / stable release?

Kind of not great when you have to dig through issues to know how to install.
