### ISSUE TITLE
redis cache always use database 1

### ISSUE THREAD

**Issue by sollyu** [tymondesigns/jwt-auth#1877]
### Subject of the issue
我的`.env`配置`CACHE_DRIVER=redis`和`REDIS_DB=3`，但是jwt-auth的缓存仍旧使用`DB1`
my `.env` config `CACHE_DRIVER=redis` and `REDIS_DB=3`, but jwt-auth still use redis database `1`
```
CACHE_DRIVER=redis
SESSION_DRIVER=redis

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
REDIS_DB=3
```

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | may be
| New Feature?      | no
| Framework         | Laravel
| Framework version | 6.0.3
| Package version   | 1.0.0-rc.5
| PHP version       | 7.3.2

### Steps to reproduce
创建一个laravel工程，使用jwt-auth作为api认证，修改缓存为redis并修改`REDIS_DB=3`
create an laravel project, use jwt-auth by api, change `CACHE_DRIVER=redis` and `REDIS_DB=3`

### Expected behaviour
jwt-auth应该使用redis的3号数据库，不是1号数据库。
jwt-auth cache shoud use redis_db `3`, not `1`.

### Actual behaviour
jwt-auth 使用了redis的1号数据库
jwt-auth use redis db 1.

**Comment by lkloon123** [comment]
this package use cache db, not default db.
u should set `REDIS_CACHE_DB=3` instead of `REDIS_DB = 3`

**Comment by sollyu** [comment]
非常感谢，问题解决了。
Thank you very much. The problem has been solved.
