### ISSUE TITLE
Get authenticated user

### ISSUE THREAD

**Issue by neeilya** [tymondesigns/jwt-auth#188]
Hi, this package is great, thank you!

Could you implement functionality similar to Laravel built in `Auth::user()`?

Right now I have to retrieve user by chain of methods  
```
function user()
{
	return JWTAuth::toUser(JWTAuth::getToken());
}
```

And each time I retrieve a user variable it makes request to database.
Could you make it cache or something.

And if you will do this, please keep in mind that it is convenient to have power to change user retrieving query (e.g. retrieve some additional info from other tables using join)

P.s. I use Laravel 5.1.*

**Comment by dani3l** [comment]
If you use `GetUserFromToken` middleware you can use Auth::user()

**Comment by tymondesigns** [comment]
@dani3l is correct.

Also note that in the next version (0.6) it will be advisable to use `JWTAuth::user();` since that wraps the authentication provider

**Comment by webkenny** [comment]
FWIW, this doesn't seem to work in my install. I use the middleware but calls to `Auth::user()` return null. The only exception here is I am doing this in a controller class that is a parent of other controllers to house common methods and properties.
