### ISSUE TITLE
Lcobucci\JWT\Signer\Hmac::doVerify() .I am working in Laragon. with apache server and done php artisan jwt: secret and php artisan config: cache and no and opted solution

### ISSUE THREAD

**Issue by dt-jegomez** [tymondesigns/jwt-auth#1883]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no / yes
| New Feature?      | no / yes
| Framework         | Laravel / Lumen
| Framework version | 5.x.y
| Package version   | 1.x.y
| PHP version       | 5.x.y / 7.x.y

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by chrisbbreuer** [comment]
Please provide some more info

**Comment by dt-jegomez** [comment]
a continuación describo el mensaje de error residido  por console:

**Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key, null given, called in C:\laragon,**

cabe destacar que estoy usando Laragon servidor apache 2.4,
laravel/framework": "5.8.*,
tymon/jwt-auth": "^1.0.0-rc.4.1,
ademas el error es aleatorio.

**Comment by chrisbbreuer** [comment]
I don't really understand, but did you run `php artisan jwt:secret`?

**Comment by dt-jegomez** [comment]
yes. also run php artisan config: clear. and the problem still persists

**Comment by chrisbbreuer** [comment]
`php artisan config: clear` should be 
`php artisan config:clear`

You seem to keep including a whitespace. Not sure if you have noticed that?

**Comment by dt-jegomez** [comment]
Actually, I do not know. but I just performed the operation and I still choose the error.
"Argument 3 passed to Lcobucci \ JWT \ Signer \ Hmac :: doVerify ()"

**Comment by chrisbbreuer** [comment]
what does your `.env`-file say for the variable `JWT_SECRET=`?

**Comment by dt-jegomez** [comment]
JWT_TTL=1440
JWT_SECRET=r3T0nRHJM8j28r3nxPm76O4FS9MQ3Ri4y79vuedvay9fzPv9RQdVqgjZlQ9ZTkck

**Comment by chrisbbreuer** [comment]
That looks good.

How can I reproduce this issue you are having? Your description is not enough to figure this one out. In fact, there is no description at all besides the title 😃

**Comment by dt-jegomez** [comment]
okay. I'm using windows 10, and laragon, apache httpd-2.4.35-win64-VC15,
laravel / framework ":" 5.8. *,
tymon / jwt-auth ":" ^ 1.0.0-rc.4.1.

post: in linux I do not present the same error with the same repository.

**Comment by chrisbbreuer** [comment]
Still not enough. How can I reproduce it? Provide some minimal example please

**Comment by dt-jegomez** [comment]
In performing the following procedure and opting for a successful result.

composer update
php artisan vendor: publish
php artisan jwt: secret
php artisan config: clear
php artisan cache: clear
php artisan clear-compiled
php artisan optimize
composer dumpautoload

**Comment by chrisbbreuer** [comment]
there are still issues
this:
```bash
composer update
php artisan vendor: publish
php artisan jwt: secret
php artisan config: clear
php artisan cache: clear
php artisan clear-compiled
php artisan optimize
composer dumpautoload
```

should be 

```bash
composer update
php artisan vendor:publish
php artisan jwt:secret
php artisan config:clear
php artisan cache:clear
php artisan clear-compiled
php artisan optimize
composer dump-autoload
```

You may want to go over some Laravel fundamentals. Laracasts is a great resource

**Comment by dt-jegomez** [comment]
cual es la diferencia ?
