### ISSUE TITLE
"Target [Tymon\JWTAuth\Providers\JWT\JWTInterface] is not instantiable." on v0.5.4

### ISSUE THREAD

**Issue by rockymontana** [tymondesigns/jwt-auth#189]
I've followed the guide on the wiki regarding Laravel 5(.1), when I do
```$ php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"```
I get:
```

[Illuminate\Contracts\Container\BindingResolutionException]             
  Target [Tymon\JWTAuth\Providers\JWT\JWTInterface] is not instantiable.
```

I updated the class definition to fit the rest of the Provider config like this:

```
Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,
```

and the Facades as well:

```
'JWTAuth'    => Tymon\JWTAuth\Facades\JWTAuth::class,
'JWTFactory' => Tymon\JWTAuth\Facades\JWTFactory::class, 
```

Any ideas why that don't bind?

**Comment by tymondesigns** [comment]
hmm.. strange, you tried `composer dump` ?

**Comment by rockymontana** [comment]
Yup!
That however failed as well with the same errors as above.
But I updated to dev-master, which worked just fine.
Might it be related to 5.1 maybe?

**Comment by tymondesigns** [comment]
what version of `jwt-auth` were you using prior? because if it was `0.6.*@dev` then the path for the service provider is different

**Comment by rockymontana** [comment]
0.5.4 (I put it in the topic =) ).
The paths were correct (I checked them before I updated).
Since I got it sorted with dev-master I’m all set, but it could be nice for others with the same issue to see that the dev-branch works in case they interested.

**Comment by tymondesigns** [comment]
Ah, missed that :+1: .. Must be something else going on since `0.5.4` and master are [identical](https://github.com/tymondesigns/jwt-auth/compare/0.5.4...master)

**Comment by oldskool73** [comment]
Just an FYI for anyone else that might hit this, looks like the order is important if you have any other packages that provide their own auth, e.g. I found ...

```
...
SleepingOwl\Admin\AdminServiceProvider::class,
Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,
...
```

...gives the above error, but 

```
...
Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,
SleepingOwl\Admin\AdminServiceProvider::class,
...
```

...doesn't.

**Comment by Phunky** [comment]
Cheers for the headsup @oldskool73, sticking JWTAuthServiceProvider as the first in the array got rid of the error for me.

**Comment by ricoa** [comment]
It works for me too! @oldskool73

**Comment by toramanlis** [comment]
Turns out not registering the service provider at all also produces errors. Who would have known. Cheeers
