### ISSUE TITLE
I can't use token through middleware

### ISSUE THREAD

**Issue by noecs** [tymondesigns/jwt-auth#1904]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 6.5
| Package version   | 1.0
| PHP version       | 7.3

### Steps to reproduce
I created a minimal example that reproduces the problem.
`php artisan migrate`
Need to insert a user information into the database to the `admin_users` table.
When I get the user token and get the user information through `postman`, refresh the token, invalidate the token, etc. http request. Will report an error
```
"message": "Argument 3 passed to Lcobucci\\JWT\\Signer\\Hmac::doVerify() must be an instance of Lcobucci\\JWT\\Signer\\Key, null given, called in /Volumes/data/ Project/super-admin/vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 44",
     "status_code": 500,
     "debug": {
         "message": "Argument 3 passed to Lcobucci\\JWT\\Signer\\Hmac::doVerify() must be an instance of Lcobucci\\JWT\\Signer\\Key, null given, called in /Volumes/data/ Project/super-admin/vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 44",
         "line": 29,
         "file": "/Volumes/data/Project/super-admin/vendor/lcobucci/jwt/src/Signer/Hmac.php",
         "class": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
```
[https://github.com/noecs/super-admin](https://github.com/noecs/super-admin)

**Comment by flavio-alves** [comment]
Did you generate the secret?
`php artisan jwt:secret`

**Comment by noecs** [comment]
@flavio-alves 
Yes, I am sure I executed and generated the secret

**Comment by noecs** [comment]
Sorry, I can't stand the bug that this package brought me.
