### ISSUE TITLE
ttl without expiration time.

### ISSUE THREAD

**Issue by KudlaiViktor** [tymondesigns/jwt-auth#192]
How to set up token without expiration time?

```
'ttl' => 0,
```
It's not working. Thanks.

**Comment by tymondesigns** [comment]
this is not currently possible, but I will be adding it in the next release

**Comment by vikasddun** [comment]
Is there any way we can extend token expiry date when catching TokenExpiredException in the Middleware

**Comment by bwaaaaaa** [comment]
@tymondesigns thanks for adding this on the next release. This feature is needed on mobile apps  :+1:

**Comment by jadjoubran** [comment]
Is there another issue to track the progress of this feature?

**Comment by tymondesigns** [comment]
@jadjoubran I have now added this on the develop branch, you simply need to set `null` as the ttl, and as a result the token will not contain an `exp` claim

**Comment by jadjoubran** [comment]
@tymondesigns that's great news!

1. Let me know if you want me to test a certain aspect of this
2. Would you mind briefly explaining the security behind this? Does it make it insecure if we're setting the ttl to null? Maybe there's a way to refresh the token everyone and a while?
3. I'm working on an out of the box integration with your package [here](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/41)

Cheers!
