### ISSUE TITLE
Laravel Passport (Personal Access Tokens) and JWT Auth are basically the same thing.

### ISSUE THREAD

**Issue by ajarti** [tymondesigns/jwt-auth#1936]
@shirshak55 @joelwmale Actually Passport's personal access tokens are pretty much the same thing.

**Comment by ajarti** [comment]
Opps was supposed to be a comment.

**Comment by ajarti** [comment]
Please delete.

**Comment by shirshak55** [comment]
@ajarti no actually.  see this : https://jwt.io/ . Yea they have same purpose but they are completely different. Laravel passport is supposed to be for Oauth purpose.

**Comment by ajarti** [comment]
@shirshak55 Agreed they are not **exactly** the same thing, but for the majority of people that want to use tokens to auth their SPA against their Laravel API .. Passport (personal tokens) do the same basic function, I.E. Takes a Username/Password .. returns a token, use the token in the Bearer header after that.  You do not HAVE to use the Oauth2 sections of Passport see: [Personal Access Tokens](https://laravel.com/docs/5.8/passport#personal-access-tokens).

I think because this library was a first mover years back in the token space for Laravel and as a result has many Medium articles etc, people use it as a "default".  There are alternatives is all I am saying.

See https://www.youtube.com/watch?v=R3Hec0_U2Cs for a simple example.

**Comment by shirshak55** [comment]
@ajarti yeah i used to use laravel passport for passwordless token. But after finding it takes like 6+ queries etc I stopped using it. I would recommend to use Airlock.  I have moved on and don't use laravel anymore due to Rust/Typescript so don't know much in detail but Airlock looks better for most people use case.

**Comment by ajarti** [comment]
OK cool ... Airlock?

**Comment by shirshak55** [comment]
https://github.com/laravel/airlock

**Comment by ajarti** [comment]
Oh nice ... thanks @shirshak55 :)
