### ISSUE TITLE
Add Laravel 7 support

### ISSUE THREAD

**Issue by iforwms** [tymondesigns/jwt-auth#1943]
### Subject of the issue
Current dependencies not satisfied by Laravel 7.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 7.0.0
| Package version   | 1.0.0-rc5.1
| PHP version       | 7.4.0

### Steps to reproduce
Try and upgrade Laravel to version 7.0.0.

### Expected behaviour
Composer update should complete sucessfully.

### Actual behaviour
Dependency error

```
tymon/jwt-auth 1.0.0-rc.5.1 requires illuminate/support ^5.1|^6 
```

Updating composer dependencies to allow `illuminate/support ^7`.

**Comment by aljamzd** [comment]
Please add Laravel 7 support or provide a temporary solution.

**Comment by erikn69** [comment]
Please add Laravel 7 support

**Comment by p4scu41** [comment]
I wanted to test the new Laravel 7 but I wasn't able, it would be great to add the support.

**Comment by gerardnll** [comment]
Please @tymondesigns it would be great if you can merge any of the PRs about this, Thanks.
