### ISSUE TITLE
Optional auth identifier

### ISSUE THREAD

**Issue by lihusha** [tymondesigns/jwt-auth#1945]
What about a possibility to make authentication by different with `sub` field?

For example, if in the [line](https://github.com/tymondesigns/jwt-auth/blob/develop/src/JWTGuard.php#L82) will be changed `$payload['sub']` to something like `$payload[config('jwt.auth_identifier_name', 'sub')]`, it will give a possibility to make authentication by custom claim field, different with `sub` (something like `custom-sub`)

**Comment by tymondesigns** [comment]
why would you want to change this?

**Comment by Victor-emil** [comment]
I'm currently migrating a Strapi project to Laravel. Strapi is using an "id" identifier instead of "sub" to locate users in the database. So in my case it would be excellent to override the key for how to retrieving the user id in the jwt payload.
