### ISSUE TITLE
There is some problem with your token

### ISSUE THREAD

**Issue by rupesh-tech** [tymondesigns/jwt-auth#1954]
### Subject of the issue
Describe your issue here.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no / yes
| New Feature?      | no / yes
| Framework         | Laravel / Lumen
| Framework version | 5.x.y
| Package version   | 1.x.y
| PHP version       | 5.x.y / 7.x.y

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by rupesh-tech** [comment]
[git_hub.docx](https://github.com/tymondesigns/jwt-auth/files/4329365/git_hub.docx)

**Comment by ibrainventures** [comment]
@rupesh-tech 

!! a undocumented .docx !! for download ... 
in time of word-virus etc. i would bet you to write something about your issue ..

@tymondesigns ... may this is a security issue .. backdoor catching ...
