### ISSUE TITLE
don't work on laravel7

### ISSUE THREAD

**Issue by nilsir** [tymondesigns/jwt-auth#1955]
### Don't work on laravel7
When will it support laravel7?

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.x
| Package version   | 1.x
| PHP version       |  7.3.x

**Comment by mfn** [comment]
I'm running it with L7. What's you actual problem? Error message? Stacktrace?

**Comment by nilsir** [comment]
> I'm running it with L7. What's you actual problem? Error message? Stacktrace?

when exec
```shell
composer require tymon/jwt-auth:1.0.0-rc.5.1
```
I got
![image](https://user-images.githubusercontent.com/15967737/76699216-556dec80-66e6-11ea-86ec-60887b3f7c0f.png)

Which version should I choose?
3q for answer

**Comment by specialtactics** [comment]
You should use 1.0.0 not rc

**Comment by nilsir** [comment]
> You should use 1.0.0 not rc

3q. I installed it.
