### ISSUE TITLE
invalidate all other sessions

### ISSUE THREAD

**Issue by MehdiAghighi** [tymondesigns/jwt-auth#1959]
### Invalidating All Other tokens for user except the current one using

Laravel Framework auth provides something called [Invalidating Sessions On Other Devices](https://laravel.com/docs/7.x/authentication#invalidating-sessions-on-other-devices)

which for example when i change my password with my laptop, it stays logged In at my current session but all other sessions are invalidated and logged out.
i want to this with jwt-auth and when i do something in my app i want to invalidate all tokens which belongs to this user except with one which he is currently logged in

do you have any ideas ?

**Comment by mattmcdev** [comment]
You can create a custom claim of the last updated timestamp and invalidate all tokens which don't match the current value.

**Comment by MehdiAghighi** [comment]
@mattmcdonald-uk can you please help me how to set a custom dynamic claim like timestamp ?
i searched for that a lot but didn't find any thing ...

**Comment by mattmcdev** [comment]
As an example, assuming a column called `password_last_updated` you were casting to a `datetime`, you could add this to your User model:

````
/**
 * Return a key value array, containing any custom claims to be added to the JWT.
 *
 * @return array
 */
public function getJWTCustomClaims()
{
    return [
        'pwu' => $this->getPasswordLastUpdatedTimestamp(),
    ];
}

/**
 * Return a timestamp of the password_last_updated value.
 *
 * @return int|null
 */
public function getPasswordLastUpdatedTimestamp()
{
    return is_null($this->password_last_updated) ? null : $this->password_last_updated->timestamp;
}
````

As a separate issue, there's a bug which means custom claims like this aren't updated when refreshing tokens. So if refreshing tokens is part of your flow you can ensure custom claims are updated by adapting [this example middleware](https://gist.github.com/mattmcdonald-uk/cce530a90b00bdb3ed05ac4f826dae1c).

**Comment by MehdiAghighi** [comment]
thank you for your great idea
