### ISSUE TITLE
Change token name in header.

### ISSUE THREAD

**Issue by KudlaiViktor** [tymondesigns/jwt-auth#196]
I'm using nginx basic auth for my API.
Nginx has same header name **"Authorization"** as this library.
My token example:
```
Authorization: Bearer e1yJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJzdWIiOiIxIiwiaXNzIjoiaHR0cD
pcL1wvbG9jYWwubXV6emFsaWZlLmNvbVwvYXV0aFwvbG9naW4iLCJpYXQiOiIxNDM2ODgyMTQ3IiwiZXhwIjoiMTQz
Njg4NTc0NyIsIm5iZiI6IjE0MzY4ODIxNDciLCJqdGkiOiI5YzYyNDFkM2UzZDcwY2E1OTcyZWQ0MWMxNDQ4Zjk1Yi
J9.OWY5YzcyOGI2YzhkMDA4YjM4MThiYTQwMjI2NDdmNTk0ZGE5ZGQ0OGZlOTE3ZTNiODc3ZTAzOWVmYjNiMmNmYQ
```
Is it possible to change header name, or how to figure out in this situation? Thanks.

**Comment by tymondesigns** [comment]
The `parseToken()` method accepts some parameters to change this. E.g.

```php
JWTAuth::parseToken('bearer', 'headerNameHere')->authenticate();
```

**Comment by dwietecha** [comment]
How can I change header globaly?
In my app had been used jwt-auth filter. There is no parseToken method induction in controllers. So I can't  parameterize token parsing.

**Comment by tdhsmith** [comment]
You can certainly create your own copy of the `jwt.auth` middleware that only changes the `parseToken` call.

**Comment by dwietecha** [comment]
Ok, thanks
6 gru 2015 1:22 AM "t d h smith" <notifications@github.com> napisał(a):
