### ISSUE TITLE
[Question] Where generated access tokens are stored

### ISSUE THREAD

**Issue by pgruziel** [tymondesigns/jwt-auth#1964]
### [Question] Where generated access tokens are stored
I suppose that they should be somewhere in cache or in database, but I can't see them there.
Is there a possibility to clear them and logout all users?

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.0
| Package version   | 1.0
| PHP version       | 7.2.5

**Comment by mikebarlow** [comment]
Generated access tokens are not stored anywhere by this package.

This package simply generates the token, usually this token would then be returned from an API to a frontend that is consuming the API. The frontend itself would store the token in something like a Cookie or js local storage depending on your preferences.
