### ISSUE TITLE
Token retrieving user always return false

### ISSUE THREAD

**Issue by Poupoule** [tymondesigns/jwt-auth#1965]
### Subject of the issue
I'm trying to get back user from a token but it always returning me false. In facts it was working untill i deleted email and password in the User table. I've tried adding an identifier, or also several potential fixes found on similar problem. The fact is i'm doing a SSO ADFS connexion afterwards i send a JWT token to my front (laravel is only my backend). But when my frontend send the token to the back and try to retrieve user he only get a false.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | ?
| New Feature?      | no
| Framework         | Laravel
| Framework version | 6.18.1
| Package version   | latest
| PHP version       | 7.2

### Expected behaviour
Retrieve the user

### Actual behaviour
Returning false

Authentication
`try {

                if (!$token = JWTAuth::fromUser($u)) {

                    return response()->json(['error' => 'invalid_credentials'], 400);

                }

            } catch (JWTException $e) {

                return response()->json(['error' => 'could_not_create_token'], 500);

            }`

Middleware
`try {

            $user = JWTAuth::parseToken()->authenticate();

        } catch (Exception $e) {

            if ($e instanceof \Tymon\JWTAuth\Exceptions\TokenInvalidException){

                return response()->json(['status' => 'Token is Invalid'],403);

            }else if ($e instanceof \Tymon\JWTAuth\Exceptions\TokenExpiredException){

                return response()->json(['status' => 'Token is Expired'], 400);

            }else{

                return response()->json(['status' => 'Authorization Token not found'], 404);

            }

        }

        return $next($request);`

Here $user always equals false.
My User entity is only a Name and the things to make the token work.

Any idea ? Thanks for all.

Edit : I used credential methode when i was still having a password with a local authentication.

**Comment by seniordev-ca** [comment]
@Poupoule, did you solve the issue ?

**Comment by Poupoule** [comment]
Yeah i did if i remember well i was missing a code line somewhere but i don't have anymore my code so i can't check in the code how did i fix it. But if you have a similar issue i can try to find out where is the problem !

**Comment by seniordev-ca** [comment]
@Poupoule, thanks for your reply.
I have exactly same issue with you.

`$user = JWTAuth::parseToken()->authenticate();`

user returns always false.

**Comment by Poupoule** [comment]
What is your $user ? Because by reading my post it seems that i tried to used authenticate on an user without password and that what why it returns false. It seems i used something else or a password to fix that. I'm not sure... But if you have your inisialisation of your var or something maybe i can figure out (sorry 4 month i've been working on that project and i don't have access to the source code)

**Comment by ghost** [comment]
Well, @drizzle3023 I had an equal issue. Make sure you do not override the User properties, e.g. username/password. In case you do and you set them null or anything else, the Lumen/Laravel behind the scenes magic won't work and the JWT-Factory is going to return false.

**Comment by Poupoule** [comment]
> 
> 
> Well, @drizzle3023 I had an equal issue. Make sure you do not override the User properties, e.g. username/password. In case you do and you set them null or anything else, the Lumen/Laravel behind the scenes magic won't work and the JWT-Factory is going to return false.

Yeah as i told you need username/password properties in your $user object, else you should use another authenticate method, i know i did something else than authenticate, if you wish i can try to find out in the documentation the way i used.

**Comment by seniordev-ca** [comment]
@Poupoule, @noxsbl I posted my exact issue here, can you help me please ?

https://github.com/tymondesigns/jwt-auth/issues/2006

**Comment by maulayyacyber** [comment]
sam problem
