### ISSUE TITLE
Third party generated JWT compatibility

### ISSUE THREAD

**Issue by wemersonrv** [tymondesigns/jwt-auth#1969]
### Subject of the issue
JWT compatibility

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | no
| Framework         | Laravel and Lumen
| Framework version | 7.0
| Package version   | 1.0.0
| PHP version       | 7.3 / 7.4

Hi, this is just a question if it's possible to use this package with tokens generated for other tools. 

My specific case: I'm mobile developer, and use firebase authentication on my apps. So, need to send the JWT token to backend (laravel) to authorize users... So it's possible to use this package to validate this kind of token generated by FIREBASE ?

I don't want to generate the tokens, just to validate them.

**Comment by germangamboa95** [comment]
You should be able to do it. You'll need to make sure the configs are the same for both the generating one and the reading one.

**Comment by wemersonrv** [comment]
> You should be able to do it. You'll need to make sure the configs are the same for both the generating one and the reading one.

Are you talking about APP_KEY? O there are more configs to check ?

**Comment by germangamboa95** [comment]
You are want to make sure the secret key is the same. 
You can read more about it here (https://jwt.io/introduction/)
