### ISSUE TITLE
How to invalidate a token string

### ISSUE THREAD

**Issue by amilgaul** [tymondesigns/jwt-auth#199]
hi, 

I just want to ask if there is a way to invalidate token string which is being get from post data calls.

Example:
//in backend ( laravel )
Route::post('/invalidate',function() {
    $token = Request::input('token');
    $token->invalidate();
});

**Comment by tymondesigns** [comment]
There is a invalidate method on the JWTAuth instance e.g.

```php
Route::post('/invalidate', function() {
   JWTAuth::parseToken()->invalidate();
});
```
