### ISSUE TITLE
Guard not working on laravel 7.1

### ISSUE THREAD

**Issue by jhgeluk** [tymondesigns/jwt-auth#1998]
### Subject of the issue
I've added JWT authentication to my laravel project, and I've followed all installation steps.
However when I navigate to a route that should be "protected" I can still access it without any issues.

It should instead give me a 401, because I didn't provide the authentication header.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.16.1
| Package version   | 1.0.0
| PHP version       | 7.4.4

### Steps to reproduce
Follow the installation steps and access a route under the 'middleware' => 'api' group

### Expected behaviour
I should get a 401 response

### Actual behaviour
Returns 200 response (I have access)

**Comment by rheedwahn** [comment]
I think the middleware auth to have been 'auth:api'
