### ISSUE TITLE
Unable to get Authorization header with laravel 5.1

### ISSUE THREAD

**Issue by fligen** [tymondesigns/jwt-auth#200]
When looking at the header on developer tools I see that it is in place but when requesting it with Request::header('Authorization') all I get is string(0) ""

I have added:
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

to my .htaccess 

I am using MAMP for my local environment with php 5.6.7

I sure my previous issue #195 is directly related to this as the middleware is unable to pull the token from the header.

Any ideas?

**Comment by tymondesigns** [comment]
what do you get if you run this:

```php
Route::get('test', function () {
   $token = JWTAuth::getToken();
   dd($token);
})
```

Still an empty string?

**Comment by fligen** [comment]
Call to a member function get() on boolean

**Comment by fligen** [comment]
if i pull the get() off I get "false".

**Comment by tymondesigns** [comment]
Ok, just one more to try
```php
Route::post('test', function () {
   $token = JWTAuth::parseToken('bearer', 'HTTP_AUTHORIZATION')->getToken();
   dd($token);
});
```

**Comment by fligen** [comment]
false

**Comment by fligen** [comment]
and if i run it in a view i get

The token could not be parsed from the request

**Comment by fligen** [comment]
I am using satellizer in my angular app, if that makes any diff.

**Comment by tymondesigns** [comment]
If you dump all headers from the request can you see the token?

**Comment by fligen** [comment]
no, shows an empty string in laravel, but can see the header on each request in dev tools.  I'm really banging my head against the wall on this one.

**Comment by fligen** [comment]
ok, this is an apache issue, I respun the app with nginx and it worked like a champ.

**Comment by frenetic** [comment]
@fligen @tymondesigns If this does not apply, please close :smiley_cat:

**Comment by frenetic** [comment]
Also, Im facing a problem that may be related to this:
https://github.com/tymondesigns/jwt-auth/issues/206

**Comment by carlosalaniz** [comment]
I had the same issue, I just used the native php function to retrieve the header I needed 

`getallheaders()["Authorization"] !==null`
