### ISSUE TITLE
set infinity TTL token

### ISSUE THREAD

**Issue by fdai3105** [tymondesigns/jwt-auth#2004]
### Your environment
| Q                 | A
| ----------------- | ---
| Framework         | Laravel
| Framework version | 7.0.x
| Package version   | 1.x.y
| PHP version       | 7.2.y / 7.2.y

I want to set TTL token not expire
TTL=null is not working
![image](https://user-images.githubusercontent.com/43561662/87115272-f20f5800-c29c-11ea-9493-3e2ae1dda567.png)
![image](https://user-images.githubusercontent.com/43561662/87115283-f89dcf80-c29c-11ea-973e-b2ba540e38cf.png)
expires_in still 3600
![image](https://user-images.githubusercontent.com/43561662/87115313-0f442680-c29d-11ea-91ba-17dffd6c8a84.png)

**Comment by Abdurozzaq** [comment]
have you tried to run the ``php artisan config:clear``
