### ISSUE TITLE
JWTAuth::parseToken()->authenticate() always returns false in middleware

### ISSUE THREAD

**Issue by seniordev-ca** [tymondesigns/jwt-auth#2006]
### Subject of the issue
I've created middleware for api auth and get token exactly from request header.
I've tested with JWTAuth::getToken()->get(); and works fine.
I want to get user from token and pass it to every request so that I can get user from controlleres via $user = request('user');
But JWTAuth::parseToken()->authenticate(); always returns false.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | ?
| New Feature?      | no
| Framework         | Laravel
| Framework version | 7.16.1
| Package version   | 1.0.0
| PHP version       | 7.3.19

### Expected behaviour
Get User Object
### Actual behaviour
Returns false

Middleware

```
public function handle($request, Closure $next, $guard = null)
    {
        $chain = JWTAuth::parser()->getChain();

        foreach ($chain as $item) {
            if ($item instanceof AuthHeaders) {
                $item->setHeaderName('x-api-token');
                $item->setHeaderPrefix('prefix');
            }
        }

        try {
            $user = JWTAuth::parseToken()->authenticate();
            $request->merge(['user' => $user]);
        } catch (Exception $e) {
            if ($e instanceof \Tymon\JWTAuth\Exceptions\TokenInvalidException){
                return response()->json(['error' => 'invalid-token']);
            }else if ($e instanceof \Tymon\JWTAuth\Exceptions\TokenExpiredException){
                return response()->json(['error' => 'token-expired']);
            }else{
                return response()->json(['error' => 'token-not-found']);
            }
        }
        return $next($request);
    }
```

$user always returns false not user model.

**Comment by Rho1and0** [comment]
The same happens to me

**Comment by seniordev-ca** [comment]
Hi, @Rho1and0 
I used `auth('api')->user()` instead of `$user`.
So it will look like this:
```
try {
        JWTAuth::parseToken()->authenticate();
        $request->merge(['user' => auth('api')->user()]);
    }
...
```
