### ISSUE TITLE
Remove closures from config to allow config:cache artisan command

### ISSUE THREAD

**Issue by ddewit** [tymondesigns/jwt-auth#203]
When using config:cache on deployment, a fatal error is thrown (or, if debugging is disabled, a white page is shown). This is caused by a few config settings using a closure to instantiate a new class.

Using callbacks of some sort should be able to fix this.

**Comment by frenetic** [comment]
+1

**Comment by jadjoubran** [comment]
The solution suggested [here](https://github.com/tymondesigns/jwt-auth/issues/147) is not working for me..
Here's how I fixed it:

'auth' => 'Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter',
'storage' => 'Tymon\JWTAuth\Providers\Storage\IlluminateCacheAdapter'

It's being used in [laravel5-angular-material-starter](https://github.com/jadjoubran/laravel5-angular-material-starter)

**Comment by tymondesigns** [comment]
I have now removed closures on the develop branch. And as @jadjoubran mentioned, you can simply switch to a string, if you want to cache the config
