### ISSUE TITLE
Token issues under laravel-swoole

### ISSUE THREAD

**Issue by alecpl** [tymondesigns/jwt-auth#2033]
### Subject of the issue
Token is not valid anymore after app restart if the app is running under swoole.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no / yes
| New Feature?      | no / yes
| Framework         | Laravel
| Framework version | 6.18.40
| Package version   | 1.0.1
| PHP version       | 7.4.9

### Steps to reproduce
1. Create an app with JWT tokens as described in documentation. (My JWT config is pretty much the default).
2. Integrate laravel-swoole
3. Run the app using laravel-swoole: `php artisan swoole:http start`
4. Use the app, so you get the token and make sure the token works on multiple followinig requests.
5. Restart the app (Ctrl+C and then `php artisan swoole:http start` again).
6. At this point the token does not work anymore. No errors in log.

Another issue is that token refresh throws exception "The token has been blacklisted".
Under swoole expired token use throws "expired content" exception causing 500 response code. This is not the case without swoole.

Any ideas why that happens? Does anyone use JWT with swoole? How I can debug these problems?

**Comment by alecpl** [comment]
Fixed by setting these in `config/swoole_http.php`:
```
'instances' => [
    'auth',
],
'providers' => [
    Illuminate\Pagination\PaginationServiceProvider::class,
    App\Providers\AuthServiceProvider::class,
    Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
],
```

**Comment by brijesh1997** [comment]
Hello @alecpl ,

I added this in my swoole_http.php file but I fetch below fatal error please check below screenshot and tell me what I need to do for that.

https://prnt.sc/w9j5tr

```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in /var/www/html/lumen-JWT-SWOOLE/lumen/vendor/swooletw/laravel-swoole/src/Server/Manager.php:414
Stack trace:
#0 /var/www/html/lumen-JWT-SWOOLE/lumen/vendor/swooletw/laravel-swoole/src/Server/Manager.php(398): SwooleTW\Http\Server\Manager->normalizeException()
#1 /var/www/html/lumen-JWT-SWOOLE/lumen/vendor/swooletw/laravel-swoole/src/Server/Manager.php(239): SwooleTW\Http\Server\Manager->logServerError()
#2 {main}
  thrown in /var/www/html/lumen-JWT-SWOOLE/lumen/vendor/swooletw/laravel-swoole/src/Server/Manager.php on line 414
```
