### ISSUE TITLE
Response status 401, even when passing correct token

### ISSUE THREAD

**Issue by mrozbarry** [tymondesigns/jwt-auth#2036]
### Subject of the issue

I am unable to authenticate on a route that requires jwt authentication.
In both tests and manual testing with postman, I get 401 errors.
I'm guessing the setup documentation is outdated or expects special knowledge of laravel or this package.
I referenced #1912 for my tests, but I don't seem to get any better results than plainly using `actingAs`.
I also read through https://www.codechief.org/article/laravel-6-rest-api-with-jwt-authentication-with-crud , but it seems to contain errors and is maybe not relevant for laravel 8. In fact, there are a handful of similar resources about this library and laravel 8, and they all seem to just copy the https://jwt-auth.readthedocs.io documentation and occasionally introduce a bug or do some minor modification that shouldn't matter (like adding aliases).

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.1.0
| Package version   | 1.0.1
| PHP version       | 7.4.10 & 7.3.x

### Steps to reproduce

 1. New laravel app
 2. `composer require tymon/jwt-auth`
 3. From https://jwt-auth.readthedocs.io/en/develop/laravel-installation/ , **skip** provider, not required for laravel 8
 3. `php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"`
 4. `php artisan jwt:secret`
 5. Follow instructions in https://jwt-auth.readthedocs.io/en/develop/quick-start/#update-your-user-model to update the **User** model and configure the auth guard. Preferably, I don't want to change the default guard, but I did for the sake of following the initial instructions
 6. Create authentication controller (see code below)
 7. Create user and log in successfully (get a token)
 8. Attempt to hit url behind api auth, with token, but get 401

#### config/auth.php
<details>

```php
return [
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
    ],
];
```

</details>

#### Authenticate/Store.php
<details>

```php
namespace App\Http\Controllers\Api\Sessions\Authenticate;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class Store
{
    public function __invoke(Request $request) : JsonResponse
    {
        $credentials = $request->only(['email', 'password']);

        $validator = Validator::make($credentials, [
            'email' => 'required|exists:App\Models\User,email',
            'password' => 'required',
        ]);

        if ($validator->fails()) {
            return $this->failure();
        }

        $response = $this->tokenCreate($credentials);

        return new JsonResponse(
            $response['body'],
            $response['status'],
        );
    }

    private function failure() : JsonResponse
    {
        return new JsonResponse(
            [],
            JsonResponse::HTTP_UNAUTHORIZED,
        );
    }

    protected function tokenCreate($credentials)
    {
        $token = auth('api')->attempt($credentials);
        if (!$token) {
            return [
                'status' => JsonResponse::HTTP_UNAUTHORIZED,
                'body' => [],
            ];
        }

        return [
            'status' => JsonResponse::HTTP_CREATED,
            'body' => $this->tokenResponse($token),
        ];
    }

    protected function tokenRefresh()
    {
        return [
            'status' => JsonResponse::HTTP_CREATED,
            'body' => $this->tokenResponse(auth('api')->refresh()),
        ];
    }

    protected function tokenResponse($token)
    {
        return [
            'access_token' => $token,
            'token_type' => 'bearer',
            'expires_in' => auth('api')->factory()->getTTL() * 60,
        ];
    }
}

```

</details>

#### routes/api.php
<details>

```php
Route::group([
    'namespace' => 'Api\Sessions\Authenticate',
    'prefix' => 'sessions',
    'as' => 'api.sessions.',
], function () {

    Route::post('authenticate', 'Store')->name('authenticate.store');
});

Route::group([
    'namespace' => 'Api',
    'as' => 'api.',
    'middleware' => ['jwt.auth'], // I have also just tried `auth` here, since the default guard is api
], function () {

    Route::get('sessions/me', 'Sessions\Me\Index')->name('sessions.me.index');
});
```

</details>

### Expected behaviour

I should not get a 401 for sending the correct token

### Actual behaviour

I get a `401` status code.

**Comment by zishang520** [comment]
+1
>Auth::factory()->buildClaimsCollection()->toPlainArray() 

Unable to load data

My problem is solved

`$payload = Auth::manager()->getJWTProvider()->decode(Auth::getToken()->get())`

**Comment by mrozbarry** [comment]
I ended up switching to sanctum, but it looks like @zishang520 has a solution, so I'm going to close this.
