### ISSUE TITLE
There are no commands defined in the "jwt" namespace (error)

### ISSUE THREAD

**Issue by ltiisidii** [tymondesigns/jwt-auth#205]
I follow the steps as is explained in the wiki. But I have this error when generating the secretkey.

"  [InvalidArgumentException]
  There are no commands defined in the "jwt" namespace."

My version of laravel is laravel Framework version 5.1.9 (LTS)

as I can fix it?

**Comment by frenetic** [comment]
Just did a fresh install here, and everything seems to be working fine.
Are you sure you didnt missed one step from the Wiki?

If so, please, paste the code/commands you are trying to execute, so we can try to help.

**Comment by tymondesigns** [comment]
Yep, must be something else going on. Make sure you have set up the service provider etc

**Comment by jcaillot** [comment]
Just my 50 cents
had the same issue while I was using cached configuration. php artisan config:clear solved the issue

**Comment by ujjaldey** [comment]
worked after clearing config cache.

**Comment by thanhtutoo** [comment]
omg, @jcaillot  u saved me ,thanks

**Comment by Givemore** [comment]
you can uncomment ：//$app->register(App\Providers\AppServiceProvider::class);
in bootstrap/app.php

**Comment by hadigun** [comment]
Clearing of config, save my day.   php artisan config:clear

**Comment by Sheshkumar123** [comment]
http://www.expertphp.in/article/api-authentication-using-jwt-in-laravel-5-4-tutorial-with-example. Here I am following each step as defined.  but in config folder there is no jwt.php existing and when trying to publish using php artisan vendor -- publish getting message : nothing to publish for tag [] ,if I think already publish ,then  in next step for command
php artisan jwt:secret 
There  are no commands defined in the "jwt" namespace

**Comment by leandroruel** [comment]
nothing is working to me... it's a fresh install and i followed all steps of the wiki... i will remove and install again from developer branch.

**Comment by akinolu52** [comment]
same here also any help @leandroruel

**Comment by leandroruel** [comment]
@akinolu52 i already solved my problem. just get the lastest release on develop branch and be happy

**Comment by dambrogia** [comment]
For anyone running Laravel >=5.5 make sure you have `"tymon/jwt-auth": "^1.0"` in your `composer.json`. [In the WIKI](https://github.com/tymondesigns/jwt-auth/wiki) it states version compatibility.

**Comment by ramesh25** [comment]
use php artisan key:generate

**Comment by itshazlan** [comment]
thanks @dambrogia  you saved my time :D

**Comment by weiweitoo** [comment]
Same issue with  Laravel 5.7.8 here. I able to solved it by add following line in config/app.php

```
'providers' => [
    ....
    'Tymon\JWTAuth\Providers\JWTAuthServiceProvider',
],
'aliases' => [
    ....
    'JWTAuth' => 'Tymon\JWTAuth\Facades\JWTAuth',
        'JWTFactory' => 'Tymon\JWTAuth\Facades\JWTFactory',
],
```

Reference [here](https://appdividend.com/2018/02/24/laravel-jwt-authentication-tutorial/)

**Comment by marufmax** [comment]
Having the same issue in laravel 5.7 application. 

just add `  "tymon/jwt-auth": "dev-develop"`   will solve your problem.

**Comment by irfanabdurrasyid** [comment]
> Having the same issue in laravel 5.7 application.
> 
> just add `"tymon/jwt-auth": "dev-develop"` will solve your problem.

where your add script. are in .env?

**Comment by hackerunet** [comment]
This doesn't work... I have a complete fresh install and none of the code added to the entire issue works for latest lumen.

**Comment by marufmax** [comment]
> where your add script. are in .env?

in your composer.json file.

**Comment by hackerunet** [comment]
The issue here is the order how to do things, you have to enable all facades and providers first before attempting the jwt:secret from cli.

**Comment by philwamba** [comment]
I had the same issue in Laravel 5.7... Solved it by updating `"tymon/jwt-auth": "^0.5"` in `composer.json` file to `"tymon/jwt-auth": "^1.0.0-rc.3"`
```
"require": {
        ...
        "tymon/jwt-auth": "^1.0.0-rc.3",
        ...
    },
```
and then run

`composer update`

and finally, add following line in `config/app.php`
```
'providers' => [
    ....
    Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
],
'aliases' => [
    ....
    'JWTAuth' => Tymon\JWTAuth\Facades\JWTAuth::class,
],
```

**Comment by mateusgalasso** [comment]
> For anyone running Laravel >=5.5 make sure you are have `"tymon/jwt-auth": "^1.0"` in your `composer.json`. [In the WIKI](https://github.com/tymondesigns/jwt-auth/wiki) it states version compatibility.

Thank you

**Comment by mytuny** [comment]
use `php artisan jwt:secret` instead to generate the key.

**Comment by mhlanga-joseph** [comment]
@philwamba worked for me. thanks
