### ISSUE TITLE
Mixed multi-auth with JWT - automatically logging in both LDAP and Eloquent based models with same token

### ISSUE THREAD

**Issue by rummanrc** [tymondesigns/jwt-auth#2058]
### Subject of the issue
Mixed (LDAP and Eloquent) multi-auth with JWT - automatically logging in both LDAP and Eloquent based models with same token

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | probably
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.15.0
| Package version   | 1.0.1
| PHP version       | 7.4.11

### Steps to reproduce
1. This repo's new_role_test_ldap branch contains all my code related to this issue.

https://github.com/rummanrc/laravelguardissue8/tree/new_role_test_ldap

2. This is the env config for the publicly available LDAP server I'm using to test:
```
LDAP_CONNECTION=default
LDAP_BASE_DN='dc=example,dc=com'
LDAP_LOGGING=true
LDAP_HOSTS=ldap.forumsys.com
LDAP_PORT=389
LDAP_TIMEOUT=5
LDAP_SSL=false
LDAP_TLS=false
LDAP_USERNAME=cn=read-only-admin,dc=example,dc=com
LDAP_PASSWORD=password
```
3. Migrate and seed, then login as employee with any username and password from here https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/
Then login as admin or trainer.

4. Use the admin token as Bearer Token and make a post request on http://localhost:8000/api/employee/me
and you'll see that the employee info is visible

### Expected behaviour

I have three separate guards: admin, user and trainer. Admin and Trainer login using eloquent driver and uses 'admin' and 'trainer' guard respectively. Employees login using ldap driver and uses 'user' guard. I'm using jwt-auth library for token based authentication and ADLDAP2-laravel for ldap auth. When I login as admin, I get a token. I can use that token to access admin info. Admin should not access Employee (user guard) info.

### Actual behaviour
 If I use the admin token on an Employee route, I can access the employee's information with the same id as the admin (e.g admin with id 2 can access employee with id 2's info). Similarly, Trainer can access Employee info when the id's match.

The 'user' guard gets assigned to both Trainer and Admin, which is causing this issue.

The JWT Auth class authenticates the admin with the values from the correct table. Then, queries both admins table and employees table using ID, and logs in both Admin and Employee using the same token. This is where it goes wrong. I'm not sure why JWT logs in both models at the same time...

**Comment by tymondesigns** [comment]
Is your `jwt.lock_subject` config set to true? https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php#L194

**Comment by rummanrc** [comment]
Yes it is set to true... It seems like for every Auth::attempt or Auth::guard()->attempt() the AdldapAuthServiceProvider class is being used, regardless of the guard. I mean even if I authenticate with my admin model (eloquent based), it logs in both admin and employee (who has the same id in a different table) at the same time with the same token.

Although it might not be a JWT specific issue, is it possible to avoid it using custom claims or any other way?

**Comment by rummanrc** [comment]
So I had to override the Adldap2-laravel's DatabaseUserProvider class and put a condition on the retrieveById function.
I added custom claims on my models, and checked for the custom claim (which contains the role) to decide whether to return the model from that function or not. 

This branch contains the code for this solution: https://github.com/rummanrc/laravelguardissue8/tree/bypass_ldap_auto_login
