### ISSUE TITLE
jwt-auth crashes after the dependency lcobucci has been updated to v3.4.0: deprecated method

### ISSUE THREAD

**Issue by danielefavi** [tymondesigns/jwt-auth#2060]
### Subject of the issue
**jwt-auth** crashes after the dependency **lcobucci** recently has been updated to v3.4.0

I run the command `composer update` then the package **lcobucci** has been updated as per below:  
`- Upgrading lcobucci/jwt (3.3.3 => 3.4.0)`

Then I run my phpunit test and I got the following error:

```
ErrorException: Not specifying the signer and key to Builder#getToken() is deprecated. Please move the arguments from Builder#sign() to Builder#getToken().

/var/www/html/auth.local/vendor/lcobucci/jwt/src/Builder.php:486
/var/www/html/auth.local/vendor/tymon/jwt-auth/src/Providers/JWT/Lcobucci.php:116
/var/www/html/auth.local/vendor/tymon/jwt-auth/src/Manager.php:84
/var/www/html/auth.local/vendor/tymon/jwt-auth/src/JWT.php:78
/var/www/html/auth.local/vendor/tymon/jwt-auth/src/JWT.php:90
...
```

To solve this issue I had to pull in the old version of the *lcobucci* package with the command `composer require lcobucci/jwt:"3.3.3"` then the tests run successfully. 

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 8.16.1
| Package version   | 1.0.0
| PHP version       | 7.4.11

**Comment by b-water** [comment]
Same problem here. Breaking Changes: https://lcobucci-jwt.readthedocs.io/en/latest/upgrading/#v3x-to-v4x

**Comment by tymondesigns** [comment]
See #2059
