### ISSUE TITLE
Tymon\\JWTAuth\\Exceptions\\JWTException: Could not create token: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead

### ISSUE THREAD

**Issue by hujianjian187** [tymondesigns/jwt-auth#2061]
### Subject of the issue
Tymon\\JWTAuth\\Exceptions\\JWTException: Could not create token: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 6.20.40
| Package version   | 1.0.1
| PHP version       |  7.2.25

### Steps to reproduce
dependency lcobucci/jwt 3.4.1 version 

```
     /**
     * @param int|DateTimeImmutable $value
     *
     * @return DateTimeImmutable
     */
    private function convertToDate($value)
    {
        if (! $value instanceof DateTimeImmutable) {
            trigger_error('Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead.', E_USER_DEPRECATED);

            return new DateTimeImmutable('@' . $value);
        }

        return $value;
    }
```

### Expected behaviour
Tell us what should happen

### Actual behaviour
To solve this issue I had to pull in the old version of the lcobucci package with the command` composer require lcobucci/jwt:"3.3.3"` then run successfully.

**Comment by Frewen** [comment]
I have the same problem

**Comment by hujianjian187** [comment]
> I have the same problem

ok

**Comment by tymondesigns** [comment]
See https://github.com/tymondesigns/jwt-auth/issues/2059
