### ISSUE TITLE
Could not create token: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead.

### ISSUE THREAD

**Issue by dev-techguy** [tymondesigns/jwt-auth#2062]
Could not create token: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead.

Happens on lcobucci 3.4.0 & 3.4.1

**Comment by henzeb** [comment]
If that happens, you can either require lcobucci 3.3.3, or you can switch to the Namshi provider. specified in the jwt.providers.jwt configuration key.

**Comment by tymondesigns** [comment]
See https://github.com/tymondesigns/jwt-auth/issues/2059
