### ISSUE TITLE
ErrorException: Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. in file xxxx/vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 57

### ISSUE THREAD

**Issue by hellogirls** [tymondesigns/jwt-auth#2064]
### Subject of the issue
ErrorException: Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. in file xxxx/vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 57

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no / yes
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 8.x.y
| Package version   | 1.x.y
| PHP version       | 7.3.y

**Comment by tymondesigns** [comment]
See https://github.com/tymondesigns/jwt-auth/issues/2059
