### ISSUE TITLE
Revert back lcobucci/jwt version

### ISSUE THREAD

**Issue by iranagame** [tymondesigns/jwt-auth#2067]
Since `lcobucci/jwt` has switched 3.4, now this library no longer workings:
Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead

**Comment by tymondesigns** [comment]
A new release has been tagged to prevent the installation of 3.4 and above https://github.com/tymondesigns/jwt-auth/releases/tag/1.0.2
