### ISSUE TITLE
PHP8

### ISSUE THREAD

**Issue by dongmu101** [tymondesigns/jwt-auth#2069]
tymon/jwt-auth dev-develop requires php ^5.5.9|^7.0 -> your php version (8.0.0) does not satisfy that requirement.

**Comment by liamhao** [comment]
Expect to be compatible with php 8.0 as soon as possible

**Comment by dogeow** [comment]
@liamhao I hope so too...

**Comment by jeanali** [comment]
@liamhao  Is it now compatible with PHP 8.0?
