### ISSUE TITLE
Token still valid after credentials change

### ISSUE THREAD

**Issue by fredrkr** [tymondesigns/jwt-auth#207]
Unless I'm missing something obvious, I've found that password- or username-changes after a token has been issued does not affect that token's validity. Shouldn't there be a mechanism for invalidating existing tokens once a user changes his/her credentials? Currently, only the user's id matters in this regard.

Thanks!

**Comment by frenetic** [comment]
IMHO, this is the correct behavior.

Im stating that based on how OAUTH works.
If you have an account in a website that uses OAUTH (like Facebook), and you use this account to sign in to another service (like Spotify), if you modify your password on Facebook, do you get logged out from Spotify?

I understand JWT should behave similar to OAUTH.

Anyways, I do agree with you.
It would be really good to have an optional way of invalidating tokens when user changes password.
:+1:

**Comment by BRupholdt** [comment]
I've worked around this by not using the id field as the subject. In my
case I have a uuid field that I only use for token authentication. I have a
logouteverywhere function which changes the uuid this invalidating all
tokens issued for that user. In your case, you could update the alternate
field value when a user changes their password.

IMHO, this is the correct behavior.

Im stating that based on how OAUTH works.
If you have an account in a website that uses OAUTH (like Facebook), and
you use this account to sign in to another service (like Spotify), if you
modify your password on Facebook, do you get logged out from Spotify?

I understand JWT should behave similar to OAUTH.

Anyways, I do agree with you.
It would be really good to have an optional way of invalidating tokens when
user changes password.
[image: :+1:]

—
Reply to this email directly or view it on GitHub
<https://github.com/tymondesigns/jwt-auth/issues/207#issuecomment-129468610>
.

**Comment by frenetic** [comment]
@BRupholdt YOU ARE A GENIOUS!!!
Im copying this idea :smiley_cat:

@tymondesigns This should be on a "tips and tricks" section in the Wiki!!!

**Comment by fredrkr** [comment]
@BRupholdt Yeah, that seems like a viable solution. If I were to implement this, I'd probably fire an event when the user changes credentials / logs out.

How did you change which table-column jwt-auth compares the subject to, though?

**Comment by BRupholdt** [comment]
In the config/jwt.php, you can set the user identifier field.

**Comment by tymondesigns** [comment]
Good way of solving that issue :+1: @fredrkr not a bad idea :)

**Comment by sumit22** [comment]
I am also using UUID field instead of id field in order to invalidate all issued tokens on event like password reset or a request for logging out from all devices. The problem I am facing is that I am getting http 500 error for a parallel session, because it token validates but fails to create an object for User Model.
