### ISSUE TITLE
Incompatible with PHP 8.0.0

### ISSUE THREAD

**Issue by arislanhaikal** [tymondesigns/jwt-auth#2079]
### Incompatible with PHP 8.0.0
Package tymon/jwt-auth at version 1.0.2 has a PHP requirement incompatible with your PHP version (8.0.0) 

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | no
| New Feature?      | yes
| Framework         | Laravel
| Framework version | 8.19.0
| Package version   | 1.0.2
| PHP version       | 8.0.0

### Steps to reproduce
composer require tymon/jwt-auth:1.0.2

### Expected behaviour
Please provide to compatible for PHP 8.0.0

### Actual behaviour
Package tymon/jwt-auth at version 1.0.2 has a PHP requirement incompatible with your PHP version (8.0.0)

**Comment by realtebo** [comment]
I got his

```
composer require tymon/jwt-auth
Using version ^0.5.12 for tymon/jwt-auth

 tymon/jwt-auth 0.5.12 requires illuminate/support ~5.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
```

Probably related to underlying php v8?

I do not understand why is autoselecting a so old version

**Comment by arislanhaikal** [comment]
I have solved this problem using dev-develop

`composer require tymon/jwt-auth:dev-develop`

Thank you
