### ISSUE TITLE
Install failed.

### ISSUE THREAD

**Issue by JYang99** [tymondesigns/jwt-auth#2083]
Laravel version: 8.20.1
Php version: 8.0

When I am trying `composer require tymon/jwt-auth`, it return me that error below.

> Using version ^0.5.12 for tymon/jwt-auth
> ./composer.json has been updated
> Running composer update tymon/jwt-auth
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires tymon/jwt-auth ^0.5.12 -> satisfiable by tymon/jwt-auth[0.5.12].
>     - tymon/jwt-auth 0.5.12 requires illuminate/support ~5.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
> 
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Below is my composer.json file.
> {
>     "name": "laravel/laravel",
>     "type": "project",
>     "description": "The Laravel Framework.",
>     "keywords": [
>         "framework",
>         "laravel"
>     ],
>     "license": "MIT",
>     "require": {
>         "php": "^7.3|^8.0",
>         "darkaonline/l5-swagger": "^8.0",
>         "fideloper/proxy": "^4.4",
>         "fruitcake/laravel-cors": "^2.0",
>         "guzzlehttp/guzzle": "^7.0.1",
>         "illuminate/support": "^8.20",
>         "laravel/framework": "^8.12",
>         "laravel/tinker": "^2.5",
>         "namshi/jose": "^7.2",
>         "zircote/swagger-php": "^3.1"
>     },
>     "require-dev": {
>         "facade/ignition": "^2.5",
>         "fakerphp/faker": "^1.9.1",
>         "laravel/sail": "^0.0.5",
>         "mockery/mockery": "^1.4.2",
>         "nunomaduro/collision": "^5.0",
>         "phpunit/phpunit": "^9.3.3"
>     },
>     "config": {
>         "optimize-autoloader": true,
>         "preferred-install": "dist",
>         "sort-packages": true
>     },
>     "extra": {
>         "laravel": {
>             "dont-discover": []
>         }
>     },
>     "autoload": {
>         "psr-4": {
>             "App\\": "app/",
>             "Database\\Factories\\": "database/factories/",
>             "Database\\Seeders\\": "database/seeders/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Tests\\": "tests/"
>         }
>     },
>     "minimum-stability": "dev",
>     "prefer-stable": true,
>     "scripts": {
>         "post-autoload-dump": [
>             "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
>             "@php artisan package:discover --ansi"
>         ],
>         "post-root-package-install": [
>             "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "@php artisan key:generate --ansi"
>         ]
>     }
> }
>

**Comment by peter842323** [comment]
This package does not support php 8.0 now :(
You can try use php 7.4 again

**Comment by Ekenzy-101** [comment]
> This package does not support php 8.0 now :(
> You can try use php 7.4 again

How do you go about it?

**Comment by damonto** [comment]
@Ekenzy-101 You can add `--ignore-platform-reqs` to force install it works well for me.

`composer require tymon/jwt-auth --ignore-platform-reqs`

**Comment by rmncv** [comment]
> @Ekenzy-101 You can add `--ignore-platform-reqs` to force install it works well for me.
> 
> 
> 
> `composer require tymon/jwt-auth --ignore-platform-reqs`

Doesn't help if project have same dependencies with different requirements to a minimum versions :(

**Comment by JYang99** [comment]
Ohhh ... It successfully downloaded.

**Comment by noor-ul-amin0** [comment]
> > @Ekenzy-101 You can add `--ignore-platform-reqs` to force install it works well for me.
> > `composer require tymon/jwt-auth --ignore-platform-reqs`
> 
> Doesn't help if project have same dependencies with different requirements to a minimum versio

> Ohhh ... It successfully downloaded.

How did you solve it?

**Comment by damonto** [comment]
Which version  are u using?

```
composer require tymon/jwt-auth:^1.0. --ignore-platform-reqs
```

**Comment by noor-ul-amin0** [comment]
version of what?

**Comment by oviniciusfeitosa** [comment]
```sh
composer require tymon/jwt-auth:^1.0.2
```

**Comment by anchal-1999** [comment]
laravet v =8
php v =7.3|^8.0
When I am trying composer require tymon/jwt-auth, it return me that error below.



D:\pcoder_laravel\AutoRiders>composer require tymon/jwt-auth
Using version ^0.5.12 for tymon/jwt-auth
./composer.json has been updated
Running composer update tymon/jwt-auth
Loading composer repositories with package  #information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires tymon/jwt-auth ^0.5.12 -> satisfiable by tymon/jwt-auth[0.5.12].
    - tymon/jwt-auth 0.5.12 requires illuminate/support ~5.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.



here is my composer

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.3",
        "laravel/framework": "^8.12",
        "laravel/passport": "^10.1",
        "laravel/sanctum": "^2.9",
        "laravel/tinker": "^2.5",
        "laravel/ui": "^3.2",
        "wildbit/swiftmailer-postmark": "^3.3"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by lecchereng** [comment]
Are there any udates?
I'm using last version of Laravel and last version of php (the last released with xamp, 
php --version
PHP 8.0.3 (cli) (built: Mar  2 2021 23:34:05) ( ZTS Visual C++ 2019 x64 )

laravel --version
Laravel Installer 4.2.4
php artisan --version
Laravel Framework 8.38.0
composer --version
Composer version 2.0.12 2021-04-01 10:14:59

composer.json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.12",
        "laravel/tinker": "^2.5"
    },
    "require-dev": {
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

**Comment by ziayamin** [comment]
laravel8:
composer require -w tymon/jwt-auth --ignore-platform-reqs

composer.json:
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4.1",
        "fruitcake/laravel-cors": "^2.0.3",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/passport": "^10.0",
        "laravel/tinker": "^2.5|dev-develop",
        "paragonie/random_compat": "2.*",
        "tymon/jwt-auth": "^1.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

**Comment by Sainath470** [comment]
but i am getting error while generating the token

**Comment by Nicolas-yonedA** [comment]
Now, jwt-auth is installable with PHP8.0  on version `dev-develop`.

```
composer require tymon/jwt-auth:"dev-develop"
```

**Comment by AD-Amlas** [comment]
@Nicolas-yonedA Thanks .. it worked for me

**Comment by gustavodsv** [comment]
> @Ekenzy-101 You can add `--ignore-platform-reqs` to force install it works well for me.
> 
> `composer require tymon/jwt-auth --ignore-platform-reqs`

Great!! ty

**Comment by ankitasen187** [comment]
I am facing some issues while installation , i am using laravel/laravel (v9.0.1)


composer require -w tymon/jwt-auth --ignore-platform-reqs
Using version ^1.0 for tymon/jwt-auth
./composer.json has been updated
Running composer update tymon/jwt-auth --with-dependencies
Loading composer repositories with package information
Dependency "laravel/framework" is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies.
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tymon/jwt-auth[dev-develop, 1.0.1, ..., 1.0.2] require illuminate/auth ^5.2|^6|^7|^8 -> found illuminate/auth[v5.2.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, 
v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tymon/jwt-auth[1.0.0-alpha1, ..., 1.0.0-alpha.2] require illuminate/auth 5.1.* || 5.2.* -> found illuminate/auth[v5.1.1, ..., 5.2.x-dev] but these were not 
loaded, likely because it conflicts with another require.
    - tymon/jwt-auth[1.0.0-alpha.3, ..., 1.0.0-beta.1] require illuminate/auth 5.1.* || 5.2.* || 5.3.* -> found illuminate/auth[v5.1.1, ..., 5.3.x-dev] but these 
were not loaded, likely because it conflicts with another require.
    - tymon/jwt-auth[1.0.0-beta.2, ..., 1.0.0-beta.3] require illuminate/auth 5.1.* || 5.2.* || 5.3.* || 5.4.* -> found illuminate/auth[v5.1.1, ..., 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tymon/jwt-auth 1.0.0-rc.1 requires illuminate/auth 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* -> found illuminate/auth[v5.1.1, ..., 5.5.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tymon/jwt-auth 1.0.0-rc.2 requires illuminate/auth 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.* -> found illuminate/auth[v5.1.1, ..., 5.6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tymon/jwt-auth 1.0.0-rc.3 requires illuminate/auth 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.* || 5.7.* -> found illuminate/auth[v5.1.1, ..., 5.7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tymon/jwt-auth[1.0.0-rc.4, ..., 1.0.0-rc.4.1] require illuminate/auth ^5.1 -> found illuminate/auth[v5.1.1, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tymon/jwt-auth[1.0.0-rc.5, ..., 1.0.0-rc.5.1] require illuminate/auth ^5.1|^6 -> found illuminate/auth[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tymon/jwt-auth 1.0.0 requires illuminate/auth ^5.2|^6|^7 -> found illuminate/auth[v5.2.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tymon/jwt-auth 1.0.x-dev is an alias of tymon/jwt-auth dev-develop and thus requires it to be installed too.
    - Root composer.json requires tymon/jwt-auth ^1.0 -> satisfiable by tymon/jwt-auth[1.0.0-alpha1, ..., 1.0.x-dev (alias of dev-develop)].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require tymon/jwt-auth:*" to figure out if any version is installable, or "composer require tymon/jwt-auth:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by ramandamaulana** [comment]
Now, jwt-auth is installable with PHP8.0 on version dev-develop.

composer require tomfordrumm/jwt-auth:dev-develop

**Comment by jdbbdj** [comment]
> 



> Now, jwt-auth is installable with PHP8.0 on version dev-develop.
> 
> composer require tomfordrumm/jwt-auth:dev-develop

This was a great answer @March32022

**Comment by lucianobargmann** [comment]
This package is dead and abandoned. Use  tomfordrumm/jwt-auth

**Comment by AhmedMub** [comment]
If you are using Laravel 9 to use JWT-auth you should use php-open-source-saver/jwt-auth it is forked of tymondesign/jwt-auth, because tymondesign/jwt-auth appears to have been abandoned and isn’t compatible with Laravel 9.

`composer require php-open-source-saver/jwt-auth
`

I suggest using sanctum instead it's lightweight, newer, more robust, and easier to implement.
