### ISSUE TITLE
tenant()->getTenantKey() is null

### ISSUE THREAD

**Issue by brandonellis** [tymondesigns/jwt-auth#2089]
### getTenantKey() during Token check is null?
After generating a token and hitting the impersonate route in your documentation the response causes a 500. In your UserImpersonation.php code we have a condition that is never matched. 

`if (((string) $token->tenant_id) !== ((string) tenant()->getTenantKey())) {
            abort(403);
` 
This could be an error in routing, maybe, however the docs are fairly short and it seems as though the tenant() function in general is null.  What would cause this?  My central app is a SPA (shouldnt matter) but maybe there is a reason why tenant() is not initiated.

The docs show this route:
`Route::get('/impersonate/{token}', function ($token) {
    return UserImpersonation::makeResponse($token);
});`

I have tried that as well as this route:

`
Route::middleware([
    'api',
    InitializeTenancyByDomainOrSubdomain::class,
])->get('/impersonate/{token}', 'ImpersonationController@impersonate');`

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no 
| Framework         | Laravel 
| Framework version | 8.x.y
| Package version   | 1.0.2
| PHP version       | 7.4

### Steps to reproduce
1. Generate a Token using impersonate().
2. Request access to tenant hitting tenant route which checks token.
3. Receive 500 as tenant->getTenantKey() is null

### Expected behaviour
Successful UserImpersonation as Tenant

### Actual behaviour
500 Error.

**Comment by njenga55** [comment]
@brandonellis did you manage to resolve this?

**Comment by brandonellis** [comment]
It's been awhile so I am digging through some of the changes that I did:

1.  Check your cors.php file and make sure the paths option is set to allow your path:

`'paths' => ['api/*', 'impersonate/*']`
2. In the controller that handles your impersonation make sure that your Tenant model is capable of finding the appropriate tenant you are looking to impersonate.

`public function impersonate(Request $request, $tenant_id)
    {
        $tenant = Tenant::find($tenant_id);

        $user = $tenant->run(function () {
            $value = 'owner';

            return User::with(['roles'])->whereHas('roles', function ($q) use ($value) {
                // Query the name field in status table
                $q->where('name', '=', $value); // '=' is optional
            })->first();
        });

        $auth_controller = new AuthController;

        //Does this need to be ran in tenant context?
        $token = $auth_controller->impersonate($user);

        //@todo Here we now need to impersonate the user and return the JWT tokens to client.
        return response()->json($token, 200);

    }
    
    3.  Your Authcontroller should look something like this:
    
    /**
     * Get impersonation JWT credentials.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function impersonate($user)
    {
        if (!$token = Auth::login($user)) {
            return response()->json(['error' => 'Unauthorized'], 401);
        }

        return $this->createNewToken($token);
    }
    
    4.  In your routing file, mine for tenants is called tenants.php Your route should look something like this:
    
    /* User Impersonation (ADMIN) */
Route::middleware([
    'api',
    InitializeTenancyByDomainOrSubdomain::class,
    PreventAccessFromCentralDomains::class,
])->prefix('api/central/impersonate')->group(function ($router) {
    Route::post('/', 'ImpersonationController@impersonate');
});
`

Hope this helps.. I haven't worked on this portion in over a year and a half but maybe it will get you unblocked.
