### ISSUE TITLE
Example / More doc

### ISSUE THREAD

**Issue by Foxandxss** [tymondesigns/jwt-auth#21]
Hello, as I said before (on twitter), really nice library, does much much more than simply encoding / decoding tokens which is nice, but that leaves more questions in the air, more for me that I just got started with Laravel.

I see that your implementation is very tight to a model (that is not bad eh!), I guess that the `UserInterface` is the contract needed to make it work.

My question is, what should we do with the `User` model itself? I know `Laravel` comes with one but I don't think that `User` can be used with this library, can it? I guess we need to create one, with our own fields (with some needed fields I guess) and then inherit from this library's `UserInterface`.

So I ask for an example of an app with a basic API (register/login endpoints and a dummy protected route). The example could wait until you release `0.4` (I am not in a hurry, still learning Laravel).

You can also add a `User` model example on the README with what the library expects and everybody's happy.

Cheers, keep the good work.

PD: I plan a Laravel + JWT + Angular article for my blog, I thought about creating a minimum JWT implementation, but I am starting to understand this library and I like it.

**Comment by Foxandxss** [comment]
To not open a new issue, is there any ETA for the new version? Will it come with L5 support? (I check your commits regularly and I think you decided to postpone the L5 support).

Now with L5 around the corner, I would like to do that article :+1:

**Comment by tymondesigns** [comment]
Ok, so to clarify.. I will be removing the laravel 5 specific stuff from the `0.4` release asap, as I think it needs to be it's own release, which will be `0.5` as there are lots of changes relating to how package development can be done, amogst other things.

So going forward, I have almost completed development on the 0.4 release, and once I am happy with that, then I will port it over to laravel 5 straight away. In-fact I have just pulled down the latest laravel 5 code, so I can have a play around with integrating with package, and working out any kinks.

To give you an ETA, My best estimate would be within the next several days for the main `0.4` (laravel `4.*` compatible) release, and then not too long afterwards, will be the `0.5` (laravel 5 compatible) release. I may even get them both done together, but we'll see about that.

I hope that helps clear things up :smile: and I look forward to your article, once I knuckle down and get these releases boxed off!

**Comment by Foxandxss** [comment]
I see, thank you. I am also looking forward for that article. I am afraid that I sold the `JWT` idea a lot on the IRC (angular) and a couple or laravel users are expecting me to write an article about how to combine both :P

**Comment by tymondesigns** [comment]
Good stuff, of course I'll be available to offer any assistance if needed :+1:

**Comment by tymondesigns** [comment]
this post might prove useful http://www.toptal.com/web/cookie-free-authentication-with-json-web-tokens-an-example-in-laravel-and-angularjs
