### ISSUE TITLE
Class tymon.jwt.auth does not exist

### ISSUE THREAD

**Issue by whoishoward** [tymondesigns/jwt-auth#210]
I just follow the instruction, but I got this error.

```
{"message":"Class tymon.jwt.auth does not exist","code":-1,"status_code":500}
```

this is the code I use.
```php
public function authenticate(Request $request)
    {
        // grab credentials from the request
        $credentials = $request->only('email', 'password');

        try {
            // attempt to verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->json(['error' => 'invalid_credentials'], 401);
            }
        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return response()->json(['error' => 'could_not_create_token'], 500);
        }

        // all good so return the token
        return response()->json(compact('token'));
    }
```

I just search this error in my project and I can't fix that:(  plz help me

Also, when I tried php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
It says: Nothing to publish for tag [].
And I tried:--tag=config, --tag="config"
I got same tips.

**Comment by Destreyf** [comment]
This is caused by a missing setup in the setup, i had the same issue with "Nothing to publish for tag []" it ended up being that my app config needed this in the service provider section.

```PHP
Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,
```
After adding that, running 
```bash
php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
```
worked, and my code worked with it.
