### ISSUE TITLE
getting authed jwt user in another middlleware laravel

### ISSUE THREAD

**Issue by parmonov98** [tymondesigns/jwt-auth#2100]
### Subject of the issue
I'm using jwt. I created the middleware for jwt, and created another one isRecruiterAdmin.

in the jwt middlreware everything works well.

When I wanna get authed user in inner middleware, I get null. both haven't worked. why ? and how can I fix this?

I have tried `$request->user()` too. but no success.

An interesting part is when the route is store, the issue exists. on get it works well.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| Framework         | Laravel 8.0
| Framework version | 8.12
| Package version   | dev-develop
| PHP version       | 7.4

### Steps to reproduce
https://stackoverflow.com/questions/66173104/getting-authed-jwt-user-in-another-middlleware-laravel

### Expected behaviour
I wanna check if the authed user is recruiterAdmin. 

### Actual behaviour
return null or false.

**Comment by JeroenvdV** [comment]
Have you checked your `$middlewarePriority`?

**Comment by parmonov98** [comment]
> Have you checked your `$middlewarePriority`?

I don't see the var in no place. where  is it? or you mean prioriting by lining up& down in kernel.php?

**Comment by parmonov98** [comment]
```
use JWTAuth;
use JWTException;

try {
            // $user = JWTAuth::parseToken()->authenticate();
            $user = JWTAuth::parseToken()->toUser();
        } catch (JWTException $e) {

            // echo $e->getMessage();

            return response()->json(
                [
                    'status' => 'error',
                    'error' => ['message' => $e->getMessage()]
                ],
                404
            );
        }

        $message = __('You are not recruiter-admin');
```
