### ISSUE TITLE
decrypt_cookies is not working with EncryptCookies Middleware.

### ISSUE THREAD

**Issue by chrisLeeTW** [tymondesigns/jwt-auth#2107]
### Subject of the issue
Currently is always got unauthorized if decrypt_cookies = true and also use EncryptCookies Middleware.

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              | yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 8.x
| Package version   | 1.0.2
| PHP version       | 7.4

### Steps to reproduce
1. set `decrypt_cookies = true` in config/jwt.php
2. make sure you use EncryptCookies middleware in `app/Http/Kernel.php`
3. try to authorize with cookie

### Expected behaviour
authorized

### Actual behaviour
unauthorized

**Comment by chrisLeeTW** [comment]
After some research, It's looks like there are two problems for this issue.

1. EncryptCookies Middleware default is encrypted without serialize.
2. Due to security issue ([link](https://blog.laravel.com/laravel-cookie-security-releases)), now Laravel will add some random hashed prefix in front of original cookie value before encrypt, so just simplelly use `Crypt::decrypt` will not got correctly jwt token.

**Comment by dimensionentropy** [comment]
Hi there,

`EncryptCookies` [decrypts](https://github.com/laravel/framework/blob/d786e741e15ad1afa723cef19f05dabc040be912/src/Illuminate/Cookie/Middleware/EncryptCookies.php#L65) cookies before parsing the token stored in a cookie, so you can set `decrypt_cookies` to false.

1. Neither does `EncryptCookies`'s decryption unserialize.
2. `EncryptCookies`'s [decrypt()](https://github.com/laravel/framework/blob/d786e741e15ad1afa723cef19f05dabc040be912/src/Illuminate/Cookie/Middleware/EncryptCookies.php#L76) removes the prefix!

Hope this helps.

**Comment by chrisLeeTW** [comment]
@Jimmy1244

1. EncryptCookies Middleware do not have options to turn off cookie prefix.
2. I do know I can turn off by set `decrypt_cookies` to false, but I need encryption for security purpose.

I know these issue is related the fundamental architecture for Parser that can not easily fixed.

So in the end, I've removed usage of EncryptCookies Middleware, and decrypt the cookie value by self.
