### ISSUE TITLE
Octane compatible?

### ISSUE THREAD

**Issue by Stunext** [tymondesigns/jwt-auth#2113]
Is this compatible with Laravel Octane

**Comment by pablorsk** [comment]
Not yet. But you can do something...

### First you need this library compatible with PHP8. Add this to your `composer.json`
```
    "dees040/jwt-auth": "1.0.3"
```
OR [use jwt-auth dev-branch](https://github.com/tymondesigns/jwt-auth/issues/2124#issuecomment-843686362)

### Second, add a prepare class for each octane request:

```octane.php```:

```php
        RequestReceived::class => [
            ...Octane::prepareApplicationForNextOperation(),
            ...Octane::prepareApplicationForNextRequest(),
            \App\RestartJwtFacades::class
        ],
```

```RestartJwtFacades.php```:

```php
namespace App;

use Laravel\Passport\Passport;
use Tymon\JWTAuth\Facades\JWTAuth;
use Tymon\JWTAuth\Facades\JWTFactory;
use Tymon\JWTAuth\Facades\JWTProvider;
use Tymon\JWTAuth\JWT;

class RestartJwtFacades
{
    public function handle($event): void
    {
         JWTAuth::clearResolvedInstances();
         JWTFactory::clearResolvedInstances();
         JWTProvider::clearResolvedInstances();
    }
}

```

**Comment by klipitkas** [comment]
> Not yet. But you can do something...
> 
> ### First you need this library compatible with PHP8. Add this to your `composer.json`
> ```
>     "dees040/jwt-auth": "1.0.3"
> ```
> 
> OR [use jwt-auth dev-branch](https://github.com/tymondesigns/jwt-auth/issues/2124#issuecomment-843686362)
> 
> ### Second, add a prepare class for each octane request:
> `octane.php`:
> 
> ```
>         RequestReceived::class => [
>             ...Octane::prepareApplicationForNextOperation(),
>             ...Octane::prepareApplicationForNextRequest(),
>             \App\RestartJwtFacades::class
>         ],
> ```
> 
> `RestartJwtFacades.php`:
> 
> ```
> namespace App;
> 
> use Laravel\Passport\Passport;
> use Tymon\JWTAuth\Facades\JWTAuth;
> use Tymon\JWTAuth\Facades\JWTFactory;
> use Tymon\JWTAuth\Facades\JWTProvider;
> use Tymon\JWTAuth\JWT;
> 
> class RestartJwtFacades
> {
>     public function handle($event): void
>     {
>          JWTAuth::clearResolvedInstances();
>          JWTFactory::clearResolvedInstances();
>          JWTProvider::clearResolvedInstances();
>     }
> }
> ```

This is a very interesting approach, however currently it is not working.

**Comment by mfn** [comment]
I suggest to contribute to the fork, we've an issue regarding Octane in general that repo is more active: https://github.com/PHP-Open-Source-Saver/jwt-auth/issues/72
