### ISSUE TITLE
Authenticate a Model by it's foreign key from a token without changing the primary key

### ISSUE THREAD

**Issue by Gummibeer** [tymondesigns/jwt-auth#212]
We got a problem - the authenticate function calls the ```byId()``` method so it ignores the _jwt.identifier_ config setting. It would be better if this function looks in the identifier column for the given sub and not fixed in the primary key column.

```php
if (! $this->auth->where(config('jwt.identifier'), $id)->first()) {
    return false;
}
```

**Comment by tymondesigns** [comment]
You could always implement your own Auth provider and query any field you like under the `byId()` method. That make sense?
