### ISSUE TITLE
Exceptions instead of json response

### ISSUE THREAD

**Issue by Gummibeer** [tymondesigns/jwt-auth#213]
It would be nice if you can throw an Exception instead of response with a json cause exception can get handled by the app developer and after that he can response with a json, error page or whatever he want.
It's better for debug, loging and render. You don'T know how i want to handle the exceptions. We wrote our own RestApi Response macro and use this inside the exception handler to format every exception we want it and how our documentation says and our frontend expects it.

**Comment by tdhsmith** [comment]
The responses all come from the default middleware, which also catches and unsets the exceptions. The middleware is completely optional, and the rest of the package entirely uses exceptions, so all you need to do is write your own middleware.

**Comment by tdhsmith** [comment]
You can even take the existing [`GetUserFromToken`](https://github.com/tymondesigns/jwt-auth/blob/master/src/Middleware/GetUserFromToken.php) script and tear out the `catch` clauses and add some new exceptions where the `token_not_provided` and `user_not_found` responses are, and you're basically done. :smiley:

**Comment by Gummibeer** [comment]
Ok, thank you. I will have a look.
