### ISSUE TITLE
Date values should be numeric

### ISSUE THREAD

**Issue by pfazzino** [tymondesigns/jwt-auth#214]
Taking **exp** as an example, from the spec 

*Its value MUST be a number containing a NumericDate value (see https://tools.ietf.org/html/rfc7519#page-9).*

Currently these are returned as strings in the token which causes a problem for certain jwt client libs which explicitly parse these as numerics.

**Comment by lkoenigsberger** [comment]
Thats already merged into develop but not released yet. #166

**Comment by pfazzino** [comment]
thanks
