### ISSUE TITLE
jsonSerialize() should either be compatible with JsonSerializable: :jsonSerialize()

### ISSUE THREAD

**Issue by dankerizer** [tymondesigns/jwt-auth#2162]
### Subject of the issue
Return type of `Tymon\JWTAuth\Claims\Claim: :jsonSerialize() should either be compatible with JsonSerializable: :jsonSerialize(): mixed, or the #[\ReturnTypeWillChange
] attribute should be used to temporarily suppress the notice `

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no 
| Framework         | Lumen
| Framework version | 8.3.4
| Package version   | dev-develop
| PHP version       | 8.1.2

### Actual behaviour
```
<br />
<b>Deprecated</b>:  Return type of Tymon\JWTAuth\Claims\Claim: :jsonSerialize() should either be compatible with JsonSerializable: :jsonSerialize(): mixed, or the #[\ReturnTypeWillChange
] attribute should be used to temporarily suppress the notice in <b>/Applications/MAMP/htdocs/..../vendor/tymon/jwt-auth/src/Claims/Claim.php</b> on line <b>147</b><br />
```

**Comment by mfn** [comment]
This library hasn't had maintainer activity in 2 years.

https://github.com/PHP-Open-Source-Saver/jwt-auth is community made fork of this library and the latest release https://github.com/PHP-Open-Source-Saver/jwt-auth/releases/tag/1.4.1 fixes it.

It's _mostly_ a drop-in, the details are documented at https://github.com/PHP-Open-Source-Saver/jwt-auth/tree/1.4.1#migrating-from-tymondesignsjwt-auth

HTH

**Comment by dankerizer** [comment]
Thank you @mfn
