### ISSUE TITLE
Custom JWT as per documentation - requiring User

### ISSUE THREAD

**Issue by zerojargon** [tymondesigns/jwt-auth#217]
I'm trying to build a custom JWT as per the documentation in the wiki.

If I do the following:

    $payload = JWTFactory::make(['sub' => url()]);
    $token = JWTAuth::encode($payload);

Then I get the error

    Class App\User does not exist

the project in question doesn't require / use a User model, and I'm using JWT-auth just to generate the JWT, not to authenticate (on this service at least)?

Any ideas on how I can get around this?

**Comment by tdhsmith** [comment]
I haven't tested it yet, but it looks like this was already changed on the develop branch:  945024d087deea8e2c46324d20cc44d6ea41e54c (`removing User Provider`). Try installing with composer version to `dev-master` and see if that fixes it?

**Comment by tdhsmith** [comment]
Ok, I tried it out and it does work, but the format for `JWTFactory::make` changed slightly on the develop branch. Now you'll need something like this:

```php
// standard way..
$payload = JWTFactory::customClaims(['sub' => url()])->make();

// ...or using magic methods
$payload = JWTFactory::sub(url())->make();
```

Slight tangent, but while these changes are being discussed: @tymondesigns, will package users be expected to implement the `JWTSubject` interface on their user models, or is there some mechanism to automatically fill in sane defaults (e.g. model id and no custom claims)?

**Comment by tymondesigns** [comment]
Yep, lots of changes coming in the new release! For the better I think.

@tdhsmith yes, it will be required to implement the interface.. I don't think it wouldn't be possible right now to have fallbacks, since various methods require an instance of said interface. However, I think I'll be adding a trait which would have defaults in there.

**Comment by tymondesigns** [comment]
Think it should be possible to create a token without a user. But I will need to double check

**Comment by zerojargon** [comment]
Looking forward to the new version :)

If you could check that, it'd be great! I realise the main functionality of the application is for auth, but using the same API for non-user-based services as well would be awesome.
