### ISSUE TITLE
Using VerifyCsrfToken gives 500 error

### ISSUE THREAD

**Issue by tommy7600** [tymondesigns/jwt-auth#221]
Hi,
I'm adding JWT to existing project. Is there any good solution to work with this package and with VerifyCsrfToken middleware? For now I commented it out.

**Comment by kylestev** [comment]
For routes that use a JWT for authentication, there is no need for CSRF tokens if you are following best practices -- i.e. [make sure your `GET` requests are idempotent](http://restcookbook.com/HTTP%20Methods/idempotency/). CSRF tokens are generally used when your authentication is stateful (read: cookies, php sessions, etc.).

See this answer on StackOverflow for more information: https://stackoverflow.com/a/25198454/758310

**Comment by tommy7600** [comment]
I used this answer: https://laracasts.com/discuss/channels/laravel/laravel-51-disable-session-and-cookies-for-some-routes
