### ISSUE TITLE
Fatal error: Call to undefined method Closure::__set_state() 

### ISSUE THREAD

**Issue by astroanu** [tymondesigns/jwt-auth#224]
When i run artisan config:cache i get this. Without caching it works well

```
Fatal error: Call to undefined method Closure::__set_state() in xxxxxxx\bootstrap\cache\config.php on line 316
```

this is what my cached config file looks like around line 316

```
  'jwt' => 
  array (
    'secret' => 'w6VA4fm0SlaS7TBBpHxpQ6SUsimTKnOx',
    'ttl' => 60,
    'refresh_ttl' => 20160,
    'algo' => 'HS256',
    'user' => 'App\\User',
    'identifier' => 'id',
    'required_claims' => 
    array (
      0 => 'iss',
      1 => 'iat',
      2 => 'exp',
      3 => 'nbf',
      4 => 'sub',
      5 => 'jti',
    ),
    'blacklist_enabled' => true,
    'providers' => 
    array (
      'user' => 'Tymon\\JWTAuth\\Providers\\User\\EloquentUserAdapter',
      'jwt' => 'Tymon\\JWTAuth\\Providers\\JWT\\NamshiAdapter',
      'auth' => 
      Closure::__set_state(array(
      )),
      'storage' => 
      Closure::__set_state(array(
      )),
    ),
  ),
```

**Comment by kylestev** [comment]
duplicate of #147

This is an issue with Laravel and it will not be fixed: https://github.com/laravel/framework/issues/9625#issuecomment-121339093

There is a workaround to get this package to work with Laravel's config caching if you take the config from the development branch. Take a look at this reply: https://github.com/tymondesigns/jwt-auth/issues/147#issuecomment-123103861

**Comment by astroanu** [comment]
That did the fix, however default config.php of this repo should not use closures then.

**Comment by kylestev** [comment]
Agreed. There hasn't been a release of the package with the new config yet, unfortunately.

**Comment by Desto1998** [comment]
Remove the **/bootstrap/cache/config.php** and run _PHP artisan vendor:publish_ instead of PHP artisan optimize, 
This worked for me

**Comment by connectwithfiroz** [comment]
Try to delete the **/bootstrap/cache/route-v7.php** file.
