### ISSUE TITLE
Laravel 11 Compatibility needs nesbot/carbon ^3.0

### ISSUE THREAD

**Issue by RBFraphael** [tymondesigns/jwt-auth#2246]
### Subject of the issue
Can't require tymon/jwt-auth on fresh Laravel 11 install

### Your environment
| Q                 | A
| ----------------- | ---
| Bug?              |  yes
| New Feature?      | no
| Framework         | Laravel
| Framework version | 11.0.1
| Package version   | 2.1.0
| PHP version       | 8.2.16

### Steps to reproduce
Create a new Laravel 11 project (through `composer create-project laravel/laravel` or via Laravel installer), then try to require tymon/jwt-auth (`composer require tymon/jwt-auth`)

### Expected behaviour
The JWT Auth package is expected to be installed normally

### Actual behaviour
It shows version compatibility error with nesbot/carbon, which is used in version 2 in tymon/jwt-auth and 3 in Laravel 11.

### Additional Notes
I've tried just to add the ^3.0 version tag on composer.json of the jwt-auth package, using my own fork of the project, at https://github.com/RBFraphael/jwt-auth , and it worked like a charm. So, it only needs to have the ^3.0 version tag on nesbot/carbon dependency on composer.json . Sorry for not "only" openning a new pull request, but I'm not too experienced with pull requests yet.

**Comment by tymondesigns** [comment]
New release tagged!
