### ISSUE TITLE
Could not create token: The algorithm 'ECDSA' is not supported for OpenSSL

### ISSUE THREAD

**Issue by kennyyap92** [tymondesigns/jwt-auth#225]
Dear all, I would like to check if anyone is facing any issue when creating a token and being prompt with not supported algorithms? I have tried with the base algo HS256, HMAC, ECDSA and all return me with invalid algorithm. 

I also have a running question in [stackoverflow](http://stackoverflow.com/questions/32175890/php-jwt-algorithm-is-not-supported-for-openssl) on the related issue. Hopefully someone can help me.

**Comment by tdhsmith** [comment]
Hrm, that error is stemming from within Namshi/JOSE, specifically [`JWS->getSigner()` on line 189](https://github.com/namshi/jose/blob/master/src/Namshi/JOSE/JWS.php#L189). That seems to indicate that it can't find the class `Namshi\JOSE\Signer\OpenSSL\ECDSA`, despite that it's [included with the package](https://github.com/namshi/jose/blob/master/src/Namshi/JOSE/Signer/OpenSSL/ECDSA.php). 

I'm kind of stupid when it comes to class visibility stuff, but have you tried running a `composer dump-autoload`?

**Comment by tymondesigns** [comment]
looking at your SO post, it appears you trying to use `HMAC`. 

The reason you get the error is becuase it is an abstract class, and so is `ECDSA` in fact.

You would need to use the algorithms that extend those sub classes, e.g. `ES256` and `HS256`.

Maybe try HS256 again. Seems weird that wouldn't work for you
