### ISSUE TITLE
Class jwt-auth does not exist

### ISSUE THREAD

**Issue by ken8203** [tymondesigns/jwt-auth#229]
Hello,

I put 'jwt.auth' in the middleware of api's controller like:
```
$this->middleware('jwt.auth');
```

But when I request the api, I got an error:
```
ReflectionException in Container.php line 779:
Class jwt-auth does not exist
```

I've modified  `Kernel.php`. Did I miss any configuration?

Thanks a lot!

**Comment by tdhsmith** [comment]
Did you add `'Tymon\JWTAuth\Providers\JWTAuthServiceProvider'` to your providers array in app.php?  (bottom of first section on the [installation page](https://github.com/tymondesigns/jwt-auth/wiki/Installation))

**Comment by digitlimit** [comment]
I am having same issue. I have added Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class to config/app.php, still same issue

**Comment by tdhsmith** [comment]
Have you run the command `composer dump-autoload` since making the changes? It's often necessary to update the classmap.

**Comment by digitlimit** [comment]
@tdhsmith thanks for responding. Dough I am using Laravel 5.1 I have done composer dump-autoload severally but issue persists

**Comment by SuperlativeEntity** [comment]
In app\Http\Kernel.php

Have you added this to the route middleware?

'jwt.auth'      => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
'jwt.refresh'   => \Tymon\JWTAuth\Middleware\RefreshToken::class,

**Comment by digitlimit** [comment]
Yes it's working now. Thanks. The issue is I was using jwt-auth instead of jwt.auth .. I think jwt-auth  is for laravel 4.

**Comment by NorthWish** [comment]
I encountered the same problem, I ask you how to solve it

**Comment by koofah** [comment]
thanks , it is now working like magic

**Comment by jaymoh** [comment]
@SuperlativeEntity you just me from crushing my laptop...

**Comment by devtosystems** [comment]
`JWTAuthServiceProvider` is now `Tymon\JWTAuth\Providers\LaravelServiceProvider::class,` and `GetUserFromToken` is not found.

Can you help me please?

**Comment by sumer5020** [comment]
In app.php add this `Tymon\JWTAuth\Providers\LaravelServiceProvider::class,`

also you can add this aliases
```
'JWTAuth' => Tymon\JWTAuth\Facades\JWTAuth::class,
'JWTFactory' => Tymon\JWTAuth\Facades\JWTFactory::class,
```
use in controller `$this->middleware('auth:api')->except('login','register');`
