### ISSUE TITLE
bcrypted password

### ISSUE THREAD

**Issue by francoismart** [tymondesigns/jwt-auth#232]
Hello
For a mobile app, I would like to store the password as bcrypted inside Keychain to avoid sending in plain text (even over https) on first attempt to login. I say bcrypt because inside laravel I can see the user's password creation is bcrypt($data['password']).
So now inside AuthController, you propose to use : 
if (! $token = JWTAuth::attempt($credentials)) {
...
} I suppose JWT uses Auth but how could we say to JWT to authenticate against  stored encrypted password ?
I'm not sure if laravel's hash function uses the app key also 
Any help appreciated

**Comment by photoart-mtlwebdev** [comment]
Hi,

I'm facing the same problem here with Laravel 5.1.

I've migrated my users with bcrypt() first, and then I tried with Hash::make().
The JWT::attempt() method fails and I get the "401 invalid_credentials" exception in both cases.

Any clue on this issue ?
Thanks a lot.

**Comment by francoismart** [comment]
i will never store the password
i will never store the password
i will never store the password
i will never store the password
i will never store the password
.....
