### ISSUE TITLE
Blacklist issue

### ISSUE THREAD

**Issue by Murwa** [tymondesigns/jwt-auth#233]
Guys, I just ran into this after updating
>Argument 1 passed to Tymon\JWTAuth\Blacklist::__construct() must be an instance of Tymon\JWTAuth\Contracts\Providers\Storage, instance of Closure given

**Comment by tymondesigns** [comment]
Which version?

**Comment by Murwa** [comment]
Dev

**Comment by tdhsmith** [comment]
Did you re-publish the configs? If not, you may still have an old copy (which uses closures in the provider settings).

**Comment by tymondesigns** [comment]
yea that will be it I think

**Comment by Murwa** [comment]
Yep, working thanks!
