### ISSUE TITLE
How to pass token from client to server on ajax requests and regular page requests

### ISSUE THREAD

**Issue by ghost** [tymondesigns/jwt-auth#234]
Hi everyone,

I'm trying to implement this amazing package in my app but I'm having a hard time figuring out how to handle both ajax requests and full page requests.

Let me explain the situation:
I have a Laravel 5.1 based Rest API that handles authentication against a MySQL database.
I'm successfully generating and returning tokens. It resides at https://api.domain.com
I properly protect some routes with the provided middlewares.

On the other end of the wire I have a Laravel 5.1 web app that authenticates against the API above via an ajax request triggered from a login form. It resides at http://consumer.domain.com

The web app renders public views and data to everyone, but should also provide restricted data, views and features to authenticated users. This app isn't a SPA but sometimes triggers some ajax calls to enhance UX.
Here comes to problem, I don't know where to store the token (cookie or localstorage) as I need to provide it in cross-domain ajax request headers as well as on full page requests.
I'm aware of different security concerns (CSRF, XSS) and know how to deal with them.

The full page requests will hit the web app that might itself call the API (with Curl or Guzzle), but the ajax requests directly call the API.

On a public page (that is rendered through a full page request) I'd like to display different call to action buttons depending on whether the user is logged in or not, but how can the web app know that the user has been granted a token ?
The token might transit through the Laravel web app (with a cookie for example so it can then be provided to a Guzzle call to the API) but the web app won't be able to read it as it has been delivered by the API and only it can decode it.

In the next few weeks, there will also be an iOS and Android app connecting to this API.

I don't know if this makes sense as my English can be approximate sometimes, but I've been trying to figure that out for 2 month now, so if someone gets it and could point me the right direction, that would be really appreciated. Thanks.

**Comment by rginnow** [comment]
@tymondesigns

This user has been deleted & the question is outdated. Suggest cleaning up and closing some of these super old issues.

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
