### ISSUE TITLE
0.4.* Package refreshFlow issue.

### ISSUE THREAD

**Issue by Gielert** [tymondesigns/jwt-auth#235]
When I tried to refresh an expired token that was within the refresh_ttl time, it still gave me an expired token exception. After some digging I found out that when a refresh occured that the refreshFlow on the decode was not set. I don't know if this was meant to be, but I fixed it by editing JWTManager.php on line 63, 67 and 84

```php
//JWTManager.php
public function decode(Token $token, $refreshFlow = false)
    {
        ...
        $payload = $this->payloadFactory->setRefreshFlow($refreshFlow)->make($payloadArray);
        ...

public function refresh(Token $token)
    {
        $payload = $this->decode($token, true);
        ...

**Comment by nivv** [comment]
I have the same issue. This seems to fix it :+1:

**Comment by tymondesigns** [comment]
Sorry guys, I don't have time to support laravel 4 I'm afraid

**Comment by olivernagy** [comment]
In case someone still has to deal with Laravel 4 like I do, the following workaround seemed to have fixed this issue:
```
$currentToken = JWTAuth::getToken();
JWTAuth::manager()->getPayloadFactory()->setRefreshFlow();
$token = JWTAuth::refresh($currentToken);

return Response::json(compact('token'));
```

It sets the `refreshFlow` on the `PayloadFactory` before even starting to refresh the token, fixing the validation in `decode`.
