### ISSUE TITLE
Same as \Auth::guest() or \Auth::user()

### ISSUE THREAD

**Issue by pavankumarkatakam** [tymondesigns/jwt-auth#237]
In normal laravel application we can check the user is guest or logged in by using \Auth::guest() and \Auth::user(), is there any same functionalities in this lib like \Jwt::guest() and \Jwt::user(). if not can we implement this function by own. please tell me.

**Comment by jlien-calwater** [comment]
@pavankumarkatakam this is already built in.

https://github.com/tymondesigns/jwt-auth/wiki/Configuration#user-model-path---user

If you have name the User model differently you can update it in the jwt.php configuration.

![image](https://cloud.githubusercontent.com/assets/3473846/9919222/49afe72e-5c80-11e5-90ba-53262edead36.png)

To retrieve the authenticated user after logging.

```php
// somewhere in your controller
public function getAuthenticatedUser()
{
    try {

        if (! $user = JWTAuth::parseToken()->authenticate()) {
            return response()->json(['user_not_found'], 404);
        }

    } catch (Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {

        return response()->json(['token_expired'], $e->getStatusCode());

    } catch (Tymon\JWTAuth\Exceptions\TokenInvalidException $e) {

        return response()->json(['token_invalid'], $e->getStatusCode());

    } catch (Tymon\JWTAuth\Exceptions\JWTException $e) {

        return response()->json(['token_absent'], $e->getStatusCode());

    }

    // the token is valid and we have found the user via the sub claim
    return response()->json(compact('user'));
}
```

Taken from here: https://github.com/tymondesigns/jwt-auth/wiki/Authentication#retreiving-the-authenticated-user-from-a-token

**Comment by tymondesigns** [comment]
`JWTAuth::user();` has been added to the next release, currently `0.6.*@dev`

**Comment by jlien-calwater** [comment]
@tymondesigns do you have roadmap or timeline on when the next release is going to happen?
