### ISSUE TITLE
Token generated does not have token type ["typ":"JWT"] in the header

### ISSUE THREAD

**Issue by yateeshr12** [tymondesigns/jwt-auth#238]
I followed the usage guide and generated a token after login. I checked token for validity on jwt.io debugger. It said "Invalid Signature" because the jwt header is missing token type [typ : JWT]. Could you tell me where might be the issue?

**Comment by tymondesigns** [comment]
this shouldn't be possible, as seen here - https://github.com/tymondesigns/jwt-auth/blob/develop/src/Providers/JWT/Namshi.php#L36

which version are you running?

**Comment by yateeshr12** [comment]
Running Laravel 5.1

**Comment by tymondesigns** [comment]
Sorry which version of this package

**Comment by yateeshr12** [comment]
It's 0.5.*

**Comment by tymondesigns** [comment]
That really is strange. What code are you using to generate the token?

**Comment by yateeshr12** [comment]
It's JWTauth::fromUser(). I'm passing a user object.

**Comment by pavankumarkatakam** [comment]
Yes, in my case also there is no `typ:jwt` in header part. i just checked the generated token in the [jwt](http://jwt.io/)

**Comment by tymondesigns** [comment]
I will have to dig and try this out myself

**Comment by yateeshr12** [comment]
I found that *typ:jwt is not present in the file named NamshiAdapter.php located at \vendor\tymon\jwt-auth\src\Providers\JWT\ . Only 'alg' => $algo is present. The version I installed is " 0.5.* " for Laravel 5.1

**Comment by tymondesigns** [comment]
ah yes, you are right, looks like this this was somehow left in. 

It's fixed now in version `0.5.5`
