### ISSUE TITLE
Token is immediately expired?

### ISSUE THREAD

**Issue by toddrimes** [tymondesigns/jwt-auth#24]
Not sure what I'm doing wrong.  Been using this great package for about two weeks, but today, the token it issues on login is immediately throwing an "expired" Exception when I next try

    $decode = JWTAuth::decode($token);

It seems like I'm using it the same way I have been.  What could I be doing wrong?

Thank you,
~Todd

**Comment by joearcher** [comment]
@toddrimes is this a timezone offset which is only set on MySQL server not the PHP server? If so the timestamps will always be at least 8:00 hours in the past as far as the PHP server is concerned. 

We could do a `SELECT @@global.time_zone, @@session.time_zone;` query to get the MySQL box's timezone offset but is this edge case worth an additional database round trip? Would it not make more sense to ensure that both servers shared the same timezone?

**Comment by toddrimes** [comment]
My PHP server and MySQL server are the same machine, but I gave up on the token long ago.  Is there some way to turn this issue "off"?

**Comment by joearcher** [comment]
Um, mark it as closed?

**Comment by tymondesigns** [comment]
Looks like this is an external issue then
