### ISSUE TITLE
can we invalidate a token when user logout?

### ISSUE THREAD

**Issue by pavankumarkatakam** [tymondesigns/jwt-auth#244]
First of all, thanks to amazing work by @tymondesigns , Im using this package and it is fine, but only one question i want to invalidate token when user logout manually from the UI, so can i use code like this
````
public function logout(){
 \JWTAuth::invalidate();
}
````

So that if anybody who has previous token, if sent to server it will be in the blacklist , so it raises an exception, Am i correct? if not please tell me who to logout a user?

**Comment by pavankumarkatakam** [comment]
And another question is, are you checking the token is in blacklist or not when processing the request. because in code i didn't found any code regarding checking the incoming token is in blacklist or not.

**Comment by tymondesigns** [comment]
Yes you can use the invalidate method to add a token to the blacklist. And that is checked each time a token is decoded.

The code you are looking for is in `Manager.php` in the decode method.

Thanks
