### ISSUE TITLE
How to use refresh token middleware.

### ISSUE THREAD

**Issue by pavankumarkatakam** [tymondesigns/jwt-auth#247]
Im creating a project with laravel and angular, by wiki if we keep refresh token middleware, each token is valid for only one request, but in my angular app there may be 2 or more requests to laravel asyncronusly, in that case what i want to do, but i want to use refresh token to avoid user always authenticating.

**Comment by tdhsmith** [comment]
It sounds like you want to have multi-use tokens, but that would require not refreshing on every request.

> i want to use refresh token to avoid user always authenticating

Why? To avoid querying the DB?

**Comment by pavankumarkatakam** [comment]
I mean, i dont want to show every time login page to user.

**Comment by tdhsmith** [comment]
I'd recommend starting out with this flow then:

1. Use the `GetUserFromToken` middleware on all protected routes.
2. After `ttl` time, this will return `token_expired`.
3. When the client receives `token_expired`, have it connect to a special route (for example, `/refreshToken`) that uses the `RefreshToken` middleware.
4. When the client receives the new token, save it and retry all the failed requests.

This is the main flow the default middleware was designed for. `GetUserFromToken` won't invalidate the current token and won't force the user to login.

**Comment by pavankumarkatakam** [comment]
Yeah, now i understood that we want to make `refresh url` seperatly and make use of it.
