### ISSUE TITLE
Capitalization on Mac throws error of invalid token?

### ISSUE THREAD

**Issue by SeoRoman** [tymondesigns/jwt-auth#248]
Line 215-216 of JWTAuth.php

protected function parseAuthHeader($header = 'Authorization', $method = 'Bearer')
    {
        $header = $this->request->headers->get($header);

       if (! starts_with(strtolower($header), $method)) {
            return false;
        }

        return trim(str_ireplace($method, '', $header));
    }

You drop the header to lowercase, but the $method remains "Bearer" and it is not found in the stack... I added a strtolower() wrapper around $method and the issue was resolved.

Unknown if this is something with MAMP, Apache, Laravel or something else...

**Comment by tymondesigns** [comment]
cannot reproduce this
