### ISSUE TITLE
Use custom url parameter

### ISSUE THREAD

**Issue by marvinosswald** [tymondesigns/jwt-auth#249]
Is it possible to use a custom url parameter as argument to parseToken ?
I'm trying to pass a custom token from laravel to angular to laravel, which has nothing to do with user authentication but is needed to auth a user to claim ownership of an element.

So the endpoint /assignElement gets the Authorization Header and a url parameter called `assignToken`.

Now I just need to decode that `assignToken` to get to my element id

**Comment by tymondesigns** [comment]
The way to do it with the current release would be to pass the relevant params to the `parseToken()` method e.g.

```php
$token = JWTAuth::parseToken('bearer', 'authorization', 'assignToken');`
```

Although note that this will change in the upcoming release
