### ISSUE TITLE
Is there a way to store token in db for more persistent and update ttl every request?

### ISSUE THREAD

**Issue by Deno028** [tymondesigns/jwt-auth#251]

**Comment by tymondesigns** [comment]
This is something you would have to implement yourself, as it goes against the fact that jwt's are meant to be stateless.

Why do you think is this necessary?

**Comment by Deno028** [comment]
Thanks Tymon but I want to store the refresh token in db. How do you think? How can I get the refresh token after login successfully? Thank you!

**Comment by youyi1314** [comment]
Hi @Deno028 ,
You may get the refreshed token from header
![image](https://cloud.githubusercontent.com/assets/8391468/10141680/78ff16a2-6640-11e5-9b91-ba4aea71118a.png)
