### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by villaloboswtf** [tymondesigns/jwt-auth#252]
While implementing JWT in Laravel 5, I was trying to catch exceptions by the not-global way, as documented [here](https://github.com/tymondesigns/jwt-auth/wiki/Authentication), but for some reason, the exceptions were never caught. After research I found out that documentation is missing a backslash, so instead of 
```php
try {
      $user = JWTAuth::parseToken()->toUser();
} catch (Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {
      $user = false;  
} 
```
a backslash is needed before declaring the exception class, so it would become
```php
try {
      $user = JWTAuth::parseToken()->toUser();
} catch (\Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {
      $user = false;  
} 
```

**Comment by tymondesigns** [comment]
Fair point... I will try to make the new wiki more friendly to beginners. Thanks
