### ISSUE TITLE
Invalidation call breaks tests

### ISSUE THREAD

**Issue by rlugge** [tymondesigns/jwt-auth#253]
I'm building up a decent test suite for my app, and I just got around to my logout route.  Unfortunately, the logout route breaks a random selection of my other tests.

	public function logout(){
		$this->authenticate();
		\JWTAuth::Invalidate(\JWTAuth::getToken());
		return response()->json(['status'=>'logged out']);
	}

The route performs properly, but causes my other tests to break.  If I comment out the invalidate call, the route (and it's associate tests) break, but none of the other routes are broken.  Not entirely sure what's up.

My database is being reset between each test using a manual call to migrate:reset in teardown, with migrate called during prepare / setup.

**Comment by tdhsmith** [comment]
How exactly are the other tests breaking?

The Blacklist uses whatever Cache driver you have configured, which defaults to `file`. I'm not sure whether Laravel test cases clear this or not between tests; it's possible there's some data sticking around and you may need to find a way to clean it in your tear down. (If this is true and you're giving tokens with the exact same `jti` claim in later tests, they would flag as invalidated.)

**Comment by rlugge** [comment]
This turned out to be exactly the issue.  Thanks.  Just had to add a call to `Cache::flush();` in my setup method.

**Comment by tymondesigns** [comment]
@rlugge It would be better calling `JWTAuth::getBlacklist()->clear();` to keep the abstraction in place. Meaning you wouldn't have to refactor if you no longer wanted to use laravel's caching system to drive the blacklist

**Comment by rlugge** [comment]
Thanks.  Wish the documentation better covered this and other testing issues!

**Comment by tymondesigns** [comment]
Its coming

**Comment by tdhsmith** [comment]
Ah didn't know about that method; should've poked around Blacklist more. Thanks @tymondesigns!
