### ISSUE TITLE
How can I make it so protected route will continue as usual, if a user is not logged in?

### ISSUE THREAD

**Issue by skcin7** [tymondesigns/jwt-auth#255]
One of my routes is protected with the "jwt.auth" middleware. However, there are circumstances in my app where the route will be accessed by a user that is not logged in. Normally, JWTAuth returns HTTP 400 error with JSON that says "token_not_provided". How can I make it so that the route will continue as usual, if a user is not logged in?

**Comment by skcin7** [comment]
Nevermind. I figured out a solution to this answer, with help from [what mmichaelbiz posted here](https://github.com/tymondesigns/jwt-auth/issues/103).

I added my own middleware to app/Http/Kernel.php:

```
'jwt.check' => 'App\Http\Middleware\JwtCheck',
```

Then, I added the file app/Http/Middleware/JwtCheck.php that mmichaelbiz wrote:

```
<?php

namespace App\Http\Middleware;

class JwtCheck extends \Tymon\JWTAuth\Middleware\GetUserFromToken
{
	/**
	* Handle an incoming request.
	*
	* @param  \Illuminate\Http\Request  $request
	* @param  \Closure  $next
	* @return mixed
	*/
	public function handle($request, \Closure $next)
	{
		if ($token = $this->auth->setRequest($request)->getToken()) {
			try {
				$this->auth->authenticate($token);
			} catch (\Exception $e) {
				unset($e);
			}
		}

		return $next($request);
    }
}
```


Now, I have the 'jwt.check' middleware available whenever I want to check to see if a user is logged in, or continue as a guest.

Tymon, AWESOME WORK with this library. I love it. I think it might be a good idea to add a jwt.guest middleware into the next official version. I'd add it myself and contribute it to this project if only I knew how to do that.

**Comment by tymondesigns** [comment]
`jwt.check` has already been added on the develop branch [here](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Middleware/Check.php)

Thanks for the sentiment :)

**Comment by skcin7** [comment]
Are you planning to add it to the master branch?

I did a 'composer update' but I'm not sure how to get the develop branch version into my project.

**Comment by tymondesigns** [comment]
Afraid not. You can install the dev version by requiring `0.6.*@dev` in your composer.json though
