### ISSUE TITLE
Why session is created when login?

### ISSUE THREAD

**Issue by DesmondPang** [tymondesigns/jwt-auth#256]
Token authentication is designed for authentication without storing session in server. I found that there is a session file created in storage/framework/sessions directory. Is it the same kind of session as basic auth or default auth in Laravel?

**Comment by tymondesigns** [comment]
jwt-auth doesn't do anything with a traditional session. You will need to disable laravel's session, see here - https://laracasts.com/discuss/channels/general-discussion/api-disabling-sessions-and-csrf?page=1

**Comment by DesmondPang** [comment]
Thank you so much!
