### ISSUE TITLE
[Question] Max tokens per user

### ISSUE THREAD

**Issue by oleynikd** [tymondesigns/jwt-auth#258]
Hi,

First of all thank you guys for such a great tool!

Is there any way to limit number of valid tokens per user? I need to implement feature to disallow users to login more then 10 times simultaneously...

Thanks.

**Comment by tdhsmith** [comment]
There isn't a built-in mechanism, but you could add your own logic to store tokens to a table of user tokens and check that table every time someone attempts a new log-in (you'd want to check the Blacklist periodically too, depending on how you want to handle expired tokens).
