### ISSUE TITLE
Is there a way to return token generated from 'jwt.refresh' middleware?

### ISSUE THREAD

**Issue by jlien-calwater** [tymondesigns/jwt-auth#259]
Something like this?

```php
public function __construct()
{
    $this->middleware('jwt.refresh', ['only' => ['refresh']]);
}

public function refresh()
{
    return $token;
}
```

**Comment by tdhsmith** [comment]
You could create your own version of [the RefreshToken middleware](https://github.com/tymondesigns/jwt-auth/blob/master/src/Middleware/RefreshToken.php) that refreshes _before_ the action (i.e. before `$next()`) and sets the local token. Haven't tested it, but something like:

```php 
public function handle($request, \Closure $next)
    {
        try {
            $newToken = $this->auth->setRequest($request)->parseToken()->refresh();
        } catch (TokenExpiredException $e) {
            return $this->respond('tymon.jwt.expired', 'token_expired', $e->getStatusCode(), [$e]);
        } catch (JWTException $e) {
            return $this->respond('tymon.jwt.invalid', 'token_invalid', $e->getStatusCode(), [$e]);
        }

        // ensure the new token is available as JWTAuth's local copy (accessible through getToken)
        $this->auth->setToken($newToken); 

        // *NOW* we run the controller (or whatever this middleware wraps)
        $response = $next($request);

        // Attach the token to the response back to the client
        $response->headers->set('Authorization', 'Bearer ' . $newToken);

        return $response;
    }
```

With something like that, the token would then be available within the controller through `JWTAuth::getToken()`.

That said, I'm not sure why you'd necessarily want this. :stuck_out_tongue:

**Comment by jlien-calwater** [comment]
@tdhsmith thanks for the response!

I've been having trouble extracting the new authorization token that is being returned from the jwt.refresh from angular $http. So I am returning the token in the response body instead.

```php
//PHP Controller
$user = User::first();
$token = JWTAuth::fromUser($user);
return response()->json(compact('token'));
```

Which is really dumb of me (was in a hurry) since a new token is being returned with jwt.refresh. Digging into the angular documentation I found that I was calling the header wrong.

```javascript
// Javascript
$http.get('/')
  .then(function(response, status, headers, config) {
    // status, headers, and config has been moved to response object
  });
```

```javascript
// Javascript
$http.get('/')
  .then(function(response) {
    var refreshToken = response.headers('Authorization');
  });
```

**Comment by tdhsmith** [comment]
I totally understand. I'm working with an Angular front-end too, and getting our interceptors to catch the new token and replace the local copy in the right way was a pain, especially when you factor in trying to resend all the requests that failed due to expired token...  :dizzy_face:

**Comment by jlien-calwater** [comment]
@tdhsmith did you get that working?

I thought about your route, but decided to avoid it due to it's complications. However, I did come up with a different approach. 

JWT token requires a client request where the server side validate the credentials.
With that said, the same is true for refreshing the token.

The solution I came up with is to refresh to token 1 minute before the token actually expires.
Once the token refreshed, all asynchronous call will have the new token.

Something like this: (I am using satellizer for my front-end validation.)

```javascript
var timer;
var failedCounter;

function start() {
  stop();
  timer = $interval(updateToken, 60000); // refresh token every min
}

function stop() {
  $interval.cancel(timer);
}

function updateToken() {

  $http.get('/api/refresh')  // calls controller that have jwt.refresh middleware
    .then(function(response) {
      var currentToken,
          refreshToken;

      currentToken = $auth.getToken();  //satellizer function
      refreshToken = response.headers('Authorization');

      if (currentToken !== refreshToken) {
        $auth.setToken(refreshToken);
      }

    }, function(response) {

      // stop interval if failed twice
      if (failedCounter === 2) {
        stop();
        $state.go('auth'); // have user log back in
      }

      $log.error('response', response);

      failedCounter++;

    });

}

// start refresh token timer
start();

```

I figured all asynchronous $http is already made, the server side should finish processing all the request while the client side is still waiting for a response without any problem.

Is there a loophole in my thinking here?

**Comment by tdhsmith** [comment]
That'll work okay, but there are a few edge cases, like a user returning to the site with less than a minute on their token. Then you aren't going to catch the error. Also you're not initiating your second refresh attempt immediately, so if a user navigates to a new page (or any action requiring an api call) after the first failure but before a minute has elapsed, you'll also be in an invalid token state. Depending on what kinds of requests you make, these failures could be acceptable or annoying.

That said, I don't think that means you should switch your system. You can probably mitigate these situations just by using instructive error messages. (Though I don't know if I'd bother with waiting for 2 failures to refresh, personally.)

**Comment by tdhsmith** [comment]
Yes we did get ours working, but it certainly has some complexity underneath. Our front-end is completely dumb to the JWT contents, so we're not using any token library. Thus we already had to use an interceptor to attach the token to our requests. From there we figured it would be best to have a single unit / point-of-failure (the interceptor) handle all token logic. We also didn't want to use timers because some aspects of our token timeout are configurable on a per-user or per-app basis, so we wanted to avoid hard numbers.

You know, if you were interested in reducing the number of requests (and likelihood of the above failures) in exchange for a small complexity increase, you could use Satellizer to get the payload of the current token and simply look up when it expires. Then set a timer until that point minus 1 minute.
