### ISSUE TITLE
"tymon/jwt-auth": "dev-master"

### ISSUE THREAD

**Issue by marijang** [tymondesigns/jwt-auth#26]
"tymon/jwt-auth": "dev-master" it is not working:(

i m using laravel 5

**Comment by tymondesigns** [comment]
Laravel 5 is not supported on the master branch. Also there is currently an issue with L5, not supporting any packages...

see here: https://laracasts.com/discuss/channels/general-discussion/l5-latest-commit-breaks-if-using-waygenerators-or-image-internvention

I can assure you though, that I have Laravel 5 in mind, and will be updating that package to when I release 0.4

Thanks
