### ISSUE TITLE
Request: add function to return JWTAuth's $this->auth

### ISSUE THREAD

**Issue by BrettTrotter** [tymondesigns/jwt-auth#264]
I'd love a function that would let me get at ->auth or ->auth->user() from the JWTAuth instance.

If I could call JWTAuth::user() or something to that effect, that would be fantastic.

Your function could be something pretty simple (or something more readable):

```
  public function user()
  {
    return ($this->auth ? $this->auth->user() : null);
  }
```

Do you have a philosophical objection that caused it to be left out in the first place, or is there another way to access that?

**Comment by tymondesigns** [comment]
this has already been added on the develop branch [here](https://github.com/tymondesigns/jwt-auth/blob/develop/src/JWTAuth.php#L240-L248), so you can expect that with the next release :+1:

**Comment by BrettTrotter** [comment]
Beautiful sir, thanks!
