### ISSUE TITLE
Same JTI for Different Tokens

### ISSUE THREAD

**Issue by athad** [tymondesigns/jwt-auth#265]
I'm currently using the jwt.refresh middleware with Dingo API. I have a problem in that JWT Auth seems to be generating the same JTI in two different contests. I set up a logging message in the JWTManager::decode method and I see this:

[2015-09-29 23:52:53] local.INFO: {"iss":"http:\/\/192.168.56.102\/api\/files", <redacted, same in both tokens>, "exp":"1443574373","iat":"1443570747","nbf":"1443570773","jti":"619198e256d402574ed78e05cc169698"}

later on I have a new token with a different issuer:
[2015-09-29 23:52:59] local.INFO: {"iss":"http:\/\/192.168.56.102\/api\/cases", <redacted, same in both tokens>,"exp":"1443574373","iat":"1443570747","nbf":"1443570773","jti":"619198e256d402574ed78e05cc169698"}

This token now gets reported as being blacklisted although it's just been generated! (checked a tcpdump and this is true, no other requests reach the token generator in-between). Basically, I requested a new token in a different context but received the old ID for a different issuer. Is this OK? Am I missing something? To me it seems like a clash...

**Comment by athad** [comment]
I just found that the JTI only depends on the sub and nbf fields; this seems wrong, it basically says that requests for two different API pages will blacklist each other!

**Comment by athad** [comment]
There should also be some randomness involved since multiple API requests by the same user might arrive in the same second and generate the same timestamp - refreshing the same page quickly does that.

**Comment by tymondesigns** [comment]
This has been fixed on the develop branch. New release coming as soon as I finish the documentation.

Thanks

**Comment by tymondesigns** [comment]
You can use it now via `0.6.*@dev`. Things won't change much now

**Comment by ftvs** [comment]
Great to know this was fixed. To help those coming from Google/issues search, is there actually a 0.6.0 release? Or is this fix in the 1.0.0-alpha.3 release?
