### ISSUE TITLE
Call to a member function toUser() on a non-object

### ISSUE THREAD

**Issue by aenciso** [tymondesigns/jwt-auth#27]
Hi,

When I call 

$user = JWTAuth::getToken()->toUser($token);

I get 

Call to a member function toUser() on a non-object

Any ideas why?

Thanks

**Comment by tymondesigns** [comment]
the `getToken()` method will parse the token from the request and return it (as a string). 

You will need to call `JWTAuth::parseToken()->toUser();` instead.

**Comment by aenciso** [comment]
Thanks. Is there any way we can add some extra data to the payload? or perhaps a way of returning the user encrypted?

Thanks
