### ISSUE TITLE
Default Claims overriding Required Claims config

### ISSUE THREAD

**Issue by MnMTech** [tymondesigns/jwt-auth#273]
I am unable to remove the exp() claim by changing the required_claims value in the jwt configuration file. It appears as if in PayloadFactory->buildClaims() the configuration is never read and the hardcoded set of default claims are always used.

**Comment by tdhsmith** [comment]
I think @tymondesigns' intent was that `required_claims` sets what claims are required for _validation_, not construction. I'm not sure if he would want to use the same setting to determine which claims are given defaults by the payload factory. Maybe a new setting would be necessary?

Regardless, `exp` is pretty important to the function of JWTAuth in determining token lifetimes. The develop branch now allows you to set `ttl` to null, which will remove `exp`. ([Factory.php#L123](https://github.com/tymondesigns/jwt-auth/blob/8298edc879ef5f97ccb3d805260d7c2e1123fbcf/src/Factory.php#L123)) Is there another reason you'd want to remove it entirely?

**Comment by tymondesigns** [comment]
Yes, the `required_claims` are purely for validation, not payload hydration :+1:
