### ISSUE TITLE
No way to change the TTL value or the expiry date on a custom token

### ISSUE THREAD

**Issue by MnMTech** [tymondesigns/jwt-auth#274]
When using the JWTFactory facade its not possible to change the expiry on a per token basis. Would be good to pass a value to exp() to amend this.

**Comment by MnMTech** [comment]
Solution to this is to adjust the ttl via Config before calling JWTFactory::make();

**Comment by tymondesigns** [comment]
just fyi... this is possible on the develop branch, any custom claims will overwrite the default ones
