### ISSUE TITLE
Avoid query DB

### ISSUE THREAD

**Issue by jepezi** [tymondesigns/jwt-auth#275]
This is not really an issue but a question about strategy for protected route. I'm using Laravel for api server and have a react app on the front on my personal project for learning purpose. I use the `GetUserFromToken` middleware for protected routes. Everything works great. From my understanding, every time auth user hits the protected route, the middleware finds token in the request and queries DB for user based on `sub` (id in this case), then let it pass if found one. 

Now I'm wondering if it's a good idea to, for example, create the middleware to just decode (verify) the token and grab the user encoded in the token, instead of hitting DB when I'm already using token. In other word, why would we query DB for user when we already have everything we need in token (for protected routes that is)?

Sorry if I've missed something very obvious. Thanks!

**Comment by Deleugpn** [comment]
I don't know if I got it right and (also) my experience with e rest api is limited, but being stateless makes your API require to make sure that everything is in order. From my understanding, each request is a new unrelated communication. It's like the server doesn't even know what's your token is about. I see it like those places you buy a storage box, people there give you a key and you go away. When you come back, they don't know who you are or where you got the key, so they test it in the keyhole and if it works you have the right for the content of the storage.
When the api checks the database to make sure the user exists, it's doing the keyhole job.

**Comment by jepezi** [comment]
Thanks for your opinion. To further discuss, let's continue with your keyhole example but with my slightly different view. 

What if the keyhole job is the token verification process? i.e. Key (token) is considered invalid when the verification fails (key is expired, signature is invalid, ..) In other words, I think keyhole job is about verifying the token, not the auth attempt. You have the valid key, you get the content decoded in the key (user info you put in the first place) and you go ahead.

**Comment by harshitdkanodia** [comment]
We can use custom attributes set the user info in the token itself , but its not good practice !
Say for example  you have a field in your database that indicates whether the user has certain rights .
Let's say your user logged in and his information is in the token, now he's using it and someone changes his rights in the database ..
Now the token and database are not in sync .
In my opinion it's a good practice to only include information that is absolutely necessary in the token , you would not put all the use info for the same reason you would set a foreign key on a column 
To keep everything in sync and validated .

*peace*

**Comment by jfoliveira** [comment]
I'm new to JWT and as @jepezi I was also under the impression that querying the DB on every request could be avoided.

Quoting http://jwt.io/introduction/:

>**Self-contained**: The payload contains all the required information about the user, **to avoid querying the database more than once**.
> ...
>The server's protected routes will check for a valid JWT in the Authorization header, and if there is, the user will be allowed. As JWTs are self-contained, **all the necessary information is there, reducing the need of going back and forward to the database**

I see the value of checking the id on DB, to make sure the token and database are in sync, but ...

1. Isn't the `exp` claim supposed to be set to the shortest amount of time that an `out of sync` situation would be allowed?
2. As any attribute can change between requests - leading to an out of sync scenario - what's the benefit of adding any claim to the token's payload other than userId/sub if they have to be retrieved from DB again on every request?

**Comment by jfoliveira** [comment]
I've just created a new PR #464
Please review it.

**Comment by tymondesigns** [comment]
See above PR for more discussion on this
