### ISSUE TITLE
0.5.5 - invalidated token can be refreshed

### ISSUE THREAD

**Issue by ValdasK** [tymondesigns/jwt-auth#278]
I'v noticed that tokens which are created and invalidated can be refreshed, and this is a bug.

`Blacklist` class, method `add`: blacklists token only for its lifetime, not lifetime with refresh duration included, therefore scenarios like that are available:

(1 min ttl, 20160 refresh_ttl)

token created -> invalidate token -> wait for 1 minute -> ask for token refresh -> new token. 

This case should not be viable, because token was invalidated previously, but I am still able to refresh it.

Maybe I am doing something wrong here? I do not use any middlewares to protect my refresh action, and it looks like that: 

    public function getRefresh(JWTAuth $jwt)
    {
        try {
            $token = $jwt->refresh($jwt->getToken());
        } catch (JWTException $e) {
            return $this->jsonResponse(null, 401);
        }
    
        return $this->jsonResponse(['token' => $token]);
    }

**Comment by tymondesigns** [comment]
This has been fixed on the develop branch, which will be the upcoming `0.6` release. Of course you're free to test it out now via `0.6.*@dev` version
