### ISSUE TITLE
jwt.io says that token got 'Invalid Signature'

### ISSUE THREAD

**Issue by Hebilicious** [tymondesigns/jwt-auth#281]
I'm using Postman to test out this package.
Everything is working correctly, except for this bug on the jwt.io debugger.

I'm using JWTAuth::attempt($credentials) to issue the token.
Dumping credentials return this array :  [ "email" => "usermail@yahoo.com", "password" => "secret"].

The token works fine, only the signature is invalid.

I'm using the latest versions : 
tymon/jwt-auth v5.5, laravel/framework v5.1.19

**Comment by tdhsmith** [comment]
Are you pasting your secret key into the form? The field isn't very obvious on [jwt.io](http://jwt.io), but in the blue "verify signature" section on the right there's a small box that says "secret".

**Comment by Hebilicious** [comment]
I didn't notice that field, my bad.
The key is the one generated by the artisan command : jwt:generate.
Thanks @tdhsmith, I'm closing the issue :)

**Comment by tdhsmith** [comment]
Yeah I miss it pretty much every time, haha.

**Comment by INGCRENGIFO** [comment]
@tdhsmith Thank you very much, I did not know that field was used, now everything makes sense. xD

**Comment by ghost** [comment]
Just to add a little context, there goes your secret key:
![image](https://user-images.githubusercontent.com/4084252/31076951-5008e3da-a785-11e7-8d5f-d60674ed4a46.png)

**Comment by katongilang** [comment]
tes

**Comment by olliechick** [comment]
When you enter a secret key into the form, it will change your JWT to match that key. You should re-paste the JWT to make sure the signature is valid.

**Comment by MelMacaluso** [comment]
@olliechick thanks, was having an existential crisis

**Comment by css0k** [comment]
but when i use the rs256, i meet the mistake that i can't generate the token, what should i do?
