### ISSUE TITLE
Invalidating all token for a User

### ISSUE THREAD

**Issue by CLOUGH** [tymondesigns/jwt-auth#282]
Hi, I was wondering if it is possible to invalidate all the tokens associated with a user. Im trying to have the user be logged into one place at a time. So if the user submits their credentials/login again it should invalidate all the other tokens associated with that user and create a set of new valid tokens for this new login. This would happen only when user log in.

**Comment by tdhsmith** [comment]
There isn't a built-in method to do this, but you could store each user's most recent token in a DB and invalidate it when a new one is generated. (#258)  See also the discussion at #97 (though as they conclude, the secret-changing idea wouldn't work)./

**Comment by tymondesigns** [comment]
as @tdhsmith has said, this is something you would need to implement yourself. 

Possibly by keeping a registry of token's issued for a user, and checking the records on each request. This is essentially the opposite of a blacklist, if you get what I mean.
