### ISSUE TITLE
Getting token_not_provided when using Authorization Header

### ISSUE THREAD

**Issue by Deleugpn** [tymondesigns/jwt-auth#284]
I read [this tutorial](http://blog.nedex.io/create-an-api-server-for-mobile-apps-using-laravel-5-1/) and I managed to make it work perfectly. The only problem is that when I switch from **?token={token_here}** to **Authorization Bearer {token here}** it stops working.
I'm using Postman and I'm writing **Authorization** in the Header field and **Bearer{white space}{token}** in the value.

I read in the Wiki about the Apache problem and I'm not sure if that's my case. I diagnosed it with PHP function [**getallheaders()**](http://php.net/manual/pt_BR/function.getallheaders.php). If I *die and dump* that function, it shows that the Authorization Header is available. I tried with and without the .htaccess modification.

**.htaccess**

    <IfModule mod_rewrite.c>
        <IfModule mod_negotiation.c>
            Options -MultiViews
        </IfModule>

        RewriteEngine On

    #    RewriteCond %{HTTP:Authorization} ^(.)
    #    RewriteRule . - [e=HTTP_AUTHORIZATION:%1]

        # Redirect Trailing Slashes If Not A Folder...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^(.*)/$ /$1 [L,R=301]

        # Handle Front Controller...
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]    
    </IfModule>

**Route File**

    dd(getallheaders()['Authorization']);
    Route::group(['prefix' => 'api'], function() {

        Route::post('login', 'AuthenticateController@email');

        Route::group(['middleware' => ['jwt.auth', 'jwt.refresh']], function() {
            Route::post('logout', 'AuthenticateController@logout');

            Route::get('test', function() {
                return response()->json(['foo' => 'bar']);
            });
        });
    });

Any thoughts on where I'm going wrong?

**Reminder**: if I use **http://localhost/projects/linus/public/api/test?token={token}** it works.

**Comment by james-daddies** [comment]
Try setting this in your apache host config:

`Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization"`

I didn't set anything in my .htaccess file for my implementation.

**Comment by Deleugpn** [comment]
Thank you very much. You saved me. I've been stuck at this for ages now. I don't remember from where I took the .htaccess configuration, but as in my post, it was missing a `*` character at `RewriteCond %{HTTP:Authorization} ^(.)`

Copying your .htaccess configuration solved my problem. No need to change anything else.

**Comment by james-daddies** [comment]
Good to hear. The apache config I now recall was for CORS.
