### ISSUE TITLE
How to make a permanent token?

### ISSUE THREAD

**Issue by ken8203** [tymondesigns/jwt-auth#285]
Hello, 

I need a permanent token for testing, how can I do it?
Thanks!

**Comment by james-daddies** [comment]
You would have to set the `exp` claim to a unix-timestamp way into the future. I am sure that would cause problems at some point.

I would generate a token based upon a user object in a setUp() method in your TestCase class, then use that for your tests.

**Comment by tymondesigns** [comment]
the upcoming release will support non-expiring tokens, fo situations such as this. Just set the ttl to null in the config, and your good to go
