### ISSUE TITLE
What is the release date for package?

### ISSUE THREAD

**Issue by adkazakov** [tymondesigns/jwt-auth#287]
Hi guys, I want to know, on what date planned the release of a new version of the package?

We really need fix type conversion for fields 'exp', 'iat' and etc.

```
return (int) Utils::now()->addMinutes($this->ttl)->format('U');
```

**Comment by gweiss27** [comment]
Hi there, I would also like to know if there is a targeted release date to migrate the develop branch to master.  Thanks!

**Comment by mytholog** [comment]
+1

**Comment by tymondesigns** [comment]
almost done with the new docs.. I can't commit to a specific date, but I definitely want this release out there asap myself

**Comment by gweiss27** [comment]
That’s fantastic.  We all appreciate your hard work.  As I mentioned on another thread, I am already migrated to your dev-develop branch and its working great.  Plus it solved the problems I was having using the current 0.5.5 build.
