### ISSUE TITLE
JWTException thrown in command line

### ISSUE THREAD

**Issue by renoguyon** [tymondesigns/jwt-auth#289]
Hi,

I just installed a fresh new Laravel 5.1 setup with JWT-Auth 0.5.5 and I got an exception thrown every time I run a command in console.

Here is my composer.json file:

```
"laravel/framework": "5.1.*",
"dingo/api": "0.10.*",
"tymon/jwt-auth": "0.5.*"
```

The command output:

```
(...)
Generating autoload files
> php artisan clear-compiled

  [Tymon\JWTAuth\Exceptions\JWTException]
  The token could not be parsed from the request

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output:
```

And every time I run a command I get something like:

```
# php artisan list

  [Tymon\JWTAuth\Exceptions\JWTException]
  The token could not be parsed from the request
```

It seems like JWT is looking for a token for each request, even if its not in API context.

Any idea?

Thanks for your support :)

**Comment by tdhsmith** [comment]
That's odd.

One unlikely guess: did you accidentally put the middleware into your kernel's `$middleware` instead of `$routeMiddleware`? The former runs on **every** request.

Otherwise I think I'd have to see some more detail. Is there a stack trace in your log file? Does verbose mode say anything (add `-v` or `--verbose` to your artisan command)?

**Comment by renoguyon** [comment]
I've found the problem. Good news, it's not on your side :)

In addition to JWTAuth middleware, I had a line like that in my API Base Controller:

```
$this->user = JWTAuth::parseToken()->toUser();
```

And for a reason I do not understand, it seems that my API Base Controller is loaded on every request, even artisan commands. API routes are handled by Dingo.

**Comment by tdhsmith** [comment]
Ahh thanks for the update; glad you figured it out!

**Comment by vivex** [comment]
I am also facing this error, and cause is also same , is there any way i can skip jwt to throw error if it is being loaded via command line.

**Comment by tdhsmith** [comment]
@vivex Where's this happening? If you're using jwt-auth calls in the controller's constructor, check out #774.

You can't really just turn off a class when you have calls to it somewhere. And besides, that would be ignoring the root problem.

**Comment by vivex** [comment]
@tdhsmith  umm ok i will put  condition in my constructor to check if request is CLI then dont initiate JWT->getuser .

**Comment by brickgale** [comment]
Also encountered this issue. After commenting it on my constructor it displays my routes fine.

**Comment by ultrono** [comment]
To add to this I had a similar problem to @renoguyon. I was trying to parse the JWT token within my app service provider:

```
try {
                    $user = JWTAuth::parseToken()->authenticate();
    
                    $report->setMetaData([
                        'Api user' => [
                             // ...
                        ]
                    ]);
                } catch (JWTException $ex) {
                    dd('JWT Exception', $ex->getMessage());
                }
```

I needed to do a check to ensure the app wasn;t running in the console via `$this->app->runningInConsole()`.
