### ISSUE TITLE
Token Expiration

### ISSUE THREAD

**Issue by RushNetMx** [tymondesigns/jwt-auth#292]
Hello!

I have an app that connects to an api in laravel, but I have some troubles whit the token expiration, what is the best way to keep login a user with lo limit or expiration time? Thanks for any help you could provide me. If you can please give me a clue with some code thanks.

**Comment by tdhsmith** [comment]
You can set the expiration time to a very high number with the `ttl` config setting. If you absolutely need a truly limitless token, you can use the develop branch, which allows you to set `ttl` to null.

But an important question is **why?** Making permanent tokens is, in most cases, a security risk that defeats the point of having tokens. If anyone else gets a hold of that token, they can permanently imitate a user. Handle them with care.
