### ISSUE TITLE
Refresh token can refresh expired token?

### ISSUE THREAD

**Issue by rogeryu23** [tymondesigns/jwt-auth#293]
I got a token and then wait till its expiration and pass to the following function
I found that the token is refreshed as long as it is within refresh_ttl
But if the refresh token itself is over refresh_ttl, then I will get TokenExpiredException which makes sense
I saw in other places that refresh token only works with not expired token, seems not the case? I can always refresh token no matter if the passed in token is expired or not?

 public static function getRefreshToken($token)
    {
        if (!$token) {
            throw new AuthException(
                Constants::get('error_code.token_not_provided'),
                trans('errors.token_not_provided'));
        }

        try {
            $newToken = JWTAuth::setToken($token)->refresh();
        } catch (TokenExpiredException $e) {
            throw new AuthException(
                Constants::get('error_code.refresh_token_expired'),
                trans('errors.refresh_token_expired'), $e);
        } catch (JWTException $e) {
            throw new AuthException(
                Constants::get('error_code.token_invalid'),
                trans('errors.token_invalid'), $e);
        }

        return $newToken;
    }

Thanks
Roger

**Comment by tdhsmith** [comment]
Yes, tokens having an _expired-but-refreshable_ period is the intended default functionality. It forces tokens to be repeatedly invalidated in the short-term (`ttl`) but allows front-end users to stay logged in over the medium term (`refresh_ttl`).

If you don't like this functionality, you can change the config (i.e. set the two values to be equal).

Other libraries and set ups may use the meanings of "expired" differently or have different refresh mechanics. (For example, you may see systems that have a separate "refresh token" passed to the client that validates its refresh requests to the server.)
