### ISSUE TITLE
how to change the token cache driver from memcached to redis in Lumen?

### ISSUE THREAD

**Issue by abcsun** [tymondesigns/jwt-auth#294]
anyone knows how to change the token cache driver from memcached to redis in Lumen, thanks

**Comment by tdhsmith** [comment]
Did you follow the instructions in the Lumen docs? http://lumen.laravel.com/docs/cache#configuration

>  install the `predis/predis` package (~1.0) and `illuminate/redis` package (~5.1) via Composer.

(...and then change your env file to have `CACHE_DRIVER=redis`.)

I don't run Lumen, but I was under the impression JWTAuth's current contract/provider setup should accept that change without a problem.

**Comment by abcsun** [comment]
it works, and thank you.
