### ISSUE TITLE
More than one token per user

### ISSUE THREAD

**Issue by andrepibo** [tymondesigns/jwt-auth#296]
Hello guys,

I am building an API that is gonna be consumed by a website front-end and an APP, and I am using jwt to perform authentication.

My question is how could I use this lib to have multiple token per user? For instance, the same user is logged in two differents PCs and in his smartphone (through the app). How could I manage separately his different logins in such a way that when he logs out from one of his PCs it is not gonna logout on his smartphone and second PC?

Another question, is there any other way to logout an user than JWTAuth::invalidate(JWTAuth::getToken()); ?

Thanks

**Comment by tdhsmith** [comment]
> How could I manage separately his different logins in such a way that when he logs out from one of his PCs it is not gonna logout on his smartphone and second PC?

Actually this is effectively "built-in". The server by default has no knowledge of what tokens currently exist (other any that are blacklisted), so if your user logs in from a new client, the server will issue a new token. There is no "state" or "session" saved on the server; the token is the only session that exists. Unless you add something yourself, logouts are going to only apply to the current token.

> Another question, is there any other way to logout an user than JWTAuth::invalidate(JWTAuth::getToken()); ?

Depending on how much security you need, that may not even be necessary. When the client forgets the token, _as long as the token hasn't been compromised somehow_, then there won't be any more copies of it, and the user is already "logged out". However I'm not a security expert, so I'm not going to claim to know how to guarantee tokens are safe from MITM/etc.

If you do want to block issued tokens on logout, the way you've presented works. If you've already parsed the token (i.e. you're behind middleware that checks before the request) you don't even need the token argument, `JWTAuth::invalidate()` will be enough.
