### ISSUE TITLE
refresh token on available

### ISSUE THREAD

**Issue by ssi-anik** [tymondesigns/jwt-auth#298]
Some routes doesn't need the token and some routes does need the token. but if I apply middleware jwt.auth it will validate if the token is a valid authenticated user or not. and jwt.refresh will refresh the token on available. They both throw some exceptions and halt the program.

Now if we visit those pages without any middleware & move back to authentication required pages then few minutes later the token will not be working. That's why thinking to build a common middleware if the token is available, refresh that token otherwise, leave that. 
Is it a good practise or there is any facility available previously?

Thanks.

**Comment by tymondesigns** [comment]
I've added a new [Check middleware](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Middleware/Check.php) in the new version that somewhat achieves what you describe. Although I would encourage you to implement your own business specific middleware to get exactly the behaviour your app requires
