### ISSUE TITLE
Issue with refreshed token

### ISSUE THREAD

**Issue by ssi-anik** [tymondesigns/jwt-auth#299]
Hours ago, I tried logging into my account with creds. Then got a token. requested few routes, went good. 
Hours later, I then tried to request with the previous token. said token has expired. This is good. but when I tried to refresh the token and found a new one then I again requested with the new token. the middleware was firing token expired? 

Can anyone explain? 

Footnote: Now I'm trying with 1 minute ttl and everything works as expected. Before, it had wheatever was given as config, didn't change anything

**Comment by tdhsmith** [comment]
Are you positive you used the new token? If the refresh attempt was within the `refresh_ttl` (default 2 weeks from initial token creation) the new token should not be expired.

I can't come up with a reason that a shorter `ttl` would make the refreshed token work. Do you have an example you can share?

**Comment by ssi-anik** [comment]
it's six days ago & I forget what happened. :(

**Comment by vukasin0** [comment]
Works fine for me with default configuration so I can confirm that default miss-configuration isn't case here.

**Comment by tymondesigns** [comment]
Assuming this is resolved
