### ISSUE TITLE
How to fix this or allow to not use Eloquent User

### ISSUE THREAD

**Issue by maxiwheat** [tymondesigns/jwt-auth#302]
I've used `jwt-auth` to allow authentication with Json Web Tokens to my API built with `dingo/api` and Lumen. I followed a [simple tutorial](http://laravelista.com/json-web-token-authentication-for-lumen/) to help familiarize myself with JWT.

Our app is kinda special in the way we connect to the database (we use SQL Server), so we dont really use Eloquent and we make our app with custom classes to make requests to the DB.

The point is, when configuring `jwt-auth` I had an issue because of the `user` config in `/config/jwt.php`. If I did not provide this class and left it to the default generated value, I got an exception : **Class App/User does not exist**. I was forced to give it a class that our app provided. I ended up making a dummy empty class that extends `\Illuminate\Database\Eloquent\Model` just to be able to call `$this->auth->setToken($token)->getPayload()`

Is there a cleaner way to do that? Or a way to desactivate the use of Eloquent for `jwt-auth` ?

**Comment by tdhsmith** [comment]
*All of this assumes JWTAuth 0.5.x. (A lot of this will be different in develop!)*

> I did not provide this class and left it to the default generated value, I got an exception : Class App/User does not exist. I was forced to give it a class that our app provided.

The issue you're seeing is [in the main service provider](https://github.com/tymondesigns/jwt-auth/blob/master/src/Providers/JWTAuthServiceProvider.php#L114):

```php
return $app->make($this->config('providers.user'), [$app->make($this->config('user'))]);
```

The SP is always going to try to `$app->make()` your configured user class. To circumvent this, you can create your own subclass `MyJWTAuthServiceProvider extends JWTAuthServiceProvider` that overrides the `registerUserProvider()` function so it doesn't construct a user instance. Then in your `app.php` config, you'll replace the stock JWTAuth service provider with your custom one. 

If you never use `JWTAuth::toUser()`, that much should be sufficient. (It's the only function that uses the user class.) However, it will completely break if you ever do call `toUser()`, so it's a slightly unclean solution.

If you might use `toUser()` or you just want a more technically-complete approach, you can also create a custom user adapter that implements [`Tymon\JWTAuth\Providers\User\UserInterface`](https://github.com/tymondesigns/jwt-auth/blob/master/src/Providers/User/UserInterface.php). (See [the Eloquent adapter for an example.](https://github.com/tymondesigns/jwt-auth/blob/master/src/Providers/User/EloquentUserAdapter.php)) Then change the `getBy($key, $value)` function to access your DB as appropriate and return an instance of something user-y. Finally, update your JWT config's `providers.user` to point to this class.

**Comment by maxiwheat** [comment]
Great thank you, I will try that

**Comment by ankitabhatti05** [comment]
@tdhsmith Can you please give a practical demo?
