### ISSUE TITLE
Correct documentation

### ISSUE THREAD

**Issue by vukasin0** [tymondesigns/jwt-auth#304]
Package | Versions: 
--------------- | ---------
"laravel/framework" | "5.1.*"
"tymon/jwt-auth" | "0.5.*"

Refresh token codeblock section should be corrected from:

```
protected $routeMiddleware = [
    ...
    'jwt.auth' => 'Tymon\JWTAuth\Middleware\GetUserFromToken',
    'jwt.refresh' => 'Tymon\JWTAuth\Middleware\RefreshToken',
];
```

to:

```
protected $routeMiddleware = [
    ...
    'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
    'jwt.refresh' => \Tymon\JWTAuth\Middleware\RefreshToken::class,
];
```

**Comment by tymondesigns** [comment]
new version will cover this. It is actually done for you in the service provider in the upcoming release
