### ISSUE TITLE
Could not create token: openssl_pkey_get_details() expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by bendbennett** [tymondesigns/jwt-auth#307]
Hi,
I've set-up JWTAuth for an API using this guidance - https://scotch.io/tutorials/token-based-authentication-for-angularjs-and-laravel-apps

Everything works as expected when using any of the HS algorithims (i.e., HS256, HS384, HS512).
But switching to any of the ES or RS algorithims causes an exception to be thrown:
`Could not create token: openssl_pkey_get_details() expects parameter 1 to be resource, boolean given`
This is thrown on line 66 of `/vendor/namshi/jose/src/Namshi/JOSE/Signer/OpenSSL/PublicKey.php`
`$keyDetails = openssl_pkey_get_details($key);`
This is due to the $key param passed into the `supportsKey($key)` method in PublicKey.php being false. Any suggestions? 

My motivation for wanting to use either ES or RS algorithims is to enable public key verification of JWT so that the secret used during the creation of the JWT does not have to be shared across all of the services that need to be able to verify the JWT. This seems to have been implemented for JWT in another library - http://bshaffer.github.io/oauth2-server-php-docs/overview/jwt-access-tokens/ but I'd like to use tymondesigns/jwt-auth as it's neatly packaged up for Laravel. Is it possible to use public key verification of JWT with tymondesigns/jwt-auth?

Thanks

**Comment by tymondesigns** [comment]
Yea, this is the last thing I wanted to get into the upcoming `0.6` release. 

I will try and get it done soon as I can.

**Comment by bendbennett** [comment]
Thanks for the feedback.

**Comment by tymondesigns** [comment]
This is done, and is currently part of the 1.0.0-alpha1 release
