### ISSUE TITLE
User Model namespace not working

### ISSUE THREAD

**Issue by laitedliang** [tymondesigns/jwt-auth#308]
Hi,

How can I define the user model for jwt authentication?
I have followed your wiki "Configuration" and "Creating Tokens" tutorial, but the "User Model namespace" assigned in config\jwt.php will always be overridden by the "Authentication Model" inside config\auth.php.

This is what my jwt.php and auth.php look like
```php
// jwt.php
/*
    |--------------------------------------------------------------------------
    | User Model namespace
    |--------------------------------------------------------------------------
    |
    | Specify the full namespace to your User model.
    | e.g. 'Acme\Entities\User'
    |
    */

    'user' => 'App\jwtUser',
```

```php
// auth.php
/*
    |--------------------------------------------------------------------------
    | Authentication Model
    |--------------------------------------------------------------------------
    |
    | When using the "Eloquent" authentication driver, we need to know which
    | Eloquent model should be used to retrieve your users. Of course, it
    | is often just the "User" model but you may use whatever you like.
    |
    */

    'model' => App\fxUser::class,
```

The table used for my jwtUser model is "jwt_users", while the table used for User model is "users".
When I am trying to call `JWTAuth::attempt($credentials))`, the "user" table is used for authentication instead of "jwt_users".

The proof:

I have dd your `attempt` function

```php
public function attempt(array $credentials = [], array $customClaims = [])
    {
        if (! $this->auth->byCredentials($credentials)) {
            return false;
        }
        dd($this->auth->user()); // <-- dd before return
        return $this->fromUser($this->auth->user(), $customClaims);
    }
```

And here is the result of dd
```
User {#219 ▼
  #table: "users"
  #fillable: array:3 [▼
    0 => "name"
    1 => "email"
    2 => "password"
  ]
  #hidden: array:2 [▼
    0 => "password"
    1 => "remember_token"
  ]
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:5 [▶]
  #original: array:5 [▶]
  #relations: []
  #visible: []
  #appends: []
  #guarded: array:1 [▶]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: true
  +wasRecentlyCreated: false
}
```

Am I missing something or done something wrong?
Thanks in advance!

**Comment by dukejib** [comment]
if you want to use your own table for authentication.

auth.php
>> 'model' => App\YourTableModel::class,
>> 'table' => 'YourTable',

jwt.php
>> 'user' => 'App\YourTableModel',
>> 'identifier' => 'Your Table ID', (if other then 'id')

Using different tables for both jwt.php and auth.php will result in 500 internal server error.

And make sure, your passwords are hashed. 

I don't know about the internals of JWT-Auth, but it seems that it authenticates the users via Auth.php and then creates a token for it (it makes sense, why would some one require 2 different tables for authentication, when you can use CSRF for desktop and Jwt-Auth for Mobiles)

**Comment by tdhsmith** [comment]
Yes @dukejib has it right. The default provider setup in v0.5 uses Laravel's `Auth` to support the authentication methods. The `jwt.user` setting only affects the `toUser()` function, but it will be necessary for it to match the `auth.model` setting if the functions are to work together properly.

(If you're using custom providers, this may or may not still apply.)
