### ISSUE TITLE
Anyway to get the User object after authentication?

### ISSUE THREAD

**Issue by aleemb** [tymondesigns/jwt-auth#309]
I may be missing something obvious here but the User is queried and setup in `GetUserFromToken` middleware. I can't see any methods to expose the user object so that I can access it in other middleware downstream without having to query the DB again.

**Comment by tymondesigns** [comment]
If you are using the default laravel auth provider, then you can simply reference `Auth::user()` anytime after the middleware is run.

Although note that this will change to `JWTAuth::user()` in the upcoming release
