### ISSUE TITLE
How to invalidate an user's token after he reseted his password?

### ISSUE THREAD

**Issue by andrepibo** [tymondesigns/jwt-auth#310]
Hello guys, I small doubt here.

An user logs in, he gets a token. That token is used to perform a serie of actions.
The user loses his password and resets it. A new password is created and when the user logs in again a new token is created.

In this scenario, how to invalidate all old token of that user? Is it necessary? Does JWTAuth check whether a token is still valide whenever the token is used?

**Comment by tdhsmith** [comment]
Check out [the discussion here.](https://github.com/tymondesigns/jwt-auth/issues/300#issuecomment-150953800).

Token-based authentication is "stateless" -- it does not keep track of what tokens have been issued. If you want to invalidate tokens before they expire, you will need to add your own way to track them. In the link above I suggest two options:
- storing all of a user's tokens in the database and calling `invalidate()` on them when you reset
- record the date+time of each user's last password reset. Whenever you check a token, you must also ensure it was issued _after_ this time.

There are other possible approaches too.

**Comment by tymondesigns** [comment]
@tdhsmith is spot on :+1:
