### ISSUE TITLE
Could not authenticate with JWTAuth::attempt

### ISSUE THREAD

**Issue by jidesakin** [tymondesigns/jwt-auth#312]
This is what my auth.php looks like

/*
    |--------------------------------------------------------------------------
    | Authentication Model
    |--------------------------------------------------------------------------
    |
    | When using the "Eloquent" authentication driver, we need to know which
    | Eloquent model should be used to retrieve your users. Of course, it
    | is often just the "User" model but you may use whatever you like.
    |
    */

    'model' => App\User::class,

    /*
    |--------------------------------------------------------------------------
    | Authentication Table
    |--------------------------------------------------------------------------
    |
    | When using the "Database" authentication driver, we need to know which
    | table should be used to retrieve your users. We have chosen a basic
    | default value but you may easily change it to any table you like.
    |
    */

    'table' => 'users',

here is what my jwt.php looks like:

    'user' => App\User::class,

    /*
    |--------------------------------------------------------------------------
    | User identifier
    |--------------------------------------------------------------------------
    |
    | Specify a unique property of the user that will be added as the 'sub'
    | claim of the token payload.
    |
    */

    'identifier' => 'id',

Credentials exist in the database but could  not authenticate.

Please help what could be wrong?

**Comment by tymondesigns** [comment]
Is the primary key for your user table `id` ?

**Comment by jidesakin** [comment]
Yes it is.

**Comment by tymondesigns** [comment]
What is returned from `JWTAuth::attempt()` ? Is an exception thrown ?

**Comment by daronjay** [comment]
I have had a similar problem with a 500 internal server error thrown by calling JWTAuth::attempt(). In my case the issue was due to having moved my user class into a Models directory, and not updating BOTH auth.php and jwt.php so that they could find it.

**Comment by tymondesigns** [comment]
I'll assume this is resolved then
