### ISSUE TITLE
Release with exp, iat, nbf as Integers

### ISSUE THREAD

**Issue by aejnsn** [tymondesigns/jwt-auth#316]
@tymondesigns Can you make a release that includes this PR?: 
https://github.com/tymondesigns/jwt-auth/commit/50c69ff3087b136b3b2c0986d3daf433c334af39

We've used Fractal to construct an API, and at this moment, I do not see a way to set up JSON_NUMERIC_CHECK on my response. I see that I would have to override a method in Fractal's Scope class, but that seems to be a difficult approach.

Thanks! :smiley:

**Comment by o15s19** [comment]
+1

**Comment by dani3l** [comment]
This is already been taken care of in the develop branch.
I wish tymon would push that fix to the master in the meantime so I can stop customizing external libraries inside the scope of my project

thank for the hard for tymon! this is much appreciated!

**Comment by aejnsn** [comment]
I feel your pain Daniel. I'm going to fork and rework. This isn't meeting the JWT spec, yet Tymon has one of the better libraries.

**Comment by tymondesigns** [comment]
I guess I could patch this on master for you guys.. is it just the `iat` `exp` etc, not casting to an int that's causing your issues?

**Comment by aejnsn** [comment]
That's pretty much it. Thanks man!

**Comment by tymondesigns** [comment]
Ok, no worries.. I'll get that up when I get home later

**Comment by tymondesigns** [comment]
`0.5.6` released

**Comment by o15s19** [comment]
Thx

**Comment by dani3l** [comment]
woohoo! thank you :)
