### ISSUE TITLE
user not found exception

### ISSUE THREAD

**Issue by derdida** [tymondesigns/jwt-auth#317]
Hello,

first thanks for this great authentication module, but ill got some problems integrating it as middleware in Laravel5.x

When a user authenticates over active directory, ill update my local user with an table column called "token" - and insert the created token.

.......
$token = JWTAuth::fromUser($user);
$user->token = $token;
$user->save();

So there is now i token, and i would like to check in my RESTful service which user is that. So when ill added your middleware 

Route::get('jobs/all', ['middleware' => 'jwt.auth', 'uses' => 'JobController@all']);

ill always receive the error "user not found".

When ill use a custom Middleware, the token is there (and its same same on in my database).

Where can ill tell jwt-auth to check which user object is the token? is that the field:

    'identifier' => 'token',

In the jwt.php config? 

Thanks in advance!

**Comment by tdhsmith** [comment]
The standard usage is that you transmit the JWT *from the front-end client*, either as an HTTP header or as a query string parameter. The `jwt.auth` middleware calls `parseToken` with default arguments: it will first check for a header of the format `Authorization: Bearer %s` and then for a URL parameter named 'token' (`?token=%s`). If it finds neither it will fail.

You don't *have* to use headers or query strings, (you can retrieve the token in your own way and then set it with `JWTAuth::setToken($token)`), but it is pretty rare to use a different format.

**Comment by tymondesigns** [comment]
assume this is resolved
