### ISSUE TITLE
Error to compiled config

### ISSUE THREAD

**Issue by devswert** [tymondesigns/jwt-auth#320]
Hi!,
I used this package for make an API on Laravel 5.1, when I push my commits in production server,it make an optimization of Laravel and caching files, between the process it exec `php artisan config:cache`. But when I do a request I get `Fatal error: Call to undefined method Closure::__set_state()`. This message occurred in the config when instance auth and cache how an anonymous function.

**Comment by jadjoubran** [comment]
Hi @devswert 
This is a duplicate of #203 
You can apply my fix in the comment

**Comment by devswert** [comment]
Oh, thanks @jadjoubran! It's works
