### ISSUE TITLE
JWTAuth can't retrieve users from mongodb database

### ISSUE THREAD

**Issue by paulocoghi** [tymondesigns/jwt-auth#326]
## Scenario / Laravel 5
I am using [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) and its custom Eloquent class within models:

```php
// use Illuminate\Database\Eloquent\Model;
// 
// class User extends Model {}

use Jenssegers\Mongodb\Model as Eloquent;

class User extends Eloquent {}
```

Mongo operations are working fine.

To JWTAuth, I configured `'identifier' => '_id'` and `'jwt.auth'` middleware in some routes.

## The issue

JWTAuth can't retrieve users from database.

_Methods like `JWTAuth::attempt` and `JWTAuth::parseToken()->authenticate()` always fail._

Therefore I created a custom method `UserController@login` that works perfectly and generates a token only for validated requests (mentioned in the end).

But subsequent ajax calls returns the error `user_not_found` with the provided tokens for protected routes.

## Possible resolution

The problem maybe is that `EloquentUserAdapter` from *jwt-auth* uses the default Eloquent class, but changing it to `Jenssegers\Mongodb\Model` does not solve the problem.

_(I tried the suggestions in #88, with no progress also)_

---

```php
// UserController@login

public function login(Request $request)
{
    $credentials = $request->only('email', 'password');

    if ( $user = User::where('email', '=', $credentials['email'])->first() )
    {
        if ( !Hash::check($credentials['password'], $user->password ) )
            return [ 'error' => true ];
        else
        {
            $token = JWTAuth::fromUser($user);

            return [ 'error' => false, 'data' => ['token' => $token] ];
        }
    }
    else
        return [ 'error' => true ];
}
```

**Comment by tymondesigns** [comment]
looks to be solved now based on answers in #322 ?
