### ISSUE TITLE
Cannot use password in $hidden array in model

### ISSUE THREAD

**Issue by munteanalexandru** [tymondesigns/jwt-auth#328]
When i put password in the $hidden array in laravel model, it doesn't work anymore. I think because this works like select * from user where email = email , so when i hide the password, it cannot compare it anymore. Shouldn't be something like select * from user where email = email and password = password ?

Also, there is a $this->password variable which i think it should be in the jwt.php config file. For example, my app database column is called Password and i had to modify the library in order to make it work.

**Comment by tdhsmith** [comment]
`$hidden` should only affect which fields are visible in a model's array/JSON format; it doesn't affect whether a field can actually be queried/retrieved/mutated.

> Also, there is a $this->password variable which i think it should be in the jwt.php config file.

What method are you using? `JWTAuth::attempt()` already allows you to pass whatever credential key-value pairs you like, so you can use `['Password' => $password]`. None of the other methods involve credentials.
