### ISSUE TITLE
Create JWTs without expiration

### ISSUE THREAD

**Issue by fe-slewis** [tymondesigns/jwt-auth#329]
Is there a built-in method to not force a token to have an expiration? Its seems that the required_claims config var is only for validation and does not get used for creation of tokens, so there's no way to create a token without an exp claim. I've worked around the problem by overriding the tymon.jwt.validators.payload binding in my own provider, then extended the PayloadValidator class and redefined the validateTimestamps method so that it doesn't throw an exception on an expired token. However, unless a JWT with no exp is against the spec could there be an easier way to handle this? Thanks!

**Comment by tdhsmith** [comment]
Already included on the develop branch. (#192, #273, #285)

(I think all of the claims are *technically* optional [according to the spec](https://tools.ietf.org/html/rfc7519#section-4.1.4), but many 3rd-party services require at least `iss`, `iat`, and `exp`.)

**Comment by fe-slewis** [comment]
@tdhsmith Thanks for the info, and thanks to @tymondesigns and contributors for the great package. Cheers!

**Comment by josuecamelo** [comment]
Try

https://github.com/josuecamelo/jwt-token-quase-eterno/blob/master/Implementacao.php
