### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by Mindstormer619** [tymondesigns/jwt-auth#332]
In here: https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens

There's the first example for Laravel 5 where this line appears:
(this also appears in the example for Laravel 4)

```php
        // all good so return the token
        return response()->json(compact('token'));
    }
```

Now here, wouldn't the correct response line be this?

```php
return response()->json(compact($token))
```

As written in the documentation right now, I would expect `compact('token')` to transform the string "token" into an array for the response. However, `$token` is the variable that actually contains the contents of the token.

Note that I have not actually run the example yet, still working through some setup. Basically noticed this as I was copying out the example by hand. The example _might_ work as written, but in that case PHP is confusing me more than I thought :sweat_smile:

**Comment by dukejib** [comment]
no need to use compact with json. just send json or compact , both convert data into json format.
personally, i use my own custom response, with objects like respons;error;type etc

**Comment by tdhsmith** [comment]
> As written in the documentation right now, I would expect compact('token') to transform the string "token" into an array for the response. However, $token is the variable that actually contains the contents of the token.

PHP's `compact` is an unusual command. ([Check out the official docs.](http://php.net/manual/en/function.compact.php))  It converts a list of variable **name** arguments into an array of key-value pairs:

```php
$cat = 'Abyssinian';
$pet = 'cat';

echo compact('pet', $pet);
// returns ['pet' => 'cat', 'cat' => 'Abyssinian'];
```

Notice the *string* `'pet'` returns the value of `$pet`, while the *variable* `$pet` returns the value of the variable with name equal to the *value* of `$pet` (`$cat`).
The command in the docs is thus equivalent to:

```php
return response()->json(['token' => $token]);
```

...which is how I tend to write it (I'm not a big fan of `compact`'s behavior myself). So it should work as written. Thanks for the critical eye though! :+1:

**Comment by tdhsmith** [comment]
> just send json or compact , both convert data into json format.

To be technical about it, `compact` only returns array data. It's Laravel that's automatically converting your responses with array data into JSON. This is robust enough to rely on (I've been known to return unwrapped arrays and Eloquent models as responses myself), but it might be important to remember if you switch to another framework that doesn't do it. :stuck_out_tongue:

**Comment by tymondesigns** [comment]
@tdhsmith is right.. there are many ways to return a response.. `compact` is just a convenience to form an array of a matching key/variable. 

It's just a simple example in the docs. Personally I would use slightly more robust response methods. As @dukejib hinted at. But of course it is project dependent :smile:
