### ISSUE TITLE
Modifying header key from "Authorization" to "anything"

### ISSUE THREAD

**Issue by vivex** [tymondesigns/jwt-auth#333]
Any config option to do so?

**Comment by jadjoubran** [comment]
Curious question: why?

**Comment by tdhsmith** [comment]
Yes actually, [you can pass arguments in to `parseToken`](https://github.com/tymondesigns/jwt-auth/blob/master/src/JWTAuth.php#L191). Something like:

```php
JWTAuth::parseToken('bearer', 'anything');

// normal JWTAuth commands here...
```

**Comment by tymondesigns** [comment]
@tdhsmith other way around :smile: 

```php
JWTAuth::parseToken('anything', 'bearer');
```

Note that this will change in the upcoming release, and you would have to update this in a service provider, e.g.

```php
// in register method
app('tymon.jwt.parser')->setHeaderName('anything');
```
