### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by dukejib** [tymondesigns/jwt-auth#334]
Updated jwt-auth today , previously working system is now broken.

Freshly fetched Token via post is returning 500 Internal Server Error upon get request.

**Comment by tdhsmith** [comment]
Can you identify the exception or provide a stack trace? What versions did you update from & to?

**Comment by dukejib** [comment]
i am using it with android app and test it with firefox extension "Http Requester" and both are returning 
500 Internal server error. 
When i post with credentials, i get my token, but that token isn't usable for any other post or get.

Exact Error Data:
HTTP/1.0 500 Internal Server Error
Date: Mon, 07 Dec 2015 19:55:43 GMT
Server: Apache/2.4.12 (Ubuntu)
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8

i think its upgraded to 0.5.6 ( I am on Laravel 5.1) (Not deliberate update, was updating composer and instead of using composer selfupdate, i typed composer update )

**Comment by tymondesigns** [comment]
We need the stack trace to provide any meaningful help here...

**Comment by dukejib** [comment]
no stack trace (laravel is on debug) just this error.

**Comment by tymondesigns** [comment]
You are probably suppressing the exception somewhere, so you would need to remove that behaviour temporarily to let the exception bubble up, if you know what I mean?

**Comment by dukejib** [comment]
i do understand what you are saying. but no exception is getting suppressed. 

Anyway, i totally removed the laravel app folder and used an earlier backup (with older jwt-auth) and now its working fine. 
I guess , the latest update was messing up. 
Thanks for your time.
