### ISSUE TITLE
Finer-grained exception-catching in default auth provider

### ISSUE THREAD

**Issue by tdhsmith** [tymondesigns/jwt-auth#335]
@tymondesigns what kinds of exceptions are you trying to avoid in the Illuminate auth provider [here](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Providers/Auth/Illuminate.php#L56)?

I ask because I just debugged a situation where we stopped implementing `Authenticatable` on our User model, which caused an exception in Guard (`ErrorException: Argument 1 passed to Illuminate\Auth\Guard::setUser() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\User given`) that got suppressed by the catch-all-return-false. It didn't end up providing too hard to solve thanks to git rollbacks, but it was confusing for a bit for all `toUser` calls to return false instead of an error.

**Comment by tymondesigns** [comment]
It was a while ago :smile: there was a reason but can't think what it was atm. 

Anyways I can't think of a reason not to change it off the top of my head. I will have a dig around to try and refresh my memory

**Comment by tdhsmith** [comment]
Maybe at one point the Auth retrieval methods threw an exception instead of returning false when they couldn't find a user? (I don't really feel like digging in Laravel git history just to find out though... at least not on a Friday, ha.)

**Comment by tymondesigns** [comment]
So I've removed the try catch block and all looks good on my end, allowing the exception to bubble up now :+1:

**Comment by tdhsmith** [comment]
Thanks for looking into that!
