### ISSUE TITLE
Last Token Blacklisted using token.refresh on middleware

### ISSUE THREAD

**Issue by weblee** [tymondesigns/jwt-auth#336]
I cant for whatever reason get past the token being blacklisted after the second request. I am using latests version 5.* for Laravel.

I have a web login form which on success returns my token. I then perform a second requested to get the users data with example below code which works fine. It only fails after I perform a refresh on the page getting some user data.

```
public function getCurrentUser(Request $request)
    {
        return JWTAuth::parseToken()->authenticate();
```

I have console.log the tokens being sent in and returned form the header and everything looks good.  Here is the example console logs.

```
Login Success Setting token = eyJ0eXAiOiJKV1Q....J23JYUps
Getting User
Send Request Token = Bearer eyJ0eXAiOiJKV1Q....J23JYUps
Setting Request token = Bearer eyJ0eXAiOiJKV1....9kGWJGR0
Navigated to http://dashboard.domain.app/
Getting New Data
Send Request Token = Bearer eyJ0eXAiOiJKV1....9kGWJGR0
GET http://dashboard.domain.app/api/dashboard/data 500 (Internal Server Error)
```

If I look at the network for the last GET request I can see it using the last return token.
```
GET /api/dashboard/data HTTP/1.1
Host: dashboard.domain.app
Connection: keep-alive
Cache-Control: max-age=0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
Accept: application/json
X-CSRF-TOKEN: im9laCT9sv1RjWaBnJuOOMHadnRsfI0y5eZvnBZ6
Authorization: Bearer eyJ0eXAiOiJKV1....9kGWJGR0
X-Requested-With: XMLHttpRequest
Referer: http://dashboard.domain.app/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
If-None-Match: "c641d90f0bf310df0997e8ce8683aaff"
```

I have for now set blacklist to false as I am only in development mode  which resolves my problem for now. Can you think why I am getting this issue? I have 100%  confirmed all my requests via the console and have tripled checked the Token being sent and saved for the next request.

Using the Dev branch sounds like the way to go as I do want to have multiple Ajax requests on one go and don't want to wait on a promise for the next call. Reading the discussions it looks like dev branch will resolve this.  Is there a guide on setting up the dev branch? I can see I need a new app provider but cant see what else has changed or required actions to work with it.

Hope you can advise !

**Comment by tymondesigns** [comment]
Firstly, what middleware (if any) do you have applied to your routes ?

**Comment by weblee** [comment]
I have.

```
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
    ];

    protected $routeMiddleware = [
        'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
        'jwt.refresh' => \Tymon\JWTAuth\Middleware\RefreshToken::class,
    ];
```

The ttl (60) & refresh_ttl (20160)  standard

**Comment by tymondesigns** [comment]
I mean what routes are they being applied to? For example do you have both middlewares applied to the same route?

**Comment by weblee** [comment]
Here ya go.

```php
$api->version('v1', function ($api) {

    // Set our namespace for the underlying routes
    $api->group(['namespace' => 'App\Api\V1\Controllers'], function ($api) {

        // Login route
        $api->post('auth/login', 'AuthController@authenticate');
        $api->post('auth/register', 'AuthController@register');

        $api->group( [ 'middleware' => 'jwt.refresh' ], function ($api) {
            $api->get('users/me', 'UsersController@getCurrentUser');
            $api->get('validate_token', 'AuthController@validateToken');
        });

    });
});
```

**Comment by tymondesigns** [comment]
ok, and does the `UsersController` have the `jwt.auth` middleware added?

Sorry for the repetitive questions, but I am trying to determine whether your issue is in-fact the same as described in #186 & #83 and that was fixed in #218

**Comment by weblee** [comment]
OK so no I have not added the middleware in the construct.  Are you meaning like.

```php
    public function __construct() 
    {
        $this->middleware('jwt.auth');
    }
```

If so this could be the issue!

**Comment by tymondesigns** [comment]
Yes if both `jwt.auth` and `jwt.refresh` run on the same route, then you will experience the issue described here https://github.com/tymondesigns/jwt-auth/issues/186#issuecomment-147816841. and you will need to use the `0.6.*@dev` release to get around that.

**Comment by weblee** [comment]
Well if so thats not the problem then as I have stated I didn't add the extra middleware. So I am just running the refresh middleware.

Im going to run with the dev branch I think. Can you describe the setup for it please?

**Comment by tymondesigns** [comment]
I misunderstood you there then..

So first step is to implement the [`JWTSubject`](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Contracts/JWTSubject.php) Contract on your User model and implement the required methods. Also you should delete the config and re publish it.

The rest is dependent on what methods you are using. But I would start there and see if everything works as expected.

**Comment by weblee** [comment]
OK,

Thanks for your time. I will close this off for you and try the dev branch.
