### ISSUE TITLE
How to get the token in POST method

### ISSUE THREAD

**Issue by kbchandiran** [tymondesigns/jwt-auth#337]
jwt-auth middleware read the token in url only? I need to configure it also need to read it in post method also..

**Comment by tdhsmith** [comment]
It reads the `Authorization` header looking for a value formatted like `Bearer $token` first before checking the url. The HTTP headers are by far the most commonly used way to pass JWTs.

See [the docs on authentication](https://github.com/tymondesigns/jwt-auth/wiki/Authentication) and [the `parseToken` function](https://github.com/tymondesigns/jwt-auth/blob/master/src/JWTAuth.php#L191) for more details.

**Comment by kbchandiran** [comment]
Thanks for your time...
