### ISSUE TITLE
Error handling in dev-master branch?

### ISSUE THREAD

**Issue by cviebrock** [tymondesigns/jwt-auth#338]
I've recently converted from the stable branch over to develop, in order to take advantage of the blacklist grace period feature.

However, all the code I had in place previously in order to send "nice" error messages to consumers of my API doesn't work the way it used to.

I realize that you're in the middle of the 0.6 release and things may not be finalized yet.  But is there any chance of providing a basic update on how to handle errors in the new version? Like, relevant changes to https://github.com/tymondesigns/jwt-auth/wiki/Authentication#global-exception-handling

**Comment by cviebrock** [comment]
FWIW, I was previously using this in my `EventServiceProvider.php`:

```php
    protected $subscribe = [
        JWTExceptionListener::class,
    ];
```

And that class basically contained a subscribe method and other methods such as:

```php
    public function subscribe(Dispatcher $events)
    {
        $events->listen('tymon.jwt.absent', __CLASS__. '@absent');
        $events->listen('tymon.jwt.expired', __CLASS__. '@expired');
        $events->listen('tymon.jwt.invalid', __CLASS__. '@invalid');
        $events->listen('tymon.jwt.user_not_found', __CLASS__ . '@userNotFound');
    }

    public function absent()
    {
        return response()->json(['message' => \Lang::get('jwt.absent')], 401);
    }

    // ... etc.
```

Not the most elegant of solutions, but I planned on refactoring it at some point.

**Comment by tymondesigns** [comment]
The reason your code is no longer working is that the events have been removed in the new version. 

Depending on your middleware, you would still be able to catch the exceptions (as described in the current Global exception handling section of the wiki) 

Using the new `Authenticate` [middleware](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Middleware/Authenticate.php) as an example. It catches all jwt specific exceptions and throws a new Symfony http specific exception, in this case `Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException` which you can then catch and respond accordingly. So in this case you would return a 401 unauthorized response.

Hope that helps

**Comment by cviebrock** [comment]
Works for me!  Any timeframe on the 0.6 release (or even some documentation on it)?

**Comment by efriandika** [comment]
Hi, can you provide me how to use dev-develop Middleware.? i want to take advantage of the blacklist grace period feature.

**Comment by tymondesigns** [comment]
Docs coming soon. It will now be a 1.0.0 release
