### ISSUE TITLE
Can't install via Composer for Laravel v5.0.*

### ISSUE THREAD

**Issue by drawmyattention** [tymondesigns/jwt-auth#34]
Doesn't look like the package can be installed for the newly released Laravel 5 release.

    Your requirements could not be resolved to an installable set of packages.

     Problem 1
    - Conclusion: remove laravel/framework v5.0.0

This is with a fresh install of Laravel 5, with no other dependencies defined in Composer except this package.

**Comment by tymondesigns** [comment]
you're using the `dev-laravel-5` release right?

**Comment by drawmyattention** [comment]
*blush* well that's embarrassing. I am however stuck at the config:publish step (i'm trying to use publish:config, as I think the command was changed in L5), but it results in a 'There are no commands defined in the "publish" namespace' error

**Comment by tymondesigns** [comment]
No worries ;)

About the command. I'm in the process of writing up some new documentation to go with the new releases when I do send them out. Currently the way to publish the config is via:
`php artisan vendor:publish` - see https://github.com/tymondesigns/jwt-auth/issues/13#issuecomment-72849052

**Comment by NikhilRadadiya** [comment]
Not able to publish config file. Laravel version is 5.2.* ,Tried 
1. $ php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
2. php artisan vendor:publish
3. php artisan publish:config tymon/jwt-auth
