### ISSUE TITLE
Problem with Doctrine

### ISSUE THREAD

**Issue by matiux** [tymondesigns/jwt-auth#343]
I use Laravel-Doctrine package (https://github.com/laravel-doctrine/orm) so, I don't use Eloquent model, but Doctrine entities.

This is my jwt.php

```
....
'user' => 'Acme\Repository\UserRepository',
'identifier' => 'id',
'providers' => [
'user' => 'Acme\Tymon\JWTAuth\Providers\User\DoctrineUserAdapter',
]
....

```

This is a test:

```
/** @var $user Entity\User */
$user = $this->userRepo->findAll()[0];

$token = \Tymon\JWTAuth\Facades\JWTAuth::fromUser($user);
```

I get this error:

Cannot access protected property Acme\Entity\User::$id in /var/www/Adrias/MailWin/Lando/vendor/tymon/jwt-auth/src/JWTAuth.php on line 84

obviously, $id is protected. I should use $user->getId();

**Comment by tdhsmith** [comment]
Yes it's definitely due to the `$id` being protected. On the develop branch this access doesn't happen directly. Instead you implement the `JWTSubject` interface with a `getJWTIdentifier()` function, which in your case could simply return `$this->getId()`.

On v0.5, I'm not as sure. You might be able to get by with a dynamic attribute on your user model? Set the `jwt.identifier` to something unused like `id_refelector` and then give the model a `getIdReflectorAttribute()` that returns `$this->getId()`. I haven't thought through all the implications yet.

Speaking of implications, you might have some trouble with the `Auth::onceUsingId($id)` stuff once you get to authenticating tokens... Let me know what happens as you continue.

**Comment by matiux** [comment]
I have solved using dev branch.

in jwt.php I have setted
```
 'auth' => 'Acme\Repository\UserRepository',
```

and my User Entity implements JWTSubject, AuthenticatableContract

**Comment by rochapablo** [comment]
Hey...

I'm really trying to understand this, but I'm stuck in this error:

> Argument 1 passed to Tymon\JWTAuth\Providers\User\EloquentUserAdapter::__construct() must be an instance of Illuminate\Database\Eloquent\Model, instance of App\...\Models\User given

I'm chancing from Eloquent to Doctrine and this is my auth.php

```
'model' => App\Sistemas\Aplicacao\Base\Models\User::class
``´

the jwt.php

```
'user' => 'App\Sistemas\Aplicacao\Base\Models\User',
```

So, what can I do?

**Comment by tdhsmith** [comment]
Since you aren't using Eloquent, you'll need to change JWT's "user provider" to a custom class (that satisfies `Tymon\JWTAuth\Providers\User\UserInterface`). Just take [the existing `EloquentUserAdapter`](https://github.com/tymondesigns/jwt-auth/blob/master/src/Providers/User/EloquentUserAdapter.php) and modify it so that `getBy` returns an instance of the user.

Afterwards, change your config value for `jwt.providers.user` to the name of the class (i.e `App\JWTAuth\Providers\DoctrineUserAdapter::class` or whatever it ends up being).

It might be a little weird, since the user adapter has a very slight active record tilt to it.

**Comment by tdhsmith** [comment]
This is a *total* guess because I'm not that familiar with Doctrine, but I think the class would generally be like this:

```php
use Doctrine\ORM\EntityManagerInterface;
class DoctrineUserAdapter implements UserInterface
{
    protected $em;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->em = $entityManager;
    }

    public function getBy($key, $value)
    {
        return $this->em->find('App\Sistemas\Aplicacao\Base\Models\User', $value);
        /* 
         * Note that I'm ignoring $key because it's almost always 'id', but if you
         * have a different jwt.identifier (that isn't your entity identifier) you'll need
         * to do something more complex here, potentially involving a repository.
         *
         * Also the entity class is hard-set in this example, but you could read it
         * from your config or have a setter to make it a more general solution.
         */
    }
}
```

In 0.6, this is all irrelevant because the user provider is gone, and it's instead handled by the auth provider and the `JWTSubject` interface.

**Comment by rochapablo** [comment]
Thanks, took me a little but i finally did and worked.

**Comment by morfin** [comment]
Just to clarify @matiux Doctrine solution.

If you're using latest 0.6.*@dev, you don't need to override the auth property.

@matiux suggested:
```
 'auth' => 'Acme\Repository\UserRepository'
```
With latest code you can leave the default:
```
'auth' => Tymon\JWTAuth\Providers\Auth\Illuminate::class
```

You just need to implement Tymon\JWTAuth\Contracts\JWTSubject in your User Entity, and then define the interface methods like this:
```
public function getJWTIdentifier(){
       // Assuming you have a getter method for the ID.
        return $this->getId();

    }

    public function getJWTCustomClaims(){
        return [];
    }
```

**Comment by LuisMejiaF** [comment]
Hi @morfin , what your mean for version 0.6? It seems to me that this repository doesn't have a 0.6 release, it jumps from 0.5.9 to alpha. 

I'm trying to implement the JWTSubject contract, but is not present in the 0.5.9 release.

**Comment by tdhsmith** [comment]
> what your mean for version 0.6? It seems to me that this repository doesn't have a 0.6 release, it jumps from 0.5.9 to alpha

Version 0.6 was renamed version 1.0 a few months ago.

> I'm trying to implement the JWTSubject contract, but is not present in the 0.5.9 release.

Then don't implement it? It's only part of v1.0. In v0.5 you can follow the normal instructions...

**Comment by LuisMejiaF** [comment]
Ok, thanks for the clarification is the versions. 

So I guess it means I need to try with the 1.0 version. The thing is that I'm using Doctrine and not Eloquent, and for what I have seen in this thread, I need to implement the JWTSubject contract. 

5.* versions doesn't even have a Contracts folder.

**Comment by tdhsmith** [comment]
I believe my earlier comments ended up being correct:

- _Regardless of version_, first you will need to make sure Laravel's "user provider" is set up correctly to work with Doctrine. If you're using something like laravel-doctrine/orm, this should be provided.

- On 0.5, you will need to make a custom jwt-auth user provider (this is distinct from the Laravel one above, which powers the whole auth system) satisfying [`Tymon\JWTAuth\Providers\User\UserInterface`](https://github.com/tymondesigns/jwt-auth/blob/master/src/Providers/User/UserInterface.php). This class only needs to do the equivalent of a where-query on your users and return it. I gave an example of what I _thought_ it might need to look like above, but it was never verified. Once you've implemented that, set `jwt.providers.user` to the classname.

- On 1.0, you should be able to get by merely implementing `JWTSubject` correctly.

Obviously the 1.0 route is a little less involved, but with the drawback that the installation isn't officially documented yet, and is slightly different from 0.5.
