### ISSUE TITLE
On token expire returning wrong status code.

### ISSUE THREAD

**Issue by mrgodhani** [tymondesigns/jwt-auth#344]
Hi

On token expire it is returning wrong status code. Instead of returning 401 it is returning 400 bad request. Any idea how to fix?

**Comment by tdhsmith** [comment]
Well, I would actually argue that 400 is the correct status code. Having an expired token says nothing about whether you *as a user* are authorized or not (which would be a 401), it merely says you could not communicate your authorization correctly on this attempt (your request was bad).

That said, if you want to change the messages, just create your own copy of the relevant middleware and replace the `$e->getStatusCode()` with whatever specific code you'd like. (for example [see here in `GetUserFromToken` which is what most people use as `jwt.auth`](https://github.com/tymondesigns/jwt-auth/blob/master/src/Middleware/GetUserFromToken.php#L26))

**Comment by mrgodhani** [comment]
Hm so I can just use same code and create middleware. FYI I also use dingo api.

**Comment by tymondesigns** [comment]
Yep.. Just implement your own middleware and return any response code you like
