### ISSUE TITLE
JWTAuth refresh

### ISSUE THREAD

**Issue by igostavro** [tymondesigns/jwt-auth#351]
Getting an exception when trying to refresh a token manually or via the middleware:

```
ErrorException (E_NOTICE)

Array to string conversion
    <path>/tymon/jwt-auth/src/PayloadFactory.php
         * @return string
         */
```
```php
    protected function jti()
    {
        $sub = array_get($this->claims, 'sub', ''); <--- sub is an array after this line
        $nbf = array_get($this->claims, 'nbf', '');
 
        return md5(sprintf('jti.%s.%s', $sub, $nbf)); <--craps out here
    }
``` 
the debugger shows that $this->claims["sub"] is an array

Laravel Framework version 5.1.26 (LTS)
In my composer.json:
"tymon/jwt-auth": "0.5.*"

Thanks in advance!

**Comment by tdhsmith** [comment]
That's pretty strange. Did you ever figure this out? Was `sub` an array before that point?

You might be able to coerce the payload factory into building a token with an array-valued claim (probably easier in 0.5 than 0.6 anyway), but it's strange that this would only happen on refresh. Maybe Namshi parses strings into arrays if they're JSON style? That would be odd too...

**Comment by tdhsmith** [comment]
In any case, if you have an example token that does this, it might help.

**Comment by tymondesigns** [comment]
@igostavro did you resolve this?

**Comment by igostavro** [comment]
Never seemed to happen again. Not sure what caused it.

Thanks for the help though:)

Sent from my iPhone

On Mar 10, 2016, at 4:19 AM, Sean Tymon <notifications@github.com<mailto:notifications@github.com>> wrote:


@igostavro<https://github.com/igostavro> did you resolve this?

-

**Comment by Abdulhmid** [comment]
i'm still error like this "Array to string conversion", anybody can help me ,

**Comment by Abdulhmid** [comment]
@igostavro  can u help me ?

**Comment by Abdulhmid** [comment]
@tymondesigns ?

**Comment by anasinfo** [comment]
aslam 
what help do u want ?? in laravel??ahmed
 Disclaimer : "Information transmitted by this e-mail and attachments may be proprietary to Dr. Chishti Mahboob Ahmed., and/or the authors of the information and is intended for use only by the individual or entity to which it is addressed and may contain confidential or legally privileged information. Unauthorized use, disclosure or copying is strictly  prohibited and may constitute unlawful act. Internet communications cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, arrive late or contain viruses. www.coremed.x10.bz 

    On Friday, 20 May 2016 12:44 PM, Abdul Hamid <notifications@github.com> wrote:
 

 @igostavro can u help me ?—
