### ISSUE TITLE
How can I refresh or remove all the tokens generated by an user id?

### ISSUE THREAD

**Issue by Al3xR0** [tymondesigns/jwt-auth#352]
I saw that if I refresh the current token, the token cannot be used anymore.

Can I do this for all tokens that have an specific user id?

I want to make a single login, so If a user logins will refresh/remove the other one token.

**Comment by tdhsmith** [comment]
See my responses in #310, #300. 

The system doesn't know which tokens exist, so you can't invalidate them with only the user id.

You'll either need access to all of a user's tokens, probably by storing them, or you'll have to impose an additional security restriction, for example saving a `last_login` time and using custom middleware to require that all tokens are issued after this date to be valid (comparing with the token's `iat` claim).

I think the latter solution is the cleaner one, but I don't use either personally.

**Comment by Al3xR0** [comment]
:+1: This is a great idea. Thank you very much. 

I will use the solution with the last_login field because is more cleaner than having a database table with all the tokens.
