### ISSUE TITLE
Refresh-token blacklist question.

### ISSUE THREAD

**Issue by HeyHugo** [tymondesigns/jwt-auth#354]
Hi, I'm looking at some different JWT solutions and maybe I have not quite understood how the flow with refresh token and blacklist works. But I'm thinking it would be better to just keep a "white-list" of long lived refresh tokens that are valid instead of adding invalidated ones to a growing blacklist?

**Comment by tymondesigns** [comment]
The blacklisted tokens are purged automatically when their exp time is reached (unless you blacklist a token forever).

So I think its more likely that a token "whitelist" would grow quicker than the blacklist does right now, obviously that's dependant on your config

**Comment by HeyHugo** [comment]
Ah of course, I didn't think about the redis purging. Thanks for your answer.

**Comment by gayanhewa** [comment]
How does the purging happen? Do I need to have something scheduled for this to get triggered?
