### ISSUE TITLE
the session closes suddenly

### ISSUE THREAD

**Issue by ekaitzastiz** [tymondesigns/jwt-auth#355]
Hi, I am using your package, an it seems to work fine, so I am not sure if it's something wrong in server-lumen side, or in angular-client side...
I did an app that works with angular, and it works against an API developed with lumen, where I put your package. But sometimes, when I am working in the admin planel, it takes me out from the panel, I mean, session is closed. I don't know why, no idea. But it's not relatedto the session or token valid time, sometimes I log in and I happens in 5 or 10 minutes.

In angular I am using satelizer...

I based on the next tutorials:
http://laravelista.com/json-web-token-authentication-for-lumen/
https://scotch.io/tutorials/token-based-authentication-for-angularjs-and-laravel-apps

**Comment by sagaio** [comment]
+1
Also experiencing similar issue. I'm using brower-sync and sometimes when it refreshes I'm suddenly in a logged out state, no errors or anything. This usually happens after being logged in for about 2-10 minutes.

**Comment by ekaitzastiz** [comment]
After writing here, last week, I read the next information, but is not exactly the same, because as I said, I don't see any error, the time when it happens it's when short time is passed from session start...So, I updated satellizer, now I see there it happening few times, but It happens...may be, I will have to implement the solution of buffering request...but I am not sure, because I as said, I don't see any error, so how I know when to buffer/queue them and re-call them. Maybe if you read it you understand it.

https://github.com/sahat/satellizer/issues/58

https://github.com/sahat/satellizer/issues/60

**Comment by capitaladot** [comment]
+1
Session seems to be empty. spare "_token", after something like 100 requests (video conferencing application doing polling of hardware on the server and reporting it to an Angular.js front end).

**Comment by tdhsmith** [comment]
Session on the front-end or the back-end? Though in either case it's almost certainly doesn't have to do with this library. JWT-Auth doesn't use Laravel sessions and issues with Satellizer should be redirected to them.

**Comment by capitaladot** [comment]
Figured out my issue was actually too short a cookie payload field.

**Comment by tdhsmith** [comment]
Thanks for the follow-up! :smiley:
