### ISSUE TITLE
I keep getting errors when verifying a user.

### ISSUE THREAD

**Issue by humbleBeginner** [tymondesigns/jwt-auth#356]
My users table is not using the default field e.g. username, password, email. Instead every field has a str appended to them, e.g. strUsername, strPassword. And I keep getting 'Undefined index password'

Here's my login controller for the API I'm building.
![err2](https://cloud.githubusercontent.com/assets/7194216/11940676/1d232168-a865-11e5-811d-758e60e20e5f.PNG)

Here's the user model.
![err3](https://cloud.githubusercontent.com/assets/7194216/11940754/acd0b348-a865-11e5-9411-a07c657edaec.PNG)

And the output, using postman
![err1](https://cloud.githubusercontent.com/assets/7194216/11940957/076f34ea-a867-11e5-9f34-1cb40f22fbef.PNG)

**Comment by jadjoubran** [comment]
Lucky guess: have you tried renaming `strPassword` to `password`?

**Comment by tdhsmith** [comment]
Laravel's default `Auth` provider uses providers (i.e. `EloquentUserProvider`) that expect your credential array to always have a `password` field. However [this will still get compared with the correct field](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/EloquentUserProvider.php#L114), as long as you've set up the `getAuthPassword` method correctly.

So yes, changing/duplicating the key from `strPassword` to `password` in the credentials array should work. You shouldn't need to change your DB or model.

**Comment by humbleBeginner** [comment]
I am not allowed to modify the database because it was used by an existing website. And I'm developing a hybrid mobile for it to share with the same database. @tdhsmith and @jadjoubran thanks for the help, I have tried you're suggestions but still no luck. I have also changed <a href="https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/EloquentUserProvider.php#L114">this</a> to strPassword and still not working.

**Comment by tdhsmith** [comment]
Sorry I didn't notice you are using the `Authenticatable` trait on `User`. You should be overriding the `getAuthPassword()` function to `return $this->srcPassword`. [Otherwise it will try to return the nonexistent password field.](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/Authenticatable.php#L24) (That's what I meant by setting it up.)

**Comment by tdhsmith** [comment]
But something should've changed about the error either way, since that was the exact line mentioned in the error?

**Comment by humbleBeginner** [comment]
The error now was `{error: 'invalid credentials'}`, returned by the controller. I am pretty sure that my creds are correct.

**Comment by thorne51** [comment]
@humbleBeginner How did you get around the 'invalid credentials' error? I've been struggling with this for a day now and can't seem to figure out why JWTAuth::attempt() isn't working. I've even loaded the model through tinker and manually verified that the values are correct.

**Comment by hjJunior** [comment]
I with the same problem here, I even tried to use `getAuthPassword` to my custom column, but just work if I keep the name of column in database as 'password'
