### ISSUE TITLE
Key generation not working

### ISSUE THREAD

**Issue by LukasMa** [tymondesigns/jwt-auth#357]
Hi, the "artisan jwt:generate" command does not work. It says "jwt-auth secret [xxxx] set successfully", but I can't see that the key is actually set anywhere. Not in the config, nor in the .env file.

**Comment by LukasMa** [comment]
Okay quick update: I fucked up. I modified my jwt-config file and set the default hash to NULL. However, I would prefer, if the ´´´jwt:generate ´´´ command would set the hash in the env file. Changing the hash in the config file, will always break my git repository on my webserver because git won't let me pull if local changes are detected. Sure, I could work around that, but I think that's not how it's supposed to be.

**Comment by jadjoubran** [comment]
Hi @LukasMa 
This has been fixed here #311 
It'll be available as of version 0.6

**Comment by LukasMa** [comment]
Thanky @jadjoubran ! I looked through the closed issues, but I missed this one :)
