### ISSUE TITLE
In dingo/api, /app/Exceptions/Handler.php can not catch the exception

### ISSUE THREAD

**Issue by khlipeng** [tymondesigns/jwt-auth#359]
In dingo/api,

 /app/Exceptions/Handler.php can not catch the exception

**Comment by Deno028** [comment]
By this way, I can handle the exceptions. Hope it's helpful for you.

In this function, I return json format. You can change it by your own.

 public function render($request, Exception $e)
    {
           if($e instanceof \Tymon\JWTAuth\Exceptions\TokenInvalidException) {
                return response()->json(['error'=>'token_invalid','error_description'=>'The token is invalid']);
            }
            if($e instanceof \Tymon\JWTAuth\Exceptions\TokenExpiredException) {
                return response()->json(['error'=>'token_expired','error_description'=>'The token was expired']);
            }
            if($e instanceof \Tymon\JWTAuth\Exceptions\JWTException) {
                return response()->json(['error'=>'token_absent','error_description'=>'The token was expired']);
            }
            if($e instanceof \Illuminate\Database\QueryException) {
                return response()->json(['error'=>'query_error','error_description'=>$e->getMessage()]);
            }

        if ($e instanceof ModelNotFoundException) {
            $e = new NotFoundHttpException($e->getMessage(), $e);
        }
        if($e instanceof \Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException){
            return response()->json(['error'=>'method_not_allow','error_description'=>'Wrong method called'],$e->getCode());
        }
return parent::render($request, $e);
}

**Comment by khlipeng** [comment]
I did it, it is still not.

**Comment by khlipeng** [comment]
My project ，In exception handling, he would skip  /app/Exceptions/Handler.php

**Comment by ingspadavecchia** [comment]
HI, I have a similar problem. I'm using the middleware, so, no exceptions are thrown. Instead that, I'm catching Events and then I'm throwing the exceptions

check my EventServiceProvider:

```
  public function boot(DispatcherContract $events)
    {
        parent::boot($events);

        // Logging in the user if the token is valid.
        $events->listen('tymon.jwt.valid', function($user) {
            Auth::login($user);
        });

        $events->listen('tymon.jwt.absent', function($user) {
            throw new JWTException("Token not provided", 400);
        });

        $events->listen('tymon.jwt.expired', function($user) {
            throw new TokenExpiredException("Token expired", 401);
        });

        $events->listen('tymon.jwt.invalid', function($user) {
            throw new JWTException("Token invalid", 401);
        });

        $events->listen('tymon.jwt.user_not_found', function($user) {
            throw new JWTException("User not found", 404);
        });
    }
```

I hope that can help you.
