### ISSUE TITLE
Error in cache driver while getting user by token

### ISSUE THREAD

**Issue by rut4** [tymondesigns/jwt-auth#36]
Hello.
When I use JWTAuthMiddleware in routing the following exception throws:
```
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags'
```
I read the same [issue](https://github.com/GrahamCampbell/Laravel-Throttle/issues/13).
It's because I use a file cache driver. The same thing for database cache driver.
What should I use for cache driver?
When I set it to array, I get a token once more, but the 'user_not_found' error occurred.

Package versions:
laravel/framework    v5.0.2
tymon/jwt-auth         dev-laravel-5 

Thank you.

**Comment by agentk** [comment]
Hi rut4,

I've just hit the same error too, submitted pull request #37 .

It was just a missed return statement when abstracting the eloquent query.

**Comment by agentk** [comment]
Also if you want to skip the blacklist checking to be able to use the 'file' cache drive again, you can specify in `.env`:

    JWT_BLACKLIST_ENABLED=false

**Comment by rut4** [comment]
Hi agentk,
Thank you.
But now I have another error.
I installed a memcached, try to use it and I have a 'token_expired' error.
I rollback all changes but error still appearing similarly in the issue #24

**Comment by agentk** [comment]
Hmmm. I'm not actually using memcached or the JWTAuthMiddleware at all in the application I'm testing as it's just a simple API.
If you want to dig into it more, a good place to start would be vendor/tymon/jwt-auth/src/Middleware/JWTAuthMiddleware.php:46
And start with something simple by inserting `dd($token);` to see if it's picking up as expected to start with.

**Comment by rut4** [comment]
I did it.
The first I set `CACHE_DRIVER=memcached` (or one can add `JWT_BLACKLIST_ENABLED=false` as agentk wrote).
Next I change file as well as in the pull request #37 .
And the last one, in my case:
```php
Route::group(['prefix' => 'api', 'middleware' => 'auth.jwt'], function () {
	Route::get('user', function () {
		$user = JWTAuth::toUser(JWTAuth::getToken());

		return response()->json(compact('user'));
	});
});
```
I should use `JWTAuth::toUser(JWTAuth::getToken())` instead of `JWTAuth::getToken()->toUser()` or `JWTAuth::parseToken()->toUser()`.

**Comment by tymondesigns** [comment]
@rut4 Glad you sorted it :)

@agentk thanks for chipping in there :+1: 

I need to look over the token extraction behaviour, to make sure everything is as it should be (with tests!)

**Comment by tymondesigns** [comment]
the following should work:

```
JWTAuth::parseToken()->toUser();
```

it may be preferable to set the request instance if available:

```
JWTAuth::setRequest($request)->parseToken()->toUser();
```
