### ISSUE TITLE
Custom attempt fileds

### ISSUE THREAD

**Issue by diogoazevedos** [tymondesigns/jwt-auth#362]
Is possible attempt with other credentials combination? Example

``` php
$credentials = $request->only('username', 'token');
$token = JWTAuth::attempt($credentials);
```

**Comment by jonagoldman** [comment]
Yes, it's explained in the docs. https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens

**Comment by tdhsmith** [comment]
Welllll `JWTAuth::attempt($credentials)` will mirror whatever you can plug into Laravel's `Auth::once($credentials)`. For default <= 5.1 set-ups, and 5.2 with the session driver, this will successfully retrieve the user, but [it's gonna require the credentials to contain a password for validation](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Auth/EloquentUserProvider.php#L112). :disappointed: 

Is this something you would bother to use with Auth though? (Is that a remember me token?) You can create your JWTs from the user instead.

**Comment by espiro** [comment]
you can create a CustomAuthAdapter for this purpose
witch should implement Tymon\JWTAuth\Providers\Auth\AuthInterface
and in byCredentials method use your own credentials to get a user

do not forgot to change auth in jwt config file with your custom Adapter
