### ISSUE TITLE
JTI claim and therefore tokens are not unique

### ISSUE THREAD

**Issue by MnMTech** [tymondesigns/jwt-auth#364]
I am having an issue when creating multiple tokens which have the same sub and nbf claim (as the tokens are being created in the same second).

    Tymon\JWTAuth\PayloadFactory
    
    /**
     * Set a unique id (jti) for the token
     *
     * @return string
     */
    protected function jti()
    {
        $sub = array_get($this->claims, 'sub', '');
        $nbf = array_get($this->claims, 'nbf', '');

        return md5(sprintf('jti.%s.%s', $sub, $nbf));
    }

Its legitimate to have tokens with the same subject (sub) and not before date (nbf) set and if this is the case the generated JTI claim is not unique which means the token generated is also not unique. I am working around this by adding another custom claim with some random in it

**Comment by tymondesigns** [comment]
This has been fixed on the develop branch
