### ISSUE TITLE
Type problem

### ISSUE THREAD

**Issue by matiux** [tymondesigns/jwt-auth#366]
Problem with "tymon/jwt-auth": "dev-develop@dev"

  Argument 3 passed to Tymon\JWTAuth\JWTAuth::__construct() must be an instance of Tymon\JWTAuth\Http\TokenParser, instance of Tymon\JWTAuth\Http\Parser given, called in /Project/vendor/tymon/jwt-auth/src/Providers/LumenServiceProvider.php on line 144 and defined

**Comment by tymondesigns** [comment]
Thanks for reporting. should be fixed now
