### ISSUE TITLE
 In 0.6.*@dev + L5.1, there is a problem about cache tag.

### ISSUE THREAD

**Issue by ClemChuang** [tymondesigns/jwt-auth#367]
An error occurs.
"message": "This cache store does not support tagging."
The problem was found, in vendor/tymon/jwt-auth/src/Providers/Storage/Illuminate.php:103, the cache() function.

```php
    protected function cache()
    {
        if (! method_exists($this->cache, 'tags')) {
            return $this->cache;
        }

        return $this->cache->tags($this->tag);
    }
 ```
The $this->cache is \Illuminate\Cache\Repository and it always has a tags() function. The method_exists() should be applied to $this->cache->getStore(). But after the modification, the test case failed because the getStore() is not in the CacheContract.

**Comment by ClemChuang** [comment]
Laravel 5.1.28 has the problem, and the below versions may work well.

**Comment by efriandika** [comment]
i got this problem too.. how to solve them ?

**Comment by drecken** [comment]
adding `JWT_BLACKLIST_ENABLED=false` to `.env` fixed it for me

**Comment by tdhsmith** [comment]
It looks like tagging hasn't actually been working for a while, because Repository hadn't had a `tags` method until 5.1.28... probably a mix up between the repo and the manager APIs at some point.

Anyway it's easy to fix the error but I'm not certain what should be done for earlier releases. I guess it doesn't matter much since there is no behavior change, haha.

**Comment by tdhsmith** [comment]
I'm thinking something like this:

```php
protected function cache()
{
    if (method_exists($this->cache, 'tags')) {
        try {
            return $this->cache->tags($this->tag);
        } catch (\BadMethodCallException $ex) {
            return $this->cache;   
        }
    } else {
        return $this->cache;
    }
}
```

**Comment by tdhsmith** [comment]
Ok I think I have an approach that might work for all releases and testing, but I probably won't be able to test it on all combinations for a day or so.

Decided to set the result on a flag, since the test was getting a little silly to run every time we do a cache operation.

```php
protected $supportsTags;

// ...

protected function cache()
{
    if (is_null($this->supportsTags)) $this->determineTagSupport;
    
    if ($this->supportsTags) {
        return $this->cache->tags($this->tag);
    } else {
        return $this->cache;
    }
}

protected function determineTagSupport()
{
    if (method_exists($this->cache, 'tags')) { // Laravel >= 5.1.28
        try {
            // Attempt the repository tags command, which throws exceptions when unsupported
            $this->cache->tags($this->tag);
            $this->supportsTags = true;
        } catch (\BadMethodCallException $ex) {
            $this->supportsTags = false;
        }
    } else {
        if (method_exists($this->cache, 'getStore')) { // Laravel <= 5.1.27
            // Check for the tags function directly on the store
            $this->supportsTags = method_exists($this->cache->getStore(), 'tags');
        } else {
            // Must be using custom cache repository without getStore(), and all bets are off,
            // or we are mocking the cache contract (in testing), which will not create a getStore method
            $this->supportsTags = false;
        }
    }
}
```
