### ISSUE TITLE
vendor:publish Nothing to publish for tag []

### ISSUE THREAD

**Issue by jasonspick** [tymondesigns/jwt-auth#370]
Running: php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"

is returning Nothing to publish for tag []. I am not getting config.

laravel 5.2

**Comment by jadjoubran** [comment]
Just to make sure, did you add the service provider in your app config?

**Comment by jasonspick** [comment]
That was it............

**Comment by HawiCaesar** [comment]
I added the service provider in the app config but I still get the same 

Nothing to publish for tag []

**Comment by prince-code** [comment]
php artisan cache:clear

and then

php artisan config:cache

solved my problem
