### ISSUE TITLE
Lumen: 502 Bad Gateway using jwt.auth middleware

### ISSUE THREAD

**Issue by syropian** [tymondesigns/jwt-auth#375]
Been working on a little API today using Lumen, but when I enable the `jwt.auth` middleware in my controller, if the `jwt.auth` middleware is active, nginx throws a 502 Bad Gateway error. If the token isn't included, I get the proper `token_not_provided` response. I confirmed the everything works fine unless the `jwt.auth` middleware is being used. Has anyone come across this? I'm stumped.

Using Lumen with Homestead and PHP7.

**Comment by rajabishek** [comment]
@syropian Check you nginx logs to get a better detailed view on the error. It can give a clear idea on where exactly the problem might be.

**Comment by syropian** [comment]
@rajabishek It's the same error every time:

```
2016/01/08 06:21:03 [error] 776#776: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.10.1, server: scryble.app, request: "POST /api/document/create HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "scryble.app"
```

I tried adding 

```
fastcgi_buffers 8 16k;
fastcgi_buffer_size 32k;
```

and restarted nginx, but that didn't work.

**Comment by syropian** [comment]
Ah, rookie mistake, I needed to uncomment `$app->register(App\Providers\AuthServiceProvider::class);` in `bootstrap/app.php`.

Getting some more problems where the user isn't being found but it doesn't pertain to this ticket so I'm closing it up.

**Comment by mikebronner** [comment]
@syropian Would you be willing to share your `/bootstrap/app.php` file? I am banging my head against the desk all day long trying to get this to work. I have uncommented the AuthServiceProvider you mentioned (and commented out the JTWAuthServiceProvider), but whenever I try Auth::attempt() I get the same 502 Gateway with the same entry in the nginx error logs.
