### ISSUE TITLE
How to use refresh token (RefreshToken Middleware)

### ISSUE THREAD

**Issue by bravist** [tymondesigns/jwt-auth#378]
routes.php

``` php
$api->group(['before' => 'jwt.auth', 'after' => 'jwt.refresh'], function($api) {

                $api->get('users', 'AuthenticateController@index');
                $api->get('users/{id}', 'AuthenticateController@show');

            });
```

jwt.php

``` php

'ttl' => 1,

'refresh_ttl' => 3,
```

After 1 minute, token does not expired, but after 3 minutes, token can also be used.Don't know how to solve, please help to explain why

**Comment by imrealashu** [comment]
just use middleware `jwt.auth`. it will work well

**Comment by tdhsmith** [comment]
@Brave-Cheng Sorry for missing this issue. Are you saying 3 minutes after a refresh, or 3 minutes from the initial token creation? I made a diagram [here](https://github.com/tymondesigns/jwt-auth/issues/201#issuecomment-131978407) about how refreshes are supposed to work in relation to `ttl` and `refresh_ttl`.

**Comment by Walk-Code** [comment]
**You can try to build an authJWT middleware and register it like this:**
public function handle($request, Closure $next)
    {
        try {
            $user = JWTAuth::toUser($request->input('token'));
        } catch (Exception $e) {
            if ($e instanceof \Tymon\JWTAuth\Exceptions\TokenInvalidException){
                return response()->json(['error'=>'token_invalid']);
            }else if ($e instanceof \Tymon\JWTAuth\Exceptions\TokenExpiredException){

                $token = JWTAuth::getToken();
                if (!$token) {
                    return $this->response->errorMethodNotAllowed('Token not provided');
                }
                try {
                    $refreshedToken = JWTAuth::refresh($token);
                } catch (JWTException $e) {
                    return $this->response->errorInternal('Not able to refresh Token');
                }

                return response()->json(['error'=>'token_expired','token'=>$refreshedToken]);
            }else{
                return response()->json(['error'=>'error']);
            }
        }
        return $next($request);
    }
