### ISSUE TITLE
Where's the 'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class 

### ISSUE THREAD

**Issue by softwareok1** [tymondesigns/jwt-auth#379]
hi,
i am using jwt-auth dev-develop
theres no GetUserFromToken-class anymore at  ../src/Middleware.
Could you explain the circumstances short?
Greetz

**Comment by tdhsmith** [comment]
The `Authenticate` middleware is closest to the old `GetUserFromToken`. `Authenticate` will only continue if there is a valid token on the request. However there are some key differences:

- `Authenticate` throws exceptions on failure. It is your role to catch them in your `Handler` and provide a response / act as necessary (whereas the old middleware would generate a stock response for you).
- None of the new middlewares use events anymore (as they throw exceptions instead).

In your controller, you can retrieve the user with `JWTAuth::toUser()`.

FYI the `Check` is similar, but it does NOT fail if the token is missing/invalid/expired. It continues in all cases.

**Comment by softwareok1** [comment]
Thx

**Comment by raniesantos** [comment]
Is `Authenticate` a drop-in replacement?

If I change this line I added in Laravel's `Kernel.php` file
```php
'auth.jwt' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
```
will it work just the same?
