### ISSUE TITLE
Packagist has old commit

### ISSUE THREAD

**Issue by irazasyed** [tymondesigns/jwt-auth#389]
Hey!

Is there a problem with the Packagist's setup? Because it seems like the dev-develop / 0.6.x-dev is stuck in this commit - https://github.com/tymondesigns/jwt-auth/commit/d9bef95263a39355929d502a54c4f0a15dc215f4

Can you please take a look @tymondesigns ?

**Comment by tymondesigns** [comment]
It should auto update :S

I've just updated manually for now anyways, but I'll take a look at the hooks when I can

**Comment by irazasyed** [comment]
Thanks and yes, please do check when you can.
