### ISSUE TITLE
Change User class implementation

### ISSUE THREAD

**Issue by ilvalerione** [tymondesigns/jwt-auth#395]
I set user config variable with my User implementation class called "Business"

'user' => 'App\Business'

but when i call api i receive 

Class '\App\User' not found

Can i change "User" class with my "Business" class?

**Comment by GrahamCampbell** [comment]
You forgot to run `php artisan config:cache`.

**Comment by ilvalerione** [comment]
Hello Graham, thanks for reply

i just run this artisan command, and there is a new exception

Call to undefined method Closure::__set_state() in C:\xampp\htdocs\laravel\api\bootstrap\cache\config.php

**Comment by crynobone** [comment]
Are you using 0.5 or 0.6?

**Comment by ilvalerione** [comment]
0.5.*

**Comment by ilvalerione** [comment]
In wiki installation page end on compatibility table i see only 0.5.* version. Is there 0.6.* ready to use with some bug fix?

**Comment by crynobone** [comment]
You can't use `php artisan config:cache` with 0.5.x as the config includes closures. So  your issue is not related with @GrahamCampbell response.

**Comment by ilvalerione** [comment]
thanks a lot @crynobone ! I deleted config cache and all works fine.

When i introducing jwt middleware (jwt.auth, jwt.refresh) i receive this exception

Class '\App\User' not found

The class that represent user of my application is called "Business", not User.

Is there a method to register my implementation or it's mandatory to use User for eloquent model?

**Comment by ilvalerione** [comment]
Ok, i change my eloquent model name in "User" instead of "Business" and i resolved prev exception.

Now the routes after jwt middleware return everytime "user_not_found".

1) Primary key of User object is "id" how to standard config of jwt.

2) I tried to send token via HTTP Header and into GET request

**Comment by nathenapse** [comment]
@ilvalerione is it mandatory to use User?? what was the solution?

**Comment by ilvalerione** [comment]
The error was caused by the presence of both middleware. To perform authentication you must use "jwt.auth", to perform refresh you must use "jwt-refresh" separately.

In any case it's mandatory to call your user class "User". Into eloquent model you can setting table_name corresponding.

**Comment by jsiebach** [comment]
@ilvalerione @nathenapse It's not mandatory to use User, you just need to change your user class in config/auth.php as well
