### ISSUE TITLE
Token Invalid error on multiple and frequent requests

### ISSUE THREAD

**Issue by Vishal0203** [tymondesigns/jwt-auth#396]
Hi,

I am  using jwt-auth library with laravel and angular. I've written my API's to refresh token on every request. However my calls are working perfect only for certain times after which the API throws invalid token. 

Please take a look at my question on stackoverflow. I'm sure I'm sending the refreshed token for each request I make. Please take a look at this

http://stackoverflow.com/questions/34835506/unknown-reason-for-jwt-tokens-invalidation

**Comment by naderst** [comment]
Hi @Vishal0203 

How did you solve this? I'm having the same issue, I checked that the client is sending the token and I also checked that the server is recieving it but it's returning invalid token.

**Comment by Motard** [comment]
I also have this problem. And I noticed that this only happens when I made some request on top of another request. Let me try to explain. I am using Postman to develop, and when I click the send button with more or less a second interval between requests, all is fine, but when I click very fast the send button, I get an invalid token response.

**Comment by nizam27391** [comment]
Hi.
I am also having this problem. 

In my app, yes I do have multiple request at once. But it is vital for my app to work. Which is necessary to check for the user is logged in or not, then for the table plugin and extra request.

You guys have any idea on how to fix this issue?

Thanks

**Comment by Vishal0203** [comment]
I couldn't solve this. 
I had to turn off my idea of refreshing token on every request.

**Comment by ratatatKE** [comment]
I am having the same problem when I write a for loop on the client side that does multiple frequent posts to the laravel server side. Somewhere in the middle jwt-auth throws a token invalid exception which forces user to logout and log back in disrupting the entire UX.

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
