### ISSUE TITLE
error when caching config [5.2]

### ISSUE THREAD

**Issue by andrewmclagan** [tymondesigns/jwt-auth#399]
When running `php artisan config:cache` any subsequent operation throws an error `Fatal error: Call to undefined method Closure::__set_state()` within the cached config file at `bootstrap/cache/config.php`.

This occurs because in the published `tymondesigns/jwt-auth` config file a closure is assigned to a config variable. e.g.

````
        /*
        |--------------------------------------------------------------------------
        | Authentication Provider
        |--------------------------------------------------------------------------
        |
        | Specify the provider that is used to authenticate users.
        |
        */

        'auth' => function ($app) {
            return new Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter($app['auth']);
        },
````

This can be fixed by simply returning a class constant:

`'auth' => Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter::class,`

and then within `Tymon\JWTAuth\Providers\JWTAuthServiceProvider` changing the function on line `136` to initialise an instance into the container rather then through a callback: 

````
    /**
     * Register the bindings for the Auth provider
     */
    protected function registerAuthProvider()
    {
        $this->app['tymon.jwt.provider.auth'] = $this->app->share(function ($app) {
            $provider = $this->getConfigInstance($this->config('providers.auth'));
            return new $provider($app['auth']);
            // return $this->getConfigInstance($this->config('providers.auth')); // does not work 
        });
    }
````

creating a pull request to address this issue as compiling cache reduces response times by 60% ..!!! in my app.

**Comment by crynobone** [comment]
Most of this changes are available under `0.6` (alias of `develop` branch).

**Comment by andrewmclagan** [comment]
hmm seems after more investigation this is already being addressed in develop branch...?

**Comment by andrewmclagan** [comment]
haha beat me to that comment..!
