### ISSUE TITLE
JWTSubject interface does not work with DatabaseUserProvider

### ISSUE THREAD

**Issue by naerymdan** [tymondesigns/jwt-auth#400]
If I am not using Eloquent, the DatabaseUserProvider return me a GenericUser which only implements "Illuminate\Contracts\Auth\Authenticatable".

This already contains a function for getting a uniqueId "getAuthIdentifier()".

Can we relax the need to implement JWTSubject by leveraging the pre-existing "getAuthIdentifier()" and assuming an empty array of custom claims?

**Comment by jfoliveira** [comment]
@naerymdan :+1: +1

**Comment by tdhsmith** [comment]
Could you temporarily get around this by subclassing?  Untested, but something like...

```php
class JWTUserProvider extends DatabaseUserProvider
{
     protected function getGenericUser($user)
    {
        if ($user !== null) {
            return new JWTUser((array) $user);
        }
    }
}
```
```php
class JWTUser extends GenericUser implements JWTSubject
{
    // jwtsubject methods ...
}
```
Then you can use `Auth::extend` with Laravel or `Auth::setProvider` with  JWTGuard...

**Comment by tymondesigns** [comment]
@naerymdan If I were to remove the `JWTSubject` contract then it would remove the flexibility to use any non-laravel providers, which I'm not keen on tbh.

I do think the suggestion that @tdhsmith has made is perfectly viable

**Comment by davidspiess** [comment]
Wouldn't it make sense to provide the `JWTUserProvider` inside the package?
