### ISSUE TITLE
0.6-alpha pre-release?

### ISSUE THREAD

**Issue by jfoliveira** [tymondesigns/jwt-auth#401]
Any plans on releasing something like `0.6-alpha-unstable-use-at-your-own-risk-dont-blame-us` pre-release?

One could certainly use `dev-master`, but if the application is being automatically deployed (e.g. using Envoyer.io) every deploy could download new commits that haven't been tested in dev time.

An alpha release - even an unstable one - at least is bound to a specific commit so one knows what can be expected/known issues.

**Comment by Murwa** [comment]
:+1:

**Comment by tymondesigns** [comment]
Yea its a fair point. I'll get an alpha release out soon

**Comment by tymondesigns** [comment]
I'm actually considering going all in and kicking it off with `1.0.0-alpha`

**Comment by jadjoubran** [comment]
:fireworks:

**Comment by crynobone** [comment]
Why would each deployment use a new commit, deployment should run `composer install` and not `composer update`, and it would be based on your `composer.lock` file.

**Comment by jfoliveira** [comment]
@crynobone you're right! If `composer.lock` is added to version control that is true.

**Comment by MallardDuck** [comment]
@tymondesigns 
> Yea its a fair point. I'll get an alpha release out soon

Nice.

> I'm actually considering going all in and kicking it off with 1.0.0-alpha

Awesome! I love using this library with laravel5, I noticed on GH recently there were options for blacklist grace periods and attempted to start using them with what I had gotten from composer. I quickly realized I wasn't on the right code base.

Long story short, I just started toying with the newer code-base, after a bit I was pretty happy but wondering when an official release would be pushed out. Needless to say this excites me and this timing is excellent.

**Comment by lukeed** [comment]
:+1:  

Including a simple installation guide would be perfect too, since the entire authentication system setup changed in laravel/lumen

**Comment by MallardDuck** [comment]
> Including a simple installation guide would be perfect too, since the entire authentication system setup changed in laravel/lumen

:+1:  I'll thumbs up that for sure too. After further testing I am still not quite sure what else needs tweaking in the code or configs to play nice with the new version. Even very simple docs showing the changes from previous docs would be awesome.

**Comment by cviebrock** [comment]
:+1: here too!

**Comment by mikebronner** [comment]
I could definitely use a guide for getting jwt-auth set up and running in Lumen 5.2. I tried following the comments in issue #376, but they are all over the place, and its not clear which steps are valid and which are not.

It seems everythime I try to use Auth::attempt() I get a 502 Gateway error as described in issue #375.

**Comment by brianseitel** [comment]
+1 on Lumen 5.2 instructions. Also tried following the comments in #376, like @mikebronner.

**Comment by josenicomaia** [comment]
+1

**Comment by driesvints** [comment]
Any chance we can get an alpha release soon for 0.6? We're currently requiring specific commit hashes but a dedicated alpha release would be nicer :smile:

**Comment by engAhmad** [comment]
+1

**Comment by tymondesigns** [comment]
Just tagged `1.0.0-alpha1` (https://packagist.org/packages/tymon/jwt-auth#1.0.0-alpha1)

Going to throw a little quick start guide in there when I get a sec, prior to the full docs

**Comment by driesvints** [comment]
Awesome! Thanks @tymondesigns :)

**Comment by driesvints** [comment]
I guess this can be closed.
