### ISSUE TITLE
Class Tymon\JWTAuth\src\Middleware\GetUserFromToken does not exist

### ISSUE THREAD

**Issue by hamalatifa** [tymondesigns/jwt-auth#403]
hi,
i m developping an project with laravel5,  and i try to include JWTAuth in this project

i follow this tuto http://laravelista.com/json-web-token-authentication-for-lumen/ who is in laravel 4
and i'm trying to change their instructions  to laravel 5, I arrived to generate a secret key
but i am blocked in step : Authentication,
 after i change middleware in route:
$router->group(['prefix' => 'auth'], function () { 
   get('login', ['middleware' => 'jwt.auth', 'as' => 'login', 'uses' => 'AuthController@getLogin']);
   post('login', ['as' => 'login.post', 'uses' => 'AuthController@postLogin']);
 });
when i try to authenticate i get this exception  
ReflectionException in Container.php line 741:
Class Tymon\JWTAuth\src\Middleware\GetUserFromToken does not exist

i verified this class in directory tymon, i found it, so i don't know what is the problem, 

Any thoughts?

thanks in advance

**Comment by tdhsmith** [comment]
Did you follow [the instructions here on the wiki](https://github.com/tymondesigns/jwt-auth/wiki/Authentication#laravel-5-1)? You likely have an issue with your kernel where you configure the middleware names.

> ReflectionException in Container.php line 741:
Class Tymon\JWTAuth\src\Middleware\GetUserFromToken does not exist

There probably shouldn't be a `\src\` in there. That's part of the file structure, but it isn't reflected in the namespaces; the correct class is just `Tymon\JWTAuth\Middleware\GetUserFromToken`.

(This assumes version 0.5. The middleware classes all change in 0.6.)

**Comment by hamalatifa** [comment]
for \src\ i detecte that and i change it but still some place where i forget it,
 thantks @tdhsmith now i have an other problem 
{"error":"token_not_provided"}

**Comment by hamalatifa** [comment]
where can i set Authorization: Bearer {yourtokenhere} !!!

**Comment by tdhsmith** [comment]
You must set it in the client. JSON Web Tokens are for exchanging information between a client app and server app.

How you set it will depend on what you are using for your client. For example, many people are using AngularJS, where you can create an http interceptor that attaches the header to requests (many people use the Satellizer library which does most of this for you). In plain JS you can call something like [`request.setRequestHeader('Authorization', 'Bearer '+token);`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#setRequestHeader\(\)) before sending the request. You don't even need to be using JS, there are server-to-server set ups and non-web applications that use JWT.

If you are looking for a simple way to start testing, maybe check out Postman? It's a free app you can use to create HTTP requests and test APIs.

**Comment by hamalatifa** [comment]
thanks a lot @tdhsmith for your responses, as client i use blades templates( blade.html )

**Comment by tdhsmith** [comment]
`header(...)` is going to set the HTTP header going from server to client (the **response**). You need to set the header going from the client to server (the **request**). Though I'm not sure if Laravel even provides a way to do that... Blade generates your views, but it isn't really a "client". Your *client* would be the HTML that Blade generates (in this case an empty document).

Also to be clear, you must replace the `{mytoken}` part with a token generated for the user.

To take a step back: why are you using JWTs? When everything is served from the same Laravel app (and there is no client code), you should probably be using sessions.

**Comment by hamalatifa** [comment]
thanks @tdhsmith ,  i know that i must replace {mytoken} by my token,
for the raison why i use jwt my application will comunicate with mobile apps

**Comment by hamalatifa** [comment]
now i have this problem 
TokenInvalidException in NamshiAdapter.php line 58: Could not decode token: The token "expzsveQMSNvz.UXpHcWH2gv9.vydRGpMXd6a" is an invalid JWS

**Comment by tdhsmith** [comment]
Well according to http://jwt.io, that _isn't _a valid token. (Even without the validator, it looks too short to have any of the expected content.)

How did you generate it?

**Comment by hamalatifa** [comment]
i generate it with this instruction

$credentials = [
            'email' => $request->email,
            'password' => $request->password,
        ];
 $token = JWTAuth::attempt($credentials);

**Comment by tdhsmith** [comment]
That is very weird, and something else must be happening. Are you doing any string operations on the token, or manipulating it in any way? What happens when you try to generate a token with hardcoded credentials? What about with `JWTAuth::encode(JWTAuth::getPayloadFactory()->make());`?

**Comment by jeffdupont** [comment]
Ok, so this is an easy fix. In the Kernel.php file you need to add slashes to pull from the root namespace.

        'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
        'jwt.refresh' => \Tymon\JWTAuth\Middleware\RefreshToken::class,

**Comment by hamalatifa** [comment]
@jeffdupont :  I've already done that;

thanks a lot @tdhsmith  : i have question can i create the token  when the user do the registre in my website ! 
because i want to save the value of token in database after register of user 
and i did some test : 
-when i create the token after login 

public function postLogin(LoginRequest $request)
    {
        $credentials = [
            'email' => $request->email,
            'password' => $request->password,
        ];
      
          $token = JWTAuth::attempt($credentials);
       print_r($token);
exit;
....
} 

after execution of this code i get the token !

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL3Rlc3RjbXNsYXJhdmVsXC9lblwvYXV0aFwvbG9naW4iLCJpYXQiOjE0NTUxMDM3NzIsImV4cCI6MTQ1NTEwNzM3MiwibmJmIjoxNDU1MTAzNzcyLCJqdGkiOiI2ZTcxMTAyMWI5MDRkYTJkNTk3YTkwM2EwZDZlYWM0MyJ9.DHRYYY0hwKPzvL10eki2f7SYYERQXAyZ7ePiBHvJNNI


- but when i create the token after register : 

 public function postRegister(RegisterRequest $request)
    {
      $credentials = [
            'email' => $request->email,
            'password' => $request->password,
        ];
    
        $token = JWTAuth::attempt($credentials);
        
       print_r($token);
exit;
....
}
after execution, i get the null as value of token

**Comment by jeffdupont** [comment]
@hamalatifa That fixed the error from the OP for me and I didn't see any reference to that in the comments, so I wanted to make sure that anyone finding this gets the correct solution.

Second, the postRegister method, you're trying to attempt to login a user that was just created? The code doesn't show that the Register is creating a user first, so the JWTAuth::attempt is probably failing. I think what you're looking for is to create the token from the newly created user object: 

$user = User::first();
$token = JWTAuth::fromUser($user);

Then you can save the token back to the user.

**Comment by tdhsmith** [comment]
@hamalatifa - There shouldn't be any reason for `attempt` to behave differently in those situations. I suspect your user provider must not be finding your new user for some reason. Can you try updating to the most recent master branch? It has a fix (#398) that isn't in 0.5.6 that should let you see if there are any exceptions happening in `attempt`.

I'd guess something is slightly different in your credentials, or perhaps you aren't actually creating the new user (as **jeff** suggests).

In any case, isn't it easier to do something like `Auth::setUser($user)` in your register function and then `JWTAuth::fromUser(Auth::user())` in post-register?

@jeffdupont - Isn't `User::first()` going to get the first sequential user?

**Comment by hamalatifa** [comment]
@tdhsmith  yes User::first()  get the first sequential user
@jeffdupont  i will try your proposition thanks

**Comment by hamalatifa** [comment]
finally i resolved this problem by getting the token after  the registre of user

here is the code : 

 public function postRegister(RegisterRequest $request)
    {
      
        app('Modules\User\Services\UserRegistration')->register($request->all());

        flash()->success(trans('user::messages.account created check email for activation'));
        $credentials = [
            'email' => $request->email,
            'password' => $request->password,
        ];
        $token = JWTAuth::attempt($credentials);
        $user=User::where('email','=',$request->email)->first();
        $user->token=$token;
        $user->save();


        return redirect()->route('register');
    }

**Comment by kylanhurt** [comment]
On a sidenote, everyone make sure they keep close attention to where the slashes are in their Kenerl.php file. For me I was missing the "\" before "Tymon\JWTAuth...", etc. Hard to catch!

**Comment by jafaronly** [comment]
I had the same problem , even if you fix it in your own way maybe some one else make use of how I

**Comment by KelvinWanyama** [comment]
@jeffdupont  thanks I had also forgotten to have the slashes at the beginning.

**Comment by aramirez92** [comment]
'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
        'jwt.refresh' => \Tymon\JWTAuth\Middleware\RefreshToken::class,

**Comment by seyidaniels** [comment]
The best thing to do is to go to the Kernel.php file and change 

        'jwt.auth' => Tymon\JWTAuth\Middleware\GetUserFromToken::class,  to

        'jwt.auth' => \Tymon\JWTAuth\Middleware\GetUserFromToken::class,
