### ISSUE TITLE
Laravel 5.0.x installation 

### ISSUE THREAD

**Issue by aniljailta** [tymondesigns/jwt-auth#41]
Hello . Not able to install this package for laravel 5 . Please update or suggest any solution
Using
    "minimum-stability": "dev",
    "prefer-stable": true

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v5.0.3
    - Conclusion: remove laravel/framework v5.0.2
    - Installation request for atticmedia/anvard dev-master -> satisfiable by atticmedia/anvard[dev-master].
    - Conclusion: don't install laravel/framework v5.0.2
    - Conclusion: don't install laravel/framework v5.0.1
    - atticmedia/anvard dev-master requires illuminate/support 4.* -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.0.0|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.10|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.3|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.5|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.0.9|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.0|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.10|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.11|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.12|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.13|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.14|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.15|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.16|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.17|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.18|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.19|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.20|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.21|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.22|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.23|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.24|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.25|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.26|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.27|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.28|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.29|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.3|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.30|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.5|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.1.9|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.0.0
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.0.0
    - Installation request for laravel/framework 5.0.* -> satisfiable by laravel/framework[v5.0.0, v5.0.1, v5.0.2, v5.0.3].

**Comment by tymondesigns** [comment]
Which version of the package are you attempting to install?

**Comment by aniljailta** [comment]
i am trying to install  version 0.3.x
		
      "tymon/jwt-auth": "0.3.*"

**Comment by tymondesigns** [comment]
You will need to use the `dev-laravel-5` release for laravel 5.

I am almost done with the new release (it will be `0.5` when I tag it). Alongside that release I will be publishing the new documentation
