### ISSUE TITLE
Unlimited refreshes during refresh_ttl ?

### ISSUE THREAD

**Issue by BenjaminOwlient** [tymondesigns/jwt-auth#419]
Hi,
I'm beginning with jwt and I wonder if this behaviour is normal : 

When your token is expired (> ttl) but still in refresh window (< refresh_ttl) you are able to refresh it as many times as you want. Nothing blocks you, as only unexpired tokens are put in blacklist when refreshing.

Shouldn't you be able to refresh it only once ?

**Comment by tdhsmith** [comment]
Are you on master? I just uncovered an issue like this in #83. Hope to have a PR for it today.

**Comment by BenjaminOwlient** [comment]
I'm not totally sure we are talking about the same issue.
My concerns are those lines in Blacklist.php :
```
    public function add(Payload $payload)
    {
        $exp = Utils::timestamp($payload['exp']);

        // there is no need to add the token to the blacklist
        // if the token has already expired
        if ($exp->isPast()) {
            return false;
        }
        // then put in blacklist
        ...
```
It means an expired token (isPast = true) stil under refresh_ttl can be used again and again for refreshing, because it is never put in blacklist. Which is very strange, because it means refreshing with an expired token is more permissive than with a valid one, as a valid one (isPast = false) will be put in blacklist on the first refresh.

**Comment by tdhsmith** [comment]
That was what I was talking about (also the way the cache lifetime is set is an issue, depending on how often your cache gets cleaned). It had been fixed on develop but never brought back to master. I just submitted a PR to address it.

**Comment by BenjaminOwlient** [comment]
Awesome, thank you !
