### ISSUE TITLE
passwords stored in md5

### ISSUE THREAD

**Issue by sefsinalas** [tymondesigns/jwt-auth#420]
Hi. I have an old system (in another framework, not laravel) that store the passwords using MD5('the_pass'). And i want to use jwt-auth to login the users. It this possible? I tried changing

```
'algo' => env('JWT_ALGO', 'none'),
```

But doesnt seem to work

**Comment by tdhsmith** [comment]
`algo` sets the algorithm for hashing the _tokens_. You're probably gonna want to leave that as the default. The password hashing is all handled by Laravel, and not this library.

You're gonna need to change the hasher used by Auth, or more specifically its user provider. There _should_ be a guide out there somewhere on this, though I'll bet you'll run into a lot of people saying "don't use MD5". (Obviously this is good advice, but sometimes things are out of your control.)

**Comment by tdhsmith** [comment]
Might involve implementing and binding your own version of `Illuminate\Contracts\Hashing\Hasher`, but maybe there are some shortcuts.

Reimplementing the user provider seems harder, though you could probably get by subclassing your existing one and then using the built-in `Auth::extend($providerFactoryCallback)`.

Just mumbling to myself really... I've never done this, so it's best to find someone who has. :wink:

**Comment by sefsinalas** [comment]
The team decided to stop using md5 and reset all the passwords.

**Comment by tdhsmith** [comment]
:tada:

**Comment by valVk** [comment]
in case if someone need custom password verification it just may use custom auth provider.
