### ISSUE TITLE
Issue with "jwt.check" middleware and/or Auth::guest()?

### ISSUE THREAD

**Issue by cviebrock** [tymondesigns/jwt-auth#422]
[This is using the `0.6@dev` version.]

I'm looking for a way in my routes to let both authenticated users and guests in, but to be able to handle authenticated users slightly differently.  As a simple example:

``` php
Route::get('test', ['middleware' => 'jwt.check', function () {
        if (Auth::guest()) {
            return 'Welcome, guest';
        } else {
            return 'You made it, ' . Auth::user()->name;
        }
}]);
```

If I try that (with or without the middleware), I get:

```
JWTException in JWTGuard.php line 317:
Token could not be parsed from the request.
```

Am I doing this wrong? Or is there not a way to gracefully check for an optional user (without wrapping all my code in `try...catch` blocks)?

**Comment by tdhsmith** [comment]
No, the `JWTGuard` code is very very new, and it's likely no one has tested the `Auth::guest` function yet. Are you on Lumen?

**Comment by cviebrock** [comment]
No, I'm on Laravel 5.2.

**Comment by tdhsmith** [comment]
Then I'd recommend using the default `session` guard for now. If you're behind `jwt.check`, then `Auth::guest` should work as expected.

The `jwt` guard should eventually stabilize (for both Laravel and Lumen), but right now it's an incomplete driver for people on Lumen who would otherwise be totally unsupported...

**Comment by cviebrock** [comment]
Well, to be fair, I seem to have gotten Laravel 5.2 working well with the JWTGuard (apart from my guest issues).  I'll try to look into what's going on and make a PR if I find anything.

**Comment by tymondesigns** [comment]
@cviebrock have you successfully gotten the Guard working as expected now? I think everything should be OK with the `1.0.0-alpha1` release

**Comment by cviebrock** [comment]
I'll try upgrading to the `alpha` release later this week and see what (if anything) breaks.

BTW, do you have any new documentation to go along with this release?

**Comment by juavidn** [comment]
Hi, Im using the 1.0.0-alpha1 version and same route test behind jwt.check Auth::guest always return true, can you please help me, I need a route that supports guests and authenticated users .. thank you so much

**Comment by Hesesses** [comment]
Should "jwt.check" work on v0.5.12? or is it a new feature for 1.0.0?

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
