### ISSUE TITLE
How add custom Claims?

### ISSUE THREAD

**Issue by angelmartz** [tymondesigns/jwt-auth#44]
I am trying with JWTAuth::encode();

Argument 1 passed to Tymon\JWTAuth\JWTManager::encode() must be an instance of Tymon\JWTAuth\Payload, array given

**Comment by tymondesigns** [comment]
which version are you using?

**Comment by tymondesigns** [comment]
It looks like you're `dev-laravel-5` ? If so..

You can pass an array of custom claims via the second parameter on the `attempt()` method, and also the `fromUser()` as seen [here](https://github.com/tymondesigns/jwt-auth/blob/laravel-5/src/JWTAuth.php#L80-L101)

Alternatively if you are manually creating the token via the `encode()` method, then you will need to create a Payload instance as follows:

```php
$customClaims = ['foo' => 'bar', 'baz' => 'bob'];

$payload = app('tymon.jwt.payload.factory')->make($customClaims);

$token = JWTAuth::encode($payload);
```

**Comment by angelmartz** [comment]
Yes I'm using dev-laravel-5

Thank you

**Comment by jgardezi** [comment]
Can someone please have a look at this issue its kind of similar https://github.com/tymondesigns/jwt-auth/issues/771.
