### ISSUE TITLE
Non expiring token as API Key - how manage multiple guard settings?

### ISSUE THREAD

**Issue by jfoliveira** [tymondesigns/jwt-auth#451]
I'm using latest `0.6.*@dev` with `Lumen 5.2` and I trying to figure out how could I support two token types on my API:

1) User token: that will be retrieved every time an user "logs into the API" and will be blacklisted when the users logs out.

2) API Key: that should be issued once and given to a third party. This one should never expire as a regular API Key.

**Question:**
If I remove `exp` claim from my `required_claims` the tokens are issued without expiration date (API Key).
Keeping this claim the tokens are issued with `exp` claim (user token).

**How to set/remove the `exp` claim programmatically** or manage different settings for each `Auth::guard`?

Below some code that illustrates my current scenario that is working for user tokens only.

`config/auth.php`:

``` php
<?php

return [
    'defaults' => [
        'guard' => env('AUTH_GUARD', 'user_token'),
        'provider' => 'users',
    ],
    'guards' => [
        'user_token' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
        'api_key' => [
            'driver' => 'jwt',
            'provider' => 'consumers',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
        'consumers' => [
            'driver' => 'eloquent',
            'model' => App\Models\Consumer::class,
        ],
    ],
];
```

`config/jwt.php`:

``` php
<?php

return [
    'secret' => env('JWT_SECRET'),
    'ttl' => env('JWT_TTL', 60),
    'refresh_ttl' => env('JWT_REFRESH_TTL', 20160),
    'algo' => env('JWT_ALGO', 'HS256'),
    'required_claims' => ['iss', 'iat', 'exp', 'nbf', 'sub', 'jti'],
    'blacklist_enabled' => env('JWT_BLACKLIST_ENABLED', true),
    'blacklist_grace_period' => env('JWT_BLACKLIST_GRACE_PERIOD', 10),
    'providers' => [
        'jwt' => Tymon\JWTAuth\Providers\JWT\Namshi::class,
        'auth' => Tymon\JWTAuth\Providers\Auth\Illuminate::class,
        'storage' => Tymon\JWTAuth\Providers\Storage\Illuminate::class,
    ],
];
```

`My token generator`:

``` php
public static function getToken($subjectId, $tokenType)
{
    $token = null;

    switch ($tokenType) {
        case self::TOKEN_TYPE_USER_TOKEN:
            $token = Auth::guard('user_token')->tokenById($subjectId);
            break;

        case self::TOKEN_TYPE_API_KEY:
            $token = Auth::guard('api_key')->tokenById($subjectId);
            /**
             * how to set/remove "exp" so token doesn't expire?
             * as this will be used as an API KEY it should not expire.
             */
            break;
    }

    if (!$token) {
        abort(401);
    }
    return $token;
}
```

**Comment by tdhsmith** [comment]
I'm not sure what happens when multiple guards are supported by the same driver... do they reference different instances, or is it the same singleton? Maybe someone better at container majjycks can come up with a trick there.

However you should still be able to do this by accessing the payload factory. It's not as clean, but something like `JWTAuth::factory()->setDefaultClaims(['iss', 'iat', 'nbf', 'jti'])` (or whatever you want excluding `exp`).

PS - I don't have time to check this out closely, so I might be off on a method call...

Also I'd recommend adding a custom claim like `'typ' => 'api' | 'user'` so you have a foolproof way to verify what token type you're dealing with, and be absolutely sure you don't mix them up.

**Comment by jfoliveira** [comment]
@tdhsmith Thanks a lot for pointing me in the right direction!

I tried
```php
JWTAuth::factory()->setDefaultClaims(['iss', 'iat', 'nbf', 'jti']);
$apiConsumer = Consumer::find($id);
$token = JWTAuth::fromUser($apiConsumer);
```
but it throws

```
'Tymon\JWTAuth\Exceptions\TokenInvalidException' with message 
'JWT payload does not contain the required claims' in 
/vendor/tymon/jwt-auth/src/Validators/PayloadValidator.php:64
```
because `exp` is defined in `config/jwt` `required_claims`.

The only way that removed the `exp` claim from the token was:
```php
JWTAuth::factory()->validator()->setRequiredClaims(['iss', 'iat', 'nbf', 'jti']);
JWTAuth::factory()->setTTL(null);
$apiConsumer = Consumer::find($id);
$token = JWTAuth::fromUser($apiConsumer);
```

Now that I have a token that does not expire I now have to find a way to workaround #275 (Avoid query DB).

My token has a subject id related to the API consumer, which is another entity not related to a regular user. When `auth` middleware is used in a route it's querying the user table in the database - because my default driver uses the `user_token` guard.
If a user is found with the same `sub id`, it's setting the user as the user found and not as the API consumer.

I still can't understand why authenticate middleware `src/Middleware/Authenticate.php` has this block querying the database. I'm reading this code for days now and I'm feeling dumb for not getting its intent:

```php
        try {
            $this->auth->parseToken()->authenticate();
        } catch (JWTException $e) {
            throw new UnauthorizedHttpException('jwt-auth', $e->getMessage());
        }
``

We call `authenticate()`, we don't use its result for anything - so it doesn't matter if the token subject id has been found on the provider database table after querying the db.
Are we just worried about catching exceptions?
What kind of exceptions could be thrown here other than database exceptions?

If only database exceptions could be raised here that would be out of the scope of this package to handle, IMHO.

**Comment by jfoliveira** [comment]
Please ignore my last comment about catching db exceptions, as the `catch` block is only catching `JWTException`.
It seems `authenticate()` is called as a shorthand as it will trigger `getPayload()`, `requireToken()`, etc.
Fine!

My challenge now is only try to avoid querying the DB when the token is an API key instead of user token.

**Comment by tdhsmith** [comment]
If you're not gonna check the DB, are you just going to assume that any valid API token has permission? 

Then you could just run a `$payload = JWTAuth::getPayload()`. That won't do any user checks on its own, but will throw an exception on invalid/expired tokens.

**Comment by jfoliveira** [comment]
Hey @tdhsmith 
I might check the DB, I just think that - as mentioned in #275 (Avoid query DB) - perhaps this check should not be automatically performed by `jwt-auth`.

The way I see JWT flow is:
* The token is self-contained, so it can itself tell me who the subject is and which claims (including my custom ones) were added to the token, so:
* If i use on a route `['middleware' => 'jwt:auth']` I would expect this middleware to:
  * check if the token is sent on the request
  * check the signature
  * check the validation/expiration (only if `exp` claim is present)

If the checks above are fine, then my route would be executed.
From that point on it would be up to the route implementation to decide if JWT token check is enough for allowing access to the specific route or if they want perform extra checks - including querying the DB if needed.

In my case, once `jwt-auth` tells me the token is valid (within expiration date or a long lived token without `exp` claim set) I would read the token payload claims and perhaps I would query the DB on different.

Not sure if I'm making myself clear.
Remember: I'm totally new to JWT so I might be mistaken here. :-)

**Comment by jfoliveira** [comment]
I've just created a new PR #464
Please review it.

**Comment by tdhsmith** [comment]
I'll eventually respond to #275, sorry. I'd like to do some research first on history of JWT though. I'm currently inclined to believe that most of what you quoted from jwt.io is in reference to expensive calls to 3rd-party authentication services, not cheap calls to local databases, since the authors of jwt.io (Auth0) built a product around identity services.

However I do agree trying to reduce database calls is a laudable goal (in the right contexts anyway). jwt-auth doesn't prevent you from doing it though. Only the `authenticate` and `attempt` methods and their aliases make DB calls, and it's already perfectly possible to utilize jwt-auth without those methods.

I guess it would be nice if the auth service provider received token claims as an additional argument, that way you could write a custom one that only acted on those claims... (But that's a pretty niche need and everyone seems confused by the service providers anyway, so I'd have to think about it.)
