### ISSUE TITLE
It can use JWTAuth and MultiAuth together?

### ISSUE THREAD

**Issue by sotnaspina** [tymondesigns/jwt-auth#455]
MultiAuth: for admin users and JWTAuth: form website users.

I use Laravel 5.2 and am using MultiAuth (Kbwebs\MultiAuth\MultiManager), how will I login via Web Service I installed JWTAuth and gave this error:

"Argument 1 passed to Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter::__construct() must be an instance of Illuminate\Auth\AuthManager, instance of Kbwebs\MultiAuth\MultiManager given"

Have any solution to this?

Thank you!

**Comment by tdhsmith** [comment]
This package is set up to allow you to swap in other auth libraries, but you will have to write your own custom provider class to connect JWTAuth to your auth service.  This class must implement `Tymon\JWTAuth\Contracts\Providers\Auth`. Once you've done that, you just need to set its class name in the config value `jwt.providers.auth`.

You can look at [an existing implementation](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Providers/Auth/Illuminate.php) for guidance. I don't know anything about MultiAuth, but the calls here probably shouldn't be complicated.

The `byId` and `byCredentials` are expected to find a user using an ID or a credentials array and return true or false whether the user was found (for credentials, this means matching all values including e.g. a password hash). Note that with the `Illuminate` driver we deliberately choose the `once` functions which won't save the user to a session -- we only want the user saved for the length of this request.

**Comment by tymondesigns** [comment]
what @tdhsmith said :smile:
