### ISSUE TITLE
Exception TokenBlacklistedException not working

### ISSUE THREAD

**Issue by juniormc** [tymondesigns/jwt-auth#457]
I am using Laravel 5.1 and I a'm trying to use Exception: TokenBlacklistedException and TokenExpiredException but it does not work. Rest Using Advanced Client for Chrome, 
returns the following error.
 ![screen shot 2016-01-28 at 3 28 36 pm](https://cloud.githubusercontent.com/assets/14990543/12659393/2826a828-c5d4-11e5-8b59-f48b5c97dd49.png)
does not return the message in the catch.

try {
 
            if (! $user = JWTAuth::parseToken()->authenticate()) {
                return response()->json(['user_not_found'], 404);
            }
 
        } catch (Tymon\JWTAuth\Exceptions\TokenBlacklistedException $e) {
 
            return response()->json(['token_expired'], $e->getStatusCode());
 
        }catch (Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {
 
            return response()->json(['token_expired'], $e->getStatusCode());
 
        } catch (Tymon\JWTAuth\Exceptions\TokenInvalidException $e) {
 
            return response()->json(['token_invalid'], $e->getStatusCode());
 
        } catch (Tymon\JWTAuth\Exceptions\JWTException $e) {
 
            return response()->json(['token_absent'], $e->getStatusCode());
 
        }

**Comment by tdhsmith** [comment]
Are you in a namespace? You'll either need leading slashes on the exceptions to escape them to the global namespace, or else `use` them so they're available in the file.

**Comment by juniormc** [comment]
Yes, I am using:

use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;
use Tymon\JWTAuth\Exceptions\TokenExpiredException;
use Tymon\JWTAuth\Exceptions\TokenInvalidException;
use Tymon\JWTAuth\Exceptions\TokenBlacklistedException;

I'm not sure if I will need something to set

**Comment by juniormc** [comment]
Thanks for you comment.

I am use: 

use Tymon\JWTAuth\Exceptions\JWTException;
use Tymon\JWTAuth\Exceptions\TokenExpiredException;
use Tymon\JWTAuth\Exceptions\TokenInvalidException;
use Tymon\JWTAuth\Exceptions\TokenBlacklistedException;

and: 

try {
 
            if (! $user = JWTAuth::parseToken()->authenticate()) {
                return response()->json(['user_not_found'], 404);
            }
 
        } catch (TokenBlacklistedException $e) {
 
            return response()->json(['token_expired'], $e->getStatusCode());
 
        }catch (TokenExpiredException $e) {
 
            return response()->json(['token_expired'], $e->getStatusCode());
 
        } catch (TokenInvalidException $e) {
 
            return response()->json(['token_invalid'], $e->getStatusCode());
 
        } catch (JWTException $e) {
 
            return response()->json(['token_absent'], $e->getStatusCode());
 
        }

**Comment by tdhsmith** [comment]
Yep sorry I wasn't clear. That's what I meant by the second option. :wink: Glad it worked out!

**Comment by davidjohns1124** [comment]
Nice working for me

**Comment by AhmadDastageer** [comment]
great answer
