### ISSUE TITLE
Invalid header

### ISSUE THREAD

**Issue by GrahamCampbell** [tymondesigns/jwt-auth#475]
You cannot use phpdoc tags in a non-phpdoc comment.

**Comment by tymondesigns** [comment]
Apparently its allowed if the `@package` keyword is present (i'll need to add that)

See https://en.m.wikipedia.org/wiki/PHPDoc

Under heading "Page-level DocBlocks"

**Comment by GrahamCampbell** [comment]
No, it's not. It it physically tokenized as a comment, not phpdoc.

**Comment by GrahamCampbell** [comment]
`@package` is deprecated, and wikipedia is frankly, a load of shit here.

**Comment by GrahamCampbell** [comment]
The only purpose of `@package` was to emulate namespaces on  php 5.2 and below.

**Comment by GrahamCampbell** [comment]
> No, it's not. It it physically tokenized as a comment, not phpdoc.

See how `/**` is `T_DOC_COMMENT` and `/*` is `T_COMMENT`.

**Comment by tymondesigns** [comment]
> No, it's not. It it physically tokenized as a comment, not phpdoc.

So the following would be valid, because it is parsed as `T_DOC_COMMENT` right ?

```php
/**
 * @author Bob
 * @link foo.com
 */
```

And I do see that StyleCI uses `T_COMMENT`

```php
/*
 * Foo bar
 */
```

What's the reason to use `T_COMMENT` over `T_DOC_COMMENT ` ?

**Comment by GrahamCampbell** [comment]
`T_DOC_COMMENT` is not widely accepted yet, and there are technical issues regarding the placement of whitespace following phpdoc that need fixing before we can allow users to choose what to use.

I'd recommend adopting the same format symfony uses for headers since that's the most widely accepted style. Basically, what you had before you changed it.

**Comment by tymondesigns** [comment]
Fair enough, I do prefer the syntax as traditional tags though, which is what led me to change it.

I'll change it back shortly
