### ISSUE TITLE
dev-master goes to stable

### ISSUE THREAD

**Issue by gil0mendes** [tymondesigns/jwt-auth#478]
Hey,

I'm trying implement JWT on a new API who I and my team we are developing. Once we are using Laravel 5.2 we want take advantage of new Guards API, for that, we using [jwt-auth-guard](https://github.com/irazasyed/jwt-auth-guard) but that package needs the dev version for your package.

I'm using this entry on the composer.json file: `"tymon/jwt-auth": "dev-master"`, but composer download the latest stable version and not the dev one.

What can I do?

**Comment by pgbastante** [comment]
You can try this

"tymon/jwt-auth": "0.6.*@dev"

**Comment by gil0mendes** [comment]
Thats works... thanks :)
