### ISSUE TITLE
Session check throws an exception

### ISSUE THREAD

**Issue by gil0mendes** [tymondesigns/jwt-auth#479]
Hey,

I'm using this piece of code to check if the user is logged `Auth::guard($guard)->check()`, but every time I call it an exception is thrown. `JWTException in JWTGuard.php line 328 - Token could not be parsed from the request.`

It's my problem?

**Comment by tdhsmith** [comment]
I haven't looked into this yet, but an FYI (from #422):

> The `JWTGuard` code is very very new, and it's likely no one has tested [every] function. [...]  The `jwt` guard should eventually stabilize (for both Laravel and Lumen), but right now it's an incomplete driver for people on Lumen who would otherwise be totally unsupported.

So if you're on Laravel I'd recommend sticking with the session guard for now.

I think you have brought up an important point with the new code though: the auth methods depending on `JWTGuard::user()` (like `check`) are going to throw exceptions when the token is invalid or nonexistent, which probably isn't the expected behavior, at least not to parallel the other guards...

**Comment by gil0mendes** [comment]
Yap, the JWTGuard not have the expected behaviour, for now I'm using try...catchs to handler with this issue... thanks for the attention :)

**Comment by tymondesigns** [comment]
Are you sure that a token is present in the request?

**Comment by tymondesigns** [comment]
Can you check the result of `Auth::getToken()` ?

**Comment by gil0mendes** [comment]
The response is `false`

**Comment by gil0mendes** [comment]
The token are not present if the login has not been done... This can't throws an exception saying `Token could not be parsed from the request.` if I'm just making a session check. Right?

**Comment by tdhsmith** [comment]
@tymondesigns I don't think he said there was always a token. I think the confusion is that `Auth::check` with another driver would simply return false in a similar situation (e.g. the session was empty).

**Comment by gil0mendes** [comment]
@tdhsmith  Yap... that is the expected behaviour.

**Comment by tymondesigns** [comment]
Ok, there's your issue.

You need to provide a token either by setting it in the Authorization header - `Authorization: Bearer foo.bar.baz`

Or just pass it in via a query string - `http://example.com/auth?token=foo.bar.baz`

**Comment by tymondesigns** [comment]
Oops looks like ilI jumped the gun there (commenting from my phone = missed replies)

I see your point. I will see if I can fix that

**Comment by tymondesigns** [comment]
Think i've fixed it. @gil0mendes could you give it a try ?

**Comment by gil0mendes** [comment]
Yap... give me a second

**Comment by gil0mendes** [comment]
Yap... it's working now... tks ;)

**Comment by tymondesigns** [comment]
Awesome :+1:
