### ISSUE TITLE
0.4 release?

### ISSUE THREAD

**Issue by SKTheo** [tymondesigns/jwt-auth#49]
Hi, first: you're doing an awesome job!!... I've implemented your 0.3.12 version successfully with L4.2 (in development enviroment), but I see that your next release will have new features and awesome things, so I wonder, are you going to release the new version soon? can I use it safely before release? or should I stay with 0.3.12? I'd like to implement 0.4 in my production enviroment... thanks for your time and dedication in this package!

**Comment by tymondesigns** [comment]
I am aiming for a release by this weeks end, so I would definately recommend holding on for that

Thanks! :smile:
