### ISSUE TITLE
Is there a function that attempt to authenticate a user, then return its object with the token?

### ISSUE THREAD

**Issue by Mahmoudz** [tymondesigns/jwt-auth#497]
The thing is, I want to attempt to authenticate a user and return the user object and its token with single query.

Currently I am attempting to authenticate the user (as shown in the line 1), to get the token.
Then I am asking for the user from that token (as shown in line 2), to get the user object.

```php
$token = $this->attempt($credentials);
$user = $this->toUser($token);
```

The problem is: that cost 2 queries for basically 1 task:

```sql
"select * from `users` where `email` = jwt@auth.com limit 1"
"select * from `users` where `id` = 1 limit 1"
```

So is there any function that return the user object with its token attached to it or something? If not I would like to contribute and add it.

Thanks.

**Comment by MallardDuck** [comment]
I could be wrong but I don't believe there would be an easy way to get around this in a way that doesn't generate 2 SQL queries. I mean you could do this:

```
$token = JWTAuth::attempt($credentials);
$user = $this->auth->user();
```

But I'm almost certain it's still doing 2 SQL queries in the above code. Another point to consider is that any performance hitches in this could be offset by a number of means. For example: Optimizing MySQL for caching, Memcache, and etc.

**Disclaimer**: I've not personally done so yet with a laravel apps  [so I could be wrong again], but I believe it should be possible. I'm a sysadmin by nature so I know those things can help in most cases, but I haven't gotten to a point with a project that I felt the need to try any of these tweaks out ever.

**Comment by Mahmoudz** [comment]
I appreciate your answer but I disagree with you as the queries are pretty much the same.
The `JWTAuth::attempt($credentials)` already queried the required user but after validating the credentials it throws it away and only generate a token out of it, to return it. While at this point it could inject the token into the object `$user->token = $token;` and return the entire object.

**Comment by w0rd-driven** [comment]
I'm unsure of which version you're on but take a look at the attempt function:
https://github.com/tymondesigns/jwt-auth/blob/master/src/JWTAuth.php#L106
If you follow the chain, $this->auth->user() is set at the moment it's authenticated.

toUser() is just an alias to authenticate(). authenticate() is meant for your protected routes that accept the token as input and populates $this->auth->user() by querying the database. There's no way to get the user object otherwise.

@MallardDuck's sample code should give you what you're looking for. $user = $this->auth->user(); doesn't make a separate SQL query, it just gets the object that has been set as part of the attempt() method call.

**Comment by tdhsmith** [comment]
Yeah agreed with @MallardDuck and @w0rd-driven. The initial `attempt` call will save the resulting user instance within the `Auth` driver (which can be retrieved and reflected by `$authProvider->user()`) for the rest of the request lifecycle.

Following the chain in Laravel 5.2, you can see that `$authGuard->lastAttempted` gets set [here](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/SessionGuard.php#L353) (which also contains the call that will spawn the DB query), and then stored to `$authGuard->user` [here](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/SessionGuard.php#L240). Subsequent calls to `Auth::user()` will simply [return this value without any DB queries](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/SessionGuard.php#L121).

**Comment by Mahmoudz** [comment]
Thanks @All that's exactly what I needed, I replaced `$user = $this->toUser($token);` with `$user = Auth::user();`.
