### ISSUE TITLE
Blacklist incompatible with database and file cache driver due to reliance on cache tags

### ISSUE THREAD

**Issue by oddz** [tymondesigns/jwt-auth#50]
The jwt auth cache driver uses tags to resolve blacklisted tokens. However, the database and file cache driver don't support tags. Therefore, when the blacklist is enabled any attempt to use the base middle ware that verifies tokens throws in an exception as seen below. The obvious quick solution to this is to use a driver other than file or database. The long term fix is change implementation of the blacklist to either not use cache tags or use a different mechanism for storing the black list when using the database or file cache driver.

call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\DatabaseStore' does not have a method 'tags'

**Comment by tymondesigns** [comment]
Ok, I have added a fallback for this. If the tags method is unavailable, then the key will be added to the root.

I will make a note of this in the docs, as most of the time it will be better to use tags if available.

Thanks
