### ISSUE TITLE
API key as a user

### ISSUE THREAD

**Issue by w0rd-driven** [tymondesigns/jwt-auth#500]
Laravel's TokenGuard is pushing me in a specific direction and the best tutorial for applying that is [here](https://gistlog.co/JacobBennett/090369fbab0b31130b51).

I use Sentinel and I like the idea of marrying a user to an api key for a few reasons:
1. As a user, they can use a normal token to login to a mechanism that generates a longer-lived api key.
2. I can apply roles to this user and using Sentinel's permission system. Instead of an API key that has blanket access to all things, I can apply fine-grained control.

I would have to alter the token generation process to strip the `exp`. I assume I would want to either extend JWTAuth or add a function to generate this token. I would want to use the same workflow as `authenticate()` and `attempt()` to make sure it could be generated under either scenario. That would give me the flexibility to use this as part of a normal login workflow or use a separate authenticated route.

I would need a way to invalidate tokens server-side and I don't know the best way to go about doing that. Store the full token in the database as the "api_token" column and pass that to JWTAuth::invalidate() to blacklist it? There also may be a use case for invalidating short-lived tokens, like in the case of locking out a user.

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
