### ISSUE TITLE
Custom identifier for token

### ISSUE THREAD

**Issue by unamix** [tymondesigns/jwt-auth#501]
I want to hide the user_id in the token payload, so i want to identify by email.
When i set identifier to email in the jwt config file, the sub gets set to the user's email when i create a token. So that's working fine. But, when i use JWTAuth::parseToken()->authenticate() in a follow up request it doesn't work because it's expecting an id as the sub: 

`if (! $this->auth->byId($id)) {`
    `return false;`
`}`

Any solution for this?

Another question not related: My users have permissions. With these permission they can do stuff on the API server. I also want to hide some elements in the client based on the permissions. Do i include these permissions in the token payload? With many permissions the token is getting a bit long..

**Comment by tdhsmith** [comment]
> Any solution for this?

Are you always using email as your identifier, outside of JWT? If so, you can set your user model's `$primaryKey = 'email'`, which will fix everything magically.

If you can't go that route, things get a little dicier. The challenge is that Laravel's `Auth` facade, which this library tries to integrate with, doesn't expose a way to retrieve a user by arbitrary query _without_ also forcing a password check. There are some workarounds but they're somewhat involved.

> I also want to hide some elements in the client based on the permissions. Do i include these permissions in the token payload?

You _could_, but I wouldn't recommend it. In most applications, jwt-auth only handles the retrieving and verifying of users, and not any additional authentication steps. After parsing the token, just run whatever checks you need on `Auth::user()`. There's some recent discussion on this in #484.

**Comment by unamix** [comment]
@tdhsmith In #484 they're discussing permissions on the API side, not the client.
So if I'm not going to store the permissions in the jwt payload, will this work and is this safe:

User posts credentials to API and receives token if valid. With the received token a new request gets send asking for the user permissions. The permissions from the response will be stored in a javascript variable. Menu items / create,edit,delete buttons in the client are shown based on the permissions in the javascript variable. If a hacker changes the variable in the browser inspector and submits a request to the API that won't work, because permissions are always checked for Auth::user().

**Comment by tdhsmith** [comment]
> permissions on the API side, not the client.

Whoops sorry! I missed the all-important word "client" in your post. :flushed: 

I think it's somewhat reasonable to store permissions information in the token if it's being communicated from the server to the client. The reason I recommended against it for the server is that I prefer the server to handle all its own checks (and to avoid being tricked by a token or introduce any errors by expecting its values to be accurate and up-to-date).

That said, I like to have a "JWT-ignorant" client that isn't able to decode/read JWTs, so I don't ever personally store data for the client in the token.

> will this work and is this safe: [...]

Yeah that seems like an adequate system; it's pretty much what I use at the moment. The most important thing is exactly as you say -- the UI elements should never have any "power" of their own because all the API calls are checked on the back.

**Comment by hauthorn** [comment]
Have you tried adding a customer [user provider](https://laravel.com/docs/5.4/authentication#adding-custom-user-providers) for the jwt guard? Which version of JWTAuth are you using?

**Comment by jsdecena** [comment]
Just in case this is not yet resolved (setting the **email** as identifier instead of **id**), we can just create our own provider and do:

```
<?php

namespace App\Providers;

use App\User;
use Tymon\JWTAuth\Exceptions\JWTException;
use Tymon\JWTAuth\Exceptions\TokenExpiredException;
use Tymon\JWTAuth\Middleware\BaseMiddleware;

class CheckUserExistenceFromToken extends BaseMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, \Closure $next)
    {
        if (! $token = $this->auth->setRequest($request)->getToken()) {
            return $this->respond('tymon.jwt.absent', 'token_not_provided', 400);
        }

        try {
            //$user = $this->auth->authenticate($token);
            $email = $this->auth->getPayload()->get('sub');
            $user = User::where(compact('email'))->first();
        } catch (TokenExpiredException $e) {
            return $this->respond('tymon.jwt.expired', 'token_expired', $e->getStatusCode(), [$e]);
        } catch (JWTException $e) {
            return $this->respond('tymon.jwt.invalid', 'token_invalid', $e->getStatusCode(), [$e]);
        }

        if (! $user) {
            return $this->respond('tymon.jwt.user_not_found', 'user_not_found', 404);
        }

        $this->events->fire('tymon.jwt.valid', $user);

        return $next($request);
    }
}
```

Just replace the:

```
'jwt.auth' => 'Tymon\JWTAuth\Middleware\GetUserFromToken',
```
to

```
'jwt.auth' => \App\Providers\CheckUserExistenceFromToken::class,
```

in `App\Http\Kernel.php`

Hope someone find this helpful! 😃
