### ISSUE TITLE
Class Tymon\JWTAuth\Providers\Storage\Illuminate does not exist

### ISSUE THREAD

**Issue by hetunandu** [tymondesigns/jwt-auth#508]
I had a problem of closure in config file so i followed instructions in this thread

https://github.com/tymondesigns/jwt-auth/issues/147

and copied the config file which made the storage file point to the Tymon\JWTAuth\Providers\Storage\Illuminate class. 

I am on 0.5.6 and I have run composer update. 

Any ideas what i am doing wrong?

**Comment by tdhsmith** [comment]
Sorry you shouldn't change the actual class, just update to the new format. (The class names change between 0.5 & 0.6)  So your storage line should be:
```php
'storage' => Tymon\JWTAuth\Providers\Storage\IlluminateCacheAdapter::class,
```

**Comment by hetunandu** [comment]
that solved it! thanks
