### ISSUE TITLE
[L5] How to use included middlewares ?

### ISSUE THREAD

**Issue by Charkhan** [tymondesigns/jwt-auth#51]
hi,

I'm trying to use your package and got stuck with the usage of JWT middleware (Seems like docs aren't updated yet , or did I missed it ?)

I don't know what class(es) to add in the `app/Http/Kernel.php`...

Did anyone face this problem ?

**Comment by JDqv** [comment]
@Charkhan just add to Kernel.php
    
    'jwt' => 'Tymon\JWTAuth\Middleware\GetUserFromToken',

At least thats what I did atm.

**Comment by Charkhan** [comment]
Thanks for the quick answer ! It worked.

Hope this will be officially documented soon :)

**Comment by tymondesigns** [comment]
docs now _mostly_ done :) [here](https://github.com/tymondesigns/jwt-auth/wiki)
