### ISSUE TITLE
Proposal : allows payload construction with \DatetimeInterface

### ISSUE THREAD

**Issue by lucasmichot** [tymondesigns/jwt-auth#510]
I think it would make sense to allows the construction of the payload using either `int` for timestamps, either `\DatetimeInterface` (for the specific claims)

**Comment by tymondesigns** [comment]
what exactly would you propose? I can't really think of a nice way to do it atm

**Comment by lucasmichot** [comment]
Create an abstract TimestampClaim which will allow either timestamps either DatetimeInterface
Or simply modify the validator of the date related claims
In JWT the timestamp is immediately converted to a Carbon instance; so it wouldn't change much IMO

**Comment by tymondesigns** [comment]
Ok i see what you mean.. ill throw something together

**Comment by lucasmichot** [comment]
I'll make a WIP PR
