### ISSUE TITLE
How to integrate ngAA to Laravel jwt-auth

### ISSUE THREAD

**Issue by essivision** [tymondesigns/jwt-auth#514]
Hi
I use ngAA to integrate Angularjs and Laravel jwt-auth. In AuthenticateController of Laravel I use this code:
```
public function authenticate(Request $request)
    {
        $credentials = $request->only('email', 'password');
        try {
            // verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->json(['error' => 'invalid_credentials'], 401);
            }
        } catch (JWTException $e) {
            // something went wrong
            return response()->json(['error' => 'could_not_create_token'], 500);
        }
        // if no errors are encountered we can return a JWT
        return response()->json(compact('token'));
    }
```
but ngAA in angularjs need to this format for response:
```
{
    token:'your jwt valid token',
    user:{
       .....,
       .....
    }
}
```
How to generate this format of token and user object in Laravel?

**Comment by mallardduck** [comment]
Bruh this is just a basic laravel question not one that is about JWT, or this package.
But I'll give you your cake anyway:

Let's start at the response, it doesn't really have much going on but we're still making a change:

```
        // if no errors are encountered we can return a JWT
        return response()->json(compact('token'));
```

That becomes:

```
return response()->json($data);
```

Ok, cool but how do we define `$data`? Well we define it how you need it to be:

```
$data = [
    'token' => $token,
    'user' => $user
]
```

And finally, the last detail to tackle; how do I get the user?

Well as long as you're not doing any thing weird that we're not aware of, you can easily do this:

```
$user = Auth::user();
```

So as long you do this after the `JWTAuth::attempt()` has succeeded then you should technically be authed with Laravel IIRC. As long as I'm remembering that fact correctly then all together you want this:

```
// if no errors are encountered we can return a JWT and User data
$user = Auth::user();
$data = [
    'token' => $token,
    'user' => $user
];
return response()->json($data);
```

Hope this gets things running along better for ya' dude. Good luck.

**Comment by essivision** [comment]
+1 Thanks
