### ISSUE TITLE
Wrong instance response on Laravel 5.2.16

### ISSUE THREAD

**Issue by massi81** [tymondesigns/jwt-auth#515]
I upgraded Laravel to v5.2.16, the package that was working fine with v5.2.15 then did stop working with the following error:

> ErrorException in ThrottleRequests.php line 94:
> 
> Argument 1 passed to Illuminate\Routing\Middleware\ThrottleRequests::addHeaders() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given, called in /var/www/Projects/nike/mostwanted/src/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php on line 53 and defined

**Comment by mallardduck** [comment]
That seems to be identifying conflicts with two things that are related to Laravel, as you may notice they are all Illuminate packages that are conflicting. I might suggest trying to clear out your vendor folder and doing a fresh `composer install` to get all the packages again.

> **Illuminate**\Routing\Middleware\ThrottleRequests::addHeaders() must be an instance of **Illuminate**\Http\Response, instance of **Illuminate**\Http\JsonResponse given

I've not used 5.2 much at all really, so I can't say much about this issue, specifically, but it seems to me that it's more likely to be an issue with Laravel itself, or it's packages, than that it's an issue with jwt-auth. So with that in mind, I'm thinking this may have a chance to fix it.

**Comment by massi81** [comment]
Thank you for your advice, unfortunately I already tried that way but it didn't fix the issue. However if i revert back to v5.2.15 everything re-start to work as expected.

**Comment by tdhsmith** [comment]
Looks like a small bug in Laravel framework, as described in laravel/framework#12309. A fix was already pushed at laravel/framework#12313 and should be available in the next version (5.2.17) whenever that releases.

**Comment by tymondesigns** [comment]
Thanks for identifying that @tdhsmith :+1:
