### ISSUE TITLE
Problem with Laravel 5.1

### ISSUE THREAD

**Issue by matiux** [tymondesigns/jwt-auth#519]
I get this error when call composer install or update in a project with Laravel 5.1

I'm using "tymon/jwt-auth": "dev-develop@dev"

Argument 3 passed to Tymon\JWTAuth\JWTAuth::__construct() must be an instance of Tymon\JWTAuth\Http\TokenParser, instance of Tymon\JWTAuth\Http\Parser given, called in /vendor/tymon/jwt-auth/src/Providers/LumenServiceProvider.php on line 144 and defined

**Comment by tdhsmith** [comment]
Have you tried updating and running again since? There was a similar issue with some of the class names a couple weeks ago on develop...
