### ISSUE TITLE
Laravel 5.2.x Setup Using JWTGuard

### ISSUE THREAD

**Issue by mtpultz** [tymondesigns/jwt-auth#534]
This is just a post of the steps to get the [JWTGuard](https://github.com/tymondesigns/jwt-auth/blob/develop/src/JWTGuard.php) in place for an API using Laravel 5.2.x to possibly help with starting the documentation of this feature, but also to see if this is the best way to implement JWTGuard.

Using JWTGuard with Laravel 5.2.x
=====

1. `config/app.php` - add `Tymon\JWTAuth\Providers\LaravelServiceProvider::class` to providers
2. `config/auth.php` - set the default guard to `api`, and change the `api` driver to `jwt`

```
'defaults' => [
    'guard' => 'api',
    'passwords' => 'users',
],
```

```
'guards' => [
    ...

    'api' => [
        'driver' => 'jwt',
        'provider' => 'users',
    ],
],
```

3. `/app/routes.php` - add a few basic authentication routes

```
Route::group([
    'prefix' => 'api'
], function () {

    $this->post('login', 'Auth\AuthController@login');
    $this->get('logout', 'Auth\AuthController@logout');
    
    Route::group([
        'prefix' => 'restricted',
        'middleware' => 'auth:api',
    ], function () {

        Route::get('/test', function () {
            return 'authenticated';
        });
    });
});
```

4. `/app/AuthController.php`

Appears to almost confirm out of the box to using the JWTGuard, while maintaining throttling on the API, except the second parameter of the call to `attempt`, is set to checking `$request->has('remember');` so in order to adhere to the JWT API.  I copied `AuthenticateUsers::login` into `AuthController` to edit the below lines.

```
public function login(Request $request)
{
    ...

    if ($token = Auth::guard($this->getGuard())->attempt($credentials)) {
        return $this->handleUserWasAuthenticated($request, $throttles, $token);
    }

    ...
}
```

5. `AuthenticatedUsers::handleUserWasAuthenticated` also needs to know about the `$token`

```
protected function handleUserWasAuthenticated(Request $request, $throttles, $token)
{
    if ($throttles) {
        $this->clearLoginAttempts($request);
    }

    if (method_exists($this, 'authenticated')) {
        return $this->authenticated($request, Auth::guard($this->getGuard())->user(), $token);
    }

    return redirect()->intended($this->redirectPath());
}
```

6. `AuthenticateUsers::handleUserWasAuthenticated` checks for  a method `authenticated`, which I added to `AuthController` to respond when authentication is successful

```
protected function authenticated($request, $user, $token)
{
    return response()->json([
        'request' => $request,
        'user'    => $user,
        'token' => $token,
    ]);
}
```

7. `AuthenticatesUsers::sendFailedLoginResponse` can be pulled up to `AuthController` to respond with JSON instead of redirecting failed authentication attempts

```
protected function sendFailedLoginResponse(Request $request)
{
    return response()->json([
        'request' => $request,
        'username' => $this->loginUsername(),
        'message'  => $this->getFailedLoginMessage(),
    ]);
}
```

8. `User` model needs to implement `Tymon\JWTAuth\Contracts\JWTSubject` (see [#260](https://github.com/tymondesigns/jwt-auth/issues/260#issuecomment-143683226), and [JWTSubject](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Contracts/JWTSubject.php))

```
...

use Tymon\JWTAuth\Contracts\JWTSubject as AuthenticatableUserContract;

use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract,
    AuthenticatableUserContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    ...

    /**
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey(); // Eloquent model method
    }

    /**
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}
```

9.  Test out whether authentication works by hitting the `/login` route with Postman

**Comment by ChitaGideon** [comment]
Use a trait to capsulate  the necessary change of `Authcontroller` could be nice
