### ISSUE TITLE
JWTException in JWTAuth.php line 295: A token is required

### ISSUE THREAD

**Issue by akimo4** [tymondesigns/jwt-auth#536]
hi . 
I want get token value, but i can't 
`$token = JWTAuth::getToken();
   return response()->json(['token' => $token],200);`
 error JWTException in JWTAuth.php line 295: A token is required.
i'm sure. my header store TOKEN.
i'm using laravel 5.1

**Comment by JustinLien** [comment]
re: "i'm sure. my header store TOKEN"

Prove it. It should have "Authorization:Bearer ..."

**Comment by AlaaSwedan** [comment]
hi I had the same error what i can do

**Comment by williansmartins** [comment]
me too

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
