### ISSUE TITLE
Invalid signatures

### ISSUE THREAD

**Issue by stuartm** [tymondesigns/jwt-auth#539]
I'm generating the token with jwt-auth but verifying it in a different application - both this application (using node-jsonwebtoken) and jwt.io are indicating the signature is invalid.

The secret I started with was generated by "php artisan jwt:generate" but I've subsequently tried other secrets, including some simple strings just to exclude any possibility of copy/paste type issues.

jwt-auth is configured to use HS256, both the client and jwt.io are expecting HS256. The decoded content of the token is correct, it's only the signature which is causing problems. This could easily be user-error, but I've no idea where to go from here.

**Comment by stuartm** [comment]
Going to close this I as verified the signature myself and it is correct, so the probably, unlikely though it seemed is that both jwt.io and node-jsonwebtoken are wrong.

One thing to note is that jwt-auth is not setting the correct type in the header of the token.

In the constructor for JWS the second argument 'JWT' needs to be specified otherwise it will default to JWS.

**Comment by stuartm** [comment]
Re-opening - this is a bug in jwt-auth. Although it's not in generating the signature but in encoding the payload. The url in the iss field is incorrectly being escaped -e.g. http:// becomes http:\/\/

jwt.io and other clients decode the payload, then re-encode without re-applying this escape resulting in signatures not matching. This much is a bug with jwt.io (ticket filed).

Per the JWT RFC - 'iss' is a StringOrURI field. StringOrURI values containing a colon **must be** valid URIs as defined by https://tools.ietf.org/html/rfc3986 - by escaping the forward slashes it is no longer a valid URI as defined by either specification.

**Comment by stuartm** [comment]
For the record, the reason signatures fail to verify on jwt.io is due to json_encode() escaping forward slashes in the iss field. jwt.io and other applications decode the payload then rebuild the token before verifying the signature. In doing this they don't escape the forward slashes and the generated signature changes.

JSON doesn't require forward slashes to be escaped, it's optional. jwt-auth is technically in the right here - other applications (most offered via Auth0) are performing the signature validation incorrectly so there are compatibility issues.

**Comment by stuartm** [comment]
With apologies for the red herrings (now deleted). This is definitely a bug - the signatures created are invalid. It's converting a hex value as an ascii/utf8 string to base64. Instead it should be converting from hex directly to base64. The bug seems to be in the Namshi/JOSE library so I'll file it upstream.

**Comment by tymondesigns** [comment]
@stuartm any update on this? Did you raise it with namshi/jose

**Comment by tymondesigns** [comment]
Ah I see that you did https://github.com/namshi/jose/pull/85 :+1:

**Comment by KrisTemmerman** [comment]
The changes in namshi/jose#85  don't work for me, any fixes?
