### ISSUE TITLE
Cache error using toUser()

### ISSUE THREAD

**Issue by gdg87** [tymondesigns/jwt-auth#54]
I update to version 0.4 and when call

    JWTAuth::toUser($token)

I have this error

    call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Cache\FileStore' does not have a method 'tags'
The error start at JWTMAnager at line 69.

**Comment by tymondesigns** [comment]
this is because the file and database cache drivers do not have the ability to add tags. 

I have published a release `0.4.1` so that this falls back silently to not use tags, so either swap your cache driver to something other than file/database or you can update to `0.4.1`

Thanks
