### ISSUE TITLE
Change authentication type from email to username?

### ISSUE THREAD

**Issue by pituseligmann** [tymondesigns/jwt-auth#540]
Hello folks, I've been reading up the issues and searching for the terms 'email', 'user' and 'username' to see if I found anything like this. Unfortunately there are some posts that may held some info but those are for older versions of this package that worked with Laravel 4.

Im running **Laravel 5.1.*** and **jwt-auth 0.5.***, and basically what I'm trying to do is after modifying the relevant user table on the DB, to make it possible to log with username instead of email. In my current setup I need the email column for something else than login, so I was hoping someone could point the right way to go about this.

Best regards

**Comment by intrepido** [comment]
I have the same problem, I need the authentication by username not email. Is there any way?

**Comment by anasceym** [comment]
Yes. There is a way, you can create a user token using JWTAuth facade credentials() method. Here is the workaround.

```
use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;

class AuthenticateController extends Controller
{
    public function authenticate(Request $request)
    {
        // grab credentials from the request
        //$credentials = $request->only('email', 'password');
        // Change email to username
        $credentials = $request->only('username', 'password');

        try {
            // attempt to verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->json(['error' => 'invalid_credentials'], 401);
            }
        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return response()->json(['error' => 'could_not_create_token'], 500);
        }

        // all good so return the token
        return response()->json(compact('token'));
    }
}
```

**Comment by pituseligmann** [comment]
Thank you @anasceym , that's a beautiful solution.

**Comment by vlafranca** [comment]
Hi,
I know this is a old thread but there is an attribute in the config.php file to handle this : 

> /*
>     |--------------------------------------------------------------------------
>     | User identifier
>     |--------------------------------------------------------------------------
>     |
>     | Specify a unique property of the user that will be added as the 'sub'
>     | claim of the token payload.
>     |
>     */
> 
>     'identifier' => 'mail',

**Comment by pankajkachhwaye** [comment]
its right but how to set credential for both email or user name

**Comment by miczed** [comment]
@pankajkachhwaye after a couple of hours I finally found a solution to make JWT auth work with  username or email:

```php
use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;

class AuthenticateController extends Controller
{
    public function authenticate(Request $request)
    {
        // assuming that the email or username is passed through a 'login' parameter
        $login = $request->input('login');
        $field = filter_var($login, FILTER_VALIDATE_EMAIL) ? 'email' : 'username';
        $request->merge([$field => $login]);
        $credentials = $request->only($field, 'password');

        try {
            // attempt to verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->json(['error' => 'invalid_credentials'], 401);
            }
        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return response()->json(['error' => 'could_not_create_token'], 500);
        }

        // all good so return the token
        return response()->json(compact('token'));
    }
}
```

**Comment by kumardinkar9** [comment]
if there is need to login with username or email:
```php
use JWTAuth;
use JWTAuthException;
class UserController extends Controller
{   
    public function login(Request $request){
        // Request input contains username, email and password
        if ($request->has(['username', 'email', 'password'])) {
            $credentials = $request->only('email', 'password');
        } // Request input contains username and password
        elseif ($request->has(['username', 'password'])) {
            $credentials = $request->only('username', 'password');
        } // Request input contains email and password
        elseif ($request->has(['email', 'password'])) {
            $credentials = $request->only('email', 'password');
        }
        else {
            $credentials = $request->only('email', 'password');
        }
        
        try {
           if (!$token = JWTAuth::attempt($credentials)) {
            return response()->json(['invalid_email_or_password']);
           }
        } catch (JWTAuthException $e) {
            return response()->json(['failed_to_create_token'], 500);
        }
        return response()->json(compact('token'));
    }
}
```

**Comment by 20170801078** [comment]
public function login(Request $request)
    {
        $field = filter_var($request->input('username'), FILTER_VALIDATE_EMAIL) ? 'email' : 'username';

        $credentials = [
            $field => $request->input('username'),
            'password' => $request->input('password')
        ];

        if (! $token = auth('api')->attempt($credentials)) {
            return response()->json(['error' => 'Unauthorized'], 401);
        }

        return $this->respondWithToken($token);
    }

**Comment by 20170801078** [comment]
Maybe this fix your problem
public function login(Request $request)
    {
        $field = filter_var($request->input('username'), FILTER_VALIDATE_EMAIL) ? 'email' : 'username';

        $credentials = [
            $field => $request->input('username'),
            'password' => $request->input('password')
        ];

        if (! $token = auth('api')->attempt($credentials)) {
            return response()->json(['error' => 'Unauthorized'], 401);
        }

        return $this->respondWithToken($token);
    }

**Comment by lucasres** [comment]
I try all but when my credentials is username and password dont work :(

Any help?

**Comment by guilherme90** [comment]
@mandala21 i have same problem. =/

**Comment by specialtactics** [comment]
If you want to do that you actually need to use an associative array when you pass it to the attempt() function, it doesn't magically know which field you want to find the user by.

Have a look at **Illuminate\Auth\EloquentUserProvider::retrieveByCredentials()**

You want to pass it this:
```php
$credentials = ['username' => $request->input('username'), 'password' => $request->input('password')];

...
JWTAuth::attempt($credentials);
```

You can form the credentials array differently based on whatever circumstance you desire, just specify the database field names of the values you want to match against, in the user table.

**Comment by avinashseth** [comment]
Hi, i would like to check certain conditions also before letting user it!
