### ISSUE TITLE
How to make whitelist IP?

### ISSUE THREAD

**Issue by donnygunawan93** [tymondesigns/jwt-auth#545]
Hello Buddy ^_^,
I want my API only can access from my server,
I don't want other people to access my API,

so I need something like whitelist IP? how do that?

**Comment by mallardduck** [comment]
You should be researching on how to do that by configuring the webserver
for that, this isn't something JWT should be involved with.

Figure out if you use Apache or Nginx and then Google 'Apache IP
whitelist', or Google for Nginx if you use that.

**Comment by tymondesigns** [comment]
as @mallardduck has said, it has nothing to do with this package. But I will point you in the right direction :) -> https://github.com/antonioribeiro/firewall
