### ISSUE TITLE
multiple roles

### ISSUE THREAD

**Issue by alireza2281** [tymondesigns/jwt-auth#548]
Hello i want to implement multiple role system with jwt. My question is if this is possible. and my other question is if i can extract the username of the authenticated account from the token

**Comment by rafaelrenanpacheco** [comment]
> Hello i want to implement multiple role system with jwt. My question is if this is possible.

Yes, this has nothing to do with jwt authentication.

> my other question is if i can extract the username of the authenticated account from the token

In the backend, yes. The backend has the private key to decode the encrypted token, which was encrypted with the public key.

In the frontend, no. The frontend doesn't have and should not have the private key to decode the JWT. If you need to send some additional information to the frontend, you can add them to the JSON that is sent to the front. Using AuthController from 1.0 as an example, you would put this additional info in respondWithToken().
