### ISSUE TITLE
Use multiple user models for authentication

### ISSUE THREAD

**Issue by shanavas786** [tymondesigns/jwt-auth#549]
jwt-auth uses a user model for authentication defaulted to App\User. How is it possible to use request specific user model ?. ie, to use Model1 for controller1 and Model2 for controller2 ..etc ?

**Comment by westhacker** [comment]
Modifier vendor/tymon/jwt-auth/src/config/config.php, change` 'user' => 'App\User',` to `'user' => 'App\Models\User'`.

More configuration is in [wiki](https://github.com/tymondesigns/jwt-auth/wiki/Configuration)
