### ISSUE TITLE
Remove claims from tokens

### ISSUE THREAD

**Issue by SKTheo** [tymondesigns/jwt-auth#55]
Hi !! Is it possible to remove a claim from a previously created token? (Or create tokens with different default claims?) If so, how?
For example, I want to have tokens without expiry time. I know I can create a token with custom claims, but in this case I'm doing this:
$token = JWTAuth::fromUser($user);
and that is way easier than:
$customClaims = [(all the default claims except exp)];
$payload = app('tymon.jwt.payload.factory')->make($customClaims);
$token = JWTAuth::encode($payload);

(P.S.: I've managed to remove the 'exp' claim from all tokens by editing the file "PayloadFactory.php", but I think that's not what I'm looking for)

**Comment by JDqv** [comment]
You could set exp time in far far future...
Have you considered using refresh tokens?
You can't remove or alter claim for previously created token as it wont decode properly and will become invalid.

**Comment by tymondesigns** [comment]
yea, I wouldn't recommend a non-expiring token, can you describe your use-case for that?

I might make the default claims configurable, since [the spec](http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#expDef) states that no claims are mandatory. I'll have think about that

**Comment by SKTheo** [comment]
You're right, I know it's a bad idea, but I was requested to do that for a mobile app (they don't want to try the refresh token =/ )... I might set the expiry time to a year better
