### ISSUE TITLE
Protected property

### ISSUE THREAD

**Issue by matiux** [tymondesigns/jwt-auth#550]
Hi,
I need to use the branch 0.5.\* because the refresh token is better documented (compared to dev-master). But with 0.5.\* I have a problem with laravel-doctrine package. My "User" entity has a protected $id, so I get this error:

Cannot access protected property Vendor\Entity\User::$id

generated by vendor/tymon/jwt-auth/src/JWTAuth.php in fromUser() method.

With dev-master I don't have this error

**Comment by matiux** [comment]
This is my controller action:

```
    public function authenticate(Request $request)
    {
        $user = $this->userFromRequestService->getByCredentials($request);

        if (!$user) {

            return response()->json(['error' => 'invalid_credentials'], 401);
        }

        try {

            $token = JWTAuth::fromUser($user);

        } catch (JWTException $e) {

            return response()->json(['error' => 'could_not_create_token'], 500);
        }

        $user = $this->userSerializerService->handle($user, compact('token'));

        return $user;
    }
```

**Comment by matiux** [comment]
Ping!

**Comment by tdhsmith** [comment]
Are you still wishing to use the ID as your JWT's subject field?  Do you have some sort of ID getter method on the User?  If so, you can just repurpose [the internals of the `fromUser` method](https://github.com/tymondesigns/jwt-auth/blob/0.5.9/src/JWTAuth.php#L91):

```php
try {
    $payload = $this->makePayload($user->getID());
    $token = $this->manager->encode($payload)->get();
}
```

If you want to use a different JWT subject, you'll want to change the `identifier` config value to that field.

>  because the refresh token is better documented (compared to dev-master)

Care to expand on what you're looking for here? Many of general commands should still be the same, just with more features.

**Comment by matiux** [comment]
What do you mean with "you can just repurpose" ?
in my controller I can't use makePayload because in 0.5 version is private.

In dev branch, the behavior is right also with private property beacuse my User class implements the interfaces with getJWTCustomClaim() and getJWTIdentifier()

**Comment by surinderpalsingh** [comment]
Hi
I'm using v0.5.9 and I'm getting same error with doctrine.

Cannot access private property App\Entities\User::$id

Please help me.

Thanks
