### ISSUE TITLE
Token only valid on homestead

### ISSUE THREAD

**Issue by saurini** [tymondesigns/jwt-auth#558]
I've been wrestling with this one for a few hours now. I'm testing the validity of the token by using the jwt.io debugger. When the token is created in homestead, it is verified with the secret. The production (pre-prod at the moment) environment produces a token that doesn't work. It's the exact same code and nearly (7.0.1 vs 7.0.2) same version of PHP. What could be the cause?

php -m on homestead:

```bcmath
calendar
Core
ctype
curl
date
dba
dom
enchant
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
```

php -m on prod

```bcmath
calendar
Core
ctype
date
dba
dom
enchant
exif
fileinfo
filter
ftp
gettext
gmp
hash
iconv
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
```

How the token is buit:

```
$claims = $user->claims()->lists('name')->toArray();

$now = time();
$jti = hash('sha1', $user->email . '-' . $now);

$jwtClaims = [
    'sub' => $user->email,
    'iss' => env('JWT_ISSUER', '[default removed]'),
    'aud' => null,
    'exp' => $now + 1209600, // 14 days
    'nbf' => $now - 300, // 5 minutes ago
    'iat' => $now,
    'jti' => $jti,
    'access' => $claims
];

$payload = JWTFactory::make($jwtClaims);
$token = JWTAuth::encode($payload)->get();

**Comment by tdhsmith** [comment]
> The production (pre-prod at the moment) environment produces a token that doesn't work.

In what way is it not working? Are you able to share an example of each token?

**Comment by saurini** [comment]
Actually... this is really embarrassing. So, JWT_SECRET was spelled JWT_SECRT. I'll just show myself out.

![](http://i.imgur.com/nVFh5tr.gif)

**Comment by tdhsmith** [comment]
No problem! We've all been inside of that cube at times...
