### ISSUE TITLE
Method [login] does not exist.

### ISSUE THREAD

**Issue by numnine** [tymondesigns/jwt-auth#56]
Hi,

I'm using v0.4.1 and get this error:

```
tymon/jwt-auth/src/JWTAuth.php line 314
Method [login] does not exist.
```

My request header is "Authorization: Bearer {access token}'

**Comment by tymondesigns** [comment]
The login method has been renamed to authenticate

**Comment by numnine** [comment]
I see. Thanks!

**Comment by ndnam90** [comment]
Sr. how to fix it. thanks

**Comment by numnine** [comment]
Use 0.3.* can fix it.
