### ISSUE TITLE
Add method, header & query parameters to getToken

### ISSUE THREAD

**Issue by Sopamo** [tymondesigns/jwt-auth#560]
Currently the getToken method calls the parseToken method with default parameters. I would like to have the possibility to call the getToken method with specific parameters as well.
Should I submit a pull request?

**Comment by mattboban** [comment]
I second this. I would actually need it on a project in the next day or so. Is this beeing worked on by somebody or should look at the implementation from my end?

**Comment by Sopamo** [comment]
I worked around the issue by calling parseToken manually prior to the getToken call. This way the token is already stored and used by getToken:

    JWTAuth::parseToken("bearer","X-MY-AUTHORIZATION");
    $token = JWTAuth::getToken();

**Comment by mattboban** [comment]
Did you implement this within a custom Middleware? And if so, could you share sample code, thanks.

**Comment by Sopamo** [comment]
No, I just use it at the point where I need the token to fetch the user from the database. This is my code

```
function user() {
    if(app()->env == "testing") {
        $token = JWTAuth::getToken();
    } else {
        JWTAuth::parseToken("bearer","X-MY-AUTHORIZATION");
        $token = JWTAuth::getToken();
    }
    
    if(!$user = JWTAuth::authenticate($token)) {
        return null;
    }
        
    return $user;
}
```

**Comment by mattboban** [comment]
The difference is that I need a middleware implementation. It turns out its simplistic. Create new middleware (copy from vendor folder and modify), with one line change.


```
<?php

namespace App\Http\Middleware;

use Closure;
use Tymon\JWTAuth\JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;
use Tymon\JWTAuth\Exceptions\TokenExpiredException;

use Tymon\JWTAuth\Middleware\BaseMiddleware;

class JWTAuthUser extends BaseMiddleware
{
    public function handle($request, Closure $next, $guard = null)
    {

        // Set custom header name for token
        $this->auth->setRequest($request)->parseToken("bearer","Apptoken");


        if (! $token = $this->auth->setRequest($request)->getToken()) {
            return $this->respond('tymon.jwt.absent', 'token_not_provided', 400);
        }

        try {
            $user = $this->auth->authenticate($token);
        } catch (TokenExpiredException $e) {
            return $this->respond('tymon.jwt.expired', 'token_expired', $e->getStatusCode(), [$e]);
        } catch (JWTException $e) {
            return $this->respond('tymon.jwt.invalid', 'token_invalid', $e->getStatusCode(), [$e]);
        }

        if (! $user) {
            return $this->respond('tymon.jwt.user_not_found', 'user_not_found', 404);
        }

        $this->events->fire('tymon.jwt.valid', $user);

        return $next($request);
    }


}
```


This should possibly be included in the documentation.

**Comment by tdhsmith** [comment]
Just a note that over in #718 I described how this kind of configuration can be accomplished on the 1.0 branch. We're discussing headers specifically, but that approach can be applied to [any of the `Parser` classes](https://github.com/tymondesigns/jwt-auth/tree/1.0.0-alpha.2/src/Http/Parser).

(`parseToken` works differently on 1.0 and no longer takes parameters in any circumstances, so the solution here won't work.)
