### ISSUE TITLE
Unresolvable dependency resolving $app in AuthManager

### ISSUE THREAD

**Issue by hopewise** [tymondesigns/jwt-auth#561]
I am wondering why would I get such an error if I tried to jwt.auth ?

`{"message":"Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\\Auth\\AuthManager","status_code":500,"debug":{"line":839,"file":"\/share\/vendor\/illuminate\/container\/Container.php","class":"Illuminate\\Contracts\\Container\\BindingResolutionException","trace":["#0 \/share\/vendor\/illuminate\/container\/Container.php(806): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))","#1 \/share\/vendor\/illuminate\/container\/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)","#2 \/share\/vendor\/illuminate\/container\/Container.php(633): Illuminate\\Container\\Container->build('Illuminate\\Auth...', Array)","#3 \/share\/vendor\/laravel\/lumen-framework\/src\/Application.php(205): Illuminate\\Container\\Container->make('Illuminate\\Auth...', Array)","#4 \/share\/vendor\/illuminate\/container\/Container.php(853): Laravel\\Lumen\\Application->make('Illuminate\\Auth...')","#5 \/share\/vendor\/illuminate\/container\/Container.php(808): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))","#6 \/share\/vendor\/illuminate\/container\/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)","#7 \/share\/vendor\/illuminate\/container\/Container.php(633): Illuminate\\Container\\Container->build('Tymon\\JWTAuth\\P...', Array)","#8 \/share\/vendor\/laravel\/lumen-framework\/src\/Application.php(205): Illuminate\\Container\\Container->make('Tymon\\JWTAuth\\P...', Array)","#9 \/share\/vendor\/tymon\/jwt-auth\/src\/Providers\/JWTAuthServiceProvider.php(273): Laravel\\Lumen\\Application->make('Tymon\\JWTAuth\\P...')","#10 \/share\/vendor\/tymon\/jwt-auth\/src\/Providers\/JWTAuthServiceProvider.php(148): Tymon\\JWTAuth\\Providers\\JWTAuthServiceProvider->getConfigInstance('Tymon\\JWTAuth\\P...')","#11 \/share\/vendor\/illuminate\/container\/Container.php(289): Tymon\\JWTAuth\\Providers\\JWTAuthServiceProvider->Tymon\\JWTAuth\\Providers\\{closure}(Object(Laravel\\Lumen\\Application))","#12 \/share\/vendor\/illuminate\/container\/Container.php(735): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Laravel\\Lumen\\Application), Array)","#13 \/share\/vendor\/illuminate\/container\/Container.php(633): Illuminate\\Container\\Container->build(Object(Closure), Array)","#14 \/share\/vendor\/laravel\/lumen-framework\/src\/Application.php(205): Illuminate\\Container\\Container->make('tymon.jwt.provi...', Array)","#15 \/share\/vendor\/illuminate\/container\/Container.php(1178): Laravel\\Lumen\\Application->make('tymon.jwt.provi...')","#16 \/share\/vendor\/tymon\/jwt-auth\/src\/Providers\/JWTAuthServiceProvider.php(199): Illuminate\\Container\\Container->offsetGet('tymon.jwt.provi...')","#17 \/share\/vendor\/illuminate\/container\/Container.php(289): Tymon\\JWTAuth\\Providers\\JWTAuthServiceProvider->Tymon\\JWTAuth\\Providers\\{closure}(Object(Laravel\\Lumen\\Application))","#18 \/share\/vendor\/illuminate\/container\/Container.php(735): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Laravel\\Lumen\\Application), Array)","#19 \/share\/vendor\/illuminate\/container\/Container.php(633): Illuminate\\Container\\Container->build(Object(Closure), Array)","#20 \/share\/vendor\/laravel\/lumen-framework\/src\/Application.php(205): Illuminate\\Container\\Container->make('tymon.jwt.auth', Array)","#21 \/share\/vendor\/illuminate\/container\/Container.php(1178): Laravel\\Lumen\\Application->make('tymon.jwt.auth')","#22 \/share\/vendor\/tymon\/jwt-auth\/src\/Providers\/JWTAuthServiceProvider.php(52): Illuminate\\Container\\Container->offsetGet('tymon.jwt.auth')","#23 \/share\/vendor\/illuminate\/container\/Container.php(735): Tymon\\JWTAuth\\Providers\\JWTAuthServiceProvider->Tymon\\JWTAuth\\Providers\\{closure}(Object(Laravel\\Lumen\\Application), Array)","#24 \/share\/vendor\/illuminate\/container\/Container.php(633): Illuminate\\Container\\Container->build(Object(Closure), Array)","#25 \/share\/vendor\/laravel\/lumen-framework\/src\/Application.php(205): Illuminate\\Container\\Container->make('Tymon\\JWTAuth\\J...', Array)","#26 \/share\/vendor\/illuminate\/container\/Container.php(853): Laravel\\Lumen\\Application->make('Tymon\\JWTAuth\\J...')","#27 \/share\/vendor\/illuminate\/container\/Container.php(808): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))","#28 \/share\/vendor\/illuminate\/container\/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)","#29 \/share\/vendor\/illuminate\/container\/Container.php(633): Illuminate\\Container\\Container->build('Tymon\\JWTAuth\\M...', Array)","#30 \/share\/vendor\/laravel\/lumen-framework\/src\/Application.php(205): Illuminate\\Container\\Container->make('Tymon\\JWTAuth\\M...', Array)","#31 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(123): Laravel\\Lumen\\Application->make('Tymon\\JWTAuth\\M...')","#32 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#33 \/share\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#34 [internal function]: Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#35 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#36 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(621): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#37 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(470): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#38 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(448): Laravel\\Lumen\\Application->handleFoundRoute(Array)","#39 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(381): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#40 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(624): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()","#41 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#42 \/share\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))","#43 \/share\/vendor\/dingo\/api\/src\/Routing\/Router.php(558): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#44 \/share\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(112): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#45 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#46 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#47 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#48 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#49 \/share\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(113): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#50 \/share\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(89): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#51 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))","#52 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(124): call_user_func_array(Array, Array)","#53 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#54 \/share\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#55 [internal function]: Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#56 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#57 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(621): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#58 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#59 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(327): Laravel\\Lumen\\Application->dispatch(NULL)","#60 \/share\/public\/index.php(28): Laravel\\Lumen\\Application->run()","#61 \/share\/vendor\/mlntn\/lumen-artisan-serve\/src\/server.php(21): require_once('\/share\/public\/i...')","#62 {main}"]}}`

**Comment by hopewise** [comment]
Ok, I found the solution by:

```
$app->singleton(Illuminate\Auth\AuthManager::class, function ($app) {
    return $app->make('auth');
});
```

but then I got this error:

`{"message":"Undefined index: provider","status_code":500,"debug":{"line":152,"file":"\/share\/vendor\/illuminate\/auth\/AuthManager.php","class":"ErrorException","trace":["#0 \/share\/vendor\/illuminate\/auth\/AuthManager.php(152): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(8, 'Undefined index...', '\/share\/vendor\/i...', 152, Array)","#1 \/share\/vendor\/illuminate\/auth\/AuthManager.php(92): Illuminate\\Auth\\AuthManager->createTokenDriver('api', Array)","#2 \/share\/vendor\/illuminate\/auth\/AuthManager.php(70): Illuminate\\Auth\\AuthManager->resolve('api')","#3 \/share\/vendor\/illuminate\/auth\/AuthManager.php(282): Illuminate\\Auth\\AuthManager->guard()","#4 \/share\/vendor\/tymon\/jwt-auth\/src\/Providers\/Auth\/IlluminateAuthAdapter.php(50): Illuminate\\Auth\\AuthManager->__call('onceUsingId', Array)","#5 \/share\/vendor\/tymon\/jwt-auth\/src\/Providers\/Auth\/IlluminateAuthAdapter.php(50): Illuminate\\Auth\\AuthManager->onceUsingId(2)","#6 \/share\/vendor\/tymon\/jwt-auth\/src\/JWTAuth.php(126): Tymon\\JWTAuth\\Providers\\Auth\\IlluminateAuthAdapter->byId(2)","#7 \/share\/vendor\/tymon\/jwt-auth\/src\/Middleware\/GetUserFromToken.php(33): Tymon\\JWTAuth\\JWTAuth->authenticate(Object(Tymon\\JWTAuth\\Token))","#8 [internal function]: Tymon\\JWTAuth\\Middleware\\GetUserFromToken->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#9 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(124): call_user_func_array(Array, Array)","#10 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#11 \/share\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#12 [internal function]: Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#13 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#14 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(621): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#15 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(470): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#16 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(448): Laravel\\Lumen\\Application->handleFoundRoute(Array)","#17 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(381): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)","#18 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(624): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()","#19 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#20 \/share\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Lumen.php(103): Laravel\\Lumen\\Application->dispatch(Object(Dingo\\Api\\Http\\Request))","#21 \/share\/vendor\/dingo\/api\/src\/Routing\/Router.php(558): Dingo\\Api\\Routing\\Adapter\\Lumen->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#22 \/share\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(112): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#23 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#24 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#25 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#26 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))","#27 \/share\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(113): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#28 \/share\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(89): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#29 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))","#30 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(124): call_user_func_array(Array, Array)","#31 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#32 \/share\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#33 [internal function]: Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#34 \/share\/vendor\/illuminate\/pipeline\/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))","#35 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(621): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#36 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(382): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))","#37 \/share\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(327): Laravel\\Lumen\\Application->dispatch(NULL)","#38 \/share\/public\/index.php(28): Laravel\\Lumen\\Application->run()","#39 `

**Comment by tdhsmith** [comment]
Version 0.5.* really has no solid Lumen support. It depends on a number or Laravel-specific assumptions.

You might be able to continue down this route injecting the necessary dependencies, but it will be much easier to move to the 1.0.0-alpha1 branch. There you can use the `jwt` auth driver which works much more smoothly with Lumen.

**Comment by hopewise** [comment]
Nice to see the new branch :+1:  Would I still need to write a guard to authenticate laravel users via jwt? what about middleware in this case? is there an example?
