### ISSUE TITLE
something confused about the auth.php

### ISSUE THREAD

**Issue by pensacola1989** [tymondesigns/jwt-auth#563]
does jwt-auth use config/auth.php,
seems if a set default guard to api,
everything crashed...

```
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
 'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
    ],
```

but If I don't make any change on the auth.php,Everything works fine!, 
So what's the problem?thx

**Comment by tymondesigns** [comment]
We'd need to see your error stack trace

**Comment by pensacola1989** [comment]
sorry, no more logs or tracks I was got, just crash, but when I leave the config clean,which just set "defaults" guard to "web", it works as expected...So I just keep guard "web" now, I haven't see your source code yet, but Is jwt-auth works without "auth.php"?
