### ISSUE TITLE
question with Lumen 5.2

### ISSUE THREAD

**Issue by abcsun** [tymondesigns/jwt-auth#564]
anyone knows which version works well with Lumen 5.2 ?

when i tried to use  the JWTAuth facade, an exception was logged as below
```
[2016-03-08 07:09:01] lumen.ERROR: exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Cache\CacheManager' in /home/vagrant/projects/lumen-master/vendor/illuminate/container/Container.php:839
...
```
and my composer.json
```
"require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "5.2.*",
        "vlucas/phpdotenv": "~2.2",
        "dingo/api": "1.0.x@dev",
        "tymon/jwt-auth": "^0.5.9"
    },
```

**Comment by patrickdronk** [comment]
Got the same problem. And i'm not that skilled to solve this xD. Have been searching for a while no succes :(

**Comment by patrickdronk** [comment]
in your config/jwt.php replace existing code with 

      'auth' => function ($app) {
          return new Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter($app['auth']);
      },


      'storage' => function ($app) {
          return new Tymon\JWTAuth\Providers\Storage\IlluminateCacheAdapter($app['cache']);
      }

**Comment by abcsun** [comment]
@patrickdronk my jwt.php is the same as you posted. any other suggests, thanks

**Comment by tdhsmith** [comment]
You're going to have a hard time getting it to work with 0.5. Try the new 1.0.0-alpha1 tag. @mtpultz made a great guide on setting it up Lumen with that branch in https://github.com/tymondesigns/jwt-auth/issues/513#issuecomment-186087297.

**Comment by jonsa** [comment]
@abcsun  Here is a [gist](https://gist.github.com/jonsa/90a8bf9b4ecac7f9dd2d) I made with the changes I needed to make to get JWT working on a fresh lumen project. You should be able to download the ZIP and just paste the files into the project directory.

**Comment by jonsa** [comment]
I didn't see at first that you used Dingo aswell. Here is a similar [gist](https://gist.github.com/jonsa/ab3a07ab8938375a6c9f) but using Dingo to create the API routes. Unfortunately this [commit](https://github.com/dingo/api/commit/5775a31f887ac52999bcac5e589af6cb6c64bae9) broke the authentication process when using the dev branch of jwt-auth. Which is why there is a hardcoded commit reference in the composer.json.

**Comment by abcsun** [comment]
Thanks for your [gist](https://gist.github.com/jonsa/ab3a07ab8938375a6c9f) @jonsa , it works well. 
@tdhsmith thanks for you link to #513

**Comment by JPeer264** [comment]
@jonsa  - please update your composer.json in your gist from `"tymon/jwt-auth": "0.6.*@dev"` to `"tymon/jwt-auth": "1.0.*@dev"` since the `0.6.*@dev` is no longer available. #685

**Comment by antonioreyna** [comment]
i have this same problem on laravel, any solution?
