### ISSUE TITLE
Getting User After Initial Middleware Authentication

### ISSUE THREAD

**Issue by dtirer** [tymondesigns/jwt-auth#566]
After applying the `jwt-refresh` (or auth) middleware to a group of routes, the user validates successfully and the request proceeds.  However, In a Controller, if I then want to retrieve the User that I just authenticated via the Middleware, how do I do that?  I suppose I could call `JWTAuth::parseToken()->toUser();`, but that seems redundant because the Middleware presumably just ran the same code.

**Comment by abhimanyusharma003** [comment]
You need to set `Authorization Bearer {token}` as header. Also make sure that token get change after every request because you are using jwt-refresh.

**Comment by dtirer** [comment]
@abhimanyusharma003 Thanks for the info, but like I said, I am successfully accomplishing this.  The middleware is authenticating the User.  However, my question is, after the middleware passes and the user is routed to my controller, how do I retrieve the User which the middleware successfully authenticated without running `authenticate` again?

**Comment by gerob** [comment]
@dtirer You would use `Auth::user()`

**Comment by dtirer** [comment]
@gerob thanks but that doesn't seem to work, it just returns NULL.  I know the token works though because if I `dd(JWTAuth::parseToken()->toUser())`` it returns a User model.  But applying the middleware and then trying to retrieve the User in a Controller with `Auth::user()` just seems to return Null

**Comment by gerob** [comment]
@dtirer You must have something else interfering with your user info. 

I basically have this.

```
Route::group(['middleware' => ['api'], 'prefix' => 'api'], function () {
    Route::post('auth', 'Auth\AuthController@authenticate');

    /*
     * Authentication Required
     */
    Route::group(['middleware' => ['jwt.auth']], function () {
        Route::resource('users', 'UsersController', ['only' => ['index', 'update']]);
    });
});
```

```
class UsersController extends Controller
{
    public function index()
    {
        return response()->json(['user' => Auth::user()]);
    }

    public function update(UpdateUserRequest $request)
    {
        User::update($request->all());

        return response()->json(['success' => true]);
    }
}
```

**Comment by dtirer** [comment]
@gerob as I just discovered, `Auth::user()` seems to work with `jwt.auth`, but not with `jwt.refresh`.  My  route group is setup as follows:

 `Route::group(['middleware' => ['jwt.refresh']], function () {`

Am I going about this incorrectly?

**Comment by gerob** [comment]
What the `jwt.refresh` does is send back a new token if your old one has expired. You would need to make another request to be able to retrieve the user.

`Route::group(['middleware' => ['jwt.auth', 'jwt.refresh']], function () {`

**Comment by dtirer** [comment]
@gerob Ok I think I figured it out.  You can use both Middleware on the route group, however, it seems that `jwt.refresh` has to be before `jwt.auth`:

` Route::group(['middleware' => [ 'jwt.refresh', 'jwt.auth']], function() { `

Now, I can use `Auth::user()` to access my User, and my token will regenerate with every request!

**Comment by gerob** [comment]
I don't know that you should have to refresh the token on every request. The refresh middleware has a check for an expired token where it returns an error.

https://github.com/tymondesigns/jwt-auth/blob/master/src/Middleware/RefreshToken.php#L33

**Comment by dtirer** [comment]
@gerob hm, but per the docs, It seems the idea is that it should be on every request, so that it functions as a single use token:

"This middleware will again try to parse the token from the request, and in turn will refresh the token (thus invalidating the old one) and return it as part of the next response. This essentially yields a single use token flow, which reduces the window of attack if a token is compromised, since it is only valid for the single request."

And it seems that `jwt.auth` also throws the same exception for an expired token:
https://github.com/tymondesigns/jwt-auth/blob/master/src/Middleware/GetUserFromToken.php#L35

**Comment by gerob** [comment]
That makes sense. I'm glad you got it figured out. :)

**Comment by dtirer** [comment]
@gerob thanks for your help!
