### ISSUE TITLE
AngularJS Remember me functionality using JWT Auth

### ISSUE THREAD

**Issue by nareshnraj** [tymondesigns/jwt-auth#570]
Hi All,

I have developed an Spring Web application using Angular JS. For the current project the client side authentication is using Cookies.
After learning the advantage JWTs, I wish to rewrite the application Authentication using JWTs.

My concern is How to handle "Rember Me" Functionality using JWT in AngularJS.

If anyone of you experts can share me suggestion or code. It would be really helpful. I tried searching internet and failed to get an sample implementation to refer.

Thanks.

**Comment by mateusjatenee** [comment]
You have to implement it. JWT will just return you a token — it's up to you to save that token in your application and use it later. Just set the right expiration time.

**Comment by tdhsmith** [comment]
Yeah it's up to you to supply this. Generally the choice for webapps is between cookies and the various HTML storage APIs (i.e. `localStorage`, `sessionStorage`). Cookies have the potential to be much more robust to XSS attacks, but they make front-end manipulation of the token challenging-to-impossible, compared to the storage APIs.

If you're building a mobile or desktop application you'll have many other storage options.

**Comment by mateusjatenee** [comment]
I think this issue should be closed, no?

**Comment by tymondesigns** [comment]
Yup
