### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by djoks** [tymondesigns/jwt-auth#571]
I want to be able to use the BLACKLIST_GRACE_PERIOD feature, I updated to the lastest with composer:

""tymon/jwt-auth": "5.*","

However this feature did not appear to be in it, it only appears to be in the "dev-develop@dev"
and when i change to that and then try to publish it I get an error:

" [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider' not found"

Please how do i fix this, how do i install and use the develop branch?

-

**Comment by abhimanyusharma003** [comment]
It is tagged as `1.0.0-alpha.1` so you can use ` "tymon/jwt-auth": "1.0.0-alpha.1",`
Also you have to use
```
Tymon\JWTAuth\Providers\LaravelServiceProvider
``` 
There are many more things that are change little bit, you have wait for docs if you don't know what you are doing or you will break things.

**Comment by djoks** [comment]
Oh okay, thank you very much, good to know. :D
