### ISSUE TITLE
some confuesd about the refresh token(not a issue, just for discussing)

### ISSUE THREAD

**Issue by pensacola1989** [tymondesigns/jwt-auth#579]
as We know, like facebook, twitter's mobile app, jsut need to login once,(never need login again)
**Except**
"you haven't open the app for a long time(for example: 1 week or other)"

and I figure that , In jwt.php

```
    /*
    |--------------------------------------------------------------------------
    | Refresh time to live
    |--------------------------------------------------------------------------
    |
    | Specify the length of time (in minutes) that the token can be refreshed
    | within. I.E. The user can refresh their token within a 2 week window of
    | the original token being created until they must re-authenticate.
    | Defaults to 2 weeks
    |
    */

    'refresh_ttl' => 20160,
```

does this mean "If user reached the 'refresh_ttl(notice not ttl :D)', the user is required to be logged in again with their pass? and does "JWT-Auth" consider this scene? thanks for read

**Comment by Brave-Cheng** [comment]
Thanks @pensacola1989 . i have same problem with it.  i'm alse confused how to do with the refresh_ttl

**Comment by pensacola1989** [comment]
@Brave-Cheng I think 
I think jwt-auth already handle with it ,but we misunderstand *"within a 2 week window of the original token being created"* which means if you haven't refresh for 2 weeks, that required to login again ,am I right?
@tymondesigns

**Comment by tdhsmith** [comment]
> I think jwt-auth already handle with it ,but we misunderstand "within a 2 week window of the original token being created" which means if you haven't refresh for 2 weeks, that required to login again ,am I right?

Yes. The token can be refreshed until `refresh_ttl` minutes have passed *from the original token creation*.

![image](https://cloud.githubusercontent.com/assets/1791252/9459832/860d7370-4ac5-11e5-9b01-d4f78751209f.png)

**Comment by Brave-Cheng** [comment]
@tdhsmith  you have not reply above problem.

> "refresh_ttl" does this mean "If user reached the 'refresh_ttl(notice not ttl :D)', the user is required to be logged in again with their pass? 

if usere reached the 'refresh_ttl', so the user must be logged in again?

**Comment by pensacola1989** [comment]
@Brave-Cheng  refresh_ttl means "if you haven't refresh your token for a long time"

**Comment by pensacola1989** [comment]
@tdhsmith  thx for the reply，still some questions about the “jwt.refresh” middleware， I think "jwt.refresh" middleware for the "refresh route" is to solve (if you want get the old token, you need privoder the token, but "jwt.auth" will throw a "expiredExceptin", so we need "jwt.refresh"," is that correct?
