### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by marciomansur** [tymondesigns/jwt-auth#58]
I need to logout and remove the token from session. How can I do this?

**Comment by ZengineChris** [comment]
It is hard to say without any informations about your use case. There is no logout in a jwt auth system. You can set the expiration time lower or overwrite the token in the session with a invalid default. Laravel has the Session. One of the benefits of jwt is that you don't store any sessions or tokens in a database. I hope this is helpful.

**Comment by tymondesigns** [comment]
Depending on your client implementation. You should remove the token from the client. E.g. delete it from localStorage or something (if you are running a single page app for example). Alongside this you should invalidate the token, so it can no longer be used e.g.

```php
JWTAuth::invalidate($token);
```

**Comment by marciomansur** [comment]
Thanks. @tymondesigns ! When the user logs out, I need to "detroy" (or invalidate) the token, so he can't do anything in the app while not logged in. This method clears the token in session? Thanks.

**Comment by hungvtitdng** [comment]
I can't use `JWTAuth::invalidate($token);` for force logout user has been banned
