### ISSUE TITLE
Namshi problem after dev-develop@dev update

### ISSUE THREAD

**Issue by matiux** [tymondesigns/jwt-auth#583]
After dev-develop@dev update, I get this error:

Argument 3 passed to Tymon\JWTAuth\Providers\JWT\Namshi::__construct() must be of the type array, null given

**Comment by tymondesigns** [comment]
is this issue present when requiring `1.0.0-alpha1` ?

**Comment by matiux** [comment]
"tymon/jwt-auth": "dev-develop@dev",

**Comment by crynobone** [comment]
Di you have the updated config schema?

**Comment by feeekkk** [comment]
Once I updated the config schema this error went away
