### ISSUE TITLE
How to use Cartalyst\Sentry instead of Illuminate\Auth?

### ISSUE THREAD

**Issue by pkhodaveissi** [tymondesigns/jwt-auth#59]
sorry to ask this here!

I've seen you have created a file named IlluminateAuthAdapter.php, I wanted to know how could I accomplish having a SentryAuthAdapter.php file

thanks dear

**Comment by hackel** [comment]
This is not a bug, it is a support request.  Please never do this again.

I just did this for my own project.  See here:
https://gist.github.com/hackel/00a2b5a43d5007eceaa1

**Comment by tymondesigns** [comment]
@pkhodaveissi you can go ahead and use @hackel's link there. 

@hackel I think I may change the way providers are passed in via the config so that dependency injection is possible
