### ISSUE TITLE
class 'Illuminate\Auth\SessionGuard' does not have a method 'createJwtDriver'

### ISSUE THREAD

**Issue by rakesh-ideal** [tymondesigns/jwt-auth#595]
Can anybody please help me to get rid out of this error - 
call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\SessionGuard' does not have a method 'createJwtDriver'

**Comment by tymondesigns** [comment]
What does your `config/auth.php` look like?
