### ISSUE TITLE
Class 'TymonJWTAuthProvidersJWTAuthServiceProvider' not found  

### ISSUE THREAD

**Issue by rakesh-ideal** [tymondesigns/jwt-auth#598]
Did anyone face this error? Please help me if you resolved it.I am getting this error when running following command - 
php artisan vendor:publish --provider="TymonJWTAuthProvidersJWTAuthServiceProvider"

Class 'TymonJWTAuthProvidersJWTAuthServiceProvider' not found  
 
Thanks!

**Comment by tymondesigns** [comment]
What version of this package are you using?

**Comment by gemox94** [comment]
I'm not sure but maybe is beacause the slashes are missing

**Comment by tymondesigns** [comment]
if that is exactly the command you entered then yes the lack of slashes is your issue
