### ISSUE TITLE
Can't install in L4

### ISSUE THREAD

**Issue by kthnxbye** [tymondesigns/jwt-auth#60]
Hey im getting this error where running composer update

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v4.2.17
    - Conclusion: remove barryvdh/laravel-cors v0.2.3
    - Installation request for tymon/jwt-auth 0.5.* -> satisfiable by tymon/jwt-auth

**Comment by kthnxbye** [comment]
Nvm i just found out the problem i was installing 0.5.* (silly me)

btw bro

YOU ARE THE REAL MVP! it's just lovely

**Comment by tymondesigns** [comment]
:smile:
