### ISSUE TITLE
Throw error instead json response

### ISSUE THREAD

**Issue by nerijunior** [tymondesigns/jwt-auth#601]
I'm working on an API with a default response pattern, but the middlewares doesn't throw exceptions they return json responses:

`Tymon\JWTAuth\Middleware\GetUserFromToken`
```php
public function handle($request, \Closure $next)
    {
        if (! $token = $this->auth->setRequest($request)->getToken()) {
            return $this->respond('tymon.jwt.absent', 'token_not_provided', 400);
        }

        try {
            $user = $this->auth->authenticate($token);
        } catch (TokenExpiredException $e) {
            return $this->respond('tymon.jwt.expired', 'token_expired', $e->getStatusCode(), [$e]);
        } catch (JWTException $e) {
            return $this->respond('tymon.jwt.invalid', 'token_invalid', $e->getStatusCode(), [$e]);
        }

        if (! $user) {
            return $this->respond('tymon.jwt.user_not_found', 'user_not_found', 404);
        }

        $this->events->fire('tymon.jwt.valid', $user);

        return $next($request);
    }
```

If I need to change the default response how can I do it?
The only way is rewriting the middleware?

**Comment by tymondesigns** [comment]
Rewriting the your own middleware is an option.

Or you could catch the symfony http exceptions globally and return responses from there, since the exception contains everything you would need to know to return a decent & informative response

**Comment by zolo2hin** [comment]
> Or you could catch the symfony http exceptions globally and return responses from there,

@tymondesigns  as I can see this is not working correctly.
