### ISSUE TITLE
Best Practice for detect anonymous or authenticated

### ISSUE THREAD

**Issue by deepslux** [tymondesigns/jwt-auth#603]
This is not an issue. But instead, I would like to find out what is the best practice to detect if current connection is whether anonymous or authenticated user.

Let me describe how I did mine first.

I have a `BaseEloquent` class (inherit from `Eloquent`) with a static method called `user()` like below

```
public static function user($defaultVisitor = true) {
    try {
      return \JWTAuth::parseToken()->toUser();
    } catch (\Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {
      if ($defaultVisitor == true) return static::getDefaultUser();
    } catch (\Tymon\JWTAuth\Exceptions\TokenInvalidException $e) {
      if ($defaultVisitor == true) return static::getDefaultUser();
    } catch (\Tymon\JWTAuth\Exceptions\JWTException $e) {
      if ($defaultVisitor == true) return static::getDefaultUser();
    } catch (\Exception $e) {
      if ($defaultVisitor == true) return static::getDefaultUser();
    }
  }
```

So, everywhere in my Eloquent classes (e.g. Department, Company) can immediately calls `static::user()` to get current authenticated user or anonymous user (default visitor).

However, based on my findings, there is a speed difference for authenticated user or anonymous user. The gap of the speed could be as much as 6 seconds for anonymous and 200ms for authenticated user. I believe the issue relies on the expensive try catch. 

Anyone could advise how can I improve on the speed by avoiding try catch?

P.S. `\JWTAuth::getToken()` is also using try catch.

**Comment by tymondesigns** [comment]
what version of laravel and this package are you running?

**Comment by deepslux** [comment]
Appreciate for your fast response.

I am currently using Laravel 5.1.15 and tymon/jwt-auth is 0.5.* (which i believe is 0.5-dev)

**Comment by deepslux** [comment]
What I would like to have is something like below, but just don't know what's the coding for it.
```
public static function user($defaultVisitor = true) {
    if (\JWTAuth::theFunctionForCheckingValidTokenWithoutTryCatchInsideTheFunction()) {
      return \JWTAuth::parseToken()->toUser();
    } else if ($defaultVisitor == true) {
      return static::getDefaultUser();
    }
  }
```

Or anyone could recommend on how you achieve similar like above without try catch?

**Comment by deepslux** [comment]
Anyone helping? Or you guys are also using try catch like how I did?

**Comment by deepslux** [comment]
Hello?

**Comment by tdhsmith** [comment]
The library still uses `try`-`catch` for essential functions (like `getToken`, as you pointed out), so there isn't much way to avoid them altogether. However I have no reason to believe they would cause a slowdown. Are you positive it isn't coming from somewhere else? For example, have you checked that the difference isn't in `static::getDefaultUser()`?

For Laravel 5.1 projects, I usually wrap all my routes in some middleware that attempts `parseToken`. For public routes this will be `Check` and for private routes this will be `Authenticate` plus potentially another middleware that checks other permissions restrictions on my user groups and roles tables (sometimes this latter bit might be handled in the controller instead but I try to be consistent app-by-app). By guaranteeing `parseToken` has run, I can just refer to `Auth::user()` in my controllers and know it will contain the token user, if any.

I don't use any sort of "default user" like you, but I'd probably accomplish that with a middleware too. Run it after the Check/Authenticate ones and just evaluate `is_null(Auth::user())` and if so, set `Auth::setUser(DefaultUserRetrievalFunction())`. Then I could continue using `Auth::user()` in the controller as I mentioned before.

(My Laravel 5.2 approach is a lot different and involves the JWT guard driver and Gates/Abilities... That comes out a lot cleaner frankly, but I don't have much code using it yet.)
