### ISSUE TITLE
JWT and Codeception teardown problem

### ISSUE THREAD

**Issue by aschwin** [tymondesigns/jwt-auth#604]
Hi all,
I have really have no idea where to put this, since it is a combination of several parts working together.

I'm unit testing Laravel 5.2 with Codeception. Laravel 5.2 is used for a REST back-end (yes, I know of Lumen). I use JWT-Auth to generate tokens.

It works quite smoothly, since the API tests in Codeception work fine. Now, in Codeception the teardown is done on all the modules that it uses. Each module has a _after() method to clean up after itself.

Well, in the Laravel 5 module it is doing something like:

```
    /**
     * After hook.
     *
     * @param \Codeception\TestCase $test
     */
    public function _after(\Codeception\TestCase $test)
    {
        if ($this->app['db'] && $this->config['cleanup']) {
            $this->app['db']->rollback();
        }

        if ($this->app['auth']) {
            $this->app['auth']->logout();
        }

        if ($this->app['session']) {
            $this->app['session']->flush();
        }

        if ($this->app['cache']) {
            $this->app['cache']->flush();
        }

        // disconnect from DB to prevent "Too many connections" issue
        if ($this->app['db']) {
            $this->app['db']->disconnect();
        }
    }
```

Notice it does a $this->app['auth']->logout(); This results in a JWTGuard->logout() under the hood.
Here's the part where I think JWT is having trouble. This section depends on a Request with a token. But in my unit test I have no control over the Request that it is doing. I can not provide a token whatsoever it is looking for. Not in the headers, not in the querystring and not in any route parameters.

I am stuck with how to make sure the test suite can properly clean up after using the JWT-Auth. Or, at least, a way to fake the Request in a way it can do its thing on the way out.

Anyone having experience with JWT authentication and Codeception?

**Comment by tymondesigns** [comment]
It looks to me that the package you are using, makes various assumptions that you are using session based authentication. 

I think it needs to be refactored and decouple the Auth inline with laravel 5.2.

I't sure what the exact error you're seeing is, since I haven't added the logout method to the guard since it is [not required by the contract](https://laravel.com/api/5.2/Illuminate/Contracts/Auth/Guard.html)

**Comment by aschwin** [comment]
So, you are saying that in JWTGuard line 115-128:
```
    /**
     * Logout the user, thus invalidating the token.
     *
     * @param  bool  $forceForever
     *
     * @return void
     */
    public function logout($forceForever = false)
    {
        $this->requireToken()->invalidate($forceForever);
        $this->user = null;
        $this->jwt->unsetToken();
    }
```
Is not actually there?

**Comment by tymondesigns** [comment]
sorry brain fart there... my point stands on the codeception package anyways

**Comment by dmoreno** [comment]
Hi,

same problem here. Codeception tests are broken when using it with jwt-auth.

JWTGuard->logout() method needs a valid token. But this is really necessary?

Others guards, like SesionGuard (default guard in Laravel), don't need a valid credential in logout method (like valid cookies).
