### ISSUE TITLE
How use Policies Laravel 5.2 + JWT

### ISSUE THREAD

**Issue by angelmartz** [tymondesigns/jwt-auth#605]
I'm trying use Policies
https://laravel.com/docs/5.2/authorization#policies

But dependency injection , inject current user auth
 
public function update(User $user, Post $post)
    {
        return $user->id === $post->user_id;
    }

**Comment by angelmartz** [comment]
With dev jwt-auth version working fine

**Comment by amsoell** [comment]
@angelmartz Can I ask how you got this to work? I've tried 1.0.0alpha3 and the Dev branch and neither one works for me with Laravels build in Policies
