### ISSUE TITLE
FatalErrorException in ProviderRepository.php line 146: Class 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider' not found

### ISSUE THREAD

**Issue by pankajthakur007** [tymondesigns/jwt-auth#608]
I am following all these step still i am getting error during run the command : 

**php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"**

error : Class 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider' not found
Install via composer - edit your composer.json to require the package.

"require": {
    "tymon/jwt-auth": "0.5.*"
}

Then run composer update in your terminal to pull it in.

Once this has finished, you will need to add the service provider to the providers array in your app.php config as follows:

'Tymon\JWTAuth\Providers\JWTAuthServiceProvider'

Next, also in the app.php config file, under the aliases array, you may want to add the JWTAuth facade.

'JWTAuth' => 'Tymon\JWTAuth\Facades\JWTAuth'

Also included is a Facade for the PayloadFactory. This gives you finer control over the payloads you create if you require it

'JWTFactory' => 'Tymon\JWTAuth\Facades\JWTFactory'

Finally, you will want to publish the config using the following command:

Laravel 5:

$ php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"

**Comment by HawiCaesar** [comment]
Have you solved this? I have the same error

**Comment by pipegris** [comment]
I had the same problem, and strangely when I wrotemanually the ServiceProvider and the Facades, the problem went away, even PHPStorm showed me some weird mispelling red mark on the single quotes. So it's probably because the copy+paste from the docs drags some "exotic" characters.

**Comment by affanhmalik** [comment]
I tried manually typing the lines in app.php - no luck, still the same error as above.

Any other suggestions?

**Comment by mtpultz** [comment]
Hi @affanhmalik, @pipegris, @HawiCaesar, and @pankajthakur007

What version of the jwt-auth are you using? Depending on which version you might need to add a different provider class and artisan command. Try #513 (comment) and see if that solves your issue.

**Comment by robertnicjoo** [comment]
same error here version 1.0.0
