### ISSUE TITLE
Crossdomain broken

### ISSUE THREAD

**Issue by kthnxbye** [tymondesigns/jwt-auth#61]
I got a new issue, when i pass the token via query (?token= ...) it brokes the crossdomain setting and i got the no origin allow and bla bla ..

is there a way to resolve this? am i missing something?

Also can you provide an example about the "Authorization: Bearer {yourtokenhere} header" approach?

ty

**Comment by jossemarGT** [comment]
Hello! 

It sounds pretty weird that passing the query param `token` triggers CORS preflight. But implementing the bearer token is easy as:

- Register jwt auth middlewares in `Kernel.php`
```php
    'jwt.auth' => 'Tymon\JWTAuth\Middleware\GetUserFromToken',
    'jwt.refresh' => 'Tymon\JWTAuth\Middleware\RefreshToken',
```
- Add `jwt.auth` middleware to the privileged controllers or routes.
- Add `Event::listen('tymon.jwt.valid')` hook in the boot function of the `EventServiceProvider.php`, like this.
```php
	public function boot(DispatcherContract $events)
	{
		parent::boot($events);

		Event::listen('tymon.jwt.valid', function($event)
		{
			Auth::setUser($event);
		});
	}
```
- Use `Auth::getUser()` to check user's model instance.

Hope that helps. :octocat: 

PS: This just is for Laravel 5

**Comment by tymondesigns** [comment]
@kthnxbye did you resolve this ?

**Comment by kthnxbye** [comment]
Yes sr i did, i'll post the answer in github just in case someone else is
having the same problem, actually it was a 'conflict' i dont know where
with another library, I was using a third-party lib to handle the cors but
i switched back the app/filter.php $request approach and it's been working
like a charm since then.
