### ISSUE TITLE
Incoming Requests with JWT in Header Occuring within Guest Middleware Route Fail

### ISSUE THREAD

**Issue by mtpultz** [tymondesigns/jwt-auth#610]
If a user is authenticated and sending a JWT up in the header with each request, but the routes being hit are within a guest middleware route group they don't invoke the controller action associated with the end point and instead return `{ token: {} }`.  

During testing of an endpoint I kept getting a 200-level response with `{ token: {} }`.  I spent about an hour making sure the data, route, headers were correct, among other things, and it was only when I moved the route out of the guest route group into a restricted route group that it began working by returning the proper response from the action.  I tested this further by replacing it back in the guest route group and removing the guest middleware, which also returned the proper response from the action.

**Comment by tymondesigns** [comment]
Specifically what is the code in your guest middleware?

Also what versions of laravel/jwt-auth are you using?

**Comment by mtpultz** [comment]
Sorry @tymondesigns, looks like this is an issue on our end due to some changes to the default guest middleware.
