### ISSUE TITLE
Token provide wrong user id

### ISSUE THREAD

**Issue by rakesh-ideal** [tymondesigns/jwt-auth#614]
I am using laravel 5.2 with jwt auth for making API, it was working fine and suddenly

```$user = JWTAuth::parseToken()->authenticate();```
gives me wrong user from database. does anyone help to get out from this issue, is there any problem in my model?

I only added    
``` use SoftDeletes;```
in my model.

but i do not use it with Users model.

**Comment by imilakovic** [comment]
Did you find out what was the issue?

**Comment by mouhsinelonly** [comment]
i m having the same probleme some users receive the wrong id . is theire any fix fir this

**Comment by mistre83** [comment]
From today, i'm having the same problem. Just one user receive a wrong user id. I tried to make login again and again and every time the user_id is wrong.

The "funny" part is that this happen with just one user!

**Comment by aldyson** [comment]
I'm having the same issue where the wrong user is retrieved, and this only happens with one specific account.

Does anybody know a solution to this?

**Comment by darrynten** [comment]
Why was this closed without any other info?

Pretty serious issue.

**Comment by aldyson** [comment]
@darrynten I agree. I still have no solution to this and have no idea why this is occuring.

**Comment by imilakovic** [comment]
My workaround to hopefully eradicate the issue was to set very short token duration (e.g. 4 hours). Therefore by the time a (possibly) duplicate token could have been generated, the previous one was for sure expired.

**Comment by aldyson** [comment]
@imilakovic My token ttl is currently set at 24 hours, but even after the token expires, re-authenticating with the same user results in the problem re-occurring.

It seems that for me at least, the issues with the two accounts are persisting regardless of what happens with the token.

**Comment by marijnhurkens** [comment]
Why is this closed? We're experiencing the same issues and it's a big security hole. I found another ticket with the same symptoms which is also lacking a solution.

https://github.com/tymondesigns/jwt-auth/issues/1487

@tymondesigns
