### ISSUE TITLE
Token Invalid Error

### ISSUE THREAD

**Issue by MohamedQabbani** [tymondesigns/jwt-auth#616]
After i got token value then make get request as ?token=value, i got {"error":"token_invalid"} in the second request.

**Comment by akanevsky** [comment]
Can you post some of the relevant code that handles your token value?

**Comment by MohamedQabbani** [comment]
Route::group(['middleware' => ['jwt.auth', 'jwt.refresh']], function() {
        Route::get('test', function(){
            return response()->json(['foo'=>'bar']);
        });
    });

**Comment by akanevsky** [comment]
There is an issue in the 0.5.* branch when using both jwt.auth and jwt.refresh middleware on the same route. Please refer to https://github.com/tymondesigns/jwt-auth/issues/336#issuecomment-163405382 for more information.

**Comment by MohamedQabbani** [comment]
Thank you
