### ISSUE TITLE
Overriding required claims.

### ISSUE THREAD

**Issue by AdnanNuruddin** [tymondesigns/jwt-auth#617]
I was hoping to override the default 'exp' value for laravel jwt. I am using this way,

```
$credentials = Input::only('email', 'password');
$customClaims = ['exp ' => '1594098305', 'test' => "HAHAHAAA"];
		if (!$token = JWTAuth::attempt($credentials, $customClaims)) {
			return response()->json(['error' => 'Invalid email or password'], HttpResponse::HTTP_UNAUTHORIZED);
		}

		return response()->json(compact('token'));
```
But when i read the payload, exp is set to the default value instead of the custom one I just gave. Is there a way to override this?

**Comment by akanevsky** [comment]
You have an extra space after `exp`. That is likely to be the cause of the issue.

**Comment by AdnanNuruddin** [comment]
What a silly mistake. Thanks for the quick reply.
