### ISSUE TITLE
 How to Invalidate previous tokens after a second authenticate

### ISSUE THREAD

**Issue by YasserHossam** [tymondesigns/jwt-auth#618]
When i authenticate for my second time(sent a request with credentials twice), i've tried to send the old token that i've got from the first authenticate and it worked (That means the second authenticate didn't invalidate the first token), how can i invalidate the first token after the second login

**Comment by ddouble** [comment]
**JWTAuth::invalidate()**,  modify **blacklist_enabled=true**  in config/jwt.php

**Comment by YasserHossam** [comment]
thanks that helped me (Y)

**Comment by prashantidealittechno** [comment]
How you used code, when I run JWTAuth::invalidate() it invalidate the currently generated code.
Thanks
