### ISSUE TITLE
JWTAuthServicePovider forces injection of Laravel AuthManager into AuthAdapter

### ISSUE THREAD

**Issue by hackel** [tymondesigns/jwt-auth#62]
The service provider forces injecting Illuminate\Auth\AuthManager into whatever custom AuthAdapter you may have defined, by passing $app['auth'] as a parameter below.
```php
        $this->app['tymon.jwt.provider.auth'] = $this->app->share(function ($app) {
            return $app->make($this->config('providers.auth'), [ $app['auth'] ]);
        });
```
This is not necessary, as when using $app->make(), it will automatically inject the type-hinted dependencies in the constructor.  I suggest simply removing that parameter entirely.

My workaround simply ignores this variable.
https://gist.github.com/hackel/00a2b5a43d5007eceaa1

**Comment by tymondesigns** [comment]
just noticed this after commenting on #59 

Yea, you are right about `$app->make()` not needing an explicit param.
That being said, I think I will do it like this in the next release: (like [dingo/api](https://github.com/dingo/api/blob/master/src/config/config.php) does it)

```php
// in config.php
'auth' => function ($app) {
    return new Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter($app['auth']);
}
```

and then in the service provider use something like [this method](https://github.com/dingo/api/blob/master/src/Provider/ApiServiceProvider.php#L201-L210):

thoughts?

**Comment by hackel** [comment]
That would definitely work too.  In my mind using type-hinted dependency injection is simpler, but this is probably more flexible.

**Comment by tymondesigns** [comment]
this is done, as of `0.5.1` :)
