### ISSUE TITLE
Memcached: refresh_ttl > 30 days

### ISSUE THREAD

**Issue by boedy** [tymondesigns/jwt-auth#625]
When using Memcached as storage provider: having a refresh_ttl greater then 30 days means it will convert the expiry value to an unix timestamp instead of minutes relative to the current time. This may cause tokens not te be blacklisted. 

``` php
 // Set the cache entry's lifetime to be equal to the amount
 // of refreshable time it has remaining (which is the larger
 // of `exp` and `iat+refresh_ttl`), rounded up a minute
 $cacheLifetime = $exp->max($refreshExp)->addMinute()->diffInMinutes();
 $this->storage->add($payload['jti'], [], $cacheLifetime);
```

Source: http://php.net/manual/en/memcached.expiration.php

**Comment by tymondesigns** [comment]
I will look into it, thanks!

**Comment by tymondesigns** [comment]
I think this simply warrants a warning in the docs
