### ISSUE TITLE
QueryString Parser does not do what it says it does.

### ISSUE THREAD

**Issue by ashleigh-hopkins** [tymondesigns/jwt-auth#631]
The QueryString parser seems to indicate that it will parse a token out of the query string, when in fact it's taking the token out of any provided input. 

`public function parse(Request $request)
{
    return $request->input($this->key);
}`

This is causing conflicts in my development environment when specifying 'token' as an input field by JSON, and also as a query string (I want it to use the token provided by query string, not the one in my JSON object!).

I think that the parser should be modified to reflect what it actually does, and a new InputParser added (with the QueryParser being higher up in the chain than the InputParser).

See pull request #630

Ash

**Comment by tymondesigns** [comment]
merged
