### ISSUE TITLE
JWTSubject is not given via user() method

### ISSUE THREAD

**Issue by sergeikretov** [tymondesigns/jwt-auth#634]
I am trying to use 1.0 alpha.
When I try to authenticate user via credentials, I get:

`ErrorException in JWT.php line 57: Argument 1 passed to Tymon\\JWTAuth\\JWT::fromUser() must be an instance of Tymon\\JWTAuth\\Contracts\\JWTSubject, instance of App\\User given, called in SOMEPATH/vendor/tymon/jwt-auth/src/JWTAuth.php on line 48 and defined.`

And I did not find any helper class to convert a model received via user model to JWTSubject class...
So, Tymon\\JWTAuth\\JWT::fromUser() method gets the full model data, not the JWTSubject object.

Any suggestions, how to make it work with my user model? Are there any specific configuration parameters required to be set in auth.php or jwt.php?

thank you in advance, Sergei

**Comment by tymondesigns** [comment]
Your User class must simply implement the [JWTSubject](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Contracts/JWTSubject.php) interface

**Comment by yesterday679** [comment]
you are so great
thanks for lot
