### ISSUE TITLE
Not work into Laravel 5.2 version, DI not bind resolution error 

### ISSUE THREAD

**Issue by adilsaeed31** [tymondesigns/jwt-auth#637]
Further more JWTAuth::atempt() called statically while this method didn't have the static keyword.

If you fixed this error via adding private property then you have new error which is resolution bind container error.

Please let me know what to do ?

Thanks
Adil

**Comment by mateusjatenee** [comment]
Are you importing the correct class?

**Comment by adilsaeed31** [comment]
Yes You can try yourself in laravel 5.2 this library doesn't work with it.

**Comment by tymondesigns** [comment]
@adilsaeed31 I can guarantee this library works with laravel 5.2. You evidently have something misconfigured something.

But before anyone can help you, you need to provide more information. What does your routes/controller look like etc..

**Comment by mateusjatenee** [comment]
I just created a fresh install of 5.2.27 and everything works fine. Have you registered the aliases and service provider? Are you importing the correct class? 

Please share your code with us. ping @tymondesigns

**Comment by adilsaeed31** [comment]
@tymondesigns and @mateusjatenee  Hi Guys, 

Below are the steps.

1) I have added the tymon/jwt-auth package into laravel after doing composer require tymon/jwt-auth
2) Then I added the Provider and aliases to config/app.php file.

provider = 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider'

Aliases = 'JWTAuth' => 'Tymon\JWTAuth\Facades\JWTAuth' , 'JWTFactory' => 'Tymon\JWTAuth\Facades\JWTFactory'

after this.
3) I tried below command 
php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"

but nothing happened. so i need to copy the config file manually into config folder with jwt name.

4) Then i tried to generate the jwt token which is also not working, so i manually added the console command to kernal and generate the jwt token through artisan and changed into config/jwt.php file.

5) Then I added the middleware into kernal into routeMiddleware protected property.

'jwt.auth' => 'Tymon\JWTAuth\Middleware\GetUserFromToken',
'jwt.refresh' => 'Tymon\JWTAuth\Middleware\RefreshToken',

6) I have added the htaccess code in public/.htaccess file

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

7) After all these steps I added route into my route.php file which is below mentiond

Route::get('authenticate', 'Auth\AuthController@authenticate');

8) In AuthController in authenticate method i have copy paste the authenticate method code which attemp the JWTAuth::atempt($credentials) to validate the users and generate the token. which doesn't work.
This is the method code 

  JWTAuth::attempt was not working due to static keyword problem so i added my patch here.

    use Tymon\JWTAuth\JWTAuth;
    use Tymon\JWTAuth\Exceptions\JWTException;

    private $user;
    private $jwtauth;
  
public function __construct(User $user, JWTAuth $jwtauth)
    {
        $this->user = $user;
        $this->jwtauth = $jwtauth;

        $this->middleware('guest', ['except' => 'logout']);
    }

    public function authenticate(Request $request)
    {
        // grab credentials from the request
        $credentials = $request->only('email', 'password');
        $token = null;
        try {

            // attempt to verify the credentials and create a token for the user
            if (! $token = $this->jwtauth->attempt($credentials)) {
                return response()->json(['error' => 'invalid_credentials'], 401);
            }
        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return response()->json(['error' => 'could_not_create_token'], 500);
        }

        // all good so return the token
        return response()->json(compact('token'));
    }

This is all i have done.

Thanks
Adil

**Comment by mtpultz** [comment]
@adilsaeed31, you're using JWTAuth, which definitely works for Laravel 5.2 as @tymondesigns mentions, but with Laravel 5.2 you can take advantage of Guards and use this packages JWTGuard.  There is a guide posted on how to set it up at: https://github.com/tymondesigns/jwt-auth/issues/513.

Hope this helps.
