### ISSUE TITLE
Get user

### ISSUE THREAD

**Issue by marijang** [tymondesigns/jwt-auth#64]
Can you give me advice.
How to avoid code like "$user = JWTAuth::parseToken()->toUser()"
Is it posible to get something  like JWTAuth::getUser()? 

Because JWTAuth::parseToken()->toUser() will parse token twice. FIrst in middleware then into controller.

**Comment by gerob** [comment]
If you've already parsed your token in the middleware then there is no reason to do it again as token has been parsed and has passed the User into `Event::listen('tymon.jwt.valid');`.

Just set the auth'd user off of this event.

**Comment by tymondesigns** [comment]
@gerob is correct, you could set the authenticated user on that event as seen here -> https://github.com/tymondesigns/jwt-auth/issues/61#issuecomment-79538721.

Alternatively I may consider caching the auth user object on the instance instead, but i'll have a think about that.

Thanks

**Comment by marijang** [comment]
Thanks. That is it:D
