### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by kbchandiran** [tymondesigns/jwt-auth#640]
perform the token refresh the token using the function 
`$token    = JWTAuth::getToken();
 $newToken = JWTAuth::refresh($token);` 
option with 
`'blacklist_enabled' => true`
 i got this error
`<span class="exception_title"><abbr title="Tymon\JWTAuth\Exceptions\TokenBlacklistedException">TokenBlacklistedException</abbr> in <a title="/vendor/tymon/jwt-auth/src/JWTManager.php line 84" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">JWTManager.php line 84</a>                             <span class="exception_message">The token has been blacklisted</span>`
if  `'blacklist_enabled' => false` means it's working fine but old token not disabled.
Anything i did wrong?

**Comment by brazenvoid** [comment]
me too!

**Comment by ddouble** [comment]
you must use the latest token to refresh, once you get new token, the old token will  be blacklisted immediately.  Next time, you must use the new token to get next new token ...  and so forth

**Comment by kbchandiran** [comment]
@ddouble i have used the new token only but before i got the refreshed token the old token get blacklisted so only i could not generate the refreshed token
@brazenvoid i have tried `\JWTAuth::parseToken()->refresh()`
but i got this error
`<span class="exception_title"><abbr title="Tymon\JWTAuth\Exceptions\JWTException">JWTException</abbr> in <a title="/vendor/tymon/jwt-auth/src/JWTAuth.php line 204" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">JWTAuth.php line 204</a>:</span>
03-31 12:24:20.750 15224-15224/com.connected.merchant D/sb.append: sb.append  ||                             <span class="exception_message">The token could not be parsed from the request</span>`
i need to add the middleware like
`'middleware' => ['jwt.refresh', 'jwt.auth']`
or anything else i need to do?

**Comment by vladislavHadzhiyski** [comment]
The jwt.auth middleware is setting the new token in the Authorization header in the response.

Authorization →Bearer **token**

Hope this helps you.

**Comment by logusgraphics** [comment]
The middleware or refresh() method only work if the JWT_BLACKLIST_ENABLED is set to FALSE which won't make sense because the only scenario in which you will need to refresh the token is if the old ones are blacklisted.

**Comment by leepin** [comment]
@kbchandiran Hey, how did you solve the problem? Can you please share?

**Comment by bachmay** [comment]
was this solved somehow? I have the same problem:

`Tymon\JWTAuth\Exceptions\TokenBlacklistedException: The token has been blacklisted in /home/forge/pelv2.stage/vendor/tymon/jwt-auth/src/JWTManager.php:84`

**Comment by bachmay** [comment]
@kbchandiran how did you solve it?

**Comment by leongpeng** [comment]
@bachmay See here [#831](https://github.com/tymondesigns/jwt-auth/issues/831)
