### ISSUE TITLE
Add custom field as payload

### ISSUE THREAD

**Issue by shanavas786** [tymondesigns/jwt-auth#641]
Is there a way to add custom payload from table fields ?
Now payload has only `id` field in `sub` key. Is is possible to add other fields ?

**Comment by tymondesigns** [comment]
yes see https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens#creating-a-token-based-on-anything-you-like

**Comment by shanavas786** [comment]
Thank you, I have went through it already. I meant adding a payload dynamically from the authentication table in the same way `sub` key is added.
