### ISSUE TITLE
How to authenticate from __construct instead of route?

### ISSUE THREAD

**Issue by jonaholsson** [tymondesigns/jwt-auth#644]
I have a fully working authentication using middleware in the routes, but I would also like to be able to control authentication within `__construct` of a controller.

I have tried to call the JWTAuth middleware that is being extended to Dingo Auth in this case during bootstrap, but nothing happens. I've also tried to register the JWTAuth middleware outside Dingo, but that isn't being picked up in `__construct` either.

Any ideas on where to look? I'm using 1.0.*@dev.

**Comment by jonaholsson** [comment]
I just noticed that users are actually authenticated when providing a correct bearer, but unauthorized users are being let through anyway (when using the middleware in `__construct`). Shouldn't this be restricted by the JWTAuth middleware automatically? Am I missing something vital here, such as verifying authenticated user in `__construct`?

**Comment by rennanfelipe** [comment]
Use "middleware" method in your "__construct".

 Apply the jwt.auth middleware to all methods in your controller
 except for the authenticate method. We don't want to prevent
 user from retrieving their token if they don't already have it
<?php
...
use JWTAuth;
...
public function __construct(){
           $this->middleware('jwt.auth', ['except' => ['authenticate', 'viewRegistrar', 'register']]);
}

**Comment by jonaholsson** [comment]
Thanks, but that's what I'm doing. I have tried both the build-in provider in Dingo ("api.auth" in my case) as well as the JWTAuth provider ("jwt.auth"). Both works just fine when used in routes.php, but doesn't do anything to restrict unauthorized users when used in `__construct`.

My bootstrap:
```
$app->routeMiddleware([
    'jwt.auth' => \Tymon\JWTAuth\Middleware\Authenticate::class,
]);
...
$app->register(Tymon\JWTAuth\Providers\LumenServiceProvider::class);
$app->register(Dingo\Api\Provider\LumenServiceProvider::class);
...
app('Dingo\Api\Auth\Auth')->extend('jwt', function ($app) {
    return new Dingo\Api\Auth\Provider\JWT($app['\Tymon\JWTAuth\JWTAuth']);
});
...

```

My controller:
```
class ProductsController extends ApiController {
    public function __construct() {
        $this->middleware('jwt.auth'); // the same result as with 'api.auth' - users are let through, authorized as unauthorized
    }
...
```

This works just fine if used in routes.php:
`$api->version('v1', ['namespace' => 'App\V1\Controllers', 'middleware' => 'api.auth'], function ($api) {...}`
and
`$api->version('v1', ['namespace' => 'App\V1\Controllers', 'middleware' => 'jwt.auth'], function ($api) {...}`
