### ISSUE TITLE
JWT Token That Never Expires For A Specific Route Group

### ISSUE THREAD

**Issue by djoks** [tymondesigns/jwt-auth#647]
I have a laravel web application. Several 3rd parties connect to the APIs on my server, the website uses those same APIs and so does my mobile app. Now for the website I am fine with the token expiring after a certain time preferably 1 hour. However for my mobile app I do not want the token to expire at all.

I know with this I can do this in the config file or my .env file but this applies to the entire app, how do I set specific token expiration lengths for each route group I have?

**Comment by iamrutvik** [comment]
I dont want to expire token for entire app? How would you do that in config?

**Comment by tdhsmith** [comment]
> The problem is i am using 0.5.*.

Then you can't use true infinite tokens. 

That said, you can still set the `ttl` expiration length to something absurdly high, like 10 years. (Do you think your app will be running the exact same configuration beyond 10 years? Probably not.)

Be aware that if you use token refreshing or token invalidation, you'll have to keep your cache intact for that whole time as well...

**Comment by ortho23** [comment]
In a new version remember to disable blacklisting alongside with high ttl and refresh_ttl values. Just set env variable: JWT_BLACKLIST_ENABLED=false
