### ISSUE TITLE
Authenticating using L5 Auth

### ISSUE THREAD

**Issue by lucadegasperi** [tymondesigns/jwt-auth#65]
Hello Tymon!

I'm reading trough the docs and was wondering why there's no mention of the authenticate method.

I would like to use the L5 Auth Guard together with this package.

**Comment by tymondesigns** [comment]
Hi Luca,

That's a good question :smile:

I need to do some more work on the docs if i'm honest - gonna try to carve some time out to do that soon.

You're refering to L5's built in Auth right?

**Comment by lucadegasperi** [comment]
Yes I am!
