### ISSUE TITLE
How do I fetch and destroy all the current tokens?

### ISSUE THREAD

**Issue by jonathanlundstrom** [tymondesigns/jwt-auth#653]
Hi!

I'm building an application and need to perform some security tests.
How would I go about fetching all the active tokens and destroying them?

I want to see what happens to all the users as the tokens are validated. They should be logged out, but I currently have no way of testing this.

Also, where are the tokens stored? I can't find them anywhere...

Regards,
Jonathan

**Comment by tymondesigns** [comment]
JWT's are stateless, so they are not stored anywhere. Unless they are blacklisted, in which case they will be stored via laravel's cache system until they expire naturally
