### ISSUE TITLE
Error: Class 'Tymon\JWTAuth\Test\Stubs\JWTProviderStub' not found

### ISSUE THREAD

**Issue by SibLiant** [tymondesigns/jwt-auth#659]
running on 5.9

me@me-virt-ultra-15-10:/var/www/myapp$ phpunit vendor/tymon/jwt-auth/tests/
PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

...........................................................E..... 65 / 79 ( 82%)
..............

Time: 481 ms, Memory: 16.00Mb

There was 1 error:

1) Tymon\JWTAuth\Test\Providers\JWT\JWTProviderTest::it_should_set_the_algo
Error: Class 'Tymon\JWTAuth\Test\Stubs\JWTProviderStub' not found

/var/www/myapp/vendor/tymon/jwt-auth/tests/Providers/JWT/JWTProviderTest.php:21
/home/me/.config/composer/vendor/phpunit/phpunit/src/TextUI/Command.php:149
/home/me/.config/composer/vendor/phpunit/phpunit/src/TextUI/Command.php:100

FAILURES!
Tests: 79, Assertions: 93, Errors: 1.

**Comment by akanevsky** [comment]
From the current version of `composer.json` for this package:
https://github.com/tymondesigns/jwt-auth/blob/0ea9a9faaf97678373b19b7be9befcf10fbade2b/composer.json#L43

```
"autoload-dev": {
     "psr-4": {
         "Tymon\\JWTAuth\\Test\\": "tests"
     }
 },
```

From `composer` documentation (https://getcomposer.org/doc/04-schema.md#autoload-dev):

> autoload-dev (root-only)
> 
> This section allows to define autoload rules for development purposes.
> 
> Classes needed to run the test suite should not be included in the main autoload rules to avoid polluting the autoloader in production and when other people use your package as a dependency.
> 
> Therefore, it is a good idea to rely on a dedicated path for your unit tests and to add it within the autoload-dev section.

This means that the autoloader of your root application does not have the path for files in the `Tymon\JWTAuth\Test` namespace, and that is why you are seeing the error message. Therefore, you can't test the package like that. To test the package, you can `cd` to `vendor/tymon/jwt-auth`, run `composer install`, rename `phpunit.xml.dist` to `phpunit.xml`, and test using the local version of PHPUnit that gets installed there. I just ran the tests using this method. All tests have passed.
