### ISSUE TITLE
Iphone refresh token

### ISSUE THREAD

**Issue by marijang** [tymondesigns/jwt-auth#66]
I need advice. We are building ios app so i have question about refreshing tokens. 
we use 3 minute token exp. What is the best way to buid refresh token functionality

Does Client need to go for new token each 3 minute if i set token exp 3 min.
Or just use refrestoken middleware and send each request with new token?
Or create listener on ios side and in 2:40 min and sec go for new token with stored username and pass into client app?

Thanks.

**Comment by tymondesigns** [comment]
Ok, I will try and explain the refresh flow as I envisioned it:

Given these settings:
- `ttl => 3`
- `refresh_ttl => 60`

If a token is issued at `09:00` then it will expire at `09:03` as expected. 

The `refresh_ttl` indicates that this token can only be refreshed for 60 minutes (in this case) after it's initial creation. So it is impossible to refresh the token after `10:00` and a brand new token must then be created.

When refreshing a token, the original `iat` (Issued At) timestamp is carried over from token to token, so it can be checked against the `refresh_ttl` during each authenticated request.

That is how it should work. Having said that, there is an issue that i'm currently fixing, as described in #63.

I hope that helps you understand the flow better

**Comment by Rep2** [comment]
Does that mean that token is being refreshed automatically on any user request without app sending credentials again? If so isn't the whole point of token expiring to limit what stolen token can do.

My way of doing it was that, if the token is about to expire, server appends warning to user request. For example http status code 282. Then user app automatically sends credentials requiring new token and transition is seamless. 

If token expired because no request was sent then server sends toke expired error and user app needs to send credentials which adds some downtime.

**Comment by pfazzino** [comment]
In the iOS app it should be pretty straightforward, when you next need to make a server request if the token has expired use the refresh token to get a new token first. You don't need a listener or some automatic process and I don't see why the server needs to send http status codes to warn the user. This is completely transparent to the user. 

The only time the user needs to get involved in when the refresh token expires. You definately don't (and never should need to) store the username/password in the app, that's what the refresh token is effectively saving you from. Set it to something like 2 weeks and then the user only needs to enter credentials if they haven't used your app for that time period unless you feel the need for some background process which handles the refresh for you.

**Comment by marijang** [comment]
JWT does not have refresh token

On 14 May 2015 at 09:50, pfazzino <notifications@github.com> wrote:

> In the iOS app it should be pretty straightforward, when you next need to
> make a server request if the token has expired use the refresh token to get
> a new token first. You don't need a listener or some automatic process and
> I don't see why the server needs to send http status codes to warn the
> user. This is completely transparent to the user.
>
> The only time the user needs to get involved in when the refresh token
> expires. You definately don't (and never should need to) store the
> username/password in the app, that's what the refresh token is effectively
> saving you from. Set it to something like 2 weeks and then the user only
> needs to enter credentials if they haven't used your app for that time
> period unless you feel the need for some background process which handles
> the refresh for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tymondesigns/jwt-auth/issues/66#issuecomment-101958319>
> .
>



-- 
Marijan Greguric

**Comment by pfazzino** [comment]
Your choice is to generate a token for refresh purposes which you present at a separate refresh endpoint of use the refresh_ttl built into jwt-auth. None of these are any concern of JWT.
