### ISSUE TITLE
Specify token black list timeout time

### ISSUE THREAD

**Issue by mehrdaad** [tymondesigns/jwt-auth#661]
Is there a way to specify a timeout before a token gets into black list.  
I mean token gets black listed. but within an interval of timeout, the token is still valid.  
I use the dev branch.  
Tnx

**Comment by tymondesigns** [comment]
Sorry no plans to add this behaviour

**Comment by mehrdad-shokri** [comment]
@tymondesigns but if I'm not misunderstood, this functionality is implemented already!

**Comment by tymondesigns** [comment]
maybe I misunderstood your question then.. I read it as: a delay in when the token _enters_ the blacklist.

If you were referring to the grace period thing, then yea we're all good!

**Comment by mehrdad-shokri** [comment]
@nope, I meant grace period. tnx
