### ISSUE TITLE
calling Auth::refresh() with blacklist enabled using redis causes WRONGTYPE operation

### ISSUE THREAD

**Issue by ctadlock** [tymondesigns/jwt-auth#666]
In `dev-develop`, if `Auth:refresh()` is called with the blacklist feature enabled it causes this exception to be thrown when using Redis for cache.

`WRONGTYPE Operation against a key holding the wrong kind of value`

![image](https://cloud.githubusercontent.com/assets/1539397/14509030/2cbdfa4e-017f-11e6-9a15-b59e6e3c6b12.png)

![image](https://cloud.githubusercontent.com/assets/1539397/14509058/4ca96a0a-017f-11e6-9587-063709674737.png)

![image](https://cloud.githubusercontent.com/assets/1539397/14509063/57721bc6-017f-11e6-84d2-0c951d28c4e1.png)

**Comment by ctadlock** [comment]
After further analysis we found that this is caused by a corrupted value in the cache. We dont know what the bad value was or how it got there. We had several developers see this issue, and when we flushed our development caches it went away. Maybe this will trigger something to who wrote this related code...

**Comment by crynobone** [comment]
> WRONGTYPE Operation against a key holding the wrong kind of value

Are you using laravel/framework between version 5.2.24 to 5.2.27?

**Comment by MitchellMcKenna** [comment]
Hitting this issue as well. laravel/lumen-framework v5.2.6
