### ISSUE TITLE
Problem 1     - Installation request for tymon/jwt-auth ^0.5.9 -> satisfiable by tymon/jwt-auth[0.5.9]

### ISSUE THREAD

**Issue by jnuc093** [tymondesigns/jwt-auth#667]
### with this tutrial [json-web-token-authentication-for-lumen](https://laravelista.com/json-web-token-authentication-for-lumen/)  the code is [here treeline-lumen](https://github.com/laravelista/treeline-lumen)

> vagrant@homestead:~/Code/treeline-lumen$ composer require tymon/jwt-auth
> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> Using version ^0.5.9 for tymon/jwt-auth
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for tymon/jwt-auth ^0.5.9 -> satisfiable by tymon/jwt-auth[0.5.9].
> - Conclusion: don't install namshi/jose 2.2.2
> - tymon/jwt-auth 0.5.9 requires namshi/jose 5.0.\* -> satisfiable by namshi/jose[5.0.0, 5.0.1, 5.0.2].
> - Can only install one of: namshi/jose[5.0.0, 2.2.2].
> - Can only install one of: namshi/jose[5.0.1, 2.2.2].
> - Can only install one of: namshi/jose[5.0.2, 2.2.2].
> - Installation request for namshi/jose == 2.2.2.0 -> satisfiable by namshi/jose[2.2.2].
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by JPeer264** [comment]
Please have a look at my answer at #660 
This may solve your problem.
