### ISSUE TITLE
GetUserFromToken middleware to return 401 status code not 400 on token not provided

### ISSUE THREAD

**Issue by mmichaelbiz** [tymondesigns/jwt-auth#67]
GetUserFromToken middleware could return 401 status code not 400 on token not provided:

```php
if (! $token = $this->auth->setRequest($request)->getToken()) {
    return $this->respond('tymon.jwt.absent', 'token_not_provided', 401);
}
```
Technically it could be considered a 400 bad request for jwt_auth seeing as there is data missing / not as expected, but seeing as the intention is usually to check if the user is authenticated / authorised or not then 401 could be more appropriate?

Trivial I know, but having it implemented this way would help with intercepting the response and redirecting users, without having to check the message also, example from angular:

```javascript
if (response.status === 401) {
    $location.path('/login');
}
```

**Comment by nathanmarks** [comment]
@mmichaelbiz You can also intercept this with a controller abstraction of your own. I use one in conjunction with `League/Fractal` to handle my API responses.

**Comment by tymondesigns** [comment]
ok I see what you mean.. I will have a think about it.. 

Alternatively, I guess you could do it this way:

```js
var disallowed = [400, 401]; // etc

if (disallowed.indexOf(response.status) != -1) {
    $location.path('/login');
}
```

**Comment by mmichaelbiz** [comment]
Thanks Sean, no biggy it is purely a preference thing and is easily fixed.. 

As I see it most front end apps would have some sort of global http interceptor in place that would be based on the status code (and / or error code if the API returns one) to be able to handle responses. 

Note that an API could return 400 for an "actual" bad request which is not related to an authorisation issue and we would normally want to handle those separately.

Perhaps you could add the status codes / messages to the config at some point?

**Comment by tymondesigns** [comment]
Yea I was thinking of adding the middleware/filter messages to the laravel language system.
I'll see what I can do, regarding configuring the status codes

**Comment by Mr-Anonymous** [comment]
I agree with OP. I do think `token_not_provided` has to be a 401 unauthorised error. Reason for me being the `http-auth-interceptor` from the angular frontend which picks on 401 can show the modal so users are allowed to login and get a new token again. So 401 for that does make more sense.

**Comment by valera33** [comment]
+1

**Comment by gabrielalack** [comment]
bump!

**Comment by irumil** [comment]
+1
