### ISSUE TITLE
catch exception to json

### ISSUE THREAD

**Issue by unabomber87** [tymondesigns/jwt-auth#670]
Hi everybody,
I have installed a fresh laravel installation V5.2, and implemented jwt. Everything works fine for testing credential of user and returning a valid token.
My problem is when i try to check the token following the documentation

`try {
			if (!$user = JWTAuth::parseToken()->authenticate()) {
				return response()->json('user_not_found');
			}

		} catch (Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {
			return response()->json('token_expired');

		} catch (Tymon\JWTAuth\Exceptions\TokenInvalidException $e) {
			return response()->json('token_invalid');

		} catch (Tymon\JWTAuth\Exceptions\JWTException $e) {
			return response()->json('token_absent');
		}

		// the token is valid and we have found the user via the sub claim
		return response()->json(compact('user'));`

All the response are exception and no one of this response are a json. Even when putting the exception on the Handler the responses aren't on a json format.
Can someone help me please.

**Comment by unabomber87** [comment]
i fanally found the solution i'm missing a root slash when calling the exception so the catch became

`catch (\Tymon\JWTAuth\Exceptions\TokenExpiredException $e)`

**Comment by tucq88** [comment]
Wow it helps me. Thanks @unabomber87

**Comment by vandemberg** [comment]
Thanks! @unabomber87

**Comment by MrTeapot** [comment]
Thank you for posting your solution, it really helped me!

**Comment by imadHafsi** [comment]
thank you @unabomber87, it's really  helped me

**Comment by bayubimantarar** [comment]
Can i see your route? are you using BaseMiddleware? @unabomber87

**Comment by omarnas** [comment]
I'm facing the same issue I'm not sure why it's not catching the Exception 
using laravel 5.6

**Comment by rpalexis** [comment]
I'm using Laravel 5.6 too.
And this : `"catch (\Tymon\JWTAuth\Exceptions\TokenExpiredException $e)"` is not working for me
