### ISSUE TITLE
Problem with multiple guards for authentication

### ISSUE THREAD

**Issue by vfsoraki** [tymondesigns/jwt-auth#677]
There is a problem when I have multiple guards defined for authentication.
Consider I have two guards, one for normal web authentication (`User` model) and one for api authentication (`ApiToken` model).
The default guard is set to `web`.
My login route works fine, and gives back token. Though I have to fetch `ApiToken` model myself (I will tell why). Now, I set up a middleware for token-based authentication with jwt called `jwt.auth` (`Tymon\JWTAuth\Middleware\GetUserFromToken`).
Any route using `jwt.auth` middleware, throws error `user_not_found`.
The problem is, default guard is set to `web` and jwt tries to resolve identifier against `User` model, whereas it should resolve it against `ApiToken` model.
This means, package should have a config somewhere to set the default guard to use. By setting default guard for jwt package to `api` (`ApiToken` model), problem is solved. And also, there is no need to do authentication manually.
I hope I explained the problem clearly. I will try to fix the problem in coming days.
Is there anything I have missed? I am almost sure I have read all the docs.

**Comment by thelastblack** [comment]
I have searched and read the source a bit. I think the problem also relates to #563.
By using `token` driver in `auth.php`, I get this error :
`call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\TokenGuard' does not have a method 'onceUsingId'`

**Comment by tonystatic** [comment]
Same issue

**Comment by gavinliu6** [comment]
Do you have resolved the problem? @vfsoraki

**Comment by vfsoraki** [comment]
I do not recall, sorry @gavinliu6 .

I think I solved it by doing things manually, or using something else, but I really don't know how I did it. This issue is considered old now :wink:

**Comment by jellybobbin** [comment]
Because of this problem, I gave up.
