### ISSUE TITLE
"jwt.refresh" middleware functionality bug/feature

### ISSUE THREAD

**Issue by Sakpal** [tymondesigns/jwt-auth#678]
When "jwt.refresh" is used as middleware for routes, the middleware refreshes the token even if it is a valid one and TTL is within expiry limit (TTL is set to 10 mins).

Is this a feature or a bug, because dont you think the TOKEN should only be refreshed if the token is expired else not. 
It makes no sense to keep refreshing the token on every request that we make. Just trying to implement the generic way you created for refreshing the token instead of creating a specific route for it.

I may be completely wrong with the assumptions.

**Comment by cj-schultz** [comment]
It is a feature. The refresh middleware is to ensure that, if the token is compromised, it can't be used by malicious users. In other words, it's to ensure that even if a token get compromised, it does not matter because it will be refreshed.

**Comment by Sakpal** [comment]
Okay. Thanks.

Is there a way where we can modify this so that the middleware will only refresh the TOKEN if it is expired else not?

**Comment by jonagoldman** [comment]
jwt is a security standard and you should follow it. the token is automatically refreshed and that's a good thing. you can still authenticate the user so it doesn't really matters.
