### ISSUE TITLE
Using JWT in the browser and passing the Bearer header with every request

### ISSUE THREAD

**Issue by stueynet** [tymondesigns/jwt-auth#683]
Trying to figure out how we can use JWT in our normal browser routes as well as our API routes. With the API its easy as you can just construct the request. However with the browser we are having trouble getting the header to be available to the methods. Tried using middleware but it doesn't getting added and JWT fails when trying to parse the token. Any thoughts on using this for normal browse routes?

**Comment by thelastblack** [comment]
You can try saving token in a cookie. Then write a middleware to read that cookie before `jwt.auth` middleware, and set the `Authorization` header there.
