### ISSUE TITLE
What happened with version 0.6.*@dev

### ISSUE THREAD

**Issue by JPeer264** [tymondesigns/jwt-auth#685]
When I want to install this version I got an error that this package does not exist.

composer.json version:

```json
"tymon/jwt-auth": "0.6.*@dev"
```

bash error:

```{r, engine='bash', count_lines}
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tymon/jwt-auth could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
```

Also on [packagist](https://packagist.org/packages/tymon/jwt-auth) the `0.6.*@dev` is gone. Is it now required to update to version `1.0.*@dev` ?

**Comment by tymondesigns** [comment]
>  Also on packagist the 0.6.*@dev is gone. Is it now required to update to version 1.0.*@dev ?

Yes 0.6 will now be `1.0.*@dev`
