### ISSUE TITLE
The use statement with non-compound name 'JWTAuth' has no effect

### ISSUE THREAD

**Issue by frohlich** [tymondesigns/jwt-auth#69]
Hi, when i try publish JWT files with:
 - php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
Return:
- [ErrorException]
  The use statement with non-compound name 'JWTAuth' has no effect

Configs[config/app.php]
Providers:
  - 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider'

Alias:

  - 'JWTAuth' => 'Tymon\JWTAuth\Facades\JWTAuth'

Compose.json:

  - "tymon/jwt-auth": "0.5.*"

Has anyone had the same problem or know how to solve?

Thanks

**Comment by frohlich** [comment]
Forget it, i reinstalled from the scratch and it works beautifully.

**Comment by chbro** [comment]
but i reinstalled it in vain.
then i replaced  "use JWTAuth" with "use Tymon\JWTAuth\Facades\JWTAuth", only to get 
```php
Class '\App\User' not found

(1/1) FatalErrorExceptionClass '\App\User' not found
--
in EloquentUserProvider.php (line 140)


```
my test code is as follow:
```php
    $credentials = ['foo' => 'foo', 'bar' => 'bar'];
    return JWTAuth::attempt($credentials);
```
and this is the only changed config line in jwt.php:
```php
    'user' => 'App\Admins',
```

**Comment by chbro** [comment]
it turned out to be my config/auth.php.
```php
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
```
......
