### ISSUE TITLE
check if a jwt token is expired or invalid 

### ISSUE THREAD

**Issue by salarAsadi** [tymondesigns/jwt-auth#690]
I want to check manually if a provided token is expired or invalid. which functions should I use?

**Comment by jonagoldman** [comment]
https://github.com/tymondesigns/jwt-auth/wiki/Authentication

**Comment by salarAsadi** [comment]
No I should not use authenticate(), because I'm not using "\App\User" model.

**Comment by jonagoldman** [comment]
Maybe ```JWT::checkOrFail()``` or ```JWT::check()``` ?

https://github.com/tymondesigns/jwt-auth/blob/7e4b73e4324b02622306a2af2df1bf76af77b9be/src/JWT.php#L100
