### ISSUE TITLE
Call to undefined method Tymon\JWTAuth\Exceptions\TokenExpiredException::getStatusCode()

### ISSUE THREAD

**Issue by andrewhl** [tymondesigns/jwt-auth#692]
If you use the Global Exception Handling error code [here](https://github.com/tymondesigns/jwt-auth/wiki/Authentication#global-exception-handling), and you actually get the error, you get the following result:

```php
Call to undefined method Tymon\JWTAuth\Exceptions\TokenExpiredException::getStatusCode()
```

Because ```class TokenExpiredException extends JWTException```, which extends Exception, which does not actually define getStatusCode().

**Comment by stueynet** [comment]
+1

**Comment by rapidtechsolutions** [comment]
+1

**Comment by tymondesigns** [comment]
The documentation in the wiki, is not for the `1.*` version... There is no plan to add http specific methods to the exceptions again
