### ISSUE TITLE
User Authentication in Lumen 5.2 - is it supported?

### ISSUE THREAD

**Issue by cj-schultz** [tymondesigns/jwt-auth#693]
When attempting to authenticate a user with JWTAuth, it calls the byCrendentials function in Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter.

I get an error saying call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\RequestGuard' does not have a method 'once'.

I was wondering if this is a problem with jwt-auth support for lumen 5.2? Thanks.

**Comment by feeekkk** [comment]
I've also been having this issue, similar to #669. Not sure how to proceed with integrating this package with Lumen

**Comment by cj-schultz** [comment]
So I got past this error by commenting out the AuthServiceProvider in app.php.

Now I just get "Auth guard driver [api] is not defined" error.

**Comment by jonasvanderhaegen** [comment]
@feeekkk https://github.com/khlipeng/lumen-api-jwt i used this as example, it works ;)
