### ISSUE TITLE
PHPUnit Test Get Token Login

### ISSUE THREAD

**Issue by nagoz** [tymondesigns/jwt-auth#694]
Hello,
I have the following code.
I want to test the token recovering through post request.

The problem is that $response is always '{"error":"invalid_credentials"}' with PHPUnit.
When I get the token with my front application ou with PostMan, the token is ok.

Can you help me ?

```
public function testGetTokenLogin()
    {
      $data = [ 'content' => '{"email":"test@test.fr","password":"test"}'];
      $data_array =  ['email' => 'test@test.fr', 'password' => 'test'];
      $headers = ['Content-Type' =>  'application/json'];

      //$this->post('/api/authenticate', $data)->seeJson(['test' => 'true']);
      $response = $this->call('POST', '/api/authenticate', [], [], [], $headers, $data_array);

      ... my assert test...
    }
````

**Comment by feeekkk** [comment]
I feel like this is probably a bug on your implementation, I am able to login during my PHPUnit tests.

I'm using Lumen 5.2 and jwt-auth: ^1.0@dev

    $this->post('auth/login', [
		'email' => $this->vendor->email,
		'password' => $this->vendorRawPassword
	]);

	$this->seeJsonStructure([
		'token'
	]);

I'm resolving my user via the following endpoint

    /**
	 * @param Request $request
	 * @return mixed
	 */
	function login(Request $request)
	{
		$this->validate($request, [
			'email'    => 'required|email|max:255',
			'password' => 'required',
		]);

		try {
			$credentials = $request->only('email', 'password');

			if (! $token = $this->jwt->attempt($credentials)) {
				return response()->json(['user_not_found'], 404);
			}
		} catch (TokenExpiredException $e) {
			return response()->json(['token_expired'], 500);
		} catch (TokenInvalidException $e) {
			return response()->json(['token_invalid'], 500);
		} catch (JWTException $e) {
			return response()->json(['token_absent' => $e->getMessage()], 500);
		}
		
		return response()->json(compact('token'));
	}

**Comment by nagoz** [comment]
thanks I'll test this soon

**Comment by nagoz** [comment]
hello,
`$this->jwt->attempt($credentials)` is not working. What are include ?



This is my code
TokenAuthController
```
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;

use App\Http\Requests;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Hash;

class TokenAuthController extends Controller
{


  public function authenticate(Request $request)
  {
    $credentials = $request->only('email', 'password');
    var_dump($this->jwt);
    //var_dump( JWTAuth::attempt(['email'=>'test@test.fr', 'password'=>'test']);
    var_dump($this->JWT->attempt($credentials));
    try {
      if (! $token = JWTAuth::attempt($credentials)) {
        var_dump($token);
        return response()->json(['error' => 'invalid_credentials'], 401);
      }
    } catch (JWTException $e) {
      return response()->json(['error' => 'could_not_create_token'], 500);
    }

    // if no errors are encountered we can return a JWT
    dd(compact('token'));
    return response()->json(compact('token'));
  }
}
```

JWTTest.php
```
<?php

class JWTTest extends TestCase
{

  public function setUp(){
    parent::setUp();
    \Illuminate\Support\Facades\Artisan::call('migrate');
  }

  public function testGetTokenLogin()
  {
    $this->post('api/authenticate', ['email' => 'test@test.fr', 'password' => 'test']);
  }
}
```

**Comment by feeekkk** [comment]
$this->jwt is just an instance of JWTAuth.

    protected $jwt;
    public function __construct(JWTAuth $jwt)
	{
		$this->jwt = $jwt;
	}

are you still getting `invalid credentials`?

You might need to call `$this->refreshApplication();` before sending your post request.

might be similar to #206

**Comment by tdhsmith** [comment]
What version of jwt-auth are you on?

Does `Auth::once($credentials)` succeed in phpunit? What is the value of `Auth::user()` afterwards?

**Comment by nagoz** [comment]
version tymon/jwt-auth 0.5.9

`$this->refreshApplication()` doesn't work too.
When I use `$this->jwt`, error 500. I verify the error message, now i've got

> 1/2
> PDOException in Connection.php line 333:
> SQLSTATE[HY000]: General error: 1 no such table: users
> 2/2
> QueryException in Connection.php line 713:
> SQLSTATE[HY000]: General error: 1 no such table: users (SQL: select * from "users" where "email" = test@test.fr limit 1)

I confirm that the users table exists.

**Comment by nagoz** [comment]
I found !
My mistake ! :(
I have a different environnement in test mode with sqllite and not my prod environment.
I create a user and now it's ok.
Thanks for all !!
