### ISSUE TITLE
class 'Illuminate\Auth\RequestGuard' does not have a method 'once'

### ISSUE THREAD

**Issue by ShahrokhNiakan** [tymondesigns/jwt-auth#696]
I'm using Lumen 5.2  and install the ymondesigns/jwt-auth. I've follow the instructions on the https://laravelista.com/json-web-token-authentication-for-lumen , but it gives me error Class 'Illuminate\Auth\RequestGuard' does not have a method 'once'

how to attempt the user login on Lumen 5.2

**Comment by cj-schultz** [comment]
You have to comment out the AuthServiceProvider in app.php. However, this just brings you to a new error Auth guard driver [api] is not defined.

**Comment by feeekkk** [comment]
#693

**Comment by fvanhove** [comment]
Is there any news regarding this issue ?

**Comment by feeekkk** [comment]
@fvanhove https://iwader.co.uk/post/tymon-jwt-auth-with-lumen-5-2 worked great for getting this set up with lumen
