### ISSUE TITLE
How do I use version 1.0.0-alpha?

### ISSUE THREAD

**Issue by CBR09** [tymondesigns/jwt-auth#698]
Hi everyone,
I've tried jwt-auth 0.5.\* with laravel 5 and everything is okay, but I want to use public/private key to sign jwt and only jwt-auth 1.0.0-alpha have that. Unfortunately, the docs isn't update :(,  many things has changed and I don't know how to config, how to get it work. Can anyone help me?  Can give me step-by-step to get it working?.

Thanks

**Comment by iWader** [comment]
I wrote a quick blog post on how I got things working with Lumen. https://iwader.co.uk/post/tymon-jwt-auth-with-lumen-5-2

**Comment by autaut03** [comment]
Oh fuck! I've been fucking with 0.5.9 version for the whole day, finally got it working as needed.. then I saw the 1.0.0 alpha and immideatelly updated.. stopped, when ->fromUser method gave me error about implementing JWTSubject and was complaining about how to append some custom claims.. Then returned everything back to the old version and now I want to get back to the alpha again. OH SHIT!

**Comment by sangar82** [comment]
@iWader Thanks for your blog post!! Is very helpful! 

I need to know how publish the config file. Copy it in the config file and add in bootstrap/app.php  $app->configure('config') or $app->configure('jwt-auth') (I tested with two names) has no effect.
