### ISSUE TITLE
Invalid tokens with refresh middleware and parallel requests

### ISSUE THREAD

**Issue by andrewhl** [tymondesigns/jwt-auth#700]
I have the following situation:

1. GET /profile with valid JWT Bearer token
2. GET /otherEndpoint with same JWT Bearer token
3. Request 1. goes through jwt.refresh middleware
4. Old token is blacklisted
5. Request 2. goes through jwt.refresh middleware
6. Old token is invalid, return response 401 unauthorized for request 2
7. Return response 200 OK for request 1
8. Browser receives new token from response to request 1, after request 2 has been issued

How can I resolve this issue? I think I need a 30 second delay before a token is blacklisted. It is not possible to queue the client requests because the application often makes requests in parallel. I have attempted to create a client side middleware of sorts that retries, a finite number of times, 401 token invalid requests. But this still is prone to failure, particularly if a given request takes a long time to return from the server. It is still subject to latency problems.

Any suggestions would be welcome.

**Comment by andrewhl** [comment]
Found it! There's a setting in jwt.php:

```php
    'blacklist_grace_period' => env('JWT_BLACKLIST_GRACE_PERIOD', 0),
```

Setting this to 30 seconds did the trick.

**Comment by nivv** [comment]
@andrewhl I can't find this option, and adding it manually does nothing. What version of `jwt-auth` are you on? 

I'm in the same situation as you were. I'd like to only use a token once, but with many async requests it's hard to keep track of which token is actually valid.

**Comment by andrewhl** [comment]
My version is: "0.6.*@dev"
