### ISSUE TITLE
Getting object not found even having the right token

### ISSUE THREAD

**Issue by rochapablo** [tymondesigns/jwt-auth#701]
I'm not understanding what I'm missing here.

Sometimes when my front-end application calls to the back-end I got the response 401. This sometimes happen passing the token through GET and/or Header.Authorization.

```
http://...?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
```

```
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
```

Right after the error with the same token I'm able to access using postman. So because of this I can't understand why in a time work and other don't.

Here's the authentication:

```
public function handle($request, Closure $next)
{
	JWTAuth::parseToken();

	if (!$token = JWTAuth::getToken()) {
		return $this->respond('tymon.jwt.absent', 'token_not_provided', 401);
	}

	try {
		$user = JWTAuth::parseToken()->authenticate();
	} catch (TokenExpiredException $e) {
		return $this->respond('tymon.jwt.expired', 'token_expired', 401, [$e]);
	} catch (JWTException $e) {
		return $this->respond('tymon.jwt.invalid', 'token_invalid', 401, [$e]);
	}

	if (!$user) {
		return $this->respond('tymon.jwt.user_not_found', 'not_found', 401);
	}

	$this->events->fire('tymon.jwt.valid', $user);

	return $next($request);
}
```

I don't know what else I can provide, so if you need something please tell me.

**Comment by tdhsmith** [comment]
Are you still having this problem? What jwt-auth version are you on?

And you're saying you get the `not_found` response (corresponding to the `!$user` condition), or a different failure?

**Comment by rochapablo** [comment]
No, for now the problem is gone. Anyway it's seems that is the env file the problem. [Here's](https://laracasts.com/discuss/channels/laravel/access-denied-for-user-atlocalhost) where I tried to describe some details.
