### ISSUE TITLE
Net_SFTP has a deprecated constructor

### ISSUE THREAD

**Issue by HtmHell** [tymondesigns/jwt-auth#702]
If I'm trying to use the `phpseclib/phpseclib` package I am getting this warning, that's because your package requires on old version of `namshi/jose` which requires on old version of `phpseclib/phpseclib`.
Please update the version of `namshi/jose` in order to fix this.

Thanks in advanced!

**Comment by antekk** [comment]
+1 same issue here. Is it possible to do a quick upgrade?

**Comment by fisharebest** [comment]
Since September 2017, the entire pacakge `namshi/jose` became deprecated - https://github.com/namshi/jose

**Comment by tymondesigns** [comment]
Since `namshi/jose` has been abandoned, I have now added a Lcobucci driver which uses https://github.com/lcobucci/jwt

It's currently on develop, but will be tagged soonish
