### ISSUE TITLE
1.0.0 Alpha - support of binary uuids

### ISSUE THREAD

**Issue by autaut03** [tymondesigns/jwt-auth#706]
Hey! I'm using your package, but right now I have to replace your auth providers just to modify $id used in auth provider byId method.. Really, it would be just great if you add some function to your JWTSubject interface like transformIdentifierIn and transformIdentifierOut.. and why do we need this - because I personally use UUID's and store it as binary 16. So when I try to authenticate - it gives me error cuz it's unreal to find a user with string'ed uuid.

Unfortunatelly there's no normal way of auto-transforming UUID's in where clause so I have to do it manually (almost) everywhere.

**Comment by helloflow** [comment]
+1 I'm facing the same issue. Would be great if their is a solution for working with UUID's.

**Comment by dodohack** [comment]
@autaut03 Have you resolved this issue? I have exactly the same problem as yours. Just trying to use binary(16) uuid instead of auto-incrementing id in user table.

**Comment by autaut03** [comment]
@dodohack Sure. Replaced AuthProvider's method and that's all. Not an elegant solution but it works.
