### ISSUE TITLE
Authorization Header

### ISSUE THREAD

**Issue by petyots** [tymondesigns/jwt-auth#707]
Hello, i have issue with setting the header Authentication: Bearer.

If i remove the Bearer and only Authentication is there it's working but then i get unable to parse token. I saw the instructions about apache but it's not working either.

This is my .hta

~~~~

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

~~~~

Btw I am using the latest version of laravel. Thanks in advance

**Comment by theatrain** [comment]
Authorization is the key and Bearer is part of the value e.g. ['Authorization' => 'Bearer {json_token}']

**Comment by petyots** [comment]
Arghhh, too much time without sleeping... Thank you I will check it later on, and i will let u know.

**Comment by petyots** [comment]
Fixed !
