### ISSUE TITLE
How to implement JWT for multi login?

### ISSUE THREAD

**Issue by evivz** [tymondesigns/jwt-auth#708]
I want to allow users to login with same creds from two different browsers at same time. How can I generate two different tokens for the same user?

Do jwt support some device id kind of concept? And refresh only particle device token?

**Comment by tdhsmith** [comment]
The library will work this way by default. It has no idea what tokens might currently exist; it can only see the token attached to the current request. This is one of the principles of JWT (_statelessness_). 

So if you visit from a device/browser that doesn't provide an existing token to the server. It won't know about any other tokens that might exist for that user. And if you refresh a token on that device it can only blacklist the old token that device provided to it.
