### ISSUE TITLE
If GetUserFromToken middleware throws exception, how to refresh the token

### ISSUE THREAD

**Issue by jishcem** [tymondesigns/jwt-auth#71]
hi, 

I am a bit new to laravel and its terminologies. 

I am building an API, and It has a verifyphone method in one of its controllers. like this 

`$this->middleware('jwt.auth', ['only' => ['verifyphone']]);`

If the token is not expired and is valid, everything works fine. 

But, if its invalid or expired, what should I do from the API side ? Just throwing the response would be fine ? 

If so, what should I do from the API side to refresh the token ? 

Thank you for any response.

**Comment by tymondesigns** [comment]
By default the `GetUserFromToken` middleware will return a relevant response for you. Although, you can override these if you like ([see here](https://github.com/tymondesigns/jwt-auth/wiki/Authentication#middleware-and-filters))

If you would like to refresh tokens then you can use the `RefreshToken` middleware or do it yourself, using the `refresh()` method:

```php
try {
    $newToken = JWTAuth::setToken('foo.bar.baz')->refresh();
} catch (TokenExpiredException $e) {
    return response()->json(['token_expired'], $e->getStatusCode());
} catch (JWTException $e) {
    return response()->json(['token_invalid'], $e->getStatusCode());
}
```

hope that helps
