### ISSUE TITLE
how to disabling the user model

### ISSUE THREAD

**Issue by fantiq** [tymondesigns/jwt-auth#710]
hi , when i use this package , it will new my User Model where i configurate at the config/jwt.php

but i change the Table Prefix at the User Model by Override the __construct function .

if i user the JWTAuth in the Middleware , the other DB operation will error by the table prefix is changed  . it is because the JWTAuth __construct function inject the User Class like this 

```
public function __construct(JWTManager $manager, UserInterface $user, AuthInterface $auth, Request $request)
    {
        $this->manager = $manager;
        $this->user = $user;
        $this->auth = $auth;
        $this->request = $request;
    }
```

but i did not need to use the User Model all my project

how can i resolve the problem ? (now i configurate the other User Model in the config/jwt.php)

**Comment by feeekkk** [comment]
will overriding the table prefix via the table property outside of the constructor help at all? I'm kind of confused as to what your problem is. https://laravel.com/docs/5.2/eloquent#defining-models

**Comment by fantiq** [comment]
@feeekkk  i don't want to use the user Model in this package .... 
but the class `JWTAuth ` has used the `UserInterface ` at the function `__construct`

**Comment by tdhsmith** [comment]
@fantiq If you "don't want to use the User model in the package", then why are you setting it in `config/jwt.php`? Just make a dummy class that implements [`UserInterface`](https://github.com/tymondesigns/jwt-auth/blob/0.5.9/src/Providers/User/UserInterface.php) and set it to that instead.

**Comment by tdhsmith** [comment]
That said, I'm with @feeekkk... I don't really understand why injecting an instance of your user is causing problems, or why you would set the user table using something other than the `$table` class property. Those things seem to indicate your app has a very nonstandard design, at least from my perspective.

**Comment by fantiq** [comment]
@tdhsmith  yes, now i am doing like what you said ...

about the design ...
like this package it will query the db every time if the route is in the jwt.auth  middle ware ...
i think it is not necessary , i only need to change the token every time , parse the token and get the session id by my rule . 

1. token can be parse by other tools
2. if the user info changed the token must be change
3. it is inefficiency to query db every time 
i think ...

**Comment by tdhsmith** [comment]
Hrm. If you don't use the `fromUser` or `toUser` methods, there won't be a user lookup, and hence no DB query. Write your own middleware that leaves out those methods. (Also look at [the `Check` middleware in 1.0](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Http/Middleware/Check.php) for an example.)

I do agree though: the library is somewhat user-centric, and it can be difficult to configure if you have "nonstandard" user models. I'm not sure what the solution for that would be though.

**Comment by muhaimincs** [comment]
@tymondesigns is it true that we can't move to another table with another fields?
