### ISSUE TITLE
Error create Token from User after update to dev-develop

### ISSUE THREAD

**Issue by SecurID** [tymondesigns/jwt-auth#711]
Hey,

I needed to update my jwt-auth because i need the feature to delay the blacklisting of tokens. 
I updated the jwt.php but when i try to login i get the following error.

<img width="1065" alt="screenshot 2016-05-12 11 38 21" src="https://cloud.githubusercontent.com/assets/7266850/15210456/dec5be66-1836-11e6-89b0-fc127654bef1.png">

Does anybody has an idea on this issue?

**Comment by SecurID** [comment]
Anybody? Couldn't solve the problem until now :(

**Comment by feeekkk** [comment]
could you show some of your code that is triggering this error?

**Comment by tymondesigns** [comment]
The issue here is that your User class must now implement the [`JWTSubject`](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Contracts/JWTSubject.php) interface and the of course the 2 methods within it

**Comment by SecurID** [comment]
Great. It worked. :) 

`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use Tymon\JWTAuth\Facades\JWTAuth;

class Helper extends Controller
{
    public static function getUserFromToken() {
        $token = JWTAuth::getToken();
        $user = JWTAuth::authenticate();

        return $user;
    }
    public static function getTokenRefreshed(){
        $token = JWTAuth::getToken();
        $newToken = JWTAuth::refresh($token);

        return $newToken;
    }
}
`

With the old version I used this to get the authenticated user and refresh the token. Unfortunately the functions seem not to exist anymore? Are there new functions for this purpose? Or is there a smarter way to get that information?
