### ISSUE TITLE
use built-in bearerToken() for parsing

### ISSUE THREAD

**Issue by lukeed** [tymondesigns/jwt-auth#713]
As of Laravel 5.2, there is a new `Request.bearerToken()` token, which will either return then token itself (sans "Bearer") or null.

Source: [API Ref](https://laravel.com/api/5.2/Illuminate/Http/Request.html#method_bearerToken)

**Comment by crynobone** [comment]
is tymon/jwt-auth already dropping support for Laravel 5.1?

**Comment by tdhsmith** [comment]
@lukeed - The parser options available in JWTAuth are much more powerful and configurable than that (i.e. some people use custom headers or prefixes and the library supports that at present) so switching to that method exclusively would be a downgrade. Is there any specific benefit to using the Laravel built-in that you'd be looking for?

@crynobone - I don't know the specific plans, but I have no reason to believe Tymon is dropping support. Laravel 5.1 is the long-term support version, after all. Also there was a lot of work done to modularize things to into both  `JWTAuth` (which supports down to L5.0) and the `JWTGuard` (which is L5.2+ only) and I doubt that get thrown away so quickly.
