### ISSUE TITLE
How to check the disabled user account flag during JWTAuth::attempt?

### ISSUE THREAD

**Issue by deepslux** [tymondesigns/jwt-auth#714]
Hi,

I would like to implement "disabled" flag in user table. During login (JWTAuth::attempt), I would like to check if the "disabled" field is true. How could I achieve that?

```

public function postLogin(Request $request) {
    $credentials = $request->only("userCode", "password");

    try {
      if (!$token = \JWTAuth::attempt($credentials)) {
          return \Response::json(["msg" => trans("err.InvalidCredential")], \HttpResponse::HTTP_UNAUTHORIZED);
      }
    } catch (JWTException $e) {
      return \Response::json(["msg" => trans("err.CouldNotCreateToken")], 500);
    }

    return \Response::json(compact("token"));
  }

```

**Comment by tdhsmith** [comment]
You can just add it to the `$credentials` array... stuff other than passwords just gets "where-d" against the user table. So if you only want to allow users that aren't disabled, just do this before you call `attempt`:

```
$credentials['disabled'] = false;
```

_If we're being technical_, this functionality comes from Laravel's [`EloquentUserProvider`](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Auth/EloquentUserProvider.php#L87), so it's only available in some auth configurations. But if you're using the default providers it will be fine.

**Comment by scramatte** [comment]
Hi,  

I need such feature too.   Solution explained here doesn't works for me

Regards
