### ISSUE TITLE
FormRequest doesn't return bearer key?

### ISSUE THREAD

**Issue by rdpascua** [tymondesigns/jwt-auth#716]
The response from the server when validating using form request doesn't return any bearer key, is this normal? I'm using `jwt.refresh` middleware inside my route group.

**Server response from server**

```
422 Unprocessable Entity
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:8080
Access-Control-Expose-Headers:Authorization
Cache-Control:no-cache
Connection:keep-alive
Content-Type:application/json
Date:Thu, 19 May 2016 13:32:20 GMT
Server:nginx/1.4.6 (Ubuntu)
Transfer-Encoding:chunked
Vary:Origin
```

After this error, If I correct my form or send the form again after a minute or two server responds `401`

**routes.php**

``` php
<?php

$api = app('Dingo\Api\Routing\Router');

$api->version('v1', function($api)
{
    $api->group(['namespace' => '\App\Http\Api'], function($api)
    {
        $api->post('auth/login', 'AuthController@authenticate');

        $api->group(['middleware' => ['api.auth', 'jwt.refresh'], 'providers' => 'jwt'], function($api)
        {
            $api->resource('foo', 'FooController');
        });
    });
});
```

btw I'm using dingo.

**Comment by tdhsmith** [comment]
Two thoughts:

1) Are you sure the server isn't stripping out the header somehow? I see you have some CORS stuff enabled and usually nginx doesn't need as much nudging on that front, but can you see the header in a debug route like this?
```php
Route::get('debug', function () {
    return response('body', 200, ['Authorization' => 'Bearer TEST']);
});
```

2) I see your response is `422 Unprocessable Entity`. Is that because an exception is being thrown? If control passes to the exception handler, the controller/middleware stack is halted and you'll never get to execute the "after" phase of the middleware (which is when the header gets assigned).

**Comment by rdpascua** [comment]
Yes @tdhsmith I'm aware of that, but is there a workaround for this current issue? I've been banging my head for a week now. I resorted disabling the `jwt.refresh` at the meantime.

**Comment by tdhsmith** [comment]
The "current issue" being that exceptions cancel the middleware? You really have that few "successful" requests that your `ttl` is running out? 

I'm not sure what a good approach is then. I guess you could have a try-catch in the middleware that still sets the header in the catch and then rethrows the exception.

Or maybe you could have a generalized concept of "handleable" middleware that pushes a special postException callback onto a stack stored in the exception handler. Then when an exception is thrown, all the callbacks are run.

Something like this has to already exist somewhere... I'm probably just not informed about it...

**Comment by rdpascua** [comment]
I've seen a working example

**Comment by tdhsmith** [comment]
I don't think we're understanding eachother.

FormRequest _can_ return the token. But if you're attaching the token with middleware, it will not happen when an exception is raised.

The link you provided shows this behavior:

- If you access the update page for a dog that does exist (e.g. http://vue.layer7.be/#!/dogs/1400), the response will have a token in the authorization header.

- If you access the update page for a dog that doesn't exist (e.g. http://vue.layer7.be/#!/dogs/55), the `DogsController` will throw an exception via [`findOrFail`](https://github.com/layer7be/vue-starter-laravel-api/blob/c88ed54fc7c8e7e4ee1ac687e3ed0117a54f2264/app/Api/Controllers/DogsController.php#L65) and the response will NOT have an authorization header.

**Comment by rdpascua** [comment]
You can see that attaching the token with middleware works, even with exception raised.

[`DogRequest`][1] extends the [`FormRequest`][2] from dingo.

You can see that even on my screenshot, 422 raises and exception and returns the `BearerKey`
![screenshot from 2016-05-26 09 35 59](https://cloud.githubusercontent.com/assets/2498246/15561130/4ba7af50-2325-11e6-8df0-888bd86efebd.png)

[1]: https://github.com/dingo/api/blob/master/src/Http/FormRequest.php#L22
[2]: https://github.com/layer7be/vue-starter-laravel-api/commit/7e1229a951dc1b2ea951d6af00d2f175fb9b2af4

**Comment by orditeck** [comment]
@rdpascua, how did you manage to send a token even after a 422 error from Dingo? We're facing the same problem.

**Comment by rdpascua** [comment]
hi all, I haven't find a fix for this one.

Sent from my iPhone

On 5 Nov 2016, at 12:51 AM, Keven Lefebvre <notifications@github.com<mailto:notifications@github.com>> wrote:


@rdpascua<https://github.com/rdpascua>, how did you manage to send a token even after a 422 error from Dingo? We're facing the same problem.

**Comment by orditeck** [comment]
Okay. We opened a similar (I think) issue to this one. 

https://github.com/tymondesigns/jwt-auth/issues/897

@tymondesigns ?

**Comment by rdpascua** [comment]
I haven't nail down the issue yet, but what I did to temporarily disable the issue is I disabled the `jwt.refresh` and just extend the life of the token to 30 days. I don't really know what happens here. I wish someone can enlighten us

**Comment by aniljaiswal** [comment]
Have you guys found a solution yet? I too have disabled the `jwt.refresh` middleware and currently extended the life of token to 2 weeks.

**Comment by rdpascua** [comment]
Still doesn't have a decent solution @aniljaiswal what I did is I extend the 30 days similar to oauth lifespan period. But I'm still looking for decent solution for this.

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
