### ISSUE TITLE
Authorization Header not populated by symphony

### ISSUE THREAD

**Issue by FoxxMD** [tymondesigns/jwt-auth#72]
This is related to #16 

The apache rewrite rule fix is not enough to get the authorization header included in the request. In some configurations (mine..has something to do with fastcgi) apache adds a `REDIRECT_` prefix to rewritten environmental variables.

[Take a look at the way Symfony's HttpFoundation](https://github.com/symfony/HttpFoundation/blob/master/ServerBag.php#L60-80) parses the authorization header. Although Symfony does account for the `REDIRECT_` prefix it only works for `basic` auth -- in scenarios where the header contains `basic`. It does not work for any other type, including `bearer` and then does not include the header.

I'm getting around it by using middleware to check the `$_SERVER` variable and adding the authorization header if the redirected header exists, but that might be too hacky for an official package.

```
class HeaderShim implements Middleware {

    public function handle($request, \Closure $next)
    {
        if(isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])){
            $request->headers->set('AUTHORIZATION',$_SERVER['REDIRECT_HTTP_AUTHORIZATION']);
        }

        return $next($request);
    }
}
```

**Comment by tymondesigns** [comment]
Thanks for investigating this.. will take a proper look soon

**Comment by cjmaio** [comment]
I also encounter a possibly similar error when using this package in conjunction with mod_shib.

When taking a look at `apache_request_headers()` or `getallheaders()` or even dumping `$_SERVER[]` I see the authorization bearer header, both with `HTTP_AUTHORIZATION` and `REDIRECT_HTTP_AUTHORIZATION` however, for some reason `$request->headers->get('authorization')` in the `parseAuthHeader` function is getting Basic authentication back and not seeing the Authorization: Bearer <token> header.

**Comment by cjmaio** [comment]
FYI - for Laravel 4 the following works in `filters.php` to get around this issue...

    App::before(function ($request) {
            if(isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])){
                $request->headers->set('AUTHORIZATION',$_SERVER['REDIRECT_HTTP_AUTHORIZATION']);
            }
    });

**Comment by FoxxMD** [comment]
@cjmaio In my post I linked to `ServerBag.php` which is where headers are first populated. Symfony's HttpFoundation does account for the redirect prefix [but only when using basic auth](https://github.com/symfony/HttpFoundation/blob/master/ServerBag.php#L68).

**Comment by tymondesigns** [comment]
@FoxxMD I am thinking about abstracting the request parsing further within the package. So I can have a dedicated place to put this logic. Taking a look now...

**Comment by tymondesigns** [comment]
Added this over on [develop](https://github.com/tymondesigns/jwt-auth/tree/develop) :)

**Comment by tymondesigns** [comment]
specifically [here](https://github.com/tymondesigns/jwt-auth/blob/develop/src/Http/TokenParser.php)

**Comment by FoxxMD** [comment]
:+1:
