### ISSUE TITLE
Urgent help please. Change User table?

### ISSUE THREAD

**Issue by patchthecode** [tymondesigns/jwt-auth#723]
https://github.com/tymondesigns/jwt-auth/wiki/Configuration#user-model-path---user

From this link i assume you can change the user table to something else.
How and where do i change it?

**Comment by jonagoldman** [comment]
This is the path that points to your User class. You can change the user table in the User class but this has nothing to do with JWT, please read the [Eloquent](https://laravel.com/docs/5.2/eloquent) docs.

**Comment by patchthecode** [comment]
What i mean is, JWT is always checking the `User` table as the table for users. Is there any other way to make JWT choose another table name for the users? 
If this is not a JWT issue then i apologize but i really need some help if you know the answer. please..

**Comment by patchthecode** [comment]
Here it says this in the JWT documentation.


**User model path - user**
This should be the namespace path that points to your User class.

Where do i change the User model path to something like `MyCompany_UserModel` path ?
