### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by autaut03** [tymondesigns/jwt-auth#725]
Is this dead?

**Comment by mallardduck** [comment]
No, I think what you're seeing is just a result of the project becoming so popular.

In the last 4-6 months there was a bit of an increase in Issues being opened from my observations, many of which focused on pushing the project to move more quickly to releasing the 1.0.0 version. Then with the increase in popularity of this project you inevitably are met with a situation where we find ourselves now.

The 0.5 branch is fairly well documented but not feature complete yet for what people desire and what @tymondesigns originally had planned. The 1.0 tags are semi functional and far more feature complete, but not documented at all really.

What we have is a project, IMHO, that's too popular for it's own good; it's over-used and under contributed to. The people who understand the code don't need the documentation to use it as it is, and not all the people making issues on GH are actually contributing to solve them.

I think this can lead to a maintainer becoming burnt out feeling, constantly feeling pressured to release the new features everyone wants and also to keep the project will documented and sane. I can't necessarily say that I'm right for sure about any of that at all, I'm probably wrong to varying degrees; but that's what I think I've observed and posts like this don't help that.

---

Especially when it's not warranted at all; the last activity by the dev was 2 days ago. Don't get your knickers in a bunch over your own impatience.

Do you assume people are dead if you haven't heard from them in 2 days as well?
:laughing:

**Comment by tymondesigns** [comment]
@mallardduck You've made some fair and solid observations there 😄 

I have just opened #726 to let people who may be interested know what's happening

**Comment by tymondesigns** [comment]
It'll also give me the kick up the arse to finish the documentation I think 😆
