### ISSUE TITLE
My absence of late...

### ISSUE THREAD

**Issue by tymondesigns** [tymondesigns/jwt-auth#726]
So, some of you may have noticed that I haven't really been responding to issues here lately...

The reason is simply that I have been tied up with other things, mainly work and family commitments. - as have many others throughout the open-source community, I have a full-time job and a family to support, so I don't always have the time that I wish I had to devote to this project.

Let me be clear though.. the reason I am writing this issue, is to _assure_ everyone that I am not out of the game by any stretch, and I will be back very soon, working my way through the issue backlog that has materialised 😱

My main focus will be to FINISH THE DAMN DOCUMENTATION! as I have admittedly let it slide for way too long. THEN I will finally be able to tag a stable `1.0.0` release.

So thank you to everyone for the amazing support and adoption of this project. Stay tuned.

Cheers

**Comment by mallardduck** [comment]
Hey, keep kicking ass man!
This is one of the best JWT packages and IMO you've done an awesome job so far.

**Comment by tymondesigns** [comment]
@mallardduck Cheers! 👍

**Comment by feeekkk** [comment]
Once the documentation is more complete I'm sure more of us will be able to help close out the issues!

**Comment by tymondesigns** [comment]
@feeekkk Right you are 👍

**Comment by pradeep-rajapaksha** [comment]
Hello! I need help.
https://github.com/tymondesigns/jwt-auth/issues/727

**Comment by tdhsmith** [comment]
@tymondesigns Is there any way we can help you with the documentation? I know you probably don't want to put anything incomplete in this repo, lest a flood of confused souls pour down upon us, but I'd be happy to do a proofing & suggestions run if you want to put it up in a gist somewhere.

**Comment by tymondesigns** [comment]
@tdhsmith Yea, once I pull it together a bit more, a once over from yourself would be a great help!

Are you on the larachat slack channel or something similar?

**Comment by tdhsmith** [comment]
Yeah I'm in the Larachat Slack under the same username. I haven't been there in a while, but I _should_ still get DM notifications...

**Comment by tucq88** [comment]
I'm in love with this library and have struggled to get it works :D What could I do to help you improve the docs ?

**Comment by svenluijten** [comment]
As others have suggested, I'd gladly help out with the documentation. You can ping me on Larachat Slack under the username "sven" if you need any more help! :smile:

**Comment by michaelcyyuen** [comment]
Thank you tymon for producing such an awesome lib.  
By the way, can i say, version 0.5 is stable to run in production but just lacks documentation support to be v1.0?
