### ISSUE TITLE
Laravel 5.2 Blacklist error

### ISSUE THREAD

**Issue by sabinad256** [tymondesigns/jwt-auth#728]
> Argument 1 passed to Tymon\JWTAuth\Blacklist::__construct() must be an instance of Tymon\JWTAuth\Providers\Storage\StorageInterface, null given, called in D:\project\demo\yproject\vendor\tymon\jwt-auth\src\Providers\JWTAuthServiceProvider.php on line 213 and defined

I am getting this error. It was working in laravel 5.1 but when i upgraded to 5.2 it suddenly stop working. How to fix this problem ?

**Comment by tdhsmith** [comment]
What version are you on? 0.5.9? What's your jwt config setting for `providers['storage']` (probably the last line in `config/jwt.php`)?

The last couple of version bumps for 0.5 changed how the providers were configured, and you could have an old copy, either of the library or just the config values.
