### ISSUE TITLE
Same id

### ISSUE THREAD

**Issue by estebansanti** [tymondesigns/jwt-auth#729]
While working locally I noticed something odd happening. When a Token is created using credentials e.g email and password, I can return the user object using Auth. Which is fine. However, the Token is attached to the user's id. So if another user has the same id, e.g on a different environment, and the token has not expired, it will not trigger an exception and it will return the object for the different user. 

My question is, is this a bug or a feature? Anyway to make the token more 'personal' to the user it was created for, say trigger an exception if other columns do not match?

Here is the best way I can replicate the issue:

- Create token for 'Joe' (email and password)
- Use said token to auth and return user on an API endpoint on Local, where 'Joe' has an id of 1 in the db
- Use said token to auth and return user on an API endpoint on Production, where 'Jane' has an id of 1 in the db, it will returned 'Jane' even thought the token was created for 'Joe' on Local.

I'm using the following code to generate Tokens from credentials.
```php
        // grab credentials from the request
        $credentials = $request->only('email', 'password');

        try {
            if (! $token = JWTAuth::attempt($credentials) ) {
                return $this->response->array(['error' => 'invalid_credentials'])->setStatusCode(401);
            }
        } catch (JWTException $e) {
            return $this->response->array(['error' => 'could_not_create_token'])->setStatusCode($e->getStatusCode());
        }

        return $this->response->array(['token' => $token]);
```

And this code to return the user object

```php

        $user = $this->auth->user();

        return $user;

```

My apologies if I'm missing any details to further explain, and/or if this whole issue is as a result of poor code, I'm new to JWT.

**Comment by eduacostam** [comment]
This would only happen if you use the same JWT_KEY in both local and production environments,  as that value is used to encrypt and decrypt the JWT in question. 

This is definitely wrong as you should not be using the same value in both environments (from a security point of view). Your server JWT_KEY must be well guarded as it's the key to the auth system in your website. 

Hope this helps!

**Comment by estebansanti** [comment]
That explains a bit. Thanks @eduacostam
