### ISSUE TITLE
How can I shorten the length of the token ?

### ISSUE THREAD

**Issue by jasonmag** [tymondesigns/jwt-auth#73]
My first try of the token returns a 386 of length, how can we shortened it like below 100?

Generated token:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJjb21wYW55IjoiRnV0dXJlRWQiLCJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2Z1dHVyZWVkLmRldlwvYXBpXC92MVwvc3R1ZGVudFwvbG9naW5cL3VzZXJuYW1lIiwiaWF0IjoiMTQyNzQyNjc3MSIsImV4cCI6IjE0Mjc0MzAzNzEiLCJuYmYiOiIxNDI3NDI2NzcxIiwianRpIjoiNmFlZDQ3MGFiOGMxYTk0MmE0MTViYTAwOTBlMTFlZTUifQ.MmM2YTUwMjEzYTE0OGNhNjk5Y2Y2MjEwZDdkN2Y1OTQ2NWVhZTdmYmI4OTA5YmM1Y2QwYTMzZjUwNTgwY2Y0MQ

**Comment by tymondesigns** [comment]
JWT's are generally pretty long as they are an encoded representation of the payload that you provide, and so directly relate to the number of claims that you have. 

Having said that, I doubt it will be possible to get it below 100 chars, without removing some claims that really should be left intact for various reasons. 

And as a result you should be careful how many claims you add to the token.

Is there any particular reason why this is an issue for you?

**Comment by jasonmag** [comment]
Why is it using sha256 and not sha1?

**Comment by tymondesigns** [comment]
I guess the short answer is that the spec seems to dictate it https://tools.ietf.org/html/draft-jones-json-web-token-00#section-8

This library utilises https://github.com/namshi/jose/ and sha1 is not available for use
