### ISSUE TITLE
How do I get the token expiration time?

### ISSUE THREAD

**Issue by HtmHell** [tymondesigns/jwt-auth#732]
Is it possible?

**Comment by tdhsmith** [comment]
You can get the "payload" of a token by _decoding_ it:

```php
$payload = JWTAuth::decode($token);
```

The expiration time is stored in the payload's `exp` "claim" (which is just a key=>value pair). This can be retrieved in multiple ways:

```
$expiration = $payload->getExp();
$expiration = $payload->get('exp');
$expiration = $payload['exp'];
```

In the default setup, the `exp` will simply be a UTC timestamp.

**Comment by elieandraos** [comment]
@HtmHell 
```
$payload = JWTAuth::parseToken()->getPayload();
$expires_at = date('d M Y h:i', $payload->get('exp')); 
```

**Comment by HtmHell** [comment]
Thanks alot!

**Comment by elieandraos** [comment]
you're welcome @HtmHell  :)

**Comment by prionkor** [comment]
Just wondering if there is any way of doing it on client side? I am currently sending and 2 extra fields to browser. expiration time for token, and expiration time for refresh.
