### ISSUE TITLE
Class '\App\User' not found

### ISSUE THREAD

**Issue by chenjiabin** [tymondesigns/jwt-auth#736]
namespace App\Models;       App\Models\User.php
use App\Common\Constant;
class User extends BaseModel
{
    protected $table = 'user';
}

'user' => 'App\Models\User',     jwt.php

message: "Fatal error: Class '\App\User' not found",

I use dingo/api

**Comment by chenjiabin** [comment]
version : 0.5.9

**Comment by tdhsmith** [comment]
Do you have a stack trace of that error? Can you identify where it is occurring in the code?

**Comment by mallardduck** [comment]
Somewhere in your code, or configs, there is something setting it to:

> \App\User

From what I see here:

> namespace App\Models; App\Models\User.php

You seem to have moved it to a Models folder which is totally fine; you just need to find where you have the reference to App\User.

If you are a Linux [probably mac too] use you can try running this, from the project folder:

> grep -irl "App\User" ./

If you are a Windows user...good luck I have no clue there. Maybe they have something similar to grep?

**Comment by NathanBurkett** [comment]
Saw this issue pop up using this package in Laravel 5.2.*. Solution was to change the `providers` configuration in `config/auth.php`. @chenjiabin's solution should be:
```php
'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\User::class, // CHANGE THIS
    ],
    // ...
],
```
to
```php
'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\Models\User::class, // TO THIS
    ],
    // ...
],
```

**Comment by commnerd** [comment]
I too, am running into an issue.  My current provider setup looks as so:
`
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => Dovetail\Models\User::class,
        ],
    ],
`
The plugin seems to ignore the setting.

**Comment by tdhsmith** [comment]
Are you on jwt-auth 0.5.x? If so, did you change the value of `user` in `config/jwt.php` as well?

What file/line is the error pointing to?

**Comment by commnerd** [comment]
So I'm missing a config/jwt.php file...  Working with NathanBurkett over slack...  I'll update with fix.  I might have missed an installation step.

**Comment by tdhsmith** [comment]
Yep, you'll want to publish the config file. ([second to last item in the installation guide](https://github.com/tymondesigns/jwt-auth/wiki/Installation#laravel-5))

```sh
# jwt-auth 0.5 on Laravel 5
php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
```

The subsequent configuration steps in the guide pretty much all refer to that `config/jwt.php` file.

**Comment by commnerd** [comment]
Yeah, I caught that.  I'm not real sure how jwt.php got blown away, because I remember running this, but apparently it was user error.

**Comment by sanchitpuri13** [comment]
Hi, I have recently started learning Laravel-5 and i am developing rest web service. To make api secure i am using JWT("tymon/jwt-auth": "0.5.*"). I am facing the same issue as stated above. 
I have moved the user class from "App\User" to "App\Models\User" and i have added following code in jwt.php

'user' => 'App\Models\User', // code in jwt.php

Inside my Controller Action i have written following code

public function signIn(SignInRequestValidationRules $request)
{

$credentials = $request->only('email', 'password');
try {
if(! $token = JWTAuth::attempt($credentials)) {
return response()->json(['error' => 'invalid_credentials'], 401);
}
} catch (JWTException $e) {
return response()->json(['error' => 'could_not_create_token'], 500);
}
return response()->json(compact('token'));
}

Now whenever i am accessing signIn action using postman i am getting the following exception message.
"Class '\App\User' not found At Line 130 in E:\xampp\htdocs\laravel-rest-service\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php".

If i change the value in Auth.php as shown below

'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\Models\User::class,
    ],
    // ...
],

After changing model value to  App\Models\User::class i am facing another exception which is as follows.
"Argument 1 passed to Illuminate\\Auth\\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\\Contracts\\Auth\\Authenticatable, instance of App\\Models\\User given, called in E:\\xampp\\htdocs\\laravel-rest-service\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\SessionGuard.php on line 385 and defined At 114 in E:\\xampp\\htdocs\\laravel-rest-service\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\EloquentUserProvider.php"

Kindly provide your valuable inputs.

**Comment by leadpresence** [comment]
comment this line
``namespace App;```

**Comment by leadpresence** [comment]
comment this line in User.php
namespace App;  //change this


//namespace App; // to this
