### ISSUE TITLE
Some clarification with JWT Refresh

### ISSUE THREAD

**Issue by jeslomo** [tymondesigns/jwt-auth#737]
Hello!,

This is not a bug, I just need some clarification on how to proceed.

I set in laravel 5.2 jwt.auth middleware and jwt.refresh and I configuring the blacklist parameter to true.

With this I get:

A) The user login and returns a token.
B) The user makes a request with the token A), this token is placed on the blacklist, and a new token that is returned in the header is generated.
C) The application changes the old token for the new token
D) In ​​the next request, the new token B is sent) we changed in C).

Thus always I have a new token and the old is in blacklist. 

How do you see this? I read a lot of the information here and there do not know if this method is **correct** and **safe**.

What do you recommend me?

Moreover, in practice, this system works "sometimes" because I do not know why, I sometimes returns "invalid token".

I read that is problem of verion 0.5. \* And that was corrected in later versions, but I tried to install the version 1.0.0.alpha.2 and but I have not gotten it to work.

Thanks for your time!

**Comment by Phillys** [comment]
Refreshing of tokens works inconsistently for me too. The first refreshed token from the `RefreshToken` middleware always works but then sometimes the second request fails. Any ideas?

**Comment by jeslomo** [comment]
Hi!

The problem is that the middleware add in blacklist the new token. This problem has been correctly in alpha version.

What version are you using?

**Comment by javisperez** [comment]
Well... i had this problem and in my case, my problem was that i had parallel requests, so when the first ended, the token was invalidated and the second request failed. My solution was to set a grace period (of about 1 minute i think) for expired tokens and that solved all my problems. There's a grace-period key in the JWT config file.

Hope this helps!

**Comment by Phillys** [comment]
I'm using 0.5.9. Will the bug be fixed in this version?

My requests which hits the `RefreshToken`middleware do not occur asynchronously since they is chained with promises.
