### ISSUE TITLE
Multi-tenant custom secrets

### ISSUE THREAD

**Issue by BRupholdt** [tymondesigns/jwt-auth#74]
Is there a way to create a variable secret?  

I want to provide a custom secret by concatenating the jwt secret with a tenant secret.  This way I can invalidate tokens app-wide by changing the jwt secret or for a single tenant by changing the tenant secret.

**Comment by tymondesigns** [comment]
I think that would be possible by simply performing your concatenation logic within the config file.

I believe it's outside of the scope of this package though
