### ISSUE TITLE
Get user on successful attempt

### ISSUE THREAD

**Issue by harveyslash** [tymondesigns/jwt-auth#750]
on successful authentication , is it possible to get the user that was authenticated ?
right now I'm doing this
`$token = JWTAuth::attempt($credentials);
`
so is it possible to get the user without doing another db hit a second time ?(i have to do second time because i have to check if he verified or not) ?

**Comment by joejordanbrown** [comment]
@harveyslash 

This should do it without another db query. It should still have the user stored in the class variable user.
`$userData = JWTAuth::toUser($token);`

**Comment by tdhsmith** [comment]
Actually, if you're on v0.5, `toUser` will always run a `where` on your user model. (cf. [JWTAuth.php L76](https://github.com/tymondesigns/jwt-auth/blob/0.5.9/src/JWTAuth.php#L76)) The situation is similar in v1.0; it will depend on your user provider, but it's likely to also hit the DB.

After an `attempt`, you can get the user from `Auth::user()` which should run off its cached user value. Other auth helpers should work as well.
