### ISSUE TITLE
getToken() after attempt()

### ISSUE THREAD

**Issue by peterstarling** [tymondesigns/jwt-auth#751]
For a valid call to attempt method:

`
$this->jwtAuth->attempt(['email' => $email, 'password' => $password]);
`

Wouldn't it be logical to be able to retrieve the token via getToken?

`
$token = $this->jwtAuth->getToken();
`

This however is 'false'. Do I need to manually set the created token (setToken) returned from attempt so that jwtAuth object would assign a token to its protected property and return it with the next getToken?

**Comment by tymondesigns** [comment]
Sorry for the immensely late reply.. but though i'd let you know this functionality has been added
