### ISSUE TITLE
Fetch only required columns when authenticating

### ISSUE THREAD

**Issue by harveyslash** [tymondesigns/jwt-auth#752]
When sending in a token , and monitoring the db query, I see:
`select * from`users`where`users`.`id`= '1' limit 1;`

Is there a way for it to just load just certain columns (I have them indexed and hope to use covering index) instead of the entire row ?

**Comment by tdhsmith** [comment]
That behavior is controlled by Laravel's _user provider_, not by the jwt-auth library.
 
You _can_ modify the behavior by creating a custom provider. For more details, check out the official docs ([Laravel 5.1](https://laravel.com/docs/5.1/authentication#adding-custom-authentication-drivers), [Laravel 5.2](https://laravel.com/docs/5.2/authentication#adding-custom-user-providers)).

**Comment by tdhsmith** [comment]
Here's a slightly-outdated diagram if that helps. (IIRC it's only accurate to jwt-auth v0.5 & stock Laravel 5.2, but the general idea is still right.)

![jwt_diagram](https://cloud.githubusercontent.com/assets/1791252/16067759/02e53872-3285-11e6-8515-ab7c022bb4e6.png)

**Comment by harveyslash** [comment]
@tdhsmith , thanks for the diagram! 
What I am doing at the moment , is , inside JWTAuth's authenticate function , I am preventing the library from  calling byId(). This is what the function looks like now:

 


```
public function authenticate($token = false)
    {
        $id = $this->getPayload($token)->get('sub');
       
        $user = new User(); 
        $user->id = $id;  
        return $user;   
        
    }
```

Is there anything crazy wrong with this approach ?
