### ISSUE TITLE
Calling invalidate() through Auth:: facade

### ISSUE THREAD

**Issue by wizard97** [tymondesigns/jwt-auth#755]
Hi,

I'm on the 1.0 dev branch. Anyways, I'm not sure if this is a bug, or you intentionally didn't implement it, but `invalidate()` works fine to blacklist when it is called on an JWTAuth instance. However, when called through the `Auth` facade (`Illuminate\Auth\AuthManager`), it throws an `JWTException` with "A token is required". I looked at the backtrace, and it nearly works, here is what happens:

1. Since `Illuminate\Auth\AuthManager` does not implement a `invalidate()` function, the `__call()` methods calls it on the guard instance (`JWTGuard`).

2. Since `JWTGuard` does not implement `invalidate()` either, the `__call()` methods is then called on the `JWTAuth` instance. Since, it inherits from `JWT`, `invalidate()` is finally called. This is what the method looks like:

```
    public function invalidate($forceForever = false)
    {
        $this->requireToken();
        return $this->manager->invalidate($this->token, $forceForever);
    }
```

3.. Finally, `requireToken()` throws the `JWTException` since `$this->token` is not set:
```
    protected function requireToken()
    {
        if (! $this->token) {
            throw new JWTException('A token is required');
        }
    }
```

Seems like the call would work if `$this->token` was set. Should `invalidate()` not be called this way, or is this a bug?

**Comment by tymondesigns** [comment]
this is indeed a bug, I will get on fixing that!

**Comment by tymondesigns** [comment]
just added the method to the guard ccbbba29418190f7243033d76278c2e90d39d3fd
