### ISSUE TITLE
Get token expiration time?

### ISSUE THREAD

**Issue by vforv** [tymondesigns/jwt-auth#757]
I want to refresh token before it expire, but problem is I don't know how to get expiration time for some token...

Flow:
1. Check how much time till expire. Ex: 3min till token expire
2. If 3 or less then invalidate old token and refresh it

**Comment by tdhsmith** [comment]
#732 - *How do I get the token expiration time?*
#321 - *Get token expiration after JWTAuth::attempt*

**Comment by tymondesigns** [comment]
Cheers @tdhsmith - A good look through other issues first is a good idea
