### ISSUE TITLE
Exception when trying to create a token with a custom payload

### ISSUE THREAD

**Issue by SeBuDesign** [tymondesigns/jwt-auth#764]
Hi all,

I think I've found a bug in the 0.5.10 version of this package. With the 0.5.9 version I am able to create a token with a custom payload. The code is like this:

```php
$payload = JWTFactory::make(SessionHelper::getBearerPayload());
```

With 0.5.9 this works just fine but with 0.5.10 I get the following exception: `JWT payload does not contain the required claims`

The data I wish to put into the token is:
```php
array:1 [
  "session-id" => "session:5763c8e425805"
]
```

I changed my composer.json to use the 0.5.9 package for now but it would be nice to have this functionality made available again.

Any ideas why this issue occurs?

Thanks!

**Comment by tymondesigns** [comment]
Sorry about that... I may just revert this release, as this is worrying

**Comment by tymondesigns** [comment]
ok release deleted until I can investigate that

**Comment by SeBuDesign** [comment]
@tymondesigns no problem, if you need more information feel free to ask!

**Comment by tdhsmith** [comment]
@SeBuDesign It looks like your payload doesn't contain a subject claim, which is in the default required claims list. If you are not using subjects in your tokens, simply remove the `sub` entry from the `jwt.required_claims` config.

(Before 0.5.10, not having a subject would incorrectly pass the test as long as you had at least one custom claim, which is why you'd first see the message now.)

**Comment by tdhsmith** [comment]
@tymondesigns Maybe to help with this, that message should explain which are missing? https://github.com/tymondesigns/jwt-auth/compare/master...tdhsmith:patch-1

**Comment by tymondesigns** [comment]
@tdhsmith I think you may be right there.. I will re-instate the release when I've checked everything over again.. passing through the missing claims looks like a great idea

**Comment by tdhsmith** [comment]
Yeah more checks are encouraged. I don't mean to sound overly confident in my code; this just happened to be a case I had already considered but forgot to communicate/do anything about earlier. 😐
