### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by ghost** [tymondesigns/jwt-auth#766]
I followed your tutorial from the wiki and the login is working correctly:

```
public function login() {
        if (!$token = JWTAuth::attempt(Input::only('email', 'password'))) {
            return response()->json(['error' => true], HttpResponse::HTTP_UNAUTHORIZED);
        }

        $user = User::where('email', Input::get('email'))->first();

        return response()->json(array(
            'user' => $user, 
            'token' => compact('token')['token'])
        );
    }
```

And for the response I got the token.

But every time I try to use the toke I got:

```
[
  "Token is invalid"
]
```

ie:

```
public function getUser() {
        $token = JWTAuth::getToken();
        return response()->json(JWTAuth::toUser($token));
    }
```

This is a GET to `{{url}}/api/getUser` with the header `Authorization: Bearer {{token}}`

my routes.php contains the following:

```
Route::group(array('prefix' => 'api'), function() {
    Route::post('/login', 'API\UserController@login');
    Route::get('/getUser', ['before' => 'jwt-auth', 'uses' => 'API\UserController@getUser']);
});
```

How can I make this working with the token? Am I missing something here?

**Comment by tdhsmith** [comment]
Can you share a token? Have you tried checking it on http://jwt.io?

**Comment by BrunoRamalho-SmartConsulting** [comment]
I got the following token:
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL3NtYXJ0YXBwXC9hcGlcL2xvZ2luIiwiaWF0IjoxNDY2Mjc5NDYzLCJleHAiOjE0NjYyODMwNjMsIm5iZiI6MTQ2NjI3OTQ2MywianRpIjoiZTdhZTg3MjliMmMwYjU1NDk5ZGNjYzVlMTBlYTUxN2EifQ.C-JWeCNOReZZb5OOk-CSxjgSfAwZ1ACxyuG1yWtDow4

When I test in jwt.io I got invalid signature. Why this is returning me an invalid signature?

**Comment by tdhsmith** [comment]
Did you enter your secret key in the box at the right?

Also what version of jwt-auth are you on? I don't recall or see any versions where `token is invalid` is one of the response messages, but I could easily be missing it.

**Comment by BrunoRamalho-SmartConsulting** [comment]
Yes I added the the secret to the right box, same result.
I'm using this secret now: `Rzp92TtQlD1vjgOk5E3J0bypLZ7NDujt`
And I got the following token: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL3NtYXJ0YXBwXC9hcGlcL2xvZ2luIiwiaWF0IjoxNDY2NDU0ODIyLCJleHAiOjE0NjY0NTg0MjIsIm5iZiI6MTQ2NjQ1NDgyMiwianRpIjoiNmU2ZTA0YmM1Yjg1MGRiZmQ0YTg4NzIzYWQzMzc5ZjYifQ.GENFjr4N9Dx2h9aA-dlGwnW-66OEj-SgKYGaiwhGTeg`

Same error as usually. My config/jwt.php:
```
return [
    'secret' => 'Rzp92TtQlD1vjgOk5E3J0bypLZ7NDujt',

    'ttl' => 60,

    'refresh_ttl' => 20160,

    'algo' => 'HS256',

    'user' => 'App\User',

    'identifier' => 'id',

    'required_claims' => ['iss', 'iat', 'exp', 'nbf', 'sub', 'jti'],

    'blacklist_enabled' => env('JWT_BLACKLIST_ENABLED', true),

    'providers' => [

        'user' => 'Tymon\JWTAuth\Providers\User\EloquentUserAdapter',

        'jwt' => 'Tymon\JWTAuth\Providers\JWT\NamshiAdapter',

        'auth' => 'Tymon\JWTAuth\Providers\Auth\IlluminateAuthAdapter',

        'storage' => 'Tymon\JWTAuth\Providers\Storage\IlluminateCacheAdapter',

    ],

];
```

About the error message, actually the exception says `Token Signature could not be verified.`. Because this comes from `App\Exceptions\Handler`:
```
public function render($request, Exception $e) {
        if ($e instanceof \Tymon\JWTAuth\Exceptions\TokenInvalidException) {
            return response(['Token is invalid: ' . $e->getMessage()], 401);
        }

        if ($e instanceof \Tymon\JWTAuth\Exceptions\TokenExpiredException) {
            return response(['Token has expired ' . $e->getMessage()], 401);
        }

        return parent::render($request, $e);
    }
```

Also my composer.json:
```
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "barryvdh/laravel-debugbar": "^2.2",
        "tymon/jwt-auth": "0.5.*",
        "barryvdh/laravel-cors": "^0.8.0"
    }
```

This is driving me crazy, I can't understand why this showing invalid token.

**Comment by BrunoRamalho-SmartConsulting** [comment]
Any suggestion why this is not working?

**Comment by tdhsmith** [comment]
Well the token you've shown isn't using that secret. In fact, it's using an _empty string_ as its secret: 

```php
$payload = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL3NtYXJ0YXBwXC9hcGlcL2xvZ2luIiwiaWF0IjoxNDY2NDU0ODIyLCJleHAiOjE0NjY0NTg0MjIsIm5iZiI6MTQ2NjQ1NDgyMiwianRpIjoiNmU2ZTA0YmM1Yjg1MGRiZmQ0YTg4NzIzYWQzMzc5ZjYifQ';
$expectedHMAC = 'GENFjr4N9Dx2h9aA-dlGwnW-66OEj-SgKYGaiwhGTeg';
$key = ''; // wat
base64url_encode(hash_hmac('sha256', $payload, $key, true)) === $expectedHMAC; // true
```

Unfortunately I can't for the life of me figure out why it would create with one secret and verify against another. Are you positive you aren't somehow constructing the token with different settings, or have a rogue config setting somewhere?

Also can you verify which versions of `tymon/jwt-auth` and `namshi/jose` you have with `composer info`?

**Comment by mattisdada** [comment]
I'm pretty sure this bug is the same as #789

**Comment by Fabiantjoeaon** [comment]
Any info on this? Experiencing the same problem.

**Comment by Blackops404** [comment]
i had the same problem,in database i used uuid v4 for primary key and column was binary(16)
 so i changed that to int, and every thing is ok.

**Comment by dhixson** [comment]
I had this same issue. It all came down to a false sense of security in the jwt:generate function. This function for me was generating a secret, but not saving it to the env. If you manually copy the secret to the env it works.

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
