### ISSUE TITLE
Hash/encrpyt passwords by default

### ISSUE THREAD

**Issue by Frondor** [tymondesigns/jwt-auth#768]
Why isn't there a hashing/encrypting method for user passwords implemented by default?

**Comment by tdhsmith** [comment]
Are you talking about when using `attempt`? The hashing/user retrieval there is handed entirely by Laravel / you user provider. It doesn't have anything to do with jwt-auth, so you'll have to look into your app's Auth settings.

This library doesn't do anything with loading/saving users to the database.

**Comment by bradders** [comment]
@tdhsmith @Frondor Apologies for digging up an ancient issue, but I think I'm having similar issues. When I pass a plain text password to `attempt()` it works, but passing a hashed password from my DB fails. 

You mention this is a problem elsewhere the auth settings, could point to where?

I'm currently using: `$jwt->attempt($request->only(["email", "password"]))` and I'd like to be able to pass in hashed passwords (as that's all I have in my DB). Thanks.

**Comment by akkhan20** [comment]
@bradders You dont provide the hashed password to 
`$jwt->attempt($request->only(["email", "password"]))`
it is basically for authenticating the user so when you pass the plain text password it gets hashed and matched with the hash in db and you can proceed. if you pass a hashed password it will be rehashed as it is supposed to take plain text and it will fail for sure.

**Comment by kloshar4o** [comment]
You can hash your plain DB password before they get compared,  
So lets say your attempt:
```
[
  email: "admin@admin.com",
  password: "12345678"
]
```
This will compare your plain db password like this:
```
  return password_verify(12345678, 12345678); //false
```
add this to your `User` model:
```
function getAuthPassword(){
  return Hash::make($this->password);
}
```
Gladly this will do:
```
return password_verify(12345678, "some hash string"); //true
```
