### ISSUE TITLE
Unable to undo custom claims when refreshing tokens

### ISSUE THREAD

**Issue by ALionNamedBoy** [tymondesigns/jwt-auth#769]
Hello, thank you all for the work and time you put into this!

I've got the in-development JWTAuth (dev-master#dfd929d) in my local setup and managed to get it working with a Lumen 5.2 setup that also uses Dingo API. 

For a password recovery solution, I've resorted to emailing users a token that contains their password hash as a custom claim, and then unpacking that token to compare against the DB before issuing them a new token that doesn't have the custom claim in it. Unfortunately the custom claim is not letting itself be overwritten, and appears in the newly generated token, even if the previous token is blacklisted. Is there a simple method or something that I'm missing?

Thank you again!

**Comment by tdhsmith** [comment]
You should be able to call `JWTAuth::customClaims([])` with an empty array to clear them. (Or call the same method on the factory, if that's where you were setting them.)

This doesn't come up terribly often because it's rare people issue more than one token in a request, but I guess it could be useful to have a `removeClaim` method...

**Comment by ALionNamedBoy** [comment]
I'm afraid that using customClaims([]) doesn't remove the password claim from the token being newly generated. Somehow the custom claim is getting stuck in the manager's list of claims when it gets read in, and doesn't reset even when the validating token is blacklisted.

**Comment by nhaarman** [comment]
Why is there even any state at all in a factory class?

**Comment by hpaknia** [comment]
Isn't this issue fixed yet?

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
