### ISSUE TITLE
Load Balancer

### ISSUE THREAD

**Issue by gjunior-tray** [tymondesigns/jwt-auth#770]
I have 2 servers running with a load balancer server that is reverse proxy. I need a centralized secret key.

What would be the most appropriate way to use the library? 

Save the key in the database or what else?

**Comment by feeekkk** [comment]
edit the `.env` file and ensure that both servers have the same secret key.

**Comment by tdhsmith** [comment]
Yeah I agree the simplest solution is what @feeekkk suggested. Were you implying your setup has an obstacle to synchronizing the env settings?

I think that should be the only _big_ concern to ensure the auth behaves identically, but I haven't tried running anything distributed myself. However, if you're invalidating or refreshing your tokens, you'll want to make sure your `Cache` driver is shared/centralized as well, or else tokens might get blacklisted on one server and not the other.

**Comment by gjunior-tray** [comment]
@feeekkk and @tdhsmith thanks for your attention.

To solve the problem on time, I will implement the key solution in .env file.

The caching layer is shared, so I'm cool with the blacklist.

My concern was about the use of TTL, how can I implement this in a distributed environment. 

I will not be able to do this if I add it in .env file, will I?

I'll do some tests here right now. Thanks for the help!
