### ISSUE TITLE
config/jwt.php missing; can't set ttl

### ISSUE THREAD

**Issue by mjbillings** [tymondesigns/jwt-auth#773]
Running laravel 5, installed jwt-auth.  Everything is working.  Need to extend ttl and read posts about config/jwt.php but it was not installed.  How to set ttl or why is config/jwt.php missing?

Thanks,
Michael

**Comment by tdhsmith** [comment]
You might not have "published" the vendor files, which is the action that actually copies the configs for you:

```bash
# Laravel 5 & jwt-auth v0.5
php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"
```

( cf. the [installation guide](https://github.com/tymondesigns/jwt-auth/wiki/Installation))

**Comment by mjbillings** [comment]
Thanks for the quick response.  I had ran that but got "Nothing to publish for tag []".  Perhaps I messed something up in the install?

Michael

**Comment by tdhsmith** [comment]
Did you add `Tymon\JWTAuth\Providers\JWTAuthServiceProvider` to the `providers` array in `config\app.php`? (And if you have, it might take a `composer dump-autoload` to reload the classes.)

**Comment by mjbillings** [comment]
It is/was in the config/app.php.  I tried composer dump-autoload then retried the vendor:publish and same result. dump-autoload reported that it was "generating autoload files".  Any other suggestions?

**Comment by tdhsmith** [comment]
`php artisan cache:clear`?

Also you are on jwt-auth version 0.5, correct?

**Comment by mjbillings** [comment]
This is in my composer.json, any other way I can verify.

        "tymon/jwt-auth": "0.5.*"

**Comment by tdhsmith** [comment]
`composer info` will tell you which versions you have actually installed.

I'd definitely try running `php artisan cache:clear` and then try publishing again though... I now see that that has been the issue for some people in the past.

**Comment by mjbillings** [comment]
Okay, I ran the clear and then reran the vendor:publish with the same results.  I'm not sure what else to do.  Can I uninstall/reinstall?  Update? or maybe just manually stick in a jwt.php?

**Comment by mjbillings** [comment]
I was able to generate the jwt.php file now.  I uninstalled and reinstalled the package but what I think did it is that I ran the vendor:publish command from the command line.  I had been running it from within PHPStorm.  Not sure what is different about the two but I think I'm all good.

TANGENT:  Do you know of a way to list the current valid tokens, TTL, and perhaps invalidate them for testing purposes?

**Comment by tdhsmith** [comment]
> what I think did it is that I ran the vendor:publish command from the command line. I had been running it from within PHPStorm. Not sure what is different about the two but I think I'm all good

Ohhh interesting. That could be the reason, but I'm not really sure why either... Well I'm glad you got it figured out!

> Do you know of a way to list the current valid tokens, TTL, and perhaps invalidate them for testing purposes?

Nope, you can't really do it with the stock library. JWTs are stateless, so the server keeps no record of which ones exist. It merely trusts them because it can validate the signatures against its key.

You're welcome to save tokens every time you generate them, but I wouldn't recommend doing it for production (because then you're basically using sessions and losing the benefits of stateless auth, plus it's way more complicated).

**Comment by tdhsmith** [comment]
There are a couple of ideas for how to invalidate users when you don't have their token, but they all pretty much equate to "leaving yourself a note" to invalidate future tokens they try to use. You can also do the nuclear option and change the jwt secret, which will invalidate ALL tokens, by merit of their signatures no longer being correct.

There's discussion on invalidating users [here](https://github.com/tymondesigns/jwt-auth/issues/300#issuecomment-150953800), and I also link a ton of other issues talking about it. I think somewhere in there are some halfway decent rants. :stuck_out_tongue:

**Comment by whoan** [comment]
I solved the same problem clearing the config cache:

    artisan config:clear

**Comment by ezdata** [comment]
I can verify that, as @mjbillings noted, running the commands in PHPStorm's terminal window is the culprit. Once I ran it from a regular terminal window, the missing config file magically appeared.

**Comment by prionkor** [comment]
Can anyone paste the complete jwt.php file? I am using lumen and I can not generate the config file.

**Comment by whoan** [comment]
@prionkor You can see it here: https://github.com/tymondesigns/jwt-auth/blob/develop/config/config.php

**Comment by gbryant200** [comment]
I can't get the config/jwt.php to show up either.  Tried all of the above.  Laravel 5.6.12; jwt version 0.5.12; the publish command indicates it's published but the file isn't there.  Can you just add the file manually?  Even tried sudo php artisan vendor: . . . no dice

**Comment by temmy-alex** [comment]
Thanks whoan you saved my time!
