### ISSUE TITLE
How to use the Jwt-auth with Filemanager to get user Credentials?

### ISSUE THREAD

**Issue by FerchoCarcho** [tymondesigns/jwt-auth#780]
Hello !!

At my site Im using  [Simogeo/Filemanager](https://github.com/simogeo/Filemanager) to browse Images and Files.
To secure the User Access Im Using
 [Bestmomo Filemanager](https://github.com/bestmomo/filemanager) to retrieve user credentials.
There,the config file [default.config.php](https://github.com/bestmomo/filemanager/blob/master/public/filemanager/connectors/php/default.config.php)
retrieves the user data with:

```
$id = $app['encrypter']->decrypt($_COOKIE[$app['config']['session.cookie']]);
$app['session']->driver()->setId($id);
$app['session']->driver()->start();
```

But as the Jwt-auth token doesn’t require Sessions Neither cookies to access user information, I can no longer get the credentials for validating. I have Overridden the authentication Controller(AuthController ) in Laravel , there,  A trait, AuthenticatesUsers initializes the cookies and the session.

How Could I replace the use of Cookie/Sessions to pull the Token inside that file and retrieve the User's Data?

In Resume, I need to send the Token to Filemanager when the User Browses it, There (but I dont understand how) Retrieve Users Data and Grant Access to Browse files.

**Comment by tdhsmith** [comment]
How are you sending the token to the server? Does filemanager need the user to exist on the session specifically, or somewhere else?

Did you try "normal" jwt-auth calls, like `JWTAuth::authenticate()`?

**Comment by FerchoCarcho** [comment]
Hello @tdhsmith,
To make petitions to the server I use ``` client({path: '/posts'}).then() ```   from [cujojs/rest](https://github.com/cujojs/rest/) . About The User living on a session , its not obligatory. 
my Issue is that Im not getting how to Send the token to Filemanager when the User Press the Browse Button, Filemanager is called within Ckeditor. 
[Here is an Illustration](https://postimg.org/image/qjj2qi1lt/)

**Comment by FerchoCarcho** [comment]
I have Found The solution and its like that:
On Click Browse Button.
1. at Ckeditor there is the fileBrowserUrl Directive which you should point to a laravel Route First where you can  Use the jwt-aut token to validate and retrieve user permissions.
2. Based on the user's Permission Return to the Browser the Url where Filemanager can Access.

Now  I need to learn how to parse that Access Url within Filemanager.

**Comment by tdhsmith** [comment]
Great, I'm glad you figured it out! And thanks for explaining the solution here.

**Comment by FerchoCarcho** [comment]
If I do 
filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images&token='+localStorage.getItem('jwt-token'),
                    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images',
                    filebrowserBrowseUrl: '/laravel-filemanager?type=Files&token='+localStorage.getItem('jwt-token'),
```
produces
```
{"error":"token_invalid"}
```
Is it because Im passing other things with it ? 
the output is 
```
http://mysite.dev/laravel-filemanager?type=Images&token=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwLCJpc3MiOiJodHRwOlwvXC9iYWNrand0LmRldlwvbG9naW4iLCJpYXQiOjE0NjczMzgyMjcsImV4cCI6MTQ2NzM0MTgyNywibmJmIjoxNDY3MzM4MjI3LCJqdGkiOiI5NTM3M2YzODE0NzRmNzAyNDliMWFlMjM4YjUyNmQ2YyJ9.WNie8dYBDLBS5zg6g81DfeCB5k1EIEGTpNkk400HHIE&CKEditor=messageArea&CKEditorFuncNum=1&langCode=en
```

**Comment by FerchoCarcho** [comment]
I had To remove the word "Bearer" from the Token and then authenticate it with 
JWTAuth::authenticate($string);

**Comment by tdhsmith** [comment]
Yes the "Bearer" component isn't part of the _token_, it's part standard format for the header: `Authorization: Bearer <token>`. So if you're not sending the token in an HTTP header, it won't need that part.

Did you try `authenticate()` without any arguments? It should already read from the `token=` query string. (see [JWTAuth::parseToken](https://github.com/tymondesigns/jwt-auth/blob/0.5.9/src/JWTAuth.php#L203))  Of course if isn't broken, don't fix it. 😛

**Comment by FerchoCarcho** [comment]
if I just  $this->me= JWTAuth::authenticate();
