### ISSUE TITLE
ErrorException in RequestGuard.php when use JWTAuth::attempt($credentials)

### ISSUE THREAD

**Issue by buihoang91tin** [tymondesigns/jwt-auth#782]
First I have problem with 

> BindingResolutionException in Container.php line 752: Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable while building [Tymon\JWTAuth\Middleware\GetUserFromToken]

I try to add this code
`$this->app->singleton('Illuminate\Contracts\Routing\ResponseFactory', function ($app)
        {
            return new ResponseFactory($app['Illuminate\Contracts\View\Factory'], $app['Illuminate\Routing\Redirector']);
        });`
It's error Class Tymon\JWTAuth\Middleware\ResponseFactory not found

So I try again to back and remove useless "use" of Interface like this [532](https://github.com/tymondesigns/jwt-auth/pull/532)

Next when I try again, I see this error: Class Tymon\JWTAuth\Middleware\ResponseFactory does not exist

So now what must I do to resolve this.Please help me.

**Comment by buihoang91tin** [comment]
I have fixed this error 
But when I try to login in website

I have create form to login
![image](https://cloud.githubusercontent.com/assets/9276526/16514824/9dad0edc-3f98-11e6-9ad4-de17f44f714d.png)

And try to login in desktop. and this is repsonse

{"error":"token_not_provided"}

What must I do now. Can I login by android by this

**Comment by buihoang91tin** [comment]
I try login with android, It's still reponse {"error":"token_not_provided"}
So what must I do for login from android by jwt. Please help me

**Comment by buihoang91tin** [comment]
I try to add these lines to .htaccess on public folder

```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

And My Database user have id column

It's still response {"error":"token_not_provided"}. What must I do now

**Comment by buihoang91tin** [comment]
My table is not default user table. So now How can I config login with other tables on database

**Comment by buihoang91tin** [comment]
I have edit Model in Model User for my table. But it's still response 

{"error":"token_not_provided"}

**Comment by tdhsmith** [comment]
Are you _providing a token_? The message is indicating that that middleware expects your request to have a token in it somewhere.

The token is most commonly included in an HTTP header, but it can also be included in a query string, the message body, a URL parameter, a cookie, (jwt-auth will automatically check the first 2 in v0.5, and all of them in v1.0) or elsewhere.

If you are confused about when and why you're creating and using tokens, check out an introduction to JWTs. For example, [the about page at jwt.io](https://jwt.io/introduction/#how-do-json-web-tokens-work-) has a decent outline of the process.

**Comment by buihoang91tin** [comment]
But hơ can I create token for HTTP request with JWTAuth in Laravel Lumen. I have set csrf_token but lumen did not have them

**Comment by buihoang91tin** [comment]
So now I have this error
ErrorException in RequestGuard.php line 66:
Undefined index: request

When I try to change once function in IlluminateAuthAdapter and I got this error. Some one know this problem

**Comment by buihoang91tin** [comment]
Please help me so now, How can I authenticated user in lumen laravel,

This is my code 

`    public function postLogin(Request $request)
    {
        try {
            $this->validate($request, [
                'email' => 'required|email|max:255', 'password' => 'required',
            ]);
        } catch (HttpResponseException $e) {
            return response()->json([
                'error' => [
                    'message' => 'Invalid auth',
                    'status_code' => IlluminateResponse::HTTP_BAD_REQUEST
                ]],
                IlluminateResponse::HTTP_BAD_REQUEST,
                $headers = []
            );
        }

        $email = $request["email"];
        $password = $request["password"];

        $credentials = $this->getCredentials($request);

        try {
            // attempt to verify the credentials and create a token for the user
            /*if (!$token = JWTAuth::attempt($credentials)) {
                return response()->json(['error' => 'invalid_credentials'], 401);
            }*/

            if(!Auth::attempt(['email' => $email, 'password' => $password])){
                return response()->json(['error' => 'invalid_credentials'], 401);
            }

        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return response()->json(['error' => 'could_not_create_token'], 500);
            //return json_encode("pass here");
        }

        // all good so return the token
        return response()->json(compact('token'));
    }`

**Comment by buihoang91tin** [comment]
Could someone help me. I'm  using jwt   
`"tymon/jwt-auth": "^0.5.9",`

**Comment by feeekkk** [comment]
https://laravelista.com/json-web-token-authentication-for-lumen/

**Comment by buihoang91tin** [comment]
Sorry, But i've tried this tutorial. But it's not success for me. I'm trying to config for them.
I still have this problem. Please help me

**Comment by buihoang91tin** [comment]
I have tried like this issue. [654](https://github.com/lucadegasperi/oauth2-server-laravel/issues/654)
It's return Auth::user()->id
But response()->json(compact('token')); always return null. So how can I compact token when I have auth

**Comment by buihoang91tin** [comment]
I have fixed this error. Thank you all

**Comment by tdhsmith** [comment]
Great news.

I'm guessing the issue was: you declared `$token` inside a try-catch, so it wasn't actually defined in the outer scope, and `compact` couldn't see it.

**Comment by ismaelse13** [comment]
Hi @buihoang91tin , I'm having the same error. Could help me with that?
