### ISSUE TITLE
Unable to parse the token from the Authorization header

### ISSUE THREAD

**Issue by PrashanthRaghu** [tymondesigns/jwt-auth#786]
The middleware for jwt.refresh just accepts tokens from the url but does not accept it from the Authorization header. We have a use case where we are unable to pass the token from the url. 

Any help is appreciated.

**Comment by tdhsmith** [comment]
The refresh middleware calls the exact same `parseToken` method as the other middlewares, so it's very unusual if it behaves differently. Are you sure you have the routes set up the same way?

What version of jwt-auth are you on? And how are your headers formatted? (i.e. did you remember the "Bearer" keyword? etc `Authorization: Bearer <token>`)

**Comment by PrashanthRaghu** [comment]
@tdhsmith : thanks for the response.

Example route:

Route::post('load_notifications', ['middleware' => ['jwt.refresh'], 'uses'=> 'NotificationController@loadNotifications']);  

Version: "tymon/jwt-auth": "0.5.*"

Yes I have added the Bearer keyword as well. I tested it using POSTMAN rest api client. Do you think there might be issue with the client ?

**Comment by bitcalc** [comment]
Are you using Apache? Have you got the `src/public/.htaccess`:

~~~
# Handle Authorization Header
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
~~~

The lines there prevent Apache from ignoring the header if not base64 encoded.

**Comment by PrashanthRaghu** [comment]
@bitcalc : Thanks for the response.

Yes I am using Apache. I will try adding these headers.

**Comment by PrashanthRaghu** [comment]
@bitcalc: It's working fine. Thanks for the response.

**Comment by prime-ralph** [comment]
Can I ask you to close this issue if you've got it working? To help those that are searching for solutions as well.
Almost missed this because I checked the closed issues first, and others might do the same.
