### ISSUE TITLE
Token blacklisted after creating it from User object and trying to invalidate it + AuthenticateAndRenew not invalidating old token

### ISSUE THREAD

**Issue by kurbar** [tymondesigns/jwt-auth#787]
I've implemented JWT authentication to a Lumen 5.2 project and am using the latest from `dev-develop`.

Environment:
PHP 7.0.4-7ubuntu2.1
nginx 1.10.0
## Token blacklisted after creating it from User object and trying to invalidate it

In my login endpoint I'm creating the token from the User object (`JWTAuth::fromUser($user)`) and then tried doing tests on the logout endpoint to see that it gets invalidated.

I'm loading in the configuration from the bootstrap/app.php file using `$app->configure('jwt');` and also have `blacklist_enabled` set to `true`.

I have the `LumenServiceProvider` registered in my bootstrap file as well as using the `AuthenticateAndRenew` routeMiddleware.

Also I'm loading in the Facades:

```
class_alias(Tymon\JWTAuth\Facades\JWTAuth::class, 'JWTAuth');
class_alias(Tymon\JWTAuth\Facades\JWTFactory::class, 'JWTFactory');
```

Now on my logout endpoint when I try to do either `JWTAuth::invalidate();` or `JWTAuth::invalidate(JWTAuth::getToken());`, I'm thrown the `TokenInvalidException` which says `The token has been blacklisted` but this doesn't happen when I navigate to a protected view that isn't logout.
### AuthenticateAndRenew not invalidating old token

**Now to the second problem:**
1) I hit the login endpoint and get a new token
2) I go to a protected view with the token in the `Authorization` header.
3) Everything works, I am able to access

**Now what should happen:**
1) The API returns back a newly generated token in the response `Authorization` header since I'm using the `AuthenticateAndRenew` middleware
2) The old token should now be invalidated and I can access the next request with the new token

**What actually happens:**
The old token does not get invalidated and I am able to access the routes with the old token.

Have I messed up somewhere or am I invalidating the tokens incorrectly?

**Comment by archie20** [comment]
I seem to have the exact same problem. Im

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
