### ISSUE TITLE
URLs in payload changes the token - forcing it to always be invalid

### ISSUE THREAD

**Issue by mattisdada** [tymondesigns/jwt-auth#789]
Confirmed this using multiple tools to generate the token, but having a forward slash (`/`) will **always** change the token - and therefore a valid signature.
### Input:

**Header:**

```
{
  "alg": "HS256",
  "typ": "JWT"
}
```

**Payload:**

```
{
  "sub": "1234567890",
  "iat": "1467933831",
  "iss": "bcsg-qk",
  "exp": "1667933831",
  "name": "John Doe",
  "admin": true,
  "partner_error_url": "https://google.com"
}
```

You can use any string as the secret (I used "secret" for this example)

**Token:**
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoiMTQ2NzkzMzgzMSIsImlzcyI6ImJjc2ctcWsiLCJleHAiOiIxNjY3OTMzODMxIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsInBhcnRuZXJfZXJyb3JfdXJsIjoiaHR0cHM6Ly9nb29nbGUuY29tIn0.N0uqMCjXZDt6OFbZqk9J_hmHWcisgPBUxoWQ-ZRD7bw`

---

Now, the output from JWTAuth (or even the base lib JOSE), is as follows:

**Token:**
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoiMTQ2NzkzMzgzMSIsImlzcyI6ImJjc2ctcWsiLCJleHAiOiIxNjY3OTMzODMxIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsInBhcnRuZXJfZXJyb3JfdXJsIjoiaHR0cHM6Ly9nb29nbGUuY29tIn0.N0uqMCjXZDt6OFbZqk9J_hmHWcisgPBUxoWQ-ZRD7bw` (please note, the signature is not included here, the lib splits it off)
### Base64 Decoded:

**Header:**

```
{
  "alg": "HS256",
  "typ": "JWT"
}
```

**Payload:**

```
{"sub":"1234567890","iat":"1467933831","iss":"bcsg-qk","exp":"1667933831","name":"John Doe","admin":true,"partner_error_url":"https:\/\/google.com"
```

Note the missing `}` and the additional slashes. This causes the hashes it needs to identify as being different, hashes decoded as strings:
Hash 1:
`b"7K¬0(Îd;z8V┘¬OI■\x19çY╚¼Ç­TãàÉ¨öCÝ╝"`

Hash 2:
`b"Ö.Ù¶¢³{êƒ)\r\x06}c=×ðqN\r>¥F­Ì\x7F\x0E,¼5—ô"`

This is a fully valid JWT token, straight form JWT.io

---

Pre-escaping the `/` will result in just more slashes being added in

---

EDIT: I did some more investigating, this looks like a bug in at least this version of the underlying lib (JOSE 5.0.*, by 7.0.* at least it has been resolved). Running jwt-auth `0.5.9`

**Comment by tdhsmith** [comment]
Hrm I haven't seen that issue before. I'm not sure if we can blame _all_ slashes immediately because the default `iss` constructor is `request()->url()`, which usually has some slashes in it. Then again I've seen some oddities on 0.5 similar to what you say where the payload slashes are escaped in the output or the hash refers to a different level of escaping...

Was the JOSE bug documented somewhere?

**Comment by mattisdada** [comment]
I couldn't find the JOSE bug, but when testing, 0.5.* did not work, anywhere I put a `/`. But on 0.7.* it never had an issue. It might have been accidentally fixed or something

**Comment by doncabron** [comment]
I run into the same problem. I successfully created a token but I can't authenticate against it. It might have to do with the slash in the `iss` field. Is there any workaround, as this is getting frustrating. I'm using the 1.0.0-alpha2 and through that JOSE 0.7.* 

Thanks a lot for your help...

**Comment by Fabiantjoeaon** [comment]
Any info on this issue? I'm experiencing the same problem.
