### ISSUE TITLE
Can't test auth'd user.

### ISSUE THREAD

**Issue by patrickcurl** [tymondesigns/jwt-auth#793]
my testcase seeds and migrates a database. -- users need special permissions to access list of all users. 

I'm trying to authenticate in a test and getting this error: 

"The token could not be parsed from the request"

public function authUserGetWithGroup($uri, $usergroup, $headers = [])
    {

```
    $authUser = App\Models\User::where('user_group_id', '=', $usergroup)->first();
    $token = JWTAuth::fromUser($authUser);

    #$headers = ['Authorization' => 'Bearer ' . $this->getAuthUserToken()];
    $endpoint = "$uri?token=$token";
    return $this->get($endpoint);
```

}

I've echoed out the token, and url - the url shows up as: "http://api.test.dev/v1/users?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjExLCJpc3MiOiJodHRwOlwvXC9jb29raWVzLmRldiIsImlhdCI6MTQ2ODcxNDY1NSwiZXhwIjoxNDY4NzE4MjU1LCJuYmYiOjE0Njg3MTQ2NTUsImp0aSI6IjA0ZmI2MTVjOGE3MGU0YmFlMDAwMjBkMzhhMGQ2MTM0In0.Hc6hllfvxycGLBc900SZKgR4SaNuMBdoDeZRuUU35tc"

I've tried both using ?token=$token and passing in the commented out $headers. Both return the same error message.

**Comment by ghprod** [comment]
have you solve it?
