### ISSUE TITLE
Dependency conflict with google/clientapi v2

### ISSUE THREAD

**Issue by tyteen4a03** [tymondesigns/jwt-auth#798]
`google/clientapi`'s [composer.json](https://github.com/google/google-api-php-client/blob/master/composer.json) requires `phpseclib/phpseclib` to be `~2.0` but the latest stable release of jwt-auth uses `namshi/jose` 5.0.\* which requires `phpseclib/phpseclib` to be `~0.3`.

Is it possible to update the 0.5 branch to use jose 7.0 to avoid this dependency conflict?

**Comment by chmoelders** [comment]
Hi @tyteen4a03,

be careful with namshi/jose:7.0 !

Have a look at my [comment](https://github.com/tymondesigns/jwt-auth/issues/783#issuecomment-233121249). Decoding/encoding in namshi/jose:7.0 is a little bit different.

**Comment by tyteen4a03** [comment]
This is a new system so I should be OK. Thanks for the heads up.

**Comment by tdhsmith** [comment]
Have you tried forcing jose 7.0 in your project? I don't know for certain, but I suspect the signatures of the methods that jwt-auth uses are unchanged between the versions, so you can probably get away with doing it in your own project.

As @chmoelders points out, the change invalidates existing tokens, so it shouldn't be applied to 0.5 without careful planning or a warning for users. (And in general development on 0.5 is "finished".)

**Comment by oleghmelevschi** [comment]
Same problem here. 
I updated the "tymon/jwt-auth" to the "1.0.x-dev" version with "google/apiclient": "2.*". 
It's works. In the config/app.php i changed the provider for the Tymon\JWTAuth\Providers\LaravelServiceProvider::class, but now i have this error: "Class Tymon\JWTAuth\Providers\JWT\NamshiAdapter does not exist"

May be a small doc for the alpha version will help?

Tnx!

**Comment by prewk** [comment]
Has anyone been able to solve this properly for the `0.5` branch? We're stuck in not being able to use `google/clientapi` v2 at all, and upgrading to `jwt-auth` alpha without docs is not an option.

**Comment by tyteen4a03** [comment]
@prewk As a workaround, you can force composer to install jose 7.0 and make it look like 5.0.

Put this line in your composer.json: `"namshi/jose": "^7.0 as ^5.0"`

**Comment by yashbarot** [comment]
I have one [plugin](https://github.com/webelightdev/laravel-dbbackup)  which used `"google/apiclient": "^2.0"`. While i am installing it in one of my project which has `jwt-auth` installed, i am getting following 

![screen shot 2016-10-17 at 4 53 38 pm](https://cloud.githubusercontent.com/assets/6562115/19435809/500d091a-948a-11e6-973d-da6b794c764e.png)

**Comment by tyteen4a03** [comment]
@yashbarot Did you use the workaround I provided?

**Comment by tvmota** [comment]
Don't work, jwt-identify the version of namshi/jose 7.0 and install 5.0,

**Comment by creightonja** [comment]
Same issue here due to a conflict with phpseclib versions. Any working fixes?

**Comment by pipriles** [comment]
I have the same issue with the google api, namshi/jose 5 has a dependecy which uses a php 5 style of constructor and i have php 7, i need namshi/jose 7 but i cannot install it because the conflict.. :(

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
