### ISSUE TITLE
AuthenticateAndRenew middleware doesn't use refresh flow

### ISSUE THREAD

**Issue by mattmcdonald-uk** [tymondesigns/jwt-auth#799]
The AuthenticateAndRenew middleware looks to authenticate a token and refresh it, combining the Authenticate and Refresh middleware.

But this doesn't work when a token has expired but can still be refreshed because it doesn't use the refreshFlow.

Should it not be allowing this in the same way the Refresh middleware would allow this?

**Comment by mattmcdonald-uk** [comment]
Alternatively - if that is as intended - then my issue instead would be why the Refresh middleware (in develop branch) doesn't set the User as the other middleware do (it never seems to make a call to byId so setUser is never invoked).

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open

**Comment by mattmcdev** [comment]
@tymondesigns Is the behaviour of the `AuthenticateAndRenew` middleware meant to combine the behaviour of the `Authenticate` and `Refresh` middlewares?
