### ISSUE TITLE
user_not_found on auth middleware

### ISSUE THREAD

**Issue by Murwa** [tymondesigns/jwt-auth#80]
Hey @tymondesigns great stuff. I just pulled in the new version(0.5.1) - should have the vulnerability patch- and realised that all my initially working requests are failing on the jwt-auth middleware. Is there something I should change in the requests?

Cheers

**Comment by mcblum** [comment]
I can't get it to work, either. I see the header listed as Authorization: Bearer {token} but the response I get is token_not_provided. Might be the same issue?

**Comment by Murwa** [comment]
seems like the issue is with the authenticate function

**Comment by tymondesigns** [comment]
I think the main issue a few people are having is surrounding the request parsing portion of the package. Which I think is what is happening here.. 

Hope to resolve the issues soon

**Comment by tymondesigns** [comment]
will be resolved when new release drops - see [here](https://github.com/tymondesigns/jwt-auth/tree/develop)

**Comment by Murwa** [comment]
Thanks
