### ISSUE TITLE
Add exception for token_not_provided

### ISSUE THREAD

**Issue by ahmadazimi** [tymondesigns/jwt-auth#802]
Is there any idea to add an exception for `token_not_provided` error, so developers can handle it and pass their custom message?

**Comment by briscula** [comment]
+1

**Comment by yanchogeorgiev** [comment]
or at leaset to change BadRequestHttpException('Token not provided') with UnauthorizedHttpException. I don't think this is a bad request.

**Comment by samthomson** [comment]
+1

**Comment by murilobd** [comment]
+1

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
