### ISSUE TITLE
Invalidate other token from current user

### ISSUE THREAD

**Issue by ynixt** [tymondesigns/jwt-auth#804]
It's possible get all tokens from the current user with a purpose of invalidate one of them?

When I've a valid token in my "Device 1", I've need to, sometimes, disconnect a "Device 2" that belongs to the same account that "Device 1" belongs, but consumes a different token.

I searched in wiki and I read another issues, but I can't find something that help me.

**Comment by ahmadbadpey** [comment]
@ynixt , have you arrived to any solution ?

**Comment by ynixt** [comment]
@ahmadbadpey I kept the tokens in database, so I can get all tokens from specif user
