### ISSUE TITLE
How to expire all old tokens and generate new token?

### ISSUE THREAD

**Issue by prashantidealittechno** [tymondesigns/jwt-auth#806]
Hello, 
In my application for iphone and android I am using JWT auth in rest API.
In case if any user login into any other device I want to make him logout from previous device.
The most easy way to do that is expire the old token and generate new one.

I wrote some code in Login to check and authentication of user email and password than I expire all the old token it expire the new one also.

Is also try to generate a new token with users info again but it does not allow me to generate new token it also expire. even after that.

Is their any way that when I check the auth it expire the old tokens and generate new token?

Thanks.

**Comment by timbroder** [comment]
@prashantidealittechno you'll need to keep track of the tokens yourself. see #300

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
