### ISSUE TITLE
RefreshToken is prematurely blacklisted

### ISSUE THREAD

**Issue by bkolicoski** [tymondesigns/jwt-auth#808]
When using the 1.0.0-alpha.2 version of the RefreshToken with the "jwt.refresh" the token is first refreshed and then it is being checked for the next request. This result in the current token being blacklisted by the refresh() call and not proceeding to execute the request. 

```
public function handle($request, Closure $next)
    {
        $this->checkForToken($request);

        try {
            $token = $this->auth->parseToken()->refresh();
        } catch (JWTException $e) {
            throw new UnauthorizedHttpException('jwt-auth', $e->getMessage(), $e, $e->getCode());
        }

        $response = $next($request);

        // send the refreshed token back to the client
        $response->headers->set('Authorization', 'Bearer '.$token);

        return $response;
    }
```

should be:

```
public function handle($request, Closure $next)
    {
        $this->checkForToken($request);

        $response = $next($request);

        try {
            $token = $this->auth->parseToken()->refresh();
        } catch (JWTException $e) {
            throw new UnauthorizedHttpException('jwt-auth', $e->getMessage(), $e, $e->getCode());
        }

        // send the refreshed token back to the client
        $response->headers->set('Authorization', 'Bearer '.$token);

        return $response;
    }
```

**Comment by tdhsmith** [comment]
> This result in the current token being blacklisted by the refresh() call and not proceeding to execute the request

Where isn't it proceeding? Sure it gets blacklisted, but that doesn't stop in the try-catch and it should still execute everything... 

The timing of this middleware was a deliberate change from 0.5->1.0. If the check goes after `next` you can end up running actions that are unauthorized before hitting an exception.

**Comment by bkolicoski** [comment]
I'm using the "jwt.refresh" middleware on the route to check if the token sent is being valid but that only executes on getting the next request. If the next request is taken after the token is refreshed, the middleware sees the token as blacklisted and it is not executing it. 

If the request is taken first, token passed from previous request is valid, next request is taken and then the token is blacklisted so if will not allow unauthorized request.

**Comment by mariaczi** [comment]
Hello,

I think I have similar issue. Similar behavior like @bkolicoski 
When I login (vue front end), I am getting token, then it is going through one request, getting refreshed token back and then there is new token attached to next request, but it is throwing `invalid_token` exception.

This is code of function where I am checking token (stored in cookie etc):
```
public function validateToken(Request $request)
    {
        try {

            if (! $user = JWTAuth::parseToken()->authenticate()) {
                return response()->json(['user_not_found'], 404);
            }

        } catch (Tymon\JWTAuth\Exceptions\TokenExpiredException $e) {

            return response()->json(['token_expired'], $e->getStatusCode());

        } catch (Tymon\JWTAuth\Exceptions\TokenInvalidException $e) {

            return response()->json(['token_invalid'], $e->getStatusCode());

        } catch (Tymon\JWTAuth\Exceptions\JWTException $e) {

            return response()->json(['token_absent'], $e->getStatusCode());

        }

        // the token is valid and we have found the user via the sub claim
        return response()->json(compact('user'));
    }
```

Both - first and second requests are under `jwt-refresh` middleware.

@tymondesigns any idea ?

**Comment by bkolicoski** [comment]
@mariaczi I ended up using "jwt.renew" instead of refresh and it seams to have solved the issue for me. 

It does have similar logic as "refresh" so I'm not sure what is the difference between both and when each should be used. Maybe someone can add more input on this?

**Comment by mariaczi** [comment]
@bkolicoski hopefully @tymondesigns can sort it out, as it would be perfect to secure routes just with `jwt.refresh` and have them secured with JWT checking and with token refreshed after every request to increase security. For this moment I've switched over to just jwt.auth to not waste my time, but all logic in frontend(Vue) is prepared to consume refreshed tokens on every request.

**Comment by mofodojodino** [comment]
I found this issue as well and I think I tracked down the place where this is occurring. I've added a PR for fixing this which changes the timing of the blacklist versus refreshing the token so that the blacklist occurs after the refresh token has been generated instead of blacklisting first invalidating the token.

How to replicate the issue:
set config jwt.blacklist_enabled = true
set config jwt.blacklist_grace_period = 0

1. Login and get a JWT token
2. wait for token to expire
3. hit route with jwt.refresh middleware attached
4. result is exception is thrown due to token being blacklisted.

Work around until fix available. Set the blacklist grace period to a value that is low so that the token even though invalidated by blacklisting is still valid for the refresh flow.

set config jwt.blacklist_grace_period = 5

Hope this helps others.

**Comment by tijanmdr** [comment]
This code gave me a valid token, without getting blacklisted
```$token = JWTAuth::parseToken()->refresh();```

Made my own middleware 
```
try {
    $user = JWTAuth::parseToken()->authenticate();
    app('auth')->setUser($user);
} catch (TokenExpiredException $e) {
    return response()->json(['success'=> 0, 'message' => 'Token Expired!','statusCode' => (int)401], 401);
} catch (TokenBlacklistedException $e) {
    return response()->json(['success' => 0, 'message' => 'Token Blacklisted!']);
} catch (TokenInvalidException $e) {
    return response()->json(['success' => 0, 'message' => 'Not Authorized!', 'statusCode' => (int)401], 401);
} catch (JWTException $e) {
    return response()->json(['success' => 0, 'message' => 'Not Authorized!', 'statusCode' => (int)401], 401);
}
return $next($request);
```

**Comment by tymondesigns** [comment]
This should be working as expected now
