### ISSUE TITLE
Remove custom claims

### ISSUE THREAD

**Issue by hfuccillo** [tymondesigns/jwt-auth#813]
I'm adding a custom claim like this: JWTAuth::fromUser($user, ['imp'=>$authenticated]);

How can I remove this custom claim? 
I try this: JWTAuth::fromUser($user, []); but it doesn't work. It still getting an 'imp' in payload 

Any ideas?
Thanks

**Comment by nhaarman** [comment]
Why is there even any state at all in a factory?

**Comment by hfuccillo** [comment]
Hi Niek, sorry I don't understand your question. I'm just asking how can I
remove a custom claim that was previously added.
Is my question clear enough?
Thanks!
