### ISSUE TITLE
Authentication - wiki page fix for laravel 5 route middleware

### ISSUE THREAD

**Issue by ratul0** [tymondesigns/jwt-auth#816]
I fix the wiki page for laravel 5 route middleware in Authentication page.

Here is the repo:

 https://github.com/ratulcse27/jwt-auth-wiki

you can review my changes and merge them in.

**Comment by johannesschobel** [comment]
You need to make a pull-request in order to get your changes merged

**Comment by feeekkk** [comment]
@johannesschobel I thought Github doesn't support PR's for wiki's though?

**Comment by johannesschobel** [comment]
I am sorry, you are right! Forking a repository on github only clones the _main_ repository, but not the _wiki repository_. My bad!
I think, it works on BitBucket though ;)

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
