### ISSUE TITLE
works like 1 out of 20 times.

### ISSUE THREAD

**Issue by atinder90** [tymondesigns/jwt-auth#82]
i have setup it as per wiki with Laravel 5, using jwt.auth middleware.

Token generates fine but when i try to use that token it always says token_invalid.

surprising thing is, it actually works sometimes.

**Comment by tymondesigns** [comment]
hmm strange.. I will see if I can reproduce

**Comment by tymondesigns** [comment]
could you try updating to `0.5.2` to see if it resolves it?

**Comment by tymondesigns** [comment]
should be fixed as of `0.5.3`
