### ISSUE TITLE
Authentication - JWT::attempt extension

### ISSUE THREAD

**Issue by dazza041** [tymondesigns/jwt-auth#833]
I've started using JWT auth for token based authentication, and wondered if its possible to only authenticate a user if they're verified or by another set of database fields?

Does JWT auth support this? Or do I need to write an extension myself?

**Comment by psychonetic** [comment]
As mentioned in the doku: https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens you can easily force the token to require more than the basic fields. Just add your fields and change the config to of jwt, so that your custom field is required.
