### ISSUE TITLE
Tymon - Are you going to maintain this package or not?

### ISSUE THREAD

**Issue by mariaczi** [tymondesigns/jwt-auth#835]
It's really long time since any updates.
@tymondesigns  - Are you going to maintain this package anymore?

**Comment by mtpultz** [comment]
There have been tons of updates, but you need to use the develop branch until the 1.0 release is official.  Develop contains the  new JWTGuard specific to Laravel 5.2+, which is great and though the wiki isn't up to date regarding the develop branch the community has posted wiki-like instructions on how to set it up for Laravel and Lumen.

**Comment by mariaczi** [comment]
What to change in composer?

czw., 25 sie 2016, 17:37 użytkownik Martin Pultz <notifications@github.com>
napisał:

**Comment by mtpultz** [comment]
Add this to composer:
"tymon/jwt-auth": "dev-develop"

And then you can read this post if you're using Laravel 5.2:
https://github.com/tymondesigns/jwt-auth/issues/513

If this helps then please close the issue.

**Comment by mariaczi** [comment]
Should I then replace

`Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class,`
With ` Tymon\JWTAuth\Providers\LaravelServiceProvider::class` ?

**Comment by mtpultz** [comment]
That post is for a clean install of Laravel 5.2 I think if you follow that post you'll find all your questions will be answered regarding setting up JWTGuard within Laravel, but yes the post indicates you need to change the provider.
