### ISSUE TITLE
Installing in Lumen 5.3

### ISSUE THREAD

**Issue by hpaknia** [tymondesigns/jwt-auth#841]
After taking more than 10 hours, it seems there is no way to install this module in Lumen 5.3. Has anyone installed this package in Lumen 3? Any tutorials?

**Comment by achiduku** [comment]
This tutorial states Lumen 5.2 but has worked perfectly for me on 5.3

P.s. don't forget to uncomment the AppServiceProvider in your bootstrap/app.php

https://iwader.co.uk/post/tymon-jwt-auth-with-lumen-5-2

**Comment by lukevear** [comment]
@hpaknia Was your issue similar to #843?

If so, feel free to try [this little package](https://github.com/lukevear/jwt-auth-guard) put together on Lumen 5.3 and see if that works for you. If it does please let me know so I can update the documentation to include Lumen installation instructions.

**Comment by tymondesigns** [comment]
@lukevear not sure if you are aware but this package *does* have a Guard implementation, although not documented just yet. via the [1.0.0 alpha releases](https://github.com/tymondesigns/jwt-auth/releases/tag/1.0.0-alpha.3).

[here it is in the flesh](https://github.com/tymondesigns/jwt-auth/blob/develop/src/JWTGuard.php)

**Comment by lukevear** [comment]
@tymondesigns Ha! Well that's fun! I did not see that at all (I've only been looking at `0.5.*`). I'll update my package incase someone is stuck on `0.5.*` for whatever reason), and update my code to use the `1.0.0-alpha` releases.

Cheers!

**Comment by hpaknia** [comment]
@lukevear I ended up with creating my own middleware (and my own middleware decodes received token using jwt-auth methods.

**Comment by mabasic** [comment]
Hi, I have written a lesson on getting this package working with Lumen 5.3 on my website [JSON Web Token Authentication for Lumen REBOOT](https://laravelista.com/lessons/json-web-token-authentication-for-lumen-reboot)

**Comment by paxku** [comment]
Hi all!

This lib saved me tons of time. Thanks a lot tymondesigns!

I did have some trouble setting up 1.0.0-beta.1 with Lumen 5.3, so I ended up deciding to write the steps down and create a repo with an example (all free as in beer).

You can check it out in http://www.akaita.com/post/json-web-token-authentication-for-lumen-5-tymon-jwt-auth 

Cheers!

**Comment by XcOdeTanzania** [comment]
@paxku Thank you very much for the share....
