### ISSUE TITLE
Laravel 5.3 Global exception handling not working

### ISSUE THREAD

**Issue by icodebuster** [tymondesigns/jwt-auth#848]
I am using `jwt-auth` with `Laravel 5.3`, carried out all the steps as per the wiki pages.
My problem is the global exception handling is not working, when I call an API with invalid token it is not following the  global exception added in 'app/Exceptions/Handler.php'

I need to customize the token related error json output as per my needs. In order to do that I have added some custom code in 'app/Exceptions/Handler.php'.

If I remove the middlewares the global exception works, does that mean I will have to make a custom middleware to handle auth and to customized json output.

Any help much appreciated :)

**Comment by RichardFans** [comment]
what version of jwt-auth do you use?

**Comment by icodebuster** [comment]
I am using, I would like to know a better way to manage custom json error

    "tymon/jwt-auth": "0.5.*"

I tried making a new middleware which is as follows.

    public function handle($request, Closure $next)
        {
            try {
                $user = JWTAuth::toUser($request['token']);
            } catch (Exception $exception) {
                if ($exception instanceof \Tymon\JWTAuth\Exceptions\TokenExpiredException) {
                    return ResponseHelper::error(Lang::get('apiresponse.tokenExpired'),     $exception->getStatusCode());
                } else if ($exception instanceof \Tymon\JWTAuth\Exceptions\TokenInvalidException) {
                    return ResponseHelper::error(Lang::get('apiresponse.tokenInvalid'), $exception->getStatusCode());
                } else {
                    return ResponseHelper::error(Lang::get('apiresponse.tokenInvalid'), $exception->getStatusCode());
                }
            }
            return $next($request);
        }

Which is working as expected. 
I am new to PHP/Laravel so any guidance would be really helpful.

**Comment by icodebuster** [comment]
@RichardFans any comments.

**Comment by icodebuster** [comment]
Update:
JWT-Auth works with Laravel 5.3 and by creating a custom middleware I was able to customize the JSON output.

**Comment by RichardFans** [comment]
maybe you should try  1.0.0 alpha3 , see #844

**Comment by victorrss** [comment]
I am using

```
"php": ">=7.0.0",
"fideloper/proxy": "~3.3",
"laravel/framework": "5.5.*",
"laravel/tinker": "~1.0",
"tymon/jwt-auth": "1.0.0-rc.1"
```

it worked here
Add the following code to the render method within app/Exceptions/Handler.php

```
public function render($request, Exception $e)
    {
        if($e instanceof \Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException){
            return response()->json([$e->getMessage()], $e->getStatusCode());
        }
        return parent::render($request, $e);
    }
```
