### ISSUE TITLE
[Question] Is there a way to invalidate all past tokens for a user?

### ISSUE THREAD

**Issue by shaljam** [tymondesigns/jwt-auth#849]
Think of the user lost his phone and application working with the token, how is it possible to invalidate the token stored on application? Does changing password have an effect?

**Comment by johannesschobel** [comment]
changing password does **not** have an effect. The token is still valid!
You need to invalidate the token - I don't think this is covered by this plugin (yet)..

**Comment by johannesschobel** [comment]
You may also take a look at #58 .. Might help you!?

**Comment by shaljam** [comment]
@johannesschobel I moved to another solution. Thanks anyway.

**Comment by johannesschobel** [comment]
What do you mean by "another solution"? Another package or another way to invalidate the token?

**Comment by shaljam** [comment]
@johannesschobel I'm using [Laravel Passport](https://laravel.com/docs/5.3/passport).
