### ISSUE TITLE
Impossible to verify if a token is blacklisted(invalid)

### ISSUE THREAD

**Issue by Maykonn** [tymondesigns/jwt-auth#85]
How to verify if a token is blacklisted? Or how to correct implement an user "logout"? I try to found on API but not exists a getToken()->isBlacklisted() or parseToken()->isBlacklisted(), and ever token is invalid parseToken() throws a TokenBlacklistedException, so an isBlacklisted method is a good way to verify if token is valid.

UPDATE:

If used the bellow code to verify if payload is invalid, throws the same exception:
```
if(false === \Tymon\JWTAuth\Blacklist::has(\Tymon\JWTAuth\Facades\JWTAuth::getPayload($token))) {
     \Tymon\JWTAuth\Facades\JWTAuth::parseToken()->invalidate();
}
```

**Comment by tymondesigns** [comment]
Thanks for the suggestion on adding a convenience method for that.. should be a helpful addition.

I expect you are using a middleware or filter, since, simply calling `parseToken()` will never throw a `TokenBlacklistedException`

**Comment by Maykonn** [comment]
In my tests no, but now I'm using. Thanks!
