### ISSUE TITLE
Using with Yii2

### ISSUE THREAD

**Issue by p4scu41** [tymondesigns/jwt-auth#854]
I have used your package with Laravel 5.3 and all ok. I would like to use it with Yii2, Is it possible?

**Comment by hpaknia** [comment]
I bet you've searched for yii2 jwt packages. Why don't you use one of them? This package has some issues even with Lumen!

**Comment by p4scu41** [comment]
I think this package is really simple and useful, thast why I love it, I found others but them don't have a friendly api and have some issues and aren't flexible

**Comment by hpaknia** [comment]
I believe If you understand the idea of JWT, then it's nothing more than 
```
$key = "example_key";
$token = array(
    "iss" => "http://example.org",
    "aud" => "http://example.com",
    "iat" => 1356999524,
    "nbf" => 1357000000
);
$jwt = JWT::encode($token, $key);
$decoded = JWT::decode($jwt, $key, array('HS256'));
print_r($decoded);
$decoded_array = (array) $decoded;
```
Take a look at: https://github.com/firebase/php-jwt
Also this package https://packagist.org/packages/damirka/yii2-jwt uses  firebase/php-jwt package.
