### ISSUE TITLE
token not provided only when token have custom claims

### ISSUE THREAD

**Issue by ahm-hossein** [tymondesigns/jwt-auth#859]
Hi, I have a weird  problem with jwt that when I add some custom claims to the token's payload the jwt middleware start to send back error that the token is not provided while the token is provided. but if I remove the claims payload everything works great. this is my authentication code :

![image](https://cloud.githubusercontent.com/assets/13381026/18878397/4bd29994-84dd-11e6-9227-986ad9b7c82d.png)

**Comment by hahmadicorp** [comment]
Obviously the problem is from custom claims that passed as second argument to the `fromUser` function. I checked the token when the token going to validate the token that validation taken on is different from the token that provided from http request.
