### ISSUE TITLE
Empty token with /? at end of url: myresource/?filters=myfilter:123

### ISSUE THREAD

**Issue by Maykonn** [tymondesigns/jwt-auth#86]
I'm getting a Tymon\\JWTAuth\\Exceptions\\JWTException with message: "The token could not be parsed from the request" when call a resource with this exact format: 

api.com/users/1/talks***/?***filters=with_user:19

If change talks/?filters to  talks***?***filters all works fine.

I capture the log info from request and Authorization header is empty when resource is called with ***/?*** at end of resource url.

**Comment by tymondesigns** [comment]
are you using apache?

**Comment by Maykonn** [comment]
Yes.

**Comment by Maykonn** [comment]
Is there any incompatibility with apache? I do not understand.

**Comment by tymondesigns** [comment]
Apache can sometimes strip the Authorization header.

see #81 and [here](http://stackoverflow.com/questions/11990388/request-headers-bag-is-missing-authorization-header-in-symfony-2)

**Comment by Maykonn** [comment]
Authorization token comes on request with .htaccess correction, but if has a ? on querystring Apache remove the token. Very very bizarre.

**Comment by tymondesigns** [comment]
I think in your case the trailing slash is affecting it. Not sure why that is happening..

You could add a rewrite rule to remove all trailing slashes I guess

**Comment by Maykonn** [comment]
Yes, is it. Thanks for help! =)

**Comment by tymondesigns** [comment]
:+1:
