### ISSUE TITLE
[Question] Integrating jwt-auth with roles and permissions route

### ISSUE THREAD

**Issue by cona88** [tymondesigns/jwt-auth#866]
Hi Everybody,
When using the Jwt-auth, I met the issue: the user logged in using Jwt-auth and then user go to the new route "/abc" this route need to permission (such as admin role) :
```
    Route::get('/abc', 'PagesController@abc');
```
Because user already loggin, so now how to check user's permission and role for this route?  My solution : check permission in "Controller" but it is not good solution.
Please help me the solution for this case.
Thanks.

**Comment by engAhmad** [comment]
Use middlware for that if the user authinticated you can check his role .

**Comment by cona88** [comment]
Hi @engAhmad ,
Can you give me the example?
Thank you

**Comment by engAhmad** [comment]
@cona88

https://scotch.io/tutorials/role-based-authentication-in-laravel-with-jwt

**Comment by cona88** [comment]
Thank @engAhmad .
