### ISSUE TITLE
TokenValidator validateStructure

### ISSUE THREAD

**Issue by yopop666** [tymondesigns/jwt-auth#869]
Hello! 
Thank you for great package. Why token string from **Tymon\JWTAuth\Validators\TokenValidator** class
**validateStructure** method must have exactly 3 segments. Can this validator be changed? How?

I want to use **JWTAuth::setToken($tokenString)** where $tokenString has just caracters witout any dots and validator give exception.

Thank you.

**Comment by johannesschobel** [comment]
A ```JWT``` must have 3 segments, which are connected using a ```.``` (dot). See [the official JWT site](https://jwt.io/) for the specificiation!
