### ISSUE TITLE
Token never Refresh

### ISSUE THREAD

**Issue by Maykonn** [tymondesigns/jwt-auth#87]
My route group:

```
Route::group(['before' => 'jwt.auth', 'after' => 'jwt.refresh']
```

But the token never is refreshed. Never entry in Tymon\JWTAuth\Middleware\RefreshToken.
My Kernel:
```
protected $routeMiddleware = [
    'jwt.auth' => 'Tymon\JWTAuth\Middleware\GetUserFromToken',
    'jwt.refresh' => 'Tymon\JWTAuth\Middleware\RefreshToken',
];
```

**Comment by Maykonn** [comment]
I change the group filter to ['middleware' => ['before' => 'jwt.auth', 'after' => 'jwt.refresh']] and now works. Isn't a bug. Sorry for this.

**Comment by Brave-Cheng** [comment]
@Maykonn ,It's not work with JWT-Auth in Laravel5.1. Please tell me how to fixed it
