### ISSUE TITLE
Error 400 Token not provided Safari

### ISSUE THREAD

**Issue by TSerra-PT** [tymondesigns/jwt-auth#873]
Hello,

I have a strange issue. I'm developing an aplication in Laravel 5.1 with jwt-auth and whether on Windows (Firefox/Chrome/Edge) or Linux (Firefox/Chrome) it works well. However when i test (one particular request) on Mac (Safari) it gives me this error -> _message: "Token not provided", status_code: 400_.
If i look to the header of my request, the _Authorization: Bearer_ isn't here (this is the reason of the error); but it is strange because whether on Windows or Linux this resquest works and _Authorization: Bearer_ is sent.

I try to follow this issue -> [#81](https://github.com/tymondesigns/jwt-auth/issues/81) ; Although i have .htaccess file like they said in issue.

If someone could help me, I would appreciate it! (this issue is blowing my mind)

**Comment by TSerra-PT** [comment]
Hello,

For future reference, I have a Get request with a slash in the end and it gave me a warning "301 - Moved Permanently". After this warning system calls other request without slash in the end.For example (1º request -> http://yoursite.com/api/users/ ; 2º request ->http://yoursite.com/api/users). And the "original" resquest is without slash
I receive response from the first request and error from second (he lose Authorization: Bearer). So to resolve my issue i put my system calling the "orginal" request (without slash in the end).

**Comment by ratatatKE** [comment]
I am also having a huge issue with this on Safari alone.
