### ISSUE TITLE
How to integrate JWT auth in Lumen 5.3?

### ISSUE THREAD

**Issue by prashantidealittechno** [tymondesigns/jwt-auth#876]
I am trying to integrate the JWT Auth in Lumen 5.3, Is their any way we can implement it? I try some tutorials but did not see any tutorial for Lumen 5.3.

**Comment by krisanalfa** [comment]
Hey, @prashantidealittechno, maybe you want to check [this](https://github.com/krisanalfa/lumen-jwt) out.

**Comment by larsbo** [comment]
@prashantidealittechno Same problem here. I tried this tutorial: 
https://iwader.co.uk/post/tymon-jwt-auth-with-lumen-5-2
(It's for Lumen 5.2 but I think that's not a problem. You must use the 1.0.0 alpha release of tymon/jwt-auth. 

So far I got this: The jwt token generation works but calling any protetected route with authorizisation header results in a "Unauthorized" response.
