### ISSUE TITLE
Problem when using with mongodb driver.

### ISSUE THREAD

**Issue by robsoncombr** [tymondesigns/jwt-auth#88]
Hello,

I use MongoDB as database on my Laravel 5 application, implemented with https://github.com/jenssegers/laravel-mongodb

While trying to implement tymondesigns/jwt-auth on my project, based on demo https://github.com/ttkalec/laravel5-angular-jwt I had some problems, related with User retrievement, I resolved all problems, however, I would like someone more experienced colleague could bless my changes, if possible.

Also, it would be nice to change the way jwt-auth reads the User model while retrieving, I had no problem during registration and login, however, I had problems to retrieve it (especifically: JWTAuth.php, toUser function)

Let me show you what I changed, to have it work, that will also clarify:

1) installed: jenssegers/laravel-mongodb

2) changed App\User.php, to extend Jenssegers\Mongodb\Model instead of Illuminate\Database\Eloquent\Model;
     - I think this should be enough to have jwt-auth working, for example I got no error to register the user, only to retrieve it, continuing...

3) JWTAuth toUser() returns false, so I did the following changes to fix:

a) JWTAuth.php - toUser():
        //if (! $user = $this->user->getBy($this->identifier, $payload['sub'])) {
        if (! $user = \App\User::find($payload['sub'])) {
b) EloquentUserAdapter.php:
        //use Illuminate\Database\Eloquent\Model;
        use Jenssegers\Mongodb\Model;
c) EloquentUserAdapterTest.php:
        //$this->builder = Mockery::mock('Illuminate\Database\Query\Builder');
        $this->builder = Mockery::mock('Jenssegers\Mongodb\Query\Builder');
        //$this->model = Mockery::mock('Illuminate\Database\Eloquent\Model');
        $this->model = Mockery::mock('Jenssegers\Mongodb\Model');

Now, it works perfectly, I'm not sure it is secure or if the changes I did are really correct, I'm not a senior programmer, however, I worked with other packages, that just accept the User model I'm using and assume it for everything, avoiding any problem.

I will be very happy to hear thoughts, ideas, etc.

Thank you very much for the attention here.

Robson

**Comment by robsoncombr** [comment]
Hello,

I just found an identifier field to be changed on config/jwt.php

I changed:
    //'identifier' => 'id',
    'identifier' => '_id',

Since MongioDB uses _id and not id, and it worked.

So, discard the mentioned change 'a'
a) JWTAuth.php - toUser():
//if (! $user = $this->user->getBy($this->identifier, $payload['sub'])) {
if (! $user = \App\User::find($payload['sub'])) {

It is not needed, I changed it back to original and it worked after I fixed the identifier.

I will post new findings...

**Comment by robsoncombr** [comment]
Hello,

I also reverted all mentioned changes to original, and everything worked perfectly!

So, it was my fault, I forgot to change the identifier and that is why it was not findings the User.

Closing this issue, thank you!

**Comment by paulocoghi** [comment]
I have changed the identifier to `_id` and, still, when I applied the `jwt.auth` middleware it returns the `user_not_found` exception.
