### ISSUE TITLE
jwt.refresh not working from cross origin request

### ISSUE THREAD

**Issue by mvaliolahi** [tymondesigns/jwt-auth#881]
i have some problem with this library, when i use it and test with POST-MAN everything work  but when i want to use my api from other origini have 2 problem:

1) from angular 2 side i make request but refresh middleware dos not work and header has not token,
2) if i pass a token because refresh dos not work is valid for every request.

---

in fact i write a larave api and want consume it from angular 2, my angular app is located in http://myapp.dev and my laravel api is located in http://api.dev

**Comment by Arkanius** [comment]
Try to add:

```
header('Access-Control-Allow-Origin:  *');
header('Access-Control-Allow-Methods:  POST, GET, OPTIONS, PUT, DELETE');
header('Access-Control-Allow-Headers:  Content-Type, X-Auth-Token, Origin, Authorization');
```

in your routes.php

Or you can create a middleware to add these headers.

**Comment by mvaliolahi** [comment]
thanks Arkanius, i use this header but my problem is not solved. in fact everything work in post-man but in cors refresh dos not work...!

**Comment by knox2** [comment]
have a look at this cors library  https://github.com/barryvdh/laravel-cors
