### ISSUE TITLE
Single sign on does not work in tymondesigns/jwt-auth package

### ISSUE THREAD

**Issue by plgautam** [tymondesigns/jwt-auth#883]
I used tymondesigns/jwt-auth package with angularjs .It works fine in that application for one of the domain.Satellizer package of angularjs help to send authorization header automatically.

But when i use the same package without angularjs it i am unable to send authorisation header and also i want to send same header in all subdomain to maintain sso.

right now i am getting "error : something is wrong" error when i use it without angularjs.

**Comment by morenDev** [comment]
How do you manage the token refresh stuff? By angular?

**Comment by plgautam** [comment]
@morenDev
I used laravel+angularjs in one application but i just want to use laravel and jwt package to handle single sign on across subdomains

**Comment by plgautam** [comment]
@morenDev
I will use laravel to refresh token

**Comment by plgautam** [comment]
@morenDev
Please let me know how to pass token generated in one subdomain across subdomains

**Comment by morenDev** [comment]
no clue((
I was curious about how to refresh the token, whether on backend or frontend
