### ISSUE TITLE
Error in refresh flow

### ISSUE THREAD

**Issue by chancezeus** [tymondesigns/jwt-auth#892]
Using the "dev-develop" version of this package I came across a bug. If I try to refresh a token (well within it's 2 week limit) it always errors with a TokenExpiredException. Tracing the reason I found that when the blacklist is enabled, the token is parsed using the "regular" (ie. non refresh) flow, this results in the token being validated as expired and the error thrown.

To resolve this on line 118 in the Manager the refreshFlow should already be enabled or the error caught as "not relevant" because if it is expired, it is blacklisted anyway.

**Comment by argentinaluiz** [comment]
I think with set refreshFlow = true before check blacklist

**Comment by argentinaluiz** [comment]
This related in other issues

**Comment by BasConijn** [comment]
This has been fixed in the latest develop, however you can refresh of an blacklisted token.
Created pull request to fix this.

**Comment by argentinaluiz** [comment]
Exact!! @tymondesigns said!! Thanks @BasConijn!!

**Comment by surinderpalsingh** [comment]
I've installed dev branch and getting this error while publishing. 


Here is my composer entry ``` "tymon/jwt-auth": "^1.0@dev"```

[Symfony\Component\Debug\Exception\FatalErrorException]   Class 'Tymon\JWTAuth\Providers\JWTAuthServiceProvider' not found 

Please help me out. I'm stuck here.

**Comment by BasConijn** [comment]
You need to add it to your providers list, see the Wiki.

**Comment by surinderpalsingh** [comment]
[Wiki](https://github.com/tymondesigns/jwt-auth/wiki/Installation) is bit old.  On emust use ```Tymon\JWTAuth\Providers\LaravelServiceProvider::class``` instead of ```Tymon\JWTAuth\Providers\JWTAuthServiceProvider```  and  executre following command in the console

`php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LaravelServiceProvider"`
`php artisan jwt:secret`
