### ISSUE TITLE
Invalidating token error

### ISSUE THREAD

**Issue by Mapamatician** [tymondesigns/jwt-auth#894]
I am building iOS with Swift 3 with a Laravel 5.3 backend running on a live server with SwiftKeychainWrapper to store jwt and JWTDecode to decode them.

In iOS I can log the user in and I can call if jwt.expired to check for the expiration .. but I cannot figure out how to invalidate the token when the user logs out.

I have searched through the forms and cannot find a solution. 

In Laravel I have tried 

    public function logout() {

        JWTAuth::invalidate();
        Auth::logout();
        return;
    }

    public function logout() {
        $token = JWTAuth::getToken();
        if ($token) {
            JWTAuth::setToken($token)->invalidate();
        }
    }

logout () {
       Auth::guard($this->getGuard())->logout();
}

logout () {
        $token = JWTAuth::getToken();
        JWTAuth::invalidate($token);
}
This last one returns  {"error":"token_invalid"}

Can anyone tell me how to invalidate the token please?

**Comment by Mapamatician** [comment]
*facepalm*
forgot to change
```
self.logout.isEnabled = false
self.login.isEnabled = true
```
during logout 
Code works fine.

**Comment by Mapamatician** [comment]
I thought it was a matter of changing the buttons but when I fire 
```
    public function logout() {
        $token = JWTAuth::getToken();
        return JWTAuth::invalidate($token);
    }
```
I am still getting  `A token is required` with status code 500

**Comment by BasConijn** [comment]
Do you have the blacklist enabled in the config?

I am using the new JWTGuard and call it like this:
```
    public function logout()
    {
        $this->guard()->logout(); // pass true to blacklist forever
    }
```
That logout functions calls the following code.
```
    public function logout($forceForever = false)
    {
        $this->requireToken()->invalidate($forceForever);

        $this->user = null;
        $this->jwt->unsetToken();
    }
```

**Comment by Mapamatician** [comment]
Update:
Removing the invalidated token from the keychain worked
