### ISSUE TITLE
[sticky] [poll] Premium Laravel API Boilerplate Interest?

### ISSUE THREAD

**Issue by tymondesigns** [tymondesigns/jwt-auth#898]
Hey peeps..

So I thought I'd give everyone a quick update on things.

I'm close to releasing the long awaited `v1.0.0` release. I just need to finish the documentation.
And I'm going to push out the beta version very soon.

I will then tackle the backlog of issues (Sorry for my absence there!)

-------------------

For the last couple of weeks, I've been working on a boilerplate type project, which is a Laravel 5.3 app with everything you would need to get up and running with an api. 

Some of the features (at the moment) include:

- Full User authentication setup with JWT powered login, logout, refresh, user activation, password reset etc.
- Complete User registration system via credentials and OAuth social providers.
- [JSON API](http://jsonapi.org) like structured responses.
- Separate admin endpoint with permissions, useful to build admin interfaces.
- Eloquent Repositories with caching support
- Out of the box test suite
And lots more to come..

This would be a premium offering and so would have a small charge associated with it. 
I'm just trying to get an idea if anyone would be interested in purchasing such a thing?

It's early days and there are lots more features to think about, and how I would package it up.

Thoughts? 😃

**Comment by faresite** [comment]
I definitely would be interested, and I do like the idea of it being premium as that gives it more chance to stay maintained... GitHub is now full of old and unmaintained boilerplates. So yes, please! 🙂

**Comment by earnaway** [comment]
Would you consider something similar for Lumen 5.3 as well?
