### ISSUE TITLE
Refresh action should also check if the token is expired

### ISSUE THREAD

**Issue by stueynet** [tymondesigns/jwt-auth#899]
When you use the refresh middleware, it only seems to check if the refresh_ttl has past but does not check if the token has expired. SO for example if I issue a token that expires in 1 minute, but can be refreshed anytime within a week, if I try to refresh after 5 minutes, I will get a refreshed token that expires in 1 minute. Shouldn't that refresh fail if the token expired? So the refresh first checks the validity of the token and the tokens exp. Then if that is good AND the refresh_ttl is ok it will issue the refreshed token.

I can deal with this by putting auth middleware on the same routes but something seems off about it.

**Comment by tymondesigns** [comment]
This is actually expected behaviour (by default). When the `refreshFlow()` is set internally it does not check the token `exp` vs the `ttl`, instead it checks it against the `refresh_ttl`, meaning the token can be refreshed successfully if it is within the specified `refresh_ttl`, but has expired as per the `ttl` value.

If this is undesirable then you could set the `refresh_ttl` to the same value as the `ttl` and it should then only allow tokens to be refreshed within the standard `ttl` value.

Does that make sense?

**Comment by stueynet** [comment]
Here is the issue. If you are trying to achieve a secure token flow you want the exp to be relatively short. So if the token gets compromised, there is only a short window to try and refresh it. The refresh_ttl requires a new authentication (login) from the user if it is expired. You don't want that to be say 15 min because the user would need to keep re-authenticating with their credentials. So at two weeks it's more feasible because chances are the user will not be carrying a token that old as your app or website would have flushed it in some way by then. 

So I solve this by adding auth to the route and it effectively does the same thing. I think the way you have it out of the gate is fine. It just doesn't really fit our specific requirements for a short validation period but a long refresh period. 

The other benefit of requiring a valid token is that you don't really need a blacklist. Because you can have a really short expiry time and a long refresh time. If a toke is compromised the attacker only has a very short window. After the 5 min, that token is effectively useless anyway if they have successfully refreshed in time and continue to do so every 4 min. Moreover you can have a security feature in the account that can lock the account for 5 min rendering any outstanding tokens useless. So again no blacklist needed. But again this is solved by requiring auth before refreshing the token. 

Thanks for the response!
