### ISSUE TITLE
lumen

### ISSUE THREAD

**Issue by devmark** [tymondesigns/jwt-auth#91]
hello tymon, any plan for lumen? 

thanks

**Comment by tymondesigns** [comment]
Don't have anything specifically in mind.

Although I guess it could be useful to have a lumen installation running exclusively as an authentication server for issuing and revoking JWT's etc..

I'm open to any ideas though!

**Comment by emars** [comment]
Is it possible to use this package with Lumen as is?

**Comment by devmark** [comment]
it is possiable to do it, bcz tymod got a custom token function, so need to  remove "auth" function for lumen

**Comment by calebeaires** [comment]
Have someone used this with lumen?

**Comment by iolson** [comment]
Would love to see some code of this implemented into Lumen for User Auth and other auth methods.

**Comment by forgottencreature** [comment]
Would also appreciate this.

**Comment by tymondesigns** [comment]
Usage should be the same... You will just need to enable auth in lumen first - http://lumen.laravel.com/docs/authentication

**Comment by tymondesigns** [comment]
Next version (`0.6.*`) will have more considered lumen support

**Comment by osteel** [comment]
- Manually copy `vendor/tymon/jwt-auth/src/config/config.php` to `app/config/jwt.php` (and make changes in there as necessary)
 - Create `app/Providers/CustomJWTAuthServiceProvider.php`:

````
<?php

namespace App\Providers;

use Tymon\JWTAuth\Providers\JWTAuthServiceProvider;

/**
 * All we do here is forcing the JWTAuthServiceProvider to take
 * our custom config as the only config (force Lumen compatibility,
 * basically).
 */
class CustomJWTAuthServiceProvider extends JWTAuthServiceProvider
{
    /**
     * Boot the service provider.
     */
    public function boot()
    {
        $this->app['config']->set('jwt', require realpath(__DIR__ . '/../../config/jwt.php'));

        $this->bootBindings();

        $this->commands('tymon.jwt.generate');
    }
}
````

 - Install the `illuminate/routing` package:

````
$ composer require illuminate/routing
````

 - In `bootstrap/app.php`, register `App\Providers\CustomJWTAuthServiceProvider` instead of `Tymon\JWTAuth\Providers\JWTAuthServiceProvider`:

````
$app->register(
    'App\Providers\CustomJWTAuthServiceProvider'
);
````

That should do it.

**Comment by balintant** [comment]
@osteel, Works like charm! Thanks!

**Comment by KennedyTedesco** [comment]
@tymondesigns You are doing an amazing job here! Congrats! :) Did you have any idea about how to implement "JWT as a Service" (like you said before, running exclusively as an authentication server for issuing and revoking tokens etc) with Lumen?

**Comment by hopewise** [comment]
@osteel many thanks
