### ISSUE TITLE
JWTAuth::toUser Not Working Properly

### ISSUE THREAD

**Issue by animationatul** [tymondesigns/jwt-auth#910]
>   
>              try {
>             Config::set('auth.providers.users.model','App\Admin');
>             if (! $token = JWTAuth::attempt($credentials)) {
> 
>                 return $this->errorUnauthorized("Invalid Credentials");
>             }
> 
>             $user = JWTAuth::toUser($token);
>             dd($user->name);

This code return false why this is not working please help !!!

**Comment by animationatul** [comment]
How to convert token to user Details Kindly Help some time it works sometime it doesn't work

**Comment by samthomson** [comment]
In your config/jwt.php file set user to 'App\Admin' or whatever user model you're using. Worked for me.

**Comment by shijisaroop** [comment]
Hi ,

In my authenticated routes in controller, i am not able to fetch the user details from bearer token. 
I am working with latest lumen -> 5.8 and tymon/jwt-auth->1.0.0-rc.4.1
I have tried the following,
JWTAuth::toUser(JWTAuth::getToken());//token is valid .Also tried to pass the bearer token from request header
@tymondesigns

**Comment by saurabhshukla123** [comment]
// Login for user
    public function login(Request $request)
    {
        $input = $request->only('email', 'password');
        $jwt_token = null;
        if (!$jwt_token = JWTAuth::attempt($input)) {
            return $this->responseHelper->error(
                Response::HTTP_UNPROCESSABLE_ENTITY,
                Response::$statusTexts[Response::HTTP_UNPROCESSABLE_ENTITY],
                config('constants.error_codes.ERROR_USER_INVALID_DATA'),
                trans('messages.custom_error_message.INVALID_USERID_OR_PASSWORD')
             );
        }
        $apiData = ['user_token' => $jwt_token];
        $apiStatus = Response::HTTP_CREATED;
        $apiMessage = trans('messages.success.MESSAGE_USER_LOGGEDIN_SUCESSFULLY');
        return $this->responseHelper->success($apiStatus, $apiMessage, $apiData);
    }

//in middle ware 
  public function handle($request, Closure $next)
    {
        try {
            $user = JWTAuth::toUser($request->input('token'));
            // dd($request->input('token'));
        } catch (JWTException $e) {
            if($e instanceof \Tymon\JWTAuth\Exceptions\TokenExpiredException) {
                return response()->json(['token_expired'], $e->getStatusCode());
            }else if ($e instanceof \Tymon\JWTAuth\Exceptions\TokenInvalidException) {
                return response()->json(['token_invalid'], $e->getStatusCode());
            }else{
                return response()->json(['error'=>'Token is required']);
            }
        }
      return $next($request);
    }

I think this would be usefull for you.

**Comment by saurabhshukla123** [comment]
In user controller dont forget to enter below code:

  public function getJWTIdentifier()
    {
        return $this->getKey();
    }

 public function getJWTCustomClaims()
    {
        return [];
    }

it would work for you
