### ISSUE TITLE
Upgrading namshi/jose to 7?

### ISSUE THREAD

**Issue by jamesgraham** [tymondesigns/jwt-auth#923]
We would love to use your library but cannot due to it conflicting with other libraries requiring phpseclib @ v2.

namshi/jose is fixed at v5 which is the problem. Can this be upgraded to 7?

**Comment by tymondesigns** [comment]
this has been resolved on the newer versions of this package (`1.0.0*`). docs coming soon

**Comment by jamesgraham** [comment]
That's great but do you know when they might be stable?
