### ISSUE TITLE
Improved JTI generation

### ISSUE THREAD

**Issue by kristijorgji** [tymondesigns/jwt-auth#924]
If 2 requests are made within the same second and blacklist is enabled the refreshtoken middleware returns back a blacklisted token (jti is the same as the token that was just blacklisted before being refreshed because nbf field and subject_id are the same). I fixed this by changing the jti generation code in PayloadFactory.php file from

```
 protected function jti()
    {
        $sub = array_get($this->claims, 'sub', '');
        $nbf = array_get($this->claims, 'nbf', '');

        return md5(sprintf('jti.%s.%s', $sub, $nbf));
    }
```

to 

`        return md5(sprintf('jti.%s.%s.%s', $sub, $nbf, microtime()));`

By appending microtime before hashing we allow more then 1 request to be made per second while blackilst is enabled. Please add this change to your original package so we can use composer again.

**Comment by tymondesigns** [comment]
This has been fixed in the `1.0.0*` prereleases. Not far of being released

**Comment by kristijorgji** [comment]
Perfect, and great library by the way very good job. When will the new version be released? Is there any place where I can see the prereleases

**Comment by tymondesigns** [comment]
Yea check out the releases here - https://github.com/tymondesigns/jwt-auth/releases

**Comment by tymondesigns** [comment]
Not got a final date yet
