### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by sirsquall** [tymondesigns/jwt-auth#929]
Hello,

I'm using jwt-auth for a while now, thank you a lot for this beautiful package :), I wanted to know, if is possible to retrieve a list of current active users ?

Thanks

**Comment by johannesschobel** [comment]
Hey @sirsquall ,

unfortunately, I do not know, if there is some kind of way to _reverse-engineer_ the token and retrieve the users' information from this data..

However, what could be some kind of work-around..
You can write your own Laravel `Middleware` (Docs)[https://laravel.com/docs/5.1/middleware], extract the user from the token (e.g., using `JWTAuth::attempt($credentials);`) and then flag the user in an `is_active` field in the database. Furthermore, you need to store the `last_active_at` timestamp...

If you want to check, if respective user is online, simply check, if the `last_active_at` timestamp is within the `config('jwt.ttl')` range (e.g., a token is valid for 60minutes).

This is, obvioulsy, not the best approach, but maybe it helps!?
Cheers

**Comment by sirsquall** [comment]
Hello @johannesschobel,

Good idea, I had exactly the same, and I started doing like this, but after I changed my mind, and I used Google Analytics, it's more convenient for real-time dashboard.


Thanks

**Comment by johannesschobel** [comment]
Hey @sirsquall ,
nice idea of using google analytics for this use-case. However, this might not be applicable in specific scenarios. For example, you may need to give google analytics access to your API.

Cheers
