### ISSUE TITLE
Deleted config/jwt.php but still can generate token

### ISSUE THREAD

**Issue by shankerm** [tymondesigns/jwt-auth#949]
Hi, I had some issues with the token's signature. After attempting a number of things, i totally removed the jwt.php file in config folder. I attempted to login via postman and authenticate my user hoping to see some errors. Shockingly no error was reported and i still received a token. I even cleared cache and config cache but nothing happened. How can this be? Thanks.

**Comment by johannesschobel** [comment]
that is, because the default `jwt.php` config file from the `package` itself is used. This file is stored in the `vendor` folder (e.g., `\vendor\tymon\jwt-auth\src\config\jwt.php`

Cheers
