### ISSUE TITLE
Multiple concurrent api calls with refresh token enabled

### ISSUE THREAD

**Issue by reshadman** [tymondesigns/jwt-auth#95]
First of all thanks for great high quality package you have made.

The idea of refreshing an access token and adding the old one imidiately to the blacklist may cause some problems when the api is used by many concurrent requests with same token.
The problem is that when the first request is sent with the JWT named A it is refreshed with the new B one, the second call is concurrently performed with the same token(A) but the first one has added A to the black list which will cause problems, I think keeping the token valid for some further seconds may solve the problem.

**Comment by reshadman** [comment]
I Also made a [PR](https://github.com/reshadman/jwt-auth/commit/ef7b25e1fe5a53e6947e5ab67ddf5f442da60301) for this.

**Comment by Ascanius** [comment]
+1 on this feature, would greatly enhance this package.

**Comment by marijang** [comment]
+1

**Comment by mattmcdonald-uk** [comment]
+1

**Comment by tymondesigns** [comment]
I have pushed a draft of this up on the develop branch.

Thanks @reshadman

**Comment by mehrdaad** [comment]
Hi, I was thinking of this feature. which found this thread.
I checked the source of projetc but commit of @reshadman hasn't been pushed to the project.  
why?! How can I add it manually?

**Comment by marcoshenriqueb** [comment]
+1
