### ISSUE TITLE
How to store logged in user id in database while filling a form Not register form.  

### ISSUE THREAD

**Issue by leezene** [tymondesigns/jwt-auth#950]
![error](https://cloud.githubusercontent.com/assets/20589958/21879174/ec333fa8-d8be-11e6-85e7-a3cf3c9d232a.PNG)
![controller](https://cloud.githubusercontent.com/assets/20589958/21879048/531da178-d8be-11e6-9c67-167e94e4e581.PNG)
![model](https://cloud.githubusercontent.com/assets/20589958/21879049/53204130-d8be-11e6-9058-d01eb302ef95.PNG)
![table](https://cloud.githubusercontent.com/assets/20589958/21879050/534c7322-d8be-11e6-8dec-a3fddd6cc011.PNG)

**Comment by tymondesigns** [comment]
Closing old issues. If still an issue please re-open
