### ISSUE TITLE
Token still valid after the user logs in again

### ISSUE THREAD

**Issue by knox2** [tymondesigns/jwt-auth#951]
The token seems to be valid and usable even after the user logs in and obtains another token. This happens during testing when using postman

**Comment by blakethepatton** [comment]
You may want to familiarize yourself with [how JWT's work.](https://en.wikipedia.org/wiki/JSON_Web_Token#How_it_works) Once a user successfully signs in, their token is generated and stored in the browser. This token authorizes them to do whatever they are allowed to do. Creating another token is just going to create another token that has access to the same stuff. If you are trying to sign out then you need to delete the token from the users' browser or update it to have an expiration that has already passed.

**Comment by knox2** [comment]
Thanks, I solved it by setting expiration times and refresh tokens
