### ISSUE TITLE
Manipulate dynamically the refresh_ttl

### ISSUE THREAD

**Issue by SolidXnake** [tymondesigns/jwt-auth#962]
Dear partner,

I would like to know if there is a way to set dynamically the refresh_ttl, Im developing a web app that would be perfect if exists a way to deliver tokens with differents refresh_ttl depending on a role of a specific user

**Comment by rajathans** [comment]
you can use `Config::set('jwt.refresh_ttl', 700)` to dynamically set the refresh_ttl value
