### ISSUE TITLE
How does jwt-auth return the JWT to the client? In the HTTP response header or body?

### ISSUE THREAD

**Issue by w5m** [tymondesigns/jwt-auth#965]
Hi there,

I'm hoping to use jwt-auth in Laravel 5 in the near future. I need to know the means by which jwt-auth sends the JWT back to the client within the HTTP response, but I'm struggling to find any information on this.

Does jwt-auth utilise the Authorization header in the HTTP response? Or is the JWT embedded in the HTTP response body?

I'm trying to write a client, so I need to know where to find the returned JWT so that I can store it and send it with subsequent HTTP requests made to the server.

Any information would be much appreciated. Thanks in advance.

**Comment by feeekkk** [comment]
Return it from your server however you want to return it.. This is a library, you can implement it how you please.

**Comment by knox2** [comment]
You return it however you please....

```
use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;

class AuthenticateController extends Controller
{
    public function authenticate(Request $request)
    {
        // grab credentials from the request
        $credentials = $request->only('email', 'password');

        try {
            // attempt to verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->json(['error' => 'invalid_credentials'], 401);
            }
        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return response()->json(['error' => 'could_not_create_token'], 500);
        }

        // return it as a response on the body
        return response()->json(compact('token'));
       // or on the header
       return response('Hey', 200)->header('Authorization','Bearer '.$token);
    }
}
```
