### ISSUE TITLE
Ability to expire all user tokens

### ISSUE THREAD

**Issue by reshadman** [tymondesigns/jwt-auth#97]
Sometimes it is needed to invalidate all tokens of a user. for example when the password is changed. 

This requires to store each token in an storage with an expiration time equal to the token exp time. 

What is your idea ?

**Comment by jfadich** [comment]
You could accomplish the same thing without storing tokens on the server by appending the secret with the users hashed password. That way if the password changed the tokens should automatically invalidate. Of course this would only be useful if password changes were the only event you want to invalidate on

I would be happy to implement this but before I do I would defer to @tymondesigns to see if this is something he wants to include and if so, if this is the approach he wants to take.

**Comment by markmooibroek** [comment]
I would be happy to see this feature implemented. My use-case is the same: Invalidate all tokens based on password change.

**Comment by MPJHorner** [comment]
@reshadman Why not have something that updates the secret, that would make them all expire no?

**Comment by jfadich** [comment]
@MPJHorner This issue is related to individual user tokens, not site wide. If we just updated the secret then all tokens would be invalidated whenever a single user changed their password. Obviously that would be a user experience nightmare because it would force users to reauthenticate frequently and unpredictably with no explanation.

**Comment by alsofronie** [comment]
The purpose of the JWT token is to make an auth mechanism independent from the user model. That's why we use this. If you want the functionality you suggest, just use database to store a login token and authenticate the user based on that token. It's simpler and you can use the same headers.

**Comment by kenpeter** [comment]
@jfadich, I assume we don't want to append the secret with users hashed password?

"You could accomplish the same thing without storing tokens on the server by appending the secret with the users hashed password. That way if the password changed the tokens should automatically invalidate. Of course this would only be useful if password changes were the only event you want to invalidate on. It would also make this package more dependent on the user model.

I would be happy to implement this but before I do I would defer to @tymondesigns to see if this is something he wants to include and if so, if this is the approach he wants to take."
