### ISSUE TITLE
How to handle the login/token inside another laravel installation

### ISSUE THREAD

**Issue by Cannonb4ll** [tymondesigns/jwt-auth#973]
I started with this API inside Laravel, another Laravel frontend installation should be able to login to this Laravel API, but im not really sure how to handle this the right way.

My setup is like this:

Laravel API -> receives POST login -> returns a token and a user model -> Laravel frontend receives this data

But then what? How would I 'auth' the right way inside the Laravel frontend part?

Just set my own sessions and check that way? Any suggestions would be nice! :)

**Comment by rajathans** [comment]
keep that token in local storage and send it in request header every time
