### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by voinearob** [tymondesigns/jwt-auth#974]
Hello,

Please add support for the latest version of Laravel.

Thanks.

**Comment by jerguslejko** [comment]
+1

**Comment by jackkitley** [comment]
> php artisan optimize
PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::share() in /Applications/XAMPP/xamppfiles/htdocs/projects/ford_approved/vendor/tymon/jwt-auth/src/Providers/JWTAuthServiceProvider.php on line 132

                                                                       
  [Symfony\Component\Debug\Exception\FatalErrorException]              
  Call to undefined method Illuminate\Foundation\Application::share()


Solution: Use of the singleton method. Share has been removed.

        $this->app['tymon.jwt.generate'] = $this->app->share(function () {
            return new JWTGenerateCommand();
        });

becomes

        $this->app->singleton('tymon.jwt.generate',function () {
            return new JWTGenerateCommand();
        });

**Comment by imagine10255** [comment]
Hi, Try this is success

http://stackoverflow.com/questions/41853751/tymon-jwt-auth-laravel-5-4-error

**Comment by voinearob** [comment]
@tymondesigns Now with beta.2 out, support was added. Thank you very much Mr. Tymon!
