### ISSUE TITLE
Changes in required_claims configuration variable are not being reflected

### ISSUE THREAD

**Issue by yunidbauza** [tymondesigns/jwt-auth#98]
Hi Tymon,

Not sure what's happening but after changing the **required_claims** variable to this:
`'required_claims' => ['sub','iat','exp'],`
and verifying the generated token using [jwt.io](http://jwt.io), I'm still seeing all claims there:
```json 
{
  "sub": 1,
  "iss": "http://localhost/mysite",
  "iat": "1429603997",
  "exp": "1429607597",
  "nbf": "1429603997",
  "jti": "fac0c94350476a8aecd4164e90a1c4fa"
}
```
I verified if for some reason it was not reading the published configuration (config/jwt.php). In the config file I changed the identifier to a different field: `'identifier' => 'username',` and I could see the changes in the generated token:
```json 
{
  "sub": "superadmin",
  "iss": "http://localhost/mysite",
  "iat": "1429603997",
  "exp": "1429607597",
  "nbf": "1429603997",
  "jti": "fac0c94350476a8aecd4164e90a1c4fa"
}
```
It means the configuration file is read but somehow is ignoring my changes in the **required_claims** array.

I'm generating the token by simply calling the attempt method:
```php
$credentials = $request->only('username', 'password');
...
if (! $token = JWTAuth::attempt($credentials)) {...}
```

**Comment by tymondesigns** [comment]
Hi @yunidbauza 

The required claims in the config simply dictate what claims must be present in the payload and not what is added to the payload by default I'm afraid.

To change what is included in the payload you would have to manually build the payload, using the PayloadFactory, as described [here](https://github.com/tymondesigns/jwt-auth/wiki/Creating-Tokens#creating-a-token-based-on-anything-you-like)

Hope that helps
