### ISSUE TITLE
Vendor publish command returns "Nothing to publish for tag []" in Lumen

### ISSUE THREAD

**Issue by ricksonchew** [tymondesigns/jwt-auth#992]
Hi, I am using the 1.0 dev version of this `"tymon/jwt-auth": "^1.0@dev",` and notice that it is not creating a jwt.php config upon vendor publishing using this command `php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\LumenServiceProvider"`. Was able to do this using Lumen 5.3.*. It just returns a message of "Nothing to publish for tag []".

In order to run the vendor publish, you must install the lumen-vendor-publish package on your composer.

Did a "quick fix" by adding this line on the `src/Providers/LumenServiceProvider.php`
```
$this->publishes([
    __DIR__.'/../../config/config.php' => config_path('jwt.php'),
], 'config');
```

**Comment by rgehan** [comment]
`laravelista/lumen-vendor-publish` is the full package name. `lumen-vendor-publish` is abandoned and is not being installed
